### PR TITLE
Change log configuration to include timestamps in stdout

### LINKED ISSUE #2943: [RFE] Include timestamps in the output
# Version
Any

```console
$ openshift-install version
4.4.0-0.nightly-2020-01-17-050113
```

# Platform:
Any

# What happened?
Even if the logs contains the timestamp such as:

```
time="2020-01-17T10:39:47Z" level=debug msg="Still waiting for the cluster to initialize: Working towards 4.4.0-0.nightly-2020-01-17-050113: 99% complete"
```

The output doesn't:

```
DEBUG Still waiting for the cluster to initialize: Working towards 4.4.0-0.nightly-2020-01-17-050113: 99% complete
```

# What you expected to happen?
It would be nice to have the timestamps in the output to avoid opening the log to know for how long a task has been stuck in that step.

# How to reproduce it (as minimally and precisely as possible)?
Run an openshift installation

```console
$ openshift-install
```

# Anything else we need to know?
Nope

# References
 None

### PR DESCRIPTION
**Pull request by filanov**
Fixes #2943

### CODE REVIEW

**Comment by sdodson** [comment]
I'd lean towards not including timestamps in STDOUT, is the log file only getting timestamps in debug level or something odd like that?

**Comment by filanov** [comment]
> I'd lean towards not including timestamps in STDOUT, is the log file only getting timestamps in debug level or something odd like that?
No log file have the timestamp in any log level.

**Comment by jstuever** [comment]
I agree with Scott. Timestamps on STDOUT adds to an already crowded landscape. I'd be more willing to support this change if it was only affecting the log file.

**Comment by patrickdillon** [comment]
> No log file have the timestamp in any log level.

This is true. However, `.openshift_install.log` does have timestamps so you can `tail -f .openshift_install.log` during an install to achieve this functionality.

**Pull request closed without merging**
