### PR TITLE
Baremetal: Generate CR to configure baremetal.

### PR DESCRIPTION
**Pull request by imain**
Use a template to generate the baremetal config CR for use by the MAO
and the baremetal operator.

### CODE REVIEW

**Comment by stbenjam** [comment]
/cc @sadasu Can you have a look at this?

Any chance we could get a dev-scripts PR put together that pulls down this PR and MAO and tests them together, without the configmap hacks?

**Comment by metal3ci** [comment]
Build SUCCESS, see build http://10.8.144.11:8080/job/dev-tools/1437/

**Comment by stbenjam** [comment]
/assign @sdodson 

This is part of the implementation for https://github.com/openshift/enhancements/pull/119. The CRD was added to the MAO in https://github.com/openshift/machine-api-operator/pull/460. 

We now need the installer to write out a CR with values from our installation configuration. Currently, MAO reads this by a manually created config map, the goal here is to remove that entirely.

**Pull request merged**
