### PR TITLE
Bug 2016008: aws: add newly supported regions for arm64 

### PR DESCRIPTION
**Pull request by AnnaZivkovic**
This PR enables 3 regions for arm64:
eu-north-1
eu-west-3
me-south-1

m6g instances are now available in these regions: 
https://aws.amazon.com/about-aws/whats-new/2021/02/aws-graviton2-based-m6g-c6g-r6g-instances-available-additional-regions/

The boot images for all architectures have been bumped to accommodate this change

### CODE REVIEW

**Comment by miabbott** [comment]
It looks like this is also including PowerVS regions; is that intended?

Could you amend the commit message to include the bootimage bump BZ for 4.10 - https://bugzilla.redhat.com/show_bug.cgi?id=2016008

Also, please note in the commit message the dependent BZs on the bootimage bump which are fixed/delivered via this change.

For example - https://github.com/openshift/installer/pull/5280

The changes to the metadata look sane, but I would like to have a good paper trail via the commit messages.

**Comment by Prashanth684** [comment]
> It looks like this is also including PowerVS regions; is that intended?
> 
> Could you amend the commit message to include the bootimage bump BZ for 4.10 - https://bugzilla.redhat.com/show_bug.cgi?id=2016008
> 
> Also, please note in the commit message the dependent BZs on the bootimage bump which are fixed/delivered via this change.
> 
> For example - #5280
> 
> The changes to the metadata look sane, but I would like to have a good paper trail via the commit messages.

tagged Bug 2016008 for the bootimage bump and listed the associated dependent BZs. The coreos-assembler now has support for parsing IBMCloud and PowerVS metadata (https://github.com/coreos/coreos-assembler/pull/2535) and since we have PowerVS ova images being uploaded to IBMCloud, it gets included when we run the cosa2stream command, so it is intended. In any case nothing is being done with it for now until the support for the platform itself gets in.

**Review by miabbott — COMMENTED** [review]
/approve

**Pull request merged**
