### PR TITLE
Bug 2085187: terraform: revendor golang.org/x/sys

### PR DESCRIPTION
**Pull request by yselkowitz**
This is necessary for these providers to build for Mac with Go 1.18.

https://github.com/golang/go/issues/51706

### CODE REVIEW

**Comment by barbacbd** [comment]
Looks like the same versions were used from [#5865](https://github.com/openshift/installer/pull/5865)

**Comment by yselkowitz** [comment]
random: our version is behind, latest upstream version builds fine with 1.18
ignition: https://github.com/community-terraform-providers/terraform-provider-ignition/pull/19

**Comment by patrickdillon** [comment]
@yselkowitz your upstream ignition PR merged. Instead of revendoring x/sys locally can we bring in the new versions of these providers with the proper x/sys support?

**Comment by yselkowitz** [comment]
For ignition, no new version has been spun, but the revendoring would be the only upstream code change, so that still seems appropriate.  For remote, a rebase to v3.1.3 was more than I bargained for, but if you insist...

**Comment by sdodson** [comment]
@yselkowitz Do we ship builds built via this method or do we cross compile? Just trying to gauge urgency here.

**Comment by yselkowitz** [comment]
yes, this affects the build of installer-artifacts, which is currently behind installer and the rest of OCP as a result.

**Comment by patrickdillon** [comment]
> @yselkowitz Do we ship builds built via this method or do we cross compile? Just trying to gauge urgency here.

This is urgent. ART is currently making an exception to build installer with go 1.18 until we get this merged. Thanks @yselkowitz  for your work on this.

**Comment by yselkowitz** [comment]
@patrickdillon e2e-vsphere-upi passed

**Pull request merged**
