### PR TITLE
[fcos] Support Ignition3 and FCOS

### PR DESCRIPTION
**Pull request by vrutkovs**
Initial PR for OKD-on-FCOS installation.

* Switch to go modules so that Ignition spec3 implementation could be used.
  Note that I had to rip out Azure support as it was incompatible with terraform
* Point AWS images to FCOS official AMIs
* Run pivot from oscontainer early in the bootstrap process
  This increases install time but ensures the latest crio/podman/kubelet are used during bootstrap process so that Fedora would not have to maintain a new stream with openshift bits
* Force-enable Hyperthreading - see https://github.com/coreos/fedora-coreos-tracker/issues/181

TODO:
* [ ] Bring back Azure (can be postponed)
* [x] Update links in `rhcos.json` to point to Fedora CoreOS
* [x] Fix unittests and go vet (vendor things again?)

Nevermind the release image - these would be replaced later once Prow would generate a proper release.

cc @LorbusChris @smarterclayton

### CODE REVIEW

**Comment by vrutkovs** [comment]
>DaemonSet \"openshift-multus/multus\" is not available (awaiting 3 nodes)\nDaemonSet \"openshift-multus/multus-admission-controller\" is not yet scheduled on any nodes

/retest

**Comment by vrutkovs** [comment]
Oh, its not a flake though.

https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_installer/2548/pull-ci-openshift-installer-fcos-e2e-aws/11/artifacts/e2e-aws/pods/openshift-multus_multus-cfg2z_cni-plugins.log
>echo 'FATAL ERROR: Unsupported OS ID=fedora'

@squeed could we add Fedora OS support to multus DS in current master?

**Comment by squeed** [comment]
Neat. @dougbtv who you wanna talk to.

**Comment by vrutkovs** [comment]
Older MCO was picked up

/retest

**Comment by vrutkovs** [comment]
Waiting for CNO to be updated in release controller. The cluster got installed with a custom payload using this PR

**Comment by vrutkovs** [comment]
`error: Unknown name requested, could not find machine-config-operator in UpdatePayload`

**Comment by vrutkovs** [comment]
Setup passes, a few FCOS fixes are required to pass e2e tests

**Comment by vrutkovs** [comment]
port-forwarding tests are now fixed, waiting for fixed nfs-utils-coreos to land in FCOS testing-devel

**Comment by smarterclayton** [comment]
Consider this branch specific to fcos, is there a variant of this opened for all included commits for master?

**Comment by vrutkovs** [comment]
I don't think there is, I was syncing we'd do sync PRs from time to time

**Comment by smarterclayton** [comment]
So these commits are "throw away" and someone else will be doing ignition 3.0 and go.mod support?

**Comment by vrutkovs** [comment]
Its likely that these are throwaway, yes, if there is a better way to restructure the codebase.

At this point it doesn't make much sense to create PR back to master:
* Azure support is missing
* RHCOS + MCO need to switch to ign3 to make tests pass		
* https://github.com/openshift/enhancements/pull/97 is not yet finalized and accepted

**Comment by smarterclayton** [comment]
And go.mod?

**Comment by vrutkovs** [comment]
go.mod might make it into the master (this PR has both ign3 switch and go.mod, since ign3 requires go.mod). go.mod switch has broken Azure though, but I'm sure it can be sorted out

**Pull request merged**
