### PR TITLE
OCPBUGS-17806: gomod: bump openshift/api version

### PR DESCRIPTION
**Pull request by qJkee**
Bump openshift/api version with new capabilities

### CODE REVIEW

**Comment by wking** [comment]
[images][1]:

```
# github.com/openshift/installer/pkg/asset/machines/azure
pkg/asset/machines/azure/machines.go:95:28: cannot use nil as string value in assignment
pkg/asset/machines/azure/machines.go:256:26: cannot use az (variable of type *string) as string value in struct literal
```

and likely other changes are required to get this compiling again.

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_installer/7421/pull-ci-openshift-installer-master-images/1696605457889628160

**Comment by jianlinliu** [comment]
Hope we can get this PR landed into nightly builds, this feature is failing QE's testing mentioned in https://github.com/openshift/release/pull/42771

**Pull request merged**
