### PR TITLE
Update OpenStack spec dependencies

### PR DESCRIPTION
**Pull request by pierreprinetti**
The the OpenStack providerSpec for Machine has been moved to openshift/api.

Implements [OSASINFRA-2981](https://issues.redhat.com//browse/OSASINFRA-2981)

### CODE REVIEW

**Comment by pierreprinetti** [comment]
openshift/api was bumped with https://github.com/openshift/installer/commit/1dd74ca7a8bcd2978d056bf742e9cff409f5fbd0

**Comment by MaysaMacedo** [comment]
@pierreprinetti seems you need to run `go mod vendor` to update the vendor folder

**Comment by pierreprinetti** [comment]
/hold
this needs further work
/uncc mdbooth MaysaMacedo

**Comment by pierreprinetti** [comment]
Should be ready now.
/cc mdbooth MaysaMacedo mandre

**Comment by pierreprinetti** [comment]
Following the bot's suggestion:
/assign @jstuever

**Comment by pierreprinetti** [comment]
/retest-required
I'm not clear if we passed all the required tests.

**Comment by pierreprinetti** [comment]
/hold
This is not a bug; since Feature freeze is coming into effect, we can retarget to 4.13.

**Comment by pierreprinetti** [comment]
This is now ready to merge.
/hold cancel
/retest-required

**Comment by pierreprinetti** [comment]
[Two](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_installer/6382/pull-ci-openshift-installer-master-e2e-openstack/1591016554030436352/artifacts/e2e-openstack/openstack-gather/artifacts/openstack_nodes.log) errored instances on e2e-openstack :(

/test e2e-openstack
/retest-required

**Comment by pierreprinetti** [comment]
/test e2e-openstack
/hold cancel
We have a Kuryr job succeeding; I think we can remove the hold.

**Comment by pierreprinetti** [comment]
e2e-openstack's only failure is a know issue with Amphora LBs.
This would be ready to merge, if it wasn't for that completely unrelated failure with `e2e-vsphere-ovn`

**Comment by pierreprinetti** [comment]
@patrickdillon Any chance we can override ci/prow/e2e-vsphere-ovn?
The vsphere run gives good results, except for the tests that are permafailing everywhere.

**Pull request merged**
