### PR TITLE
Bug 1964751: Bump boot images for RHCOS fixes

### PR DESCRIPTION
**Pull request by ravanelli**
Changes generated with:
```
python update-rhcos-bootimage.py https://rhcos-redirector.apps.art.xq1c.p1.openshiftapps.com/art/storage/releases/rhcos-4.6-ppc64le/46.82.202109161439-0/ppc64le/meta.json ppc64le
python update-rhcos-bootimage.py https://rhcos-redirector.apps.art.xq1c.p1.openshiftapps.com/art/storage/releases/rhcos-4.6-s390x/46.82.202109171905-0/s390x/meta.json s390x
python update-rhcos-bootimage.py https://rhcos-redirector.apps.art.xq1c.p1.openshiftapps.com/art/storage/releases/rhcos-4.6/46.82.202109171856-0/x86_64/meta.json amd64
```
Signed-off-by: Renata Ravanelli <rravanel@redhat.com>

### CODE REVIEW

**Comment by miabbott** [comment]
/hold

The RHCOS pipeline isn't currently building 4.7 boot media. We'll need to re-enable that and update this PR.

**Comment by miabbott** [comment]
`e2e-libvirt` looks like the job needs an update:

`  * could not run steps: step e2e-libvirt failed: could not wait for template instance to be ready: failed to create objects: Template.template.openshift.io "e2e-libvirt" is invalid: [template.parameters[4]: Required value: template.parameters[4]: parameter IMAGE_LIBVIRT_INSTALLER is required and must be specified, template.parameters[5]: Required value: template.parameters[5]: parameter IMAGE_TESTS is required and must be specified] `

`e2e-aws-workers-rhel7` got the cluster up but failed on `[sig-instrumentation] Prometheus when installed on the cluster shouldn't have failing rules evaluation [Suite:openshift/conformance/parallel]`

`e2e-vsphere-upi` looks like it failed because the RHEL repos it uses couldn't be contacted.  Actually looks like it is trying to contact an internal location:

`- Curl error (6): Couldn't resolve host name for http://rhsm-pulp.corp.redhat.com/content/tus/rhel8/8.2/x86_64/nfv/os/repodata/repomd.xml [Could not resolve host: rhsm-pulp.corp.redhat.com]
Error: Failed to download metadata for repo 'localdev-rhel-8-rt-rpms': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried`

`e2e-azure-upi` needs to be updated:

`  * could not run steps: step e2e-azure-upi failed: could not wait for template instance to be ready: failed to create objects: Template.template.openshift.io "e2e-azure-upi" is invalid: [template.parameters[5]: Required value: template.parameters[5]: parameter IMAGE_TESTS is required and must be specified, template.parameters[6]: Required value: template.parameters[6]: parameter IMAGE_UPI_INSTALLER is required and must be specified] `

**Comment by miabbott** [comment]
`e2e-gcp` got the cluster up and running, but failed on this `[sig-storage] In-tree Volumes [Driver: aws] [Testpattern: Pre-provisioned PV (block volmode)] volumes should store data [Suite:openshift/conformance/parallel] [Suite:k8s]` which is confusing since it mentions the `aws` driver

**Comment by miabbott** [comment]
Both `e2e-vsphere` jobs are actually failing when trying to build the bare metal installer:

`[36mINFO[0m[2021-09-28T18:18:41Z] Build baremetal-installer failed, printing logs: `

Root cause is inaccessible yum repos

**Comment by sdodson** [comment]
/override ci/prow/e2e-azure-upi
/override ci/prow/e2e-vsphere-upi
job definition problems with those two

**Pull request merged**
