### PR TITLE
upgrade terraform to 0.14.6

### PR DESCRIPTION
**Pull request by staebler**
This updates the installer to use Terraform 0.14.6.

Terraform 0.13.x updated the on-disk layout of the plugins directory, how to access offline plugins, and a lock file used for plugin versions. plugin_versions_generate.go has been added which generates plugin_versions.go. All terraform plugin files the installer uses have been updated to use the plugin version. All terraform config files have been updated to use the local providers. A terraform.rc file has been added to specify where the local providers are.

A temporary vendor path for terraform is in this PR that allows the location of the new plugin version lock file to be overridden. Once I can get everything green it will be added to our local terraform fork.

https://issues.redhat.com/browse/CORS-1520

https://www.terraform.io/docs/language/providers/requirements.html
https://www.terraform.io/docs/language/dependency-lock.html

This brings together the changes from #4729 and #4822.
/cc @jhixson74 @rna-afk

### CODE REVIEW

**Comment by staebler** [comment]
The ovirt install is failing to delete the template during bootstrap destroy.
```
[31mERRO[0m[2021-04-09T16:14:01Z] level=error msg=Error: Error removing Template (d66bc985-e095-48e5-ad86-4dc29631b719): Fault reason is "Operation Failed". Fault detail is "[Cannot delete Template. Template is being used by the following VMs: *****12-qbkhq-worker-rpgxq.]". HTTP response code is "409". HTTP response message is "409 Conflict". 
```

**Comment by staebler** [comment]
Failures with pip.
/test e2e-kubevirt
/test e2e-vsphere

**Comment by rna-afk** [comment]
For the ovirt, I was trying to remove [this](https://github.com/openshift/installer/blob/5086499eca66825c0fa2a4966776f60d2b7fd7c6/pkg/destroy/bootstrap/bootstrap.go#L83) case statement by adding the boostrapping variable to the components.

**Comment by staebler** [comment]
The ovirt install is also deleting the master VMs during bootstrap destroy. Presumably that is because it is deleting the template, which the master VMs depend upon.
```
time="2021-04-09T15:57:07Z" level=debug msg="module.masters.*****_vm.master[0]: Destroying... [id=ac3a17fe-43b6-4bde-a4bb-01aa3cee4f48]"
```

**Comment by staebler** [comment]
> The ovirt install is also deleting the master VMs during bootstrap destroy. Presumably that is because it is deleting the template, which the master VMs depend upon.
> 
> ```
> time="2021-04-09T15:57:07Z" level=debug msg="module.masters.*****_vm.master[0]: Destroying... [id=ac3a17fe-43b6-4bde-a4bb-01aa3cee4f48]"
> ```

I add a commit that retains the temporary template. This is a workaround that I will raise a BZ for the ovirt team to address.

**Pull request closed without merging**
