### PR TITLE
hack/build: Pin to RHCOS 47.249 and quay.io/openshift-release-dev/ocp-release:4.0.0-0.1

### PR DESCRIPTION
**Pull request by wking**
DO NOT MERGE!  This PR is just for CI coverage.

Recycling the RHCOS build from 76f91bdf (#1009, v0.9.1).

Clayton just pushed `4.0-art-latest-2019-01-15-010905` to `quay.io/openshift-release-dev/ocp-release:4.0.0-0.1`, although we might update that tag with a later hot fix.  We're cutting this release on 4.0.0-0.1 so folks can use a (mostly) pinned installer with an (almost) released update payload ;).

Renaming `OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE` gets us CI testing of the pinned release despite openshift/release@60007df2 (openshift/release#1793).

Also comment out regions which this particular RHCOS build wasn't pushed to, leaving only:

```console
$ curl -s https://releases-rhcos.svc.ci.openshift.org/storage/releases/maipo/47.246/meta.json | jq -r '.amis[] | .name'
ap-northeast-1
ap-northeast-2
ap-south-1
ap-southeast-1
ap-southeast-2
ca-central-1
eu-central-1
eu-west-1
eu-west-2
eu-west-3
sa-east-1
us-east-1
us-east-2
us-west-1
us-west-2
```

I'd initially expected to export the pinning environment variables in `release.sh`, but I've put them in `build.sh` here because our continuous integration tests use `build.sh` directly and don't go through `release.sh`.

See #1002 for the very similar commit behind v0.9.0.

### CODE REVIEW

**Comment by wking** [comment]
@tkatarki, this is the commit that will become 0.10.0.

**Comment by crawford** [comment]
/hold

Looks good to me.

**Comment by wking** [comment]
[images][1]:

```
info: Included 56 referenced images into the payload
Uploading ... failed
error: received unexpected HTTP status: 500 Internal Server Error
2019/01/15 17:59:52 Container release in pod release-latest failed, exit code 1, reason Error
```

/retest

[1]: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_installer/1068/pull-ci-openshift-installer-master-images/2168/build-log.txt

**Comment by wking** [comment]
[e2e-aws][1]:

```
level=warning msg="Failed to connect events watcher: Get https://ci-op-c9nti40h-1d3f3-api.origin-ci-int-aws.dev.rhcloud.com:6443/api/v1/namespaces/kube-system/events?resourceVersion=149&watch=true: dial tcp 100.26.0.166:6443: connect: connection refused"
level=fatal msg="waiting for bootstrap-complete: timed out waiting for the condition"
2019/01/15 18:57:15 Container setup in pod e2e-aws failed, exit code 1, reason Error
```

I'm not entirely clear on what happened.  Checking from my dev box while the installer was waiting (after copying the admin kubeconfig out of ci.openshift.org), showed events:

```console
$ oc get events --all-namespaces
NAMESPACE                                    LAST SEEN   FIRST SEEN   COUNT     NAME                                                                              KIND         SUBOBJECT                                                  TYPE      REASON                       SOURCE                                                      MESSAGE
kube-system                                  31m         31m          1         kube-scheduler.157a18ee94b33467                                                   Endpoints                                                               Normal    LeaderElection               default-scheduler                                           ip-10-0-15-172_28613320-18f3-11e9-bc14-126bc65547cc became leader
kube-system                                  30m         30m          1         kube-controller-manager.157a18ef984b44d1                                          ConfigMap                                                               Normal    LeaderElection               kube-controller-manager                                     ip-10-0-15-172_286df4e8-18f3-11e9-8fff-126bc65547cc became leader
openshift-cluster-version                    30m         30m          12        cluster-version-operator.157a18f24287242f                                         Deployment                                       
...
openshift-apiserver-operator                 4m          4m           1         openshift-apiserver-operator.157a1a5d1dd13f11                                     Deployment                                                              Normal    OperatorStatusChanged        openshift-cluster-openshift-apiserver-operator              Status for operator openshift-apiserver changed: Available message changed from "apiservice/v1.apps.openshift.io: not available: no response from https://172.30.150.77:443: Get https://172.30.150.77:443: dial tcp 172.30.150.77:443: connect: no route to host\napiservice/v1.authorization.openshift.io: not available: no response from https://172.30.150.77:443: Get https://172.30.150.77:443: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)\napiservice/v1.build.openshift.io: not available: no response from https://172.30.150.77:443: Get https://172.30.150.77:443: dial tcp 172.30.150.77:443: connect: no route to host\napiservice/v1.image.openshift.io: not available: no response from https://172.30.150.77:443: Get https://172.30.150.77:443: dial tcp 172.30.150.77:443: connect: no route to host\napiservice/v1.oauth.openshift.io: not available: no response from https://172.30.150.77:443: Get https://172.30.150.77:443: dial tcp 172.30.150.77:443: connect: no route to host\napiservice/v1.project.openshift.io: not available: no response from https://172.30.150.77:443: Get https://172.30.150.77:443: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)\napiservice/v1.quota.openshift.io: not available: no response from https://172.30.150.77:443: Get https://172.30.150.77:443: dial tcp 172.30.150.77:443: connect: no route to host\napiservice/v1.route.openshift.io: not available: no response from https://172.30.150.77:443: Get https://172.30.150.77:443: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)\napiservice/v1.security.openshift.io: not available: no response from https://172.30.150.77:443: Get https://172.30.150.77:443: dial tcp 172.30.150.77:443: connect: no route to host\napiservice/v1.template.openshift.io: not available: no response from https://172.30.150.77:443: Get https://172.30.150.77:443: dial tcp 172.30.150.77:443: connect: no route to host\napiservice/v1.user.openshift.io: not available: no response from https://172.30.150.77:443: Get https://172.30.150.77:443: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)" to "apiservice/v1.apps.openshift.io: not available: no response from https://172.30.150.77:443: Get https://172.30.150.77:443: dial tcp 172.30.150.77:443: connect: no route to host\napiservice/v1.authorization.openshift.io: not available: no response from https://172.30.150.77:443: Get https://172.30.150.77:443: dial tcp 172.30.150.77:443: connect: no route to host\napiservice/v1.build.openshift.io: not available: no response from https://172.30.150.77:443: Get https://172.30.150.77:443: dial tcp 172.30.150.77:443: connect: no route to host\napiservice/v1.image.openshift.io: not available: no response from https://172.30.150.77:443: Get https://172.30.150.77:443: dial tcp 172.30.150.77:443: connect: no route to host\napiservice/v1.oauth.openshift.io: not available: no response from https://172.30.150.77:443: Get https://172.30.150.77:443: dial tcp 172.30.150.77:443: connect: no route to host\napiservice/v1.project.openshift.io: not available: no response from https://172.30.150.77:443: Get https://172.30.150.77:443: dial tcp 172.30.150.77:443: connect: no route to host\napiservice/v1.quota.openshift.io: not available: no response from https://172.30.150.77:443: Get https://172.30.150.77:443: dial tcp 172.30.150.77:443: connect: no route to host\napiservice/v1.route.openshift.io: not available: no response from https://172.30.150.77:443: Get https://172.30.150.77:443: dial tcp 172.30.150.77:443: connect: no route to host\napiservice/v1.security.openshift.io: not available: no response from https://172.30.150.77:443: Get https://172.30.150.77:443: dial tcp 172.30.150.77:443: connect: no route to host\napiservice/v1.template.openshift.io: not available: no response from https://172.30.150.77:443: Get https://172.30.150.77:443: dial tcp 172.30.150.77:443: connect: no route to host\napiservice/v1.user.openshift.io: not available: no response from https://172.30.150.77:443: Get https://172.30.150.77:443: dial tcp 172.30.150.77:443: connect: no route to host"
default                                      4m          29m          6         ip-10-0-25-19.ec2.internal.157a1902779684e5                                       Node                                                                    Warning   ImageGCFailed                kubelet, ip-10-0-25-19.ec2.internal                         failed to get imageFs info: non-existent label "crio-images"
```

So maybe this is our [master stability issue][2]?  I dunno what's going on with `crio-images` either.

/retest

[1]: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_installer/1068/pull-ci-openshift-installer-master-e2e-aws/2921/build-log.txt
[2]: https://bugzilla.redhat.com/show_bug.cgi?id=1666084

**Comment by wking** [comment]
[e2e-aws][1]:

```
level=info msg="Waiting up to 10m0s for the openshift-console route to be created..."
level=fatal msg="waiting for openshift-console URL: context deadline exceeded"
```

but at least the non-console parts of the cluster came up, and we cut 0.10.0 based on this commit.

/close

[1]: https://deck-ci.svc.ci.openshift.org/log?job=pull-ci-openshift-installer-master-e2e-aws&id=2927

**Pull request closed without merging**
