### PR TITLE
no-jira: cluster-api/aws: bump capa to latest version

### PR DESCRIPTION
**Pull request by r4f4**
Latest CAPA version adds support to cluster-api 1.7.0

### CODE REVIEW

**Comment by r4f4** [comment]
GCP: is failing with a known issue.
AWS: cluster installed.
VSphere: cluster installed.
Azure: bootstrap completed.

**Comment by r4f4** [comment]
Update: rebased to fix merge conflicts.

**Comment by r4f4** [comment]
Update: rebased to fix merge conflicts.

**Comment by r4f4** [comment]
/hold
Depends on https://github.com/openshift/release/pull/51127

**Comment by r4f4** [comment]
/retitle  no-jira: cluster-api/aws: bump capa to latest version

**Comment by r4f4** [comment]
Update: changed the capa version from https://github.com/kubernetes-sigs/cluster-api-provider-aws/commit/b918c3636f5dcc030bbbc5191e757e37df87c682 to https://github.com/kubernetes-sigs/cluster-api-provider-aws/commit/810bbf4eafd8fd6584e0c653b24c5f07f223b8e4 to include health check changes by @mtulio

**Comment by r4f4** [comment]
/hold

capi-aws is failing with 
```
time="2024-04-22T22:54:32Z" level=debug msg="\tfailed to create target group for load balancer: ValidationError: Target group name 'rdossant-installer-04-wn9qs-int-6443' cannot be longer than '32' characters"
```
will need to investigate.

**Comment by r4f4** [comment]
Update: revert capa to the previous bumped version https://github.com/kubernetes-sigs/cluster-api-provider-aws/commit/b918c3636f5dcc030bbbc5191e757e37df87c682 since the recent health check changes cause the target groups creation to fail. https://github.com/openshift/installer/pull/8223 will include the bump with the required changes upstream + the fix for target groups. 
I have also added a commit to update the capi-aws CRD which I had forgotten to do before.

**Comment by r4f4** [comment]
Local tests are good.

/hold cancel

**Comment by mtulio** [comment]
/lgtm

holding until `master-altinfra-e2e-aws-ovn` have finished, fell free to drop after it :)
/hold

**Comment by r4f4** [comment]
altinfra-e2e-aws-ovn succeeded but let's try another platform for good measure:

/test altinfra-e2e-vsphere-capi-ovn

**Comment by r4f4** [comment]
vsphere installed.

/hold cancel

**Comment by r4f4** [comment]
/override ci/prow/e2e-aws-ovn
Changes in this PR do not affect the terraform provisioning path and this PR is blocking other features.

**Pull request merged**
