### PR TITLE
SPLAT-1670: install pwsh from ci mirrored image

### PR DESCRIPTION
**Pull request by rvanderp3**
installs image which is mirrored and build based on:
- https://github.com/openshift-splat-team/pwsh
- https://quay.io/repository/ocp-splat/pwsh

### CODE REVIEW

**Comment by rvanderp3** [comment]
cc @jcpowermac @vr4manta

**Comment by rvanderp3** [comment]
/hold

placing hold pending @vr4manta's review

**Review by r4f4 — COMMENTED** [review]
Thank you for working on this!

/approve

**Comment by r4f4** [comment]
/override ci/prow/e2e-azure-ovn-upi
e2e test failures not related to PR changes.

**Comment by rvanderp3** [comment]
e2e-vsphere-ovn-upi-zones is also failing due to an unrelated issue

**Pull request merged**
