### PR TITLE
Bug 1750338: use region info when simulating permissions

### PR DESCRIPTION
**Pull request by joelddiaz**
Vendor in an updated cloud-credential-operator:
`dep ensure -update github.com/openshift/cloud-credential-operator`

This pulls in support for providing the region as part of permissions simulation for AWS.

Update the installer to pass in region info as part of permissions validation.

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
/approve

> https://github.com/openshift/installer/pull/3056/commits/7abbe9b758c42ef6c05288d1b95c72b2201a098c

would love to see the steps that were used to make the bump in the commit message, but not necessary.

**Comment by wking** [comment]
[upgrade][1]:

```
level=fatal msg="failed to initialize the cluster: Cluster operator openshift-apiserver is still updating"
```

That failure is [the only such failure today][2].

[1]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_installer/3056/pull-ci-openshift-installer-master-e2e-aws-upgrade/4713#1:build-log.txt%3A63
[2]: https://search.svc.ci.openshift.org/chart?search=failed%20to%20initialize%20the%20cluster:%20Cluster%20operator%20openshift-apiserver%20is%20still%20updating

**Pull request merged**
