### PR TITLE
no-jira: images: upi-installer image cleanup

### PR DESCRIPTION
**Pull request by r4f4**
* remove terraform and terraform provider binaries: they are leftover from before the time we started building or own
 binaries.
* remove alibaba cli: the provider support has been removed.

### CODE REVIEW

**Comment by patrickdillon** [comment]
e2e-vsphere-upi failure is legit. terraform is used in the vsphere upi ci flow

**Comment by r4f4** [comment]
> e2e-vsphere-upi failure is legit. terraform is used in the vsphere upi ci flow

aha, I forgot about that. Let's hold this PR for now.

/hold

**Comment by r4f4** [comment]
vsphere upi has moved from terraform to powercli.

/hold cancel

**Review by barbacbd — COMMENTED** [review]
/lgtm

**Comment by r4f4** [comment]
/cc @yunjiang29 
I see some steps in CI use terraform, but afaiu it should be ok to remove from 4.17+ because the steps use upi-installer:4.12.

Steps:
 * ci-operator/step-registry/configure-registry-storage/destroy-s3-cloudfront/
 * ci-operator/step-registry/configure-registry-storage/deploy-s3-cloudfront

**Comment by yunjiang29** [comment]
> /cc @yunjiang29 I see some steps in CI use terraform, but afaiu it should be ok to remove from 4.17+ because the steps use upi-installer:4.12.
> 
> Steps:
> 
>     * ci-operator/step-registry/configure-registry-storage/destroy-s3-cloudfront/
> 
>     * ci-operator/step-registry/configure-registry-storage/deploy-s3-cloudfront

@r4f4 thanks for your reminder.  cc @xiuwang

**Comment by r4f4** [comment]
/override ci/prow/e2e-azure-ovn-upi
e2e failures not related to PR changes.

/hold cancel

**Comment by r4f4** [comment]
/hold
I didn't realize there is still a vsphere job using terraform.

**Comment by r4f4** [comment]
/hold cancel
It seems the issue was only that the PR had to be rebased on top of current master.

**Comment by r4f4** [comment]
/override ci/prow/e2e-azure-ovn-upi
e2e failures not related.

**Comment by r4f4** [comment]
/override ci/prow/e2e-gcp-ovn-upi 
e2e test failures not related to PR.

**Pull request merged**
