### PR TITLE
OCPBUGSM-47740: No networkconfig needed with DHCP agent config

### PR DESCRIPTION
**Pull request by pawanpinjarkar**
When creating DHCP only cluster with agent config ( i.e. only RendezvousIP), do not require any networkConfig to be provided.

### CODE REVIEW

**Comment by rwsu** [comment]
Because the networkConfig is not required, I think we need to remove this validation in finish().
```
	if n.Config == nil {
		return errors.New("missing configuration or manifest file")
	}
```

I found "create-manifests" failed when I defined an agent-config that had hosts defined but none of them specified a networkConfig.

`+(./agent/05_agent_create_cluster.sh:20): create_image(): /home/rwsu/go/src/github.com/openshift-metal3/dev-scripts/ocp/ostest/openshift-install --dir=ocp/ostest --log-level=debug agent create cluster-manifests
level=debug msg=OpenShift Installer 4.11.0-0.nightly-2022-09-06-225330
level=debug msg=Built from commit 95e0172d0df3d941fc248a1ff82b2c63312b9dd7
level=debug msg=Fetching Agent Manifests...
level=debug msg=Loading Agent Manifests...
level=debug msg=  Loading Agent PullSecret...
level=debug msg=    Loading Install Config...
level=warning msg=Host host1 hasn't any role configured
level=warning msg=Host host2 hasn't any role configured
level=warning msg=Host host3 hasn't any role configured
level=debug msg=    Using Install Config loaded from target directory
level=debug msg=  Loading InfraEnv Config...
level=debug msg=    Loading Install Config...
level=debug msg=  Loading NMState Config...
level=debug msg=    Loading Agent Config...
level=debug msg=    Using Agent Config loaded from target directory
level=debug msg=  Loading AgentClusterInstall Config...
level=debug msg=    Loading Install Config...
level=debug msg=  Loading ClusterDeployment Config...
level=debug msg=    Loading Install Config...
level=debug msg=  Loading ClusterImageSet Config...
level=debug msg=    Loading Release Image Pull Spec...
level=debug msg=    Loading Install Config...
level=debug msg=  Fetching Agent PullSecret...
level=debug msg=    Fetching Install Config...
level=debug msg=    Reusing previously-fetched Install Config
level=debug msg=  Generating Agent PullSecret...
level=debug msg=  Fetching InfraEnv Config...
level=debug msg=    Fetching Install Config...
level=debug msg=    Reusing previously-fetched Install Config
level=debug msg=  Generating InfraEnv Config...
level=debug msg=  Fetching NMState Config...
level=debug msg=    Fetching Agent Config...
level=debug msg=    Reusing previously-fetched Agent Config
level=debug msg=  Generating NMState Config...
level=fatal msg=failed to fetch Agent Manifests: failed to fetch dependency of "Agent Manifests": failed to generate asset "NMState Config": missing configuration or manifest file
`
/hold

**Comment by lranjbar** [comment]
@rwsu It might be faster to remake the PR. I placed a hold to stop using CI resources until we can get an override for the old job name.

**Pull request merged**
