### PR TITLE
data/bootstrap/files/etc/motd: Mention release-image.service

### PR DESCRIPTION
**Pull request by wking**
Catching up with d1ec85a5cc (#2234).

### CODE REVIEW

**Comment by smarterclayton** [comment]
Thanks, lgtm

/cherry-pick release-4.3

**Comment by abhinavdahiya** [comment]
why do we want to add this service to the message? bootkube.sh is the primary one that people should care about.
how do we know when to add any other to the list?
also what use-case/ user-flow do we see this adding value to?

**Comment by jstuever** [comment]
/lgtm

nit: maybe recommend a single call with `-u release-image.service -u bootkube.service`.

**Comment by wking** [comment]
> nit: maybe recommend a single call with -u release-image.service -u bootkube.service.

Done with f15a40645 -> 8626b5ef5.

> why do we want to add this service to the message? bootkube.sh is the primary one that people should care about.

And release-image is a prereq.  But probably not the only prereq.  I'm also fine dropping this MoTD completely and assuming folks know how to investigate systemd services.  #2569 would help catch things like insufficient registry auth once the user waited long enough for the installer to give up and scrape down logs.  @smarterclayton suggested also possibly reducing inside-the-script retries like [this endless loop][1] so folks looking for failing units would notice the pull failures.  I'm fine with anything in this space, and while mentioning this unit in the MoTD seemed like a cheap win, I'm fine with any combination of the above possibilities (and likely additional ideas not listed above) to make it easier for users to discover why their install is stuck.

[1]: https://github.com/openshift/installer/blob/b9968d12926a7914163c06af23581db7ebf66c20/data/data/bootstrap/files/usr/local/bin/release-image-download.sh.template#L15


how do we know when to add any other to the list?
also what use-case/ user-flow do we see this adding value to?

**Pull request merged**
