### PR TITLE
Add and vendor VSphere Terraform provider.

### PR DESCRIPTION
**Pull request by patrickdillon**
Vendored dependencies are a result of adding constraint to Gopkg.toml and running `dep ensure`.

cc @jcpowermac @jstuever

### CODE REVIEW

**Comment by patrickdillon** [comment]
I am baffled why shellcheck is failing for this PR but not #2893 when both vendor the same file in question...

```
[padillon@thinkpad installer]$ diff <(curl -s https://raw.githubusercontent.com/openshift/installer/09ec4d2adfea366e60014f2e284c685c65315bf4/pkg/terraform/exec/plugins/vendor/github.com/vmware/govmomi/scripts/license.sh) <(curl -s https://raw.githubusercontent.com/openshift/installer/54f5b4b45375d65c3db7077aaa30f1209758fe7a/vendor/github.com/vmware/govmomi/scripts/license.sh)
[padillon@thinkpad installer]$
```

**Comment by patrickdillon** [comment]
shellcheck issue resolves. thanks joe!

**Comment by sdodson** [comment]
merge conflict, so stop the hot looping
/lgtm cancel

**Comment by patrickdillon** [comment]
/hold cancel

The vSphere provider has a transitive dependency on govmomi, which I added, because it has not been updated to include this PR https://github.com/vmware/govmomi/commit/0399353f7859c4775827e454b2cc4f57956dd7ac#diff-4c906832aa0dba4d3e0e7075107581f3

Also, this PR removes an unused oVirt dependency which was left in master.

**Comment by mtnbikenc** [comment]
/hold
Tests are churning.

**Comment by patrickdillon** [comment]
/hold cancel
/skip
I think churn is resolved...

**Pull request merged**
