### PR TITLE
Bug 1809780: OpenStack: pass all CA from cert bundle to bootstrap ign…

### PR DESCRIPTION
**Pull request by mandre**
…ition

When the CA cert file referenced from the `clouds.yaml` contained more
than one certficate, the complete cert bundle was added to the boostrap
ignition file, but only the first one was actually trusted to gather
the ignition file.

This patch splits the CA cert bundle into separate certs and add them
to the ignition file as separate certs.

### CODE REVIEW

**Comment by mandre** [comment]
/hold
This needs to be tested

**Comment by mandre** [comment]
/hold cancel
Tested this new version locally.

**Comment by iamemilio** [comment]
This won't affect any of the other platforms, so their tests shouldn't matter.

**Pull request merged**
