### PR TITLE
MULTIARCH-5162: Power VS: Bump openshift/api to include https://github.com/openshift/api/pull/2076

### PR DESCRIPTION
**Pull request by mjturek**
https://github.com/openshift/api/pull/2076 fixed an issue with Power VS endpoint name validation that was stopping us from doing truly disconnected clusters with CAPI. This PR bumps the openshift API to a version that includes the necessary change.

### CODE REVIEW

**Comment by mjturek** [comment]
@r4f4 any idea what I'm doing wrong? Pulled in the new change and ran `go mod tidy && go mod vendor`

**Comment by r4f4** [comment]
@mjturek for the 'verify-codegen' test, you need to run `./hack/verify-codgen.sh` and commit the changes to `data/data/install.openshift.io_installconfigs.yaml`. Those changes are a result of the kubebuilder validation you introduced in o/api.

For the other failures, I cannot reproduce them, so something went wrong when you ran `go get github.com/openshift/api@051d53359b95 && go mod tidy && go mod vendor`.

**Comment by mjturek** [comment]
> @mjturek for the 'verify-codegen' test, you need to run `./hack/verify-codgen.sh` and commit the changes to `data/data/install.openshift.io_installconfigs.yaml`. Those changes are a result of the kubebuilder validation you introduced in o/api.
> 
> For the other failures, I cannot reproduce them, so something went wrong when you ran `go get github.com/openshift/api@051d53359b95 && go mod tidy && go mod vendor`.

I think 2 new files were added to the api repo that remained untracked, I've added them and am hoping that does the trick. Thanks for the advice!

**Pull request merged**
