### PR TITLE
Bug 1955701: Bump boot images for RHEL 8.4 Beta

### PR DESCRIPTION
**Pull request by travier**
```
x86_64  48.84.202104271417-0
s390x   48.84.202104271619-0
ppc64le 48.84.202104261624-0
```

### CODE REVIEW

**Review by ravanelli — APPROVED** [review]
Looks sane to me

**Comment by miabbott** [comment]
`e2e-libvirt` is consistently failing on Terraform creating the necessary libvirt resources; there is evidence that this has been happening before this PR was introduced

`e2e-aws-upgrade` is failing these two tests:
 - `[sig-auth][Feature:SCC][Early] should not have pod creation failures during install [Suite:openshift/conformance/parallel]`
 - `[sig-network] pods should successfully create sandboxes by other`
 
The latter seems linked to https://bugzilla.redhat.com/show_bug.cgi?id=1927264.  The former has some hits in search.ci.openshift.org that are outside of this PR

`e2e-crc` failed due to networking flakes a few times and also failed on this test a few times:
  - `[sig-apps] Deployment should run the lifecycle of a Deployment [Conformance] [Suite:openshift/conformance/parallel/minimal] [Suite:k8s] `

There's evidence of that failure outside of this PR in search.ci.openshift.org, too.

/assign @staebler

**Review by staebler — COMMENTED** [review]
The changes to `rhcos-stream.json` look fine to me. We need to continue to update the other `rhcos*.json` files, too, since there are still tests out there that rely on the old files. For 4.9, we can remove the old files and let tests that still use them fail.

Are you looking to make these changes in OpenShift 4.8?

**Comment by travier** [comment]
I did not know that we still had tests looking at that. Will update all files.

**Comment by yselkowitz** [comment]
If you update this again, could you please add a matching aarch64 build to this?  (ARM support is being added via #4870)

**Comment by travier** [comment]
Ping @staebler

**Comment by staebler** [comment]
> Ping @staebler

I had an open question for you.

> Are you looking to make these changes in OpenShift 4.8?

If you want this in 4.8, you need a BZ.

**Comment by staebler** [comment]
These changes look reasonable to me. Can someone from the CoreOS team look it over for a lgtm?

/approve

**Comment by travier** [comment]
> I had an open question for you.
> 
> > Are you looking to make these changes in OpenShift 4.8?
> 
> If you want this in 4.8, you need a BZ.

Whoops sorry for the confusion. Yes, this is for 4.8. Will make a BZ.

**Review by cgwalters — APPROVED** [review]

**Comment by travier** [comment]
> If you update this again, could you please add a matching aarch64 build to this? (ARM support is being added via #4870)

Will do that with the next boot image bump.

**Pull request merged**
