### PR TITLE
Add gather support for gcp

### PR DESCRIPTION
**Pull request by patrickdillon**
Adds support for the gather command for the GCP platform. 

There might be a more elegant way to parse the terraform state file for GCP using the unstructured package, but this implementation works and has error checking at each step.

[CORS-1123](https://jira.coreos.com/browse/CORS-1123)

/label platform/google

### CODE REVIEW

**Comment by patrickdillon** [comment]
@abhinavdahiya asked me to look into how the bootstrap node having an ephemeral public ip address could affect the gather command: it should not be an issue.

An ephemeral ip is only released if the instance is stopped. If the instance is reset the ip address is maintained. I tested this. [Docs](https://cloud.google.com/compute/docs/ip-addresses/#ephemeraladdress):

> Ephemeral external IP address are released from a resource if you delete the resource. For VM instances, if you stop the instance, the IP address is also released. Once you restart the instance, it is assigned a new ephemeral external IP address.

**Comment by jstuever** [comment]
Are we concerned a user may stop their instance? If so, we may want to spin off a bug to set a static IP here.

**Comment by jstuever** [comment]
/lgtm

I'm with you, the unraveling is a bit clunky and I'd hope there is a cleaner way. But, it works.

**Pull request merged**
