### PR TITLE
Bug 1812599: bump RHCOS boot images to 43.81.202003111353.0

### PR DESCRIPTION
**Pull request by miabbott**
This bumps the RHCOS boot images to include fixes for IPv6 support
and handling of kernel arguments.

### CODE REVIEW

**Comment by miabbott** [comment]
Yeah, this is pending the merge of https://github.com/openshift/installer/pull/3271 and apparently some additional BZ gymnastics

**Comment by jlebon** [comment]
Can you print the diff?

**Comment by miabbott** [comment]
Generated with `hack/update-rhcos-bootimage.py https://releases-art-rhcos.svc.ci.openshift.org/art/storage/releases/rhcos-4.3/43.81.202003111353.0/x86_64/meta.json`

Package diff:

```
$ ./differ.py -fe api.ci -fv 43.81.202001142154.0 -se api.ci -sv 43.81.202003111353.0
{
    "sources": {
        "43.81.202001142154.0": "https://releases-art-rhcos.svc.ci.openshift.org/art/storage/releases/rhcos-4.3/43.81.202001142154.0/x86_64/commitmeta.json",
        "43.81.202003111353.0": "https://releases-art-rhcos.svc.ci.openshift.org/art/storage/releases/rhcos-4.3/43.81.202003111353.0/x86_64/commitmeta.json"
    },
    "diff": {
        "container-selinux": {
            "43.81.202001142154.0": "container-selinux-2.124.0-1.el8.noarch",
            "43.81.202003111353.0": "container-selinux-2.124.0-1.module+el8.1.1+5259+bcdd613a.noarch"
        },
        "containernetworking-plugins": {
            "43.81.202001142154.0": "containernetworking-plugins-0.8.3-1.el8.x86_64",
            "43.81.202003111353.0": "containernetworking-plugins-0.8.3-4.module+el8.1.1+5259+bcdd613a.x86_64"
        },
        "containers-common": {
            "43.81.202001142154.0": "containers-common-0.1.40-2.el8.x86_64",
            "43.81.202003111353.0": "containers-common-0.1.40-8.module+el8.1.1+5351+506397b0.x86_64"
        },
        "cri-o": {
            "43.81.202001142154.0": "cri-o-1.16.2-6.dev.rhaos4.3.git9e3db66.el8.x86_64",
            "43.81.202003111353.0": "cri-o-1.16.3-28.dev.rhaos4.3.git9aad8e4.el8.x86_64"
        },
        "dracut": {
            "43.81.202001142154.0": "dracut-049-27.git20190906.el8_1.1.x86_64",
            "43.81.202003111353.0": "dracut-049-70.git20200228.el8.x86_64"
        },
        "dracut-network": {
            "43.81.202001142154.0": "dracut-network-049-27.git20190906.el8_1.1.x86_64",
            "43.81.202003111353.0": "dracut-network-049-70.git20200228.el8.x86_64"
        },
        "fuse-overlayfs": {
            "43.81.202001142154.0": "fuse-overlayfs-0.4.1-1.module+el8.1.0+4081+b29780af.x86_64",
            "43.81.202003111353.0": "fuse-overlayfs-0.7.2-1.module+el8.1.1+5259+bcdd613a.x86_64"
        },
        "glibc": {
            "43.81.202001142154.0": "glibc-2.28-72.el8.x86_64",
            "43.81.202003111353.0": "glibc-2.28-72.el8_1.1.x86_64"
        },
        "glibc-all-langpacks": {
            "43.81.202001142154.0": "glibc-all-langpacks-2.28-72.el8.x86_64",
            "43.81.202003111353.0": "glibc-all-langpacks-2.28-72.el8_1.1.x86_64"
        },
        "glibc-common": {
            "43.81.202001142154.0": "glibc-common-2.28-72.el8.x86_64",
            "43.81.202003111353.0": "glibc-common-2.28-72.el8_1.1.x86_64"
        },
        "grub2-common": {
            "43.81.202001142154.0": "grub2-common-2.02-78.el8.noarch",
            "43.81.202003111353.0": "grub2-common-2.02-78.el8_1.1.noarch"
        },
        "grub2-efi-x64": {
            "43.81.202001142154.0": "grub2-efi-x64-2.02-78.el8.x86_64",
            "43.81.202003111353.0": "grub2-efi-x64-2.02-78.el8_1.1.x86_64"
        },
        "grub2-pc": {
            "43.81.202001142154.0": "grub2-pc-2.02-78.el8.x86_64",
            "43.81.202003111353.0": "grub2-pc-2.02-78.el8_1.1.x86_64"
        },
        "grub2-pc-modules": {
            "43.81.202001142154.0": "grub2-pc-modules-2.02-78.el8.noarch",
            "43.81.202003111353.0": "grub2-pc-modules-2.02-78.el8_1.1.noarch"
        },
        "grub2-tools": {
            "43.81.202001142154.0": "grub2-tools-2.02-78.el8.x86_64",
            "43.81.202003111353.0": "grub2-tools-2.02-78.el8_1.1.x86_64"
        },
        "grub2-tools-extra": {
            "43.81.202001142154.0": "grub2-tools-extra-2.02-78.el8.x86_64",
            "43.81.202003111353.0": "grub2-tools-extra-2.02-78.el8_1.1.x86_64"
        },
        "grub2-tools-minimal": {
            "43.81.202001142154.0": "grub2-tools-minimal-2.02-78.el8.x86_64",
            "43.81.202003111353.0": "grub2-tools-minimal-2.02-78.el8_1.1.x86_64"
        },
        "ignition": {
            "43.81.202001142154.0": "ignition-0.34.0-1.rhaos4.3.git92f874c.el8.x86_64",
            "43.81.202003111353.0": "ignition-0.34.0-2.rhaos4.3.git92f874c.el8.x86_64"
        },
        "iptables": {
            "43.81.202001142154.0": "iptables-1.8.2-16.el8.x86_64",
            "43.81.202003111353.0": "iptables-1.8.4-9.el8.x86_64"
        },
        "iptables-libs": {
            "43.81.202001142154.0": "iptables-libs-1.8.2-16.el8.x86_64",
            "43.81.202003111353.0": "iptables-libs-1.8.4-9.el8.x86_64"
        },
        "kbd": {
            "43.81.202001142154.0": "kbd-2.0.4-8.el8.x86_64",
            "43.81.202003111353.0": "Not present"
        },
        "kbd-legacy": {
            "43.81.202001142154.0": "kbd-legacy-2.0.4-8.el8.noarch",
            "43.81.202003111353.0": "Not present"
        },
        "kbd-misc": {
            "43.81.202001142154.0": "kbd-misc-2.0.4-8.el8.noarch",
            "43.81.202003111353.0": "Not present"
        },
        "kernel": {
            "43.81.202001142154.0": "kernel-4.18.0-147.3.1.el8_1.x86_64",
            "43.81.202003111353.0": "kernel-4.18.0-147.5.1.el8_1.x86_64"
        },
        "kernel-core": {
            "43.81.202001142154.0": "kernel-core-4.18.0-147.3.1.el8_1.x86_64",
            "43.81.202003111353.0": "kernel-core-4.18.0-147.5.1.el8_1.x86_64"
        },
        "kernel-modules": {
            "43.81.202001142154.0": "kernel-modules-4.18.0-147.3.1.el8_1.x86_64",
            "43.81.202003111353.0": "kernel-modules-4.18.0-147.5.1.el8_1.x86_64"
        },
        "kernel-modules-extra": {
            "43.81.202001142154.0": "kernel-modules-extra-4.18.0-147.3.1.el8_1.x86_64",
            "43.81.202003111353.0": "kernel-modules-extra-4.18.0-147.5.1.el8_1.x86_64"
        },
        "libarchive": {
            "43.81.202001142154.0": "libarchive-3.3.2-7.el8.x86_64",
            "43.81.202003111353.0": "libarchive-3.3.2-8.el8_1.x86_64"
        },
        "libnftnl": {
            "43.81.202001142154.0": "libnftnl-1.1.1-4.el8.x86_64",
            "43.81.202003111353.0": "libnftnl-1.1.5-4.el8.x86_64"
        },
        "libxkbcommon": {
            "43.81.202001142154.0": "libxkbcommon-0.8.2-1.el8.x86_64",
            "43.81.202003111353.0": "Not present"
        },
        "machine-config-daemon": {
            "43.81.202001142154.0": "machine-config-daemon-4.3.0-202001131753.git.1.e2edc36.el8.x86_64",
            "43.81.202003111353.0": "machine-config-daemon-4.3.6-202003110901.git.0.b4999a5.el8.x86_64"
        },
        "openldap": {
            "43.81.202001142154.0": "openldap-2.4.46-10.el8.x86_64",
            "43.81.202003111353.0": "openldap-2.4.46-11.el8_1.x86_64"
        },
        "openshift-clients": {
            "43.81.202001142154.0": "openshift-clients-4.3.0-202001030600.git.1.5e09fe6.el8.x86_64",
            "43.81.202003111353.0": "openshift-clients-4.3.6-202003110601.git.0.4b8c32c.el8.x86_64"
        },
        "openshift-hyperkube": {
            "43.81.202001142154.0": "openshift-hyperkube-4.3.0-202001131753.git.0.0aee6a8.el8.x86_64",
            "43.81.202003111353.0": "openshift-hyperkube-4.3.6-202003090404.git.0.737076f.el8.x86_64"
        },
        "openssh": {
            "43.81.202001142154.0": "openssh-8.0p1-3.el8.x86_64",
            "43.81.202003111353.0": "openssh-8.0p1-4.el8_1.x86_64"
        },
        "openssh-clients": {
            "43.81.202001142154.0": "openssh-clients-8.0p1-3.el8.x86_64",
            "43.81.202003111353.0": "openssh-clients-8.0p1-4.el8_1.x86_64"
        },
        "openssh-server": {
            "43.81.202001142154.0": "openssh-server-8.0p1-3.el8.x86_64",
            "43.81.202003111353.0": "openssh-server-8.0p1-4.el8_1.x86_64"
        },
        "openvswitch-selinux-extra-policy": {
            "43.81.202001142154.0": "openvswitch-selinux-extra-policy-1.0-19.el8fdp.noarch",
            "43.81.202003111353.0": "openvswitch-selinux-extra-policy-1.0-22.el8fdp.noarch"
        },
        "openvswitch2.11": {
            "43.81.202001142154.0": "openvswitch2.11-2.11.0-35.el8fdp.x86_64",
            "43.81.202003111353.0": "openvswitch2.11-2.11.0-48.el8fdp.x86_64"
        },
        "podman": {
            "43.81.202001142154.0": "podman-1.6.4-1.el8.x86_64",
            "43.81.202003111353.0": "podman-1.6.4-7.el8.x86_64"
        },
        "podman-manpages": {
            "43.81.202001142154.0": "podman-manpages-1.6.4-1.el8.noarch",
            "43.81.202003111353.0": "podman-manpages-1.6.4-7.el8.noarch"
        },
        "policycoreutils": {
            "43.81.202001142154.0": "policycoreutils-2.9-3.el8.x86_64",
            "43.81.202003111353.0": "policycoreutils-2.9-3.el8_1.1.x86_64"
        },
        "policycoreutils-python-utils": {
            "43.81.202001142154.0": "policycoreutils-python-utils-2.9-3.el8.noarch",
            "43.81.202003111353.0": "policycoreutils-python-utils-2.9-3.el8_1.1.noarch"
        },
        "python3-policycoreutils": {
            "43.81.202001142154.0": "python3-policycoreutils-2.9-3.el8.noarch",
            "43.81.202003111353.0": "python3-policycoreutils-2.9-3.el8_1.1.noarch"
        },
        "rpm-ostree": {
            "43.81.202001142154.0": "rpm-ostree-2019.6-6.el8.x86_64",
            "43.81.202003111353.0": "rpm-ostree-2019.6-8.el8.x86_64"
        },
        "rpm-ostree-libs": {
            "43.81.202001142154.0": "rpm-ostree-libs-2019.6-6.el8.x86_64",
            "43.81.202003111353.0": "rpm-ostree-libs-2019.6-8.el8.x86_64"
        },
        "runc": {
            "43.81.202001142154.0": "runc-1.0.0-64.rc9.el8.x86_64",
            "43.81.202003111353.0": "runc-1.0.0-65.rc10.rhaos4.3.el8.x86_64"
        },
        "skopeo": {
            "43.81.202001142154.0": "skopeo-0.1.40-2.el8.x86_64",
            "43.81.202003111353.0": "skopeo-0.1.40-8.module+el8.1.1+5351+506397b0.x86_64"
        },
        "slirp4netns": {
            "43.81.202001142154.0": "slirp4netns-0.4.2-1.git21fdece.el8.x86_64",
            "43.81.202003111353.0": "slirp4netns-0.4.2-4.git21fdece.el8.x86_64"
        },
        "sqlite-libs": {
            "43.81.202001142154.0": "sqlite-libs-3.26.0-3.el8.x86_64",
            "43.81.202003111353.0": "sqlite-libs-3.26.0-4.el8_1.x86_64"
        },
        "sudo": {
            "43.81.202001142154.0": "sudo-1.8.25p1-8.el8_1.x86_64",
            "43.81.202003111353.0": "sudo-1.8.25p1-8.el8_1.1.x86_64"
        },
        "systemd": {
            "43.81.202001142154.0": "systemd-239-18.el8_1.1.x86_64",
            "43.81.202003111353.0": "systemd-239-27.el8.x86_64"
        },
        "systemd-journal-remote": {
            "43.81.202001142154.0": "systemd-journal-remote-239-18.el8_1.1.x86_64",
            "43.81.202003111353.0": "systemd-journal-remote-239-27.el8.x86_64"
        },
        "systemd-libs": {
            "43.81.202001142154.0": "systemd-libs-239-18.el8_1.1.x86_64",
            "43.81.202003111353.0": "systemd-libs-239-27.el8.x86_64"
        },
        "systemd-pam": {
            "43.81.202001142154.0": "systemd-pam-239-18.el8_1.1.x86_64",
            "43.81.202003111353.0": "systemd-pam-239-27.el8.x86_64"
        },
        "systemd-udev": {
            "43.81.202001142154.0": "systemd-udev-239-18.el8_1.1.x86_64",
            "43.81.202003111353.0": "systemd-udev-239-27.el8.x86_64"
        },
        "toolbox": {
            "43.81.202001142154.0": "toolbox-0.0.5-1.rhaos4.2.el8.noarch",
            "43.81.202003111353.0": "toolbox-0.0.7-1.rhaos4.3.el8.noarch"
        },
        "xkeyboard-config": {
            "43.81.202001142154.0": "xkeyboard-config-2.24-3.el8.noarch",
            "43.81.202003111353.0": "Not present"
        }
    }
}
```

**Comment by miabbott** [comment]
We may want to drop BZ#1807395 as a dependent.  It's the RHEL `dracut` bug, we don't want to re categorize it for OCP, and having it as a dependent is going to make the Bugzilla bot unhappy.

Or we just get the powers that be to force the merge after all the tests come back happy.

**Comment by jlebon** [comment]
New dracut :heavy_check_mark: 
New rpm-ostree :heavy_check_mark: 

/approve

**Comment by ashcrow** [comment]
/test e2e-aws-upgrade
```
throttling: Rate exceeded\n\tstatus code: 400,
```

**Comment by miabbott** [comment]
Prow reports that `e2e-aws-upgrade` is still Pending, but clicking through shows the job failed:

`Mar 11 21:45:54.482 I openshift-apiserver OpenShift API stopped responding to GET requests: the server is currently unable to handle the request (get imagestreams.image.openshift.io missing)`

**Comment by miabbott** [comment]
PR #3271 merged and associated BZ moved to VERIFIED

/bugzilla refresh

**Comment by sdodson** [comment]
Overrode `bugzilla/valid-bug` for RHCOS boot image bumps which address multiple bugs and prevent decent tracking. A plan is in progress to come up with a better way to track RHCOS boot image bugs.

**Comment by miabbott** [comment]
@ashcrow can you give the `approve` and/or `cherry-pick-approved` labels?

**Pull request merged**
