### PR TITLE
scripts: add Makefile

### PR DESCRIPTION
**Pull request by soltysh**
I'm adding Makefile to simplify dev workflow and make it similar to other components under openshift org.

### CODE REVIEW

**Comment by wking** [comment]
I'm personally fine with a `Makefile` like this, but see previous decisions to not go in this direction [here][1] and [here][2].

[1]: https://github.com/openshift/installer/pull/91#issuecomment-409717199
[2]: https://github.com/openshift/installer/pull/385#issuecomment-426421482

**Comment by soltysh** [comment]
@crawford @abhinavdahiya any chance for changing your mind? /cc @smarterclayton since I think this is reasonable approach applied from k8s through all of our operators.

**Comment by abhinavdahiya** [comment]
IMO
- `make all/build` is better than `./hack/build.sh`
- `make verify`  is not useful to everybody as most people are not changing `tf` files all the time.
- no targets in the Makefile actually help dev workflow. 
  `libvirt` vs `non-libvirt` `release` vs `non-release`
  using install-config store somewhere to create a cluster
  testing new release images.

So I would like to see more examples of how moving to make helps/improves our dev workflow or even if people using installer are going to use one workflow that we define... ?

**Comment by soltysh** [comment]
>     * `make all/build` is better than `./hack/build.sh`

Yes, that's probably my main motivation for `Makefile`. 

>     * `make verify`  is not useful to everybody as most people are not changing `tf` files all the time.

I don't see any reason to have multiple verify targets.

>     * no targets in the Makefile actually help dev workflow.
>       `libvirt` vs `non-libvirt` `release` vs `non-release`
>       using install-config store somewhere to create a cluster
>       testing new release images.

This contradicts to what you've said in the first point. I don't see any reason not to expand `Makefile` with additional targets which will hide the script complexity.

**Comment by abhinavdahiya** [comment]
> > ```
> > * `make all/build` is better than `./hack/build.sh`
> > ```
> 
> Yes, that's probably my main motivation for `Makefile`.


oops, brain fart... I actually wanted to say the `make all/build` is **not any** better than `./hack/build.sh`

**Comment by soltysh** [comment]
> oops, brain fart... I actually wanted to say the `make all/build` is **not any** better than `./hack/build.sh`

:sob: my main reason for `Makefile` is also the fact that when jumping between repos I'm confident that invoking `make` will give me binary, except for the installer, currently.

**Comment by abhinavdahiya** [comment]
This looks abandoned. Please feel free to reopen if you think this change is still useful.

/close

**Pull request closed without merging**
