### PR TITLE
OCPBUGS-35440: capi/aws: bump provider for ingress rules fix

### PR DESCRIPTION
**Pull request by r4f4**
* Brings in this fix
  https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/5024
  to avoid unnecessary revoke-authorize of ingress rules.

### CODE REVIEW

**Comment by r4f4** [comment]
/uncc @rwsu @barbacbd 
Will CC back in when it's ready for review.

**Comment by r4f4** [comment]
/retitle WIP: OCPBUGS-35440: capi/aws: bump provider for ingress rules fix

**Comment by r4f4** [comment]
/retitle OCPBUGS-35440: capi/aws: bump provider for ingress rules fix

**Comment by r4f4** [comment]
This is ready for review now.

/cc @barbacbd @patrickdillon 
/hold cancel

**Review by barbacbd — COMMENTED** [review]
New value natGatewaysIPsSource isn't used but the infrastructure file is updated to keep in sync.

/lgtm

**Comment by r4f4** [comment]
`e2e-aws-ovn`: looking at the [installer log output](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_installer/8596/pull-ci-openshift-installer-master-e2e-aws-ovn/1811010992612577280/artifacts/e2e-aws-ovn/ipi-install-install/artifacts/.openshift_install-1720618893.log) we see only one revoke:
```
time="2024-07-10T13:24:03Z" level=debug msg="I0710 13:24:03.343095     336 securitygroups.go:181] \"Revoked ingress rules from security group\" controller=\"awscluster\" controllerGroup=\"infrastructure.cluster.x-k8s.io\" controllerKind=\"AWSCluster\" AWSCluster=\"openshift-cluster-api-guests/ci-op-bkh1pxfk-3266f-45qjd\" namespace=\"openshift-cluster-api-guests\" name=\"ci-op-bkh1pxfk-3266f-45qjd\" reconcileID=\"f262f46e-8a38-4c96-a940-102acaee7baa\" cluster=\"openshift-cluster-api-guests/ci-op-bkh1pxfk-3266f-45qjd\" revoked-ingress-rules=[{\"description\":\"Bootstrap SSH Access\",\"protocol\":\"tcp\",\"fromPort\":22,\"toPort\":22,\"cidrBlocks\":[\"0.0.0.0/0\"]}] security-group-id=\"sg-09052a567b89797a3\""
time="2024-07-10T13:24:03Z" level=debug msg="I0710 13:24:03.343150     336 recorder.go:104] \"Revoked security group ingress rules [protocol=tcp/range=[22-22]/description=Bootstrap SSH Access] for SecurityGroup \\\"sg-09052a567b89797a3\\\"\" logger=\"events\" type=\"Normal\" object={\"kind\":\"AWSCluster\",\"namespace\":\"openshift-cluster-api-guests\",\"name\":\"ci-op-bkh1pxfk-3266f-45qjd\",\"uid\":\"32d80da0-633e-4bb8-83f6-e7d9c9219b28\",\"apiVersion\":\"infrastructure.cluster.x-k8s.io/v1beta2\",\"resourceVersion\":\"718\"} reason=\"SuccessfulRevokeSecurityGroupIngressRules\""
```
and that's expected because we explicitly remove the bootstrap ssh ingress rule.

Looking at a [different job run without the CAPA bump](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_installer/8722/pull-ci-openshift-installer-master-e2e-aws-ovn/1811514829693784064/artifacts/e2e-aws-ovn/ipi-install-install/artifacts/.openshift_install-1720739048.log) we can see multiple revoke-authorize reconciliations for the same ingress rules.

**Comment by patrickdillon** [comment]
> `e2e-aws-ovn`: looking at the [installer log output](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_installer/8596/pull-ci-openshift-installer-master-e2e-aws-ovn/1811010992612577280/artifacts/e2e-aws-ovn/ipi-install-install/artifacts/.openshift_install-1720618893.log) we see only one revoke:
> 
> ```
> time="2024-07-10T13:24:03Z" level=debug msg="I0710 13:24:03.343095     336 securitygroups.go:181] \"Revoked ingress rules from security group\" controller=\"awscluster\" controllerGroup=\"infrastructure.cluster.x-k8s.io\" controllerKind=\"AWSCluster\" AWSCluster=\"openshift-cluster-api-guests/ci-op-bkh1pxfk-3266f-45qjd\" namespace=\"openshift-cluster-api-guests\" name=\"ci-op-bkh1pxfk-3266f-45qjd\" reconcileID=\"f262f46e-8a38-4c96-a940-102acaee7baa\" cluster=\"openshift-cluster-api-guests/ci-op-bkh1pxfk-3266f-45qjd\" revoked-ingress-rules=[{\"description\":\"Bootstrap SSH Access\",\"protocol\":\"tcp\",\"fromPort\":22,\"toPort\":22,\"cidrBlocks\":[\"0.0.0.0/0\"]}] security-group-id=\"sg-09052a567b89797a3\""
> time="2024-07-10T13:24:03Z" level=debug msg="I0710 13:24:03.343150     336 recorder.go:104] \"Revoked security group ingress rules [protocol=tcp/range=[22-22]/description=Bootstrap SSH Access] for SecurityGroup \\\"sg-09052a567b89797a3\\\"\" logger=\"events\" type=\"Normal\" object={\"kind\":\"AWSCluster\",\"namespace\":\"openshift-cluster-api-guests\",\"name\":\"ci-op-bkh1pxfk-3266f-45qjd\",\"uid\":\"32d80da0-633e-4bb8-83f6-e7d9c9219b28\",\"apiVersion\":\"infrastructure.cluster.x-k8s.io/v1beta2\",\"resourceVersion\":\"718\"} reason=\"SuccessfulRevokeSecurityGroupIngressRules\""
> ```
> 
> and that's expected because we explicitly remove the bootstrap ssh ingress rule.
> 
> Looking at a [different job run without the CAPA bump](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_installer/8722/pull-ci-openshift-installer-master-e2e-aws-ovn/1811514829693784064/artifacts/e2e-aws-ovn/ipi-install-install/artifacts/.openshift_install-1720739048.log) we can see multiple revoke-authorize reconciliations for the same ingress rules.

Awesome!!

**Comment by r4f4** [comment]
/label acknowledge-critical-fixes-only

The changes in upstream CAPA are very small and e2e tests show no regressions. Also this PR should cut down on a lot of extra AWS API calls in CI.

**Pull request merged**
