### PR TITLE
MULTIARCH-4770: bump o/api for MultiArchInstall TechPreview gates

### PR DESCRIPTION
**Pull request by r4f4**
The MultiArchInstallAWS/MultiArchInstallGCP feature gates have been added to the TechPreview feature set.

### CODE REVIEW

**Comment by r4f4** [comment]
TechPreview change in o/api: https://github.com/openshift/api/pull/1973

**Comment by r4f4** [comment]
No regressions:
`e2e-aws-ovn-heterogeneous`: camgi output shows worker nodes are `amd64` and master nodes are `arm64`
`e2e-gcp-ovn-heterogeneous`: same thing ^

**Review by barbacbd — COMMENTED** [review]
/lgtm

**Pull request merged**
