### PR TITLE
OCPBUGS-30642:  Revert "Generate PowerVS machine manifests for CAPI" and subsequent vendoring changes

### PR DESCRIPTION
**Pull request by stbenjam**
Reverts #7546, #8020, #8114; tracked by [TRT-1556](https://issues.redhat.com//browse/TRT-1556)

Reverting the original change, and subsequent vendoring changes that are required for a clean revert.

Per [OpenShift policy](https://github.com/openshift/enhancements/blob/master/enhancements/release/improving-ci-signal.md#quick-revert), we are reverting this breaking change to get CI and/or nightly payloads flowing again.

GCP installs are failing on 4.16.

To unrevert this, revert this PR, and layer an additional separate commit on top that addresses the problem. Before merging the unrevert, please run these jobs on the PR and check the result of these jobs to confirm the fix has corrected the problem:

GCP installs succeed

CC: @qjkee, @hamzy, @r4f4

### CODE REVIEW

**Comment by stbenjam** [comment]
Alternative to https://github.com/openshift/installer/pull/8133

/hold

**Comment by r4f4** [comment]
/retitle OCPBUGS-30642:  Revert "Generate PowerVS machine manifests for CAPI" and subsequent vendoring changes

**Comment by patrickdillon** [comment]
/close 
in favor of #8133

**Pull request closed without merging**
