### PR TITLE
bootstrap: add --infra-config-file to kube-api render

### PR DESCRIPTION
**Pull request by tsorya**
Kube-api operator need to render different params in sno and ha modes.
Installer should provide infrastructure file path for kube-api rendering process

### CODE REVIEW

**Comment by tsorya** [comment]
test e2e-aws-single-node

**Review by eranco74 — COMMENTED** [review]
This PR complete the work done in  https://github.com/openshift/cluster-kube-apiserver-operator/pull/1171
/lgtm

**Pull request merged**
