### PR TITLE
OCPBUGS-18113: Do not set FailureDomains on CPMS when in a single zone Azure region

### PR DESCRIPTION
**Pull request by JoelSpeed**
When there's only a single zone, we do not need to use the `failureDomains` feature of CPMS. In particular, this is causing issue for the westus region where it has no zones, but the CPMS is being created with a single failure domain `zone: ""`. We have a few changes going in that should help to resolve this but we shouldn't really be using the failure domains at all for single zones clusters.

### CODE REVIEW

**Comment by JoelSpeed** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.14-e2e-azure-ovn-upgrade 10
/jira refresh

**Review by r4f4 — COMMENTED** [review]
/lgtm

**Comment by RadekManak** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.14-e2e-azure-ovn-upgrade 10

**Comment by JoelSpeed** [comment]
I think for installer based PRs the upgrade jobs don't help, since the upgrade will be from a previous installer version, I think we will want to run a regular install job to prove this out

**Comment by JoelSpeed** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.14-e2e-azure-ovn 10

**Comment by sadasu** [comment]
/retest

Waiting for ci/prow/e2e-azurestack to pass before approve.

**Comment by JoelSpeed** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.14-e2e-azure-ovn 10

**Comment by JoelSpeed** [comment]
Not a single install on the last run landed in the westus region, lets try that again
/payload-aggregate periodic-ci-openshift-release-master-ci-4.14-e2e-azure-ovn 10

**Comment by DennisPeriquet** [comment]
@JoelSpeed these two jobs in your last `/payload` command went to `westus` and passed: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/openshift-installer-7448-ci-4.14-e2e-azure-ovn/1701245948786642944 https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/openshift-installer-7448-ci-4.14-e2e-azure-ovn/1701245950191734784

**Pull request merged**
