### PR TITLE
[release-4.12] OCPBUGS-7481: Fix file check for loading openshift manifests

### PR DESCRIPTION
**Pull request by rna-afk**
When generating the openshift manifests, it tries to load the dependency control plane asset that creates files in the openshift directory. It then checks to see if the openshift manifest is actually already generated before this by checking the openshift directory for files that are not generated by the machine asset.

The newly created CPMS file was missing from the check, hence the asset loader always thought the asset was generated since there are files that exist other than the machine files and exits but it actually had to be newly generated with 4 files that were crucial to installation.

Adding the CPMS files to the list of machine asset files.

### CODE REVIEW

**Comment by r4f4** [comment]
So this is a manual cherry-pick of https://github.com/openshift/installer/pull/6821 + https://github.com/openshift/installer/pull/6887 ?
We are missing the comment and the warning in https://github.com/openshift/installer/pull/6887. Is that on purpose?

**Comment by rna-afk** [comment]
> We are missing the comment and the warning in https://github.com/openshift/installer/pull/6887. Is that on purpose?

Knew I missed something. Thanks it's fixed.

**Review by r4f4 — COMMENTED** [review]
/lgtm

**Review by jianli-wei — APPROVED** [review]

**Pull request merged**
