### PR TITLE
[DNM] OKD: Combined test of PR #7484 and PR #7634

### PR DESCRIPTION
**Pull request by JM1**
**TEST. DO NOT MERGE**

Combined test of PR #7484 and PR #7634 for OKD/FCOS.

### CODE REVIEW

**Comment by andfasano** [comment]
/test okd-e2e-agent-compact-ipv4

(past job didn't get a resource from ofcir)

**Comment by JM1** [comment]
(need release image to test)

/test okd-e2e-agent-compact-ipv4
/test okd-e2e-agent-sno-ipv6

**Comment by JM1** [comment]
(need release image to test again)

/test okd-e2e-agent-compact-ipv4
/test okd-e2e-agent-sno-ipv6

**Comment by andfasano** [comment]
Let's try also ha flavor:

/test okd-e2e-agent-ha-dualstack

**Comment by andfasano** [comment]
Latest agent compact failures was due etcd operator being degraded, not sure it's related to the current patch

/test okd-e2e-agent-compact-ipv4

**Comment by andfasano** [comment]
All the okd agent jobs are green

/approve

**Comment by JM1** [comment]
Code works as expected. Closing PR and continuing in original PRs.

**Pull request closed without merging**
