### PR TITLE
OCPBUGS-1048: if tag categories don't exist, the installation will fail to bootstrap

### PR DESCRIPTION
**Pull request by rvanderp3**

### CODE REVIEW

**Comment by rvanderp3** [comment]
rebased

**Comment by r4f4** [comment]
@rvanderp3 maybe we can fixup this https://github.com/openshift/installer/pull/6327/commits/75010af68343ea96764fcde8d9a8ca4a5ce0b9f2 with the commit it's fixing?

**Comment by rvanderp3** [comment]
> @rvanderp3 maybe we can fixup this [75010af](https://github.com/openshift/installer/commit/75010af68343ea96764fcde8d9a8ca4a5ce0b9f2) with the commit it's fixing?

@r4f4 I just squashed that commit in to the 'unit tests' commit.  Is that what you were looking for?

**Comment by r4f4** [comment]
> > @rvanderp3 maybe we can fixup this [75010af](https://github.com/openshift/installer/commit/75010af68343ea96764fcde8d9a8ca4a5ce0b9f2) with the commit it's fixing?
> 
> @r4f4 I just squashed that commit in to the 'unit tests' commit. Is that what you were looking for?

Yes, thank you!

/approve

**Pull request merged**
