### PR TITLE
data/data/*/inputs: Drop terraform_remote_state

### PR DESCRIPTION
**Pull request by wking**
We used to use this for passing asset state from the assets step to the infra step.  But the new installer performs all asset generation in Go with a single Terraform step (e.g. see df14588e, #362).  So we'll alwayshave `var.ignition_bootstrap` set and we can just use it directly.

### CODE REVIEW

**Comment by wking** [comment]
/hold

Wait on #379.

**Comment by abhinavdahiya** [comment]
/hold cancel
#379 merged
/retest

**Comment by wking** [comment]
[Hung][1] waiting for the API:

```
Waiting for API at https://ci-op-11frdjx6-1d3f3-api.origin-ci-int-aws.dev.rhcloud.com:6443 to respond ...
Waiting for API at https://ci-op-11frdjx6-1d3f3-api.origin-ci-int-aws.dev.rhcloud.com:6443 to respond ...
Another process exited
2018/09/29 08:32:05 Container test in pod e2e-aws failed, exit code 1, reason Error
2018
```

/retest

[1]: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_installer/373/pull-ci-openshift-installer-master-e2e-aws/268/build-log.txt

**Pull request merged**
