### PR TITLE
Updating architecture diagram based on Dia

### PR DESCRIPTION
**Pull request by cuppett**
Still waiting on #1525 to land. In the meantime, updating the picture in the IPI docs to reflect the private masters and be consistent with the diagram in the UPI docs.

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
https://github.com/openshift/installer/pull/1525 is LGTMed and in merge queue

**Comment by cuppett** [comment]
/hold 

Will add a chaser commit to rebase on #1525 and adopt the SVG output from that.

**Pull request merged**
