### PR TITLE
Bug 2105933: data/data/coreos: update FCOS to 36.20220716.3.1

### PR DESCRIPTION
**Pull request by vrutkovs**
Update FCOS used by OKD to latest stable

### CODE REVIEW

**Comment by vrutkovs** [comment]
/retest

Pod pending timeout

**Comment by jlebon** [comment]
I'll leave this to @travier since he follows more closely OKD happenings.

**Comment by vrutkovs** [comment]
@travier I can haz LGTM?

**Review by travier — APPROVED** [review]

**Pull request merged**
