### PR TITLE
issue-template: Make it easy to remove irrelevant platforms

### PR DESCRIPTION
**Pull request by zeenix**
With the current template, people just fill in the name of their platform, leaving the list of platforms as is. This makes it a bit hard to label issues. Let's modify the template a bit so reporters simply remove the irrelevant platforms from the list and the issue description only mentions the relevant platform.

### CODE REVIEW

**Comment by zeenix** [comment]
/assign @wking 

@wking as agreed on slack. :)

**Comment by mandre** [comment]
I support this :)
It can be quite tricky to filter out irrelevant platforms in github issue search because the current issue template.

**Comment by patrickdillon** [comment]
What about putting the platforms in a comment?  For example: 
```
#Platform: 
<!-- specify below one of aws,  libvirt, or openstack --> 
```
I think this has some advantages. Users filling out the form don't have to delete anything. If they submit the form without deleting the extra platforms it won't make filtering difficult as described https://github.com/openshift/installer/pull/1892#issuecomment-504981979

**Comment by patrickdillon** [comment]
Also should we already be including platforms being actively developed: azure & gcp?

**Comment by zeenix** [comment]
> Also should we include platforms being actively developed: azure & gcp?

I'm afraid i can't answer that question. @abhinavdahiya @wking ?

**Comment by zeenix** [comment]
@patrickdillon PTALA.

**Comment by patrickdillon** [comment]
@zeenix The statement `and REMOVE THIS COMMENT so that description only mentions the
relevant platform.`  is unnecessary, can you remove it? 

The comments will not show up in the form or in search. I think that is the main advantage of moving this change to the comment as you did. Otherwise looks good.

**Comment by zeenix** [comment]
> The statement `and REMOVE THIS COMMENT so that description only mentions the relevant platform.` is unnecessary, can you remove it?

Yes. Sorry, I didn't read your last sentence on https://github.com/openshift/installer/pull/1892#issuecomment-505045180 properly. I disagree and actually that's the whole point of this exercise so that we don't end up with mentions of irrelevant platforms in the issue description, making it harder to filter before the issue is tagged with `platform/libvirt`. The ideal thing would be for some automation though.

**Comment by patrickdillon** [comment]
>  disagree and actually that's the whole point of this exercise so that we don't end up with mentions of irrelevant platforms in the issue description

I think you are misunderstanding. Whether they delete the platforms or not from the comment makes no difference, the platforms will not appear in the issue description or the search either way. So asking the authors to delete the platforms is an extra, unnecessary step. 

That is my understanding and I tried testing it out, it seems to work.

**Comment by zeenix** [comment]
> I think you are misunderstanding. Whether they delete the platforms or not from the comment makes no difference, the platforms will not appear in the issue description or the search either way. So asking the authors to delete the platforms is an extra, unnecessary step.

Oh! The comments are really treated as such by GH, didn't know that. :) In that case, yes i'll update as you suggested and thanks for pointing out. :)

**Comment by zeenix** [comment]
@patrickdillon PTALA.

**Pull request merged**
