### PR TITLE
openstack: make dhcp files available to UPI too

### PR DESCRIPTION
**Pull request by tomassedovic**
The OpenStack provider requires two extra configuration files on the bootstrap node. Without this patch, they're only available to the IPI installer and the UPI process needs to add them to the ignition explicitly.

This makes the UPI process more arduous than it needs to be and it can pose maintenance issues later on.

By moving them under ` data/data/bootstrap/openstack/`, these files will be generated with `openshift-install create ignition-configs` and therefore available to both IPI and UPI.

### CODE REVIEW

**Comment by tomassedovic** [comment]
/test e2e-openstack

This looks like an OpenStack env issue rather than a bug with this patch. Retesting and also re-running it locally.

**Comment by pierreprinetti** [comment]
/lgtm

Clean & tidy!

**Comment by tomassedovic** [comment]
Okay, this worked locally. The "glitch in the OpenStack CI" hypothesis seems to hold up.

**Comment by tomassedovic** [comment]
/hold

We're in a feature freeze and this is a feature. We hold off merging until the 4.4 master opens.

**Comment by abhinavdahiya** [comment]
> /hold
> 
> We're in a feature freeze and this is a feature. We hold off merging until the 4.4 master opens.

we should be okay to merge towards 4.4 now.. Thanks!

/hold cancel

**Pull request merged**
