### PR TITLE
Bug 1798498: gather: enable bootstrap log gathering for baremetal

### LINKED ISSUE #2009: baremetal: Add support for install gather
Original issue from @stbenjam - https://github.com/openshift-metal3/kni-installer/issues/79

---

openshift added debugging - https://github.com/openshift/installer/blob/master/cmd/openshift-install/gather.go - on installation failure.  We need to add support for the baremetal platform.  In order to do that, terraform needs to know the IP's of the bootstrap and master nodes.

This produces some confusing error messages:

```
level=debug msg="Fetching \"Install Config\"..."
level=debug msg="Loading \"Install Config\"..."
level=debug msg="  Loading \"SSH Key\"..."
level=debug msg="  Loading \"Base Domain\"..."
level=debug msg="    Loading \"Platform\"..."
level=debug msg="  Loading \"Cluster Name\"..."
level=debug msg="    Loading \"Base Domain\"..."
level=debug msg="  Loading \"Pull Secret\"..."
level=debug msg="  Loading \"Platform\"..."
level=debug msg="Using \"Install Config\" loaded from state file"
level=debug msg="Reusing previously-fetched \"Install Config\""
level=error msg="Cannot fetch the bootstrap and control plane host addresses from state file for baremetal platform"
level=error msg="boostrap host address and at least one control plane host address must be provided"
```

This isn't the actual failure, it's just a failure to gather debugging data. The real problem should be elsewhere in the log (usually a timeout)

For the masters, we will be able to gather the IP's via introspection data: openshift-metal3/terraform-provider-ironic#28

### PR DESCRIPTION
**Pull request by stbenjam**
This enables bootstrap log gathering for baremetal. We fetch the IP's
for the control plane hosts using ironic introspection data, and use
the provisioning IP for the bootstrap.

fixes #2009

### CODE REVIEW

**Comment by stbenjam** [comment]
/retitle Bug 1798498: gather: enable bootstrap log gathering for baremetal

**Comment by imain** [comment]
It looks good!  It would be nice if we could get info on the ironic containers.  I see you get logs for all containers but ironic stuff isn't in there.  Could be a later patch if deemed reasonable.  Otherwise lgtm.

**Comment by stbenjam** [comment]
> It looks good! It would be nice if we could get info on the ironic containers. I see you get logs for all containers but ironic stuff isn't in there. Could be a later patch if deemed reasonable. Otherwise lgtm.

The container logs should be in bootstrap/pods/, but good call about services, I'll add ironic and the master update service to the list tomorrow.

**Comment by imain** [comment]
> > It looks good! It would be nice if we could get info on the ironic containers. I see you get logs for all containers but ironic stuff isn't in there. Could be a later patch if deemed reasonable. Otherwise lgtm.
> 
> The container logs should be in bootstrap/pods/, but good call about services, I'll add ironic and the master update service to the list tomorrow.

Actually the more I think about it, this could be pretty important.  If there are any problems with ironic (including configuration) they will likely surface during bootstrap since that's its first use.

**Comment by stbenjam** [comment]
> > > It looks good! It would be nice if we could get info on the ironic containers. I see you get logs for all containers but ironic stuff isn't in there. Could be a later patch if deemed reasonable. Otherwise lgtm.
> > 
> > 
> > The container logs should be in bootstrap/pods/, but good call about services, I'll add ironic and the master update service to the list tomorrow.
> 
> Actually the more I think about it, this could be pretty important. If there are any problems with ironic (including configuration) they will likely surface during bootstrap since that's its first use.

I've pushed a change to gather ironic and master-bmh-update logs

**Comment by stbenjam** [comment]
/hold

Hold for now, would like to see CI pass before merging. We're sorting out the issues with it at the moment.

**Comment by hardys** [comment]
After discussion with @stbenjam we agreed to merge this as it will help debug the ongoing issues with the metal-ipi CI

**Comment by stbenjam** [comment]
CI is a mess, we need as much logging as we can at this point.

/hold cancel

**Pull request merged**
