### PR TITLE
Revert "Merge pull request #7096 from r4f4/gcp-instance-zones"

### PR DESCRIPTION
**Pull request by r4f4**
This reverts commit 76a40181107c3d1ee24a95a29f84faee2c35bf73, reversing changes made to 0b68802de63f046d010e9697df7788bf6546b692.

Seems to be causing https://issues.redhat.com/browse/OCPBUGS-16515

### CODE REVIEW

**Comment by r4f4** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-gcp-sdn-serial

**Comment by JoelSpeed** [comment]
In https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_installer/7360/pull-ci-openshift-installer-master-e2e-gcp-ovn/1683409251520745472 we can see that there are now only the A, B, C and F MachineSets, which is to be as expected.
This confirms the suspicion that #7096 was the one to introduce the additional MachineSet in the invalid zone

**Comment by r4f4** [comment]
> In https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_installer/7360/pull-ci-openshift-installer-master-e2e-gcp-ovn/1683409251520745472 we can see that there are now only the A, B, C and F MachineSets, which is to be as expected. This confirms the suspicion that #7096 was the one to introduce the additional MachineSet in the invalid zone

I'm pretty sure https://github.com/openshift/installer/pull/7317/files#diff-5b78d3dce8e57bde6663e00a48292e102afaf1c0893ff084c6244d863a9bbca3R80-R90 should fix it.

**Pull request merged**
