### PR TITLE
never automatically restart bootkube

### LINKED ISSUE #441: bootkube.sh failures should be fatal to CI
Running the installer today, I see this in the bootkube.service on bootstrap node:
```
Oct 09 19:37:38 dev-bootstrap bootkube.sh[800]: Rendering Kubernetes Controller Manager core manifests...
Oct 09 19:37:40 dev-bootstrap bootkube.sh[800]: Trying to pull registry.svc.ci.openshift.org/openshift/origin-v4.0-20181009182333@sha256:0d2b6b3f38be97581dc278ecfb09288ce18448386aa72462ba0081a7961fdc3
Oct 09 19:37:40 dev-bootstrap bootkube.sh[800]: Skipping fetch of repeat blob sha256:256b176beaff7815db2a93ee2071621ae88f451bb1e198ca73010ed5bba79b65
Oct 09 19:37:40 dev-bootstrap bootkube.sh[800]: Copying blob sha256:cb122062656b84ec7bc4bdb038fcae48099cda259bc15dda5280f9cb5dd9dfca
Oct 09 19:37:42 dev-bootstrap bootkube.sh[800]: [103B blob data]
Oct 09 19:37:42 dev-bootstrap bootkube.sh[800]: Copying config sha256:0a875fc5b4928197dbbcde73fe4321b180c56efa110c1a89a56a1ba4caa1474e
Oct 09 19:37:42 dev-bootstrap bootkube.sh[800]: [37B blob data]
Oct 09 19:37:42 dev-bootstrap bootkube.sh[800]: Writing manifest to image destination
Oct 09 19:37:42 dev-bootstrap bootkube.sh[800]: Storing signatures
Oct 09 19:37:43 dev-bootstrap bootkube.sh[800]: Writing asset: /assets/kube-controller-manager-bootstrap/bootstrap-manifests/kube-controller-manager-pod.yaml
Oct 09 19:37:43 dev-bootstrap bootkube.sh[800]: Writing asset: /assets/kube-controller-manager-bootstrap/manifests/fake-checkpointer-daemonset.yaml
Oct 09 19:37:43 dev-bootstrap bootkube.sh[800]: Writing asset: /assets/kube-controller-manager-bootstrap/manifests/kube-controller-manager-daemonset.yaml
Oct 09 19:37:43 dev-bootstrap bootkube.sh[800]: Writing asset: /assets/kube-controller-manager-bootstrap/manifests/00_openshift-kube-controller-manager-ns.yaml
Oct 09 19:37:43 dev-bootstrap bootkube.sh[800]: Writing asset: /assets/kube-controller-manager-bootstrap/manifests/configmap-kube-controller-manager-config.yaml
Oct 09 19:37:43 dev-bootstrap bootkube.sh[800]: cp: cannot stat ‘kube-controller-manager-bootstrap/manifests/secret-*’: No such file or directory
Oct 09 19:37:43 dev-bootstrap systemd[1]: bootkube.service: main process exited, code=exited, status=1/FAILURE
Oct 09 19:37:43 dev-bootstrap systemd[1]: Unit bootkube.service entered failed state.
Oct 09 19:37:43 dev-bootstrap systemd[1]: bootkube.service failed.
Oct 09 19:37:49 dev-bootstrap systemd[1]: bootkube.service holdoff time over, scheduling restart.
Oct 09 19:37:49 dev-bootstrap systemd[1]: Started Bootstrap a Kubernetes cluster.
Oct 09 19:37:49 dev-bootstrap systemd[1]: Starting Bootstrap a Kubernetes cluster...
Oct 09 19:37:49 dev-bootstrap bootkube.sh[2581]: Found Machine Config Operator's image: registry.svc.ci.openshift.org/openshift/origin-v4.0-20181009182333@sha256:4bf64a72c1c118b15bb23b91c2759d5f79f2a8
Oct 09 19:37:51 dev-bootstrap bootkube.sh[2581]: Rendering Kubernetes Scheduler core manifests...
Oct 09 19:37:53 dev-bootstrap bootkube.sh[2581]: Trying to pull registry.svc.ci.openshift.org/openshift/origin-v4.0-20181009182333@sha256:d096f6b5bf225838714b6ce888ceabfcf00ca2a54d8bcf837d8f1566361378
Oct 09 19:37:53 dev-bootstrap bootkube.sh[2581]: Skipping fetch of repeat blob sha256:256b176beaff7815db2a93ee2071621ae88f451bb1e198ca73010ed5bba79b65
Oct 09 19:37:53 dev-bootstrap bootkube.sh[2581]: Copying blob sha256:b36922edad5a0d9fa2c761a061f74c677058247638fc8261fc2ab1c2dfa4ef49
Oct 09 19:37:55 dev-bootstrap bootkube.sh[2581]: [125B blob data]
Oct 09 19:37:55 dev-bootstrap bootkube.sh[2581]: Copying config sha256:0f59f132eeb89848a4c9f6555000f5fd62dd5ef59eba7ee76528e259afb9ec59
Oct 09 19:37:55 dev-bootstrap bootkube.sh[2581]: [37B blob data]
Oct 09 19:37:55 dev-bootstrap bootkube.sh[2581]: Writing manifest to image destination
Oct 09 19:37:55 dev-bootstrap bootkube.sh[2581]: Storing signatures
Oct 09 19:37:56 dev-bootstrap bootkube.sh[2581]: Writing asset: /assets/kube-scheduler-bootstrap/bootstrap-manifests/kube-scheduler-pod.yaml
Oct 09 19:37:56 dev-bootstrap bootkube.sh[2581]: Writing asset: /assets/kube-scheduler-bootstrap/manifests/00_openshift-kube-scheduler-ns.yaml
Oct 09 19:37:56 dev-bootstrap bootkube.sh[2581]: Writing asset: /assets/kube-scheduler-bootstrap/manifests/configmap-kube-scheduler-config.yaml
Oct 09 19:37:56 dev-bootstrap bootkube.sh[2581]: Writing asset: /assets/kube-scheduler-bootstrap/manifests/kube-scheduler-daemonset.yaml
Oct 09 19:37:56 dev-bootstrap bootkube.sh[2581]: cp: cannot stat ‘kube-scheduler-bootstrap/manifests/secret-*’: No such file or directory
Oct 09 19:37:56 dev-bootstrap systemd[1]: bootkube.service: main process exited, code=exited, status=1/FAILURE
Oct 09 19:37:56 dev-bootstrap systemd[1]: Unit bootkube.service entered failed state.
Oct 09 19:37:56 dev-bootstrap systemd[1]: bootkube.service failed.
Oct 09 19:38:01 dev-bootstrap systemd[1]: bootkube.service holdoff time over, scheduling restart.
Oct 09 19:38:01 dev-bootstrap systemd[1]: Started Bootstrap a Kubernetes cluster.
Oct 09 19:38:01 dev-bootstrap systemd[1]: Starting Bootstrap a Kubernetes cluster...
Oct 09 19:38:02 dev-bootstrap bootkube.sh[3405]: Found Machine Config Operator's image: registry.svc.ci.openshift.org/openshift/origin-v4.0-20181009182333@sha256:4bf64a72c1c118b15bb23b91c2759d5f79f2a8
Oct 09 19:38:04 dev-bootstrap bootkube.sh[3405]: Rendering MCO manifests...
```
These failures actually prevent elements of the cluster from starting, but fail silently because the service just restarts bootkube.sh and continues on.   These errors should be fatal I think.

@rphillips

### PR DESCRIPTION
**Pull request by sjenning**
fixes #441 

@rphillips

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
cc @crawford 
we bootkube to restart because sometimes podman ends up in network failures.

**Comment by sjenning** [comment]
what is the nature of these network failures? should we just wrap the podman calls in a retry wrapper rather than rerunning all of `bootkube.sh`?

**Comment by crawford** [comment]
If we disable retries at the service level, every invocation of podman (and any future, failable commands) needs to get retry logic. This also doesn't fix #441. If the issue is that CI didn't catch this, then it is a CI issue. If the issue was that this was difficult to debug, then it is a UX issue.

Also, your commit message format doesn't adhere to the contribution guide. We need a nice description for _why_ the change is being made.

**Comment by rphillips** [comment]
@crawford If there is a script error in bootkube.sh, how do you think this should be handled? bootkube.sh could stop executing anywhere with a partial rollout of a semi-functional cluster.

```Oct 09 19:37:56 dev-bootstrap bootkube.sh[2581]: cp: cannot stat ‘kube-scheduler-bootstrap/manifests/secret-*’: No such file or directory```

**Comment by crawford** [comment]
> If there is a script error in bootkube.sh, how do you think this should be handled? bootkube.sh could stop executing anywhere with a partial rollout of a semi-functional cluster.

It depends on the type of error. If it's something where a retry might help, then it should obviously retry. If it hits something that isn't expected to fail, then I think it's fine if the script exits non-zero and we let systemd and journald bubble up the failure.

**Comment by crawford** [comment]
I'm going to close this out since work seems to have stalled. Feel free to reopen it once the points above have been addressed.

/close

**Pull request closed without merging**
