### PR TITLE
Bug 2082604: Revert "image: set os name to red-coreos-stable-amd64"

### PR DESCRIPTION
**Pull request by cjschaef**
This reverts commit 9f339a3a6f34c0498bb137693f4941669945b7e9.

### CODE REVIEW

**Review by jckasper — APPROVED** [review]

**Comment by MayXuQQ** [comment]
pre-merge test, the bug [2082604](https://bugzilla.redhat.com/show_bug.cgi?id=2082604) resolved, but the nodes is still not ready, https://coreos.slack.com/archives/C01U40AM37F/p1651854679271969?thread_ts=1651843400.106319&cid=C01U40AM37F

**Comment by MayXuQQ** [comment]
pre-merge test, the bug [2082604](https://bugzilla.redhat.com/show_bug.cgi?id=2082604) resolved, but the nodes is still not ready, https://coreos.slack.com/archives/C01U40AM37F/p1651854679271969?thread_ts=1651843400.106319&cid=C01U40AM37F
/label qe-approved
/bugzilla cc-qa

**Review by MayXuQQ — APPROVED** [review]

**Pull request merged**
