### PR TITLE
Bug 1802526: AWS Terraform: use machine_cidr instead of VPC main cidr …

### PR DESCRIPTION
**Pull request by patrickdillon**
This PR:

1. Deprecates `machine_cidr` by creating (moving from Azure) two top-level TF vars for holding IPv4 & IPv6 machine CIDRs. All platforms are updated to use them.
2. Fixes BZ-1802526, where only the main CIDR from an AWS VPC was being added to the security group. This change adds all the IPv4 CIDRs to the SG.

Tested by slightly modifying the UPI 01_vpc.yaml cloudformation template: https://gist.github.com/patrickdillon/9c26636e7d5b500a511252ed7661f343

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
hmm.. the users can provide a list of machine CIDRs... 
so for byo vpc case, we should ask our users to provides all the CIDRs main, additional (which everones they want to use or cluster to know about) as part of the list.

and then in terraform we shuold use the vpc datasource to find all the CIDRs attached to the VPC and use the ones which are part of the user specified list..

**Comment by patrickdillon** [comment]
> hmm.. the users can provide a list of machine CIDRs...
> so for byo vpc case, we should ask our users to provides all the CIDRs main, additional (which everones they want to use or cluster to know about) as part of the list.

I can update terraform to where we accept all CIDRs. Currently we only use the first:
https://github.com/openshift/installer/blob/master/pkg/asset/cluster/tfvars.go#L134

> and then in terraform we shuold use the vpc datasource to find all the CIDRs attached to the VPC and use the ones which are part of the user specified list..

Then we will take the intersection of the VPC cidr block associations and install-config machine cidrs, and use those in the security groups and bootstrap.

> users might specify subnets that are outside the main CIDR or from different ranges of the VPC

The subnets are already validated against the machine cidr. The problem is that we were ignoring the machine cidr for sg and bootstrap node. I will check to see if we need to update validation to use multiple cidrs.

Can you confirm that if we accept multiple machine cidrs, validate subnets are in those cidrs and then use the intersection in bootstrap node and sg that addresses the issue? Otherwise I am missing something.

**Comment by abhinavdahiya** [comment]
so thinking a little bit...

I think we should enable our terraform setup to accept multiple machine_cidrs for byo case and our security groups should be setup to allow traffic from all these specified ones. _so your terraform change currently is fine it just needs to be list instead of one_

And the users should be expected to set all the network ranges for various subnets (_they are not expected to set the range for each subnet i think they can set the network ranges attached to the vpc_ ) they have provided i.e. make sure each subnet provided is part of at least one of the network ranges.

hopefully, that simplifies things a little bit.

**Comment by patrickdillon** [comment]
I have updated this PR (and description) . There are minor changes to several platforms, so I will be watching the e2e tests. I am also running a local test for the bug fix. 

I think it's generally ready for review.

**Comment by patrickdillon** [comment]
Regarding bz-1802526, just finished succesfully testing with this install-config:
```
  machineNetwork:
  - cidr: 10.0.0.0/16
  - cidr: 10.190.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  aws:
    region: us-east-2
    subnets:
    - subnet-022a1f6993b4643a5 #10.190.16.0/20
    - subnet-0e983ba423574af74 #10.190.32.0/20

```

**Comment by patrickdillon** [comment]
removed the updates to vSphere UPI

**Comment by patrickdillon** [comment]
Also successfully tested subnets from different CIDR blocks:
```
machineNetwork:
  - cidr: 10.0.0.0/16
  - cidr: 10.190.0.0/16
platform:
  aws:
    region: us-east-2
    subnets:
    - subnet-069d49a095263da52 # 10.0.48.0/20, private
    - subnet-0e983ba423574af74 # 10.190.32.0/20, public
```

**Comment by patrickdillon** [comment]
/cherry-pick release-4.3

I don't expect this to work, but this seems like an easy way to check.

**Pull request merged**
