### PR TITLE
pkg/tfvars/baremetal: don't hardcode external and provision interfaces

### PR DESCRIPTION
**Pull request by karmab**
Baremetal: get external and provision from configuration

### CODE REVIEW

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/1163/

**Comment by metal3ci** [comment]
Build SUCCESS, see build http://10.8.144.11:8080/job/dev-tools/1180/

**Comment by stbenjam** [comment]
This looks good to me, but small nit, would you mind adjusting the commit message to be a bit more descriptive? See https://github.com/openshift/installer/blob/master/CONTRIBUTING.md#commit-message-format

Something like `pkg/tfvars/baremetal: don't hardcode external and provision interfaces`

**Comment by stbenjam** [comment]
@karmab Did you intend to close this PR? I think it's still needed, isn't it?

**Comment by metal3ci** [comment]
Build SUCCESS, see build http://10.8.144.11:8080/job/dev-tools/1276/

**Pull request merged**
