### PR TITLE
Bug 2098299: Make new machinepool fields pointers+omitempty

### PR DESCRIPTION
**Pull request by 2uasimojo**
install-configs generated with versions of installer libs since fdb10d991 / #5793 would fail to install on 4.10 due to the addition of optional-but-not-omitempty-pointer fields combined with strict unmarshalling that punts on unrecognized fields. Ensure new fields are a) pointer types, and b) `omitempty` so they are not emitted during marshaling if absent from the go object. cf. https://github.com/golang/go/issues/11939

closes: 2098299

### CODE REVIEW

**Comment by rna-afk** [comment]
/retitle Bug 2098299: Make AWS MachinePool EC2Metadata omitempty

**Comment by 2uasimojo** [comment]
/hold

This does *not* fix the problem. The field needs to be made a pointer (or we need to revert `UnmarshalStrict`).

See https://github.com/golang/go/issues/11939 (thanks for the pointer, @wking).

**Comment by 2uasimojo** [comment]
Updated. But let's keep the hold -- [discussing](https://coreos.slack.com/archives/C68TNFWA2/p1655842108884639) how to approach this class of problem more generally.

**Comment by patrickdillon** [comment]
/close
in favor of #6039

**Comment by 2uasimojo** [comment]
> /close in favor of #6039

@patrickdillon the work in this PR is still valid though, isn't it?

**Pull request closed without merging**
