### PR TITLE
prevent send to closed channel

### PR DESCRIPTION
**Pull request by deads2k**
Builds on top of the revert.

The channel closes could race, using a basic lock will not race.

/assign @r4f4

### CODE REVIEW

**Comment by deads2k** [comment]
/hold

still concerned over possible false etcd progressing=true

**Comment by r4f4** [comment]
Don't forget to update https://github.com/openshift/installer/pull/7319/files#diff-56276d5381d618d46ec8d35d93210662c8fdd4c9bcd90fd36afbc6a59227eb0bR830

**Comment by patrickdillon** [comment]
/close

This has been solved in another PR.

**Pull request closed without merging**
