### PR TITLE
Set default release image to 4.7

### PR DESCRIPTION
**Pull request by pierreprinetti**
Align the default release image with the current development version.

### CODE REVIEW

**Comment by pierreprinetti** [comment]
hmm maybe 4.6 has better chances of existing

**Comment by LorbusChris** [comment]
I wonder whether we should go to 4.7 in master directly, and switch to 4.6 only on release-4.6

**Comment by pierreprinetti** [comment]
> I wonder whether we should go to 4.7 in master directly, and switch to 4.6 only on release-4.6

That was my original idea TBH, however

```
$ podman pull registry.svc.ci.openshift.org/origin/release:4.7
Trying to pull registry.svc.ci.openshift.org/origin/release:4.7...
  manifest unknown: manifest unknown
Error: unable to pull registry.svc.ci.openshift.org/origin/release:4.7: Error initializing source docker://registry.svc.ci.openshift.org/origin/release:4.7: Error reading manifest 4.7 in registry.svc.ci.openshift.org/origin/release: manifest unknown: manifest unknown
```

**Comment by staebler** [comment]
> podman pull registry.svc.ci.openshift.org/origin/release:4.7



> > I wonder whether we should go to 4.7 in master directly, and switch to 4.6 only on release-4.6
> 
> That was my original idea TBH, however
> 
> ```
> $ podman pull registry.svc.ci.openshift.org/origin/release:4.7
> Trying to pull registry.svc.ci.openshift.org/origin/release:4.7...
>   manifest unknown: manifest unknown
> Error: unable to pull registry.svc.ci.openshift.org/origin/release:4.7: Error initializing source docker://registry.svc.ci.openshift.org/origin/release:4.7: Error reading manifest 4.7 in registry.svc.ci.openshift.org/origin/release: manifest unknown: manifest unknown
> ```
> 
> Same with `latest`, `master` and `nightly`. Any ideas?

The 4.7 image exists. We should definitely move to 4.7.
```
$ oc image info registry.svc.ci.openshift.org/origin/release:4.7 | head -n4
Name:        registry.svc.ci.openshift.org/origin/release:4.7
Digest:      sha256:bccbfcc0d7c0ce7f1bb5ef5a3dd681cb39501a7c01822d7461440c45554531f8
Media Type:  application/vnd.docker.distribution.manifest.v2+json
Created:     14h ago
```

**Comment by pierreprinetti** [comment]
> Created:     14h ago

:) updated

PTAL @staebler

**Review by staebler — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
