### PR TITLE
Drop sigs.k8s.io/cluster api reference

### PR DESCRIPTION
**Pull request by enxebre**
Drop sigs.k8s.io/cluster api reference and drop package from `vendor`
cc @flaper87

### CODE REVIEW

**Comment by flaper87** [comment]
thanks for the cc, @enxebre 

I'll give this a try with OpenStack

**Comment by abhinavdahiya** [comment]
@enxebre @tomassedovic is this still required or getting worked on?

ping

**Comment by enxebre** [comment]
@abhinavdahiya  after rebasing only remaining changes are for dropping unused library

**Comment by enxebre** [comment]
there was a still reference in openstack, I removed it.

**Comment by abhinavdahiya** [comment]
@enxebre @trown PTAL

Is this still required?

**Comment by abhinavdahiya** [comment]
similar changes in https://github.com/openshift/installer/pull/1872

/close

**Pull request closed without merging**
