### PR TITLE
WIP Log modified and deleted events when waiting for bootstrap to complete

### PR DESCRIPTION
**Pull request by vrutkovs**
This might help when debugging the hanging bootstrap node

### CODE REVIEW

**Comment by wking** [comment]
Why not just log all events, if we're going to open this up?  Did you have paeticular events you expect to see with this?

**Comment by vrutkovs** [comment]
I hope it would log smth like "failed to pull image", which is most likely what breaks CI in most cases

**Comment by wking** [comment]
> I hope it would log smth like "failed to pull image", which is most likely what breaks CI in most cases

Really?  I didn't think the CI registry was *that* buggy.  Can you post an example (possibly via kicking this PR's e2e-aws until you trigger one)?

**Comment by vrutkovs** [comment]
This is getting a bit useful - most modified events are `0/3 nodes are available: 3 node(s) were not ready.`. This shows the known issue - machine-approver operator starts later than usual, so worker CSRs are not approved.

**Pull request closed without merging**
