### PR TITLE
Masters-gather: Include the full logs of failed units

### PR DESCRIPTION
**Pull request by beekhof**
Signed-off-by: Andrew Beekhof <andrew@beekhof.net>

### CODE REVIEW

**Comment by beekhof** [comment]
Not convinced the codegen test failure has anything to do with this PR

**Comment by wking** [comment]
/approve

Forgot I need to do that explicitly for the installer, instead of `/lgtm` implying it.

**Comment by wking** [comment]
Probably copy any changes into `data/data/bootstrap/files/usr/local/bin/installer-gather.sh` too, in case something blows up on the bootstrap machine.

**Comment by beekhof** [comment]
reworked to send journalctl output to its own file

**Comment by ashcrow** [comment]
/retest

(not required, but curious)

**Pull request merged**
