### PR TITLE
data/data/aws/variables-aws: Drop tectonic_aws_worker_ec2_type, etc.

### PR DESCRIPTION
**Pull request by wking**
The last consumers for these were removed by 124ac351 (#119).

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
relates to #743 can we drop worker stuff wholesale in one PR/commit. multiple PRs for same logical thing is :(

**Comment by wking** [comment]
> relates to #743 can we drop worker stuff wholesale in one PR/commit.

I can pull that commit in here.  I split them up because this one's clearly a no-op, while #743 changes the libvirt behavior (althpugh hopefully not in a way that breaks the cluster).

**Comment by wking** [comment]
I've pushed 76b5757 -> 2ef00f2, pulling in the commit from #743.

**Comment by wking** [comment]
I'd forgotten to drop a `data.libvirt_network_dns_host_template.workers` consumer.  Fixed in 2ef00f2 -> 6ccf0f1.

**Pull request merged**
