### PR TITLE
*: remove the deprecated kube-system coreos-pull-secret

### PR DESCRIPTION
**Pull request by abhinavdahiya**
PR https://github.com/openshift/installer/pull/1554 marked kube-system coreos-pull-secret deprecated in favor of openshift-config pull-secret

consumer PRs like https://github.com/openshift/origin/pull/22508 https://github.com/openshift/machine-config-operator/pull/609 should allow removal now.

### CODE REVIEW

**Comment by wking** [comment]
[e2e-aws][1]:

```
level=fatal msg="failed to initialize the cluster: Could not update servicemonitor \"openshift-service-catalog-apiserver-operator/openshift-service-catalog-apiserver-operator\" (288 of 307): the server does not recognize this resource, check extension API servers: timed out waiting for the condition"
```

Discussion in [rhbz#1680201][2].

/retest

[1]: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_installer/1567/pull-ci-openshift-installer-master-e2e-aws/5057
[2]: https://bugzilla.redhat.com/show_bug.cgi?id=1680201

**Comment by wking** [comment]
/lgtm

Although this may not pass until openshift/origin#22508 actually lands (it's currently in the merge queue).

**Comment by wking** [comment]
[e2e-aws][1]:

```
fail [github.com/openshift/origin/test/extended/operators/images.go:28]: Apr 10 21:52:39.464: unable to get pull secret for cluster: secrets "coreos-pull-secret" not found
...
Flaky tests:

[Feature:DeploymentConfig] deploymentconfigs with failing hook [Conformance] should get all logs from retried hooks [Suite:openshift/conformance/parallel/minimal]

Failing tests:

[Feature:Platform][Smoke] Managed cluster should ensure pods use images from our release image with proper ImagePullPolicy [Suite:openshift/conformance/parallel]
[Feature:Prometheus][Conformance] Prometheus when installed on the cluster should start and expose a secured proxy and unsecured metrics [Suite:openshift/conformance/parallel/minimal]
```

/hold

Until openshift/origin#22508 lands.

[1]: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_installer/1567/pull-ci-openshift-installer-master-e2e-aws/5122

**Comment by abhinavdahiya** [comment]
https://github.com/openshift/origin/pull/22508 merged
https://github.com/openshift/cluster-monitoring-operator/pull/315 merged

so ^^ should close the loop on all the consumers.

/hold cancel

**Comment by abhinavdahiya** [comment]
e2e-aws failure: rate limited:
```console
level=error msg="Error: Error applying plan:"
level=error
level=error msg="1 error occurred:"
level=error msg="\t* module.vpc.aws_route.igw_route: 1 error occurred:"
level=error msg="\t* aws_route.igw_route: Error creating route: timeout while waiting for state to become 'success' (timeout: 2m0s)"
```

/retest

**Comment by abhinavdahiya** [comment]
```console
Failing tests:

[Feature:Platform] Managed cluster should have no crashlooping pods in core namespaces over two minutes [Suite:openshift/conformance/parallel]
```

looks like deleting the pull-secret didn't create any problems. :yay:

/retest

**Pull request merged**
