### PR TITLE
PR for making use of openshift/api#1064 changes

### PR DESCRIPTION
**Pull request by bharath-b-rh**

### CODE REVIEW

**Comment by staebler** [comment]
@bharath-b-rh What are you trying to accomplish with this PR? I see that you are vendoring in the changes to openshift/api, but you are not using any of the changes. Is your intention to change the infrastructure manifest, too?
https://github.com/openshift/installer/blob/f6ebd26034c9b07b44f01a389566dbe09d9b4d07/pkg/asset/manifests/infrastructure.go#L111-L121

**Comment by bharath-b-rh** [comment]
> @bharath-b-rh What are you trying to accomplish with this PR? I see that you are vendoring in the changes to openshift/api, but you are not using any of the changes. Is your intention to change the infrastructure manifest, too?
> 
> https://github.com/openshift/installer/blob/f6ebd26034c9b07b44f01a389566dbe09d9b4d07/pkg/asset/manifests/infrastructure.go#L111-L121

@staebler I am working on CFE-52(support for updating AWS tags). I have made changes to Infrastructure manifest too and was using the locally built binary to create cluster. Left this PR open to use the changes and do e2e test with the other components dependent on these changes using cluster-bot.

**Comment by staebler** [comment]
@bharath-b-rh My point is that there is nothing in this PR that changes the installer in any way. You could just as easily use the installer from master to test the changes to the infrastructure CRD.

**Comment by bharath-b-rh** [comment]
@staebler Yeah I agree might waste someone's time when they check it. Let me close this and create a PR with the Infrastructure manifest changes when it's required to be merged.

**Pull request closed without merging**
