### PR TITLE
PowerVS: Create new newAuthenticator function

### PR DESCRIPTION
**Pull request by hamzy**
Since it is easy to not create a new authenticator structure and validate it before every new use, we will create a function which implements this.

### CODE REVIEW

**Comment by r4f4** [comment]
Can you separate the `%v -> %w` changes into their own commit, please?

**Comment by hamzy** [comment]
@r4f4 done! :)

**Comment by r4f4** [comment]
> @r4f4 done! :)

Thanks, that made it easier to review the changes. Also thanks for working on the `%v -> %w` tech debt.

/approve

**Pull request merged**
