### PR TITLE
MGMT-19191: Provide a way to add coreos installer params for installation phase

### PR DESCRIPTION
**Pull request by tsorya**
[MGMT-19191](https://issues.redhat.com//browse/MGMT-19191): Provide a way to add coreos installer params for installation phase
Adding new field CoreosInstallerParams to image based install command to customize coreos installer command in lca cli

### CODE REVIEW

**Comment by eranco74** [comment]
what will happen in case the LCA version in the seed doesn't know this new field?

**Review by javipolo — APPROVED** [review]
LGTM

**Comment by tsorya** [comment]
> what will happen in case the LCA version in the seed doesn't know this new field?

it will work as we don't require strict json, so new fields will be dropped

**Review by r4f4 — COMMENTED** [review]
/approve

**Pull request merged**
