### PR TITLE
update azure arm templates to support customer provided vnet

### PR DESCRIPTION
**Pull request by jianlinliu**
To resolve https://github.com/openshift/release/pull/27977#discussion_r867916077

### CODE REVIEW

**Comment by jianlinliu** [comment]
From the failed "ci/prow/e2e-azure-upi " job log:
```
Adding ingress DNS records
Unable to connect to the server: dial tcp 20.84.231.171:6443: i/o timeout
ERROR: argument --ipv4-address/-a: expected one argument
```
It is a known issue, we are trying to fix it in https://github.com/openshift/release/pull/27977/files#diff-5483a633ffe74be033f28def4e9b0c9adbfb0ec96b53e43ef314e22672b64ae9R1098-R1119

**Comment by patrickdillon** [comment]
/approve

@jianlinliu is there someone else that can LGTM this? If not I will LGTM it.

**Comment by jianlinliu** [comment]
@yuhuijiang @MayXuQQ anyone can help review and give a LGTM here?

**Comment by jianlinliu** [comment]
@patrickdillon now I am using `4.10:upi-installer` to run upi install, to ensure the PR landed into the 4.10 upi-installer, shall I backport the change 4.10 branch?

**Pull request merged**
