### PR TITLE
 [release-4.13] OCPBUGS-10597: fix agent tui showing up multiple times

### PR DESCRIPTION
**Pull request by andfasano**
This patch is to verify the changes initially published in https://github.com/openshift/installer/pull/6977 on the 4.13 branch (specifically the `e2e-agent-*` jobs)

/draft

### CODE REVIEW

**Comment by bfournie** [comment]
Looks like e2e-agent-* tests are passing now.

I assume we will close this out, merge https://github.com/openshift/installer/pull/6977 (potentially with an override since its failing due to the separate "no space left on device" issue, and backport that to 4.13 after it merges?)

**Comment by zaneb** [comment]
/approve

I'm happy to go ahead and link this to https://issues.redhat.com/browse/OCPBUGS-10597 and merge it.

**Pull request merged**
