### PR TITLE
Openstack IPI: Validate API and Ingress VIPs are not the same

### PR DESCRIPTION
**Pull request by gyohuangxin**
https://github.com/openshift/installer/issues/4945

### CODE REVIEW

**Review by mandre — COMMENTED** [review]
/lgtm

Let's wait for master branch to open for new development on June 11th.

**Comment by gyohuangxin** [comment]
> /lgtm
> 
> Let's wait for master branch to open for new development on June 11th.

Thanks, got it.

**Comment by gyohuangxin** [comment]
@mandre Hi, is master branch open to merge?

**Comment by mandre** [comment]
> @mandre Hi, is master branch open to merge?

Yes it is, thanks for the reminder.
/approve

**Comment by gyohuangxin** [comment]
> > @mandre Hi, is master branch open to merge?
> 
> Yes it is, thanks for the reminder.
> /approve

Thank you so much!

**Pull request merged**
