### PR TITLE
OCPBUGS-32292: Remove deprecated replace directives

### PR DESCRIPTION
**Pull request by r4f4**
These replaces were needed at some point to force a bump to a lib version with CVE fixes but we have since moved way past the pinned version.

We should drop them before we run into problems from having deps pinned to versions that are too old. For example, I've seen PRs with the following diff:
```
# golang.org/x/net v0.23.0 => golang.org/x/net v0.5.0
```
which is not really what we want.

### CODE REVIEW

**Comment by r4f4** [comment]
Verified that we're not downgrading any dep with:

```bash
MODS=(github.com/mattn/go-sqlite3 sigs.k8s.io/controller-tools sigs.k8s.io/controller-runtime golang.org/x/crypto golang.org/x/text gopkg.in/yaml.v2 github.com/Masterminds/goutils github.com/prometheus/client_golang golang.org/x/net github.com/containerd/containerd go.mongodb.org/mongo-driver)

for mod in ${MODS[@]}; do
	go list -mod=readonly -m "${mod}"
done

#
github.com/mattn/go-sqlite3 v1.14.15
sigs.k8s.io/controller-tools v0.12.0
sigs.k8s.io/controller-runtime v0.17.2
golang.org/x/crypto v0.21.0
golang.org/x/text v0.14.0
gopkg.in/yaml.v2 v2.4.0
github.com/Masterminds/goutils v1.1.1
github.com/prometheus/client_golang v1.18.0
golang.org/x/net v0.22.0
github.com/containerd/containerd v1.5.2 => github.com/containerd/containerd v1.6.26
go.mongodb.org/mongo-driver v1.14.0
```

**Comment by r4f4** [comment]
Update: I tried all the build variations I could think of but forgot about `go generate`. I've added back the `controller-tools` replace since it's still needed to fix
```
/go/src/github.com/openshift/installer/pkg/ipnet/ipnet.go:18:2: encountered struct field "" without JSON tag in type "IPNet"
```
/hold
For tests and commit squash.

**Comment by r4f4** [comment]
Update: removed `controller-gen` pinning + fixes so it works with the newer version.

/cc @vincepri 
Could you please double check the related changes?

**Comment by r4f4** [comment]
/cc @jcpowermac 
For the vsphere changes.

**Comment by zaneb** [comment]
I'd like to see a Jira ticket for this.

**Comment by r4f4** [comment]
Update: rebased to fix merge conflicts.

Dep versions now:
```
github.com/mattn/go-sqlite3 v1.14.15
sigs.k8s.io/controller-tools v0.12.0
sigs.k8s.io/controller-runtime v0.17.2
golang.org/x/crypto v0.21.0
golang.org/x/text v0.14.0
gopkg.in/yaml.v2 v2.4.0
github.com/Masterminds/goutils v1.1.1
github.com/prometheus/client_golang v1.19.0
golang.org/x/net v0.23.0
github.com/containerd/containerd v1.5.2 => github.com/containerd/containerd v1.6.26
go.mongodb.org/mongo-driver v1.14.0
```

**Comment by r4f4** [comment]
Update: rebased to fix merge conflicts.

**Comment by patrickdillon** [comment]
/approve

needs rebase then I will tag

**Comment by r4f4** [comment]
Update: rebased on master and fixed merge conflicts.

**Comment by r4f4** [comment]
Update: rebased to fix merge conflicts.

**Pull request merged**
