### PR TITLE
Gather Console Logs for GCP & Azure

### PR DESCRIPTION
**Pull request by patrickdillon**
This rebases #5902 and #5904 after #5807 merged. 

/cc @r4f4 

/approve

### CODE REVIEW

**Comment by patrickdillon** [comment]
I added b216585ecf3f15a70a7aa3ec0e8d931d698d10b7 as a way of getting around a build error. It seems like these imports are unused so it is fine to remove them, although I'm not sure I see where exactly the gathers are running `init()` and getting registered. So I would appreciate a second opinion that this is the correct fix.

**Comment by patrickdillon** [comment]
/close
Hm CI is having a build error which I thought I fixed locally and now cannot reproduce locally. Not sure why it is happening in CI and it is late. Will check it out in the morning if I have time.

**Comment by r4f4** [comment]
> I added [b216585](https://github.com/openshift/installer/commit/b216585ecf3f15a70a7aa3ec0e8d931d698d10b7) as a way of getting around a build error. It seems like these imports are unused so it is fine to remove them, although I'm not sure I see where exactly the gathers are running `init()` and getting registered. So I would appreciate a second opinion that this is the correct fix.

These imports are needed so the `init()` inside `pkg/gather/$platform/register.go` can run.

**Pull request closed without merging**
