### PR TITLE
ipv6: Fix joining IP and port number

### PR DESCRIPTION
**Pull request by russellb**
You can't just manually join an IP and port because that will break
with an IPv6 address.  net.JoinHostPort() will do the right thing and
add square brackets around an IPv6 address.

Reported-by: Steven Hardy <shardy@redhat.com>

### CODE REVIEW

**Comment by stbenjam** [comment]
I found a couple other instances with `grep -r "Sprintf(.*http.*:.*)" . | grep -v vendor`, can we fix them here?

- https://github.com/openshift/installer/blob/9e2323181e660a5cc65be4db8b1ec26a5d9d38ef/pkg/tfvars/baremetal/baremetal.go#L62-L63
https://github.com/openshift/installer/blob/9e2323181e660a5cc65be4db8b1ec26a5d9d38ef/pkg/tfvars/baremetal/baremetal.go#L106
- https://github.com/openshift/installer/blob/9e2323181e660a5cc65be4db8b1ec26a5d9d38ef/pkg/asset/machines/baremetal/machines.go#L89

**Comment by stbenjam** [comment]
Maybe this one too?

https://github.com/openshift/installer/blob/master/cmd/openshift-install/gather.go#L121

**Comment by danwinship** [comment]
PR changes look right but maybe add unit tests? All of the places @stbenjam pointed out also look like they need updating. (For the ones with no port the simplest fix would be to explicitly specify port 80 so you can use `net.JoinHostPort`)

**Comment by russellb** [comment]
I've updated this PR to address more places where similar problems existed.  I haven't added unit tests though, since the changes seem pretty trivial.  I'll add them if someone insists, though.  :-)

**Comment by fabianofranz** [comment]
LGTM, reassigning for approval
/assign @wking

**Comment by stbenjam** [comment]
/label platform/baremetal

(For metal3 CI)

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/1424/

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/1425/

**Comment by metal3ci** [comment]
Build SUCCESS, see build http://10.8.144.11:8080/job/dev-tools/1435/

**Comment by russellb** [comment]
4.3 backport is here: https://github.com/openshift/installer/pull/2977

**Pull request merged**
