### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by jjmengze**
fix typo

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
@jjmengze Thanks a lot for the typo fix :tada: 

but can can you update the commit message based on https://github.com/openshift/installer/blob/master/CONTRIBUTING.md#commit-message-format

esp, can you add the `subsystem` so that we see which area of the code the typo was fixed when looking at commit history. Thanks!

**Comment by jjmengze** [comment]
@abhinavdahiya 
Would you be opposed to  close this PR ?

I will modify it to the correct format and resubmit

**Comment by abhinavdahiya** [comment]
Why not just amend and force push? I think that's acceptable for us.

Also if you want to do a new one.. I'm okay with that too. Whatever works best for you.

Thanks!

**Comment by jjmengze** [comment]
cc @abhinavdahiya Would you be opposed to review this PR commit  ? thanks

**Comment by abhinavdahiya** [comment]
> cc @abhinavdahiya Would you be opposed to review this PR commit ? thanks

I'm really sorry for being this nitpicky on this commit, but the current title `fix: fix typo` doesn't provide any information about the changeset.

Can you please re-review the comment and update the title.
https://github.com/openshift/installer/pull/3336#issuecomment-603400801

one example:
` pkg/destroy/bootstrap/bootstrap.go: fix typo`

**Comment by abhinavdahiya** [comment]
> > cc @abhinavdahiya Would you be opposed to review this PR commit ? thanks
> 
> I'm really sorry for being this nitpicky on this commit, but the current title `fix: fix typo` doesn't provide any information about the changeset.
> 
> Can you please re-review the comment and update the title.
> [#3336 (comment)](https://github.com/openshift/installer/pull/3336#issuecomment-603400801)
> 
> one example:
> ` pkg/destroy/bootstrap/bootstrap.go: fix typo`

/close

closing due to inactivity, please feel free to re-open if you think this is still necessary.

**Pull request closed without merging**
