### PR TITLE
OCPBUGS-44230: Add C4A instance types

### PR DESCRIPTION
**Pull request by barbacbd**
** Add the C4A instance type for GCP. This instance type requires a disk type
    of hyperdisk balanced. It is currently under PREVIEW.

** Vendor updates for GCP Machine API Provider in 4.17

This is a manual backport for https://github.com/openshift/installer/pull/9122

### CODE REVIEW

**Review by r4f4 — COMMENTED** [review]
/lgtm

**Comment by patrickdillon** [comment]
Nice work. Looks like machine-api-provider was correctly vendored from release-4.17 branch :+1: 

/approve
/label backport-risk-assessed

**Pull request merged**
