### PR TITLE
Bug 1899175: data/rhcos.json: Update boot images for RHEL 8.3

### PR DESCRIPTION
**Pull request by travier**
amd64:   47.83.202012030221-0
s390x:   47.83.202012030410-0
ppc64le: 47.83.202012030110-0

### CODE REVIEW

**Comment by miabbott** [comment]
`e2e-crc` looks like it has been red for the most recent 40+ runs, so its unlikely this PR is affecting the job status

`e2e-ipi` has had some success recently, so it looks like there may be some impact being felt from this PR.  The bootstrap node appears to be successfully created, but the masters are not able to finish creation.  The logs are a bit sparse around section of the test, so it is not obvious why the masters are failing to be created.

**Comment by sdodson** [comment]
/retitle Bug 1899175: data/rhcos.json: Update boot images for RHEL 8.3

**Comment by sdodson** [comment]
Gateway timeouts pushing release image to CI registry across the board, seems like a CI infra problem, will try again later.

**Comment by sdodson** [comment]
@shardy @stbenjam PTAL at the metal-ipi failures, are these previously known or believed to be related to this change?

**Comment by sdodson** [comment]
@jcpowermac ARe the vsphere tests in line with your expectations for where vsphere is right now or are you concerned about this boot image bump moving forward?

**Comment by stbenjam** [comment]
The metal-ipi failures are possibly related, we're otherwise green on 4.7.

I've kicked off a local install to examine the bootstrap (we didn't collect an install bundle because of https://github.com/openshift/installer/issues/3927).

**Comment by stbenjam** [comment]
From the bootstrap:

```
Dec 01 21:30:55 localhost startironic.sh[11449]: + podman wait -i 1000 ipa-downloader
Dec 01 21:30:55 localhost startironic.sh[11449]: Error: invalid argument "1000" for "-i, --interval" flag: …n 1000
Dec 01 21:30:55 localhost systemd[1]: ironic.service: Main process exited, code=exited, status=125/n/a
```

This RHCOS build shipped with the busted podman that broke backwards compatibility with accepting `podman wait` without units. I had filed a BZ for this as we saw it in RHEL 8.3: https://bugzilla.redhat.com/show_bug.cgi?id=1897282

This very unfortunate bug won't be fixed until 8.4.

https://github.com/openshift/installer/pull/4377 would fix it, but it is not compatible with some very old podmans, which probably isn't an issue for us.

**Comment by stbenjam** [comment]
Something seems messed up with networking

```
error: error creating buildah builder: Error writing blob: error storing blob to file "/var/tmp/storage520951614/1": read tcp 10.129.59.52:53030->172.217.193.128:443: read: connection reset by peer
```

**Comment by stbenjam** [comment]
Looks like the `oc` we use disappeared off mirror.openshift.com sometime around this afternoon.  We (and 35 other jobs in the release repo) use the oc utils from https://mirror.openshift.com/pub/openshift-v4/clients/oc/4.4/linux/oc.tar.gz.  That's just to bootstrap extracting it from the release payload. 

I posted https://github.com/openshift/release/pull/13999 to grab client from somewhere else for now.

**Comment by travier** [comment]
Waiting on https://github.com/openshift/release/pull/14012

**Comment by stbenjam** [comment]
https://github.com/openshift/release/pull/14012 landed

/test e2e-metal-ipi
/test e2e-metal-ipi-ovn-ipv6

**Comment by stbenjam** [comment]
Packet is busy today..  :-\

```
2020/12/02 15:39:54 Acquiring 1 lease(s) for "packet-quota-slice"
2020/12/02 17:00:25 Acquired lease(s) [f04700fa-98c2-4ff1-bdfa-b2a06a6bdff8] for "packet-quota-slice"
```

**Comment by stbenjam** [comment]
Thanks for your patience, IPv4 and v6 metal ipi jobs passed. 

/lgtm

**Comment by sdodson** [comment]
/approve cancel
/test e2e-gcp
/test e2e-azure
Not sure where those statuses went in the list.

**Comment by sdodson** [comment]
/approve
Nevermind, after reviewing the history those jobs completed installation but had e2e failures which we generally accept especially when we're just trying to hit feature freeze and have time to address post install issues later.

**Comment by travier** [comment]
We will need a new image bump for other fixes so I'll place this one on hold until updated and will restart al tests.
/hold

**Comment by miabbott** [comment]
`e2e-aws` hitting capacity issues:

`Error creating VPC: VpcLimitExceeded: The maximum number of VPCs has been reached.`

**Comment by miabbott** [comment]
`e2e-gcp` has been red for the last 3-4 days.  Looks like it has been hitting a combination of:

- https://bugzilla.redhat.com/show_bug.cgi?id=1886922
- https://bugzilla.redhat.com/show_bug.cgi?id=1882750
- https://bugzilla.redhat.com/show_bug.cgi?id=1901982

**Comment by stbenjam** [comment]
Why did the commit from https://github.com/openshift/installer/pull/4377 get pulled out of this PR? I don't think this should be merged without it. If you'll do it separately you'll end up getting some release payloads rejected while 4377 tries to get through CI.

**Comment by travier** [comment]
> Why did the commit from #4377 get pulled out of this PR? I don't think this should be merged without it. If you'll do it separately you'll end up getting some release payloads rejected while 4377 tries to get through CI.

Sorry, I pushed a new version and I had not realized that you had added this commit to this PR. Will push it again.

**Comment by stbenjam** [comment]
> > Why did the commit from #4377 get pulled out of this PR? I don't think this should be merged without it. If you'll do it separately you'll end up getting some release payloads rejected while 4377 tries to get through CI.
> 
> Sorry, I pushed a new version and I had not realized that you had added this commit to this PR. Will push it again.

Oh wasn't me, maybe Scott pushed it :) But should get included here, thanks!

**Comment by sdodson** [comment]
/test e2e-metal
e2e-aws finished the installer, so i'm fine overriding that, I just don't know that we've seen a successful metal upi install

**Comment by sdodson** [comment]
All of the platforms have completed install phase so no reason to block this.

**Pull request merged**
