### PR TITLE
Power VS Install Config changes

### PR DESCRIPTION
**Pull request by 23TNC**
This PR attempts to move Region and Zone out of .powervs/config.json as well as add ResourceGroup to the survey and default to Default.

### CODE REVIEW

**Comment by clnperez** [comment]
remind me why we're writing the apkey to disk if we're requiring that it be set as an env var? Or, are we still prompting for that during `create install-config` so it's not mandatory that it be set as an env var?

**Comment by 23TNC** [comment]
API Key and ID are saved to config.json under .powervs in the users home directory. This does a few things, it prevents requiring the apikey and id every call.  It also ensures its written to disk and available to subsequent calls later in the process and therefore wont prompt for the API Key and ID 3 times.

**Comment by clnperez** [comment]
i forgot about https://github.com/openshift/installer/pull/5734. it's been open for so long. it looks like these two are changing the same functions, so let's get it in first and circle back to cleaning this up

**Comment by barbacbd** [comment]
@23TNC can you squash the commits? There is no need for three commits this small that are all related.

**Comment by clnperez** [comment]
@23TNC did you close this intentionally?

**Comment by barbacbd** [comment]
@23TNC was this reopened as a new PR [here](https://github.com/openshift/installer/pull/6015) ?

**Comment by 23TNC** [comment]
yes

**Pull request closed without merging**
