### PR TITLE
openstack: Switch yaml libs

### PR DESCRIPTION
**Pull request by flaper87**

### CODE REVIEW

**Comment by flaper87** [comment]
/assign @tomassedovic 
/hold

(testing, will remove hold soon)

**Comment by tomassedovic** [comment]
Looks good to me and my installation finished successfully. Happy to merge it once the hold is lifted.

One question: any reason to switch gophercloud/utils to master rather than updating the revision to include https://github.com/gophercloud/utils/pull/75?

**Comment by flaper87** [comment]
> Looks good to me and my installation finished successfully. Happy to merge it once the hold is lifted.
> 
> One question: any reason to switch gophercloud/utils to master rather than updating the revision to include [gophercloud/utils#75](https://github.com/gophercloud/utils/pull/75)?

Thought I'd make dev cycle easier by tracking master for now and then pin it once we're ready to release the opnestack support.

**Comment by flaper87** [comment]
@wking @tomassedovic I think we can get this in

**Pull request merged**
