### PR TITLE
OpenStack: Document the MachineSet resource

### PR DESCRIPTION
**Pull request by pierreprinetti**
Add an example MachineSet with the OpenStack platform-specific
properties.

/label platform/openstack

CC: @maxwelldb

### CODE REVIEW

**Comment by iamemilio** [comment]
Adding this is a good idea. What do you think about documenting the fields like we do in [the customization docs](https://github.com/openshift/installer/blob/master/docs/user/openstack/customization.md#cluster-scoped-properties)?

**Comment by pierreprinetti** [comment]
@iamemilio 
> documenting the fields

Is it OK if we do that next time?

**Comment by iamemilio** [comment]
Yeah sure

**Comment by iamemilio** [comment]
Lgtm, however I think you should add a link to https://github.com/openshift/cluster-api-provider-openstack/blob/master/pkg/apis/openstackproviderconfig/v1alpha1/types.go in a mean time so that users can see the full interface available to them

**Comment by pierreprinetti** [comment]
@iamemilio 
>you should add a link

Good idea! Added. PTAL

**Comment by mandre** [comment]
This example should probably be added to downstream docs at https://docs.openshift.com/container-platform/4.5/machine_management/creating-infrastructure-machinesets.html#creating-infrastructure-machinesets-clouds, cc @maxwelldb

**Comment by pierreprinetti** [comment]
@mandre 

> This example should probably be added to downstream docs

Is this OK? https://docs.openshift.com/container-platform/4.5/machine_management/creating_machinesets/creating-machineset-osp.html

**Comment by maxwelldb** [comment]
Yeah, that's already there, and the source file is OSP-specific. Feel free to make a PR against the docs repo (or just ask me) if you'd like to see changes to it.

**Pull request merged**
