### PR TITLE
WIP Bug 1773108: upi/metal Only configure the first interface

### PR DESCRIPTION
**Pull request by sdodson**
Recent changes[1] mean that critical services wait for
NetworkManager-wait-online.service and the timeout has been increased[2] to
300 seconds which results in significant delays in booting instances
while we wait for the second interface.

1 - https://github.com/openshift/machine-config-operator/pull/1206
2 - https://bugzilla.redhat.com/show_bug.cgi?id=1741296

### CODE REVIEW

**Comment by metal3ci** [comment]
Build SUCCESS, see build http://10.8.144.11:8080/job/dev-tools/1314/

**Comment by sdodson** [comment]
/retitle Bug 1773108: WIP upi/metal: Only configure the first interface

**Comment by sdodson** [comment]
/close
Roll multiple changes into #2695

**Pull request closed without merging**
