### PR TITLE
[wip] Libvirt plugin via golang plugin instead of TAGS=libvirt

### PR DESCRIPTION
**Pull request by dcbw**
@eparis

### CODE REVIEW

**Comment by stbenjam** [comment]
It's an interesting idea but having the installer be a single binary is pretty convenient, how would we distribute the libvirt plugin?

When we talked about this before, we discussed having terraform-provider-libvirt not use C-bindings at all, e.g. https://github.com/digitalocean/go-libvirt. Then even a mac could run the baremetal or libvirt installers.

**Comment by dcbw** [comment]
> It's an interesting idea but having the installer be a single binary is pretty convenient, how would we distribute the libvirt plugin?
> 
> When we talked about this before, we discussed having terraform-provider-libvirt not use C-bindings at all, e.g. https://github.com/digitalocean/go-libvirt. Then even a mac could run the baremetal or libvirt installers.

@stbenjam yeah, that seems like a bunch more work, but would certainly be nicer.

**Comment by dcbw** [comment]
@stbenjam so unfortunately we can't just convert over go go-libvirt in the installer, because github.com/dmacvicar/terraform-provider-libvirt still uses libvirt-go C bindings. And that's a heavy thing to lift.

But the installer is *already* downloaded as a tarball with the binary and a README. Would it be such a big problem to ship a shared object in the Linux build of the installer too?

**Comment by stbenjam** [comment]
> @stbenjam so unfortunately we can't just convert over go go-libvirt in the installer, because github.com/dmacvicar/terraform-provider-libvirt still uses libvirt-go C bindings. And that's a heavy thing to lift.
> 
> But the installer is _already_ downloaded as a tarball with the binary and a README (eg https://openshift-release-artifacts.svc.ci.openshift.org/4.4.0-0.nightly-2020-03-04-191159/). Would it be such a big problem to ship a shared object in the Linux build of the installer too?

We'd need to update `oc` to understand extracting multiple files (not a big deal).  It also affects automation which will be a bigger deal.  For libvirt alone it's probably not bad, but I'm more concerned about baremetal which uses a libvirt bootstrap VM.

If libvirt folks want this, could we keep the TAGS for building openshift-baremetal-install? I really find a single binary more convenient  (it's extractable with oc as well, https://github.com/openshift/oc/pull/52)

What does the plugin buy us? I guess we could stop shipping multiple installer images.

/cc @vrutkovs

**Comment by dcbw** [comment]
Not going to have time to pursue this further...

**Pull request closed without merging**
