### PR TITLE
Bug 1779421: Bump RHCOS to 44.81.202002211631-0

### PR DESCRIPTION
**Pull request by jlebon**
```
./hack/update-rhcos-bootimage.py https://releases-art-rhcos.svc.ci.openshift.org/art/storage/releases/rhcos-4.4/44.81.202002211631-0/x86_64/meta.json amd64
```

This includes cri-o 1.17, as well as OVA fixes for VMWare.

Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1779421
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1804413

```
$ ./differ.py --first-endpoint art --first-version 44.81.202001241431.0 --second-endpoint art --second-version 44.81.202002211631-0
{
    "sources": {
        "44.81.202001241431.0": "https://releases-rhcos-art.cloud.privileged.psi.redhat.com/storage/releases/rhcos-4.4/44.81.202001241431.0/x86_64/commitmeta.json",
        "44.81.202002211631-0": "https://releases-rhcos-art.cloud.privileged.psi.redhat.com/storage/releases/rhcos-4.4/44.81.202002211631-0/x86_64/commitmeta.json"
    },
    "diff": {
        "conmon": {
            "44.81.202001241431.0": "conmon-2.0.9-1.el8.x86_64",
            "44.81.202002211631-0": "conmon-2.0.9-1.rhaos4.4.el8.x86_64"
        },
        "container-selinux": {
            "44.81.202001241431.0": "container-selinux-2.124.0-1.el8.noarch",
            "44.81.202002211631-0": "container-selinux-2.124.0-1.module+el8.1.1+5259+bcdd613a.noarch"
        },
        "containernetworking-plugins": {
            "44.81.202001241431.0": "containernetworking-plugins-0.8.3-1.el8.x86_64",
            "44.81.202002211631-0": "containernetworking-plugins-0.8.3-4.module+el8.1.1+5259+bcdd613a.x86_64"
        },
        "containers-common": {
            "44.81.202001241431.0": "containers-common-0.1.40-2.el8.x86_64",
            "44.81.202002211631-0": "containers-common-0.1.40-8.module+el8.1.1+5351+506397b0.x86_64"
        },
        "cri-o": {
            "44.81.202001241431.0": "cri-o-1.16.2-6.dev.rhaos4.3.git9e3db66.el8.x86_64",
            "44.81.202002211631-0": "cri-o-1.17.0-4.dev.rhaos4.4.gitc3436cc.el8.x86_64"
        },
        "cri-tools": {
            "44.81.202001241431.0": "cri-tools-1.16.1-1.rhaos4.3.el8.x86_64",
            "44.81.202002211631-0": "cri-tools-1.17.0-2.el8.x86_64"
        },
        "fuse-overlayfs": {
            "44.81.202001241431.0": "fuse-overlayfs-0.4.1-1.module+el8.1.0+4081+b29780af.x86_64",
            "44.81.202002211631-0": "fuse-overlayfs-0.7.2-1.module+el8.1.1+5259+bcdd613a.x86_64"
        },
        "glibc": {
            "44.81.202001241431.0": "glibc-2.28-72.el8.x86_64",
            "44.81.202002211631-0": "glibc-2.28-72.el8_1.1.x86_64"
        },
        "glibc-all-langpacks": {
            "44.81.202001241431.0": "glibc-all-langpacks-2.28-72.el8.x86_64",
            "44.81.202002211631-0": "glibc-all-langpacks-2.28-72.el8_1.1.x86_64"
        },
        "glibc-common": {
            "44.81.202001241431.0": "glibc-common-2.28-72.el8.x86_64",
            "44.81.202002211631-0": "glibc-common-2.28-72.el8_1.1.x86_64"
        },
        "grub2-common": {
            "44.81.202001241431.0": "grub2-common-2.02-78.el8.noarch",
            "44.81.202002211631-0": "grub2-common-2.02-78.el8_1.1.noarch"
        },
        "grub2-efi-x64": {
            "44.81.202001241431.0": "grub2-efi-x64-2.02-78.el8.x86_64",
            "44.81.202002211631-0": "grub2-efi-x64-2.02-78.el8_1.1.x86_64"
        },
        "grub2-pc": {
            "44.81.202001241431.0": "grub2-pc-2.02-78.el8.x86_64",
            "44.81.202002211631-0": "grub2-pc-2.02-78.el8_1.1.x86_64"
        },
        "grub2-pc-modules": {
            "44.81.202001241431.0": "grub2-pc-modules-2.02-78.el8.noarch",
            "44.81.202002211631-0": "grub2-pc-modules-2.02-78.el8_1.1.noarch"
        },
        "grub2-tools": {
            "44.81.202001241431.0": "grub2-tools-2.02-78.el8.x86_64",
            "44.81.202002211631-0": "grub2-tools-2.02-78.el8_1.1.x86_64"
        },
        "grub2-tools-extra": {
            "44.81.202001241431.0": "grub2-tools-extra-2.02-78.el8.x86_64",
            "44.81.202002211631-0": "grub2-tools-extra-2.02-78.el8_1.1.x86_64"
        },
        "grub2-tools-minimal": {
            "44.81.202001241431.0": "grub2-tools-minimal-2.02-78.el8.x86_64",
            "44.81.202002211631-0": "grub2-tools-minimal-2.02-78.el8_1.1.x86_64"
        },
        "kernel": {
            "44.81.202001241431.0": "kernel-4.18.0-147.3.1.el8_1.x86_64",
            "44.81.202002211631-0": "kernel-4.18.0-147.5.1.el8_1.x86_64"
        },
        "kernel-core": {
            "44.81.202001241431.0": "kernel-core-4.18.0-147.3.1.el8_1.x86_64",
            "44.81.202002211631-0": "kernel-core-4.18.0-147.5.1.el8_1.x86_64"
        },
        "kernel-modules": {
            "44.81.202001241431.0": "kernel-modules-4.18.0-147.3.1.el8_1.x86_64",
            "44.81.202002211631-0": "kernel-modules-4.18.0-147.5.1.el8_1.x86_64"
        },
        "kernel-modules-extra": {
            "44.81.202001241431.0": "kernel-modules-extra-4.18.0-147.3.1.el8_1.x86_64",
            "44.81.202002211631-0": "kernel-modules-extra-4.18.0-147.5.1.el8_1.x86_64"
        },
        "libarchive": {
            "44.81.202001241431.0": "libarchive-3.3.2-7.el8.x86_64",
            "44.81.202002211631-0": "libarchive-3.3.2-8.el8_1.x86_64"
        },
        "machine-config-daemon": {
            "44.81.202001241431.0": "machine-config-daemon-4.4.0-202001241232.git.1.189a2ca.el8.x86_64",
            "44.81.202002211631-0": "machine-config-daemon-4.4.0-202002211531.git.1.dc52ee1.el8.x86_64"
        },
        "openldap": {
            "44.81.202001241431.0": "openldap-2.4.46-10.el8.x86_64",
            "44.81.202002211631-0": "openldap-2.4.46-11.el8_1.x86_64"
        },
        "openshift-clients": {
            "44.81.202001241431.0": "openshift-clients-4.4.0-202001240656.git.1.db0174c.el8.x86_64",
            "44.81.202002211631-0": "openshift-clients-4.4.0-202002211016.git.1.4f9e05c.el8.x86_64"
        },
        "openshift-hyperkube": {
            "44.81.202001241431.0": "openshift-hyperkube-4.4.0-202001241232.git.0.e552f5f.el8.x86_64",
            "44.81.202002211631-0": "openshift-hyperkube-4.4.0-202002210654.git.0.97c8826.el8.x86_64"
        },
        "openssh": {
            "44.81.202001241431.0": "openssh-8.0p1-3.el8.x86_64",
            "44.81.202002211631-0": "openssh-8.0p1-4.el8_1.x86_64"
        },
        "openssh-clients": {
            "44.81.202001241431.0": "openssh-clients-8.0p1-3.el8.x86_64",
            "44.81.202002211631-0": "openssh-clients-8.0p1-4.el8_1.x86_64"
        },
        "openssh-server": {
            "44.81.202001241431.0": "openssh-server-8.0p1-3.el8.x86_64",
            "44.81.202002211631-0": "openssh-server-8.0p1-4.el8_1.x86_64"
        },
        "openvswitch2.11": {
            "44.81.202001241431.0": "openvswitch2.11-2.11.0-35.el8fdp.x86_64",
            "44.81.202002211631-0": "openvswitch2.11-2.11.0-47.el8fdp.x86_64"
        },
        "podman": {
            "44.81.202001241431.0": "podman-1.6.4-1.el8.x86_64",
            "44.81.202002211631-0": "podman-1.6.4-4.rhaos4.4.el8.x86_64"
        },
        "podman-manpages": {
            "44.81.202001241431.0": "podman-manpages-1.6.4-1.el8.noarch",
            "44.81.202002211631-0": "podman-manpages-1.6.4-4.rhaos4.4.el8.noarch"
        },
        "policycoreutils": {
            "44.81.202001241431.0": "policycoreutils-2.9-3.el8.x86_64",
            "44.81.202002211631-0": "policycoreutils-2.9-3.el8_1.1.x86_64"
        },
        "policycoreutils-python-utils": {
            "44.81.202001241431.0": "policycoreutils-python-utils-2.9-3.el8.noarch",
            "44.81.202002211631-0": "policycoreutils-python-utils-2.9-3.el8_1.1.noarch"
        },
        "python3-policycoreutils": {
            "44.81.202001241431.0": "python3-policycoreutils-2.9-3.el8.noarch",
            "44.81.202002211631-0": "python3-policycoreutils-2.9-3.el8_1.1.noarch"
        },
        "runc": {
            "44.81.202001241431.0": "runc-1.0.0-64.rc9.el8.x86_64",
            "44.81.202002211631-0": "runc-1.0.0-65.rc10.rhaos4.4.el8.x86_64"
        },
        "skopeo": {
            "44.81.202001241431.0": "skopeo-0.1.40-2.el8.x86_64",
            "44.81.202002211631-0": "skopeo-0.1.40-8.module+el8.1.1+5351+506397b0.x86_64"
        },
        "slirp4netns": {
            "44.81.202001241431.0": "slirp4netns-0.4.2-1.git21fdece.el8.x86_64",
            "44.81.202002211631-0": "slirp4netns-0.4.2-4.git21fdece.el8.x86_64"
        },
        "sqlite-libs": {
            "44.81.202001241431.0": "sqlite-libs-3.26.0-3.el8.x86_64",
            "44.81.202002211631-0": "sqlite-libs-3.26.0-4.el8_1.x86_64"
        },
        "sudo": {
            "44.81.202001241431.0": "sudo-1.8.25p1-8.el8_1.x86_64",
            "44.81.202002211631-0": "sudo-1.8.25p1-8.el8_1.1.x86_64"
        },
        "systemd": {
            "44.81.202001241431.0": "systemd-239-18.el8_1.1.x86_64",
            "44.81.202002211631-0": "systemd-239-18.el8_1.2.x86_64"
        },
        "systemd-journal-remote": {
            "44.81.202001241431.0": "systemd-journal-remote-239-18.el8_1.1.x86_64",
            "44.81.202002211631-0": "systemd-journal-remote-239-18.el8_1.2.x86_64"
        },
        "systemd-libs": {
            "44.81.202001241431.0": "systemd-libs-239-18.el8_1.1.x86_64",
            "44.81.202002211631-0": "systemd-libs-239-18.el8_1.2.x86_64"
        },
        "systemd-pam": {
            "44.81.202001241431.0": "systemd-pam-239-18.el8_1.1.x86_64",
            "44.81.202002211631-0": "systemd-pam-239-18.el8_1.2.x86_64"
        },
        "systemd-udev": {
            "44.81.202001241431.0": "systemd-udev-239-18.el8_1.1.x86_64",
            "44.81.202002211631-0": "systemd-udev-239-18.el8_1.2.x86_64"
        },
        "toolbox": {
            "44.81.202001241431.0": "toolbox-0.0.5-1.rhaos4.2.el8.noarch",
            "44.81.202002211631-0": "toolbox-0.0.6-1.rhaos4.4.el8.noarch"
        },
        "authselect": {
            "44.81.202001241431.0": "Not present",
            "44.81.202002211631-0": "authselect-1.1-2.el8.x86_64"
        },
        "authselect-libs": {
            "44.81.202001241431.0": "Not present",
            "44.81.202002211631-0": "authselect-libs-1.1-2.el8.x86_64"
        }
    }
}
```

### CODE REVIEW

**Comment by jlebon** [comment]
I didn't include the bugzilla references in the title since those aren't actually fixed until it's backported to 4.4.

**Comment by mrunalp** [comment]
@abhinavdahiya ptal.

**Comment by abhinavdahiya** [comment]
> I didn't include the bugzilla references in the title since those aren't actually fixed until it's backported to 4.4.

i think we need a BZ in modified on 4.5 to merge an change to 4.4..

**Comment by rphillips** [comment]
/retitle Bug 1779421: Bump RHCOS to 44.81.202002211631-0

**Comment by rphillips** [comment]
/cherry-pick release-4.4

Use Bug #1806000 for the cherry-pick

**Comment by metal3ci** [comment]
Build SUCCESS, see build http://10.8.144.11:8080/job/dev-tools/1530/

**Pull request merged**
