### PR TITLE
Bug 1711533: Remove unnecessary binding to system:discovery

### PR DESCRIPTION
**Pull request by enj**
The same binding exists in the bootstrap RBAC policy of the
openshift kube API server.  As we work towards tightening the rules
that are assigned to system:unauthenticated, we need to consolidate
where those rules are applied.

Signed-off-by: Monis Khan <mkhan@redhat.com>

xref: https://github.com/openshift/origin/pull/23049

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
I would like to not move ahead with this PR until we merge a change that provides the same effect when upgrading a cluster.

**Comment by enj** [comment]
> I would like to not move ahead with this PR until we merge a change that provides the same effect when upgrading a cluster.

These permissions will still be applied by KAS until I finish with https://github.com/openshift/origin/pull/23049 - there is no value in this binding being here.  It simply makes it impossible for me to make progress on Bug 1711533.

**Comment by deads2k** [comment]
> I would like to not move ahead with this PR until we merge a change that provides the same effect when upgrading a cluster.

@abhinavdahiya As a general statement, permissions like this are generally granted during kube-apiserver bootstrap.  Looking at file history, this appears to be a crufty leftover from an existing bootstrap flow that may not have been properly self-provisioning roles.

**Comment by abhinavdahiya** [comment]
> > I would like to not move ahead with this PR until we merge a change that provides the same effect when upgrading a cluster.
> 
> These permissions will still be applied by KAS until I finish with [openshift/origin#23049](https://github.com/openshift/origin/pull/23049) - there is no value in this binding being here. It simply makes it impossible for me to make progress on Bug 1711533.



> > I would like to not move ahead with this PR until we merge a change that provides the same effect when upgrading a cluster.
> 
> @abhinavdahiya As a general statement, permissions like this are generally granted during kube-apiserver bootstrap. Looking at file history, this appears to be a crufty leftover from an existing bootstrap flow that may not have been properly self-provisioning roles.

Both these make sense, but 4.1.0 ships with discovery allowed for unauthenticated. So to make sure **all** clusters to discovery not allowed to unauthenticated. This needs a migration path to reconcile all clusters to this new state.

And @enj I do not think it is in interest of anybody for maintaining 2 kinds of openshift clusters installed at 4.1.0 that have previous behavior, while clusters installed at 4.2.0 (_based on where this change ends up) with new behavior.

**Comment by enj** [comment]
> This needs a migration path to reconcile all clusters to this new state.

We have never managed RBAC in this way because we do not know who added the rules or subjects.  All old RBAC is effectively permanent today, as it has been since the beginning of the project.

I do not even know if OpenShift will work correctly in this configuration (something may rely on unauthenticated access), but I do not see a point in blocking this change on the 4.1 case.

If we feel strongly enough, I can wire a subset of the RBAC reconciliation to tighten these specific bindings, but first let me actually figure out if it work at all.

**Comment by deads2k** [comment]
> @deads2k @enj
> Both these make sense, but 4.1.0 ships with discovery allowed for unauthenticated. So to make sure **all** clusters to discovery not allowed to unauthenticated. This needs a migration path to reconcile all clusters to this new state.
> 
> And @enj I do not think it is in interest of anybody for maintaining 2 kinds of openshift clusters installed at 4.1.0 that have previous behavior, while clusters installed at 4.2.0 (_based on where this change ends up) with new behavior.

@abhinavdahiya Let's stop the bleed first and then work on what to do about old data.  Because we're tightening, we can be assured that code written against new cluster will run on migrated clusters.  And because we don't remove permissions today, we are assured that code deployed on clusters running today will continue running.

This step is necessary regardless of which decision we make about reconciliation (and I'm leaning towards, "leave existing clusters as they are").  Even merging this change, doesn't instantly change the state, we have to make that choice in origin.

The creation of the clusterrolebinding here shouldn't be done here even if we decide to keep discovery open.

**Comment by abhinavdahiya** [comment]
> Even merging this change, doesn't instantly change the state, we have to make that choice in origin.

/approve

**Comment by smarterclayton** [comment]
/hold

I need a commitment that this gets fixed in 4.2 for 4.1 clusters.

Please open a blocking bug for 4.2 that 4.1 -> 4.2 clusters end up consistent with 4.2 clusters.

**Comment by smarterclayton** [comment]
Top level principle - this is an API change, it is different in 4.2 from 4.1, in a 4.1 -> 4.2 upgrade I expect it to be consistent, and the team making the API change own the upgrade process that keeps it consistent.

 Burden of proof will be to keep all 4.2 clusters consistent.

**Pull request merged**
