### PR TITLE
Bug 1998643: Revert "bump RHCOS boot images for 4.9"

### PR DESCRIPTION
**Pull request by ardaguclu**
`e2e-metal-ipi-ovn-ipv6` and `e2e-metal-ipi-ovn-dualstack` jobs are failing in bootstrap stage. Service network endpoint can not be up and pods are crashlooping.

This PR reverts https://github.com/openshift/installer/pull/5168

### CODE REVIEW

**Comment by ardaguclu** [comment]
@ashcrow @miabbott investigations continue but so far there is no clue yet what is causing this network problem. It can not complete cluster setup within installer timeout, but on local after waiting more(of course getting the same error as CI jobs), it becomes ready.

**Comment by miabbott** [comment]
I really don't like the idea of reverting the boot image without knowing the underlying root cause, but if we are blocked on shipping in this state, it seems like this is the best path forward.

/approve

**Comment by patrickdillon** [comment]
/approve 

@miabbott I am giving high-level installer approval. I will leave it to you to lgtm

**Comment by miabbott** [comment]
One thing to note is that we have identified another blocker in RHCOS that we need a new boot image update to fully solve - https://bugzilla.redhat.com/show_bug.cgi?id=1999577

Which means we need to sort out the underlying problem that required us to pursue this revert before we can fully fix BZ#1999577

I'm going to give the `/lgtm` in hopes that we can unblock other folks from more reliable CI jobs, but we really need to understand the root cause that is requiring us to revert.

cc: @ardaguclu @hardys 

/lgtm

**Comment by ashcrow** [comment]
@ardaguclu @hardys please keep us updated with your debugging. Note that https://bugzilla.redhat.com/show_bug.cgi?id=1999577 is also related to bare metal installs.

**Pull request merged**
