### PR TITLE
IP address should be specified without underscore.

### PR DESCRIPTION
**Pull request by bortek**
Just tested it and it did not work worn with underscore but works without.

### CODE REVIEW

**Comment by dcbw** [comment]
/ok-to-test
/lgtm

PR is correct; ifcfg key for the main IP address is definitely `IPADDR` without underscore.

**Comment by bortek** [comment]
@dcbw Not sure why it is stuck now on tide - Pending. Can you help ?

**Comment by bortek** [comment]
Can anyone take a look at tide as it seems to be unresponsive/hanging.

**Comment by abhinavdahiya** [comment]
ping @jcpowermac for review

**Pull request merged**
