### PR TITLE
Bug 1965969: aws: Output public zone id correctly when deleting hosted dns records

### PR DESCRIPTION
**Pull request by squidboylan**
fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1965969

### CODE REVIEW

**Comment by patrickdillon** [comment]
doh I tested the wrong platform. azure on the brain

/test e2e-aws-shared-vpc

**Review by staebler — APPROVED** [review]
/lgtm

**Comment by staebler** [comment]
/hold

I cannot find the expected output in the deprovision logs.

**Comment by staebler** [comment]
> /hold
> 
> I cannot find the expected output in the deprovision logs.

/hold cancel

Nevermind. We don't have e2e coverage for this yet. (https://github.com/openshift/release/pull/19310)

**Pull request merged**
