### PR TITLE
[gcp] pkg/asset/cluster - add gcp metadata

### PR DESCRIPTION
**Pull request by csrwng**

### CODE REVIEW

**Comment by csrwng** [comment]
@abhinavdahiya ptal
With this and https://github.com/openshift/installer/pull/1964 we get to the point that terraform is invoked. Currently failing with:
```
ERROR                                              
ERROR Error: Unassigned variable                   
ERROR                                              
ERROR The input variable "gcp_image_id" has not been assigned a value. This is a bug 
ERROR in Terraform; please report it in a GitHub issue. 
ERROR                                              
ERROR Failed to read tfstate: open /var/folders/7g/lc7lmfxd329196hpr8r3b77w0000gn/T/openshift-install-152218221/terraform.tfstate: no such file or directory 
FATAL failed to fetch Cluster: failed to generate asset "Cluster": failed to create cluster: failed to apply using Terraform 
```

**Comment by abhinavdahiya** [comment]
> @abhinavdahiya ptal
> With this and #1964 we get to the point that terraform is invoked. Currently failing with:
> 
> ```
> ERROR                                              
> ERROR Error: Unassigned variable                   
> ERROR                                              
> ERROR The input variable "gcp_image_id" has not been assigned a value. This is a bug 
> ERROR in Terraform; please report it in a GitHub issue. 
> ERROR                                              
> ERROR Failed to read tfstate: open /var/folders/7g/lc7lmfxd329196hpr8r3b77w0000gn/T/openshift-install-152218221/terraform.tfstate: no such file or directory 
> FATAL failed to fetch Cluster: failed to generate asset "Cluster": failed to create cluster: failed to apply using Terraform 
> ```

that's the lack of os image for GCP.

**Pull request merged**
