### PR TITLE
Bug 1915617: update boot images for various fixes

### PR DESCRIPTION
**Pull request by bgilbert**
See the dependencies of [RHBZ 1915617](https://bugzilla.redhat.com/show_bug.cgi?id=1915617) for the list of fixes.

| Platform | Version |
| - | - |
| amd64 | 47.83.202101161239-0 |
| ppc64le | 47.83.202101161312-0 |
| s390x | 47.83.202101160310-0 |

### CODE REVIEW

**Comment by Prashanth684** [comment]
> See the dependencies of [RHBZ 1915617](https://bugzilla.redhat.com/show_bug.cgi?id=1915617) for the list of fixes.
> 
> Platform	Version
> amd64	47.83.202101122253-0
> ppc64le	47.83.202101122210-0
> s390x	47.83.202101130012-0

is there a reason why the s390x image is one from the 13th and not the 12th ?

**Comment by bgilbert** [comment]
> is there a reason why the s390x image is one from the 13th and not the 12th ?

That's the build whose package set matches the amd64 one.  But I see that the ppc64le build doesn't match the others; will update.

**Comment by miabbott** [comment]
`e2e-aws` hitting VPC quota issues; there's ongoing investigation/mitigation happening in Slack

`e2e-gcp` appears to be hitting issues creating IAM roles

**Review by staebler — COMMENTED** [review]
/approve

**Comment by bgilbert** [comment]
/hold

for https://github.com/coreos/fedora-coreos-config/pull/815 and https://github.com/openshift/os/pull/485.

**Comment by bgilbert** [comment]
Those changes have landed.  Now blocked on [RHBZ 1916502](https://bugzilla.redhat.com/show_bug.cgi?id=1916502).

**Comment by bgilbert** [comment]
Updated.

/hold cancel

**Comment by miabbott** [comment]
The `e2e-vsphere` test appears to be hitting https://bugzilla.redhat.com/show_bug.cgi?id=1904684, which will be fixed in a new version of `oc` it seems.  (And it looks like a test-only failure problem)

In other words, not related to this PR.

**Pull request merged**
