### PR TITLE
Bug 1791993: proxy: use explicit list of platforms for metadata addresses

### PR DESCRIPTION
**Pull request by stbenjam**
The installer creates a manifest for proxy configuration, automatically
adding specific addresses to NO_PROXY depending on the platform. One of
those addresses is the metadata service, hosted at 169.254.169.254. The
installer assumes this must be done for all platforms other than None of
vSphere, whereas the cluster-network-operator has an explicit list of
platforms:

https://github.com/openshift/cluster-network-operator/blob/adaf257b4d63661726443ab2b059a9b4209a02d1/pkg/util/proxyconfig/no_proxy.go#L67-L69

When using a proxy with baremetal IPI, the installer adds this address,
however when the CNO comes up, it does not, causing the rendered
machine configs to differ, and installation to fail, with MCO reporting
errors like:

```
pool master has not progressed to latest configuration: configuration
status for pool master is empty: pool is degraded because nodes fail
with "3 nodes are reporting degraded status on sync": "Node master-1 is
reporting: \"machineconfig.machineconfiguration.openshift.io
\\\"rendered-master-982b8698753da7e31b5f902aa4dc135e\\\" not found\""
```

This needs a better, longer term solution to ensure the installer and
CNO are not creating conflicting proxy objects, however as a short-term
fix that is easily backportable to 4.3 to ensure proxies work on
baremetal, this syncs the two lists between the installer and CNO.

### CODE REVIEW

**Comment by cgwalters** [comment]
Ahh, that's the bug behind https://github.com/openshift/machine-config-operator/pull/1376 ?

It feels like the cleanest fix here is to add the CNO into the bootstrap phase explicitly, rather than duplicate what it's doing in Terratform?

**Comment by cgwalters** [comment]
Excellent commit message (as usual) BTW!

And just for completeness here's the exact code in the CNO: https://github.com/openshift/cluster-network-operator/blob/adaf257b4d63661726443ab2b059a9b4209a02d1/pkg/util/proxyconfig/no_proxy.go#L67

**Comment by stbenjam** [comment]
> Ahh, that's the bug behind [openshift/machine-config-operator#1376](https://github.com/openshift/machine-config-operator/pull/1376) ?
> 
> It feels like the cleanest fix here is to add the CNO into the bootstrap phase explicitly, rather than duplicate what it's doing in Terratform?

That sounds like the right solution, however given that this affects 4.3, and we have some users affected by this, do you think there's a chance we could sync the two lists of platforms for now, and then work on a longer term fix?

**Comment by cgwalters** [comment]
> do you think there's a chance we could sync the two lists of platforms for now, and then work on a longer term fix?

Yep, I 100% agree with landing this fix as is now.

**Comment by stbenjam** [comment]
4.3 BZ is 1791995

**Comment by stbenjam** [comment]
I didn't hit save :man_facepalming: 

/bugzilla refresh

**Comment by wking** [comment]
/approve

Maybe we need explicit approval now?

**Comment by abhinavdahiya** [comment]
Hmm there are more clouds than none/baremetal so this metadata ip being added to default and none/baremetal opting out seems like a maintainable solution imo.

**Comment by stbenjam** [comment]
> Hmm there are more clouds than none/baremetal so this metadata ip being added to default and none/baremetal opting out seems like a maintainable solution imo.

I am fine with either approach, but this change has the benefit of only requiring 1 change instead of 2.

What did you think of @cgwalters suggestion? IMHO I agree the best approach is not having the same thing done in two different codebases and avoid introducing this risk of conflict at all. https://github.com/openshift/installer/pull/2939#issuecomment-575326769

**Pull request merged**
