### PR TITLE
OCPBUGS-15844: Enable FIPS in agent ISO

### PR DESCRIPTION
**Pull request by zaneb**

### CODE REVIEW

**Comment by andfasano** [comment]
I've not been able to deploy a cluster usign the latest 4.15 nightly, but the issue (CrashLoopBack on openshift-ingress) didn't appear to be related to the current patch

/lgtm

**Review by rwsu — APPROVED** [review]
4.14 nightly worked for me. 
/approve since it is targeting 4.14

**Review by rwsu — COMMENTED** [review]
/lgtm

**Pull request merged**
