### PR TITLE
pkg/types/installconfig: Bump v1beta4 to v1

### PR DESCRIPTION
**Pull request by wking**
We're locking ourselves in for stability going forward.  Hopefully we got this right ;).

CC @abhinavdahiya, @crawford

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
/hold
@mstaebler and me were discussing on pruning the install config before we make it v1

Also need to talk with hive team.

**Comment by wking** [comment]
> Also need to talk with hive team.

We need them on board before we can drop v1beta3 support, but we don't need that to stabilize on v1, do we?

**Comment by crawford** [comment]
Actually, it looks like this isn't a strict requirement for Beta 4. We should still go ahead with the planned pruning, but we can go with `v1beta5` with the hopes that it will become `v1`.

**Comment by sdodson** [comment]
> Actually, it looks like this isn't a strict requirement for Beta 4. We should still go ahead with the planned pruning, but we can go with `v1beta5` with the hopes that it will become `v1`.

@jwforres @crawford is that still accurate? I thought we were being asked to publish v1.

**Comment by wking** [comment]
Rebased onto master with 48952b78f -> befde3c23 (no conflicts).

**Comment by jwforres** [comment]
@sdodson It is not a requirement for beta 4, we need to be on v1 for API freeze which is about getting deployed to Starter

**Pull request merged**
