### PR TITLE
OCPBUGS-24473: IBMCloud: Set IBM TF visibility based on URLs

### PR DESCRIPTION
**Pull request by cjschaef**
Set the IBM Cloud Terraform visibility mode based on whether
any ServiceEndpoints are suspected to be private (or direct for COS),
based on their URL's.

Related: https://issues.redhat.com/browse/OCPBUGS-24473

### CODE REVIEW

**Comment by cjschaef** [comment]
/retitle OCPBUGS-24473: IBMCloud: Set IBM TF visibility based on URLs

**Comment by cjschaef** [comment]
The failures in `e2e-ibmcloud-ovn` are affected by this bug
https://issues.redhat.com/browse/OCPBUGS-25246

/test okd-e2e-aws-ovn-upgrade

**Comment by MayXuQQ** [comment]
with service_endpoint_COS: "https://s3.eu-gb.cloud-object-storage.appdomain.cloud"
pre-merge test PASS 
pre-merge info: https://storage.googleapis.com/origin-ci-test/logs/release-openshift-origin-installer-launch-aws-modern/1735138980858433536/build-log.txt

**Pull request merged**
