### PR TITLE
vendor: Bump OpenShift API to Add Alibaba Platform

### PR DESCRIPTION
**Pull request by patrickdillon**
```
go mod edit -require=github.com/openshift/api@master \
            -replace=k8s.io/client-go=k8s.io/client-go@v0.22.0 \
            -replace=k8s.io/kube-openapi=k8s.io/kube-openapi@v0.0.0-20210305001622-591a79e4bda7
```
Bumps the OpenShift & k8s APIs. There seems to be a breaking change
in kube-openshift which breaks our kubevirt.io dependencies. I'm pinning
this to the earlier kube-openapi until these dependencies can be
updated.

cc @kwoodson 

I believe this is a functional solution. I'm marking this as a work in progress as I am still looking into this breaking change from the kube-openapi, which were introduced, I believe in kubernetes/kube-openapi#234

### CODE REVIEW

**Comment by patrickdillon** [comment]
@sttts I wonder if you could take a look, as you were involved with the upstream PRs: 

It seems like the upstream API change to remove go-openapi, kubernetes/kube-openapi#234 has broken one of our dependencies, [kubervirt/containerized-data-importer](https://github.com/kubevirt/containerized-data-importer).

When I update the API & client-go
``` 
$ go mod edit -require=github.com/openshift/api@master -replace=k8s.io/client-go=k8s.io/client-go@v0.22.0
```
I start getting compilation errors all similar to this:
```
# kubevirt.io/containerized-data-importer/pkg/apis/core/v1alpha1
vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1alpha1/openapi_generated.go:56:3: cannot use "github.com/go-openapi/spec".Schema{...} (type "github.com/go-openapi/spec".Schema) as type "k8s.io/kube-openapi/pkg/validation/spec".Schema in field value
```
So it seems this API change and removal of go-openapi is causing a failure in this generated code here as it is attempting to use go-openapi instead of kube-openapi: https://github.com/kubevirt/containerized-data-importer/blob/release-v1.12/pkg/apis/core/v1alpha1/openapi_generated.go#L26

Are issues like this expected? I have resolved the issue in this PR by replacing the kube-openapi version with one that is compatible with our dependency. Presumably this will be pinned until the dependency is fixed (the installer does not depend on kube-openapi). Do you think this is an acceptable fix or have any further suggestions?

**Comment by patrickdillon** [comment]
/retitle vendor: Bump OpenShift API to Add Alibaba Platform

Removing this from WIP as it seems like this is an accepted way to deal with these dependencies. @jhixson74 PTAL

I do need to add a comment in the code explaining the dependency

Replaces #5198

**Comment by kwoodson** [comment]
@patrickdillon Thanks for the help with this. I was able to build the Alibaba PR #5018 on top of this PR and get the code to compile.

/lgtm

**Comment by kwoodson** [comment]
@patrickdillon 
Test e2e-aws failed with this. This seems unrelated to this PR.
```
could not resolve inputs: could not determine inputs for step [input:rhel-7]: could not resolve base image from ocp/4.10:base-7: imagestreamtags.image.openshift.io "4.10:base-7" not found
```
Test okd-unit failed with similar message but I believe the test might be out-of-date?
```
could not resolve inputs: could not determine inputs for step [input:rhel-7]: could not resolve base image from ocp/4.9:base-7: imagestreamtags.image.openshift.io "4.9:base-7" not found
```
There must be an issue with the `base-7` image tag.

**Comment by clnperez** [comment]
@kwoodson -- hopefully this https://github.com/openshift/release/pull/22103 fixed these issues and you can retest successfully.

**Comment by kwoodson** [comment]
@patrickdillon Looks like we will be dependent on this https://github.com/openshift/installer/pull/5235

**Comment by patrickdillon** [comment]
/hold
need to look at failing okd-unit test

**Comment by kwoodson** [comment]
@patrickdillon Looks like a vendor issue in the okd unit test?
```
vendor/k8s.io/client-go/plugin/pkg/client/auth/exec/metrics.go:21:2: cannot find package "." in:
	/go/src/github.com/openshift/installer/vendor/io/fs
{"component":"entrypoint","error":"wrapped process failed: exit status 1","file":"prow/entrypoint/run.go:80","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2021-09-27T15:46:16Z"}
2/3 Tests Passed!
expand_more
```

**Comment by patrickdillon** [comment]
> @patrickdillon Looks like a vendor issue in the okd unit test?
> 
> ```
> vendor/k8s.io/client-go/plugin/pkg/client/auth/exec/metrics.go:21:2: cannot find package "." in:
> 	/go/src/github.com/openshift/installer/vendor/io/fs
> {"component":"entrypoint","error":"wrapped process failed: exit status 1","file":"prow/entrypoint/run.go:80","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2021-09-27T15:46:16Z"}
> 2/3 Tests Passed!
> expand_more
> ```

Correct but I don't understand the issue. Why is it only failing on the okd-unit test? It looks like this okd-unit test is using a different image with go 1-14 but I'm not that familiar with these tests.

**Comment by patrickdillon** [comment]
> > @patrickdillon Looks like a vendor issue in the okd unit test?
> > ```
> > vendor/k8s.io/client-go/plugin/pkg/client/auth/exec/metrics.go:21:2: cannot find package "." in:
> > 	/go/src/github.com/openshift/installer/vendor/io/fs
> > {"component":"entrypoint","error":"wrapped process failed: exit status 1","file":"prow/entrypoint/run.go:80","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2021-09-27T15:46:16Z"}
> > 2/3 Tests Passed!
> > expand_more
> > ```
> 
> Correct but I don't understand the issue. Why is it only failing on the okd-unit test? It looks like this okd-unit test is using a different image with go 1-14 but I'm not that familiar with these tests.

Looks like that package may require go 1-16, so maybe we need to update the okd-unit images

**Comment by patrickdillon** [comment]
let's retry this once openshift/release#22357 lands

**Pull request merged**
