### PR TITLE
bootkube: drop phase 2 for controller manager

### PR DESCRIPTION
**Pull request by deads2k**
rebased version of https://github.com/openshift/installer/pull/580 which was already lgtm'd

### CODE REVIEW

**Comment by deads2k** [comment]
@sttts fyi for your morning, since you're asleep now.

**Comment by deads2k** [comment]
well @sttts based on time, it looks like it still fails.  Have fun while I'm asleep.

**Comment by abhinavdahiya** [comment]
[logs.txt](https://github.com/openshift/installer/files/2540784/logs.txt)
The controller manager is not progessing
```console
[core@ip-10-0-13-174 ~]$ sudo oc --config /opt/tectonic/auth/kubeconfig get pods --all-namespaces
NAMESPACE                              NAME                                                              READY     STATUS             RESTARTS   AGE
kube-system                            kube-dns-787c975867-wrgrv                                         3/3       Running            0          1h
kube-system                            kube-flannel-54czw                                                2/2       Running            1          1h
kube-system                            kube-flannel-5czns                                                2/2       Running            0          1h
kube-system                            kube-flannel-l8jdh                                                2/2       Running            0          1h
kube-system                            kube-flannel-mm58d                                                2/2       Running            0          1h
kube-system                            kube-flannel-n2cgp                                                2/2       Running            1          1h
kube-system                            kube-flannel-sffl7                                                2/2       Running            1          1h
kube-system                            kube-proxy-6dp2b                                                  1/1       Running            0          1h
kube-system                            kube-proxy-fjrcm                                                  1/1       Running            0          1h
kube-system                            kube-proxy-h87ps                                                  1/1       Running            0          1h
kube-system                            kube-proxy-rsqps                                                  1/1       Running            0          1h
kube-system                            kube-proxy-rx56s                                                  1/1       Running            0          1h
kube-system                            kube-proxy-trt7b                                                  1/1       Running            0          1h
kube-system                            kube-scheduler-5fsw2                                              1/1       Running            0          1h
kube-system                            kube-scheduler-rw6rd                                              1/1       Running            0          1h
kube-system                            kube-scheduler-tm86z                                              1/1       Running            0          1h
kube-system                            metrics-server-5767bfc576-hnpc9                                   2/2       Running            0          1h
kube-system                            tectonic-network-operator-fwmhg                                   1/1       Running            0          1h
kube-system                            tectonic-network-operator-gjplw                                   1/1       Running            0          1h
kube-system                            tectonic-network-operator-tdkrh                                   1/1       Running            0          1h
openshift-apiserver                    apiserver-gtv8g                                                   1/1       Running            0          1h
openshift-apiserver                    apiserver-r9f2k                                                   1/1       Running            0          1h
openshift-apiserver                    apiserver-w2j6x                                                   1/1       Running            0          1h
openshift-cluster-api                  clusterapi-manager-controllers-57d4cdd58f-lxrgd                   2/2       Running            0          1h
openshift-cluster-api                  machine-api-operator-b98c7f744-vxwrc                              1/1       Running            0          1h
openshift-cluster-version              cluster-version-operator-9rtmh                                    1/1       Running            0          1h
openshift-cluster-version              cluster-version-operator-f76q5                                    1/1       Running            0          1h
openshift-cluster-version              cluster-version-operator-zmwtv                                    1/1       Running            0          1h
openshift-controller-manager           controller-manager-4x7mh                                          0/1       CrashLoopBackOff   13         1h
openshift-controller-manager           controller-manager-6h5d7                                          1/1       Running            12         1h
openshift-controller-manager           controller-manager-cfkjn                                          1/1       Running            14         1h
openshift-core-operators               openshift-cluster-kube-apiserver-operator-68d844d8f4-qtgmm        1/1       Running            0          1h
openshift-core-operators               openshift-cluster-kube-controller-manager-operator-76df5f8kh9nx   1/1       Running            0          1h
openshift-core-operators               openshift-cluster-kube-scheduler-operator-68d67f84c7-gt62n        1/1       Running            0          1h
openshift-core-operators               openshift-cluster-openshift-apiserver-operator-64fccf776f-l9vs8   1/1       Running            0          1h
openshift-core-operators               openshift-cluster-openshift-controller-manager-operator-8578wfv   1/1       Running            0          1h
openshift-core-operators               openshift-service-cert-signer-operator-549bbccf46-mvscp           1/1       Running            0          1h
openshift-kube-apiserver               installer-1-ip-10-0-0-148.ec2.internal                            0/1       Completed          0          1h
openshift-kube-apiserver               installer-1-ip-10-0-30-47.ec2.internal                            0/1       Completed          0          1h
openshift-kube-apiserver               installer-1-ip-10-0-34-33.ec2.internal                            0/1       Completed          0          1h
openshift-kube-apiserver               openshift-kube-apiserver-ip-10-0-0-148.ec2.internal               1/1       Running            0          1h
openshift-kube-apiserver               openshift-kube-apiserver-ip-10-0-30-47.ec2.internal               1/1       Running            0          1h
openshift-kube-apiserver               openshift-kube-apiserver-ip-10-0-34-33.ec2.internal               1/1       Running            0          1h
openshift-kube-controller-manager      installer-1-ip-10-0-0-148.ec2.internal                            0/1       Completed          0          1h
openshift-kube-controller-manager      installer-1-ip-10-0-30-47.ec2.internal                            0/1       Completed          0          1h
openshift-kube-controller-manager      installer-1-ip-10-0-34-33.ec2.internal                            0/1       Completed          0          1h
openshift-kube-controller-manager      openshift-kube-controller-manager-ip-10-0-0-148.ec2.internal      1/1       Running            0          1h
openshift-kube-controller-manager      openshift-kube-controller-manager-ip-10-0-30-47.ec2.internal      1/1       Running            0          1h
openshift-kube-controller-manager      openshift-kube-controller-manager-ip-10-0-34-33.ec2.internal      1/1       Running            0          1h
openshift-kube-scheduler               scheduler-69bc96c66b-g58rr                                        1/1       Running            0          1h
openshift-machine-config-operator      machine-config-controller-864996fcb7-bj242                        1/1       Running            0          1h
openshift-machine-config-operator      machine-config-daemon-58jn9                                       1/1       Running            0          1h
openshift-machine-config-operator      machine-config-daemon-k2mdk                                       1/1       Running            0          1h
openshift-machine-config-operator      machine-config-daemon-l2f2s                                       1/1       Running            0          1h
openshift-machine-config-operator      machine-config-daemon-r277g                                       1/1       Running            0          1h
openshift-machine-config-operator      machine-config-daemon-r9hsg                                       1/1       Running            0          1h
openshift-machine-config-operator      machine-config-daemon-wx9ww                                       1/1       Running            0          1h
openshift-machine-config-operator      machine-config-operator-5f4c687c88-pltf7                          1/1       Running            0          1h
openshift-machine-config-operator      machine-config-server-2fmqq                                       1/1       Running            0          1h
openshift-machine-config-operator      machine-config-server-f5q6h                                       1/1       Running            0          1h
openshift-machine-config-operator      machine-config-server-t7ghl                                       1/1       Running            0          1h
openshift-operator-lifecycle-manager   catalog-operator-6cd4db4d7b-tb7tf                                 1/1       Running            0          1h
openshift-operator-lifecycle-manager   olm-operator-8898b97f8-hms27                                      1/1       Running            0          1h
openshift-operator-lifecycle-manager   package-server-748dc6f76-8rjds                                    1/1       Running            0          1h
openshift-service-cert-signer          apiservice-cabundle-injector-bbc898857-kq7kr                      1/1       Running            0          1h
openshift-service-cert-signer          configmap-cabundle-injector-6556bfbd88-bvpw7                      1/1       Running            0          1h
openshift-service-cert-signer          service-serving-cert-signer-845f6c9447-4dgfn                      1/1       Running            0          1h
tectonic-system                        kube-addon-operator-654588755f-7bs5l                              1/1       Running            0          1h
```

**Comment by sttts** [comment]
I see a green run here locally. Everything as expected.

**Comment by wking** [comment]
@sttts is awake again, so back to #580 ;).

/close

**Pull request closed without merging**
