### PR TITLE
OpenStack CI: add awscli to the CI image

### PR DESCRIPTION
**Pull request by tomassedovic**
The OpenStack CI will use Route 53 to create the DNS records necessary
for the tests. We will use the `awscli` tool to create and delete them.

### CODE REVIEW

**Comment by tomassedovic** [comment]
The image builds fine but I'd like to test I can actually use it to add/remove the DNS records before merging.

Keeping WIP until that's done.

**Comment by tomassedovic** [comment]
Tested it locally, the `aws` command is there and works fine.

**Comment by mandre** [comment]
The CI was green on last run, and only the commit message changed since then.

**Pull request merged**
