### PR TITLE
Remove bootstrap.ign template and use the config from ignition provider

### PR DESCRIPTION
**Pull request by yussufsh**
The `httpHeaders` field support is added in the recent provider version.
This PR removes the template file usage and uses the provider configuration with replace spec.

### CODE REVIEW

**Comment by yussufsh** [comment]
Terraform snippet from powervs install debug log:
```
DEBUG module.vm.ibm_cos_bucket_object.ignition: Creating...
DEBUG module.vm.ibm_cos_bucket_object.ignition: Creation complete after 4s [id=crn:v1:bluemix:public:cloud-object-storage:global:a/c265c8cefda241ca9c107adcbbacaa84:a406c676-9e8e-4e36-b5e8-34b16f5af74c:bucket:yus-igntest-t48wc-bootstrap-ign:objec
t:bootstrap.ign:location:ca-tor]
DEBUG module.vm.data.ignition_config.redirect: Reading...
DEBUG module.vm.data.ignition_config.redirect: Read complete after 0s [id=d6db385ddcf0dcb62672184f0926c854da3b769f82631d4f357523d7dc10f59d]
DEBUG module.vm.ibm_pi_instance.bootstrap: Creating...
DEBUG module.lb.ibm_is_lb_pool.bootstrap_pool: Still creating... [30s elapsed]
DEBUG module.vm.ibm_pi_instance.bootstrap: Still creating... [10s elapsed]
DEBUG module.lb.ibm_is_lb_pool.bootstrap_pool: Still creating... [40s elapsed]
DEBUG module.vm.ibm_pi_instance.bootstrap: Still creating... [20s elapsed]
DEBUG module.lb.ibm_is_lb_pool.bootstrap_pool: Still creating... [50s elapsed]
```

**Comment by yussufsh** [comment]
Terraform console snippet from ibmcloud install debug log:
```
DEBUG ibm_cos_bucket.bootstrap_ignition: Creation complete after 8s [id=crn:v1:bluemix:public:cloud-object-storage:global:a/c265c8cefda241ca9c107adcbbacaa84:52820c31-b114-44b0-8dec-ba57ee189480:bucket:yus-igntest-2jpz4-bootstrap-ignition:meta:rl:jp-tok:public]
DEBUG ibm_cos_bucket_object.bootstrap_ignition: Creating...
DEBUG ibm_is_security_group.bootstrap: Still creating... [10s elapsed]
DEBUG ibm_cos_bucket_object.bootstrap_ignition: Creation complete after 2s [id=crn:v1:bluemix:public:cloud-object-storage:global:a/c265c8cefda241ca9c107adcbbacaa84:52820c31-b114-44b0-8dec-ba57ee189480:bucket:yus-igntest-2jpz4-bootstrap-ignition:object:bootstrap.ign:location:jp-tok]
DEBUG data.ignition_config.redirect: Reading...
DEBUG data.ignition_config.redirect: Read complete after 0s [id=27db7131dac37b4f873689e7eb613d3e2e7c8392dc8a9d686a9a54d0c5ab2c2d]
DEBUG ibm_is_security_group.bootstrap: Creation complete after 18s [id=r022-3de811a7-aa4c-4d17-a2b8-5c2aa874fa86]
DEBUG ibm_is_security_group_rule.bootstrap_ssh_inbound[0]: Creating...
DEBUG ibm_is_instance.bootstrap_node: Creating...
```

**Comment by sadasu** [comment]
@yussufsh are you looking into the failures in ci/prow/e2e-ibmcloud-ovn?

**Comment by yussufsh** [comment]
> @yussufsh are you looking into the failures in ci/prow/e2e-ibmcloud-ovn?

I am not sure how to debug that the failure... I see `Error creating: pods "ibm-vpc-block-csi-node-" is forbidden`. Don't think it is related to this PR. Do you know how can I find and fix them?

**Comment by yussufsh** [comment]
/test e2e-aws-ovn
The AWS test is not reporting back I think.
```
{"component":"entrypoint","file":"k8s.io/test-infra/prow/entrypoint/run.go:173","func":"k8s.io/test-infra/prow/entrypoint.Options.ExecuteProcess","level":"error","msg":"Entrypoint received interrupt: terminated","severity":"error","time":"2023-11-10T14:08:20Z"}
```

**Comment by yussufsh** [comment]
@sadasu @rvanderp3  ptal again, thanks. I did rebase this PR with the latest changes.

**Comment by mjturek** [comment]
@yussufsh took a quick look, the changes look good but can you confirm that you've tried this end to end? Thanks!

**Comment by yussufsh** [comment]
> @yussufsh took a quick look, the changes look good but can you confirm that you've tried this end to end? Thanks!

Yes @mjturek  evidence was posted initially at https://github.com/openshift/installer/pull/7471#issuecomment-1708404434

**Comment by sadasu** [comment]
Isn't powerVs and IBMCloud moving away from terraform? Do you still need these changes?

**Comment by yussufsh** [comment]
yes had created this issue long ago but due to unknown build failures and repeated approval request this could not go in. 👎

**Pull request closed without merging**
