### PR TITLE
MULTIARCH-4515: Bump version dependency and address new files for agent-based installer

### PR DESCRIPTION
**Pull request by AmadeusPodvratnik**
Bump assisted-image-service to make feature available.

New feature added (new endpoints for LPAR support on s390x architecture).

### CODE REVIEW

**Comment by AmadeusPodvratnik** [comment]
@pawanpinjarkar , @AnnaZivkovic would it be possible that you can have a look into this PR. Thank you.

**Comment by andfasano** [comment]
Looks like it's missing a ` go mod vendor`?

**Comment by AmadeusPodvratnik** [comment]
> Looks like it's missing a ` go mod vendor`?

I did a go mod vendor, too. I just redo a "go mod tidy" and "go mod vendor" but the result is the same.

**Comment by andfasano** [comment]
> > Looks like it's missing a ` go mod vendor`?
> 
> I did a go mod vendor, too. I just redo a "go mod tidy" and "go mod vendor" but the result is the same.

Ok, a reason could be that the new changes (by looking at the diffs between the selected commits https://github.com/openshift/assisted-image-service/compare/82517255ca17..1362d5b6f4e7) are not currently used by the installer, and this could produced an "empty" vendored PR (as in this case): only the `isoeditor` and `overlay` modules are currently referenced in the [vendor/modules.txt](https://github.com/openshift/installer/blob/3a7f60abf8af3c3814be8c46d65e850ca38dc21a/vendor/modules.txt#L995-L996).

**Comment by AmadeusPodvratnik** [comment]
> > > Looks like it's missing a ` go mod vendor`?
> > 
> > 
> > I did a go mod vendor, too. I just redo a "go mod tidy" and "go mod vendor" but the result is the same.
> 
> Ok, a reason could be that the new changes (by looking at the diffs between the selected commits https://github.com/openshift/assisted-image-service/compare/82517255ca17..1362d5b6f4e7) are not currently used by the installer, and this could produced an "empty" vendored PR (as in this case): only the `isoeditor` and `overlay` modules are currently referenced in the [vendor/modules.txt](https://github.com/openshift/installer/blob/3a7f60abf8af3c3814be8c46d65e850ca38dc21a/vendor/modules.txt#L995-L996).

The patch is addressing a feature (two new endpoints needed to get two files to support LPAR on s390x). The code for the agend-based installer will follow.

**Comment by andfasano** [comment]
> > > > Looks like it's missing a ` go mod vendor`?
> > > 
> > > 
> > > I did a go mod vendor, too. I just redo a "go mod tidy" and "go mod vendor" but the result is the same.
> > 
> > 
> > Ok, a reason could be that the new changes (by looking at the diffs between the selected commits https://github.com/openshift/assisted-image-service/compare/82517255ca17..1362d5b6f4e7) are not currently used by the installer, and this could produced an "empty" vendored PR (as in this case): only the `isoeditor` and `overlay` modules are currently referenced in the [vendor/modules.txt](https://github.com/openshift/installer/blob/3a7f60abf8af3c3814be8c46d65e850ca38dc21a/vendor/modules.txt#L995-L996).
> 
> The patch is addressing a feature (two new endpoints needed to get two files to support LPAR on s390x). The code for the agend-based installer will follow.

I'd suggest to followup directly in this PR, in a separate commit, otherwise the vendored code will remain empty

**Pull request closed without merging**
