### PR TITLE
OCPBUGS-15238: GCP: ic: client: use a higher context timeout

### PR DESCRIPTION
**Pull request by r4f4**
We are probably being too optimistic with timeouts like 30s and 1min for API calls. If your account happens to have access to thousands of projects, the API calls can easily exceed that. Let's settle in 2min for now.

I also used the opportunity to fix a few instances where the context passed as parameter was being ignored.

### CODE REVIEW

**Review by barbacbd — COMMENTED** [review]
/lgtm 

Let's hope that this is enough time. Only the QE project will let us know.

**Comment by r4f4** [comment]
Update: removed spurious gofmt change. No change in functionality.

**Comment by r4f4** [comment]
/retitle OCPBUGS-15238: GCP: ic: client: use a higher context timeout

**Review by jianli-wei — APPROVED** [review]

**Pull request merged**
