### PR TITLE
vsphere capv testing - do not merge

### PR DESCRIPTION
**Pull request by jcpowermac**
We are unable to create periodics for the installer repo as an automated process will remove them, this is the alternative.

This PR is open just for a CronJob (vsphere build cluster) to run github cli every 3 hours to comment `altinfra-e2e-vsphere-capi-ovn`

### CODE REVIEW

**Comment by jcpowermac** [comment]
test

**Comment by jcpowermac** [comment]
```
error: unable to read image registry.apps.build02.vmc.ci.openshift.org/ci-op-ycx0j8l2/stable@sha256:7942b3c547a7a77a3392ae5e96353d3deb550452eade9573ab58fa910654211c: unknown: unable to pull manifest from quay.io/openshift/ci@sha256:7942b3c547a7a77a3392ae5e96353d3deb550452eade9573ab58fa910654211c: Get "https://quay.io/v2/openshift/ci/manifests/sha256:7942b3c547a7a77a3392ae5e96353d3deb550452eade9573ab58fa910654211c": received unexpected HTTP status: 502 Bad Gateway
```
/test altinfra-e2e-vsphere-capi-zones

**Comment by jcpowermac** [comment]
/payload-job-with-prs altinfra-e2e-vsphere-capi-zones github.com/openshift/api/pull/1806

**Comment by jcpowermac** [comment]
/payload-job-with-prs altinfra-e2e-vsphere-capi-zones openshift/api#1806

**Comment by patrickdillon** [comment]
@jcpowermac are you pinging these tests from a parisian hotel room? 

I talked to TRT and I think you just got unlucky that your periodic was removed: we should be able to add a periodic and I'm about to open a PR, but I don't see vsphere passing any of the tests. Does it make sense to add a periodic at this stage?

**Comment by patrickdillon** [comment]
Just opened the PR to add AWS periodic: https://github.com/openshift/release/pull/50438

**Comment by jcpowermac** [comment]
> @jcpowermac are you pinging these tests from a parisian hotel room? 
> 
> 
> 
> I talked to TRT and I think you just got unlucky that your periodic was removed: we should be able to add a periodic and I'm about to open a PR, but I don't see vsphere passing any of the tests. Does it make sense to add a periodic at this stage?

@patrickdillon 
Lol nope. It's running the GitHub client on the vSphere ci cluster as a cronjob. When a left Only a few tests were failing that seemed to be attributed to customnoupgrade.

**Pull request closed without merging**
