### PR TITLE
no-jira: Capv bump to v1.11.1

### PR DESCRIPTION
**Pull request by jcpowermac**

### CODE REVIEW

**Comment by jcpowermac** [comment]
/close

in favor of @vr4manta upcoming pr with govmomi based changes

**Comment by jcpowermac** [comment]
requires
https://github.com/openshift/installer/pull/9062

**Comment by patrickdillon** [comment]
Probably need to bump https://github.com/openshift/installer/blob/master/data/data/cluster-api/vsphere-infrastructure-components.yaml too right?

**Comment by jcpowermac** [comment]
> Probably need to bump https://github.com/openshift/installer/blob/master/data/data/cluster-api/vsphere-infrastructure-components.yaml too right?

is there an easy way to do that? probably missed that in the last bump tbh

cc: @vr4manta

**Review by r4f4 — COMMENTED** [review]
/approve

**Pull request merged**
