### PR TITLE
OPNET-415: Upgrade o/api to include extended network config

### PR DESCRIPTION
**Pull request by mkowalski**
Infra CR allows now to more extensive configuration of host networking (implemented as https://github.com/openshift/api/pull/1695).

This PR gets those changes into the installer.

We are forcefully making `k8s.io/api` and `k8s.io/apimachinery` to stay at `v0.28.3` because their bump to `v0.29.0` should happen as a separate task.

### CODE REVIEW

**Comment by mkowalski** [comment]
/cc @JoelSpeed 
/cc @cybertron

As reviewers of the o/api change
 
/cc @zaneb

As approver of installer

**Review by bbethell-1 — APPROVED** [review]

**Comment by sadasu** [comment]
@mkowalski are additional changes required within the Installer while generating the Infra manifest for the platforms that are  updated with the opnshift/api changes?

**Comment by mkowalski** [comment]
> are additional changes required within the Installer while generating the Infra manifest for the platforms that are updated with the opnshift/api changes?

@sadasu, once this PR with API update merges I will ask for review of https://github.com/openshift/installer/pull/7604 which is responsible for filling the new fields.

The reason I don't do it in a single PR is that it is not mandatory to have those new fields with values immediately, thus merging the API update without code updating new values is not going to break anything

**Review by cybertron — COMMENTED** [review]
/lgtm

**Pull request merged**
