### PR TITLE
ovirt: Update to latest cluster-api-provider

### PR DESCRIPTION
**Pull request by rgolangh**

### CODE REVIEW

**Comment by rgolangh** [comment]
@patrickdillon PTAL

**Comment by patrickdillon** [comment]
What is the motivation for this? Unless I'm missing something this change has no effect. If the intention is to be up-to-date, perhaps it makes more sense to switch to `branch="master"`.

**Comment by iamemilio** [comment]
The previous revision is an invalid hash, which prevents the usage of dep in the installer repo.

**Comment by patrickdillon** [comment]
> The previous revision is an invalid hash, which prevents the usage of dep in the installer repo.

confirmed...

```
# on master branch
$ rm -rf vendor
$ dep ensure
grouped write of manifest, lock and vendor: error while writing out vendor tree: failed to write dep tree: failed to export github.com/ovirt/cluster-api-provider-ovirt: fatal: failed to unpack tree object f7b0ebc7f9ae17c0d5d5b4f5795a1b70972a5570
: exit status 128

```
/lgtm

**Comment by rgolangh** [comment]
please don't merged I want to update to the openshift/cluster-api-provider-ovirt repo

**Comment by sdodson** [comment]
> please don't merged I want to update to the openshift/cluster-api-provider-ovirt repo

ok, anytime you have an outstanding PR that you don't want to merge make sure that the title says WIP which will prevent it from merging and also defer review until you're ready

**Comment by iamemilio** [comment]
Should be ok to remove the hold
/hold cancel

**Pull request merged**
