### PR TITLE
libvirt: Delete volumes & storage pool directory

### LINKED ISSUE #2074: Images not getting removed on cluster destruction
# Version

```console
$ openshift-install version
bin/openshift-install unreleased-master-1404-ge090d19dda2ba9d80dba652e168fcc8ed54f1b55
built from commit e090d19dda2ba9d80dba652e168fcc8ed54f1b55
release image registry.svc.ci.openshift.org/origin/release:4.2
```

# Platform:

libvirt

# What happened?

Seems I introduced a regression in https://github.com/openshift/installer/pull/1956 so our custom pool gets deleted on cluster destruction but the images and the dir are not deleted. The issue is probably in terraform-libvirt-provider side but I need to investigate first.

/assign
/label platform-libvirt

### PR DESCRIPTION
**Pull request by zeenix**
Two patches that ensures we delete the volumes and storage pool when destroying the relevant cluster.

Fixes #2074.

### CODE REVIEW

**Comment by zeenix** [comment]
I think I've a better patch that will push soon.

/hold

**Comment by zeenix** [comment]
/unhold

PTAL

**Comment by praveenkumar** [comment]
Tested it out and works as expected. 

```
# ls /var/lib/libvirt/openshift-images/
nested-f2whd/ nested-tzl6f/

$ openshift-install destroy cluster --dir clusters/nested/                                                                                       
INFO Deleted domain                                domain=nested-f2whd-worker-0-kcflk                                                                                        
INFO Deleted domain                                domain=nested-f2whd-master-0                                                                                              
INFO Deleted network                               network=nested-f2whd                                                                                                      
INFO Deleted volume                                volume=nested-f2whd-worker-0-kcflk.ignition                                                                               
INFO Deleted volume                                volume=nested-f2whd-master.ign                                                                                            
INFO Deleted volume                                volume=nested-f2whd-master-0                                                                                              
INFO Deleted volume                                volume=nested-f2whd-base                                                                                                  
INFO Deleted volume                                volume=nested-f2whd-worker-0-kcflk                                                                                        
INFO Deleted pool                                  pool=nested-f2whd 

# ls /var/lib/libvirt/openshift-images
nested-tzl6f
```

/lgtm

**Pull request merged**
