### PR TITLE
openstack: Add OpenStack to the platform selection

### PR DESCRIPTION
**Pull request by tomassedovic**

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
Are there doc updates that would help with this change?

**Comment by tomassedovic** [comment]
@abhinavdahiya sorry, yes. We've been focusing on the service VM removal and I've mostly opened this so we don't forget to do it.

I plan to address these PRs and then bring our docs up to date:

https://github.com/openshift/installer/pull/1959
https://github.com/openshift/machine-config-operator/pull/740

**Comment by tomassedovic** [comment]
@abhinavdahiya all the pull requests we needed to merge are now in.

The docs are open but ready to go: https://github.com/openshift/installer/pull/2148.

Would you mind taking another look at this please? I'm not sure whether this is required for the FFE or can be addressed later.

**Comment by abhinavdahiya** [comment]
/lgtm

cc @crawford @cuppett

**Pull request merged**
