### PR TITLE
OCPBUGS-35426: Update cluster-api-provider-openstack to v0.10.3

### PR DESCRIPTION
**Pull request by pierreprinetti**
* Upgrade from v0.10.0 to v0.10.3
* Depend on the upstream provider, as the downstream carry-patch that reverted to Go v1.21 is no longer useful

### CODE REVIEW

**Review by r4f4 — COMMENTED** [review]
/approve

/hold
The infrastructure-components.yaml also needs to be updated.

**Comment by pierreprinetti** [comment]
> /approve
> 
> /hold The infrastructure-components.yaml also needs to be updated.

Thank you for noticing that, I had missed it. It's now in.

/cc mandre emilienm

**Pull request merged**
