### PR TITLE
upi/aws/cloudformation/01_vpc: Drop PublicNetworkAcl

### PR DESCRIPTION
**Pull request by wking**
We've had this since the templates landed in 39a926a918 (#1408).  But our Terraform modules contain no analog using [`aws_network_acl`][1] and their presence in the UPI templates is [breaking the ping-based network connectivity test][2].

[1]: https://www.terraform.io/docs/providers/aws/r/network_acl.html
[2]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/canary-openshift-ocp-installer-e2e-aws-upi-4.2/28#0:build-log.txt%3A10235

### CODE REVIEW

**Comment by wking** [comment]
CC @kalexand-rh about this CloudFormation template change.

**Comment by abhinavdahiya** [comment]
LGTM @cuppett ptal

**Comment by cuppett** [comment]
This generates the desired effect (no restrictions via the NACL on the public subnets).

**Comment by cuppett** [comment]
LGTM

**Comment by abhinavdahiya** [comment]
/lgtm


/retest


/hold

Would like to see the UPI pr go green

**Comment by wking** [comment]
Previous [UPI run][1]:

```
Flaky tests:
[Feature:Platform] Managed cluster should have no crashlooping pods in core namespaces over two minutes [Suite:openshift/conformance/parallel]
[sig-api-machinery] CustomResourcePublishOpenAPI [Feature:CustomResourcePublishOpenAPI] works for CRD with validation schema [Suite:openshift/conformance/parallel] [Suite:k8s]
[sig-cli] Kubectl client [k8s.io] Kubectl client-side validation should create/apply a valid CR with arbitrary-extra properties for CRD with partially-specified validation schema [Suite:openshift/conformance/parallel] [Suite:k8s]

Failing tests:
[Feature:Builds][webhook] TestWebhook [Suite:openshift/conformance/parallel]
```

So at least we passed `Networking should provide Internet connection for containers`.  And [`TestWebhook` seems generally flaky][2].

[1]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_installer/2296/pull-ci-openshift-installer-master-e2e-aws-upi/5
[2]: https://ci-search-ci-search-next.svc.ci.openshift.org/?search=failed%3A.*TestWebhook&maxAge=12h&context=-1&type=all

**Comment by wking** [comment]
Ah, `TestWebhook` issue is [`timed out waiting for the condition, namespace is empty but is not yet removed`][1].

[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1727090

**Comment by wking** [comment]
AWS UPI is [green][1] :).  Although I dunno what's up with the `tar` errors:

```
2019/08/30 22:26:16 Pod e2e-aws-upi succeeded after 1h30m11s
tar: can't open './installer/sedXk9NiC': Permission denied
tar: can't open './installer/sedtuNq5B': Permission denied
tar: error exit delayed from previous errors
2019/08/30 22:26:33 Copied 286.40Mi of artifacts
```

[1]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_installer/2296/pull-ci-openshift-installer-master-e2e-aws-upi/6

**Comment by wking** [comment]
[e2e-aws][1] hit a bunch of:

```
timed out waiting for the condition, namespace is empty but is not yet removed
```

/test e2e-aws

[1]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_installer/2296/pull-ci-openshift-installer-master-e2e-aws/7498

**Comment by kalexand-rh** [comment]
Thank you, @wking!

**Pull request merged**
