### PR TITLE
Azure Stack: type, validation, & infrastructure manifest

### PR DESCRIPTION
**Pull request by patrickdillon**
This PR takes the bits of #4823 and #4799 that I believe are ready to merge and can provide a foundation to build from. 

Individual commits should have explanations in the commit messages.

This will be followed up with a PR to add support for the cloud provider config and update the APIs to the hybrid profiles for ASH support.

### CODE REVIEW

**Review by staebler — COMMENTED** [review]
Looks good to me, once the formatting and the code generation issues are resolved.

**Comment by patrickdillon** [comment]
Including #5030 to test whether this solves  yamllint issue (yaml-lint is failing on symlink to files vendored in this PR)

**Pull request merged**
