### PR TITLE
METAL-871: baremetal: remove ironic tf files

### PR DESCRIPTION
**Pull request by honza**
A few were accidentally left behind during the recent refactor

### CODE REVIEW

**Comment by dtantsur** [comment]
```
level=error msg=Error: No value for required variable
level=error
level=error msg=  on variables-baremetal.tf line 11:
level=error msg=  11: variable "masters" { 
```

Still used or defined somewhere?

**Comment by honza** [comment]
> Still used or defined somewhere?

I deleted the `masters` var in the latest push.

**Comment by honza** [comment]
Weird rpm mirror errors

/retest-required

**Pull request merged**
