### PR TITLE
update ci image references

### PR DESCRIPTION
**Pull request by staebler**
* Replace uses of registry.svc.ci.openshift.org with registry.ci.openshift.org.
* Update references to golang-1.14 images to golang-1.15.
* Update references to OpenShift images to 4.8.

### CODE REVIEW

**Review by mandre — COMMENTED** [review]
/retest

LGTM for the openstack image. e2e-openstack-upi failure is likely unrelated as e2e-openstack succeeded.

**Comment by patrickdillon** [comment]
Image looks fine in CI., which should be the same for all tests.
/lgtm

**Comment by staebler** [comment]
/override ci/prow/e2e-ovirt

The e2e-ovirt job is broken and should not be required.

**Pull request merged**
