### PR TITLE
[release-4.15] OCPBUGS-35359: GCP: Prevent cluster installation with mismatched worker assets and worker replicas

### PR DESCRIPTION
**Pull request by sadasu**
Add checks around number of compute replicas requested, the number of worker manifests and whether masters are schedulable. These are useful especially for compact cluster installs.

Manual backport of https://github.com/openshift/installer/pull/8553.

### CODE REVIEW

**Review by r4f4 — COMMENTED** [review]
/approve

**Review by barbacbd — COMMENTED** [review]
/lgtm

**Pull request merged**
