### PR TITLE
OCPBUGS-36196: CAPZ USGovernmentCloud fixes

### PR DESCRIPTION
**Pull request by jhixson74**
https://issues.redhat.com/browse/OCPBUGS-36196

### CODE REVIEW

**Comment by jhixson74** [comment]
This works without https://github.com/openshift/installer/pull/8813 . With https://github.com/openshift/installer/pull/8813, the following error occurs in bootkube.sh over and over preventing anything from working:

Aug 20 03:43:34 jhcapi-4u0pt9-mc9tz-bootstrap bootkube.sh[40509]: Error: unknown flag: --feature-gate-manifest-path

**Comment by r4f4** [comment]
> This works without #8813 . With #8813, the following error occurs in bootkube.sh over and over preventing anything from working:
> 
> Aug 20 03:43:34 jhcapi-4u0pt9-mc9tz-bootstrap bootkube.sh[40509]: Error: unknown flag: --feature-gate-manifest-path

@jhixson74 if this is happening during local testing, it's because you need a nightly release image. The latest 4.17.0-ec.3 doesn't contain the CVO changes to accept that argument.

**Review by r4f4 — COMMENTED** [review]
/approve

**Pull request merged**
