### PR TITLE
WIP: Terraform providers subtree

### PR DESCRIPTION
**Pull request by r4f4**
Use terraform providers from their own repo as a subtree. Alternative to https://github.com/openshift/installer/pull/7614

### CODE REVIEW

**Comment by zaneb** [comment]
Continuing discussion from https://github.com/openshift/installer/pull/7614#issuecomment-1780578716

> > Leaving the merits of submodules aside 🙃 does this mean that there would be no way to test a change to a terraform provider in CI without first merging the change in the provider repo and then proposing a separate PR to the installer that can tell if it worked?
> 
> I can't find a way around it. To build the providers separately, they need to be in a separate repo.

You mean that all images get rebuilt every time a repo changes, so it's not possible to avoid a complete rebuild of Terraform+providers on every change to the installer as long as they're in the same repo?

I note that in https://steps.ci.openshift.org/ci-operator-reference it says you can set a flag in the `images` list:

```
      # Optional means the build step is not built, published, or
      # promoted unless explicitly targeted. Use for builds which
      # are invoked only when testing certain parts of the repo.
```

I'm not sure how the 'explicitly targeted' part works, but it seems like this _might_ be possible after all. Unfortunately the [docs](https://docs.ci.openshift.org/docs/how-tos/onboarding-a-new-component/#ci-operator-configuration) for the CI config are pretty spartan.

> And that means we need to merge changes there first. If you know of a better way, I'm all ears.

Other than the above I don't, which makes me think maybe we shouldn't do this.

**Comment by zaneb** [comment]
Marginally more informative docs: https://github.com/openshift/ci-operator/blob/master/CONFIGURATION.md#imagesnameoptional

**Comment by r4f4** [comment]
> You mean that all images get rebuilt every time a repo changes, so it's not possible to avoid a complete rebuild of Terraform+providers on every change to the installer as long as they're in the same repo?
> 
> I note that in https://steps.ci.openshift.org/ci-operator-reference it says you can set a flag in the `images` list:
> 
> ```
>       # Optional means the build step is not built, published, or
>       # promoted unless explicitly targeted. Use for builds which
>       # are invoked only when testing certain parts of the repo.
> ```
> 
> I'm not sure how the 'explicitly targeted' part works, but it seems like this _might_ be possible after all. Unfortunately the [docs](https://docs.ci.openshift.org/docs/how-tos/onboarding-a-new-component/#ci-operator-configuration) for the CI config are pretty spartan.

Please, check out our conversation with the test platform team: https://issues.redhat.com/browse/DPTP-3514
 
> > And that means we need to merge changes there first. If you know of a better way, I'm all ears.
> 
> Other than the above I don't, which makes me think maybe we shouldn't do this.

Why not? The providers change much less often than the Installer itself and it'll be even less as we move away from terraform. Just building the providers part in the `installer-artifacts` takes 1h30. We can save that time and CI resources *for every PR* by pre-building them in exchange for a 2-repo bump workflow.

**Comment by zaneb** [comment]
Is there a doc describing the proposed workflow anywhere?

Presumably a developer does `git subtree pull` to update the code in the installer... what purpose does the code in the installer have if the binaries are already built in another repo?

**Comment by r4f4** [comment]
> Is there a doc describing the proposed workflow anywhere?

Not yet but there will be one. I think @patrickdillon has already started working on it.

> Presumably a developer does `git subtree pull` to update the code in the installer... what purpose does the code in the installer have if the binaries are already built in another repo?

No changes to the development workflow. As devs, we're still going to build the providers locally. We can even bump the providers in the Installer repo, then `git subtree split && git subtree push <terraform-providers-repo>`. Also, by having the whole providers tree, we don't have to remember to do `git submodule init --update` every time we change branches as it would've been the case if we were using git submodule.

**Comment by patrickdillon** [comment]
> > I'm not sure how the 'explicitly targeted' part works, but it seems like this _might_ be possible after all. Unfortunately the [docs](https://docs.ci.openshift.org/docs/how-tos/onboarding-a-new-component/#ci-operator-configuration) for the CI config are pretty spartan.
> 
> Please, check out our conversation with the test platform team: https://issues.redhat.com/browse/DPTP-3514

I'm glad we're revisiting this idea of using ci job variants to produce these images, because I do think that is the best solution, if it works. I believe we abandoned that approach after we were told that we cannot conditionally trigger image jobs, but it does not seem like that is firmly established so we should press harder. I have updated that thread with a summary.

**Pull request closed without merging**
