### PR TITLE
[fcos] Merge fcos-devel

### PR DESCRIPTION
**Pull request by LorbusChris**
This branch contains exactly the same code as the LorbusChris:fcos-devel branch
from #3337
but keeps history of the fcos branch intact so CI tests can run.

Fixes https://github.com/openshift/okd/issues/116

### CODE REVIEW

**Comment by vrutkovs** [comment]
Generally LGTM, but it still has "source: null" in ssh config, so it would break MCO rebase

**Comment by LorbusChris** [comment]
/hold
this contains all changes from current master -- will change that to release-4.4 instead

**Comment by LorbusChris** [comment]
actually, no -- the delta with 4.4 is too big (no Go Modules etc)
let's stick to master
/hold cancel

**Comment by vrutkovs** [comment]
`kube-controller-manager` never became ready

/retest

**Comment by vrutkovs** [comment]
>Cluster operator ingress Available is False with IngressUnavailable: Not all ingress controllers are available

/retest

**Comment by LorbusChris** [comment]
ingress controller didn't come up
/retest

**Comment by vrutkovs** [comment]
Reached the test phase! \o/

openshift-machine-api alert is a bit odd

/retest

**Comment by LorbusChris** [comment]
/hold
let's switch to v3 for provided ignition config templates to avoid issues later when upgradin from here (upgrading from v3.1-exp might be troublesome)

**Comment by vrutkovs** [comment]
machine-api alerts, seems worker didn't join the cluster

/retest

**Comment by LorbusChris** [comment]
looks like another flake..
/test e2e-vsphere

**Pull request merged**
