### PR TITLE
Bug 1773909: OpenStack: Fix destroy module

### PR DESCRIPTION
**Pull request by Fedosin**
This patch contains improvements for the destroy module from PRs https://github.com/openshift/installer/pull/2408

### CODE REVIEW

**Comment by mandre** [comment]
Let's leave #2561 out of this. It's not strictly needed to fix bz#1773909 and makes the `destroy` command to never return because https://github.com/openshift/installer/pull/2390 is missing from release-4.2.

**Comment by pierreprinetti** [comment]
/lgtm

Thanks!

**Pull request merged**
