### PR TITLE
[release-4.6] Bug 1949150: add proxy params to bootstrap ignition

### PR DESCRIPTION
**Pull request by EmilienM**
This is an manual cherry-pick of #4804

### CODE REVIEW

**Review by mtnbikenc — COMMENTED** [review]
LGTM

**Review by mandre — COMMENTED** [review]
/lgtm

**Comment by sdodson** [comment]
/override ci/prow/e2e-vsphere-upi
vsphere-upi job is permanently failing in 4.6 and this code does not affect that installation path

**Pull request merged**
