### PR TITLE
Revert #8416 "OCPBUGS-33880: CORS-2840: promote capi-installers to default feature set"

### PR DESCRIPTION
**Pull request by neisw**
Reverts #8416 ; tracked by https://issues.redhat.com/browse/TRT-1674

Per [OpenShift policy](https://github.com/openshift/enhancements/blob/master/enhancements/release/improving-ci-signal.md#quick-revert), we are reverting this breaking change to get CI and/or nightly payloads flowing again.

Multiple payload failures due to bootstrap cleanup failures

To unrevert this, revert this PR, and layer an additional separate commit on top that addresses the problem. Before merging the unrevert, please run these jobs on the PR and check the result of these jobs to confirm the fix has corrected the problem:

```
/payload-aggregate periodic-ci-openshift-release-master-ci-4.17-e2e-aws-ovn 10
```

CC: @patrickdillon

<div align="right">
PR created by <a href="https://github.com/stbenjam/revertomatic">Revertomatic<sup>:tm:</sup></a>
</div>

### CODE REVIEW

**Comment by neisw** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.17-e2e-aws-ovn 10

**Comment by patrickdillon** [comment]
Including here, what @neisw pointed out on slack, this revert needs to be coupled with a revert of https://github.com/openshift/installer/pull/8254. Expecting vsphere to fail here in this revert.

**Comment by neisw** [comment]
/close

https://github.com/openshift/installer/pull/8433 contains both of the reverts we need

**Pull request closed without merging**
