### PR TITLE
OCPBUGS-27482,OCPBUGS-27483: [release-4.14] Fix Agent-based Installer on OKD/FCOS

### PR DESCRIPTION
**Pull request by JM1**

### CODE REVIEW

**Comment by JM1** [comment]
/test okd-e2e-agent-sno-ipv6
/test okd-e2e-aws-ovn
/test images

(ci issues...)

**Comment by titou10titou10** [comment]
Any chance to have this PR merged soon? thx

**Comment by JM1** [comment]
/jira cherrypick OCPBUGS-19303,OCPBUGS-22453,OCPBUGS-19552,AGENT-710

**Comment by JM1** [comment]
@andfasano Could you please approve? 🥺

**Comment by JM1** [comment]
With release of OKD/FCOS [4.15.0-0.okd-2024-01-27-070424](https://github.com/okd-project/okd/releases/tag/4.15.0-0.okd-2024-01-27-070424), no new 4.14 releases will be released. So this PR is obsolete 😕

**Pull request closed without merging**
