### PR TITLE
no-jira: bump cluster-api version to 1.8.2

### PR DESCRIPTION
**Pull request by r4f4**
This is a fallout from https://github.com/openshift/installer/pull/9010.

The cluster-api binary version used should be no lower than the greatest version required by the providers which in this case is 1.8.2 by ibmcloud. Otherwise, we will be running an older binary while linking the provider against a newer version, possibly requiring new function args and/or functions.

### CODE REVIEW

**Comment by r4f4** [comment]
nutanix and vsphere: e2e failures, so no issues with capi 1.8.2
powervs: seems it timed out waiting for the master-1 reconciliation. Probably not related to capi 1.8.2:
```
time="2024-09-26T23:30:52Z" level=debug msg="I0926 23:30:52.878000     912 ibmpowervsmachine_controller.go:202] \"Reconciling IBMPowerVSMachine\" controller=\"ibmpowervsmachine\" controllerGroup=\"infrastructure.cluster.x-k8s.io\" controllerKind=\"IBMPowerVSMachine\" IBMPowerVSMachine=\"openshift-cluster-api-guests/p-mad02-2-capi-master-k8j8p-master-1\" namespace=\"openshift-cluster-api-guests\" name=\"p-mad02-2-capi-master-k8j8p-master-1\" reconcileID=\"52d60055-78e5-4b1a-bc44-a849f9c01e48\" ibmPowerVSMachine=\"p-mad02-2-capi-master-k8j8p-master-1\" cluster=\"p-mad02-2-capi-master-k8j8p\""
```

**Comment by r4f4** [comment]
```
INFO[2024-09-27T09:59:09Z] Step e2e-powervs-capi-ovn-ipi-install-powervs-install succeeded after 1h11m1s. 
```
So the powervs install finished. It seems we are good with capi 1.8.2

**Review by barbacbd — COMMENTED** [review]
/lgtm

**Comment by patrickdillon** [comment]
> This is a fallout from https://github.com/openshift/installer/pull/9010.

Ah, my bad. 

/approve

Thanks for cleaning this up!

**Comment by r4f4** [comment]
> > This is a fallout from #9010.
> 
> Ah, my bad.
> 
> /approve
> 
> Thanks for cleaning this up!

It's easy to miss. I've added a card in our tech debt epic to add a check for that in our presubmit tests.

**Comment by r4f4** [comment]
/override ci/prow/e2e-gcp-ovn
Just some e2e failures that are not related to the capi bump. Overriding since other PRs are blocked on this one.

**Pull request merged**
