### PR TITLE
OCPBUGS-7966: Do not remove host default configuration unless network configuration is provided for it

### PR DESCRIPTION
**Pull request by paul-maidment**
Presently, in the PreNetworkConfig script, we are removing the default network manager configuration for a host in every case. This should be altered so that the default configuration is deleted only if custom nmstate configuration has been provided for the host.

### CODE REVIEW

**Comment by bfournie** [comment]
@paul-maidment Thanks for making this change in the installer. I had created a bug for this https://issues.redhat.com/browse/OCPBUGS-7966. Could you change the title to preface it with "OCPBUGS-7966" so it gets tracked properly?

/lgtm

**Comment by patrickdillon** [comment]
/retitle OCPBUGS-7966: Do not remove host default configuration unless network configuration is provided for it

**Comment by bfournie** [comment]
Thanks @patrickdillon 

/jira refresh
/cherry-pick release-4.13

**Pull request merged**
