### PR TITLE
Fixes tested_instance_types_aarch64.md

### PR DESCRIPTION
**Pull request by aleskandro**
The correct arm64 instance types for arm64 are `m6g`, not `m6i`. The content in the changed file is printed at https://docs.openshift.com/container-platform/4.11/installing/installing_aws/installing-aws-customizations.html#installation-aws-arm-tested-machine-types_installing-aws-customizations as per https://github.com/openshift/openshift-docs/pull/49799/files#diff-07cf011d0e9ab4d28bdf09424f0a6036be3a791d5fe6f243867fb2454092eec1R18-R21

Refers openshift/openshift-docs#49799 and https://issues.redhat.com/browse/OCPBUGS-752

/cc @jeffdyoung  

cc @lwan-wanglin  @yunjiang29 @kelbrown20

### CODE REVIEW

**Comment by aleskandro** [comment]
cc @lwan-wanglin @yunjiang29 @kelbrown20

**Review by jeffdyoung — APPROVED** [review]

**Review by kelbrown20 — COMMENTED** [review]
/label docs-approved

**Pull request merged**
