### PR TITLE
pkg/types/aws/validation/platform: Include eu-north-1

### LINKED ISSUE #1814: please support region eu-north
Summary:

We want to install a openshift 4.1 cluster in region eu-north (stockholm). This region is currently not supported. We were able to install a test cluster in AWS region eu-central-1, Frankfurt, just fine.

We would like our production cluster to be in eu-north-1.

# Version

4.1

```console
$ openshift-install version
<your output here>
```

# Platform (aws|libvirt|openstack):

AWS, region eu-north

# What happened?

region is not supported

Enter text here.
See [the troubleshooting documentation](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md) for ideas about what information to collect.
For example, if the installer [fails to create resources](https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md#installer-fails-to-create-resources), attach the relevant portions of your `.openshift_install.log`.

# What you expected to happen?

we expected it to be possible to install an openshift cluster on aws in region eu-north (stockholm)

# How to reproduce it (as minimally and precisely as possible)?

```console
$ your-commands-here
```

# Anything else we need to know?

Enter text here.

# References

- enter text here.

### PR DESCRIPTION
**Pull request by wking**
RHCOS grew support for this in 905db73fdf (#1941), and until something like #1528 lands we need to bump this list to keep up.

Fixes #1814.

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
what's the result of the `platformtests` ??

**Comment by wking** [comment]
> what's the result of the `platformtests` ??

Passes once I add bf0369dfe to account for the new-but-not-yet-getting-RHCOS-AMIs [Bahrain][1] ([me-south-1][2]).

[1]: https://aws.amazon.com/about-aws/whats-new/2019/07/announcing-the-new-aws-middle-east--bahrain--region-/
[2]: https://github.com/aws/aws-sdk-go/commit/384f4536edd1f4b59cf0c03ab3b346aba4c1c9cc#diff-fe3b36d57dc4378fa7b13c85492f4119R49

**Comment by wking** [comment]
Pushed bf0369dfe -> 612143d5a to fix [the unit failure][1].

[1]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_installer/2308/pull-ci-openshift-installer-master-unit/5639

**Comment by abhinavdahiya** [comment]
/hold

candidate for 4.3 when master opens.

**Comment by wking** [comment]
/hold cancel

Master is open for 4.3 fixes :).  Still needs a `/lgtm` to merge.

**Comment by wking** [comment]
/assign @abhinavdahiya 

Green enough to merge, and we want to land this before the 4.3 window closes ;)

**Pull request merged**
