### PR TITLE
Updating vpc and infra aws upi templates to be able to do blackhole

### PR DESCRIPTION
**Pull request by ewolinetz**
... config, add proxy template

This PR moves the extra templates from the following into installer templates:
* https://github.com/openshift/release/pull/4719
* https://github.com/openshift/release/pull/5308

cc @wking

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
/hold

the installer repo is not the correct place to hold these modifications.

**Comment by ewolinetz** [comment]
@abhinavdahiya why is this not the appropriate place for these modifications? Where would you suggest these changes live instead?

**Comment by ewolinetz** [comment]
cc @danehans

**Comment by ewolinetz** [comment]
closing per discussion on slack -- this isn't something we expect to deliver to customers so it doesn't make sense to keep this here.

**Pull request closed without merging**
