### PR TITLE
BUG 1782516: Disable client side rate limiting in Azure.

### PR DESCRIPTION
**Pull request by enxebre**
Client side rate limiting is being problematic for fresh installs and scaling operations [1]

Azure ARM throttling is applied at subscription level, so client side rate limiting helps to prevent cluster sharing the same subscription from disrupting each other.
However there's lower limits which apply at the SP/tenant and resource level e.g ARM limits the number of write calls per service principal to 1200/hour [2]. Since we ensure particular SPs per cluster via Cloud Credential Operator it should be relatively safe to disable the client rate limiting 

Orthogonally to this some improvements on the rate limiting and back off mechanisms are being added to the cloud provider.

[1] https://bugzilla.redhat.com/show_bug.cgi?id=1782516.
[2] https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/request-limits-and-throttling
[3] https://github.com/kubernetes-sigs/cloud-provider-azure/issues/247

### CODE REVIEW

**Comment by enxebre** [comment]
cc @abhinavdahiya @jim-minter @joelddiaz @mrunalp

**Comment by abhinavdahiya** [comment]
> Since we ensure particular SPs per cluster via Cloud Credential Operator it should be relatively safe to disable the client rate limiting

can you expand a little?
we have managed identity attached for the control-plane VMs so that k8s-cloud-provider can communicate with API

also today we have a SP per operator created by the cred-minter, where cred-minter itself uses the SP used to install. _ we can leave overlook this here as the configuration only controls the k8s-cloud-provider_

So since we are using managed identity for control plane VMs we are okay to remove the limits? The original limits were from AKS, was AKS using shared SP that they use the client side limits?

**Comment by abhinavdahiya** [comment]
Secondly, how do we get our already existing clusters to follow this new limits?

**Comment by abhinavdahiya** [comment]
also @enxebre it would be very helpful to move the PR desc into the commit message too.

**Comment by enxebre** [comment]
>Since we ensure particular SPs per cluster via Cloud Credential Operator it should be relatively safe to disable the client rate limiting
can you expand a little?
we have managed identity attached for the control-plane VMs so that k8s-cloud-provider can communicate with API
also today we have a SP per operator created by the cred-minter, where cred-minter itself uses the SP used to install. _ we can leave overlook this here as the configuration only controls the k8s-cloud-provider_
So since we are using managed identity for control plane VMs we are okay to remove the limits

My understanding is that we mostly do tenant-level operations and limits are scoped to SP. Since we have granular SP as you described above we wouldn't likely throttle the subscription. https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/request-limits-and-throttling#subscription-and-tenant-limits

>The original limits were from AKS, was AKS using shared SP that they use the client side limits?

I know they set it to prevent subscription level throttling but I'm not 100% sure they share a SP. FWIW ARO has rate limiting turned off.

 >Secondly, how do we get our already existing clusters to follow this new limits?

Good point. There's afaik nothing owns `openshift-config/cloud-provider-config` so this is an open question. Currently users are needing to change this manually to overcome this issue.

**Comment by jim-minter** [comment]
@enxebre I can lgtm this if it helps?
Can we get this in 4.4?

**Comment by danehans** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1826069 created for 4.4, please backport.

https://bugzilla.redhat.com/show_bug.cgi?id=1826073 created for 4.3, please backport.

**Comment by danehans** [comment]
@abhinavdahiya do the `e2e-libvirt` and `e2e-aws-scaleup-rhel7` jobs need to succeed for a /lgtm?

**Comment by danehans** [comment]
Note that this fix needs to be backported to 4.4 and 4.3. See https://bugzilla.redhat.com/show_bug.cgi?id=1782516#c24 for details.

**Comment by danehans** [comment]
@enxebre can you sync with @abhinavdahiya to get this PR in a state to get merged?

**Pull request merged**
