### PR TITLE
Bump golang version to 1.12

### PR DESCRIPTION
**Pull request by Fedosin**
This PR updated the current building system and ci images from golang 1.10 to 1.12.

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
FYI, the from is replaced by CI to match 1.10 https://github.com/openshift/release/blob/f31fae4ccbc6331273fdcf41875a4a33588ecaa4/ci-operator/config/openshift/installer/openshift-installer-master.yaml#L10

So the CI is still building this with 1.10

**Comment by Fedosin** [comment]
@abhinavdahiya thanks! done: https://github.com/openshift/release/pull/5509

**Comment by Fedosin** [comment]
not sure about libvirt but openstack ci doesn't work for another reason, seems like a DNS issue

**Pull request merged**
