### PR TITLE
CORS-3569: UDR for Capz

### PR DESCRIPTION
**Pull request by jhixson74**
When user defined routing is configured, don't create an outbound load
balancer with outbound rules. Since a public load balancer isn't being
created, we create one for public API access.

https://issues.redhat.com/browse/CORS-3569

### CODE REVIEW

**Comment by patrickdillon** [comment]
I'm concerned that if we edit a CAPZ-provisioned LB with the SDK, that CAPZ may reconcile the LB and overwrite our changes. If we remove the outbound rule, capz might put them back. I haven't tested this, but looking at the capz code, it seems like that is what is supposed to happen:

https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/90797931a191d5baf48bd6fa70c78f2207ad117f/azure/services/loadbalancers/spec.go#L114-L120

Prior to the changes in #8652, we were using the SDK to create a LB without an outbound rule. Perhaps an alternative approach to this one could be to use that pre-#8652 logic in the case when User-defined routing is set?

**Comment by jhixson74** [comment]
> I'm concerned that if we edit a CAPZ-provisioned LB with the SDK, that CAPZ may reconcile the LB and overwrite our changes. If we remove the outbound rule, capz might put them back. I haven't tested this, but looking at the capz code, it seems like that is what is supposed to happen:
> 
> https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/90797931a191d5baf48bd6fa70c78f2207ad117f/azure/services/loadbalancers/spec.go#L114-L120
> 
> Prior to the changes in #8652, we were using the SDK to create a LB without an outbound rule. Perhaps an alternative approach to this one could be to use that pre-#8652 logic in the case when User-defined routing is set?

In testing this, I have not seen this behavior. It works as advertised.

**Comment by patrickdillon** [comment]
> In testing this, I have not seen this behavior. It works as advertised.

That's good to know. It would depend on whether CAPZ reconciles the LB after we modify it. For example, in AWS, we update the awscluster to remove the SSH rules during bootstrap destroy. If we did something similar in Azure, the outboundrule would get added back in. But AFAIK, we have no need for that in Azure, so we might get away with it.

> If we were to go back to the previous behavior, we have 3 load balancers again, in addition to whatever is setup on the BYO vnet.

In the alternative I was suggesting, we would drop the CAPZ-created Control plane outbound load balancer (egress would be provided by UDR), and use the SDK to create the ext LB. So only 2 LBs. 

> My interpretation of the code referenced is that if there is an update to the outbound rules, then the outbound rules get updated, which is what we do here ;-)

When reconciling, if CAPZ finds an existing LB, it checks to see whether the existing LB has the expected outbound rules. If the rules are missing, it adds them back in.

**Comment by jhixson74** [comment]
> > In testing this, I have not seen this behavior. It works as advertised.
> 
> That's good to know. It would depend on whether CAPZ reconciles the LB after we modify it. For example, in AWS, we update the awscluster to remove the SSH rules during bootstrap destroy. If we did something similar in Azure, the outboundrule would get added back in. But AFAIK, we have no need for that in Azure, so we might get away with it.
> 
> > If we were to go back to the previous behavior, we have 3 load balancers again, in addition to whatever is setup on the BYO vnet.
> 
> In the alternative I was suggesting, we would drop the CAPZ-created Control plane outbound load balancer (egress would be provided by UDR), and use the SDK to create the ext LB. So only 2 LBs.
> 
> > My interpretation of the code referenced is that if there is an update to the outbound rules, then the outbound rules get updated, which is what we do here ;-)
> 
> When reconciling, if CAPZ finds an existing LB, it checks to see whether the existing LB has the expected outbound rules. If the rules are missing, it adds them back in.

Testing this out right now, will update PR if okay ;-)

**Review by sadasu — COMMENTED** [review]
/lgtm

**Review by patrickdillon — COMMENTED** [review]
/approve

**Pull request merged**
