### PR TITLE
gather: always prefer explicit arguments and other clean-ups

### PR DESCRIPTION
**Pull request by stbenjam**
If a user supplies host addresses as arguments these should always be
preferred over the terraform state file. This also cleans up the gather
code to be a little more understandable. Users will now get distinct
errors in these cases:

  - gather is used on an unsupported platform
  - gather could not get the information from the tfstate file
  - no tfstate file is found

Currently users receive identical or very similar error messages without
being able to know exactly why gather failed.

### CODE REVIEW

**Comment by stbenjam** [comment]
Any chance someone could PTAL? Thanks

/cc @smarterclayton @crawford @wking

**Comment by wking** [comment]
Huh, I guess #2563 never landed.  I'll go through and compare...

**Comment by stbenjam** [comment]
https://github.com/openshift/installer/pull/2563 is now closed, is there any interest in this?

Otherwise I can close this one, too.

**Comment by wking** [comment]
I still think having the options take precedent over Terraform makes sense.  I haven't had time to look through your implementation yet.

**Comment by stbenjam** [comment]
Doesn't look like it'll get any one to review, and it's stale now anyway with merge conflicts.

**Pull request closed without merging**
