### PR TITLE
terraform: only use embedded plugins when `release` tag is set

### PR DESCRIPTION
**Pull request by abhinavdahiya**
/cc @wking

### CODE REVIEW

**Comment by wking** [comment]
ff3c4307c0 looks good to me, but we'll need to work harder to train users who want this isolation to use released installers.  CC @sallyom, @ironcladlou, @RobertKrawitz, in case they want to chime in before we land this.

**Comment by abhinavdahiya** [comment]
> but we'll need to work harder to train users who want this isolation to use released installers

developers (trackingmaster) can be expected to be more informed compared to users using released versions.

**Comment by ironcladlou** [comment]
What's the use case for using non-vendored plugins?

**Comment by abhinavdahiya** [comment]
> What's the use case for using non-vendored plugins?

so that we can test newer versions of plugins by putting them in `~/.terraform.d/plugins` without changing the vendored ones for developer testing

**Comment by ironcladlou** [comment]
>>What's the use case for using non-vendored plugins?

>so that we can test newer versions of plugins by putting them in ~/.terraform.d/plugins without changing the vendored ones for developer testing

Is it fair to say this comes at the expense of re-introducing external dependencies and steps for development builds?

I don't know what's more common, using the vendored plugins for development or using custom plugins, so I can't say who it makes more sense to optimize for. Speaking only for myself, I never use custom plugins, and if I did I would be willing to jump through hoops to do so.

**Comment by ironcladlou** [comment]
Thanks for the clarification — it wasn't obvious to me that this just adds another entry to a precedence list!

**Pull request merged**
