### PR TITLE
BUG 1685704: upi/metal: add the api-int dns

### PR DESCRIPTION
**Pull request by abhinavdahiya**
Add DNS record for api-int that points to the control plane hosts.

infrastructure architecture change happening for https://bugzilla.redhat.com/show_bug.cgi?id=1685704

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
similar PRs https://github.com/openshift/installer/pull/1604 https://github.com/openshift/installer/pull/1601

**Comment by wking** [comment]
[e2e-aws][1]:

```
Failing tests:

[Feature:Platform] Managed cluster should have no crashlooping pods in core namespaces over two minutes [Suite:openshift/conformance/parallel]
```

openshift-kube-scheduler crash looping is [rhbz#1698251][2].

/retest

[1]: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_installer/1605/pull-ci-openshift-installer-master-e2e-aws/5200
[2]: https://bugzilla.redhat.com/show_bug.cgi?id=1698251

**Comment by wking** [comment]
[e2e-aws][1]:

```
level=fatal msg="failed to initialize the cluster: Some cluster operators are still updating: console, monitoring: timed out waiting for the condition"
```

/retest

[1]: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_installer/1605/pull-ci-openshift-installer-master-e2e-aws/5239

**Comment by wking** [comment]
[e2e-aws][1]:

```
Failing tests:

[Feature:Platform] Managed cluster should have no crashlooping pods in core namespaces over two minutes [Suite:openshift/conformance/parallel]
```

/retest

[1]: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_installer/1605/pull-ci-openshift-installer-master-e2e-aws/5272

**Pull request merged**
