### PR TITLE
Bug 1767066: Vendor terraform update to fix symlink bug

### PR DESCRIPTION
**Pull request by patrickdillon**
Steps to create this commit:
1. update go.mod with new version of openshift/hashicorp-terraform
2. go mod tidy
3. go mod vendor

Fixes: #1839

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
@patrickdillon it would be very helpful if you can paste an example that shows how it now solves the #1839 ??

**Comment by patrickdillon** [comment]
Reproducer is similar to https://github.com/hashicorp/terraform/issues/24196

To reproduce:
Run `openshift-install` from a symlink directory where the symlink target is at a different level in the hierarchy than the link:
```
$ ls -al
drwxrwxr-x. 4 padillon padillon     4096 Feb 21 16:37 a
lrwxrwxrwx. 1 padillon padillon        6 Feb 21 16:25 symlink-dir -> a/b/c/

[symlink-dir]$ openshift-install create cluster
```

Without the patch, this command will fail when initializing plugins.

**Comment by patrickdillon** [comment]
@abhinavdahiya I posted reproducer above. I don't think I need to add it to commit message but let me know if you think I should or anything else is needed

**Comment by abhinavdahiya** [comment]
Thank you!

/approve
/lgtm

**Pull request merged**
