### PR TITLE
Add the terraform plugin for Nutanix

### PR DESCRIPTION
**Pull request by thunderboltsid**
Add Nutanix terraform plugin in pkg/terraform/exec/plugins.

### CODE REVIEW

**Comment by rvanderp3** [comment]
Can you separate vendor changes into their own commits, to make reviewing and perusing history easier.

**Comment by rvanderp3** [comment]
@thunderboltsid there have been some updates regarding how additional terraform providers are added to the installer.  Please see this document for details.

**Comment by rvanderp3** [comment]
/lgtm 

My only comment here is that it would have been helpful to have tools.go in its own commit.

**Comment by thunderboltsid** [comment]
> /lgtm
> 
> My only comment here is that it would have been helpful to have tools.go in its own commit.

Given the entire file is a single import statement, does that really help?

**Review by staebler — COMMENTED** [review]
1. Please separate the terraform/providers/nutanix/vendor files into their own commit.
2. Fix the commit message, as it still refers to an old directory.
3. Add the provider in pkg/terraform/providers/providers.go.

**Comment by staebler** [comment]
> > /lgtm
> > My only comment here is that it would have been helpful to have tools.go in its own commit.
> 
> Given the entire file is a single import statement, does that really help?

Yes, it is helpful to have the tools.go, go.mod, and go.sum in their own commit. With it all in one commit, it is difficult to review the commit in github. I am not looking over each file in the vendor directory, so it is convenient to have them separated from the files that I do want to look at.

**Comment by staebler** [comment]
See https://github.com/openshift/installer/commit/7c216a7c1104a610004bd0a23cecbc38bf6e688d and https://github.com/openshift/installer/commit/d7fe250d6c51c6a770f880166a184b9b7abe36a5 for precedent.

**Comment by thunderboltsid** [comment]
> * Please separate the terraform/providers/nutanix/vendor files into their own commit.
> * Fix the commit message, as it still refers to an old directory.
> * Add the provider in pkg/terraform/providers/providers.go.

Reg. 3: No such file exists https://github.com/openshift/installer/tree/master/terraform/providers

**Comment by thunderboltsid** [comment]
> * Please separate the terraform/providers/nutanix/vendor files into their own commit.
> * Fix the commit message, as it still refers to an old directory.
> * Add the provider in pkg/terraform/providers/providers.go.

Done.

**Review by staebler — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
