### PR TITLE
openstack UPI: Remove unneeded allowed IP

### PR DESCRIPTION
**Pull request by pierreprinetti**
ref: https://github.com/openshift/installer/pull/2681

Extracted from https://github.com/openshift/installer/pull/2823

### CODE REVIEW

**Comment by mandre** [comment]
/lgtm
Did a full end to end deployment using this patch.

**Comment by pierreprinetti** [comment]
@mandre When you are ready, please remember you have to approve explicitly, as the author no loger auto-approves, and /lgtm does not mean /approve anymore

**Pull request merged**
