### PR TITLE
Bug 1958884: openstack: Fix error message typo when getting volume availability zones

### PR DESCRIPTION
**Pull request by gyohuangxin**

### CODE REVIEW

**Comment by gyohuangxin** [comment]
@Fedosin @iamemilio Hi, when failed to get **volume** AZ, the error message is "could not find an available **compute** availability zone". I updated it in this PR, could you review it? Thanks.

**Review by mandre — COMMENTED** [review]
Good catch! However because we're in feature freeze we won't be able to merge anything without an associated BZ. Would you mind creating one?

**Comment by jichenjc** [comment]
https://github.com/openshift/installer/issues/4920 created for this 

@gyohuangxin you can update in the commit msg :)

**Comment by gyohuangxin** [comment]
@jichenjc @mandre Thank you! And I've updated the commit msg, pls review again :)

**Comment by mandre** [comment]
/retitle Bug 1958884: openstack: Fix error message typo when getting volume availability zones

Thanks @jichenjc, I've moved the bug over to bugzilla as this is what we'll need to make prow happy.

**Review by mandre — COMMENTED** [review]
/lgtm

**Pull request merged**
