### PR TITLE
assets/installconfig: apply defaults to install config

### PR DESCRIPTION
**Pull request by wking**
The Install Config asset will apply defaults to fields for which there are reasonable defaults. This applies to a generated Install Config asset and to an Install Config asset loaded from disk.

Carrying #902 onto #1057.  CC @staebler, @abhinavdahiya, @crawford.  Hold until #1057 lands:

/hold

### CODE REVIEW

**Comment by wking** [comment]
The commit carried from #902 actually conflicted with changes that landed in master since #1057 branched off.  So I've pushed 2444a35 -> f3ffb86 to rebase the two commits onto master.  If #1057 lands before midnight, I'll rebase this again.  If someone drops a `/lgtm` on *this* PR before #1057 lands, I'll `/hold` #1057 and try and get this one landed (with both changes) instead.

**Comment by wking** [comment]
[e2e-aws][1]:

```
failed: (2m2s) 2019-01-12T07:58:33 "[Feature:Platform] Managed cluster should have no crashlooping pods in core namespaces over two minutes [Suite:openshift/conformance/parallel]"
```

and many more.  Maybe my rebase broke something?

/retest

[1]: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_installer/1058/pull-ci-openshift-installer-master-e2e-aws/2845/build-log.txt

**Comment by wking** [comment]
Logs from that busted osin pod:

```console
$ curl -s https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_installer/1058/pull-ci-openshift-installer-master-e2e-aws/2845/artifacts/e2e-aws/pods/openshift-core-operators_origin-cluster-osin-operator2-7c95d6b586-f55tl_operator_previous.log.gz | gunzip  | tail -n 13
ERROR: logging before flag.Parse: I0112 07:33:52.629752       1 leaderelection.go:209] successfully renewed lease openshift-core-operators/cluster-osin-operator2-lock
ERROR: logging before flag.Parse: I0112 07:33:54.651256       1 leaderelection.go:209] successfully renewed lease openshift-core-operators/cluster-osin-operator2-lock
panic: osins.osin.openshift.io "openshift-osin" is forbidden: caches not synchronized

goroutine 85 [running]:
github.com/openshift/cluster-osin-operator/vendor/github.com/openshift/library-go/pkg/operator/v1helpers.EnsureOperatorConfigExists(0x1c2bf60, 0xc4200e6430, 0xc4208e2000, 0x91, 0xa0, 0x1a5e164, 0x11, 0x1a529f5, 0x8, 0x1a4e7be, ...)
	/go/src/github.com/openshift/cluster-osin-operator/vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go:99 +0x34e
github.com/openshift/cluster-osin-operator/pkg/operator2.RunOperator(0xc420470f90, 0x0, 0x0)
	/go/src/github.com/openshift/cluster-osin-operator/pkg/operator2/starter.go:83 +0x5a6
github.com/openshift/cluster-osin-operator/vendor/github.com/openshift/library-go/pkg/controller/controllercmd.(*ControllerBuilder).Run.func2(0xc42051fb00)
	/go/src/github.com/openshift/cluster-osin-operator/vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go:213 +0x4f
created by github.com/openshift/cluster-osin-operator/vendor/k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run
	/go/src/github.com/openshift/cluster-osin-operator/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:155 +0x92
```

Dunno what was going on there, but once I find out, I'll file an upstream issue or PR.

**Comment by wking** [comment]
> ```
> panic: osins.osin.openshift.io "openshift-osin" is forbidden: caches not synchronized
>
> goroutine 85 [running]:
> github.com/openshift/cluster-osin-operator/vendor/github.com/openshift/library-go/pkg/operator/v1helpers.EnsureOperatorConfigExists(0x1c2bf60, 0xc4200e6430, 0xc4208e2000, 0x91, 0xa0, 0x1a5e164, 0x11, 0x1a529f5, 0x8, 0x1a4e7be, ...)
> 	/go/src/github.com/openshift/cluster-osin-operator/vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go:99 +0x34e
> ```

The panic is from [this line][1], and openshift/library-go#168 may fix it (I'm not sure, but it mentions "fix panic" and syncing ;).

[1]: https://github.com/openshift/cluster-osin-operator/blob/7cd867feddc7729daaeb3c322ac159ff2959fa3d/vendor/github.com/openshift/library-go/pkg/operator/v1helpers/helpers.go#L99

**Comment by crawford** [comment]
Rebased onto master. No content changes. Still looks good to me.

/lgtm

**Comment by wking** [comment]
[e2e-aws][1]:

```
Jan 12 16:11:13.964 E kube-apiserver Kube API started failing: Get https://ci-op-f1bz6hw3-1d3f3-api.origin-ci-int-aws.dev.rhcloud.com:6443/api/v1/namespaces/kube-system?timeout=3s: context deadline exceeded (Client.Timeout exceeded while awaiting headers) Jan 12 16:11:42.964 E kube-apiserver Kube API started failing: Get https://ci-op-f1bz6hw3-1d3f3-api.origin-ci-int-aws.dev.rhcloud.com:6443/api/v1/namespaces/kube-system?timeout=3s: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

and more.

/retest

[1]: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_installer/1058/pull-ci-openshift-installer-master-e2e-aws/2860

**Pull request merged**
