### PR TITLE
Remove unused tests/ directory

### PR DESCRIPTION
**Pull request by LorbusChris**
also removes hack/run_bdd_suite.sh

Prep for #2745

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
So we don't use these tests at all today, I'm totally fine removing them. 

/cc @crawford 

But these don't cause any trouble today, and would like if you included why removing these un-used is important now?

**Comment by LorbusChris** [comment]
I added an explanation of the reasoning to the commit message

**Pull request merged**
