### PR TITLE
OCPBUGS-41257: pass k8s version to kube-apiserver render during bootstrap

### PR DESCRIPTION
**Pull request by atiratree**
to allow enabling different API groups versions according to the k8s version

### CODE REVIEW

**Comment by atiratree** [comment]
/hold 
this will fail until https://github.com/openshift/cluster-kube-apiserver-operator/pull/1731 merges

**Comment by patrickdillon** [comment]
/approve

we can run a techpreview job  once https://github.com/openshift/cluster-kube-apiserver-operator/pull/1731 merges

**Comment by bertinatto** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.18-e2e-aws-ovn-techpreview

**Comment by bertinatto** [comment]
> /hold this will fail until [openshift/cluster-kube-apiserver-operator#1731](https://github.com/openshift/cluster-kube-apiserver-operator/pull/1731) merges

KASO PR merged and TechPreview job is green: https://pr-payload-tests.ci.openshift.org/runs/ci/8b738540-6c97-11ef-977f-c5e47c575d65-0

/lgtm

**Pull request merged**
