### PR TITLE
hack/get-terraform: Remove obsolete script

### PR DESCRIPTION
**Pull request by wking**
Now that we're vendoring Terraform, we no longer need a script to pull down pre-compiled binaries.

I've also reworded the `create cluster` description in `overview.md` to be more generic.  See 0c3d8658 (#840) for similar changes to another location.

Builds on #822.  I dunno how well Prow handles this sort of thing with both PRs actively in the merge queue, so:

/hold

CC @crawford

### CODE REVIEW

**Comment by wking** [comment]
Rebased onto master with f9666a3 -> aff2e98 now that #822 has landed.

/hold cancel

**Comment by dgoodwin** [comment]
Hive was pulling the installer image, copying out openshift-install, and terraform, should we adjust hive now to just copy out openshift-install and terraform is no longer needed?

**Comment by dgoodwin** [comment]
Disregard, in testing I can see this is the case.

**Pull request merged**
