### PR TITLE
Add VPCRegionForPowerVSRegion function

### PR DESCRIPTION
**Pull request by hamzy**
This function will be used to create a CloudProvider config for
Power VS among other potential uses.

### CODE REVIEW

**Comment by clnperez** [comment]
@patrickdillon another Power VS PR. Can we get this one merged before the manifest assets one (https://github.com/openshift/installer/pull/5610)? I'm going to make a small change to that one but need this first. Trying to cut down on the number of PRs since CI is such a time-consuming gate for these.

**Comment by patrickdillon** [comment]
> since CI is such a time-consuming gate for these.

Agree. I'm really hoping we can devote some time to improving this experience ASAP.

**Pull request merged**
