### PR TITLE
Remove clusterID from installconfig and move it to cluster

### PR DESCRIPTION
**Pull request by staebler**
#783 rebased on top of #1052

### CODE REVIEW

**Comment by wking** [comment]
/lgtm
/hold

I'll pull the /hold once #1052 lands.

**Comment by wking** [comment]
#1052 landed.

/hold cancel
/retest

**Comment by wking** [comment]
[e2e-aws][1]:

```
error: unable to connect to image repository registry.svc.ci.openshift.org/ci-op-n9v1pkj1/stable@sha256:6cd9842c7897cff8eb05d6e3a9b9dd05de21ae484a68d2b7dba8d71e58b7c22d: Get https://registry.svc.ci.openshift.org/v2/: net/http: TLS handshake timeout
```

/retest

[1]: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_installer/1057/pull-ci-openshift-installer-master-e2e-aws/2840/build-log.txt

**Comment by abhinavdahiya** [comment]
```
Failing tests:

[Conformance][Area:Networking][Feature:Router] The HAProxy router converges when multiple routers are writing conflicting status [Suite:openshift/conformance/parallel/minimal]
[Feature:Builds][pullsecret][Conformance] docker build using a pull secret  Building from a template should create a docker build that pulls using a secret run it [Suite:openshift/conformance/parallel/minimal]
[k8s.io] [sig-node] Security Context [Feature:SecurityContext] should support seccomp default which is unconfined [Feature:Seccomp] [Suite:openshift/conformance/parallel] [Suite:k8s]
[sig-api-machinery] Servers with support for API chunking should return chunks of results for list calls [Suite:openshift/conformance/parallel] [Suite:k8s]
[sig-apps] StatefulSet [k8s.io] Basic StatefulSet functionality [StatefulSetBasic] Burst scaling should run to completion even with unhealthy pods [Conformance] [Suite:openshift/conformance/parallel/minimal] [Suite:k8s]
[sig-storage] Projected should set mode on item file [NodeConformance] [Conformance] [Suite:openshift/conformance/parallel/minimal] [Suite:k8s]

Writing JUnit report to /tmp/artifacts/junit/junit_e2e_20190112-072844.xml

Error: 6 fail, 519 pass, 97 skip (28m54s)
```
/retest

**Comment by dgoodwin** [comment]
Per last arch call Hive and service delivery both have a need to know the cluster ID, before we start provisioning resources. With this change it looks like we can no longer specify our own, but I'm not seeing the cluster metadata on disk when I generate manifests. Did this change make it in before this? Any advice on what our best path here is to know that UUID before we provision? I do see a few mentions of it in state file and cvo-overrides.yml after generating manifests.

CC @crawford @wking

**Comment by crawford** [comment]
@dgoodwin oops, I think this was merged a little prematurely. We'll need to follow up with an easy way to capture that UUID before the provisioning is started.

CC @abhinavdahiya

**Comment by wking** [comment]
> We'll need to follow up with an easy way to capture that UUID before the provisioning is started.

Instead of just the UUID, can we make a `metadata.json` asset that is part of the `ignition-configs` target?

**Comment by wking** [comment]
You need `metadata.json` before `create cluster` because bring-your-own-infrastructure will never actually call `create cluster`, and they'll still want the metadata to be able to destroy clusters later.

**Comment by wking** [comment]
> You need `metadata.json` before create cluster because bring-your-own-infrastructure...

Never mind, I was confused.  Bring-your-own-infrastructure must also be destroy-your-own-infrastructure.  For Hive or anything that *is* actually calling `create cluster`, I agree that "`metadata.json` will be there when we exit" seems to cover things.  @dgoodwin, can you remind us why you wanted it before calling `create cluster`?  I've pushed up an implementation [here][1] if it turns out we do need this, but realized I had misunderstood the motivation when writing up the commit message.

[1]: https://github.com/wking/openshift-installer/tree/metadata

**Comment by dgoodwin** [comment]
The two uses cases were (1) service delivery will start receiving telemetry for the cluster while it's installing, but they have no knowledge of the UUID which is a problem for them, and (2) if Hive fails to upload that UUID after install we have an orphaned cluster that can't be cleaned up automatically. Writing the metadata.json as an asset is a perfect solution, we can upload once ready and if it fails, no harm done, we'll just keep retrying.

**Pull request merged**
