### PR TITLE
Power VS: fix terraform vars 

### PR DESCRIPTION
**Pull request by clnperez**
looks like when i added descriptions to all these variables i bungled a couple, and somehow the terraform provider version isn't new enough. how that was missed is a complete mystery

### CODE REVIEW

**Comment by clnperez** [comment]
@jeffnowicki @cjschaef any objections to this bump?

**Comment by jeffnowicki** [comment]
> @jeffnowicki @cjschaef any objections to this bump?

I already have a PR up with version bump https://github.com/openshift/installer/pull/5862. Christy Norman will verify and comment on that PR.

**Comment by clnperez** [comment]
@rna-afk i removed the tf provider bump from this one since @jeffnowicki 's had a newer version. can you re-lgtm this one?

**Comment by clnperez** [comment]
tests pass. can we get an approve @patrickdillon ?

**Review by jstuever — COMMENTED** [review]
/approve

**Pull request merged**
