### PR TITLE
Revert "baremetal: Extra time for provisioning interface"

### PR DESCRIPTION
**Pull request by derekhiggins**
This reverts commit abf1de99e04eeb756eebaa57d81518e929679338.

### CODE REVIEW

**Comment by derekhiggins** [comment]
/payload periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ipi-sdn-bm

**Comment by derekhiggins** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ipi-sdn-bm

**Comment by derekhiggins** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ipi-sdn-bm

**Comment by derekhiggins** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ipi-sdn-bm

**Comment by derekhiggins** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ipi-sdn-bm

**Comment by derekhiggins** [comment]
/hold
will wait until a nightly runs with https://github.com/openshift/cluster-kube-apiserver-operator/pull/1425 so that we only attempt to rule out one thing at a time

**Comment by stbenjam** [comment]
We've had a few passes of the 4.13 bm job, but the most recent payload failed, is it the same failure mode?


https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ipi-sdn-bm/1612716674417430528

Trying the bm job again on this revert 
/payload-job periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ipi-sdn-bm

**Comment by derekhiggins** [comment]
This was just a test commit, closed

**Pull request closed without merging**
