### PR TITLE
CORS-3041: Bring your own DNS for AWS

### PR DESCRIPTION
**Pull request by jhixson74**
Bring your own DNS for AWS. This relies on https://github.com/openshift/installer/pull/7775.

[Copied from https://github.com/openshift/installer/pull/7631]

```
New functionality for updating ignition data for the bootstrap node. After the terraform stage that establishes the public and private load balancer ips/dns date is applied:

    The output is read / parsed
    The load balancer data is added to a new file
    The bootstrap ignition file is regenerated
    The contents of the ignition file are used to update the file that contains the terraform variables
```

https://issues.redhat.com/browse/CORS-3041
https://issues.redhat.com/browse/CORS-3042
https://issues.redhat.com/browse/CORS-3043
https://issues.redhat.com/browse/CORS-3044
https://issues.redhat.com/browse/CORS-3045
https://issues.redhat.com/browse/CORS-3046
https://issues.redhat.com/browse/CORS-3047
https://issues.redhat.com/browse/CORS-3048

### CODE REVIEW

**Comment by patrickdillon** [comment]
As much as I could review the relevant code, it looked good, but the commit structure is confusing. This PR contains changes for both AWS & Azure--not sure if that is intentional as the PR is marked as depending on the Azure PR. 

It would help to make this easier to review to separate the commits, for example there are a lot of tf linting changes that could go into their own commit.

**Comment by jhixson74** [comment]
> As much as I could review the relevant code, it looked good, but the commit structure is confusing. This PR contains changes for both AWS & Azure--not sure if that is intentional as the PR is marked as depending on the Azure PR.
> 
> It would help to make this easier to review to separate the commits, for example there are a lot of tf linting changes that could go into their own commit.

I've split things up into relevant commits.

**Review by barbacbd — COMMENTED** [review]
This commit states that it is changing AWS defaults, but it is only GCP code changes.

**Comment by barbacbd** [comment]
> > As much as I could review the relevant code, it looked good, but the commit structure is confusing. This PR contains changes for both AWS & Azure--not sure if that is intentional as the PR is marked as depending on the Azure PR.
> > It would help to make this easier to review to separate the commits, for example there are a lot of tf linting changes that could go into their own commit.
> 
> I've split things up into relevant commits.

I would agree the structure is still a bit confusing and jumbled together. There is also a GCP commit thrown in here. I think those the main AWS and Azure code should be split into separate PRs.

I also don't know how much of this is relevant. There are a lot of changes to terraform code here and some are merely name changes. Those changes don't seem like they _need_ to be here since terraform for these platforms will be removed.

**Comment by jhixson74** [comment]
> > > As much as I could review the relevant code, it looked good, but the commit structure is confusing. This PR contains changes for both AWS & Azure--not sure if that is intentional as the PR is marked as depending on the Azure PR.
> > > It would help to make this easier to review to separate the commits, for example there are a lot of tf linting changes that could go into their own commit.
> > 
> > 
> > I've split things up into relevant commits.
> 
> I would agree the structure is still a bit confusing and jumbled together. There is also a GCP commit thrown in here. I think those the main AWS and Azure code should be split into separate PRs.
> 
> I also don't know how much of this is relevant. There are a lot of changes to terraform code here and some are merely name changes. Those changes don't seem like they _need_ to be here since terraform for these platforms will be removed.

I will explain the changes:

https://github.com/openshift/installer/pull/7775 (Bring your own DNS for Azure) was incrementally built off of your Bring your own DNS for GCP PR. For a while until that PR merged, it looked like this one. This PR  is was built incrementally off of the Azure bring your own DNS PR. So until that PR merges, this PR includes it. The GCP changes are here because they are also in the Azure PR.  I made changes to how a few things were done in the GCP to be more generic across Azure and AWS. I suppose they could be in their own PR. When I rebased things yesterday, there were changes that had been made to GCP while I was away, so I had to fix them for this PR and the Azure PR. 

As for the "name changes", I split out the vpc part of the Terraform cluster code into it's own stage to simplify getting the LB IP's. The VPC stage only creates network resources. Cluster and bootstrap create the machines and what not. 

So right now, I need the Azure PR to merge, then a lot of the commits in this PR will go away. I don't know if any of this stuff is even relevant at this point since we are getting rid of Terraform. I still see code being merged that has Terraform changes though. I will update things as it becomes more clear what the path forward is.

**Pull request closed without merging**
