### PR TITLE
OCPBUGS-44922: Power VS: SetDefaultPrivateServiceEndpoints mistakenly called for External deploys

### PR DESCRIPTION
**Pull request by miyamotoh**
In #9165, the default set of endpoint overrides necessary for `Internal` deploy was set for `External` as well for CCM. This PR properly conditionalizes the behavior.

### CODE REVIEW

**Comment by mjturek** [comment]
/retitle OCPBUGS-44922: Power VS: SetDefaultPrivateServiceEndpoints mistakenly called for External deploys

**Review by r4f4 — COMMENTED** [review]
/approve

**Pull request merged**
