### PR TITLE
DNM/SPLAT-1860: aws - track CAPA 4917

### PR DESCRIPTION
**Pull request by mtulio**

### CODE REVIEW

**Comment by mtulio** [comment]
cc @r4f4 to track OCP impact by https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/5175 on managed/unmapaned VPC scenarios.

**Comment by mtulio** [comment]
IIUC not at all jobs are exercising tags, specially for BYO VPC to test CAPA#5171. Testing the basic changes;

/test e2e-aws-ovn

**Comment by r4f4** [comment]
@mtulio it seems to be fine? It kept existing tags, including the "k8s: shared" installer-added one.
```yaml
    - id: subnet-022372a8a97126bd4
      resourceid: subnet-022372a8a97126bd4
      cidrblock: 10.0.48.0/20
      ipv6cidrblock: ""
      availabilityzone: us-east-1a
      ispublic: false
      isipv6: false
      routetableid: rtb-0c2f14d8ac0816126
      natgatewayid: null
      tags:
        aws:cloudformation:logical-id: PrivateSubnet
        aws:cloudformation:stack-id: arn:aws:cloudformation:us-east-1:460538899914:stack/ci-op-nybl0rdv-85edf-shared-vpc/c0c489a0-917d-11ef-8df4-0affc13b32f3
        aws:cloudformation:stack-name: ci-op-nybl0rdv-85edf-shared-vpc
        ci-build-info: 1849178330570428416_pull-ci-openshift-installer-master-altinfra-e2e-aws-ovn-shared-vpc
        expirationDate: 2024-10-24T00:31+00:00
        kubernetes.io/cluster/ci-op-nybl0rdv-85edf-clz9j: shared
      zonetype: availability-zone
      parentzonename: null
```
which is very similar to the [output](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_installer/8704/pull-ci-openshift-installer-master-e2e-aws-ovn-shared-vpc-custom-security-groups/1848743677787115520/artifacts/e2e-aws-ovn-shared-vpc-custom-security-groups/ipi-install-install/artifacts/clusterapi_output-1729616804/AWSCluster-openshift-cluster-api-guests-ci-op-1m6j03lr-ff55c-7p4zm.yaml) from [another job without the CAPA changes](https://github.com/openshift/installer/pull/8704):
```yaml
    - id: subnet-03227b5289b4a64f4
      resourceid: subnet-03227b5289b4a64f4
      cidrblock: 10.0.48.0/20
      ipv6cidrblock: ""
      availabilityzone: us-west-2a
      ispublic: false
      isipv6: false
      routetableid: rtb-08fbaea9464237fec
      natgatewayid: null
      tags:
        aws:cloudformation:logical-id: PrivateSubnet
        aws:cloudformation:stack-id: arn:aws:cloudformation:us-west-2:460538899914:stack/ci-op-1m6j03lr-ff55c-shared-vpc/3694ef90-9092-11ef-8c85-06fb3556500d
        aws:cloudformation:stack-name: ci-op-1m6j03lr-ff55c-shared-vpc
        ci-build-info: 1848743677787115520_pull-ci-openshift-installer-master-e2e-aws-ovn-shared-vpc-custom-security-groups
        expirationDate: 2024-10-22T20:25+00:00
        kubernetes.io/cluster/ci-op-1m6j03lr-ff55c-7p4zm: shared
      zonetype: availability-zone
      parentzonename: null
```

**Comment by mtulio** [comment]
In the job [1849178330570428416][1849178330570428416] (BYO VPC deployment), I can see the custom tags on install-config:
```
platform:
  aws:
    subnets:
    - 'subnet-022372a8a97126bd4'
...
    region: us-east-1
    userTags:
      expirationDate: 2024-10-24T04:33+00:00
      clusterName: ci-op-nybl0rdv-85edf
```

And the subnet on CAPA cluster object has only original tags from subnet:

```
    subnets:
    - id: subnet-022372a8a97126bd4
      resourceid: subnet-022372a8a97126bd4
      cidrblock: 10.0.48.0/20
      ipv6cidrblock: ""
      availabilityzone: us-east-1a
      ispublic: false
      isipv6: false
      routetableid: rtb-0c2f14d8ac0816126
      natgatewayid: null
      tags:
        aws:cloudformation:logical-id: PrivateSubnet
        aws:cloudformation:stack-id: arn:aws:cloudformation:us-east-1:[..]:stack/ci-op-nybl0rdv-85edf-shared-vpc/c0c489a0-917d-11ef-8df4-0affc13b32f3
        aws:cloudformation:stack-name: ci-op-nybl0rdv-85edf-shared-vpc
        ci-build-info: 1849178330570428416_pull-ci-openshift-installer-master-altinfra-e2e-aws-ovn-shared-vpc
        expirationDate: 2024-10-24T00:31+00:00
        kubernetes.io/cluster/ci-op-nybl0rdv-85edf-clz9j: shared
      zonetype: availability-zone
      parentzonename: null
```
I can confirm that the object hasn't the expected tag:

```sh
$ AWS_PROFILE=ci-openshift aws ec2 describe-subnets --subnet-ids subnet-022372a8a97126bd4 --region us-east-1 | jq -rc '.Subnets[].Tags[]'
{"Key":"aws:cloudformation:stack-id","Value":"arn:aws:cloudformation:us-east-1:[...]:stack/ci-op-nybl0rdv-85edf-shared-vpc/c0c489a0-917d-11ef-8df4-0affc13b32f3"}
{"Key":"aws:cloudformation:logical-id","Value":"PrivateSubnet"}
{"Key":"openshift_creationDate","Value":"2024-10-23T21:05:42.610615+00:00"}
{"Key":"ci-build-info","Value":"1849178330570428416_pull-ci-openshift-installer-master-altinfra-e2e-aws-ovn-shared-vpc"}
{"Key":"kubernetes.io/cluster/ci-op-nybl0rdv-85edf-clz9j","Value":"shared"}
{"Key":"aws:cloudformation:stack-name","Value":"ci-op-nybl0rdv-85edf-shared-vpc"}
{"Key":"expirationDate","Value":"2024-10-24T00:31+00:00"}

```

Need to check:
- is the `platform.aws.userTags` filling the subnet tags object on BYO VPC scenario?
    - if not, forcing the tags in subnet object the CAPA#4917 will apply tags to existing subnet?
- why platform.aws.userTags are not applied to subnets?


[1849178330570428416]: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_installer/9131/pull-ci-openshift-installer-master-altinfra-e2e-aws-ovn-shared-vpc/1849178330570428416

**Comment by r4f4** [comment]
>     * why platform.aws.userTags are not applied to subnets?

For BYO subnets, we don't want them to be applied. Customers can tag their own BYO resources. The `userTags` is just for installer/CAPA-created resources, right?

**Comment by mtulio** [comment]
> > ```
> > * why platform.aws.userTags are not applied to subnets?
> > ```
> 
> For BYO subnets, we don't want them to be applied. Customers can tag their own BYO resources.The `userTags` is just for installer/CAPA-created resources, right?

Yes:
```
$ openshift-install explain installconfig.platform.aws.userTags
KIND:     InstallConfig
VERSION:  v1

RESOURCE: <object>
  UserTags additional keys and values that the installer will add as tags to all resources that it creates.
  Resources created by the cluster itself may not include these tags.
```

And looks like CAPA follow the same meaning: https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/5175/files#r1814372499

Although, CAPA#5175 intents to address that scenario (tag BYO subnet), I just checked we are not setting tags to subnets: https://github.com/openshift/installer/blob/master/pkg/asset/manifests/aws/zones.go

Probably we'll not affected by that change/fix.

**Comment by r4f4** [comment]
> Probably we'll not affected by that change/fix.

@mtulio thanks for checking and for keeping an eye on possibly impactful changes in upstream CAPA!

**Pull request closed without merging**
