### PR TITLE
images: Add ssh support to UPI container

### PR DESCRIPTION
**Pull request by honza**
This is to avoid nasty nss hacks in CI. cc @andfasano

### CODE REVIEW

**Comment by honza** [comment]
I'll create a dedicated image, I think.

**Comment by stbenjam** [comment]
Could you adjust the commit to have an `images: ` prefix

**Comment by stbenjam** [comment]
/retitle images: Add ssh support to UPI container

**Comment by stbenjam** [comment]
Also looking at https://github.com/openshift/release/pull/7323, I don't see where upi-installer image is used in a step that has ssh.  Both packet-setup and teardown don't actually seem to do any SSH. Does something else that's doing call ssh (like terraform)?

**Comment by andfasano** [comment]
It seems that this one can be closed.

**Comment by abhinavdahiya** [comment]
> It seems that this one can be closed.

/close

**Pull request closed without merging**
