### PR TITLE
CORS-3296: CAPG - configure Internal LoadBalancer in the provider

### PR DESCRIPTION
**Pull request by bfournie**
Remove the configuration of the GCP Internal Load Balancer from the installer as its now being done in the CAPG provider. This allows only the Internal LB to be created to support Private Clusters.

### CODE REVIEW

**Review by barbacbd — COMMENTED** [review]
/approve

**Comment by bfournie** [comment]
CAPG fix to use internal Load Balancer is now being included, so removing hold

**Pull request merged**
