### PR TITLE
[fcos] add a new upstream community operator source

### PR DESCRIPTION
**Pull request by vrutkovs**
This adds a new "upstream-community-operators" operator source for OKD clusters, alongside with curated "community-operators"

Ref: https://github.com/openshift/okd/issues/99

### CODE REVIEW

**Comment by droslean** [comment]
@vrutkovs This PR is not tested. The jobs were retired and the `e2e-vsphere` job never passed. Can you check if this is needed to be reverted?

**Comment by vrutkovs** [comment]
Thanks, I'll have a look at vSphere later

**Pull request merged**
