### PR TITLE
Documentation/design/installconfig: Drop this file

### PR DESCRIPTION
**Pull request by wking**
Now that these structures are defined under `pkg/type/`, dropping this file avoids either the content going stale (if we don't keep it up to date) or tedious updates (if we do keep it up to date).  Consumers who want details on the structure can use [the godocs][1].

[1]: https://godoc.org/github.com/openshift/installer/pkg/types#InstallConfig

### CODE REVIEW

**Comment by crawford** [comment]
I'd rather generate docs from code than try to keep things up-to-date by hand.

/approve

**Comment by wking** [comment]
> ... so maybe add this link https://godoc.org/github.com/openshift/installer/pkg/types#InstallConfig as comment.

You mean beyond the `the godocs` link in my initial PR comment?  Or somewhere in the Git repo itself (somewhere (new?) under `Documentation/`?)?

**Comment by abhinavdahiya** [comment]
> You mean beyond the the godocs link in my initial PR comment? Or somewhere in the Git repo itself 
`README` sounds good?

**Pull request merged**
