### PR TITLE
change machine-config-server port

### PR DESCRIPTION
**Pull request by kikisdeliveryservice**
Change machine-config-server port from 49500 -> 22623
to avoid conflict with local port and node port ranges.

Closes machine-config-operator issue: [166](https://github.com/openshift/machine-config-operator/issues/166)
Requires: https://github.com/openshift/machine-config-operator/pull/368

### CODE REVIEW

**Comment by kikisdeliveryservice** [comment]
cc: @abhinavdahiya

**Comment by cgwalters** [comment]
One thing I hadn't considered too is that if we want to change this port in the future, it will also need changes in firewalling (AWS: security groups).  Do we have those under cluster management today?

If we're going to pull the trigger on this port we should probably be *really* sure that `22623` is what we want and can stick with.

**Comment by cgwalters** [comment]
Code changes seem good to me offhand.

**Comment by kikisdeliveryservice** [comment]
@wking I wasn't sure how that was generated either!  But when I looked in the repo today, the 49500 was no longer there?
https://github.com/openshift/installer/blob/master/data/data/openstack/main.tf

**Comment by wking** [comment]
> @wking I wasn't sure how that was generated either, so I left it in hopes someone would tell me :smile:

Doesn't seem to be generated (at least, #1185 bumped it and the new version contains strings that do not show up elsewhere in that diff).  I expect you can just:

```console
$ sed -i s/49500/22623/g data/data/openstack/lb/main.tf
```

**Comment by cgwalters** [comment]
> You're wondering about how this would work if someone wanted to upgrade their cluster to an OpenShift release that used a different port?

Right.

**Comment by abhinavdahiya** [comment]
@kikisdeliveryservice
https://github.com/openshift/machine-config-operator/pull/368 was merged
Also this needs a rebase..

**Comment by ashcrow** [comment]
Needs rebase.

**Comment by kikisdeliveryservice** [comment]
@abhinavdahiya question, the file that keeps needing a rebase (3 time so far) is `data/data/openstack/lb/main.tf` and the bit that changes looks kind of like something auto-generated?  I'm now wondering more if I _shouldn't_ update that one to replace the 49500->22523?

If you can confirm changing that is ok, I'll rebase and repush.

**Comment by abhinavdahiya** [comment]
> @abhinavdahiya question, the file that keeps needing a rebase (3 time so far) is `data/data/openstack/lb/main.tf` and the bit that changes looks kind of like something auto-generated? I'm now wondering more if I _shouldn't_ update that one to replace the 49500->22523?
> 
> If you can confirm changing that is ok, I'll rebase and repush.

@flaper87 / @russellb can you help @kikisdeliveryservice here regarding `data/data/openstack/lb/main.tf`

**Comment by staebler** [comment]
> @abhinavdahiya question, the file that keeps needing a rebase (3 time so far) is `data/data/openstack/lb/main.tf` and the bit that changes looks kind of like something auto-generated? I'm now wondering more if I _shouldn't_ update that one to replace the 49500->22523?
> 
> If you can confirm changing that is ok, I'll rebase and repush.

I am fairly certain that it is not auto-generated. Unfortunately, it is a script crammed into a single URL-encoded line that is going to have conflicts whenever anyone makes any change to it.

**Comment by kikisdeliveryservice** [comment]
thanks @staebler , I'll go ahead and rebase then.

**Comment by ashcrow** [comment]
@kikisdeliveryservice is this ready for a final review?

**Comment by kikisdeliveryservice** [comment]
@ashcrow yep. removed the WIP :)

**Pull request merged**
