### PR TITLE
WIP: NO MERGE: dummy commit for azure testing

### PR DESCRIPTION
**Pull request by kikisdeliveryservice**
cc: @yuqi-zhang

### CODE REVIEW

**Comment by kikisdeliveryservice** [comment]
```level=info msg="Waiting up to 30m0s for the cluster at https://api.ci-op-qqglhgt9-2dc90.ci.azure.devcluster.openshift.com:6443 to initialize..." level=fatal msg="failed to initialize the cluster: Some cluster operators are still updating: authentication, console"```

/test e2e-azure

**Comment by cgwalters** [comment]
It's worth diving into the must-gather logs I think here to see why those two operators are failing.  From a quick glance, it looks to me like [it's DNS](https://www.reddit.com/r/sysadmin/comments/6qhih0/its_always_dns/):

```
                        "message": "RouteHealthDegraded: failed to GET route: dial tcp: lookup oauth-openshift.apps.ci-op-qqglhgt9-2dc90.ci.azure.devcluster.openshift.com on 172.30.0.10:53: no such host",
```

**Comment by kikisdeliveryservice** [comment]
From the kubelet logs as well:
`Jul 30 22:51:59 ci-op-qqglhgt9-2dc90-qrhnl-master-2 hyperkube[1223]: 2019/07/30 22:49:29 auth: error contacting auth provider (retrying in 10s): request to OAuth issuer endpoint https://oauth-openshift.apps.ci-op-qqglhgt9-2dc90.ci.azure.devcluster.openshift.com/oauth/token failed: Head https://oauth-openshift.apps.ci-op-qqglhgt9-2dc90.ci.azure.devcluster.openshift.com: dial tcp: lookup oauth-openshift.apps.ci-op-qqglhgt9-2dc90.ci.azure.devcluster.openshift.com on 172.30.0.10:53: no such host`

Not sure why we are hitting this right now tho?

**Comment by abhinavdahiya** [comment]
It looks like cluster-ingress-operator regressed on Azure.

possible fix: https://github.com/openshift/cluster-ingress-operator/pull/278

some internal discussion: https://coreos.slack.com/archives/CCH60A77E/p1564527283085200

so @kikisdeliveryservice I would hold on retesting until then...

**Comment by kikisdeliveryservice** [comment]
thank you for the update @abhinavdahiya !!

**Comment by kikisdeliveryservice** [comment]
Wondering if this is less about: are these tests incompatible with Azure and more about: is Azure exposing issues in the way we are choosing to run parallel tests generally? Bc on a quick search I can find examples of many of these failures in aws-e2e as well... we are also hitting timeouts consistently here. Is this a resource issue?

**Comment by wking** [comment]
/test e2e-aws-upi

Piggybacking on this to get a recent AWS UPI run, don't mind me ;).

**Comment by wking** [comment]
To @kikisdeliveryservice's point, [here][1]'s AWS failing the same `oc new-app should succeed with a --name of 58 characters` with the same `Failed to import expected imagestreams` at around the same time that [these Azure tests hit that error][2].  Is there a Test-Grid-ish way to see which failures are flakes in these Azure tests vs. consistently failing?

[1]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-4.2/2722
[2]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_installer/2123/pull-ci-openshift-installer-master-e2e-azure/107

**Comment by kikisdeliveryservice** [comment]
aside from the inflight fix for the user groups & oauth, we're basically seeing a bunch of timeouts.. digging around now.

**Comment by kikisdeliveryservice** [comment]
attempting to replicate some results

/test e2e-azure

**Comment by yuqi-zhang** [comment]
/test e2e-azure

Last run was not great, also testing for https://github.com/openshift/origin/pull/23531

**Comment by kenya888** [comment]
2019年7月31日(水) 3:02 Kirsten <notifications@github.com>:

**Comment by abhinavdahiya** [comment]
https://testgrid.k8s.io/redhat-openshift-release-informing#redhat-canary-openshift-ocp-installer-e2e-azure-4.2

is running azure CI every 4 hours.

/close

**Pull request closed without merging**
