### PR TITLE
CFE-582 : Generate Infrastructure CR with the azure user defined tags

### PR DESCRIPTION
**Pull request by bharath-b-rh**
PR:
- Make user defined tags in installconfig available in infrastructure CR created by installer for cluster operations

### CODE REVIEW

**Comment by JoelSpeed** [comment]
Do we have any validations running against the user input? Are they allowed to specify values for tags that are typically reserved such as `kubernetes.io` or `openshift.io` namespaces?

**Comment by bharath-b-rh** [comment]
> Do we have any validations running against the user input? Are they allowed to specify values for tags that are typically reserved such as kubernetes.io or openshift.io namespaces?

Yes, installer validates the user configured tags, it's done [here](https://github.com/openshift/installer/blob/b625387cddbd388839eca982e53626f45955d376/pkg/types/azure/validation/platform.go#L32-L41)

**Comment by patrickdillon** [comment]
/approve
This LGTM but you should separate the code changes from the vendor changes. Vendoring should go in its own commit.

**Comment by bharath-b-rh** [comment]
> This LGTM but you should separate the code changes from the vendor changes. Vendoring should go in its own commit.

comment incorporated.

**Pull request merged**
