### PR TITLE
OCPBUGS-30642: pin google oauth2 version

### PR DESCRIPTION
**Pull request by r4f4**
Since the bump to GCP SDK, the GCP jobs have been failing with variations of
```
level=info msg=Credentials loaded from environment variable "GOOGLE_CLOUD_KEYFILE_JSON", file "/var/run/secrets/ci.openshift.io/cluster-profile/gce.json"
level=error msg=failed to fetch Master Machines: failed to load asset "Install Config": failed to create install config: [platform.gcp.project: Internal error: failed to create cloud resource service: Get "http://169.254.169.254/computeMetadata/v1/universe/universe_domain": dial tcp 169.254.169.254:80: connect: connection refused, : Internal error: failed to create compute service: Get "http://169.254.169.254/computeMetadata/v1/universe/universe_domain": dial tcp 169.254.169.254:80: connect: connection refused]
```

The latest google sdk will try to get the universe_domain from the metadata server if it is not set in the credentials but traffic to that server's IP can be blocked.

This fixes `connection refused` issues to access the metadata server we are seeing in CI.

### CODE REVIEW

**Comment by r4f4** [comment]
/hold
Doesn't look like this is enough to fix the problem.

**Comment by patrickdillon** [comment]
/test e2e-gcp-ovn

There seem to be test infra problems preventing this test from running

**Comment by patrickdillon** [comment]
seems like the build cluster is down, blocking these tests:

```
[36mINFO[0m[2024-03-10T18:40:17Z] build didn't start running within 1h0m0s (phase: Pending):
Found 1 events for Pod src-amd64-build:
* 2024-03-10T18:35:19Z 12x default-scheduler: 0/18 nodes are available: 1 node(s) had untolerated taint {node-role.kubernetes.io/ci-
```

**Comment by r4f4** [comment]
Cluster installed in: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_installer/8133/pull-ci-openshift-installer-master-e2e-gcp-ovn-shared-vpc/1767102139986874368

Waiting for e2e-gcp-ovn to double check.

**Comment by r4f4** [comment]
/hold cancel
e2e-gcp-ovn also installed.

**Comment by r4f4** [comment]
Update: rebased on master and fixed merge conflicts.

**Pull request merged**
