### PR TITLE
Fix perm errors with selinux enabled

### PR DESCRIPTION
**Pull request by derekwaynecarr**
fixes https://github.com/openshift/installer/issues/132

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
there are other perm errors i am still seeing on etcd machine, working my way through them

**Comment by crawford** [comment]
@derekwaynecarr Once you've tracked down all of the issues, can you also bump the [hardcoded AMI](https://github.com/openshift/release/blob/e05d0365de62ddb641b65c1bc175127ccfa79178/ci-operator/templates/cluster-launch-installer-e2e.yaml#L193) in the release repo?

**Comment by derekwaynecarr** [comment]
@crawford - i am unable to resolve issues i see on the etcd0 machine, but this fixes the master0 so would like to merge this and do the rest as follow-on.  WDYT?

**Comment by crawford** [comment]
@derekwaynecarr Sounds good. I'm close to opening a PR that removes the etcd nodes altogether, so it might be easier to see if my change is adequate.

**Comment by crawford** [comment]
@derekwaynecarr Can you cherry-pick https://github.com/openshift/installer/pull/137/commits/11dcec2e7ed373c2638ab801fc702458e1930d87 onto this? That'll bring in all of your changes to the operators.

**Comment by derekwaynecarr** [comment]
@crawford -- all set, i do not see selinux errors on etcd0 as well.

**Comment by wking** [comment]
[The e2e-aws error][1] was:

```
1 error(s) occurred:

* module.vpc.aws_route.to_nat_gw[1]: 1 error(s) occurred:

* aws_route.to_nat_gw.1: Error finding route after creating it: Unable to find matching route for Route Table (rtb-05585710172029cc3) and destination CIDR block (0.0.0.0/0).
```

Maybe that was a flake?

/retest

[1]: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_installer/134/pull-ci-origin-installer-e2e-aws/578/build-log.txt

**Comment by wking** [comment]
[Similar][1] route-gateway issue [this time][2]:

```
2 error(s) occurred:

* module.vpc.aws_route.to_nat_gw[2]: 1 error(s) occurred:

* aws_route.to_nat_gw.2: Error finding route after creating it: Unable to find matching route for Route Table (rtb-0b1f7f47433e0926a) and destination CIDR block (0.0.0.0/0).
* module.vpc.aws_route.to_nat_gw[4]: 1 error(s) occurred:

* aws_route.to_nat_gw.4: Error finding route after creating it: Unable to find matching route for Route Table (rtb-0ba7bbc0316b4a55f) and destination CIDR block (0.0.0.0/0).
```

[1]: https://github.com/openshift/installer/pull/134#issuecomment-415136462
[2]: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_installer/134/pull-ci-origin-installer-e2e-aws/579/build-log.txt

**Comment by jlebon** [comment]
Hmm, just tried these patches here, and I still see the following denials on `master0`:

```
Aug 22 21:16:12 test1-master-0 kernel: type=1400 audit(1534972572.365:3): avc:  denied  { write } for  pid=2978 comm="checkpoint" name="lock" dev="tmpfs" ino=7219 scontext=system_u:system_r:container_t:s0:c5,c64 tcontext=system_u:object_r:var_lock_t:s0 tclass=dir
Aug 22 21:16:12 test1-master-0 kernel: type=1400 audit(1534972572.375:4): avc:  denied  { add_name } for  pid=2978 comm="checkpoint" name="pod-checkpointer.lock" scontext=system_u:system_r:container_t:s0:c5,c64 tcontext=system_u:object_r:var_lock_t:s0 tclass=dir
Aug 22 21:16:12 test1-master-0 kernel: type=1400 audit(1534972572.386:5): avc:  denied  { create } for  pid=2978 comm="checkpoint" name="pod-checkpointer.lock" scontext=system_u:system_r:container_t:s0:c5,c64 tcontext=system_u:object_r:var_lock_t:s0 tclass=file
Aug 22 21:16:12 test1-master-0 kernel: type=1400 audit(1534972572.400:6): avc:  denied  { read write open } for  pid=2978 comm="checkpoint" path="/run/lock/pod-checkpointer.lock" dev="tmpfs" ino=50756 scontext=system_u:system_r:container_t:s0:c5,c64 tcontext=system_u:object_r:var_lock_t:s0 tclass=file
Aug 22 21:16:12 test1-master-0 kernel: type=1400 audit(1534972572.419:7): avc:  denied  { lock } for  pid=2978 comm="checkpoint" path="/run/lock/pod-checkpointer.lock" dev="tmpfs" ino=50756 scontext=system_u:system_r:container_t:s0:c5,c64 tcontext=system_u:object_r:var_lock_t:s0 tclass=file
Aug 22 21:16:17 test1-master-0 kernel: type=1400 audit(1534972577.192:8): avc:  denied  { read } for  pid=2863 comm="hypershift" name="ca-bundle.crt" dev="dm-0" ino=6447543 scontext=system_u:system_r:container_t:s0:c569,c810 tcontext=system_u:object_r:cert_t:s0 tclass=lnk_file
Aug 22 21:16:17 test1-master-0 kernel: type=1400 audit(1534972577.210:9): avc:  denied  { read } for  pid=2863 comm="hypershift" name="certs" dev="dm-0" ino=6447541 scontext=system_u:system_r:container_t:s0:c569,c810 tcontext=system_u:object_r:cert_t:s0 tclass=dir
Aug 22 21:16:17 test1-master-0 kernel: type=1400 audit(1534972577.215:10): avc:  denied  { read } for  pid=2863 comm="hypershift" name="Makefile" dev="dm-0" ino=6447542 scontext=system_u:system_r:container_t:s0:c569,c810 tcontext=system_u:object_r:cert_t:s0 tclass=file
Aug 22 21:16:17 test1-master-0 kernel: type=1400 audit(1534972577.220:11): avc:  denied  { open } for  pid=2863 comm="hypershift" path="/etc/pki/tls/certs/Makefile" dev="dm-0" ino=6447542 scontext=system_u:system_r:container_t:s0:c569,c810 tcontext=system_u:object_r:cert_t:s0 tclass=file
Aug 22 21:16:20 test1-master-0 kernel: type=1400 audit(1534972580.174:12): avc:  denied  { read write } for  pid=3169 comm="checkpoint" name="pod-checkpointer.lock" dev="tmpfs" ino=50756 scontext=system_u:system_r:container_t:s0:c76,c248 tcontext=system_u:object_r:var_lock_t:s0 tclass=file
Aug 22 21:16:20 test1-master-0 kernel: type=1400 audit(1534972580.186:13): avc:  denied  { open } for  pid=3169 comm="checkpoint" path="/run/lock/pod-checkpointer.lock" dev="tmpfs" ino=50756 scontext=system_u:system_r:container_t:s0:c76,c248 tcontext=system_u:object_r:var_lock_t:s0 tclass=file
Aug 22 21:16:20 test1-master-0 kernel: type=1400 audit(1534972580.203:14): avc:  denied  { lock } for  pid=3169 comm="checkpoint" path="/run/lock/pod-checkpointer.lock" dev="tmpfs" ino=50756 scontext=system_u:system_r:container_t:s0:c76,c248 tcontext=system_u:object_r:var_lock_t:s0 tclass=file
```

**Comment by derekwaynecarr** [comment]
Fixing checkpointer and others in this PR (other repo)

https://github.com/coreos-inc/tectonic-operators/pull/440#issuecomment-415243728

**Comment by wking** [comment]
Merged via #151 (which added some more e2e-aws fixes on top of this branch).

**Pull request merged**
