### PR TITLE
Update install_upi.md

### PR DESCRIPTION
**Pull request by mariaeis**
@dbenoit17 
Hello David, I have added the requirements I am aware of.

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
It would be n nice if you can make sure the commits follows the guidelines https://github.com/openshift/installer/blob/master/CONTRIBUTING.md#commit-message-format

**Comment by abhinavdahiya** [comment]
ping @mariaeis @dbenoit17

**Comment by mariaeis** [comment]
@abhinavdahiya Hello, thanks for the ping. This is kind of ancient now, I don't know if there is any point in pursuing it. If David is of the same opinion, I think we can delete it.

**Comment by abhinavdahiya** [comment]
> @abhinavdahiya Hello, thanks for the ping. This is kind of ancient now, I don't know if there is any point in pursuing it. If David is of the same opinion, I think we can delete it.

closing due to inactivity

/close

**Pull request closed without merging**
