### PR TITLE
OCPBUGS-35523: remove terraform libvirt from the installer

### PR DESCRIPTION
**Pull request by r4f4**
libvirt IPI has never been supported.

### CODE REVIEW

**Comment by r4f4** [comment]
This is an alternative to https://github.com/openshift/installer/pull/8603

**Comment by r4f4** [comment]
/payload-job periodic-ci-openshift-multiarch-master-nightly-4.17-ocp-e2e-ovn-remote-libvirt-ppc64le

**Comment by r4f4** [comment]
/payload-job periodic-ci-openshift-multiarch-master-nightly-4.17-ocp-e2e-ovn-remote-libvirt-s390x

**Comment by r4f4** [comment]
mutli-arch jobs failed to connect to the hypervisor in pre-cleanup:
```
INFO[2024-06-15T18:11:50Z] Using libvirt connection for qemu+tcp://C155F2U33/system
error: failed to connect to the hypervisor
error: Unable to resolve address 'C155F2U33' service '16509': Name or service not known
```
```
INFO[2024-06-15T19:35:48Z] Using libvirt connection for qemu+tcp://lnxocp05/system
error: failed to connect to the hypervisor
error: Unable to resolve address 'lnxocp05' service '16509': Name or service not known
```
That's because the jobs are supposed to run on `build01` cluster but `/payload-job` is running them on `build03` for some reason.

**Comment by sadasu** [comment]
ci/prow/e2e-ibmcloud-ovn  is perma-failing. ci/prow/e2e-openstack-ovn failing with an unrelated issue with a permafailing load-balancer test. e2e-crc hasn't run is a while and so not aware of its recent pass/fail status.

**Comment by r4f4** [comment]
/payload-job periodic-ci-openshift-multiarch-master-nightly-4.17-ocp-e2e-ovn-remote-libvirt-s390x

Let's try again to see if it runs from the right build cluster.

**Comment by r4f4** [comment]
> /test altinfra-e2e-aws-ovn

The altinfra variant doesn't include terraform at all.

**Pull request merged**
