### PR TITLE
libvirt: switch back to upstream terraform libvirt provider

### PR DESCRIPTION
**Pull request by eparis**
Upstream merged something very similar to our forked changes. Use that.
Also remove the option to set DNS forwarders, we don't need it anymore with local_only=yes

### CODE REVIEW

**Comment by eparis** [comment]
didn't like my PR, huh @abhinavdahiya ?

**Comment by abhinavdahiya** [comment]
I mistakenly pressed 'close and comment'  😋

**Comment by crawford** [comment]
@eparis Can you squash those last two commits? Otherwise, it looks perfect.

**Comment by steveeJ** [comment]
I removed the *dns* key from *libvirt.network*, then from scratch built a cluster with `tectonic init` and `tectonic install`.

```
(...)
Error: libvirt_network.tectonic_net: : invalid or unknown key: dns


FATA[0015] Failed to run Terraform: exit status 1  
```

Can someone else reproduce this?

**Comment by eparis** [comment]
@steveeJ gotta do: `GOBIN=~/.terraform.d/plugins go get -u github.com/dmacvicar/terraform-provider-libvirt`

**Comment by steveeJ** [comment]
> gotta do: GOBIN=~/.terraform.d/plugins go get -u github.com/dmacvicar/terraform-provider-libvirt

Thanks that helped!

**Pull request merged**
