### PR TITLE
Bug 1934557: bump RHCOS image for LUKS fix

### PR DESCRIPTION
**Pull request by miabbott**
This bumps the RHCOS boot image address the LUKS problem described in RHBZ#1934174

### CODE REVIEW

**Comment by miabbott** [comment]
`ci/prow/e2e-aws-workers-rhel7` looks like it is permafailing

`ci/prow/e2e-ovirt` looks flaky

/test ci/prow/e2e-ovirt

**Review by staebler — COMMENTED** [review]
/approve

@miabbott Can you assign someone on your team to review this for a lgtm?

**Comment by miabbott** [comment]
`e2e-aws-upgrade` doesn't have a great track record of late.  In this run, we see the following tests failing:

```[sig-node] kubelet terminates kube-apiserver gracefully
[sig-node] pods should never transition back to pending
```

Both show up in Sippy as occurring frequently in the last 7 days, so seems unlikely related to this change.

**Comment by jlebon** [comment]
This needs to bump the other arches too, no? (See https://github.com/openshift/installer/pull/4422#issuecomment-734391348 and https://github.com/openshift/installer/pull/4422#issuecomment-734415355 for instructions).

**Comment by staebler** [comment]
> `e2e-aws-upgrade` doesn't have a great track record of late. In this run, we see the following tests failing:
> 
> ```
> [sig-node] kubelet terminates kube-apiserver gracefully
> [sig-node] pods should never transition back to pending
> ```
> 
> Both show up in Sippy as occurring frequently in the last 7 days, so seems unlikely related to this change.

Yes, the allowable disruption time during upgrades was dropped to 0 in the past few weeks, making this job very flaky until the cause of disruptions is resolved. The failure is not necessarily a result of changes in this PR.

```
Mar 12 16:12:26.417: FAIL: API "openshift-api-available-reused-connections" was unreachable during disruption for at least 46s of 1h1m46s (1%)
```

**Comment by miabbott** [comment]
> This needs to bump the other arches too, no? (See [#4422 (comment)](https://github.com/openshift/installer/pull/4422#issuecomment-734391348) and [#4422 (comment)](https://github.com/openshift/installer/pull/4422#issuecomment-734415355) for instructions).

Yeah, it should but the Power builds haven't been successful in some time.

I can update the PR to include `s390x` with the fix for the LUKS problem, but we'll be waiting on a successful Power build

**Comment by miabbott** [comment]
OK, we got a successful Power build over the weekend, so I've updated all arches to be at the latest build per this morning.

**Comment by miabbott** [comment]
The failing tests look similar to the first run.  Going to need some `overrides` here.

**Comment by miabbott** [comment]
`e2e-aws` looks like the actual test succeeded

`2021/03/15 14:32:37 Pod e2e-aws-openshift-e2e-test succeeded after 28m45s`

But gathering info about nodes/machines failed?

```
2021/03/15 14:33:27 Executing pod "e2e-aws-gather-aws-console" running image "pipeline:ocp-4.5-upi-installer"
2021/03/15 14:48:27 pod didn't start running within 15m0s: 
* Container sidecar is not ready with reason PodInitializing
* Container test is not ready with reason PodInitializing
Found 4 events for Pod e2e-aws-gather-aws-console:
* 0x : Successfully assigned ci-op-9vq1cqfl/e2e-aws-gather-aws-console to ip-10-0-128-195.ec2.internal
* 3x kubelet: Failed to create pod sandbox: rpc error: code = DeadlineExceeded desc = context deadline exceeded
* 1x multus: Add eth0 [10.130.17.191/23]
* 1x multus: Add eth0 [10.130.17.215/23]```

All the other steps in that test were successful

**Pull request merged**
