### PR TITLE
Bug 1966862: pattern removed from sed to prevent expansion

### PR DESCRIPTION
**Pull request by aliasbo**
The pattern used in sed within the script /etc/NetworkManager/dispatcher.d/30-local-dns-prepender is causing the bootkube.sh not to complete sucessfully as it is not adding the 'nameserver 127.0.0.1' to /etc/resolv.conf. This is affecting vSphere IPI.

I have removed the problematic pattern

from:
  sed -i "/^# Generated by.*$/a nameserver $DNS_IP" /etc/resolv.conf

to:
  sed -i "/^# Generated by/a nameserver $DNS_IP" /etc/resolv.conf

### CODE REVIEW

**Comment by aliasbo** [comment]
The Bug 1966862 was created to support this PR.

**Review by staebler — APPROVED** [review]
/lgtm

**Pull request merged**
