### PR TITLE
NE-1316: bump openshift api to add ingress capability

### PR DESCRIPTION
**Pull request by alebedev87**
This PR bumps the OpenShift API to the version which has with the ingress capability. The `v4.16` capabilityset is added along the way because `Ingress` is the first new capability of 4.16. The [API PR](https://github.com/openshift/api/pull/1724) which adds the ingress capability is a prerequisite.

### CODE REVIEW

**Comment by sadasu** [comment]
@alebedev87 is this PR and corresponding openshift/api version bump still required?

**Comment by alebedev87** [comment]
Rebased from `master` + added the latest api with the ingress capability from https://github.com/openshift/api/pull/1724.

**Comment by alebedev87** [comment]
@sadasu : I recreated [the API PR](https://github.com/openshift/api/pull/1724) so I still plan to bump it in the installer.

**Comment by alebedev87** [comment]
/retitle NE-1316: bump openshift api to add ingress capability

PR's ready to be reviewed.

**Comment by alebedev87** [comment]
`verify-codegen` fixed.

**Review by sadasu — APPROVED** [review]

**Comment by alebedev87** [comment]
Merge conflict merged.

**Comment by alebedev87** [comment]
https://github.com/openshift/installer/pull/7546 bumped the API to the latest version so this PR is not needed anymore.

**Pull request closed without merging**
