### PR TITLE
fix: Gopkg.lock after running dep ensure on pkg/terraform/exec

### LINKED ISSUE #1471: dep check fails in pkg/terraform/exec
# Version 
dev environment

# Platform (all):
I want to add the azure terraform provider, and I'm looking at how I should manage the dependencies under `pkg/terraform/exec`.
from latest master, running `dep check` under the `exec` folder fails with : 
```
~/go/src/github.com/openshift/installer/pkg/terraform/exec master
% dep check            
# Gopkg.lock is out of sync:
github.com/hashicorp/terraform/version: in Gopkg.lock's input-imports, but neither imported nor required
```

dep version : 
```
% dep version
dep:
 version     : v0.5.0
 build date  : 2018-07-26
 git hash    : 224a564
 go version  : go1.10.3
 go compiler : gc
 platform    : darwin/amd64
 features    : ImportDuringSolve=false
```
I'll just send a PR to fix the above if in case it's not expected.

I am unsure how you manage the dependencies under this folder as there seems to be a hierarchy between exec and the plugins?
Do you have docs around how to manage the dependencies for terraform?

Thanks

### PR DESCRIPTION
**Pull request by serbrech**
See linked issue for details.

fixes #1471

### CODE REVIEW

**Comment by serbrech** [comment]
@enxebre

**Comment by wking** [comment]
Catching up with 0502c5c4d (#919).

**Comment by wking** [comment]
[e2e][1]:

```
level=fatal msg="failed to initialize the cluster: Working towards 0.0.1-2019-03-26-234559: 98% complete: timed out waiting for the condition"
```

Fixed since by openshift/cluster-version-operator#141.

/retest

[1]: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_installer/1472/pull-ci-openshift-installer-master-e2e-aws/4664

**Comment by serbrech** [comment]
Should this be merged now? @wking?

**Comment by wking** [comment]
[e2e-aws][1]:

```
Failing tests:

[Feature:Builds][Conformance] s2i build with a root user image should create a root build and fail without a privileged SCC [Suite:openshift/conformance/parallel/minimal]
```

/retest

[1]: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_installer/1472/pull-ci-openshift-installer-master-e2e-aws/4738

**Pull request merged**
