### PR TITLE
tls: remove deprecated kubelet.kubeconfig

### PR DESCRIPTION
**Pull request by deads2k**
The kube-ca was a signer that allowed for trust domain confusion,
this removes the bootstrap kubelet kubeconfig from that chain and uses
a dedicated chain that can be discarded, shortened, or rotated by
an independent owner.

@abhinavdahiya as we discussed
@sjenning can you find me a worker bootstrap kubeconfig.  I think I have theory about why that funny/wrong CA is present.

### CODE REVIEW

**Comment by wking** [comment]
Is this for https://bugzilla.redhat.com/show_bug.cgi?id=1684049 ?

**Comment by deads2k** [comment]
> Is this for https://bugzilla.redhat.com/show_bug.cgi?id=1684049 ?

No.  It is unrelated.

**Comment by deads2k** [comment]
statefulset flake

/retest

**Comment by abhinavdahiya** [comment]
as per @deads2k suggestion, we are waiting for installer to cut for beta2 drop. will cancel hold after that.

**Comment by deads2k** [comment]
@wking @abhinavdahiya ping

**Pull request merged**
