### PR TITLE
baremetal: expand baremetal IPI docs to include customizations

### PR DESCRIPTION
**Pull request by stbenjam**
The platform now has a bunch of optional possible customizations, this
expands the documentation to follow the other platforms by including a
customization.md that details each of the options and why you might want
to use them.

### CODE REVIEW

**Comment by stbenjam** [comment]
This is probably good enough for a first pass, would someone mind taking a look?

/assign @abhinavdahiya 
/cc @hardys

**Comment by abhinavdahiya** [comment]
Why is this different in structure and formatting compared to https://github.com/openshift/installer/blob/195a8aa017031966f99331559f2d06a35fedda2d/docs/user/aws/customization.md ??

I would like to see them be similarly formatted.

Also can we no create new `metal/ipi` directory, and keep this in the same directory, this new one might create more confusion.

**Comment by stbenjam** [comment]
I don't like the AWS formatting because we need to group settings together (e.g. here's all the networking-related things you can tweak), and we also need much more prose to describe what it does than AWS documentation conveys in it's simple bulleted list and minimal examples.

**Comment by abhinavdahiya** [comment]
> I don't like the AWS formatting because we need to group settings together (e.g. here's all the networking-related things you can tweak), and we also need much more prose to describe what it does than AWS documentation conveys in it's simple bulleted list and minimal examples.

I think the format there should be able to support your list and also provide a way to look at all the fields available..

I don't see how it hinders your "group settings together" or add as much prose your need with the examples.

**Comment by stbenjam** [comment]
Can you clarify the complaint? This is awfully nitpicky. It uses the same title format as AWS, and we don't have machine-pool scoped parameters. Do you want another layer of headers that clarifies these are all Cluster-scoped properties?

I absolutely want examples in-line with the text, and the grouping as I've written it.

**Comment by stbenjam** [comment]
I'll push an update in a minute with a few formatting changes that make it look closer to AWS, but I don't think it needs to be exact...

**Comment by stbenjam** [comment]
PTAL, I've updated the formatting.

**Comment by abhinavdahiya** [comment]
> I absolutely want examples in-line with the text, and the grouping as I've written it.

Sure, if you must.

/approve
/lgtm

**Pull request merged**
