### PR TITLE
THIS REPO IS FOR PR JOB TESTING ONLY

### PR DESCRIPTION
**Pull request by smarterclayton**
Before creating your PR, please make sure to add the appropriate GitHub labels
like e.g. `run-smoke-tests` + `platform/<xxx>`. For more details see
[tests/README.md](../tests/README.md).

(In case you don't have permissions to add labels, please ask a
[Maintainer](../MAINTAINERS).)

### CODE REVIEW

**Comment by crawford** [comment]
It looks like this can be closed. I'd close it for you, @smarterclayton but I don't have permissions anymore.

**Comment by smarterclayton** [comment]
I need to set up a team for this group, will make someone an admin

**Comment by smarterclayton** [comment]
Made you an owner of the installer team which has write to this repo, you
can add others.

**Comment by smarterclayton** [comment]
Also, you can always use the bot

/close

**Pull request closed without merging**
