### PR TITLE
Bug 1791457: [release-4.3] Add support for AWS Bahrain region me-south-1

### PR DESCRIPTION
**Pull request by patrickdillon**
4.3 variant of #2826 
cherry-picks 2 out of 4 of those commits
manually update Gopkg.toml and run `dep ensure`
separate commit to bump RHCOS release image for 4.3

### CODE REVIEW

**Comment by patrickdillon** [comment]
@sdodson should I create a bz for this (and forthcoming 4.2) to get this into 4.3?

**Comment by wking** [comment]
> should I create a bz for this (and forthcoming 4.2) to get this into 4.3?

If we want to backport this feature to 4.2 and 4.3, then yes, we'll need bugs to motivate the backports.

**Comment by patrickdillon** [comment]
Removed the RHCOS bump because it was already satisfied by 079c8139f6ba0a0d77ff81f2c0a166a1be6f3369

**Pull request merged**
