### PR TITLE
Update cluster-api-provider-ovirt, cluster-api-provider-aws and baremetal-operator

### PR DESCRIPTION
**Pull request by Gal-Zaidman**
This PR updates the vendor to use
cluster-api-provider-ovirt from 15.03.2021

This is required for https://github.com/openshift/installer/pull/4674

It also updates the required deps: cluster-api-provider-aws and baremetal-operator

### CODE REVIEW

**Comment by staebler** [comment]
I get this when I try to tidy the modules.
```
$ go mod tidy
warning: ignoring symlink /home/staebler/src/installer/pkg/asset/store/data
go: finding module for package sigs.k8s.io/controller-runtime/pkg/runtime/log
github.com/openshift/installer/pkg/tfvars/baremetal imports
	github.com/metal3-io/baremetal-operator/pkg/bmc tested by
	github.com/metal3-io/baremetal-operator/pkg/bmc.test imports
	sigs.k8s.io/controller-runtime/pkg/runtime/log: module sigs.k8s.io/controller-runtime@latest found (v0.8.2), but does not contain package sigs.k8s.io/controller-runtime/pkg/runtime/log
```

**Comment by Gal-Zaidman** [comment]
> ```
> 	sigs.k8s.io/controller-runtime/pkg/runtime/log: module sigs.k8s.io/controller-runtime@latest found (v0.8.2), but does not contain package sigs.k8s.io/controller-runtime/pkg/runtime/log
> ```

Looking at the [baremetal-operator](https://github.com/openshift/baremetal-operator/blob/master/go.mod#L18) it uses controller-runtime v0.6.2 which change the log path on 0.7 ([example](https://github.com/openshift/cluster-api-provider-ovirt/commit/b410f5cdf8e5283035c8140392d5025dd61da9a7))
Is there a way to solve this within go mod? meaning without porting baremetal-operator to controller-runtime 0.7 ?

**Comment by janoszen** [comment]
It looks like the log package was removed in v0.8.2: https://github.com/kubernetes-sigs/controller-runtime/tree/v0.8.2/pkg/runtime

Captain obvious here: is it wise to rely on a zero-dot version of something?

**Comment by Gal-Zaidman** [comment]
> It looks like the log package was removed in v0.8.2: https://github.com/kubernetes-sigs/controller-runtime/tree/v0.8.2/pkg/runtime

Yep, I hitted in in the ovit example I linked, but hoped there is a quicker fix then sending a PR to bm, but that is probably the way to go

**Comment by Gal-Zaidman** [comment]
Pushed https://github.com/openshift/baremetal-operator/pull/129

**Comment by Gal-Zaidman** [comment]
> I get this when I try to tidy the modules.
> 
> ```
> $ go mod tidy
> warning: ignoring symlink /home/staebler/src/installer/pkg/asset/store/data
> go: finding module for package sigs.k8s.io/controller-runtime/pkg/runtime/log
> github.com/openshift/installer/pkg/tfvars/baremetal imports
> 	github.com/metal3-io/baremetal-operator/pkg/bmc tested by
> 	github.com/metal3-io/baremetal-operator/pkg/bmc.test imports
> 	sigs.k8s.io/controller-runtime/pkg/runtime/log: module sigs.k8s.io/controller-runtime@latest found (v0.8.2), but does not contain package sigs.k8s.io/controller-runtime/pkg/runtime/log
> ```

My PR to port baremetal-operator to controller-runtime0.7 was merged, so now go mod tidy works for me

**Comment by Gal-Zaidman** [comment]
/unhold

e2e-metal-ipi passed ovn and regular

**Comment by Gal-Zaidman** [comment]
@staebler Looks like e2e-aws-upgrade is broken for 2 days is that really required for the PR?

**Comment by staebler** [comment]
> @staebler Looks like e2e-aws-upgrade is broken for 2 days is that really required for the PR?

Yes, since the changes in this PR make changes to AWS as well. That job has been a pain point for everyone since the acceptable downtime during upgrades was dropped to 0.

**Comment by Gal-Zaidman** [comment]
@staebler 
The aws upgrade test is blocking the go mod update for almost a week now :/
I really think that the fact that it fails the tests (which mostly fail if you look at the history) and not the installation is a good indication that this PR doesn't break AWS upgrade.
Can you please take a look? or consult with someone from the AWS provider to confirm?

This PR is blocking features we have for 4.8

**Comment by staebler** [comment]
> @staebler
> The aws upgrade test is blocking the go mod update for almost a week now :/
> I really think that the fact that it fails the tests (which mostly fail if you look at the history) and not the installation is a good indication that this PR doesn't break AWS upgrade.
> Can you please take a look? or consult with someone from the AWS provider to confirm?
> 
> This PR is blocking features we have for 4.8

I do agree that your changes almost assuredly do not have any effect on the upgrade. However, given that there is a change to aws-sdk-go, which is used by terraform to install the cluster, I cannot be certain that there are not changes that may affect upgrade. The architects have prioritized ensuring 0 downtime during upgrades, so this is a pain that we must all bear. If you have concerns, feel free to bring it up with them.

**Pull request merged**
