### PR TITLE
baremetal: Remove unused assets

### PR DESCRIPTION
**Pull request by bcrochet**
The baremetal bootstrap assets have moved into machine-config-operator.
These files are vestigal and are no longer required. They can be safely
removed.

### CODE REVIEW

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/1016/

**Comment by abhinavdahiya** [comment]
/hold

The master is open only for bug fixes as we prepare for 4.2 release. this need a bugzilla targeted for 4.2 to merge.

**Comment by hardys** [comment]
@bcrochet: what's the plan for this - I guess these now-redundant assets can be considered a bug, so you can raise a bz against 4.2 then update the title of this PR so we can remove the hold?

**Comment by hardys** [comment]
Also would be good to see metal3ci pass, but that's currently blocked on https://github.com/openshift/installer/pull/2277

**Comment by hardys** [comment]
> @hardys: We can, but I don't think it's necessary for 4.2. These are on the bootstrap node, which makes them ephemeral anyway.

Ok thanks for confirming, that's fine by me, just wanted to ensure this wasn't blocked on a bz unintentionally :)

**Comment by stbenjam** [comment]
metal3 ci http://10.8.144.11:8080/job/dev-tools/

**Comment by patrickdillon** [comment]
/uncc @patrickdillon 
will leave this to more knowledgeable folks

**Pull request merged**
