### PR TITLE
asset/precluster: pre-cluster stage

### PR DESCRIPTION
**Pull request by staebler**
Add an installer command to create a pre-cluster asset. This asset includes read-only copies of assets that are useful prior to creating a cluster.

* bootstrap ignition
* master ignition
* worker ignition
* metadata.json
* kubeconfig
* kube admin password

The files are created in a pre-cluster directory under the assets directory.

The pre-cluster stage is a replacement for the node-configs stage, which had collected more targeted assets than just node configs. The old stage has been retained but deprecated.

A bootstrap-config stage has also been added which targets just the bootstrap ignition.

A bootstrap-config stage has been added which targets just the bootstrap ignition. A node-config stage has been added which targets just the master and worker ignitions.

Fixes https://jira.coreos.com/browse/CORS-948

### CODE REVIEW

**Comment by staebler** [comment]
```console
$ openshift-install create node-config
INFO Consuming "Install Config" from target directory
$ tree
.
├── master.ign
└── worker.ign

0 directories, 2 files
$ openshift-install create bootstrap-config
INFO Consuming "Master Ignition Config" from target directory 
INFO Consuming "Worker Ignition Config" from target directory 
$ tree
.
└── bootstrap.ign

0 directories, 1 file
$ openshift-install create pre-cluster
INFO Consuming "Bootstrap Ignition Config" from target directory
$ tree
.
└── pre-cluster
    ├── auth
    │   ├── kubeadmin-password
    │   └── kubeconfig
    ├── bootstrap.ign
    ├── master.ign
    ├── metadata.json
    └── worker.ign

2 directories, 6 files
```

**Comment by abhinavdahiya** [comment]
can we move each of these to separate PRs:
https://github.com/openshift/installer/pull/1532/commits/21b631a8d74c59cec4fe55c82512c9a33ad88900
https://github.com/openshift/installer/pull/1532/commits/a9b38030026efba18c1595dfb543aa0191323936

??

**Comment by staebler** [comment]
> can we move each of these to separate PRs:
> [21b631a](https://github.com/openshift/installer/commit/21b631a8d74c59cec4fe55c82512c9a33ad88900)
> [a9b3803](https://github.com/openshift/installer/commit/a9b38030026efba18c1595dfb543aa0191323936)
> 
> ??

@abhinavdahiya Sure. I can. This PR won't work without those two commits, though, so I would still keep them in this PR. Do you have specific concerns about the individual commits where you think some of them may be acceptable and others not?

**Comment by abhinavdahiya** [comment]
> > can we move each of these to separate PRs:
> > [21b631a](https://github.com/openshift/installer/commit/21b631a8d74c59cec4fe55c82512c9a33ad88900)
> > [a9b3803](https://github.com/openshift/installer/commit/a9b38030026efba18c1595dfb543aa0191323936)
> > ??
> 
> @abhinavdahiya Sure. I can. This PR won't work without those two commits, though, so I would still keep them in this PR. Do you have specific concerns about the individual commits where you think some of them may be acceptable and others not?

I'm hoping we can fix the metadata and missing kubeadmin issue in existing setup before we decide on using the `pre-cluster` target.

**Comment by staebler** [comment]
On further analysis, the issue addressed by 21b631a8d74c59cec4fe55c82512c9a33ad88900 is not a problem in master. The metadata.json file is not created when `create cluster` is run after `create ignition-configs`. However, since the `Load` function for the Metadata asset returns false, the asset store does not think that the asset is on disk. Consequently, the metadata.json file is not consumed by `create cluster` is run. The issue only becomes a problem with the `pre-cluster` stage introduced in this PR. So, I don't know if it makes sense to move 21b631a8d74c59cec4fe55c82512c9a33ad88900 to its own PR.

**Comment by staebler** [comment]
Also, the kubeadmin-password file only needs to be created by the Kubeadmin Password asset instead of the Cluster asset so that it can also be created by the `pre-cluster` stage. Since a9b38030026efba18c1595dfb543aa0191323936 is only necessary if the `pre-cluster` stage is added, it doesn't make sense to move a9b38030026efba18c1595dfb543aa0191323936 to its own PR either.

**Comment by staebler** [comment]
21b631a8d74c59cec4fe55c82512c9a33ad88900: #1538 
a9b38030026efba18c1595dfb543aa0191323936: #1539

**Comment by wking** [comment]
> 21b631a: #1538
> a9b3803: #1539

Both landed; can we get a rebase here? :)

**Comment by staebler** [comment]
> > [21b631a](https://github.com/openshift/installer/commit/21b631a8d74c59cec4fe55c82512c9a33ad88900): #1538
> > [a9b3803](https://github.com/openshift/installer/commit/a9b38030026efba18c1595dfb543aa0191323936): #1539
> 
> Both landed; can we get a rebase here? :)

b319655be...f681b6581

**Comment by abhinavdahiya** [comment]
closing due to inactivity. Please reopen if needed.

/close

**Pull request closed without merging**
