### PR TITLE
Bug 1879649: oVirt UPI - Simplify create templates

### PR DESCRIPTION
**Pull request by gekorob**
Removing some not mandatory attributes according to the
ovirt.image-template docs and the ovirt/RHV UPI docs that
explains mandatory parameters to set in the inventory.yml

### CODE REVIEW

**Review by dougsland — APPROVED** [review]

**Comment by dougsland** [comment]
waiting ovirt CI pass  to merge.

**Review by jan-zmeskal — APPROVED** [review]

**Pull request merged**
