### PR TITLE
Bug 1788707: Backport Azure private DNS to 4.2 branch

### PR DESCRIPTION
**Pull request by jhixson74**
This brings Azure private DNS into the 4.2 branch

https://issues.redhat.com/browse/CORS-1316

### CODE REVIEW

**Comment by wking** [comment]
There's no 4.3 analog to this installer PR, and the 4.3 [rhbz#1772804][1] is VERIFIED with no installer changes.  Is that intentional?  Can you explain why 4.3+ don't need this installer change?

[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1772804

**Comment by wking** [comment]
[Azure job][1] died with:

```
fail [github.com/openshift/origin/test/extended/prometheus/prometheus_builds.go:135]: Expected
    <map[string]error | len:1>: {
        "ALERTS{alertname!=\"Watchdog\",alertstate=\"firing\"} >= 1": {
            s: "promQL query: ALERTS{alertname!=\"Watchdog\",alertstate=\"firing\"} >= 1 had reported incorrect results: ALERTS{alertname=\"ClusterMonitoringOperatorDown\", alertstate=\"firing\", severity=\"critical\"} => 1 @[1578596289.224]\nALERTS{alertname=\"MachineAPIOperatorDown\", alertstate=\"firing\", severity=\"critical\"} => 1 @[1578596289.224]\nALERTS{alertname=\"TargetDown\", alertstate=\"firing\", job=\"api\", namespace=\"openshift-apiserver\", service=\"api\", severity=\"warning\"} => 1 @[1578596289.224]\nALERTS{alertname=\"TargetDown\", alertstate=\"firing\", job=\"catalog-operator-metrics\", namespace=\"openshift-operator-lifecycle-manager\", service=\"catalog-operator-metrics\", severity=\"warning\"} => 1 @[1578596289.224]\nALERTS{alertname=\"TargetDown\", alertstate=\"firing\", job=\"cluster-monitoring-operator\", namespace=\"openshift-monitoring\", service=\"cluster-monitoring-operator\", severity=\"warning\"} => 1 @[1578596289.224]\nALERTS{alertname=\"TargetDown\", alertstate=\"firing\", job=\"controller-manager\", namespace=\"openshift-controller-manager\", service=\"controller-manager\", severity=\"warning\"} => 1 @[1578596289.224]\nALERTS{alertname=\"TargetDown\", alertstate=\"firing\", job=\"dns-default\", namespace=\"openshift-dns\", service=\"dns-default\", severity=\"warning\"} => 1 @[1578596289.224]\nALERTS{alertname=\"TargetDown\", alertstate=\"firing\", job=\"machine-api-operator\", namespace=\"openshift-machine-api\", service=\"machine-api-operator\", severity=\"warning\"} => 1 @[1578596289.224]\nALERTS{alertname=\"TargetDown\", alertstate=\"firing\", job=\"metrics\", namespace=\"openshift-apiserver-operator\", service=\"metrics\", severity=\"warning\"} => 1 @[1578596289.224]\nALERTS{alertname=\"TargetDown\", alertstate=\"firing\", job=\"metrics\", namespace=\"openshift-authentication-operator\", service=\"metrics\", severity=\"warning\"} => 1 @[1578596289.224]\nALERTS{alertname=\"TargetDown\", alertstate=\"firing\", job=\"metrics\", namespace=\"openshift-controller-manager-operator\", service=\"metrics\", severity=\"warning\"} => 1 @[1578596289.224]\nALERTS{alertname=\"TargetDown\", alertstate=\"firing\", job=\"metrics\", namespace=\"openshift-kube-apiserver-operator\", service=\"metrics\", severity=\"warning\"} => 1 @[1578596289.224]\nALERTS{alertname=\"TargetDown\", alertstate=\"firing\", job=\"metrics\", namespace=\"openshift-kube-controller-manager-operator\", service=\"metrics\", severity=\"warning\"} => 1 @[1578596289.224]\nALERTS{alertname=\"TargetDown\", alertstate=\"firing\", job=\"metrics\", namespace=\"openshift-kube-scheduler-operator\", service=\"metrics\", severity=\"warning\"} => 1 @[1578596289.224]\nALERTS{alertname=\"TargetDown\", alertstate=\"firing\", job=\"olm-operator-metrics\", namespace=\"openshift-operator-lifecycle-manager\", service=\"olm-operator-metrics\", severity=\"warning\"} => 1 @[1578596289.224]",
        },
    }
to be empty
```

That's a MachineAPIOperatorDown and a bunch of TargetDown.  I didn't dig deeper to see if they were related to this PR or not.

[1]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_installer/2825/pull-ci-openshift-installer-release-4.2-e2e-azure/84

**Comment by jhixson74** [comment]
> There's no 4.3 analog to this installer PR, and the 4.3 [rhbz#1772804](https://bugzilla.redhat.com/show_bug.cgi?id=1772804) is VERIFIED with no installer changes. Is that intentional? Can you explain why 4.3+ don't need this installer change?

This code is a feature in 4.3. The same commits in this PR are already in 4.3. This PR is for back porting the changes to 4.2.

**Comment by jhixson74** [comment]
> [Azure job](https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_installer/2825/pull-ci-openshift-installer-release-4.2-e2e-azure/84) died with:
> 
> ```
> fail [github.com/openshift/origin/test/extended/prometheus/prometheus_builds.go:135]: Expected
>     <map[string]error | len:1>: {
>         "ALERTS{alertname!=\"Watchdog\",alertstate=\"firing\"} >= 1": {
>             s: "promQL query: ALERTS{alertname!=\"Watchdog\",alertstate=\"firing\"} >= 1 had reported incorrect results: ALERTS{alertname=\"ClusterMonitoringOperatorDown\", alertstate=\"firing\", severity=\"critical\"} => 1 @[1578596289.224]\nALERTS{alertname=\"MachineAPIOperatorDown\", alertstate=\"firing\", severity=\"critical\"} => 1 @[1578596289.224]\nALERTS{alertname=\"TargetDown\", alertstate=\"firing\", job=\"api\", namespace=\"openshift-apiserver\", service=\"api\", severity=\"warning\"} => 1 @[1578596289.224]\nALERTS{alertname=\"TargetDown\", alertstate=\"firing\", job=\"catalog-operator-metrics\", namespace=\"openshift-operator-lifecycle-manager\", service=\"catalog-operator-metrics\", severity=\"warning\"} => 1 @[1578596289.224]\nALERTS{alertname=\"TargetDown\", alertstate=\"firing\", job=\"cluster-monitoring-operator\", namespace=\"openshift-monitoring\", service=\"cluster-monitoring-operator\", severity=\"warning\"} => 1 @[1578596289.224]\nALERTS{alertname=\"TargetDown\", alertstate=\"firing\", job=\"controller-manager\", namespace=\"openshift-controller-manager\", service=\"controller-manager\", severity=\"warning\"} => 1 @[1578596289.224]\nALERTS{alertname=\"TargetDown\", alertstate=\"firing\", job=\"dns-default\", namespace=\"openshift-dns\", service=\"dns-default\", severity=\"warning\"} => 1 @[1578596289.224]\nALERTS{alertname=\"TargetDown\", alertstate=\"firing\", job=\"machine-api-operator\", namespace=\"openshift-machine-api\", service=\"machine-api-operator\", severity=\"warning\"} => 1 @[1578596289.224]\nALERTS{alertname=\"TargetDown\", alertstate=\"firing\", job=\"metrics\", namespace=\"openshift-apiserver-operator\", service=\"metrics\", severity=\"warning\"} => 1 @[1578596289.224]\nALERTS{alertname=\"TargetDown\", alertstate=\"firing\", job=\"metrics\", namespace=\"openshift-authentication-operator\", service=\"metrics\", severity=\"warning\"} => 1 @[1578596289.224]\nALERTS{alertname=\"TargetDown\", alertstate=\"firing\", job=\"metrics\", namespace=\"openshift-controller-manager-operator\", service=\"metrics\", severity=\"warning\"} => 1 @[1578596289.224]\nALERTS{alertname=\"TargetDown\", alertstate=\"firing\", job=\"metrics\", namespace=\"openshift-kube-apiserver-operator\", service=\"metrics\", severity=\"warning\"} => 1 @[1578596289.224]\nALERTS{alertname=\"TargetDown\", alertstate=\"firing\", job=\"metrics\", namespace=\"openshift-kube-controller-manager-operator\", service=\"metrics\", severity=\"warning\"} => 1 @[1578596289.224]\nALERTS{alertname=\"TargetDown\", alertstate=\"firing\", job=\"metrics\", namespace=\"openshift-kube-scheduler-operator\", service=\"metrics\", severity=\"warning\"} => 1 @[1578596289.224]\nALERTS{alertname=\"TargetDown\", alertstate=\"firing\", job=\"olm-operator-metrics\", namespace=\"openshift-operator-lifecycle-manager\", service=\"olm-operator-metrics\", severity=\"warning\"} => 1 @[1578596289.224]",
>         },
>     }
> to be empty
> ```
> 
> That's a MachineAPIOperatorDown and a bunch of TargetDown. I didn't dig deeper to see if they were related to this PR or not.

The only problem I am aware of as to why the Azure test will fail is the ingress operator not having support for the new Azure private DNS in 4.2. The PR for that (https://github.com/openshift/cluster-ingress-operator/pull/344) merged today, so the test should now work. I am not clear on if this change is immediate or if there is a delay before it is available for CI.

**Comment by wking** [comment]
> I am not clear on if this change is immediate or if there is a delay before it is available for CI.

PR merging should be all that is needed before changes appear in subsequent CI jobs.  But if you want to check for a particular job, can drill in like:

* `Details` link for the e2e-azure job link from this PR to get to https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_installer/2825/pull-ci-openshift-installer-release-4.2-e2e-azure/85
* `Artifacts` link to get to https://gcsweb-ci.svc.ci.openshift.org/gcs/origin-ci-test/pr-logs/pull/openshift_installer/2825/pull-ci-openshift-installer-release-4.2-e2e-azure/85/
* Walk `artifacts` -> `release-latest` -> `release-payload-latest` -> `image-references` to get to https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_installer/2825/pull-ci-openshift-installer-release-4.2-e2e-azure/85/artifacts/release-latest/release-payload-latest/image-references , which has:

    ```
          {
            "name": "cluster-ingress-operator",
            "annotations": {
              "io.openshift.build.commit.id": "c0a5e5eb5a9e80dd304f4e49066e4bf52708be4a",
    ```

    which is that PR landing: openshift/cluster-ingress-operator@c0a5e5eb5a9e80dd304f4e49066e4bf52708be4a

**Comment by wking** [comment]
> This code is a feature in 4.3.

So looks like this mostly backports #2470, but with 36e431a54 and 0ec99ccc4 unique to the backport?  0ec99ccc4f6 overlaps with, but is not the same as 48da3788433 (#2429).  Oh, I see you have some commit references in your cherry-pick commit references.  Looking...

**Comment by wking** [comment]
* af00810e035 -> fa5412a49b is clean.
* c1e24af93cd -> 3c1118f5ce71 drops [the master `private_dns_zone_id` removal][1].  I'm not clear on why, because [that variable is in 4.2][2].  Ah, then you clean it out later in 0ec99ccc4f6.  You could squash that `private_dns_zone_id` removal down into 3c1118f5ce71 to make the cherry-picks clearer, but the end effect is the same.

[1]: https://github.com/openshift/installer/commit/c1e24af93cdfa5257627f5b66a24686e260dc231#diff-e1983977011640174c1c393e26c9ac96L81
[2]: https://github.com/openshift/installer/blob/46f909e4ccb4f7a4f82bf1ee28b32fa011a6bd1f/data/data/azure/master/variables.tf#L86

**Comment by wking** [comment]
* 7d3119f8ba3ece -> eb1884da336e is clean
* e80fde1336b2c5feb4 -> 36e431a54bf1 is clean
* 65111a04a42c -> 5e8e8a5816ee is clean
* I don't understand 0ec99ccc4f6d1 (except for the `private_dns_zone_id` recovery mentioned above).

**Comment by jhixson74** [comment]
>     * [7d3119f](https://github.com/openshift/installer/commit/7d3119f8ba3ecefba5b1ec7168de526fdab81b6d) -> [eb1884d](https://github.com/openshift/installer/commit/eb1884da336e9b5d276f49378a1f9beaa9b5801f) is clean
> 
>     * [e80fde1](https://github.com/openshift/installer/commit/e80fde1336b2c5feb400428b74364fc455b78c57) -> [36e431a](https://github.com/openshift/installer/commit/36e431a54bf18a472a1ea912d2ccac21820df22e) is clean
> 
>     * [65111a0](https://github.com/openshift/installer/commit/65111a04a42cf864900086acdbb46ee86a8f9724) -> [5e8e8a5](https://github.com/openshift/installer/commit/5e8e8a5816ee6c50d9850cdfd73d10e05c800d8b) is clean
> 
>     * I don't understand [0ec99cc](https://github.com/openshift/installer/commit/0ec99ccc4f6d1b68670fc8ac4b008a87a7822893) (except for the `private_dns_zone_id` recovery mentioned above).

master_subnet_cidr was nuked in 4.3 except in the vnet module, where it has become a local. The cherry pick relies on this, so that commit removed the older 4.2 references.

**Comment by wking** [comment]
/approve

Trying again.

**Comment by wking** [comment]
/approve

Eventually Prow will hear about this ;).

**Pull request merged**
