### PR TITLE
OCPBUGS-37780: aws: do not allow edge pools of different arch

### PR DESCRIPTION
**Pull request by r4f4**
When we enabled the multi-arch day0 feature via the MultiArchInstallAWS feature gate, we inadvertently allowed "worker" and "edge" compute machine pools to have different architectures.

This change introduces a validation to check all the compute pools use the same architecture and errors out otherwise.

### CODE REVIEW

**Comment by r4f4** [comment]
With the following install-config.yaml:
```yaml
apiVersion: v1
metadata:
  name: rdossant-installer-07312024
publish: External
baseDomain: devcluster.openshift.com
platform:
  aws:
    region: us-east-1
compute:
  - name: worker
    platform:
      aws: {}
  - name: edge
    architecture: arm64
    platform:
      aws:
        zones: ["us-east-1-dfw-2a"]
featureSet: CustomNoUpgrade
featureGates:
  - MultiArchInstallAWS=true
```

* before the change:
```
$ ./openshift-install create manifests
WARNING Found override for release image (quay.io/openshift-release-dev/ocp-release:4.17.0-ec.2-x86_64). Release Image Architecture is unknown
WARNING Could not determine release architecture for multi arch cluster configuration. Make sure the release is a multi architecture payload.
INFO Credentials loaded from the "default" profile in file "/run/secrets/aws_credentials"
ERROR failed to fetch Master Machines: failed to load asset "Install Config": failed to create install config: compute[1].platform.aws.zones: Invalid value: "us-east-1-dfw-2a": zone group is not opted-in: us-east-1-dfw-
```
* after the change:
```
$ ./openshift-install create manifests
WARNING Found override for release image (quay.io/openshift-release-dev/ocp-release:4.17.0-ec.2-x86_64). Release Image Architecture is unknown
WARNING Could not determine release architecture for multi arch cluster configuration. Make sure the release is a multi architecture payload.
INFO Credentials loaded from the "default" profile in file "/run/secrets/aws_credentials"
ERROR failed to fetch Master Machines: failed to load asset "Install Config": failed to create install config: [compute[1].architecture: Invalid value: "arm64": all compute machine pools must be of the same architecture, compute[1].platform.aws.zones: Invalid value: "us-east-1-dfw-2a": zone group is not opted-in: us-east-1-dfw-2]
```

**Comment by r4f4** [comment]
Update: fixed logic to handle architecture not defined and added unit tests.

**Comment by mtulio** [comment]
> ERROR failed to fetch Master Machines: ....compute[1].platform.aws.zones: Invalid value: "us-east-1-dfw-2a": zone group is not opted-in: us-east-1-dfw-2]

Hi @r4f4 , did you tested `arm64/arm64`  in a Local Zone zone that is enabled (opted-in)?

Considering the limitation of supported types[1], versus the offerings[2] of those types in AWS Local Zones, I am unsure if any of those options are valid:
- 1/ disable day-0 edge pool when deploying on ARM64, instructing the user to day-2. (no network automation by installer); or
- 2/ set the replicas==0 in the edge pool when edge pool is set to `arm64`. Installer will automate the network for edge zones, but MAPI may not fail to create instance in mostly edge zones that does not support any of [1], set on machineset manifest; or
- 3/ support multi-arch compute pools by setting the respective arch for each pool

@r4f4 @patrickdillon any of those options makes sense?

[1] https://github.com/openshift/installer/blob/master/pkg/types/aws/defaults/platform.go#L58-L61
[2] https://aws.amazon.com/about-aws/global-infrastructure/localzones/locations/?nc=sn&loc=3

**Comment by r4f4** [comment]
> > ERROR failed to fetch Master Machines: ....compute[1].platform.aws.zones: Invalid value: "us-east-1-dfw-2a": zone group is not opted-in: us-east-1-dfw-2]
> 
> Hi @r4f4 , did you tested `arm64/arm64` in a Local Zone zone that is enabled (opted-in)?

I did not. I never did a local zone install.

> Considering the limitation of supported types[1], versus the offerings[2] of those types in AWS Local Zones, I am unsure if any of those options are valid:
> 
>     * 1/ disable day-0 edge pool when deploying on ARM64, instructing the user to day-2. (no network automation by installer); or
> 
>     * 2/ set the replicas==0 in the edge pool when edge pool is set to `arm64`. Installer will automate the network for edge zones, but MAPI may not fail to create instance in mostly edge zones that does not support any of [1], set on machineset manifest; or

If the Installer fails during validation, can't we just document this as a known issue? Adding further restrictions to the Installer means we need to remove those restrictions when AWS expands their arm64 offerings in local zones in the future.

>     * 3/ support multi-arch compute pools by setting the respective arch for each pool

You mean mixing arches in the compute pools? That's not currently supported by the Installer and it'll involve further work to select the correct AMI. That's why I'm adding the mixed arch validation in this PR.

**Comment by sadasu** [comment]
LGTM

Will let @mtulio add the label.

**Comment by mtulio** [comment]
> LGTM
> 
> Will let @mtulio add the label.

/lgtm

**Comment by mtulio** [comment]
> > * 1/ disable day-0 edge pool when deploying on ARM64, instructing the user to day-2. (no network automation by installer); or
> > 
> > * 2/ set the replicas==0 in the edge pool when edge pool is set to `arm64`. Installer will automate the network for edge zones, but MAPI may not fail to create instance in mostly edge zones that does not support any of [1], set on machineset manifest; or
> > ```
> 
> If the Installer fails during validation, can't we just document this as a known issue? Adding further restrictions to the Installer means we need to remove those restrictions when AWS expands their arm64 offerings in local zones in the future.

Yes, mostly documentation. Specially the AWS is not offering types we are supporting at this moment in almost all edge zones.

> > ```
> > * 3/ support multi-arch compute pools by setting the respective arch for each pool
> > ```
> 
> You mean mixing arches in the compute pools? That's not currently supported by the Installer and it'll involve further work to select the correct AMI. That's why I'm adding the mixed arch validation in this PR.

Yes, as a follow up work as it is "possible".

**Pull request merged**
