### PR TITLE
MULTIARCH-4814: ic: add release arch validation for multi-arch clusters

### PR DESCRIPTION
**Pull request by r4f4**
If a multi-arch cluster is configured, check that the release payload is multi arch or return an error otherwise.

### CODE REVIEW

**Comment by r4f4** [comment]
I tested locally the following scenarios:
* controlPlane and compute same arch, single payload with OVERRIDE:
```
[root@1f86111bf7fb c]# ./openshift-install create manifests
WARNING Found override for release image (quay.io/openshift-release-dev/ocp-release:4.16.2-x86_64). Release Image Architecture is unknown
INFO Credentials loaded from environment variable "GOOGLE_APPLICATION_CREDENTIALS", file "/run/secrets/gcp_credentials"
WARNING Length of cluster name "rdossant-installer-07231613" is 27 which is greater than the max 21 allowed. The name will be truncated to "rdossant-installer-07"
INFO Consuming Install Config from target directory
INFO Manifests created in: manifests and openshift
```
* controlPlane and compute same arch, multi payload with OVERRIDE:
```
[root@1bc35c91a0f1 c]# ./openshift-install create manifests
WARNING Found override for release image (quay.io/openshift-release-dev/ocp-release-nightly@sha256:e73f99dc6117f8bb67f36c955db1b6b95119b3dc225906993863aef82e19b6a6). Release Image Architecture is unknown
INFO Credentials loaded from environment variable "GOOGLE_APPLICATION_CREDENTIALS", file "/run/secrets/gcp_credentials"
WARNING Length of cluster name "rdossant-installer-07231619" is 27 which is greater than the max 21 allowed. The name will be truncated to "rdossant-installer-07"
INFO Consuming Install Config from target directory
INFO Manifests created in: manifests and openshift
```
* controlPlane and compute different arches, single payload with OVERRIDE:
```
[root@30c5a6eb1d33 c]# ./openshift-install create manifests
WARNING Found override for release image (quay.io/openshift-release-dev/ocp-release:4.16.2-x86_64). Release Image Architecture is unknown
WARNING Could not determine release architecture for multi arch cluster configuration. Make sure the release is a multi architecture payload.
INFO Credentials loaded from environment variable "GOOGLE_APPLICATION_CREDENTIALS", file "/run/secrets/gcp_credentials"
WARNING Length of cluster name "rdossant-installer-07231605" is 27 which is greater than the max 21 allowed. The name will be truncated to "rdossant-installer-07"
INFO Consuming Install Config from target directory
INFO Manifests created in: manifests and openshift
```
* controlPlane and compute different arches, multi payload with OVERRIDE:
```
[root@50b2207faf54 c]# ./openshift-install create manifests
WARNING Found override for release image (quay.io/openshift-release-dev/ocp-release-nightly@sha256:e73f99dc6117f8bb67f36c955db1b6b95119b3dc225906993863aef82e19b6a6). Release Image Architecture is unknown
WARNING Could not determine release architecture for multi arch cluster configuration. Make sure the release is a multi architecture payload.
INFO Credentials loaded from environment variable "GOOGLE_APPLICATION_CREDENTIALS", file "/run/secrets/gcp_credentials"
WARNING Length of cluster name "rdossant-installer-07231620" is 27 which is greater than the max 21 allowed. The name will be truncated to "rdossant-installer-07"
INFO Consuming Install Config from target directory
INFO Manifests created in: manifests and openshift
```

**Comment by r4f4** [comment]
Unfortunately I cannot validate the cases when we don't set `RELEASE_IMAGE_OVERRIDE` unless I manually build a custom release payload (cluster-bot doesn't support multi-arch release payloads).

**Review by barbacbd — COMMENTED** [review]
/approve

**Pull request merged**
