### PR TITLE
Bug 1972524: baremetal: Ensure ipv6 bootstrap VM client-id is predictable

### PR DESCRIPTION
**Pull request by hardys**
In #4052 we added interfaces to control the MAC addresses for the
NICs in the bootstrap VM, so that in environments where DHCP pools
are not allowed, a static reservation can be made.

Unfortunately that doesn't work in ipv6 environments currently,
because NetworkManager needs a specific configuration similar to
that applied via the MCO[1] for cluster hosts to ensure the
generated client-ID is derived from the MAC and predictable.

[1] https://github.com/openshift/machine-config-operator/blob/master/templates/common/on-prem/files/NetworkManager-onprem.conf.yaml

### CODE REVIEW

**Comment by hardys** [comment]
I tested this and we can now see if you set e.g `externalMACAddress: "00:51:ff:2b:0d:5e"` that the client-ID is derived from the MAC like the cluster hosts:

``` 
Expiry Time           MAC address         Protocol   IP address                    Hostname   Client ID or DUID
------------------------------------------------------------------------------------------------------------------------------------------------------
 2021-07-28 14:29:14   00:51:ff:2b:0d:45   ipv6       fd2e:6f44:5dd8:c956::14/120   master-0   00:03:00:01:00:51:ff:2b:0d:45
 2021-07-28 14:29:25   00:51:ff:2b:0d:49   ipv6       fd2e:6f44:5dd8:c956::15/120   master-1   00:03:00:01:00:51:ff:2b:0d:49
 2021-07-28 14:29:39   00:51:ff:2b:0d:4d   ipv6       fd2e:6f44:5dd8:c956::16/120   master-2   00:03:00:01:00:51:ff:2b:0d:4d
 2021-07-28 14:13:08   00:51:ff:2b:0d:5e   ipv6       fd2e:6f44:5dd8:c956::3c/120   -          00:03:00:01:00:51:ff:2b:0d:5e
```

**Comment by hardys** [comment]
/cc @stbenjam @yrobla 

I also added a commit to clarify the install-config docs, since we currently say they control the bridge MAC which isn't strictly accurate.

**Comment by hardys** [comment]
Note we should ensure e2e-metal-ipi-ovn-ipv6 passes before merging this

**Review by kirankt — APPROVED** [review]
/lgtm

**Comment by stbenjam** [comment]
/approve
/hold

Feel free to release the hold when metal IPv6 passes

**Comment by hardys** [comment]
Looks like we hit an issue which will be fixed via https://github.com/openshift/cluster-kube-apiserver-operator/pull/1202 - probably best to hold off retesting until that lands

**Pull request merged**
