### PR TITLE
AGENT-318: Merge agent-based installer

### PR DESCRIPTION
**Pull request by zaneb**
Merge the `agent-installer` branch containing the agent-based installer implementation to master so that it will be part of the 4.12 installer.

### CODE REVIEW

**Comment by jhixson74** [comment]
/cc @patrickdillon 

I think this is in good shape to merge, however I'd like to see what patrick thinks

**Comment by zaneb** [comment]
I had to update because a change (#5798) merged on master that renames fields in the installConfig.

**Pull request merged**
