### PR TITLE
[vsphere] cleanup unused types and constants after platform spec refactor

### PR DESCRIPTION
**Pull request by rvanderp3**
cleanup unused types and constants left behind after the platform spec refactor.

### CODE REVIEW

**Comment by sadasu** [comment]
@rvanderp3 does this still need to be on hold?

**Comment by rvanderp3** [comment]
@sadasu thanks for the nudge on this.  no, it does not.  tests lgtm.

/hold cancel

**Review by sadasu — APPROVED** [review]
/approve

**Comment by rvanderp3** [comment]
after discussion with @sadasu , overriding failing tests and fails are not related to change 
/override e2e-vsphere-ovn
/override e2e-vsphere-zones
/override okd-e2e-gcp-ovn-upgrade

**Comment by sadasu** [comment]
/override ci/prow/e2e-vsphere-ovn
Failures in CI are known and unrelated to this change.

**Pull request merged**
