### PR TITLE
AGENT-271: Generate kubeadmin-password with ISO 

### PR DESCRIPTION
**Pull request by zaneb**

### CODE REVIEW

**Review by rwsu — COMMENTED** [review]
dev-scripts didn't print out the kubeadmin password. Running install-complete outside of dev-scripts did print out the kubeadmin password. Was able to log into the OpenShift console using it.

Minor nit with the comment in password.go.

/lgtm

**Review by rwsu — COMMENTED** [review]
/lgtm

**Comment by zaneb** [comment]
We need https://github.com/openshift/assisted-service/pull/4443 or something else that allows the assisted-service to cope.

**Comment by zaneb** [comment]
Tested with a cluster-bot build that combines this PR and https://github.com/openshift/assisted-service/pull/4443, and it works and allows login using the generated password.

**Comment by zaneb** [comment]
Agent test is now passing with just this PR.
/retest-required

**Pull request merged**
