### PR TITLE
CORS-3003: [ibmcloud] add key-protect plugin in ibmcloud cli

### PR DESCRIPTION
**Pull request by MayXuQQ**
[CORS-3003](https://issues.redhat.com//browse/CORS-3003) CI implementation: Review and support the work from IBM to enable BYOK in OpenShift on IBM Cloud VPC

### CODE REVIEW

**Review by r4f4 — COMMENTED** [review]
/approve

**Comment by jianlinliu** [comment]
> tide Pending — Not mergeable. Needs jira/valid-reference labels.

I think you need a jira issue to associate with this PR.

**Comment by r4f4** [comment]
> > tide Pending — Not mergeable. Needs jira/valid-reference labels.
> 
> I think you need a jira issue to associate with this PR.

Will this be backported? If not, we don't need a Jira.

**Comment by r4f4** [comment]
/override ci/prow/e2e-azure-ovn-upi ci/prow/e2e-gcp-ovn-upi ci/prow/altinfra-e2e-aws-ovn-upi
e2e test failures unrelated to PR

/override ci/prow/e2e-vsphere-upi-zones
Job looks broken with invalid terraform arguments

**Comment by r4f4** [comment]
/override ci/prow/e2e-aws-ovn-upi
e2e failures unrelated to PR changes.

**Pull request merged**
