### PR TITLE
OCPBUGS-32042: fix usage of addtionalTrustBundle field

### PR DESCRIPTION
**Pull request by andfasano**
This patch fixes the usage of the registry CA bundle when mounted for the assisted-service and the agent-installer-client

### CODE REVIEW

**Review by rwsu — APPROVED** [review]
/approve

I verified this PR fixed the issue where the additionalTrustBundle in install-config.yaml generated by Assisted Service would contain all certificates on the OS image whereas it should only contain the mirror's certificate, the additionalTrustBundle specified in the agent's version of the install-config or infraenv.

The PR fixes the issue for clusters that will be deployed in the future and does not fix existing clusters already deployed where they may contain an over populated additionalTrustBundle.

**Comment by andfasano** [comment]
/hold

As per a previous discussion with @zaneb it could be maybe better to revert https://github.com/openshift/installer/pull/6098/commits/15db1cbb0816e767a0ca98076613ced6d04ff6fd

**Comment by rwsu** [comment]
> /hold
> 
> As per a previous discussion with @zaneb it could be maybe better to revert [15db1cb](https://github.com/openshift/installer/commit/15db1cbb0816e767a0ca98076613ced6d04ff6fd)

I think reverting  [15db1cb](https://github.com/openshift/installer/commit/15db1cbb0816e767a0ca98076613ced6d04ff6fd) would end up reading the certificate from the wrong path `/etc/assisted/mirror/ca-bundle.crt`. 

This PR removes this mount `-v /etc/pki/ca-trust:/etc/pki/ca-trust:z` which is what prevents reading all of the certificates on the system and it has the correct path to the certificate identified by additionalTrustBundle, `/etc/pki/ca-trust/source/anchors/domain.crt`.

**Comment by zaneb** [comment]
I think what we want to do is:

- When there is [a mirror registry configured](https://github.com/openshift/assisted-service/blob/master/pkg/mirrorregistries/generator.go#L38-L39): bind mount `/etc/pki/ca-trust/source/anchors/domain.crt` from the host at `/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem` in the container
- When there is no mirror registry configured: bind mount `/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem` from the host at `/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem` in the container

That would give the best coverage of all of the cases:

1. No mirror registry or additional trust bundle (connected deployment): use CoreOS root of trust, assisted-service will not mess with additionalTrustBundle
2. Mirror registry but no additional trust bundle (mirror registry cert signed by PKI CA): use CoreOS root of trust, assisted-service will dump garbage in additionalTrustBundle but there's nothing we can do from our side (ZTP installs likely have the same problem, assuming there is a default `/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem` in the container base image)
3. No mirror registry, but additionalTrustBundle present (MitM proxy in front of public registry): use user-supplied CA, assisted will not mess with additionalTrustBundle, we'll pass additionalTrustBundle through InfraEnv ourselves
4. Mirror registry with additionalTrustBundle present (normal disconnected deployment): use user-supplied CA, assisted will automatically ensure it gets passed to cluster, resulting in 2 copies but no extra garbage

**Comment by zaneb** [comment]
Correction: When there is [a mirror registry configured](https://github.com/openshift/assisted-service/blob/master/pkg/mirrorregistries/generator.go#L38-L39) **and** there is an additionalTrustBundle CA (case 4 above), mount `/etc/pki/ca-trust/source/anchors/domain.crt`. Otherwise mount `/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem`.

**Comment by andfasano** [comment]
/hold cancel

PR updated to reflect the latest discussed scenarios

**Pull request merged**
