### PR TITLE
Bug 1870082: Use index in MachineSet names for Openstack IPI 

### LINKED ISSUE #4069: OpenStack IPI install fails during bootstrap due to availability zone name
# Version

```
# ./openshift-install version
./openshift-install 4.6.0-0.nightly-ppc64le-2020-08-18-034628
built from commit c5495ccf4b1b784f10d073f1e7aaa12189be051d
release image quay.io/openshift-release-dev/ocp-release-nightly@sha256:2b016d9d663693551c4958d27e3613dcfb7f8691e58acab3c474538340be8134
```

# Platform:
openstack IPI

# What happened?

Bootkube process loops endlessly to create the worker machineset due to the availability zone name having uppercase letters.

```
Aug 19 09:57:13 yus-pt67t-bootstrap bootkube.sh[2565]: [#12247] failed to create some manifests:
Aug 19 09:57:13 yus-pt67t-bootstrap bootkube.sh[2565]: "99_openshift-cluster-api_worker-machineset-0.yaml": failed to create machinesets.v1beta1.machine.openshift.io/yus-pt67t-worker-PowerKVM -n openshift-machine-api: MachineSet.machine.openshift.io "yus-pt67t-worker-PowerKVM" is invalid: metadata.name: Invalid value: "yus-pt67t-worker-PowerKVM": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

# What you expected to happen?

Worker machines should get created without any error related to the metadata name.

# How to reproduce it (as minimally and precisely as possible)?

1. Use availability zone name in install-config having at least one capital letter.
2. Run the create cluster command.

# Anything else we need to know?

This is on top of https://github.com/openshift/installer/pull/4000

# References

https://github.com/openshift/installer/pull/4000

Need to use lowercase name in machineset.

### PR DESCRIPTION
**Pull request by yussufsh**
Fixes #4069

Signed-off-by: Yussuf Shaikh <yussuf@us.ibm.com>

### CODE REVIEW

**Comment by yussufsh** [comment]
I have problems accessing my Bugzilla account hence created #4069 with details.

**Comment by pierreprinetti** [comment]
@yussufsh Thank you for the patch!

/retitle Bug 1870082: Always convert AZ to lowercase in MachineSet name
/label platform/openstack
/approve
/hold

@mandre 
Do you happen to know if OpenStack availability zones case-sensitive (and thus could cause collisions in the MachineSet names)?

**Comment by mandre** [comment]
Since the availability zone name ends up in the machine name, we need to ensure that it contains only alphanumeric characters, `-` or `.`. We'll need to strip or convert invalid characters in the AZ names to `-`, or possibly add a validation so that we can fail early when the AZ names include invalid chars. 

> Do you happen to know if OpenStack availability zones are case-sensitive (and thus could cause collisions in the MachineSet names)?

I do not know, but the fact that Yussuf was able to create an AZ with name `PowerKVM` makes me think it's case sensitive. I'll double check with nova people.

**Review by Fedosin — COMMENTED** [review]
Based on the documentation az names can contain everything except ":". https://docs.openstack.org/nova/latest/admin/availability-zones.html
If so, we need to get rid of special characters too. I created a go playground with an example how I would do it: https://play.golang.org/p/XqlHfz6IsE5

**Comment by yussufsh** [comment]
Frankly I am not sure what is the relevance of appending the AZ name to the machineset. If it is just a matter of uniqueness then I think we could use the index (idx) instead of AZ name.

Also, if I am not wrong the filename would be in same format.

Just a suggestion to save us a lot of thinking.

**Comment by pierreprinetti** [comment]
If we operate transformations to the AZ name (and if we want to keep composing the MachineSet name out of the AZ name), we might need to add random characters to the MachineSet name to prevent collisions.

**Comment by yussufsh** [comment]
I wonder if this is not a problem with other cloud providers supporting AZ.

**Comment by pierreprinetti** [comment]
>I wonder if this is not a problem with other cloud providers supporting AZ.

It appears that [AWS](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html#concepts-availability-zones) and [GCP](https://cloud.google.com/compute/docs/regions-zones/) have URL-compatible zone names, and [they compose](https://github.com/openshift/installer/blob/bc4722257643dd0d643564c686ecd5ea421f947b/pkg/asset/machines/aws/machinesets.go#L55) the MachineSet name out of those. Sensible variability in AZ names is probably a problem of on-premise clouds.

>Frankly I am not sure what is the relevance of appending the AZ name to the machineset. If it is just a matter of uniqueness then I think we could use the index (idx) instead of AZ name.

I like this. @mandre @Fedosin what do you think?

**Comment by yussufsh** [comment]
> @yussufsh
> We discussed this; having the index in the name instead of the AZ name sounds like a plan.
> 
> Do you want to amend the PR and implement your idea?

Sure about that.

**Comment by pierreprinetti** [comment]
/lgtm
/hold cancel

Thank you! :tada:

**Pull request merged**
