### PR TITLE
TRT-1674: 4.17 capi revert 1

### PR DESCRIPTION
**Pull request by neisw**
Reverts both https://github.com/openshift/installer/pull/8254 and https://github.com/openshift/installer/pull/8416

tracked by https://issues.redhat.com/browse/TRT-1674

Per [OpenShift policy](https://github.com/openshift/enhancements/blob/master/enhancements/release/improving-ci-signal.md#quick-revert), we are reverting this breaking change to get CI and/or nightly payloads flowing again.

Multiple payload failures due to bootstrap cleanup failures

To unrevert this, revert this PR, and layer an additional separate commit on top that addresses the problem. Before merging the unrevert, please run these jobs on the PR and check the result of these jobs to confirm the fix has corrected the problem:

/payload-aggregate periodic-ci-openshift-release-master-ci-4.17-e2e-aws-ovn 10

CC: @patrickdillon

### CODE REVIEW

**Comment by neisw** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.17-e2e-aws-ovn 10

**Comment by stbenjam** [comment]
This shows b2541d  (the commit prior to the CAPI stuff) and forrest's PR are identical:
```
$ git diff b2541d223a864f660ea82e98d9f0ba2636df7bd1 forrest/trt-1674-4.17-capi-revert-1
$
```

We're returning to a previously tested HEAD of the repo. 

/skip
/label acknowledge-critical-fixes-only
/label approved
/lgtm

**Comment by neisw** [comment]
Closing to try to get it unstuck

**Comment by stbenjam** [comment]
/close

Going to reopen to unstick tide/prow

**Pull request merged**
