### PR TITLE
images: UPI: update gcloud install on rhel8 container

### PR DESCRIPTION
**Pull request by r4f4**
Changes based on the latest instructions from
https://cloud.google.com/sdk/docs/install#rpm and
https://cloud.google.com/sdk/crypto

### CODE REVIEW

**Review by jstuever — COMMENTED** [review]
/approve

**Comment by sadasu** [comment]
/skip
Failing tests have nothing in common with the change.

**Comment by r4f4** [comment]
I tested building this image locally, since `Dockerfile.ci.upi.rhel8` doesn't seem to be used anywhere in CI:
```
$: podman build -f images/installer/Dockerfile.upi.ci.rhel8 -t upi-installer-rhel8 .
[...]
[3/3] COMMIT upi-installer-rhel8
--> bb686c5e1c6
Successfully tagged localhost/upi-installer-rhel8:latest
bb686c5e1c6af5f71bd3d63fbb6df4099fa39f5ce88fd68e8039ef0328f8807c

$: podman run --rm -it upi-installer-rhel8:latest /bin/bash
bash-4.4$ gcloud version
Google Cloud SDK 403.0.0
alpha 2022.09.20
beta 2022.09.20
bq 2.0.77
bundled-python3-unix 3.9.12
core 2022.09.20
gcloud-crc32c 1.0.0
gsutil 5.13
```

**Comment by r4f4** [comment]
/override ci/prow/e2e-openstack
install succeded, failed in some e2e tests. No need to keep retesting.

**Comment by r4f4** [comment]
/override ci/prow/okd-e2e-aws-ovn
install succeeded, failed in some e2e tests. No need to keep retesting.

**Comment by r4f4** [comment]
/override ci/prow/okd-e2e-aws-upgrade
stableinitial install succeeded, timed out after 4h. No need to retest.

**Comment by r4f4** [comment]
/override ci/prow/e2e-azure-ovn-upi
Passed the install phase, just some e2e failures. No need to retest.

**Comment by r4f4** [comment]
/override ci/prow/e2e-gcp-ovn-upi
Passed the install phase, just some e2e failures. No need to retest.

**Comment by r4f4** [comment]
/override ci/prow/e2e-aws-ovn ci/prow/e2e-aws-ovn-upi ci/prow/e2e-azure-ovn-upi ci/prow/e2e-gcp-ovn-upi

**Pull request merged**
