### PR TITLE
bug 1805251: Master azure terraform address prefixes

### PR DESCRIPTION
**Pull request by jhixson74**
When a subnet uses address_prefixes, address_prefix is null in the virtual network resource. Add address_prefixes to virtual network resource and allow null for address_prefix. Don't assume IPv4 for private_ip_address on load balancer resource.

https://bugzilla.redhat.com/show_bug.cgi?id=1808973

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
@jhixson74 this PR fixes https://bugzilla.redhat.com/show_bug.cgi?id=1805936 and https://bugzilla.redhat.com/show_bug.cgi?id=1805251 correct?

**Comment by abhinavdahiya** [comment]
> /msg @clusterbot launch opeshift/installer#3247 azure,ipv6

https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-launch-azure/144

seems to have done well in terms of going past the bootstrap complete.

**Comment by jhixson74** [comment]
> @jhixson74 this PR fixes https://bugzilla.redhat.com/show_bug.cgi?id=1805936 and https://bugzilla.redhat.com/show_bug.cgi?id=1805251 correct?

Correct.

**Pull request merged**
