### PR TITLE
pkg/asset/machines/master.go: update the disk size for azure to 1024

### PR DESCRIPTION
**Pull request by abhinavdahiya**

### CODE REVIEW

**Comment by yuqi-zhang** [comment]
/test e2e-azure

Even on the failed case there seems to be less overloads, might be promising

**Comment by hexfusion** [comment]
Numbers seem better but even from a passing test[1] I am seeing logs like below which are quite frightening. 

```
>2019-09-13 21:18:24.519934 W | etcdserver: read-only range request "key:\"/kubernetes.io/network.openshift.io/netnamespaces\" range_end:\"/kubernetes.io/network.openshift.io/netnamespacet\" count_only:true " with result "error:etcdserver: request timed out" took too long (9.3928289s) to execute
2019-09-13 21:18:24.520042 W | etcdserver: read-only range request "key:\"/kubernetes.io/operator.openshift.io/kubeapiservers\" range_end:\"/kubernetes.io/operator.openshift.io/kubeapiservert\" count_only:true " with result "error:etcdserver: request timed out" took too long (9.9545263s) to execute
2019-09-13 21:18:24.520147 W | etcdserver: read-only range request "key:\"/kubernetes.io/rolebindings\" range_end:\"/kubernetes.io/rolebindingt\" count_only:true " with result "error:etcdserver: request timed out" took too long (10.2173313s) to execute
2019-09-13 21:18:24.520243 W | etcdserver: read-only range request "key:\"/kubernetes.io/secrets/openshift-machine-api/machine-api-operator-token-8rcbc\" " with result "error:etcdserver: request timed out" took too long (10.9969343s) to execute
2019-09-13 21:18:24.520363 W | etcdserver: read-only range request "key:\"/kubernetes.io/autoscaling.openshift.io/clusterautoscalers\" range_end:\"/kubernetes.io/autoscaling.openshift.io/clusterautoscalert\" count_only:true " with result "error:etcdserver: request timed out" took too long (11.9090701s) to execute
2019-09-13 21:18:24.520442 W | etcdserver: read-only range request "key:\"/kubernetes.io/serviceaccounts/openshift-kube-scheduler/openshift-kube-scheduler-sa\" " with result "error:etcdserver: request timed out" took too long (13.9838737s) to execute
```
[1]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_installer/2352/pull-ci-openshift-installer-master-e2e-azure/163

I plan on digging more into this.

**Comment by abhinavdahiya** [comment]
/hold

@hexfusion is looking into performance issue related to Azure, we are using this PR to test options.

Sorry, forgot to mention it..

**Pull request closed without merging**
