### PR TITLE
OCPBUGS-10585: rhcos: Update to 413.92.202303190222-0

### PR DESCRIPTION
**Pull request by cgwalters**
This is to fix OCPBUGS-10585

### CODE REVIEW

**Comment by mike-nguyen** [comment]
We'll need to run the cloud-replicate job if we want the cloud images replicated to all the regions

**Comment by zaneb** [comment]
> Note: It'd be cleaner to land a 4.14 bump first, but we're still in the process of branching and I'd like to just consolidate things there for master/4.14 so we both fix this bug and correctly switch to a 4.14 version, etc.

The Jira bot will complain about that, but I can manually set the labels if necessary, given that there is no danger of failing bumping the version at any time during 4.14 development.
I would note that CI for the agent installer is broken right now on 4.14 though, so we'd prefer not to delay too long.

**Comment by patrickdillon** [comment]
/retest

Most cloud platforms were borked due to the dns migration issues, which should be fixed now.

/approve
/label backport-risk-assessed

**Comment by cgwalters** [comment]
I'm tentatively planning to take a look at this at the same time as we do a final bootimage respin, which will happen sometime soon.

**Comment by mike-nguyen** [comment]
The cloud replication job is pending. I will update here when it is completed (usually about one more hour)

**Comment by mike-nguyen** [comment]
`cloud-replication` job completed.  I don't think I can push to this PR so I have a branch in my repo with the changes if needed: https://github.com/mike-nguyen/installer/tree/413_92_bib

**Comment by cgwalters** [comment]
I pulled in your changes, and also rebased :surfer: for good measure.

**Pull request merged**
