### PR TITLE
CORS-3607: Azure CAPI Installs within Tech Preview featureset

### PR DESCRIPTION
**Pull request by sadasu**

### CODE REVIEW

**Comment by sadasu** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.17-e2e-azure-ovn-techpreview periodic-ci-openshift-release-master-ci-4.17-e2e-azure-ovn-techpreview-serial

**Comment by r4f4** [comment]
/hold
Until the o/api https://github.com/openshift/api/pull/1967 merges and the ref is updated in this PR.

**Review by r4f4 — COMMENTED** [review]
/approve

**Pull request merged**
