### PR TITLE
Bug 1839268: pkg/destroy/gcp: ensure cluster service accounts and policy bindings are removed

### PR DESCRIPTION
**Pull request by abhinavdahiya**
service account names or the name in it's email has max length of 30 and therefore using it for identifying makes it difficult as the creator will probably have to truncate the infra-id prefix to fit as the name.
service account's displayName has 100 char limit and therefore using that ensure we can identity the service accounts much better.
The change checks both the email, and displayName to figure out if cluster id is prefixed.

secondly project iam policy only have service account email, and therefore to clean up members correctly, the change now lists the service accounts in the project for the cluster and
then uses that to check if a member of the policy maps to service account of the cluster.

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
@jstuever ping for another review.

if the destroy cleans up all the resources in CI run, i will add lgtm as this is causing leak in CI project.

**Comment by abhinavdahiya** [comment]
> https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_installer/3646/pull-ci-openshift-installer-master-e2e-gcp/354/artifacts/e2e-gcp/ipi-deprovision-deprovision/.openshift_install.log

```
time="2020-05-22T23:56:07Z" level=debug msg="Listing service accounts"
time="2020-05-22T23:56:16Z" level=debug msg="Found service account: projects/openshift-gce-devel-ci/serviceAccounts/ci-op-h16crsnb-15937-dch4s-w@openshift-gce-devel-ci.iam.gserviceaccount.com"
time="2020-05-22T23:56:16Z" level=debug msg="Found service account: projects/openshift-gce-devel-ci/serviceAccounts/ci-op-h16crs-openshift-i-54x2t@openshift-gce-devel-ci.iam.gserviceaccount.com"
time="2020-05-22T23:56:16Z" level=debug msg="Found service account: projects/openshift-gce-devel-ci/serviceAccounts/ci-op-h16crs-openshift-i-zdpxh@openshift-gce-devel-ci.iam.gserviceaccount.com"
time="2020-05-22T23:56:16Z" level=debug msg="Found service account: projects/openshift-gce-devel-ci/serviceAccounts/ci-op-h16crsnb-15937-dch4s-m@openshift-gce-devel-ci.iam.gserviceaccount.com"
time="2020-05-22T23:56:16Z" level=debug msg="Found service account: projects/openshift-gce-devel-ci/serviceAccounts/ci-op-h16crs-openshift-m-h8bps@openshift-gce-devel-ci.iam.gserviceaccount.com"
time="2020-05-22T23:56:16Z" level=debug msg="Deleting service account projects/openshift-gce-devel-ci/serviceAccounts/ci-op-h16crsnb-15937-dch4s-m@openshift-gce-devel-ci.iam.gserviceaccount.com"
time="2020-05-22T23:56:16Z" level=info msg="Deleted service account projects/openshift-gce-devel-ci/serviceAccounts/ci-op-h16crsnb-15937-dch4s-m@openshift-gce-devel-ci.iam.gserviceaccount.com"
time="2020-05-22T23:56:16Z" level=debug msg="Deleting service account projects/openshift-gce-devel-ci/serviceAccounts/ci-op-h16crs-openshift-m-h8bps@openshift-gce-devel-ci.iam.gserviceaccount.com"
time="2020-05-22T23:56:17Z" level=info msg="Deleted service account projects/openshift-gce-devel-ci/serviceAccounts/ci-op-h16crs-openshift-m-h8bps@openshift-gce-devel-ci.iam.gserviceaccount.com"
time="2020-05-22T23:56:17Z" level=debug msg="Deleting service account projects/openshift-gce-devel-ci/serviceAccounts/ci-op-h16crsnb-15937-dch4s-w@openshift-gce-devel-ci.iam.gserviceaccount.com"
time="2020-05-22T23:56:17Z" level=info msg="Deleted service account projects/openshift-gce-devel-ci/serviceAccounts/ci-op-h16crsnb-15937-dch4s-w@openshift-gce-devel-ci.iam.gserviceaccount.com"
time="2020-05-22T23:56:17Z" level=debug msg="Deleting service account projects/openshift-gce-devel-ci/serviceAccounts/ci-op-h16crs-openshift-i-54x2t@openshift-gce-devel-ci.iam.gserviceaccount.com"
time="2020-05-22T23:56:18Z" level=info msg="Deleted service account projects/openshift-gce-devel-ci/serviceAccounts/ci-op-h16crs-openshift-i-54x2t@openshift-gce-devel-ci.iam.gserviceaccount.com"
time="2020-05-22T23:56:18Z" level=debug msg="Deleting service account projects/openshift-gce-devel-ci/serviceAccounts/ci-op-h16crs-openshift-i-zdpxh@openshift-gce-devel-ci.iam.gserviceaccount.com"
time="2020-05-22T23:56:18Z" level=info msg="Deleted service account projects/openshift-gce-devel-ci/serviceAccounts/ci-op-h16crs-openshift-i-zdpxh@openshift-gce-devel-ci.iam.gserviceaccount.com"
time="2020-05-22T23:56:18Z" level=debug msg="Fetching project IAM policy"
time="2020-05-22T23:56:18Z" level=debug msg="IAM: removing serviceAccount:ci-op-h16crsnb-15937-dch4s-m@openshift-gce-devel-ci.iam.gserviceaccount.com from role roles/compute.instanceAdmin"
time="2020-05-22T23:56:18Z" level=debug msg="IAM: removing serviceAccount:ci-op-h16crs-openshift-m-h8bps@openshift-gce-devel-ci.iam.gserviceaccount.com from role roles/compute.instanceAdmin.v1"
time="2020-05-22T23:56:18Z" level=debug msg="IAM: removing serviceAccount:ci-op-h16crs-openshift-m-h8bps@openshift-gce-devel-ci.iam.gserviceaccount.com from role roles/compute.loadBalancerAdmin"
time="2020-05-22T23:56:18Z" level=debug msg="IAM: removing serviceAccount:ci-op-h16crsnb-15937-dch4s-m@openshift-gce-devel-ci.iam.gserviceaccount.com from role roles/compute.networkAdmin"
time="2020-05-22T23:56:18Z" level=debug msg="IAM: removing serviceAccount:ci-op-h16crsnb-15937-dch4s-m@openshift-gce-devel-ci.iam.gserviceaccount.com from role roles/compute.securityAdmin"
time="2020-05-22T23:56:18Z" level=debug msg="IAM: removing serviceAccount:ci-op-h16crsnb-15937-dch4s-w@openshift-gce-devel-ci.iam.gserviceaccount.com from role roles/compute.viewer"
time="2020-05-22T23:56:18Z" level=debug msg="IAM: removing serviceAccount:ci-op-h16crs-openshift-i-zdpxh@openshift-gce-devel-ci.iam.gserviceaccount.com from role roles/dns.admin"
time="2020-05-22T23:56:18Z" level=debug msg="IAM: removing serviceAccount:ci-op-h16crs-openshift-i-54x2t@openshift-gce-devel-ci.iam.gserviceaccount.com from role roles/iam.serviceAccountUser"
time="2020-05-22T23:56:18Z" level=debug msg="IAM: removing serviceAccount:ci-op-h16crs-openshift-m-h8bps@openshift-gce-devel-ci.iam.gserviceaccount.com from role roles/iam.serviceAccountUser"
time="2020-05-22T23:56:18Z" level=debug msg="IAM: removing serviceAccount:ci-op-h16crsnb-15937-dch4s-m@openshift-gce-devel-ci.iam.gserviceaccount.com from role roles/iam.serviceAccountUser"
time="2020-05-22T23:56:18Z" level=debug msg="IAM: removing serviceAccount:ci-op-h16crs-openshift-i-54x2t@openshift-gce-devel-ci.iam.gserviceaccount.com from role roles/storage.admin"
time="2020-05-22T23:56:18Z" level=debug msg="IAM: removing serviceAccount:ci-op-h16crsnb-15937-dch4s-m@openshift-gce-devel-ci.iam.gserviceaccount.com from role roles/storage.admin"
time="2020-05-22T23:56:18Z" level=debug msg="IAM: removing serviceAccount:ci-op-h16crsnb-15937-dch4s-w@openshift-gce-devel-ci.iam.gserviceaccount.com from role roles/storage.admin"
time="2020-05-22T23:56:18Z" level=debug msg="Setting project IAM policy"
time="2020-05-22T23:56:19Z" level=debug msg="Policy bindings: 1 items pending"
```

looks like this deletes all the service accounts.

**Comment by sdodson** [comment]
/lgtm
/hold
Clear the hold whenever you're ready

**Comment by abhinavdahiya** [comment]
> https://github.com/openshift/installer/pull/3646#issuecomment-632948202

/hold cancel

**Pull request merged**
