### PR TITLE
terraform: upgrade alicloud provider to v1.158.0

### PR DESCRIPTION
**Pull request by staebler**
When https://github.com/openshift/installer/pull/5507 was merged, the version of the alicloud terraform provider was set to v1.148.0, which is the version in use when the PR was created. However, in the time between creation and merge, https://github.com/openshift/installer/pull/5571 was merged, which upgrade the version to v1.153.0. This change was lost during conflict resolution.

Let's upgrade to the latest version (v1.158.0) of the alicloud terraform provider while we are at it.

### CODE REVIEW

**Comment by staebler** [comment]
/cc @kwoodson 
Would you mind giving this a review, please?

**Comment by kwoodson** [comment]
Testing cluster install.

**Comment by staebler** [comment]
> Testing cluster install.

Thanks. Note that this is restoring the version that is used in 4.10. I am open to upgrading to an even more recent version, too. As of now, that would be v1.160.0.

**Comment by staebler** [comment]
> Unfortunately I'm still seeing this behavior.

Sorry, for the confusion. I did not mean to imply that the upgrade of the terraform provider would fix that problem. I am just trying to rectify the mistaken change in versions from 4.10 to 4.11.

**Comment by kwoodson** [comment]
@staebler I'm supportive of this change. Moving back to the 1.158 sounds good to me. If you want to try moving forward I can test that as well.

**Comment by sadasu** [comment]
/close

Latest version is now 1.182.0. Will upgrade to the latest when we see a need.

**Pull request closed without merging**
