### PR TITLE
baremetal: sync baremetal-operator

### PR DESCRIPTION
**Pull request by dtantsur**
Minor changes were required because of significant code reordering.

### CODE REVIEW

**Comment by dtantsur** [comment]
/retest

It's ironic that the baremetal job is one of the few that passed.

**Comment by dtantsur** [comment]
/recheck

We're improving! (Not sure about the root cause though).

**Comment by dtantsur** [comment]
/retest

... I meant

**Comment by staebler** [comment]
> /recheck
> 
> We're improving! (Not sure about the root cause though).

The failures are flakes not related to your changes. No need to retest.

**Comment by stbenjam** [comment]
It would be helpful if the commit indicated why we were syncing baremetal-operator, based on the branch name I suspect it's related to secure booting, presumably to pull in a new value for bootMode?

**Comment by stbenjam** [comment]
I won't hold things up on my nit above since installer team already approved

/lgtm

**Comment by staebler** [comment]
> It would be helpful if the commit indicated why we were syncing baremetal-operator, based on the branch name I suspect it's related to secure booting, presumably to pull in a new value for bootMode?

/lgtm cancel

That is a good point. Let's improve on the commit message, please.

**Comment by dtantsur** [comment]
@staebler @stbenjam amended the commit.

**Pull request merged**
