### PR TITLE
Calico networking enables IPIP and BPG

### PR DESCRIPTION
**Pull request by tmjd**

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
cluster-networking-operator needs to own managing the infra for new network types.
see https://github.com/openshift/installer/issues/1218

/hold

**Comment by tmjd** [comment]
Also for Calico we want to to disable Source/Destination checks so encapsulation isn't required for all traffic. This can be done in the installer for the masters but it looks like for the clients, as best as I can tell, it will require updating the AWSMachineProviderConfig and the operator that brings up nodes to be able to configure that on the nodes. Any suggestions for disabling those checks are welcome.

**Comment by abhinavdahiya** [comment]
> Also for Calico we want to to disable Source/Destination checks so encapsulation isn't required for all traffic. This can be done in the installer for the masters but it looks like for the clients, as best as I can tell, it will require updating the AWSMachineProviderConfig and the operator that brings up nodes to be able to configure that on the nodes. Any suggestions for disabling those checks are welcome.

That's going to have to be done by the help of machine-config-operator.

**Comment by tmjd** [comment]
@abhinavdahiya is the machine-config-operator responsible for implementing the config of worker nodes as AWSMachineProviderConfig and will it also be updating master nodes too? I thought it looked like there were AWSMachineProviderConfigs created for the masters but the masters are also directly created by the installer through terraform.
Are there some docs that I should be looking at to understand installation and master/worker creation/configuration? Sorry I kind of jumped in the deep end and didn't start with a survey of the available docs.

**Comment by abhinavdahiya** [comment]
Network operator should be handling this.

closing due to inactivity. Please reopen if needed.

/close

**Pull request closed without merging**
