### PR TITLE
Bug 1856467: upi/aws: add m5 instances to allowed list for upi templates

### PR DESCRIPTION
**Pull request by abhinavdahiya**
51f66d63c changed the default for instance to m5 class, but did not update the valid instance types for master
and worker UPI templates and therefore causing the erorr,

```
An error occurred (ValidationError) when calling the CreateStack operation: Parameter 'MasterInstanceType' must be one of AllowedValues
```

### CODE REVIEW

**Comment by wking** [comment]
CC @kalexand-rh , because this will need to be ported to openshift-docs too.

**Comment by abhinavdahiya** [comment]
this does not affect [e2e-aws](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_installer/3947/pull-ci-openshift-installer-master-e2e-aws/1286325391002177536) or e2e-aws-upgrade. and [e2e-aws-upi](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_installer/3947/pull-ci-openshift-installer-master-e2e-aws-upi/1286155225979162624) is already green 

/override ci/prow/e2e-aws

**Pull request merged**
