### PR TITLE
 manifests: add cloudproviderconfig asset 

### PR DESCRIPTION
**Pull request by abhinavdahiya**
This configuration file is used to configure the Kubernetes cloud provider integration
when using the built-in cloud provider integration or the external cloud controller manager.

The configmap containing cloud provider config must be in `openshift-config` namespace as required by openshift/api PR 245 [1]

[1]: https://github.com/openshift/api/blob/master/config/v1/types_infrastructure.go#L28

/cc @staebler @derekwaynecarr 
This should help plumb the vsphere cloud provider config whenever that becomes ready.

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
Hold until @gnufied and I have a chance to sync up this week.

**Comment by gnufied** [comment]
@derekwaynecarr I double and triple check storage bits for vsphere and traditionally in openshift-ansible when we configure vsphere cloudprovider, naturally you specify a datastore too. But - it is not mandatory to have datastore specified in storageclass and storagelclass will simply default to datastore configured in current workspace.

So, in a nutshell - we don't need anything beyond platform being set to `vSphere`. After that, if controller-manager is configured correctly, everything should work as expected.  I am sorry that, my earlier assumption about this was not entirely correct. but like I said - I am 100% certain now that, we aren't going to need anything for configuring default storageclass.

**Comment by sjenning** [comment]
fyi @rphillips

**Comment by sdodson** [comment]
/close
rolled into #1516

**Pull request closed without merging**
