### PR TITLE
OCPBUGS-8540: CVE: bump mongo-go-driver for fix

### PR DESCRIPTION
**Pull request by r4f4**
Specific cstrings input may not be properly validated in the MongoDB Go
Driver when marshalling Go objects into BSON.

### CODE REVIEW

**Review by barbacbd — COMMENTED** [review]
/lgtm

**Comment by r4f4** [comment]
Rebased to fix merge conflicts.

**Comment by r4f4** [comment]
Rebased to fix merge conflicts.

**Review by barbacbd — COMMENTED** [review]
/lgtm

**Comment by r4f4** [comment]
Rebased to fix merge conflicts.

**Pull request merged**
