### PR TITLE
README: change install to create

### PR DESCRIPTION
**Pull request by vadimeisenbergibm**
there is no `install` command, the command is `create`

### CODE REVIEW

**Comment by staebler** [comment]
Please follow the commit message format [guidelines](https://github.com/openshift/installer/blob/master/CONTRIBUTING.md#commit-message-format).

/lgtm cancel

**Comment by vadimeisenbergibm** [comment]
@staebler I have fixed the commit message, thank you.

**Review by staebler — COMMENTED** [review]
/approve
/lgtm
/ok-to-test

**Comment by staebler** [comment]
These changes are only doc changes.

/override ci/prow/e2e-aws-upgrade
/skip

**Pull request merged**
