### PR TITLE
OCPBUGS-13636: new Aws secret regions support

### PR DESCRIPTION
**Pull request by r4f4**
Add support for SC2S region (us-isob-east-1) and new TC2S region (us-iso-west-1).

### CODE REVIEW

**Comment by yunjiang29** [comment]
Hello @r4f4 pre-merge test failed with error `Unsupported Operation`

install logs:
```
10-19 18:15:01.781  level=debug msg=module.iam.aws_iam_role.worker_role[0]: Still creating... [1h2m11s elapsed]
10-19 18:15:03.710  level=error
10-19 18:15:03.710  level=error msg=Error: failed creating IAM Role (yunjiang-57c2s2-fmjqq-worker-role): RequestError: send request failed
10-19 18:15:03.710  level=error msg=caused by: Post "https://iam.us-iso-east-1.c2s.ic.gov/": Service Unavailable
10-19 18:15:03.710  level=error
10-19 18:15:03.710  level=error msg=  with module.iam.aws_iam_role.worker_role[0],
10-19 18:15:03.710  level=error msg=  on iam/main.tf line 13, in resource "aws_iam_role" "worker_role":
10-19 18:15:03.710  level=error msg=  13: resource "aws_iam_role" "worker_role" {
10-19 18:15:03.710  level=error
10-19 18:15:03.710  level=error
10-19 18:15:03.710  level=error msg=Error: failed creating IAM Role (yunjiang-57c2s2-fmjqq-master-role): RequestError: send request failed
10-19 18:15:03.710  level=error msg=caused by: Post "https://iam.us-iso-east-1.c2s.ic.gov/": Service Unavailable
10-19 18:15:03.710  level=error
10-19 18:15:03.710  level=error msg=  with module.masters.aws_iam_role.master_role[0],
10-19 18:15:03.710  level=error msg=  on master/main.tf line 18, in resource "aws_iam_role" "master_role":
10-19 18:15:03.710  level=error msg=  18: resource "aws_iam_role" "master_role" {
10-19 18:15:03.710  level=error
10-19 18:15:03.710  level=error
10-19 18:15:03.710  level=error msg=Error: error creating Route53 Hosted Zone: SerializationError: failed to unmarshal error message
10-19 18:15:03.710  level=error msg=	status code: 400, request id: 
10-19 18:15:03.710  level=error msg=caused by: UnmarshalError: failed to unmarshal error message
10-19 18:15:03.710  level=error msg=	00000000  3c 3f 78 6d 6c 20 76 65  72 73 69 6f 6e 3d 22 31  |<?xml version="1|
10-19 18:15:03.710  level=error msg=00000010  2e 30 22 20 65 6e 63 6f  64 69 6e 67 3d 22 55 54  |.0" encoding="UT|
10-19 18:15:03.710  level=error msg=00000020  46 2d 38 22 20 73 74 61  6e 64 61 6c 6f 6e 65 3d  |F-8" standalone=|
10-19 18:15:03.710  level=error msg=00000030  22 6e 6f 22 3f 3e 3c 52  65 73 70 6f 6e 73 65 3e  |"no"?><Response>|
10-19 18:15:03.710  level=error msg=00000040  3c 45 72 72 6f 72 73 3e  3c 45 72 72 6f 72 3e 3c  |<Errors><Error><|
10-19 18:15:03.710  level=error msg=00000050  43 6f 64 65 3e 55 6e 73  75 70 70 6f 72 74 65 64  |Code>Unsupported|
10-19 18:15:03.710  level=error msg=00000060  4f 70 65 72 61 74 69 6f  6e 3c 2f 43 6f 64 65 3e  |Operation</Code>|
10-19 18:15:03.711  level=error msg=00000070  3c 4d 65 73 73 61 67 65  3e 54 68 65 20 66 75 6e  |<Message>The fun|
10-19 18:15:03.711  level=error msg=00000080  63 74 69 6f 6e 61 6c 69  74 79 20 79 6f 75 20 72  |ctionality you r|
10-19 18:15:03.711  level=error msg=00000090  65 71 75 65 73 74 65 64  20 69 73 20 6e 6f 74 20  |equested is not |
10-19 18:15:03.711  level=error msg=000000a0  61 76 61 69 6c 61 62 6c  65 20 69 6e 20 74 68 69  |available in thi|
10-19 18:15:03.711  level=error msg=000000b0  73 20 72 65 67 69 6f 6e  2e 3c 2f 4d 65 73 73 61  |s region.</Messa|
10-19 18:15:03.711  level=error msg=000000c0  67 65 3e 3c 2f 45 72 72  6f 72 3e 3c 52 65 71 75  |ge></Error><Requ|
10-19 18:15:03.711  level=error msg=000000d0  65 73 74 49 44 3e 63 64  38 31 39 36 33 64 64 37  |estID>cd81963dd7|
10-19 18:15:03.711  level=error msg=000000e0  66 31 34 61 37 62 39 31  38 33 37 61 35 38 38 31  |f14a7b91837a5881|
10-19 18:15:03.711  level=error msg=000000f0  65 32 34 35 32 34 3c 2f  52 65 71 75 65 73 74 49  |e24524</RequestI|
10-19 18:15:03.711  level=error msg=00000100  44 3e 3c 2f 45 72 72 6f  72 73 3e 3c 2f 52 65 73  |D></Errors></Res|
10-19 18:15:03.711  level=error msg=00000110  70 6f 6e 73 65 3e                                 |ponse>|
10-19 18:15:03.711  level=error
10-19 18:15:03.711  level=error msg=caused by: unknown error response tag, {{ Response} []}
10-19 18:15:03.711  level=error
10-19 18:15:03.711  level=error msg=  with module.dns.aws_route53_zone.new_int[0],
10-19 18:15:03.711  level=error msg=  on route53/base.tf line 24, in resource "aws_route53_zone" "new_int":
10-19 18:15:03.711  level=error msg=  24: resource "aws_route53_zone" "new_int" {
10-19 18:15:03.711  level=error
10-19 18:15:03.965  level=error msg=failed to fetch Cluster: failed to generate asset "Cluster": failure applying terraform for "cluster" stage: failed to create cluster: failed to apply Terraform: exit status 1
10-19 18:15:03.965  level=error
10-19 18:15:03.965  level=error msg=Error: failed creating IAM Role (yunjiang-57c2s2-fmjqq-worker-role): RequestError: send request failed
10-19 18:15:03.965  level=error msg=caused by: Post "https://iam.us-iso-east-1.c2s.ic.gov/": Service Unavailable
10-19 18:15:03.965  level=error
10-19 18:15:03.965  level=error msg=  with module.iam.aws_iam_role.worker_role[0],
10-19 18:15:03.966  level=error msg=  on iam/main.tf line 13, in resource "aws_iam_role" "worker_role":
10-19 18:15:03.966  level=error msg=  13: resource "aws_iam_role" "worker_role" {
10-19 18:15:03.966  level=error
10-19 18:15:03.966  level=error
10-19 18:15:03.966  level=error msg=Error: failed creating IAM Role (yunjiang-57c2s2-fmjqq-master-role): RequestError: send request failed
10-19 18:15:03.966  level=error msg=caused by: Post "https://iam.us-iso-east-1.c2s.ic.gov/": Service Unavailable
10-19 18:15:03.966  level=error
10-19 18:15:03.966  level=error msg=  with module.masters.aws_iam_role.master_role[0],
10-19 18:15:03.966  level=error msg=  on master/main.tf line 18, in resource "aws_iam_role" "master_role":
10-19 18:15:03.966  level=error msg=  18: resource "aws_iam_role" "master_role" {
10-19 18:15:03.966  level=error
10-19 18:15:03.966  level=error
10-19 18:15:03.966  level=error msg=Error: error creating Route53 Hosted Zone: SerializationError: failed to unmarshal error message
10-19 18:15:03.966  level=error msg=	status code: 400, request id: 
10-19 18:15:03.966  level=error msg=caused by: UnmarshalError: failed to unmarshal error message
10-19 18:15:03.966  level=error msg=	00000000  3c 3f 78 6d 6c 20 76 65  72 73 69 6f 6e 3d 22 31  |<?xml version="1|
10-19 18:15:03.966  level=error msg=00000010  2e 30 22 20 65 6e 63 6f  64 69 6e 67 3d 22 55 54  |.0" encoding="UT|
10-19 18:15:03.966  level=error msg=00000020  46 2d 38 22 20 73 74 61  6e 64 61 6c 6f 6e 65 3d  |F-8" standalone=|
10-19 18:15:03.966  level=error msg=00000030  22 6e 6f 22 3f 3e 3c 52  65 73 70 6f 6e 73 65 3e  |"no"?><Response>|
10-19 18:15:03.966  level=error msg=00000040  3c 45 72 72 6f 72 73 3e  3c 45 72 72 6f 72 3e 3c  |<Errors><Error><|
10-19 18:15:03.966  level=error msg=00000050  43 6f 64 65 3e 55 6e 73  75 70 70 6f 72 74 65 64  |Code>Unsupported|
10-19 18:15:03.966  level=error msg=00000060  4f 70 65 72 61 74 69 6f  6e 3c 2f 43 6f 64 65 3e  |Operation</Code>|
10-19 18:15:03.966  level=error msg=00000070  3c 4d 65 73 73 61 67 65  3e 54 68 65 20 66 75 6e  |<Message>The fun|
10-19 18:15:03.966  level=error msg=00000080  63 74 69 6f 6e 61 6c 69  74 79 20 79 6f 75 20 72  |ctionality you r|
10-19 18:15:03.966  level=error msg=00000090  65 71 75 65 73 74 65 64  20 69 73 20 6e 6f 74 20  |equested is not |
10-19 18:15:03.966  level=error msg=000000a0  61 76 61 69 6c 61 62 6c  65 20 69 6e 20 74 68 69  |available in thi|
10-19 18:15:03.967  level=error msg=000000b0  73 20 72 65 67 69 6f 6e  2e 3c 2f 4d 65 73 73 61  |s region.</Messa|
10-19 18:15:03.967  level=error msg=000000c0  67 65 3e 3c 2f 45 72 72  6f 72 3e 3c 52 65 71 75  |ge></Error><Requ|
10-19 18:15:03.967  level=error msg=000000d0  65 73 74 49 44 3e 63 64  38 31 39 36 33 64 64 37  |estID>cd81963dd7|
10-19 18:15:03.967  level=error msg=000000e0  66 31 34 61 37 62 39 31  38 33 37 61 35 38 38 31  |f14a7b91837a5881|
10-19 18:15:03.967  level=error msg=000000f0  65 32 34 35 32 34 3c 2f  52 65 71 75 65 73 74 49  |e24524</RequestI|
10-19 18:15:03.967  level=error msg=00000100  44 3e 3c 2f 45 72 72 6f  72 73 3e 3c 2f 52 65 73  |D></Errors></Res|
10-19 18:15:03.967  level=error msg=00000110  70 6f 6e 73 65 3e                                 |ponse>|
10-19 18:15:03.967  level=error
10-19 18:15:03.967  level=error msg=caused by: unknown error response tag, {{ Response} []}
10-19 18:15:03.967  level=error
10-19 18:15:03.967  level=error msg=  with module.dns.aws_route53_zone.new_int[0],
10-19 18:15:03.967  level=error msg=  on route53/base.tf line 24, in resource "aws_route53_zone" "new_int":
10-19 18:15:03.967  level=error msg=  24: resource "aws_route53_zone" "new_int" {
10-19 18:15:03.967  level=error
10-19 18:15:03.967  level=error
```

**Comment by r4f4** [comment]
This seems to be happening in a different terraform resource, but I wonder if it's related to https://github.com/openshift/installer/pull/6475 and https://issues.redhat.com/browse/OCPBUGS-2324

**Comment by patrickdillon** [comment]
/approve

@r4f4 you put a hold on this, is that still valid? seems ready to merge to me

**Comment by r4f4** [comment]
> /approve
> 
> @r4f4 you put a hold on this, is that still valid? seems ready to merge to me

I hope I would've stated a reason for the hold, but I think I did it because we were still discussing if this needed an RFE or not.

/hold cancel

**Comment by r4f4** [comment]
I have broken out the CNAME -> Alias change to its own PR: https://github.com/openshift/installer/pull/7184

**Review by barbacbd — COMMENTED** [review]
/lgtm

**Pull request merged**
