### PR TITLE
Bump Azure Stack Terraform Provider for Go 1.18

### PR DESCRIPTION
**Pull request by patrickdillon**
Builds for Mac are failing with Go 1.18 due to an outdated dependency in the Azure Stack Terraform provider on x/sys: https://github.com/golang/go/issues/49219

I tested this using `registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.18-openshift-4.11` and it resolves the issue.

### CODE REVIEW

**Comment by patrickdillon** [comment]
Let's make sure `e2e-azurestack` gets a successful terraform run.

**Comment by patrickdillon** [comment]
The goal here is to ensure compatibility with Go 1.18, but not yet require it.

**Comment by barbacbd** [comment]
Sifted through the files and there was only the one go.mod file changed. Verified the version of sys that was updated. /lgtm

**Comment by patrickdillon** [comment]
Reran with `go mod tidy -compat=1.17` to fix failing verify-vendor test.

**Comment by patrickdillon** [comment]
e2e-azurestack tests are successfully running terraform. failure is after bootstrap complete.

/approve

**Pull request merged**
