### PR TITLE
OCPBUGS-33874: capi/aws: fix bootstrap ssh destroy

### PR DESCRIPTION
**Pull request by r4f4**
We do not want to modify the AWSCluster object, specially in the middle of deleting the bootstrap node, because it triggers a cluster reconcile loop in CAPA. Instead, let's use the AWS SDK to revoke only the ssh rule directly.

It should be fine to modify the cluster without CAPA's knowledge because at the bootstrap destroy stage we're about to shutdown the capi system anyway. Besides, the Installer is responsible for deleting resources and it knows how to find the security groups and its rules by the cluster tag.

### CODE REVIEW

**Comment by r4f4** [comment]
Update: adding the re-revert of https://github.com/openshift/installer/pull/8433 so we can payload-test the fix.

/payload-aggregate periodic-ci-openshift-release-master-ci-4.17-e2e-aws-ovn 10

/assign @patrickdillon 
To help monitor the results.

**Comment by r4f4** [comment]
Aggregate results:
```
1. [periodic-ci-openshift-release-master-ci-4.17-e2e-aws-ovn/1792768625870901248](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/openshift-installer-8425-ci-4.17-e2e-aws-ovn/1792768625870901248) build03 success after 2h53m20s **********
2. [periodic-ci-openshift-release-master-ci-4.17-e2e-aws-ovn/1792768626793648128](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/openshift-installer-8425-ci-4.17-e2e-aws-ovn/1792768626793648128) build03 success after 3h3m43s ***********
3. [periodic-ci-openshift-release-master-ci-4.17-e2e-aws-ovn/1792768637140996096](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/openshift-installer-8425-ci-4.17-e2e-aws-ovn/1792768637140996096) build03 failure after 3h1m21s **********
4. [periodic-ci-openshift-release-master-ci-4.17-e2e-aws-ovn/1792768630451081216](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/openshift-installer-8425-ci-4.17-e2e-aws-ovn/1792768630451081216) build03 success after 2h56m11s **********
5. [periodic-ci-openshift-release-master-ci-4.17-e2e-aws-ovn/1792768627238244352](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/openshift-installer-8425-ci-4.17-e2e-aws-ovn/1792768627238244352) build03 success after 2h58m59s **********
6. [periodic-ci-openshift-release-master-ci-4.17-e2e-aws-ovn/1792768626319691776](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/openshift-installer-8425-ci-4.17-e2e-aws-ovn/1792768626319691776) build03 failure after 2h57m55s **********
7. [periodic-ci-openshift-release-master-ci-4.17-e2e-aws-ovn/1792768625396944896](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/openshift-installer-8425-ci-4.17-e2e-aws-ovn/1792768625396944896) build03 success after 3h4m5s ***********
8. [periodic-ci-openshift-release-master-ci-4.17-e2e-aws-ovn/1792768632132997120](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/openshift-installer-8425-ci-4.17-e2e-aws-ovn/1792768632132997120) build03 success after 2h59m23s **********
9. [periodic-ci-openshift-release-master-ci-4.17-e2e-aws-ovn/1792768628756582400](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/openshift-installer-8425-ci-4.17-e2e-aws-ovn/1792768628756582400) build03 success after 3h4m43s ***********
10. [periodic-ci-openshift-release-master-ci-4.17-e2e-aws-ovn/1792768634624413696](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/openshift-installer-8425-ci-4.17-e2e-aws-ovn/1792768634624413696) build03 success after 3h3m21s ***********
```
Failure 3. happened during waiting for bootstrap to complete, so not related the the ssh rule timeout : https://prow.ci.openshift.org/view/gs/test-platform-results/logs/openshift-installer-8425-ci-4.17-e2e-aws-ovn/1792768637140996096

Failure 6. was due to an e2e test: https://prow.ci.openshift.org/view/gs/test-platform-results/logs/openshift-installer-8425-ci-4.17-e2e-aws-ovn/1792768626319691776

**Comment by patrickdillon** [comment]
/approve

Still in process testing/reviewing this, but looks good at a high level. Will apply more labels after further review

**Comment by patrickdillon** [comment]
/approve cancel

I don't think the SSH rule is getting deleted. It looks like it might be getting reconciled by capi after the delete. I was working on something similar to this that runs after capi shutdown, but is buggy. Will share it and continue to work on this

**Comment by patrickdillon** [comment]
After reviewing this and working on an sdk-implementation myself in #8442, I want to revisit the idea of handling this through CAPI , and adjusting the failure logic (timeouts). Deleting the security rules through the SDK is complex and CAPI seems to handle this quite nicely for us.

I know there were concerns over recreating bootstrap ignition so I will review that, and I will look at what's going on in the outlier cases where deleting the rules takes longer than 5 minutes.

**Comment by patrickdillon** [comment]
/hold
in favor of #8427

**Comment by r4f4** [comment]
/close
Fixed by https://github.com/openshift/installer/pull/8427

**Pull request closed without merging**
