### PR TITLE
[4.3] vendor: update gopkg.in/AlecAivazis/survey to v1.8.7

### PR DESCRIPTION
**Pull request by mkumatag**
Fixes: https://github.com/openshift/installer/issues/2290

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
/hold

Candidate for 4.3, in order to stabilize the product got 4.2 we aren't adding code that isn't a bug.

**Comment by mkumatag** [comment]
> /hold
> 
> Candidate for 4.3, in order to stabilize the product got 4.2 we aren't adding code that isn't a bug.

@abhinavdahiya any idea when the gate will opened for 4.3 release?

**Pull request merged**
