### PR TITLE
cmd/openshift-install/waitfor: Rename from user-provided-infrastructure

### PR DESCRIPTION
**Pull request by wking**
There is no hard line between installer- and user-provided infrastructure.  Rename these commands to focus on what they'll do instead of the work-flow into which we expect them to fit.

We're still working out how we can drop the router-CA injection to avoid `wait-for cluster-ready` surprising users my editing their on-disk kubeconfig (#1541).  But that's mitigated somewhat by the fact that `addRouterCAToClusterCA` is idempotent, because [`AppendCertsFromPEM` wraps `AddCert`][2] and [`AddCert` checks to avoid duplicate certificates][3].

I haven't provided backwards-compat shims because the UPI workflow is so young that I don't expect users who rely on its stability.

[2]: https://github.com/golang/go/blob/go1.12/src/crypto/x509/cert_pool.go#L144
[3]: https://github.com/golang/go/blob/go1.12/src/crypto/x509/cert_pool.go#L106-L109

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
@wking can you update other users of `upi` like https://github.com/abhinavdahiya/installer/commit/16b7301cd2e2bf9bbe8bf5a2d1f36f8cfc5db420

**Comment by wking** [comment]
> ... can you update other users of `upi`...

That's what you get for using the convenient alias instead of the full subcommand name ;).  But yeah, done with 2a39d8bce -> 8cd13c0af.

**Comment by wking** [comment]
[e2e-aws][1]:

```
Flaky tests:

[Feature:Platform][Smoke] Managed cluster should start all core operators [Suite:openshift/conformance/parallel]
[Feature:Prometheus][Conformance] Prometheus when installed on the cluster should start and expose a secured proxy and unsecured metrics [Suite:openshift/conformance/parallel/minimal]

Failing tests:

[sig-storage] In-tree Volumes [Driver: hostPath] [Testpattern: Dynamic PV (default fs)] provisioning should provision storage with mount options [Suite:openshift/conformance/parallel] [Suite:k8s]
```

/retest

[1]: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_installer/1552/pull-ci-openshift-installer-master-e2e-aws/5016

**Pull request merged**
