### PR TITLE
tests/run: Make IAM role changes optional

### PR DESCRIPTION
**Pull request by wking**
This pull request builds on #171; I'll rebase after that lands, and reviewers can feel free to wait on that before reviewing this PR.

I'm not authorized to assume roles in the teamcoreservices account, and the `assume-role` call errors out with:

> An error occurred (AccessDenied) when calling the AssumeRole operation: Not authorized to perform sts:AssumeRole

That's fine though; I can still launch the cluster with my usual access.  This pull request makes the role assumption optional.  I've made setting up the `AWS_*` access variables conditional on successful role assumption, because setting them based on an empty `$RES` wouldn't work ;).

Using the `&&` chain with a terminal `||` keeps the script from dying on this `assume-role` failure.  From [the `set -e` docs][1]:

> The shell does not exit if the command that fails is ... part of any command executed in a `&&` or `||` list except the command following the final `&&` or `||`...

I'm also only setting `iamRoleName` configs if `assume-role` succeeded.  We've been setting `iamRoleName` since the script landed in a2405e4d (coreos/tectonic-installer#3284) and possibly before that since 82daae14 (coreos/tectonic-installer#3074).  I don't see anything in those commits or PRs to motivate the `iamRoleName` entries, but I'd guess they, like the `tf-tectonic-installer` role, are specific to the Jenkins setup.  I've tied them together with `CONFIGURE_AWS_ROLES` based on that similarity, although in theory you may be able to toggle the `iamRoleName` settings independently of `assume-role` success.

Even though the `&&`/`||` chain sets `CONFIGURE_AWS_ROLES=False` when `assume-role` failes, I'm using `${CONFIGURE_AWS_ROLES:-False}` in the Python script.  That way, future versions of this script that support libvirt (or other backends) won't need to bother setting `CONFIGURE_AWS_ROLES` and will still get valid Python here.  The `:-` syntax is specified [in POSIX][2], and my expansion defaults to `False` if `CONFIGURE_AWS_ROLES` is unset or empty.

I've also included an unrelated commit to move `AWS_REGION` and adjust its default fallbacks.  Details in that commit message.  I'm happy to spin this out into its own PR if it would make review easier.

[1]: https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html
[2]: http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_06_02

### CODE REVIEW

**Comment by wking** [comment]
retest this please

**Comment by abhinavdahiya** [comment]
This script is supposed to be used by CI. Does it make sense to make is generic enough for users ???

**Comment by wking** [comment]
> Does it make sense to make is generic enough for users ???

It's easier for me to debug CI failures like I'm seeing in #94 if I can run the tests locally.  These changes make it easier for me to adjust the script so I can launch a cluster in the smoke-test-approved way, run the smoke tests multiple times against that cluster, and then finally tear the cluster back down.  I could accomplish pretty much the same thing by walking through the `README` steps to create my cluster; but it's convenient to use the almost-works-for-me-out-of-the-box script ;).

**Comment by wking** [comment]
There's a conflict with the just-landed #169.  I'll wait until #171 lands and then rebase this one.

**Comment by wking** [comment]
Rebased around #169 with bcf2cde -> 1121c0b.

**Comment by wking** [comment]
[The smoke-test error][1] was:

```
 Unpacking artifacts...
 Exiting... Destroying Tectonic...
tectonic: error: path 'ci-pr-172-7fbe2' does not exist, try --help
```

I'm guessing that's because `aws configure get region` exited non-zero.  I've pushed 1121c0b -> 0ad03ed which should address that.

[1]: https://jenkins-tectonic-installer.prod.coreos.systems/job/openshift-installer/view/change-requests/job/PR-172/5/consoleText

**Comment by wking** [comment]
All green, but see [above][1] for @abhinavdahiya's "do we want to do this?".

[1]: https://github.com/openshift/installer/pull/172#issuecomment-415864317

**Comment by wking** [comment]
/retest all

^ exercising the just-landed openshift/release#1289.

**Comment by wking** [comment]
Hmm, maybe `/retest all` isn't the right incantation.

/test all

**Comment by wking** [comment]
[The e2e-aws error][1] was:

```
Waiting for API at https://ci-op-wj52qf1g-68485-api.origin-ci-int-aws.dev.rhcloud.com:6443 to respond ...
Interrupted
```

/retest

[1]: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_installer/172/pull-ci-origin-installer-e2e-aws/750/build-log.txt

**Pull request merged**
