### PR TITLE
no-jira: cmd/openshift-install: Remove "migrate" command

### PR DESCRIPTION
**Pull request by jhixson74**
The migrate command migrated old style Azure DNS zones to the newer style. The ability to create old style DNS zones in Azure hasn't existed in years, so this command can be retired.

### CODE REVIEW

**Comment by sadasu** [comment]
/test verify-vendor

Afaik, failure does not seem related to this change.

**Review by r4f4 — COMMENTED** [review]
/lgtm

**Comment by r4f4** [comment]
/lgtm cancel
Needs `go mod tidy && go mod vendor`

**Review by r4f4 — COMMENTED** [review]
Always nice to see  `+0 −68,776`
/lgtm

**Pull request merged**
