### PR TITLE
OCPBUGS-4549: azure: replace deprecated AD Graph API

### PR DESCRIPTION
**Pull request by r4f4**
Use the new MS Graph API instead.
    
Please note that `Applications.ReadWrite.OwnedBy` permissions must be granted in Azure for MSGraph.
    
https://github.com/azure-deprecation/dashboard/issues/60
    
https://issues.redhat.com/browse/CORS-1897

### CODE REVIEW

**Comment by r4f4** [comment]
Depends on https://github.com/openshift/installer/pull/6003

This is an alternative to https://github.com/openshift/installer/pull/5714. In this PR, only the new MSGraph calls are tried with no fallback to the deprecated AD Graph APIs (which are removed here).

**Comment by r4f4** [comment]
Error strings from msgraph sdk are not very helpful. They just say `error status code received from the API`. So we might want to unwrap the `ODataError` before logging it.

https://github.com/microsoftgraph/msgraph-sdk-go/discussions/218

**Comment by patrickdillon** [comment]
/retest
/approve
LGTM but let's see what the tests say and obviously we need to wait for #6003

But I think we should do this over #5714

**Comment by patrickdillon** [comment]
ug, was coming to LGTM but we already hit another conflict :(

**Comment by r4f4** [comment]
/override ci/prow/golint
It's timing out. It should be better when https://github.com/openshift/installer/pull/6601 merges. I ran it locally and there were no problems reported.

**Comment by r4f4** [comment]
/override ci/prow/e2e-gcp-ovn
Not affected by the changes in this PR

**Comment by r4f4** [comment]
/override ci/prow/e2e-gcp-ovn
Not affected by the PR

**Comment by r4f4** [comment]
/override ci/prow/e2e-gcp-ovn
Not affected and timing out

**Pull request merged**
