### PR TITLE
OCPBUGS-39586: Add C4A instance types

### PR DESCRIPTION
**Pull request by barbacbd**
** Add the C4A instance type for GCP. This instance type requires a disk type of hyperdisk balanced. It is currently under PREVIEW.

### CODE REVIEW

**Comment by barbacbd** [comment]
/hold 

waiting for https://github.com/openshift/machine-api-provider-gcp/pull/94

**Comment by r4f4** [comment]
/approve

/hold
In case @patrickdillon  wants to check it out before it merges.

**Comment by patrickdillon** [comment]
/hold cancel
lgtm. Seems to be very minimal changes and mostly vendoring.

**Pull request merged**
