### PR TITLE
Alibaba: fix: use the max function

### PR DESCRIPTION
**Pull request by bd233**
Use the max function is a lot easier to read

### CODE REVIEW

**Review by staebler — COMMENTED** [review]
This looks good to me. @kwoodson can you verify this change?

/approve

**Comment by kwoodson** [comment]
@staebler Was able to successfully install using this PR.

**Comment by staebler** [comment]
> @staebler Was able to successfully install using this PR.

Thanks. Feel free to give PRs that you are verifying on my behalf an lgtm.
/lgtm

**Pull request merged**
