### PR TITLE
OCPBUGS-3123: Pass FeatureSet to cluster config render

### PR DESCRIPTION
**Pull request by sanchezl**
- add FeatureSet to bootstrap template data
- pass FeatureSet to cluster config render

### CODE REVIEW

**Comment by deads2k** [comment]
this looks plausible the me.  the CI failures are kind of weird looking

**Comment by sanchezl** [comment]
/hold 
for https://github.com/openshift/cluster-config-operator/pull/271

**Comment by patrickdillon** [comment]
/override ci/prow/e2e-vsphere-ovn

Tests are failing with unrelated: https://issues.redhat.com/browse/OCPBUGS-2991

**Pull request merged**
