### PR TITLE
OCPBUGS-30642: Revert "Merge pull request #8020 from hamzy/PowerVS-MULTIARCH-4095"

### PR DESCRIPTION
**Pull request by r4f4**
This reverts commit 1b99648e0bf435e3a29e838a26e23c4819964be8, reversing changes made to cc61152548a2f91bff1a14a35a78114d178c4909.

### CODE REVIEW

**Comment by patrickdillon** [comment]
/approve
Let's see how gcp ovn looks

**Comment by r4f4** [comment]
Since the bump to GCP SDK, the GCP jobs have been failing with variations of 
```
level=info msg=Credentials loaded from environment variable "GOOGLE_CLOUD_KEYFILE_JSON", file "/var/run/secrets/ci.openshift.io/cluster-profile/gce.json"
level=error msg=failed to fetch Master Machines: failed to load asset "Install Config": failed to create install config: [platform.gcp.project: Internal error: failed to create cloud resource service: Get "http://169.254.169.254/computeMetadata/v1/universe/universe_domain": dial tcp 169.254.169.254:80: connect: connection refused, : Internal error: failed to create compute service: Get "http://169.254.169.254/computeMetadata/v1/universe/universe_domain": dial tcp 169.254.169.254:80: connect: connection refused]
```
The latest google sdk will try to get the `universe_domain` from the metadata server if it is not set in the credentials but traffic to that server's IP can be blocked.

**Comment by r4f4** [comment]
/hold
I messed up the revert.

**Comment by r4f4** [comment]
/retitle OCPBUGS-30642: Revert "Merge pull request #8020 from hamzy/PowerVS-MULTIARCH-4095"

**Pull request closed without merging**
