### PR TITLE
Bug 1963205: rhcos: Use ART redirector

### PR DESCRIPTION
**Pull request by cgwalters**
See https://github.com/openshift/release/pull/18496
and https://issues.redhat.com/browse/DPTP-2198

This is not the final location, but it's better than the previous
version on the old cluster.

### CODE REVIEW

**Review by staebler — APPROVED** [review]
/lgtm
/hold for a BZ or master to open

**Comment by e-tienne** [comment]
/lgtm
https://rhcos-redirector.ci.openshift.org/art/storage/releases/rhcos-4.8/48.84.202104271417-0/x86_64/meta.json works

**Comment by cgwalters** [comment]
Filed a BZ, but feel free to debate severity - this could wait for later, but risk of landing is pretty low and we want to do this.

**Comment by cgwalters** [comment]
/hold cancel
since we have a BZ

**Comment by hongkailiu** [comment]
@cgwalters 

Have you deployed the service on another cluster (neither api.ci nor app.ci)? From DPTP side, we want to resume the decommission of api.ci ASAP. That is why I am trying to redirect the traffic of releases-rhcos.svc.ci.openshift.org to app.ci.

I can also set up the CNAME or A record of `releases-art-rhcos.svc.ci.openshift.org` to the new cluster and thus we do not need https://github.com/openshift/release/pull/18642 or api.ci.

**Comment by hongkailiu** [comment]
> So yes, we could actually now drop the service from app.ci too and have the CNAME now redirect to the ART version which is referenced in #4928

https://issues.redhat.com/browse/ART-2818?focusedCommentId=16225911&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16225911

**Pull request merged**
