### PR TITLE
vsphere: upi, use community ignition provider

### PR DESCRIPTION
**Pull request by jcpowermac**

### CODE REVIEW

**Comment by jcpowermac** [comment]
CI cluster was having issues let's try again

/test e2e-vsphere-upi

**Comment by jcpowermac** [comment]
baremetal install build is broke

**Comment by jcpowermac** [comment]
see:
https://github.com/openshift/release/pull/27834

**Comment by jcpowermac** [comment]
/test e2e-vsphere-upi

:crossed_fingers:

**Comment by jcpowermac** [comment]
@patrickdillon any chance we can skip `e2e-metal-ipi-ovn-ipv6` ? 
https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/pull-ci-openshift-installer-master-e2e-metal-ipi-ovn-ipv6
doesn't look too stable and unrelated

**Comment by patrickdillon** [comment]
> e2e-metal-ipi-ovn-ipv6

Yes. I don't understand why this is running, unless it is due to an old context or something. I recently changed the triggers so this job SHOULD only be required on metal jobs: https://github.com/openshift/release/blob/master/ci-operator/jobs/openshift/installer/openshift-installer-master-presubmits.yaml#L2163-L2235

/refresh
/skip

Let's see if that helps and if not I'll override it.

**Comment by sebsoto** [comment]
@patrickdillon any idea whats going on here with the `e2e-metal-ipi-ovn-ipv6` test?

**Comment by patrickdillon** [comment]
/override ci/prow/e2e-metal-ipi-ovn-ipv6

> @patrickdillon any idea whats going on here with the `e2e-metal-ipi-ovn-ipv6` test?

The test has been broken, the fixed, then seems to be a bit broken again? I'm not sure. It is maintained by the baremetal installer team. 

The test was included in too many unrelated PRs, which has since been fixed, but PRs created before the jobs changed still seem to be running the test.

**Pull request merged**
