### PR TITLE
OCPBUGS-35366: Update upi references to api-internal

### PR DESCRIPTION
**Pull request by barbacbd**
** Updated the UPI references in docs and scripts to use api-internal to the name to match those of the capg and terraform resources.

### CODE REVIEW

**Comment by patrickdillon** [comment]
upi test failed with

```
 - code: MANIFEST_EXPANSION_USER_ERROR
  location: /deployments/ci-op-8wv5v3bn-88016-8zbhb-infra/manifests/manifest-1718218075502
  message: "Manifest expansion encountered the following errors: Resource name 'ci-op-8wv5v3bn-88016-8zbhb-api-internal'\
    \ is not unique in 02_lb_int.py. Resource: {'name': 'ci-op-8wv5v3bn-88016-8zbhb-api-internal',\
    \ 'type': 'compute.v1.regionBackendService', 'properties': {'backends': [{'group':\
    \ '$(ref.ci-op-8wv5v3bn-88016-8zbhb-master-us-central1-c-ig.selfLink)'}, {'group':\
    \ '$(ref.ci-op-8wv5v3bn-88016-8zbhb-master-us-central1-f-ig.selfLink)'}, {'group':\
    \ '$(ref.ci-op-8wv5v3bn-88016-8zbhb-master-us-central1-b-ig.selfLink)'}], 'healthChecks':\
    \ ['$(ref.ci-op-8wv5v3bn-88016-8zbhb-api-internal.selfLink)'], 'loadBalancingScheme':\
    \ 'INTERNAL', 'region': 'us-central1', 'protocol': 'TCP', 'timeoutSec': 120}}\
    \ Resource: config" 
```

not sure what's up there

**Comment by r4f4** [comment]
> upi test failed with
> 
> ```
>  - code: MANIFEST_EXPANSION_USER_ERROR
>   location: /deployments/ci-op-8wv5v3bn-88016-8zbhb-infra/manifests/manifest-1718218075502
>   message: "Manifest expansion encountered the following errors: Resource name 'ci-op-8wv5v3bn-88016-8zbhb-api-internal'\
>     \ is not unique in 02_lb_int.py. Resource: {'name': 'ci-op-8wv5v3bn-88016-8zbhb-api-internal',\
>     \ 'type': 'compute.v1.regionBackendService', 'properties': {'backends': [{'group':\
>     \ '$(ref.ci-op-8wv5v3bn-88016-8zbhb-master-us-central1-c-ig.selfLink)'}, {'group':\
>     \ '$(ref.ci-op-8wv5v3bn-88016-8zbhb-master-us-central1-f-ig.selfLink)'}, {'group':\
>     \ '$(ref.ci-op-8wv5v3bn-88016-8zbhb-master-us-central1-b-ig.selfLink)'}], 'healthChecks':\
>     \ ['$(ref.ci-op-8wv5v3bn-88016-8zbhb-api-internal.selfLink)'], 'loadBalancingScheme':\
>     \ 'INTERNAL', 'region': 'us-central1', 'protocol': 'TCP', 'timeoutSec': 120}}\
>     \ Resource: config" 
> ```
> 
> not sure what's up there

As @theobarberbany figured out, the UPI workflow in CI needs to be updated with equivalent changes: https://github.com/openshift/release/pull/53419

**Comment by theobarberbany** [comment]
We need https://github.com/openshift/installer/pull/8582 to merge first, we've got a bit of a chicken & egg problem

**Comment by theobarberbany** [comment]
The o/release PR has merged, so lets hope everything turns green now 🤞

**Review by r4f4 — COMMENTED** [review]
/approve

**Pull request merged**
