### PR TITLE
WIP: Adding support for s390 while performing an agent based Install

### PR DESCRIPTION
**Pull request by Neeraj8418**

### CODE REVIEW

**Review by barbacbd — CHANGES_REQUESTED** [review]
@Neeraj8418 

1. You should modify your PR title and commit message to reflect what changes you made
2. You should probably state why this is an issue that needs fixing. For instance I do see in the [docs](https://docs.openshift.com/container-platform/4.14/operators/operator_sdk/osdk-multi-arch-support.html) that we state this is a supported architecture.
3. You should have 1 commit as this is very small and the are related. Please drop the commit by root.

**Comment by sadasu** [comment]
/retitle WIP: Neeraj8418 patch 1

Please fix title

**Comment by sadasu** [comment]
/retitle WIP: Adding support for s390 while performing an agent based Install

**Pull request closed without merging**
