### PR TITLE
[FCOS] Rebase Aug 12

### PR DESCRIPTION
**Pull request by vrutkovs**
Rebase fcos on latest commits from release-4.5

```
TARGET_COMMIT=$(git describe --tags fcos | sed 's/.*-g//')
git checkout -b fcos-rebase-aug12 origin/release-4.5
git rebase --onto fcos $TARGET_COMMIT
```

/cc @LorbusChris

### CODE REVIEW

**Comment by vrutkovs** [comment]
Flake

/retest

**Comment by LorbusChris** [comment]
We probably don't want the RHCOS AMIs in `rhcos.json` on this branch?

**Comment by vrutkovs** [comment]
>We probably don't want the RHCOS AMIs in rhcos.json on this branch?

These are not used by our installer (it swiches to `fcos.json`), keeping these commits to make further rebasing simple

**Pull request merged**
