### PR TITLE
Bug 2061947: IBMCloud: Handle missing RG

### PR DESCRIPTION
**Pull request by cjschaef**
Handle cases when there is no ResourceGroupName provided
during destroy, or the ResourceGroup doesn't exist, or cannot
be found.

Related: https://bugzilla.redhat.com/show_bug.cgi?id=2061947

### CODE REVIEW

**Comment by cjschaef** [comment]
Tested that an empty `resourceGroupName` or one that doesn't exist in the `metadata.json` result in a failure.
```
# bin/openshift-install destroy cluster --dir bz_2061947/bz2061947-no-rg-2
FATAL Failed to destroy cluster: No ResourceGroupName provided
```
```
# bin/openshift-install destroy cluster --dir bz_2061947/bz2061947-no-rg-2
FATAL Failed to destroy cluster: ResourceGroup '"bz2061947-no-rg-not-rg-tqcmc"' not found
```

**Comment by MayXuQQ** [comment]
can you help deal with such issue, fail to delete the volume (blocked by Service Broker returned error status code 500) , avoid loop prompt. 
the metadata.json 
{"clusterName":"logci4272","clusterID":"eaaac982-574e-48c1-a455-32b3bbd6a0c8","infraID":"logci4272-ddbjm","ibmcloud":{"accountID":"fdc2e14cf8bc4d53a67f972dc2e2c861","baseDomain":"ibmcloud.qe.devcluster.openshift.com","cisInstanceCRN":"crn:v1:bluemix:public:internet-svcs:global:a/fdc2e14cf8bc4d53a67f972dc2e2c861:e8ee6ca1-4b31-4307-8190-e67f6925f83b::","region":"us-east","resourceGroupName":"logci4272-ddbjm"}}

**Comment by cjschaef** [comment]
Things appear okay, will attempt to retry test, given other CI builds don't seem affected a this time.
/test e2e-ibmcloud

**Comment by cjschaef** [comment]
There have been numerous issues with IBM Cloud IAM and COS. I believe that is the cause of the latest failure (perhaps earlier failure as well), I have experienced with local testing. I will monitor until things appear to be restored and retry the testing then.

**Review by MayXuQQ — APPROVED** [review]

**Comment by cjschaef** [comment]
I've been seeing IAM errors with IBM Cloud, causing COS and other failures, likely resulting in the issues during testing.
I will see if I can get some successful builds to verify whether those issues have been resolved.

/test e2e-ibmcloud

**Comment by cjschaef** [comment]
`e2e-ibmcloud` requires a fix to the MAPI repo/image
https://github.com/openshift/machine-api-provider-ibmcloud/pull/3

**Comment by cjschaef** [comment]
[MAPI patch](https://github.com/openshift/machine-api-provider-ibmcloud/pull/3) merged.

Retesting `e2e-ibmcloud` to verify install works (Conformance tests expected to fail).
/test e2e-ibmcloud

**Comment by cjschaef** [comment]
This [`e2e-ibmcloud` failure](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_installer/6152/pull-ci-openshift-installer-master-e2e-ibmcloud/1556634870967439360) is expected, the install completed, and failure during Conformance tests (yet to be resolved).

This should be good for review/merge finally.

**Pull request merged**
