### PR TITLE
OCPBUGS-15659: IPI pre-check for MachineAPI capability

### PR DESCRIPTION
**Pull request by rwsu**
Adds a validation check to ensure that MachineAPI capability is included for IPI deployments.

### CODE REVIEW

**Review by patrickdillon — COMMENTED** [review]
/approve

**Comment by jinyunma** [comment]
@rwsu FYI. MachineAPI is required on IPI including IPI SON, IPI compact and common IPI (3 masters + N workers). It only can be disabled in UPI cluster.
Discussion is [here](https://redhat-internal.slack.com/archives/C032HSVS71T/p1689850599305979).

**Pull request merged**
