### PR TITLE
CORS-2890: Bump CAPA Dependencies for Secondary Load Balancers

### PR DESCRIPTION
**Pull request by patrickdillon**
Bump CAPA (controller and installer packages) to bring in secondary load balancer support.

/cc @vincepri @r4f4

### CODE REVIEW

**Review by r4f4 — COMMENTED** [review]
/lgtm

**Comment by patrickdillon** [comment]
/hold cancel

Bumped to the shiny new v2.4.0 and remembered to include infrastructure-components.yaml this time

**Review by r4f4 — COMMENTED** [review]
/lgtm

**Pull request merged**
