### PR TITLE
Bug 2085721:  Fix name for customization controller image

### PR DESCRIPTION
**Pull request by elfosardo**
The ICC has been renamed to machine-image-customization-controller

### CODE REVIEW

**Comment by derekhiggins** [comment]
lgtm
Ci is now getting further and failing on creating the  machine-image-customization-controller pod (a related but seperate problem)
image-customization

**Comment by stbenjam** [comment]
This needs a BZ.

**Comment by stbenjam** [comment]
/retitle Bug 2085721:  Fix name for customization controller image

**Comment by deads2k** [comment]
unsticking metal . @stbenjam will watch

**Pull request merged**
