### PR TITLE
OCPBUGS-34506: [release-4.16] bump golang-protobuf for CVE fix

### PR DESCRIPTION
**Pull request by r4f4**
Bump golang.org/protobuf to v1.33.0 for https://github.com/advisories/GHSA-8r3f-844c-mc37 fix.

Manual cherry-pick of https://github.com/openshift/installer/pull/8379

### CODE REVIEW

**Review by barbacbd — COMMENTED** [review]
/lgtm

**Review by sadasu — COMMENTED** [review]
/approve

**Pull request merged**
