### PR TITLE
openstack: Set kuryr as NetworkType if trunks and octavia are available

### PR DESCRIPTION
**Pull request by luis5tb**
This PR check the trunk extension and if octavia is available to
automatically set the SDN to Kuryr for OpenStack environments

### CODE REVIEW

**Comment by trown** [comment]
/lgtm

This is no longer being tested, so we will want to setup an e2e-openstack-kuryr job ASAP.

**Comment by tomassedovic** [comment]
/lgtm

For what it's worth, both @trown and myself approve of this change for OpenStack, but we can't merge it due to the `Gopkg.lock` changes.

**Comment by tomassedovic** [comment]
/hold

While the installer portion looks good, there are a few configuration issues that need to be addressed in CNO that prevent Kuryr to do a successful end to end run.

Since Kuryr will be enabled on any OpenStack that has Neutron Trunk Ports and Octavia enabled, merging this PR now would break those deployments.

I'm proposing a hold until we can finish a deployment with  Kuryr successfully. And ideally, until we've got a job exercising it too:

https://github.com/openshift/release/pull/4292
https://github.com/openshift/release/pull/4294

**Comment by dulek** [comment]
@tomassedovic, @luis5tb: In #2071 I proposed an approach that will only set Kuryr automatically when there is no NetworkType set in InstallConfig. I believe it's way safer as it'll be easy to override in any case.

**Comment by abhinavdahiya** [comment]
closing due to inactivity. Please reopen if needed.

/close

**Pull request closed without merging**
