### PR TITLE
OCPBUGS-17851: Update Azure zone to non-pointer

### PR DESCRIPTION
**Pull request by RadekManak**
Azure's AzureMachineProviderSpec Zone field was updated to be a non-pointer. This PR updates its usage to be compatible again.

### CODE REVIEW

**Review by r4f4 — COMMENTED** [review]
/lgtm

**Comment by r4f4** [comment]
/retest-required
CI should be more stable now

**Comment by RadekManak** [comment]
/hold

We have reverted https://github.com/openshift/machine-api-provider-azure/pull/72. We need to reconsider the implications of this change. This will probably not ship in 4.14.

**Pull request closed without merging**
