### PR TITLE
OCPBUGS-1242: Add PowerVS zone mon01 support

### PR DESCRIPTION
**Pull request by hamzy**
The 4.11 branch of the installer needs to support the zone mon01 in PowerVS for the CI

### CODE REVIEW

**Comment by hamzy** [comment]
@rna-afk can we get an approve?

**Comment by hamzy** [comment]
@jhixson74 Hello.  How do I get the "backport-risk-assessed" label as this bug is not a cherry pick.

**Comment by r4f4** [comment]
> @jhixson74 Hello. How do I get the "backport-risk-assessed" label as this bug is not a cherry pick.

Technically it is because you're applying a change in master to an older branch. Anyway you need a dev to give you the `backport-risk-assessed` and a QE to give `cherry-pick-approved` labels.

**Comment by hamzy** [comment]
@r4f4 
>  Anyway you need a dev to give you the ...
I guess I am not a dev in this scenario?  If not, would that dev be in the approvers section?

**Comment by Prashanth684** [comment]
> @r4f4
> 
> > Anyway you need a dev to give you the ...
> 
> I guess I am not a dev in this scenario? If not, would that dev be in the approvers section?

do we need this support in 4.11? given that powervs is not supported in 4.11

**Comment by hamzy** [comment]
> do we need this support in 4.11? given that powervs is not supported in 4.11

Yes!  There is only one properly fixed zone so far in PowerVS and that is mon01.  While it may not be supported it is used by developers.  Which is why I created this PR.

**Comment by hamzy** [comment]
@openshift-ci-robot Empty set [], nice! :)

**Comment by r4f4** [comment]
> @r4f4
> 
> > Anyway you need a dev to give you the ...
> 
> I guess I am not a dev in this scenario? If not, would that dev be in the approvers section?

@jhixson74 or @patrickdillon should be able to set the label.

**Pull request merged**
