### PR TITLE
Bump Nutanix Prism Go Client dep to c8a2536 to include refactors.

### PR DESCRIPTION
**Pull request by abutcher**
I encountered the following bumping `github.com/nutanix-cloud-native/prism-go-client` in hive to [match the version used by the cloud credential operator](https://github.com/openshift/cloud-credential-operator/blob/7bc6617ac80d7205af5dd2f2d32a7b73d59406ee/go.mod#L30) since [some refactoring has occurred](https://github.com/nutanix-cloud-native/prism-go-client/commit/b758bb855b7e0bc6bc0fb22e4e5557878832b0d7) in the Nutanix Prism Go Client module and the installer is vendoring a previous version.
 
```
➜  hive (nutanix) ✗ go mod tidy          
go: finding module for package github.com/nutanix-cloud-native/prism-go-client/pkg/nutanix/v3
go: finding module for package github.com/nutanix-cloud-native/prism-go-client/pkg/utils
go: finding module for package github.com/nutanix-cloud-native/prism-go-client/pkg/nutanix
github.com/openshift/hive/contrib/pkg/deprovision imports
	github.com/openshift/installer/pkg/destroy/nutanix imports
	github.com/nutanix-cloud-native/prism-go-client/pkg/nutanix/v3: package github.com/nutanix-cloud-native/prism-go-client/pkg/nutanix/v3 provided by github.com/nutanix-cloud-native/prism-go-client at latest version v0.2.0 but not at required version v0.2.1-0.20220804130801-c8a253627c64
github.com/openshift/hive/contrib/pkg/deprovision imports
	github.com/openshift/installer/pkg/types/nutanix imports
	github.com/nutanix-cloud-native/prism-go-client/pkg/nutanix: package github.com/nutanix-cloud-native/prism-go-client/pkg/nutanix provided by github.com/nutanix-cloud-native/prism-go-client at latest version v0.2.0 but not at required version v0.2.1-0.20220804130801-c8a253627c64
github.com/openshift/hive/contrib/pkg/deprovision imports
	github.com/openshift/installer/pkg/types/nutanix imports
	github.com/nutanix-cloud-native/prism-go-client/pkg/utils: package github.com/nutanix-cloud-native/prism-go-client/pkg/utils provided by github.com/nutanix-cloud-native/prism-go-client at latest version v0.2.0 but not at required version v0.2.1-0.20220804130801-c8a253627c64
```

This PR bumps the installer's vendor to the same version of the Nutanix Prism Go Client used by the cloud credential operator and modifies `imports` to reflect the refactored, more shallow import paths.

/cc @thunderboltsid

### CODE REVIEW

**Comment by jstuever** [comment]
/hold
Let's at least see the e2e-nutanix test pass.

**Comment by abutcher** [comment]
@jstuever needs a lgtm after rebasing

**Pull request merged**
