### PR TITLE
Bump worker resources

### LINKED ISSUE #1860: Worker resources not sufficient
With recent versions of operators, worker node resources are no longer sufficient for prometheus pods to start:

```
$ oc describe pods/prometheus-k8s-0 -n openshift-monitoring
Name:               prometheus-k8s-0
Namespace:          openshift-monitoring
Priority:           2000000000
PriorityClassName:  system-cluster-critical
Node:               <none>
Labels:             app=prometheus
                    controller-revision-hash=prometheus-k8s-59556679f4
                    prometheus=k8s
                    statefulset.kubernetes.io/pod-name=prometheus-k8s-0
Annotations:        openshift.io/scc: restricted
Status:             Pending
IP:                 
Controlled By:      StatefulSet/prometheus-k8s
Containers:
  prometheus:
    Image:      registry.svc.ci.openshift.org/origin/4.2-2019-06-17-063354@sha256:e01303a1d00dc4b1d804d7a787db492ac2ac31e35d1f2b7ded63d53f02633caf
    Port:       <none>
    Host Port:  <none>
    Args:
      --web.console.templates=/etc/prometheus/consoles
      --web.console.libraries=/etc/prometheus/console_libraries
      --config.file=/etc/prometheus/config_out/prometheus.env.yaml
      --storage.tsdb.path=/prometheus
      --storage.tsdb.retention.time=15d
      --web.enable-lifecycle
      --storage.tsdb.no-lockfile
      --web.external-url=https://prometheus-k8s-openshift-monitoring.apps.tt.testing/
      --web.route-prefix=/
      --web.listen-address=127.0.0.1:9090
    Requests:
      cpu:        200m
      memory:     1Gi
    Environment:  <none>
    Mounts:
      /etc/prometheus/config_out from config-out (ro)
      /etc/prometheus/configmaps/kubelet-serving-ca-bundle from configmap-kubelet-serving-ca-bundle (ro)
      /etc/prometheus/configmaps/serving-certs-ca-bundle from configmap-serving-certs-ca-bundle (ro)
      /etc/prometheus/rules/prometheus-k8s-rulefiles-0 from prometheus-k8s-rulefiles-0 (rw)
      /etc/prometheus/secrets/kube-etcd-client-certs from secret-kube-etcd-client-certs (ro)
      /etc/prometheus/secrets/kube-rbac-proxy from secret-kube-rbac-proxy (ro)
      /etc/prometheus/secrets/prometheus-k8s-htpasswd from secret-prometheus-k8s-htpasswd (ro)
      /etc/prometheus/secrets/prometheus-k8s-proxy from secret-prometheus-k8s-proxy (ro)
      /etc/prometheus/secrets/prometheus-k8s-tls from secret-prometheus-k8s-tls (ro)
      /prometheus from prometheus-k8s-db (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from prometheus-k8s-token-tdkg5 (ro)
  prometheus-config-reloader:
    Image:      registry.svc.ci.openshift.org/origin/4.2-2019-06-17-063354@sha256:5b2c2b273c14348764b2da89a092df7ecb9dd6cdf8ae473ffd6c886bdd6101b3
    Port:       <none>
    Host Port:  <none>
    Command:
      /bin/prometheus-config-reloader
    Args:
      --log-format=logfmt
      --reload-url=http://localhost:9090/-/reload
      --config-file=/etc/prometheus/config/prometheus.yaml.gz
      --config-envsubst-file=/etc/prometheus/config_out/prometheus.env.yaml
    Limits:
      cpu:     100m
      memory:  25Mi
    Requests:
      cpu:     100m
      memory:  25Mi
    Environment:
      POD_NAME:  prometheus-k8s-0 (v1:metadata.name)
    Mounts:
      /etc/prometheus/config from config (rw)
      /etc/prometheus/config_out from config-out (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from prometheus-k8s-token-tdkg5 (ro)
  rules-configmap-reloader:
    Image:      registry.svc.ci.openshift.org/origin/4.2-2019-06-17-063354@sha256:ec19558b9d4d2e50e820219d1d9199a55fdbdbef2c8bdb04f7f38b13c75f825d
    Port:       <none>
    Host Port:  <none>
    Args:
      --webhook-url=http://localhost:9090/-/reload
      --volume-dir=/etc/prometheus/rules/prometheus-k8s-rulefiles-0
    Limits:
      cpu:     100m
      memory:  25Mi
    Requests:
      cpu:        100m
      memory:     25Mi
    Environment:  <none>
    Mounts:
      /etc/prometheus/rules/prometheus-k8s-rulefiles-0 from prometheus-k8s-rulefiles-0 (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from prometheus-k8s-token-tdkg5 (ro)
  prometheus-proxy:
    Image:      registry.svc.ci.openshift.org/origin/4.2-2019-06-17-063354@sha256:f73bfe880c1caaf4a0a03cb6ffdb58baab2170e12ebafab26ea8e6abba66b3f4
    Port:       9091/TCP
    Host Port:  0/TCP
    Args:
      -provider=openshift
      -https-address=:9091
      -http-address=
      -email-domain=*
      -upstream=http://localhost:9090
      -htpasswd-file=/etc/proxy/htpasswd/auth
      -openshift-service-account=prometheus-k8s
      -openshift-sar={"resource": "namespaces", "verb": "get"}
      -openshift-delegate-urls={"/": {"resource": "namespaces", "verb": "get"}}
      -tls-cert=/etc/tls/private/tls.crt
      -tls-key=/etc/tls/private/tls.key
      -client-secret-file=/var/run/secrets/kubernetes.io/serviceaccount/token
      -cookie-secret-file=/etc/proxy/secrets/session_secret
      -openshift-ca=/etc/pki/tls/cert.pem
      -openshift-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      -skip-auth-regex=^/metrics
    Requests:
      cpu:        10m
      memory:     20Mi
    Environment:  <none>
    Mounts:
      /etc/proxy/htpasswd from secret-prometheus-k8s-htpasswd (rw)
      /etc/proxy/secrets from secret-prometheus-k8s-proxy (rw)
      /etc/tls/private from secret-prometheus-k8s-tls (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from prometheus-k8s-token-tdkg5 (ro)
  kube-rbac-proxy:
    Image:      registry.svc.ci.openshift.org/origin/4.2-2019-06-17-063354@sha256:2faeacd3cdd6dcabffce0266251d0a6930020155e85764a1434e26769fa33f25
    Port:       9092/TCP
    Host Port:  0/TCP
    Args:
      --secure-listen-address=0.0.0.0:9092
      --upstream=http://127.0.0.1:9095
      --config-file=/etc/kube-rbac-proxy/config.yaml
      --tls-cert-file=/etc/tls/private/tls.crt
      --tls-private-key-file=/etc/tls/private/tls.key
      --tls-cipher-suites=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
      --logtostderr=true
      --v=10
    Requests:
      cpu:        10m
      memory:     20Mi
    Environment:  <none>
    Mounts:
      /etc/kube-rbac-proxy from secret-kube-rbac-proxy (rw)
      /etc/tls/private from secret-prometheus-k8s-tls (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from prometheus-k8s-token-tdkg5 (ro)
  prom-label-proxy:
    Image:      registry.svc.ci.openshift.org/origin/4.2-2019-06-17-063354@sha256:ec96c3efbfb587a4b1c9693d1eabb2a26bf66b6c4fad9c9a500c814a503d7263
    Port:       <none>
    Host Port:  <none>
    Args:
      --insecure-listen-address=127.0.0.1:9095
      --upstream=http://127.0.0.1:9090
      --label=namespace
    Requests:
      cpu:        10m
      memory:     20Mi
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from prometheus-k8s-token-tdkg5 (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  config:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  prometheus-k8s
    Optional:    false
  config-out:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:  
  prometheus-k8s-rulefiles-0:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      prometheus-k8s-rulefiles-0
    Optional:  false
  secret-kube-etcd-client-certs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kube-etcd-client-certs
    Optional:    false
  secret-prometheus-k8s-tls:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  prometheus-k8s-tls
    Optional:    false
  secret-prometheus-k8s-proxy:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  prometheus-k8s-proxy
    Optional:    false
  secret-prometheus-k8s-htpasswd:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  prometheus-k8s-htpasswd
    Optional:    false
  secret-kube-rbac-proxy:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kube-rbac-proxy
    Optional:    false
  configmap-serving-certs-ca-bundle:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      serving-certs-ca-bundle
    Optional:  false
  configmap-kubelet-serving-ca-bundle:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      kubelet-serving-ca-bundle
    Optional:  false
  prometheus-k8s-db:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:  
  prometheus-k8s-token-tdkg5:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  prometheus-k8s-token-tdkg5
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  beta.kubernetes.io/os=linux
Tolerations:     node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age                From               Message
  ----     ------            ----               ----               -------
  Warning  FailedScheduling  3s (x27 over 37m)  default-scheduler  0/2 nodes are available: 1 Insufficient cpu, 1 Insufficient memory, 1 node(s) had taints that the pod didn't tolerate.
```

# Version

```console
$ openshift-install version
bin/openshift-install unreleased-master-1126-g158835dde00eec3f4d399a5b8d18aa1fedccdb3c
built from commit 158835dde00eec3f4d399a5b8d18aa1fedccdb3c
release image registry.svc.ci.openshift.org/origin/release:4.2
```

# Platform (aws|libvirt|openstack):

libvirt

### PR DESCRIPTION
**Pull request by zeenix**
Bump up worker resources so that all the prometheus pods can start.

Fixes #1860.

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
Do you have a list of resource requests and limits on current cluster that show what's the current state.., not just the effect that prom pods are failing.. ?

**Comment by zeenix** [comment]
> Do you have a list of resource requests and limits on current cluster that show what's the current state.., not just the effect that prom pods are failing.. ?

I just have the

```
  Warning  FailedScheduling  3s (x27 over 37m)  default-scheduler  0/2 nodes are available: 1 Insufficient cpu, 1 Insufficient memory, 1 node(s) had taints that the pod didn't tolerate.
```
event from prometheus-k8s pods: https://github.com/openshift/installer/issues/1860#issue-457025258 . Please let me know if there is other specific info you'd like me to gather.

**Pull request merged**
