### PR TITLE
IBMCloud: Pull in latest openshift/api changes

### PR DESCRIPTION
**Pull request by cjschaef**
IBMCloud DNS support requires a change to PlatformStatus, which
is now available in the openshift/api.

### CODE REVIEW

**Comment by cjschaef** [comment]
Having issues rebasing and trying to pull in these changes now.
Will continue to investigate why `go mod` is not updating the files and vendor as expected after rebasing off  latest `master`

**Comment by cjschaef** [comment]
/retitle Bug 2094891: IBMCloud: Pull in latest openshift/api changes

**Comment by cjschaef** [comment]
Some more overwhelmed CI workloads
`state: waiting, reason: "CreateContainerError", message: "context deadline exceeded"`

Will look at re-kicking the tests tomorrow hopefully.

**Comment by cjschaef** [comment]
I've opened a separate PR to update the Kubernetes components first (required for kube-openapi update)
https://github.com/openshift/installer/pull/6165

Then can rebase and rework this PR to pull in the `openshift/api` changes for IBM Cloud DNS CRN support (`installconfig.platform.ibmcloud.platformstatus.dnsInstanceCRN`)

**Comment by cjschaef** [comment]
Will need to re-kick the tests, since the CI pod timeouts have prevented tests from running.
`Job execution failed: Pod pending timeout.`

**Comment by cjschaef** [comment]
`e2e-ibmcloud` requires a fix to the MAPI repo/image
https://github.com/openshift/machine-api-provider-ibmcloud/pull/3

**Review by barbacbd — COMMENTED** [review]
/lgtm

We could consider updating this further since there are newer commits.

**Review by barbacbd — COMMENTED** [review]
Can you alter the commit to split the go.mod and go.sum into a single commit and the vendor file changes should be made into its own commit

**Comment by cjschaef** [comment]
I've updated the `openshift/api` commit and removed the vendor changes, will open a new PR with those changes once this merges.

**Review by barbacbd — COMMENTED** [review]
/lgtm

**Comment by cjschaef** [comment]
Removing my initial hold, now that required PR has merged and I've updated/rebased the PR
/unhold

**Comment by MayXuQQ** [comment]
test with the pre-merge build [registry.build05.ci.openshift.org/ci-ln-vr03g02/release:latest](https://storage.googleapis.com/origin-ci-test/logs/release-openshift-origin-installer-launch-gcp-modern/1557928866012467200/build-log.txt)

> platform:
>   ibmcloud:
>     computeSubnets:
>     - maxu-ibm-58gcf-subnet-compute-eu-gb-1
>     - maxu-ibm-58gcf-subnet-compute-eu-gb-2
>     - maxu-ibm-58gcf-subnet-compute-eu-gb-3
>     controlPlaneSubnets:
>     - maxu-ibm-58gcf-subnet-control-plane-eu-gb-1
>     - maxu-ibm-58gcf-subnet-control-plane-eu-gb-2
>     - maxu-ibm-58gcf-subnet-control-plane-eu-gb-3
>     region: eu-gb
>     resourceGroupName: maxu-ibm-58gcf
>     vpcName: maxu-ibm-58gcf-vpc
> publish: Internal


ERROR failed to fetch Master Machines: failed to load asset "Install Config": failed to create install config: invalid "install-config.yaml" file: publish: Invalid value: "Internal": Internal publish strategy is not supported on "ibmcloud" platform

**Comment by MayXuQQ** [comment]
needs to be rebased to branch master

**Comment by cjschaef** [comment]
`Pod pending timeout.`
/retest

**Review by MayXuQQ — CHANGES_REQUESTED** [review]
pre-merge checking with 
`publish: Internal`
install failed. 
ERROR failed to fetch Metadata: failed to load asset "Install Config": failed to create install config: invalid "install-config.yaml" file: publish: Invalid value: "Internal": Internal publish strategy is not supported on "ibmcloud" platform

**Comment by cjschaef** [comment]
It looks like I need to update `vendor` once again on this PR
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_installer/6056/pull-ci-openshift-installer-master-verify-vendor/1562064354239582208

I will look at getting that done and force pushing once again.

**Comment by r4f4** [comment]
/hold
until vendor is fixed

**Review by MayXuQQ — COMMENTED** [review]
skip review, will check with feature

**Comment by cjschaef** [comment]
I investigated the [`e2e-ibmcloud` failure](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_installer/6056/pull-ci-openshift-installer-master-e2e-ibmcloud/1562148413049409536), and it appears to be an issue with the IBM CSI driver. I plan to open a Jira Bug for that issue.

Otherwise, attempting to retrigger pod timeouts.

/retest

**Comment by r4f4** [comment]
I see the main cloud providers passed the tests e2e-(azure, aws, gcp, metal-ipi, vsphere, ovirt). I think that could be enough proof the `openshift/api` bump is not causing problems. I think it's pointless to keep retrying tests, so after the current run we could consider skipping/overriding them.

**Pull request merged**
