### PR TITLE
Bug 1974598: OpenStack: Optimize cluster deletion

### PR DESCRIPTION
**Pull request by mandre**
Previously each destroy function would exit on the first conflict and
it was expected to retry on a next iteration, hoping that in the mean
time the conflict that prevented removal of the resource was fixed.
While this strategy works, it is also slower then necessary. A better
strategy is to try deleting all resources and ignore the ones that have
conflicts. On the next iteration there will be less conflicts.

This patch was tested on a openstack cluster with openshiftSDN, and
we observed a 37% faster cluster deletion. I expect the performance
boost to be significantly higher for clusters using kuryr.

### CODE REVIEW

**Comment by staebler** [comment]
Nice. This matches more closely the desired destroy behavior that we am for with cloud platforms.

**Comment by mandre** [comment]
/hold
I'd like to get numbers for kuryr cluster deletion. If the performance gain is really amazing we might consider backporting the change, in which case I'd like a BZ for it.

**Comment by mandre** [comment]
My test on a kuryr cluster shows a 24% improvement on the time it takes to delete a cluster, 14m37s vs 19m14s. Not as impressive as I hoped it would be but still nice to take.

**Comment by EmilienM** [comment]
```
INFO Time elapsed: 8m22s
```

Wow !!

/lgtm
/approve

**Comment by mandre** [comment]
/retest
e2e-openstack should be working now, thanks to https://github.com/openshift/release/pull/19272

**Pull request merged**
