### PR TITLE
openstack: Revert Gophercloud workaround

### PR DESCRIPTION
**Pull request by pierreprinetti**
With the bump to Gophercloud v1.1.1, the library should be able to handle HTTP status 204 responses without `content-type` without erroring. The workaround that was in place to force contentful responses can then be removed.

Follows up on https://github.com/openshift/installer/pull/6615

### CODE REVIEW

**Review by mandre — COMMENTED** [review]
Thanks @pierreprinetti.
/lgtm

**Comment by pierreprinetti** [comment]
rebased. CC @mandre

**Review by mandre — COMMENTED** [review]
/lgtm

**Comment by mandre** [comment]
/hold
We'll want v1.1.1 instead.

**Review by mandre — COMMENTED** [review]
Thanks!
/lgtm
/hold cancel

**Review by mandre — COMMENTED** [review]
/lgtm

**Comment by pierreprinetti** [comment]
/hold
Let's take the opportunity and wait for Gophercloud v1.1.2, which will come with a fix to all endpoints and not only to container listing

**Comment by pierreprinetti** [comment]
/hold cancel
hey actually v1.1.1 already fixes object listing. Let's merge! Thank you @mandre for the heads-up

**Comment by pierreprinetti** [comment]
/hold
This should also revert https://github.com/openshift/installer/pull/6707 (which hasn't merged yet)

**Review by mandre — COMMENTED** [review]
/lgtm

**Review by mandre — COMMENTED** [review]
/lgtm

**Review by mandre — COMMENTED** [review]
Last LGTM :crossed_fingers: 
/lgtm

**Comment by mandre** [comment]
e2e-azure-ovn is apparently broken since Dec 10, can we consider overriding it since it should not be impacted by this change?

https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/pull-ci-openshift-installer-master-e2e-azure-ovn

**Comment by pierreprinetti** [comment]
@mandre 
> e2e-azure-ovn is apparently broken since Dec 10, can we consider overriding it since it should not be impacted by this change?

@patrickdillon has a more definitive solution here: https://github.com/openshift/release/pull/34883

**Pull request merged**
