### PR TITLE
bootkube: remove unused kube-core secrets

### PR DESCRIPTION
**Pull request by sttts**
Since we remove kube-core from bootstrapping, these secrets are unused.

Fixes https://github.com/openshift/cluster-kube-apiserver-operator/issues/96

### CODE REVIEW

**Comment by wking** [comment]
This may also allow some pruning [here][1].  I can check in an hour if nobody beats me to it ;).

**Comment by wking** [comment]
Pushing this prune back up the call chain was a bit more difficult than I expected.  I've pushed d11305a with what I've come up with so far.  Can you give that a look over and squash it in here if it looks right to you (you can `git pull https://github.com/wking/openshift-installer.git unused-kube-core-secrets-fixup` to get the commit locally).  Then we'll see if it passes CI ;).

Moving forward, it would be nice to make these links to external operators easier to audit.  Maybe we can add comments linking to the operator docs for the secret we're providing?  Then we know which consumer(s) need the secret, and we can go check and see if they have made changes to their requirements (e.g. deprecating fields, or completely dropping the secret).

**Comment by wking** [comment]
>  I've pushed d11305a with what I've come up with so far. 


Based on [feedback there][1], I've pushed d11305a -> 8ebcaf0.  That restores some TLS assets (they're [consumed by `render` calls in `bootkube.sh`][2]).  I still think we can drop `OpenshiftAPIServerCertKey` (or at least, I haven't found or been told about a consumer yet).  And I think we can still drop a bunch of things from our manifest rendering.

There's still some [opaque-to-me][3] stuff going on with `/etc/ssl/etcd/ca.crt`, so you may not want that part of my fixup commit (if you want any of it ;).  I'd still like to know how that asset was getting out to the masters though.

[1]: https://github.com/openshift/installer/commit/d11305ae93fa49086a5f8e83e0d9a764160bae09#r31105842
[2]: https://github.com/openshift/installer/commit/d11305ae93fa49086a5f8e83e0d9a764160bae09#r31123280
[3]: https://github.com/openshift/installer/commit/d11305ae93fa49086a5f8e83e0d9a764160bae09#commitcomment-31124053

**Comment by abhinavdahiya** [comment]
/lgtm

we can do the cleanup on our end in another PR.

**Pull request merged**
