### PR TITLE
baremetal: update terraform-provider-ironic and use newer API

### PR DESCRIPTION
**Pull request by stbenjam**
With 1.56 of the Ironic API, we can send Ironic the JSON data for a config
drive, rather than a base64-encoded, gzipped ISO9660 image. This avoids
a dependency on the host running the installer to have mkisofs
available.

### CODE REVIEW

**Comment by stbenjam** [comment]
FYI, regarding the issue you encountered earlier

/cc @dhellmann

**Comment by metal3ci** [comment]
Build SUCCESS, see build http://10.8.144.11:8080/job/dev-tools/1273/

**Comment by abhinavdahiya** [comment]
This should be good to merge towards 4.4 now.

**Pull request merged**
