### PR TITLE
pkg/destroy/aws: 10-second lower bound for deletion period

### PR DESCRIPTION
**Pull request by wking**
Currently this is a somewhat-warm loop while we wait for Amazon to reap dependencies that have already had successful "deleted" calls.  For example:

```console
$ curl -s  https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_installer/1346/pull-ci-openshift-installer-master-e2e-aws/4324/artifacts/e2e-aws/installer/.openshift_install.log| grep '[Dd]elet.*vpc-08dc4aea3c1c2db8f' | tail -n4
time="2019-03-01T15:21:47Z" level=debug msg="deleting arn:aws:ec2:us-east-1:460538899914:vpc/vpc-08dc4aea3c1c2db8f: DependencyViolation: The vpc 'vpc-08dc4aea3c1c2db8f' has dependencies and cannot be deleted.\n\tstatus code: 400, request id: 0c437bd8-ed5f-4989-abda-987aefdac6ce"
time="2019-03-01T15:21:50Z" level=debug msg="deleting arn:aws:ec2:us-east-1:460538899914:vpc/vpc-08dc4aea3c1c2db8f: DependencyViolation: The vpc 'vpc-08dc4aea3c1c2db8f' has dependencies and cannot be deleted.\n\tstatus code: 400, request id: 04085023-f9ca-442b-85a7-ab4a242604e4"
time="2019-03-01T15:21:52Z" level=debug msg="deleting arn:aws:ec2:us-east-1:460538899914:vpc/vpc-08dc4aea3c1c2db8f: DependencyViolation: The vpc 'vpc-08dc4aea3c1c2db8f' has dependencies and cannot be deleted.\n\tstatus code: 400, request id: 1d3f92e3-1e7e-432f-ae4d-be47b5fab722"
time="2019-03-01T15:21:54Z" level=info msg=Deleted arn="arn:aws:ec2:us-east-1:460538899914:vpc/vpc-08dc4aea3c1c2db8f" id=vpc-08dc4aea3c1c2db8f
```

which shows an ~2 second period during that time.  So this should be an ~5x reduction for that phase of deletion.

In a quiet account, a few DependencyViolation failures aren't a big deal.  But in our CI account we can create 600+ clusters a day, and Amazon starts giving us `RequestLimitExceeded` responses as we pound away on multiple deletions in parallel.

The downsides to limiting this loop are:

* For resources that are cleaned up immediately, we are slowing our walk through the dependency graph.  But the graph isn't that deep, so I'm not worried about this at the moment.

* Waiting gives the cluster time to self-heal.  For example, after we terminate an instance, the remaining instances may notice and create a replacement.  And while we'll attempt to terminate that full generation in the current round, if we wait too long between rounds the replacement machines may be alive enough to be able to launch grandchildren.  But 10 seconds seems short enough that we don't have to worry about machines going from boot to child-spawning in that window.

From [the `PollImmediateInfinite` docs][1]:

> Some intervals may be missed if the condition takes too long or the time window is too short.

which is what we want, because we're only attempting each resource once per cycle.  If the first round takes 40 seconds, and the second takes 5, we still want to sleep 5 seconds instead of executing immediately.

[1]: https://godoc.org/k8s.io/apimachinery/pkg/util/wait#PollImmediateInfinite

### CODE REVIEW

**Comment by wking** [comment]
vpc

Data from CI that I'm trying to address with this pull request.  All of the errors are `RequestLimitExceeded` or `DependencyViolation` except for a single `InvalidVpcID.NotFound` at 2019-03-02T06:07:58Z.  My expectation is that we get a ~4x reduction in `DependencyViolation` which should almost completely eliminate `RequestLimitExceeded` (assuming the rate-limits are per-resource-type, I'm not sure how that works yet).

**Comment by wking** [comment]
It's working:

```console
$ curl -s https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_installer/1352/pull-ci-openshift-installer-master-e2e-aws/4341/artifacts/e2e-aws/installer/.openshift_install.log | grep '[Dd]elet.*vpc-08e52650d73916cfe' | tail -n3
time="2019-03-04T08:07:53Z" level=debug msg="deleting arn:aws:ec2:us-east-1:460538899914:vpc/vpc-08e52650d73916cfe: DependencyViolation: The vpc 'vpc-08e52650d73916cfe' has dependencies and cannot be deleted.\n\tstatus code: 400, request id: 4f763067-2bd1-4cf2-9589-6e46816b655c"
time="2019-03-04T08:08:03Z" level=debug msg="deleting arn:aws:ec2:us-east-1:460538899914:vpc/vpc-08e52650d73916cfe: DependencyViolation: The vpc 'vpc-08e52650d73916cfe' has dependencies and cannot be deleted.\n\tstatus code: 400, request id: 4a8425ad-0b14-47a7-bd32-fd5337c01c9a"
time="2019-03-04T08:08:13Z" level=info msg=Deleted arn="arn:aws:ec2:us-east-1:460538899914:vpc/vpc-08e52650d73916cfe" id=vpc-08e52650d73916cfe
```

**Comment by abhinavdahiya** [comment]
> vpc
> 
> Data from CI that I'm trying to address with this pull request. All of the errors are `RequestLimitExceeded` or `DependencyViolation` except for a single `InvalidVpcID.NotFound` at 2019-03-02T06:07:58Z. My expectation is that we get a ~4x reduction in `DependencyViolation` which should almost completely eliminate `RequestLimitExceeded` (assuming the rate-limits are per-resource-type, I'm not sure how that works yet).

https://forums.aws.amazon.com/thread.jspa?messageID=720883 or https://docs.aws.amazon.com/AWSEC2/latest/APIReference/query-api-troubleshooting.html#api-request-rate makes it seem like there are 3 tiers of API calls and these limits are not resource type dependent.

would it be useful to use client side flowcontrol to mimic these 3 tiers ?
https://github.com/kubernetes/client-go/blob/master/util/flowcontrol/throttle.go can be useful.

**Comment by wking** [comment]
> would it be useful to use client side flowcontrol to mimic these 3 tiers ?

Well, the AWS SDK should be very well-behaved, with [the default retryer based on RFC 7231's `Retry-After` header][1].  That seems to be per-request though (so you only get back-off for a given API request if you've had an earlier attempt for that specific request throttled, it doesn't delay subsequent requests).  Something like a [`NewTokenBucketRateLimiter`][2] carried with the client to give us client-side throttling for all our requests (or having multiple tiers of buckets for different classes of requests) would be more proactive.

But this particular PR is less about the throttling itself, and more about AWS's [eventual consistency][3] approach, where, for example, successful NAT-gateway removal does not immediately unblock removal of the dependent subnet.  A more specific approach might be to hard-code per-resource-type consistency times.  For example, "instance removal usually takes around 30 seconds, so don't bother trying to deleted dependencies until that has elapsed", with the time based on:

```console
$ curl -s  https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_installer/1346/pull-ci-openshift-installer-master-e2e-aws/4324/artifacts/e2e-aws/installer/.openshift_install.log | grep -i destroying
...
time="2019-03-01T14:42:02Z" level=debug msg="module.bootstrap.aws_instance.bootstrap: Destroying... (ID: i-0c253c05166dd78b7)"
time="2019-03-01T14:42:12Z" level=debug msg="module.bootstrap.aws_instance.bootstrap: Still destroying... (ID: i-0c253c05166dd78b7, 10s elapsed)"
time="2019-03-01T14:42:22Z" level=debug msg="module.bootstrap.aws_instance.bootstrap: Still destroying... (ID: i-0c253c05166dd78b7, 20s elapsed)"
time="2019-03-01T14:42:32Z" level=debug msg="module.bootstrap.aws_instance.bootstrap: Still destroying... (ID: i-0c253c05166dd78b7, 30s elapsed)"
time="2019-03-01T14:42:35Z" level=debug msg="module.bootstrap.aws_iam_instance_profile.bootstrap: Destroying... (ID: ci-op-n2gv668g-1d3f3-jzfcv-bootstrap-profile)"
...
```

But I don't know how reliable those delays are.

We could follow Terraform and use 10-second sleeps between describe polls for "has the resource deletion gone through?", but for that to be useful, we need more of a dependency graph than we have in our current AWS-destroyer logic.  This PR's 10-second-per-round minimum is the dependency-graph-less version of that, although we are measuring removal with the more-expensive next-generation-delete-attempt vs. cheaper but harder to code up this-generation-describe-attempt.  One potential approach would be to grow more graph logic (e.g. `deleteEC2SubnetsByVPC` with `DescribeSubnets` polling blocking the VPC-deletion attempt, and `deleteEC2NATGatewaysBySubnet` which does the same for `DescribeNatGateways`).  That should allow us to chip away at the problem without having to solve it in one swoop.

Personally, I think this PR is a reasonable starting point for backing off our deleter.  And that I'd like to land it while we work up something with more finesse.  But if you want to shoot for something more elegant now, let me know which direction to head and I'll start in on it.

[1]: https://github.com/openshift/installer/blob/v0.13.1/vendor/github.com/aws/aws-sdk-go/aws/client/default_retryer.go#L85-L103
[2]: https://godoc.org/k8s.io/client-go/util/flowcontrol#NewTokenBucketRateLimiter
[3]: https://docs.aws.amazon.com/AWSEC2/latest/APIReference/query-api-troubleshooting.html#eventual-consistency

**Comment by abhinavdahiya** [comment]
> > would it be useful to use client side flowcontrol to mimic these 3 tiers ?
> 
> Well, the AWS SDK should be very well-behaved, with [the default retryer based on RFC 7231's `Retry-After` header](https://github.com/openshift/installer/blob/v0.13.1/vendor/github.com/aws/aws-sdk-go/aws/client/default_retryer.go#L85-L103). That seems to be per-request though (so you only get back-off for a given API request if you've had an earlier attempt for that specific request throttled, it doesn't delay subsequent requests). Something like a [`NewTokenBucketRateLimiter`](https://godoc.org/k8s.io/client-go/util/flowcontrol#NewTokenBucketRateLimiter) carried with the client to give us client-side throttling for all our requests (or having multiple tiers of buckets for different classes of requests) would be more proactive.
> 
> But this particular PR is less about the throttling itself, and more about AWS's [eventual consistency](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/query-api-troubleshooting.html#eventual-consistency) approach, where, for example, successful NAT-gateway removal does not immediately unblock removal of the dependent subnet. A more specific approach might be to hard-code per-resource-type consistency times. For example, "instance removal usually takes around 30 seconds, so don't bother trying to deleted dependencies until that has elapsed", with the time based on:
> 
> ```
> $ curl -s  https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_installer/1346/pull-ci-openshift-installer-master-e2e-aws/4324/artifacts/e2e-aws/installer/.openshift_install.log | grep -i destroying
> ...
> time="2019-03-01T14:42:02Z" level=debug msg="module.bootstrap.aws_instance.bootstrap: Destroying... (ID: i-0c253c05166dd78b7)"
> time="2019-03-01T14:42:12Z" level=debug msg="module.bootstrap.aws_instance.bootstrap: Still destroying... (ID: i-0c253c05166dd78b7, 10s elapsed)"
> time="2019-03-01T14:42:22Z" level=debug msg="module.bootstrap.aws_instance.bootstrap: Still destroying... (ID: i-0c253c05166dd78b7, 20s elapsed)"
> time="2019-03-01T14:42:32Z" level=debug msg="module.bootstrap.aws_instance.bootstrap: Still destroying... (ID: i-0c253c05166dd78b7, 30s elapsed)"
> time="2019-03-01T14:42:35Z" level=debug msg="module.bootstrap.aws_iam_instance_profile.bootstrap: Destroying... (ID: ci-op-n2gv668g-1d3f3-jzfcv-bootstrap-profile)"
> ...
> ```
> 
> But I don't know how reliable those delays are.
> 
> We could follow Terraform and use 10-second sleeps between describe polls for "has the resource deletion gone through?", but for that to be useful, we need more of a dependency graph than we have in our current AWS-destroyer logic. This PR's 10-second-per-round minimum is the dependency-graph-less version of that, although we are measuring removal with the more-expensive next-generation-delete-attempt vs. cheaper but harder to code up this-generation-describe-attempt. One potential approach would be to grow more graph logic (e.g. `deleteEC2SubnetsByVPC` with `DescribeSubnets` polling blocking the VPC-deletion attempt, and `deleteEC2NATGatewaysBySubnet` which does the same for `DescribeNatGateways`). That should allow us to chip away at the problem without having to solve it in one swoop.
> 
> Personally, I think this PR is a reasonable starting point for backing off our deleter. And that I'd like to land it while we work up something with more finesse. But if you want to shoot for something more elegant now, let me know which direction to head and I'll start in on it.

IMO lets try to introduce client side flow control to make sure we are not hammering the AWS API. but for now if you think this gets us started that feels okay too.

/lgtm

**Pull request merged**
