### PR TITLE
add systemd-resolved section to libvirt docs

### PR DESCRIPTION
**Pull request by kwiesmueller**
This PR adds the steps required to setup DNS on a systemd-resolved based OS when using the libvirt provider.

Thanks to @cfergeau for the assistance resolving this.

### CODE REVIEW

**Comment by kwiesmueller** [comment]
/hold
I just recreated my cluster and the change was gone.
Might really be required as a hook.

**Comment by cfergeau** [comment]
> /hold
> I just recreated my cluster and the change was gone.
> Might really be required as a hook.

The systemd-resolved changes go away when the corresponding libvirt network is destroyed or undefined, and do not come back automatically when it's restarted or recreated. Maybe this is what you saw?

**Comment by kwiesmueller** [comment]
Yes, that's what I saw.
I suppose a hook can reapply them when it comes back?

**Comment by cfergeau** [comment]
> Yes, that's what I saw.
> I suppose a hook can reapply them when it comes back?

A libvirt hook should be usable for that purpose https://www.libvirt.org/hooks.html

**Comment by cfergeau** [comment]
I've attempted to consolidate https://github.com/openshift/installer/pull/4929/ and this PR in https://github.com/openshift/installer/pull/5132 in order to finally update the libvirt documentation for resolvectl.

**Comment by cfergeau** [comment]
> > Yes, that's what I saw.
> > I suppose a hook can reapply them when it comes back?
> 
> A libvirt hook should be usable for that purpose https://www.libvirt.org/hooks.html

I've had success with the hook below. The cluster name needs to be adjusted to match the one you are creating, but apart from this it should be generic. The hook file must be executable to be used by libvirt.

```
$ cat /etc/libvirt/hooks/network

#!/bin/bash

# Change this to the name of the cluster which will be created.
cluster_name="tt"

network_name=$1
operation=$2

if ! [[ "$network_name" =~ ^$cluster_name-.* ]]; then
        # not a network created by openshift-install
        exit 0
fi

net_xml=$(cat)
interface=$(echo $net_xml|xmllint --xpath 'string(/hookData/network/bridge/@name)' -)
domain=$(echo $net_xml | xmllint --xpath 'string(/hookData/network/domain/@name)' -)
ip=$(echo $net_xml | xmllint --xpath 'string(/hookData/network/ip/@address)' -)

if [[ -z "$interface" ]]; then
        exit 1
fi
if [[ -z "$domain" ]]; then
        exit 1
fi
if [[ -z "$ip" ]]; then
        exit 1
fi

case $operation in
        "started")
                /usr/bin/resolvectl domain "$interface" "$ip" ~"$domain"
                /usr/bin/resolvectl dns "$interface" "$ip"
                ;;
esac
```

**Pull request closed without merging**
