### PR TITLE
CORS-3702: Add api and api-int ips to bootstrap node

### PR DESCRIPTION
**Pull request by barbacbd**
** The api and api-int addresses are coming from the capi gcp provider. The addresses must be added to the Load Balancer Config and to the ignition config for the bootstrap node.

### CODE REVIEW

**Review by sadasu — COMMENTED** [review]
What is the format of the API Server IP address in the Cluster Status? Why do we need to do:
```
apiIPAddress := *gcpCluster.Status.Network.APIServerAddress
addressCut := apiIPAddress[strings.LastIndex(apiIPAddress, "/")+1:]
```

**Comment by barbacbd** [comment]
> What is the format of the API Server IP address in the Cluster Status? Could add sample output here? Why do we need to do:
> 
> ```
> apiIPAddress := *gcpCluster.Status.Network.APIServerAddress
> addressCut := apiIPAddress[strings.LastIndex(apiIPAddress, "/")+1:]
> ```

```
WARNING api address: https://www.googleapis.com/compute/v1/projects/openshift-dev-installer/global/addresses/bbarbach-gcp-oa-scc2d-apiserver 
WARNING api int address: https://www.googleapis.com/compute/v1/projects/openshift-dev-installer/regions/us-east1/addresses/bbarbach-gcp-oa-scc2d-api-internal
```

**Comment by sadasu** [comment]
> > What is the format of the API Server IP address in the Cluster Status? Could add sample output here? Why do we need to do:
> > ```
> > apiIPAddress := *gcpCluster.Status.Network.APIServerAddress
> > addressCut := apiIPAddress[strings.LastIndex(apiIPAddress, "/")+1:]
> > ```
> 
> ```
> WARNING api address: https://www.googleapis.com/compute/v1/projects/openshift-dev-installer/global/addresses/bbarbach-gcp-oa-scc2d-apiserver 
> WARNING api int address: https://www.googleapis.com/compute/v1/projects/openshift-dev-installer/regions/us-east1/addresses/bbarbach-gcp-oa-scc2d-api-internal
> ```

We should be able to get to the actual IP address.

**Comment by barbacbd** [comment]
> > > What is the format of the API Server IP address in the Cluster Status? Could add sample output here? Why do we need to do:
> > > ```
> > > apiIPAddress := *gcpCluster.Status.Network.APIServerAddress
> > > addressCut := apiIPAddress[strings.LastIndex(apiIPAddress, "/")+1:]
> > > ```
> > 
> > 
> > ```
> > WARNING api address: https://www.googleapis.com/compute/v1/projects/openshift-dev-installer/global/addresses/bbarbach-gcp-oa-scc2d-apiserver 
> > WARNING api int address: https://www.googleapis.com/compute/v1/projects/openshift-dev-installer/regions/us-east1/addresses/bbarbach-gcp-oa-scc2d-api-internal
> > ```
> 
> We should be able to get to the actual IP address.

@sadasu We do get the actual IP address. You asked what the output above was. I Provided that output, but if you look at the changes to the PR we then take that information and query the API to get the IP Address from the compute address.

**Comment by sadasu** [comment]
> > > > What is the format of the API Server IP address in the Cluster Status? Could add sample output here? Why do we need to do:
> > > > ```
> > > > apiIPAddress := *gcpCluster.Status.Network.APIServerAddress
> > > > addressCut := apiIPAddress[strings.LastIndex(apiIPAddress, "/")+1:]
> > > > ```
> > > 
> > > 
> > > ```
> > > WARNING api address: https://www.googleapis.com/compute/v1/projects/openshift-dev-installer/global/addresses/bbarbach-gcp-oa-scc2d-apiserver 
> > > WARNING api int address: https://www.googleapis.com/compute/v1/projects/openshift-dev-installer/regions/us-east1/addresses/bbarbach-gcp-oa-scc2d-api-internal
> > > ```
> > 
> > 
> > We should be able to get to the actual IP address.
> 
> @sadasu We do get the actual IP address. You asked what the output above was, so I provided that output but maybe I should have provided the other data too. If you look at the changes to the PR we then take that information above and query the API to get the IP Address from the compute address.

Thanks! That is neat.

**Comment by sadasu** [comment]
/retitle CORS-3702: Add api and api-int ips to bootstrap node

**Pull request merged**
