### PR TITLE
aws/permissions: Add s3:GetBucketObjectLockConfiguration to pre-flight checks

### PR DESCRIPTION
**Pull request by wking**
And alphabetize this section.  The new permission [avoids][1]:

```
error getting S3 Bucket Object Lock configuration: AccessDenied
```

which came in with our Terraform bump from d1c17b7f83 (#1442).

[1]: https://github.com/terraform-providers/terraform-provider-aws/issues/7550

### CODE REVIEW

**Comment by wking** [comment]
From @csrwng:

> btw, install is progressing now with the new permission

so I don't think we're missing anything else.  It would be nice to have CI coverage to ensure that our set of required permissions was sufficient (even if it would be hard to ensure it was minimal), but I'm punting all of that to follow-up work.

**Comment by abhinavdahiya** [comment]
```
Failing tests:

[Feature:DeploymentConfig] deploymentconfigs when run iteratively [Conformance] should only deploy the last deployment [Suite:openshift/conformance/parallel/minimal]
```

/retest

**Comment by wking** [comment]
[e2e-aws][1]:

```
level=fatal msg="waiting for Kubernetes API: context deadline exceeded"
```

/retest

[1]: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_installer/1491/pull-ci-openshift-installer-master-e2e-aws/4773

**Comment by wking** [comment]
[e2e-aws]:

```
Flaky tests:

[sig-cli] Kubectl client [k8s.io] Kubectl logs should be able to retrieve and filter logs  [Conformance] [Suite:openshift/conformance/parallel/minimal] [Suite:k8s]

Failing tests:

[Feature:Platform] Managed cluster should have no crashlooping pods in core namespaces over two minutes [Suite:openshift/conformance/parallel]
```

/retest

[1]: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_installer/1491/pull-ci-openshift-installer-master-e2e-aws/4775/build-log.txt

**Pull request merged**
