### PR TITLE
CORS-3574: [WIP] Azure: Make CAPI default install for Azure

### PR DESCRIPTION
**Pull request by jhixson74**
https://issues.redhat.com/browse/CORS-3574

### CODE REVIEW

**Review by r4f4 — CHANGES_REQUESTED** [review]
You may want to also update `pkg/infrastructure/platform/platform_altinfra.go`

This change is not enough to make Azure the default. As is, no manifests are being generated since [they are also gated](https://github.com/openshift/installer/blob/master/pkg/asset/manifests/clusterapi/cluster.go#L75-L78).

You need to move Azure to the default feature set in openshift/api first. See https://github.com/openshift/api/pull/1892.

**Comment by patrickdillon** [comment]
> You need to move Azure to the default feature set in openshift/api first. See [openshift/api#1892](https://github.com/openshift/api/pull/1892).

Right, I don't think we're ready to remove the feature gate yet. The process should actually be to first promote to [the tech preview feature set in the API](https://github.com/openshift/api/pull/1880). Now that installs are stable, we can do that and probably should do that today. technically we will be breaking techpreview private installs etc, but I don't think anybody's using that.

**Comment by r4f4** [comment]
> Right, I don't think we're ready to remove the feature gate yet.

/hold

**Comment by jhixson74** [comment]
> > You need to move Azure to the default feature set in openshift/api first. See [openshift/api#1892](https://github.com/openshift/api/pull/1892).
> 
> Right, I don't think we're ready to remove the feature gate yet. The process should actually be to first promote to [the tech preview feature set in the API](https://github.com/openshift/api/pull/1880). Now that installs are stable, we can do that and probably should do that today. technically we will be breaking techpreview private installs etc, but I don't think anybody's using that.

This was meant to be a WIP. I forgot to label it as such. Sorry for the noise.

**Pull request closed without merging**
