### PR TITLE
 asset/manifests: update status of Infrastructure

### PR DESCRIPTION
**Pull request by abhinavdahiya**
This updates the `Infrastructure.config.openshift.io` object to catch up with [1].

Machine Config Operator uses the `APIServerURL` to point the kubelet on machines to apiserver, and `EtcdDiscoveryDomain` to setup the etcd
members to bootstrap the etcd cluster using dns discovery [2].

This is required as Machine Config Operator currently uses the `cluster-config-v1` to creates these values and as `cluster-config-v1` is getting deprecated [3], Machine Config Operator will move to
using the status of `Infrastructure.config.openshift.io` for sourcing that information.

[1]: openshift/api#189
[2]: https://github.com/etcd-io/etcd/blob/583763261f1c843e07c1bf7fea5fb4cfb684fe87/Documentation/op-guide/clustering.md#dns-discovery
[3]: #680

### CODE REVIEW

**Comment by wking** [comment]
[e2e-aws][1]:

```
Failing tests:

[Feature:Prometheus][Conformance] Prometheus when installed on the cluster should report telemetry if a cloud.openshift.com token is present [Suite:openshift/conformance/parallel/minimal]
```

But the telemetry folks just fixed a config issue, so...

/retest

[1]: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_installer/1155/pull-ci-openshift-installer-master-e2e-aws/3262/build-log.txt

**Comment by wking** [comment]
[e2e-aws][1]:

```
Failing tests:

[sig-apps] StatefulSet [k8s.io] Basic StatefulSet functionality [StatefulSetBasic] should adopt matching orphans and release non-matching pods [Suite:openshift/conformance/parallel] [Suite:k8s]
[sig-apps] StatefulSet [k8s.io] Basic StatefulSet functionality [StatefulSetBasic] should provide basic identity [Suite:openshift/conformance/parallel] [Suite:k8s]
```

both with panics :p.  Just in case they're also flakes...

/retest

[1]: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_installer/1155/pull-ci-openshift-installer-master-e2e-aws/3278/build-log.txt

**Comment by wking** [comment]
The `should provide basic identity` panic has shown up in around 1/6 of [recent update-payload promotion checks][1], so flakiness confirmed.  `should adopt matching orphans...` seems more stable.  And I hear these will be fixed once we get a RHCOS with a 1.12 kubelet, but I'm not sure how close we are to that.

[1]: https://testgrid.k8s.io/redhat-openshift-release-blocking#redhat-release-openshift-origin-installer-e2e-aws-4.0&sort-by-flakiness=&show-stale-tests=&exclude-non-failed-tests=10

**Comment by wking** [comment]
[e2e-aws][1]:

```
Flaky tests:

[sig-network] Services should serve multiport endpoints from pods  [Conformance] [Suite:openshift/conformance/parallel/minimal] [Suite:k8s]

Failing tests:

[sig-apps] StatefulSet [k8s.io] Basic StatefulSet functionality [StatefulSetBasic] should provide basic identity [Suite:openshift/conformance/parallel] [Suite:k8s]
```

/retest

[1]: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_installer/1155/pull-ci-openshift-installer-master-e2e-aws/3280/build-log.txt

**Comment by wking** [comment]
Needs a rebase.

**Comment by abhinavdahiya** [comment]
rebase around #1132

**Comment by abhinavdahiya** [comment]
ping @wking

**Pull request merged**
