### PR TITLE
OPRUN-3588: Add OperatorLifecycleManagerV1 capability

### PR DESCRIPTION
**Pull request by everettraven**
## Description
Updates the `InstallConfig` `.capabilities.additionalEnabledCapabilities` to add the `OperatorLifecycleManagerV1` capability.

Updated openshift/api, openshift/library-go, openshift/client-go to the latest versions to pull in the new capability

Prior ART for adding CVO capability:
- https://github.com/openshift/api/pull/2097
- https://github.com/openshift/cluster-version-operator/pull/1108

### CODE REVIEW

**Review by tmshort — APPROVED** [review]
/lgtm

**Comment by perdasilva** [comment]
Add OPRUN-3588: to the PR title =D

**Comment by LalatenduMohanty** [comment]
@installer-team Can you please take a look. We need this PR before code branch for 4.18 happens.

**Comment by LalatenduMohanty** [comment]
https://github.com/openshift/cluster-version-operator/pull/1108 is the PR to add the capability to CVO

**Comment by patrickdillon** [comment]
@everettraven the install config crd can be generated with

```
go generate ./pkg/types/installconfig.go
```

Can you squash the fix commit? It looks like this pr is just vendoring new dependencies and then generating the new crd, so if you want to squash everything into one commit that is fine too

**Comment by everettraven** [comment]
@patrickdillon I rolled the fix commit into the commit to regenerate the CRD

**Review by LalatenduMohanty — APPROVED** [review]
/lgtm

**Pull request merged**
