### PR TITLE
pkg/asset/installconfig/aws: Extract regions from RHCOS metadata

### PR DESCRIPTION
**Pull request by wking**
Builds on #1423 (spun off from [here][1]); I'll rebase after that lands.

Uncomment all of the regions in `pkg/types/aws/validation` which had been commented out in (#1407).  Instead, perform the "can we find an AMI for that region?" check directly in `pkg/asset/installconfig/aws` when we're building a list of regions for the wizard prompt.  With this change, bumping the `rhcos.json` asset (via `hack/update-rhcos-bootimage.py`) will automatically keep the wizard prompt's choices in sync with the published AMIs.

[1]: https://github.com/openshift/installer/pull/1423#issuecomment-479584940

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
wouldn't the other way ie switching validation to use AMI regions from internal meta.json more sense... so that validation of install config catch the invalid region?

**Comment by wking** [comment]
> wouldn't the other way ie switching validation to use AMI regions from internal meta.json more sense... so that validation of install config catch the invalid region?

The previous install-config validation was overly-strict.  For example, you can have a working install-config in a region that does not include an official RHCOS AMI as long as you specify your own AMI.  For example, see my suggestion to QE try [here][1], and while we ended up closing that bug, I suspect other folks in cn-north-1 or us-gov-west-1 or similar places where we can't put official AMIs to need to do similar things.  The issue with regions that have RH-published RHCOS AMIs is just with picking a default AMI.  If you want to detect that at install-time, I can drop `rhcos.Image` and make that lookup part of install-config defaulting.  Thoughts?

Rebased onto master with 96c8b394b -> fac85144a.

[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1669396#c18

**Comment by abhinavdahiya** [comment]
> > wouldn't the other way ie switching validation to use AMI regions from internal meta.json more sense... so that validation of install config catch the invalid region?
> 
> The previous install-config validation was overly-strict. For example, you can have a working install-config in a region that does not include an official RHCOS AMI as long as you specify your own AMI. For example, see my suggestion to QE try [here](https://bugzilla.redhat.com/show_bug.cgi?id=1669396#c18), and while we ended up closing that bug, I suspect other folks in cn-north-1 or us-gov-west-1 or similar places where we can't put official AMIs to need to do similar things. The issue with regions that have RH-published RHCOS AMIs is just with picking a default AMI.

trying to use master openshift-install
```
$ cat >dev/install-config.yaml <<EOF
apiVersion: v1beta4
baseDomain: devcluster.openshift.com
controlPlane:
  name: master
  replicas: 3
compute:
- name: worker
  replicas: 3
  platform:
metadata:
  name: adahiya-1
networking:
  clusterNetworks:
  - cidr: 10.128.0.0/14
    hostSubnetLength: 9
  machineCIDR: 10.0.0.0/16
  serviceCIDR: 172.30.0.0/16
  type: OpenShiftSDN
platform:
  aws:
    region: cn-north-1
pullSecret: '{"auths":{.....}}}'
sshKey: |
  ssh-rsa REDACTED
EOF
$ ./bin/openshift-install version
./bin/openshift-install unreleased-master-700-gf04777c0164fc5822bd68b24301ea995f559e812
built from commit f04777c0164fc5822bd68b24301ea995f559e812
release image registry.svc.ci.openshift.org/openshift/origin-release:v4.0
$ ./bin/openshift-install --dir dev create manifests
FATAL failed to fetch Master Machines: failed to load asset "Install Config": invalid "install-config.yaml" file: platform.aws.region: Unsupported value: "cn-north-1": supported values: "ap-northeast-1", "ap-northeast-2", "ap-south-1", "ap-southeast-1", "ap-southeast-2", "ca-central-1", "eu-central-1", "eu-west-1", "eu-west-2", "eu-west-3", "sa-east-1", "us-east-1", "us-east-2", "us-west-1", "us-west-2"
```
So i'm not sure even copying will help the https://bugzilla.redhat.com/show_bug.cgi?id=1669396#c18
and OS_IMAGE override is not meant for everybody (dev purpose only) and therefore it is not documented.

This PR changes the current behavior as it would pass install-config validation but then later on fail when trying to fetch image from meta.json.

**Comment by abhinavdahiya** [comment]
/close

closing without prejudice due to age. Please consider opening an issue or [enhancement](https://github.com/openshift/enhancements/) to discuss and bring consensus on the fix, or if you think this is still important in current state feel free to reopen.

**Comment by wking** [comment]
Rebased on master with fac85144a -> b8a02dceb, which also distinguishes between "is a known AWS region" and "has a default RHCOS AMI".

> ...OS_IMAGE override is not meant for everybody...

Since #2002, user-specified AMI IDs are no longer a special case.

**Comment by crawford** [comment]
This makes me nervous. The RHCOS build pipeline should not be the source of truth for the list of supported regions as it is just one of many pieces that have to be in place in order for the installation to succeed.

**Comment by wking** [comment]
What are the other pieces?

**Comment by abhinavdahiya** [comment]
Closing due to this being open for a long time, Please feel free to reopen

/close

**Pull request closed without merging**
