### PR TITLE
tf/stages: delete unused code around compat and gather, and improve comments

### PR DESCRIPTION
**Pull request by staebler**
* Delete compat stage functionality.
* Delete unused code for extracting the IPs for bootstrap gather.
* Improve comments around bootstrap destroy behavior for a stage.
* Add OWNERS files to the stage packages.

### CODE REVIEW

**Comment by staebler** [comment]
This builds on https://github.com/openshift/installer/pull/5078, https://github.com/openshift/installer/pull/5064, and https://github.com/openshift/installer/pull/5034.
/hold

**Comment by staebler** [comment]
> This builds on #5078, #5064, and #5034. /hold

/hold cancel

**Review by jhixson74 — APPROVED** [review]
/lgtm

**Comment by staebler** [comment]
c91764e05...bd3be0cfe
* Restore lost commit that moved code from pkg/terraform/gather/vsphere to pkg/terraform/stages/vsphere.

**Comment by staebler** [comment]
No functionally changes to how baremetal works.
/override ci/prow/e2e-metal-ipi-ovn-ipv6-required

**Pull request merged**
