### PR TITLE
docs: fix broken link to CVO/operators.md in operators.md

### PR DESCRIPTION
**Pull request by rohantmp**
The link moved from the cluster-version-operator to the enhancements repo.

Unsubscribing because the bot seems to have gone a bit crazy. Please tag me if you want me to be notified. :)

Signed-off-by: Rohan CJ <rohantmp@gmail.com>

### CODE REVIEW

**Review by e-tienne — APPROVED** [review]
matches permanent move: https://github.com/openshift/cluster-version-operator/tree/master/docs/dev

/lgtm

**Comment by rohantmp** [comment]
Unsubscribing because the bot seems to have gone a bit crazy. Please tag me if you want me to be notified. :)

**Pull request merged**
