### PR TITLE
[vsphere] populate vSphere infrastructure spec

### PR DESCRIPTION
**Pull request by rvanderp3**
populates vSphere infrastructure specification based on openshift/api#1278

### CODE REVIEW

**Comment by rvanderp3** [comment]
cc: @jcpowermac 
/test e2e-vsphere
/test e2e-vsphere-zones

**Comment by patrickdillon** [comment]
/override ci/prow/e2e-aws-ovn  ci/prow/e2e-azure-ovn ci/prow/e2e-vsphere-ovn

**Pull request merged**
