### PR TITLE
openstack: Assign floating IP to service VM.

### PR DESCRIPTION
**Pull request by russellb**
Automatically assign a floating IP to the service VM that hosts the load
balancer in front of the API.  This is required to reach the cluster,
so we should automate it.

### CODE REVIEW

**Comment by russellb** [comment]
This works, but leaves the FIP around after destroy.  Fixing that doesn't look quick, as we'll need to add resource tagging for FIPs into gophercloud, then support it in terraform-provider-openstack, and then we can update the destroy code to handle it.

or maybe we can discover FIPs to destroy because of their association with a tagged port.  That could be done in our current install code.  I'll look into that as an option.

/hold

**Comment by russellb** [comment]
ok, added destroy support.  I think this is good now.

/hold cancel

**Comment by flaper87** [comment]
I think it is fine, at least for now, to expect that the cloud will have FIPs available and that we'll attach one to the `api` port.

We can/should revisit this in the future.

**Pull request merged**
