### PR TITLE
CORS-2645: AWS Cross-Account Private Hosted Zone: Add Further Validations

### PR DESCRIPTION
**Pull request by patrickdillon**
Adds/refines validations for the cross-account private hosted zone use case:

- do not allow mint credential mode
- do not require unnecessary permissions when using an existing hosted zone
- require sts:AssumeRole permissions  

Also includes some refactoring that did not make it into the previous PR.

ccing previous reviewers:
/cc @barbacbd @r4f4 @mtulio @sadasu

### CODE REVIEW

**Comment by patrickdillon** [comment]
@yunjiang29 PTAL

**Review by r4f4 — COMMENTED** [review]
/lgtm

**Comment by patrickdillon** [comment]
> @patrickdillon while doing AssumeRole validation tests, is the below message expected? It looks like it's a _real_ "_No Permission_" error instead of a "_current credentials insufficient for performing cluster installation_" [2]

I think this should now be fixed in bfd54274464407ca988cde3624d88a4e2d54043a. I would expect a `Tested creds not able to perform all requested actions` error/warning if the INSTALLER creds do not have the right permissions (in this case AssumeRole). 

But we are not testing the provided role for permissions, so if the role is missing route53 or tagging permissions, we will get an actual error and that is expected. 

I hope that makes sense! LMK if it is unclear.

**Comment by r4f4** [comment]
I don't think the `resource_dep.svg` was generated correctly. Here's the content 
```

 * Waiting in queue... 
The following packages have to be installed:
 graphviz-5.0.0-4.fc37.x86_64	Graph Visualization Tools
 gts-0.7.6-42.20121130.fc37.x86_64	GNU Triangulated Surface Library
 lasi-1.1.3-9.fc37.x86_64	C++ library for creating Postscript documents
 mkfontscale-1.2.2-2.fc37.x86_64	Tool to generate legacy X11 font system index files
 netpbm-11.02.00-1.fc37.x86_64	A library for handling different graphics file formats
 xorg-x11-fonts-ISO8859-1-100dpi-7.5-34.fc37.noarch	A set of 100dpi ISO-8859-1 fonts for X

 * Waiting in queue... 
 * Waiting for authentication... 
 * Waiting in queue... 
 * Downloading packages... 
 * Requesting data... 
 * Testing changes... 
 * Installing packages... 
```

**Comment by yunjiang29** [comment]
> I think this should now be fixed in [bfd5427](https://github.com/openshift/installer/commit/bfd54274464407ca988cde3624d88a4e2d54043a).

@patrickdillon it looks like the issue is still there:
```
time="2023-06-21T12:23:55+08:00" level=fatal msg="failed to fetch Terraform Variables: failed to fetch dependency of \"Terraform Variables\": failed to generate asset \"Platform Provisioning Check\": aws.hostedZone: Invalid value: \"Z0134236393RTBLQK2N75\": unable to retrieve hosted zone: could not get hosted zone: Z0134236393RTBLQK2N75: AccessDenied: User: arn:aws:iam::301721915996:user/yunjiang-deny-AssumeRole is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::641733028092:role/yunjiang-noassu5-rol1\n\tstatus code: 403, request id: bf64206b-bebd-4dcf-a79b-d1de6976d4a9"
```

**Comment by patrickdillon** [comment]
> I don't think the `resource_dep.svg` was generated correctly. Here's the content
> 
> ```
> 
>  * Waiting in queue... 
> The following packages have to be installed:
>  graphviz-5.0.0-4.fc37.x86_64	Graph Visualization Tools
>  gts-0.7.6-42.20121130.fc37.x86_64	GNU Triangulated Surface Library
>  lasi-1.1.3-9.fc37.x86_64	C++ library for creating Postscript documents
>  mkfontscale-1.2.2-2.fc37.x86_64	Tool to generate legacy X11 font system index files
>  netpbm-11.02.00-1.fc37.x86_64	A library for handling different graphics file formats
>  xorg-x11-fonts-ISO8859-1-100dpi-7.5-34.fc37.noarch	A set of 100dpi ISO-8859-1 fonts for X
> 
>  * Waiting in queue... 
>  * Waiting for authentication... 
>  * Waiting in queue... 
>  * Downloading packages... 
>  * Requesting data... 
>  * Testing changes... 
>  * Installing packages... 
> ```

:facepalm: 

In any case, I have removed the commit changing the resource dependency so this doesn't need to be updated anymore.

**Comment by patrickdillon** [comment]
> > I think this should now be fixed in [bfd5427](https://github.com/openshift/installer/commit/bfd54274464407ca988cde3624d88a4e2d54043a).
> 
> @patrickdillon it looks like the issue is still there:
> 
> ```
> time="2023-06-21T12:23:55+08:00" level=fatal msg="failed to fetch Terraform Variables: failed to fetch dependency of \"Terraform Variables\": failed to generate asset \"Platform Provisioning Check\": aws.hostedZone: Invalid value: \"Z0134236393RTBLQK2N75\": unable to retrieve hosted zone: could not get hosted zone: Z0134236393RTBLQK2N75: AccessDenied: User: arn:aws:iam::301721915996:user/yunjiang-deny-AssumeRole is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::641733028092:role/yunjiang-noassu5-rol1\n\tstatus code: 403, request id: bf64206b-bebd-4dcf-a79b-d1de6976d4a9"
> ```

On further examination, it appears that there are no permissions that need to be checked in Account B to perform this assume role option: all of the permissions reside within Account A. We could potentially check the permissions for the role in Account A, but that would require expanding the permissions needed by the role in Account A (such as the IAM simulate policy role). Considering that in this case a user-friendly permissions error will appear before any resources have been created (or when attempting to destroy DNS records), it does not seem like a good idea to pursue further permissions checking. Therefore I have removed the check for sts:AssumeRole (because it does nothing), and we should expect errors like the one Yunfei posted https://github.com/openshift/installer/pull/7253#issuecomment-1600089843 in the case of an incorrect configuration.

**Review by r4f4 — COMMENTED** [review]
/approve

**Comment by yunjiang29** [comment]
> > > I think this should now be fixed in [bfd5427](https://github.com/openshift/installer/commit/bfd54274464407ca988cde3624d88a4e2d54043a).
> > 
> > 
> > @patrickdillon it looks like the issue is still there:
> > ```
> > time="2023-06-21T12:23:55+08:00" level=fatal msg="failed to fetch Terraform Variables: failed to fetch dependency of \"Terraform Variables\": failed to generate asset \"Platform Provisioning Check\": aws.hostedZone: Invalid value: \"Z0134236393RTBLQK2N75\": unable to retrieve hosted zone: could not get hosted zone: Z0134236393RTBLQK2N75: AccessDenied: User: arn:aws:iam::301721915996:user/yunjiang-deny-AssumeRole is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::641733028092:role/yunjiang-noassu5-rol1\n\tstatus code: 403, request id: bf64206b-bebd-4dcf-a79b-d1de6976d4a9"
> > ```
> 
> On further examination, it appears that there are no permissions that need to be checked in Account B to perform this assume role option: all of the permissions reside within Account A. We could potentially check the permissions for the role in Account A, but that would require expanding the permissions needed by the role in Account A (such as the IAM simulate policy role). Considering that in this case a user-friendly permissions error will appear before any resources have been created (or when attempting to destroy DNS records), it does not seem like a good idea to pursue further permissions checking. Therefore I have removed the check for sts:AssumeRole (because it does nothing), and we should expect errors like the one Yunfei posted [#7253 (comment)](https://github.com/openshift/installer/pull/7253#issuecomment-1600089843) in the case of an incorrect configuration.

@patrickdillon thanks for the detailed explanation, the pre-merge test gets passed.

**Review by barbacbd — COMMENTED** [review]
/lgtm

**Pull request merged**
