### PR TITLE
Enable re-use of existing private hosted zone in AWS

### PR DESCRIPTION
**Pull request by mihail-milev**
This modification allows by modifying the cluster-dns-02-config.yml manifest
file to ask the installer to re-use an already existing private AWS
hosted zone in Route53.

In the data/data/aws/route53/base.tf file a new "data" section was
added and based on the value of a TF variable either the "data" section
or the "ressource" section is being used. If the TF variable is set
to Golang's string zero value ("") then a new hosted zone will be
created (default behavior), otherwise, if not string zero, then TF will
try to use the hosted zone, which ID corresponds to the one specified
in the TF variable.

In order to activate the mechanism:
1) specify "publish: Internal" inside the install-config.yaml
2) generate the manifests
3) modify manifests/cluster-dns-02-config.yml by:
3.1) removing the "tags" section from "privateZone"
3.2) adding "id" string value inside the "privateZone". Set the value
     of this string to the hosted zone ID ("Z0123QQQZXX..."), you
     wish to reuse
4) execute "openshift-install create cluster ..."

This is exactly what is described in this file:
docs/user/aws/install_upi.md
under the chapter "Identify the internal DNS zone"

This mechanism could be extended for other cloud providers, e.g.
Azure or GCP, but I don't have the resources to do it.

### CODE REVIEW

**Comment by staebler** [comment]
Thank you for your PR. Unfortunately, this is not a change that we will be accepting.

We deliberately do not provide all possible configurations in the installer-provisioned installation flow. The intention is for the options available to be curated to a small set that is useful for a large share of our users or difficult to work around in other ways.

**Comment by mihail-milev** [comment]
> Thank you for your PR. Unfortunately, this is not a change that we will be accepting.
> 
> We deliberately do not provide all possible configurations in the installer-provisioned installation flow. The intention is for the options available to be curated to a small set that is useful for a large share of our users or difficult to work around in other ways.

Hello,

I do understand the urge to keep it as simple as possible and to make it easy for the users to deploy a cluster. That is the reason, why I also kept the default behavior of the installer - just execute it like you are doing it until now, and it will work as it worked until now.

But there are some "power users" over there, which deploy > 10 clusters a day and there is the need to do customization sometimes. Most of the time there are restrictions (like e.g. not allowed to create new hosted zones) and every time "workarounds" need to be done. That is not oriented towards the users - that is against the users.

What would be the "other ways" to solve this problem?

**Comment by staebler** [comment]
> But there are some "power users" over there, which deploy > 10 clusters a day and there is the need to do customization sometimes. Most of the time there are restrictions (like e.g. not allowed to create new hosted zones) and every time "workarounds" need to be done. That is not oriented towards the users - that is against the users.
> 
> What would be the "other ways" to solve this problem?

The "other ways" to solve this problem is to take the user-provisioned infrastructure approach. It is precisely for those "power users" with special requirements that we offer that approach, where the user has more control over what is and is not provisioned. You could start with and modify to your needs the CloudFormation from https://github.com/openshift/installer/tree/master/upi/aws/cloudformation or even the terraform that the installer uses to do an installer-provisioned infrastructure installation. Or you can use whatever other tools you prefer to provision the infrastructure.

**Comment by staebler** [comment]
Bring-your-own private hosted zone is being implemented as a configurable field in the install config with https://github.com/openshift/installer/pull/4772.
/close

**Pull request closed without merging**
