### PR TITLE
[UPI on OSP] make remove network and port more faster

### PR DESCRIPTION
**Pull request by wjiangjay**

### CODE REVIEW

**Comment by wjiangjay** [comment]
@MaysaMacedo @pierreprinetti help review this, Thanks

**Comment by MaysaMacedo** [comment]
Thanks for contributing @wjiangjay. Could you add a commit message explaining how the new changes make it faster?

**Comment by wjiangjay** [comment]
@MaysaMacedo Thanks for checking, and I update the commit message to 
```
    [UPI on OSP] make remove network and port more faster

    Merge ports deletion requests to one instead of delete one by one to save time.
    And also for networks
```

**Comment by pierreprinetti** [comment]
/approve
Thanks!
I am not sure if there's a lot of gain for networks though.

**Comment by wjiangjay** [comment]
@pierreprinetti yes, before this, the deletion will cost about 45~60 minutes.
With this, it will be 20 ~ 30 minutes.

**Pull request merged**
