### PR TITLE
AGENT-870: Update AUTH_TYPE

### PR DESCRIPTION
**Pull request by pawanpinjarkar**
Enable the new auth type `agent-installer-local`

### CODE REVIEW

**Comment by pawanpinjarkar** [comment]
This PR should be merged once all the other PRs are merged.
/depends-on

- https://github.com/openshift/assisted-service/pull/6174
- https://github.com/openshift/installer/pull/8270
- https://github.com/openshift/installer/pull/8393 
- https://github.com/openshift/installer/pull/8395

**Comment by pawanpinjarkar** [comment]
/hold

Enable only when we have the required changes ready for authenticating day2 operations

**Comment by andfasano** [comment]
@pawanpinjarkar does it work also with the add node feature?

**Comment by pawanpinjarkar** [comment]
> @pawanpinjarkar does it work also with the add node feature?

Once day1 auth is enabled via current PR, the day2 changes can be merged (PR for review https://github.com/openshift/installer/pull/8717) Unless https://github.com/openshift/installer/pull/8108 is merged, the auth won't work for day 1 and day2.

**Comment by pawanpinjarkar** [comment]
/hold depends on https://github.com/openshift/installer/pull/8717
Once all the day2 changes are reviewed and merged, as a last step we could switch the auth type

**Comment by andfasano** [comment]
> /hold until the CI jobs are for day2 are ready [openshift/release#54082](https://github.com/openshift/release/pull/54082)

Unfortunately it will not be enough, since the complete usage of the `oc` commands will be introduced only in https://issues.redhat.com/browse/WRKLDS-1319 (and ofc it depends on #54082, where just the TP scripts were used)

**Review by rwsu — COMMENTED** [review]
/lgtm

**Pull request merged**
