### PR TITLE
OCPBUGS-33205: Gcp bootstraping release 4.15

### PR DESCRIPTION
**Pull request by barbacbd**
GCP: Fix Bootstrapping manual backport to 4.15
    
** Presign a url. This will include adding the proxy information to the shim.
** Pass the value to terraform (this will be the url not the data contained in it).
** During custom dns solutions, the data that url points to will change but not the url itself.

### CODE REVIEW

**Review by r4f4 — COMMENTED** [review]
/lgtm

**Comment by sadasu** [comment]
This is a manual backport of https://github.com/openshift/installer/pull/8056 and https://github.com/openshift/installer/pull/8248

**Pull request merged**
