### PR TITLE
Bug 1899176: Bump RHCOS bootimages to 46.82.202011260640-0

### PR DESCRIPTION
**Pull request by jlebon**
This includes fixes for the following bugs:
- https://bugzilla.redhat.com/show_bug.cgi?id=1899289
- https://bugzilla.redhat.com/show_bug.cgi?id=1899361
- https://bugzilla.redhat.com/show_bug.cgi?id=1899286
- https://bugzilla.redhat.com/show_bug.cgi?id=1901021

```
$ ./differ.py --first-endpoint art --first-release [rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202010011740-0 \
              --second-endpoint art --second-release [rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202011260640-0
{
    "sources": {
        "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202010011740-0": "https://releases-rhcos-art.cloud.privileged.psi.redhat.com/storage/releases/rhcos-4.6/46.82.202010011740-0/x86_64/commitmeta.json",
        "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202011260640-0": "https://releases-rhcos-art.cloud.privileged.psi.redhat.com/storage/releases/rhcos-4.6/46.82.202011260640-0/x86_64/commitmeta.json"
    },
    "diff": {
        "NetworkManager": {
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202010011740-0": "NetworkManager-1.22.8-6.el8_2.x86_64",
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202011260640-0": "NetworkManager-1.22.8-7.el8_2.x86_64"
        },
        "NetworkManager-libnm": {
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202010011740-0": "NetworkManager-libnm-1.22.8-6.el8_2.x86_64",
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202011260640-0": "NetworkManager-libnm-1.22.8-7.el8_2.x86_64"
        },
        "NetworkManager-ovs": {
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202010011740-0": "NetworkManager-ovs-1.22.8-6.el8_2.x86_64",
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202011260640-0": "NetworkManager-ovs-1.22.8-7.el8_2.x86_64"
        },
        "NetworkManager-team": {
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202010011740-0": "NetworkManager-team-1.22.8-6.el8_2.x86_64",
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202011260640-0": "NetworkManager-team-1.22.8-7.el8_2.x86_64"
        },
        "NetworkManager-tui": {
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202010011740-0": "NetworkManager-tui-1.22.8-6.el8_2.x86_64",
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202011260640-0": "NetworkManager-tui-1.22.8-7.el8_2.x86_64"
        },
        "console-login-helper-messages": {
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202010011740-0": "console-login-helper-messages-0.19-1.rhaos4.6.el8.noarch",
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202011260640-0": "console-login-helper-messages-0.19-3.rhaos4.6.el8.noarch"
        },
        "console-login-helper-messages-issuegen": {
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202010011740-0": "console-login-helper-messages-issuegen-0.19-1.rhaos4.6.el8.noarch",
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202011260640-0": "console-login-helper-messages-issuegen-0.19-3.rhaos4.6.el8.noarch"
        },
        "console-login-helper-messages-profile": {
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202010011740-0": "console-login-helper-messages-profile-0.19-1.rhaos4.6.el8.noarch",
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202011260640-0": "console-login-helper-messages-profile-0.19-3.rhaos4.6.el8.noarch"
        },
        "cri-o": {
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202010011740-0": "cri-o-1.19.0-19.rhaos4.6.gitda1d894.el8.x86_64",
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202011260640-0": "cri-o-1.19.0-25.rhaos4.6.gitf51f94a.el8.x86_64"
        },
        "cri-tools": {
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202010011740-0": "cri-tools-1.18.0-3.el8.x86_64",
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202011260640-0": "cri-tools-1.19.0-4.el8.x86_64"
        },
        "criu": {
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202010011740-0": "criu-3.14-2.module+el8.2.1+6750+e53a300c.x86_64",
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202011260640-0": "criu-3.12-9.module+el8.2.0+7659+b700d80e.x86_64"
        },
        "freetype": {
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202010011740-0": "freetype-2.9.1-4.el8.x86_64",
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202011260640-0": "freetype-2.9.1-4.el8_2.1.x86_64"
        },
        "fuse-overlayfs": {
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202010011740-0": "fuse-overlayfs-1.0.0-2.module+el8.2.1+6465+1a51e8b6.x86_64",
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202011260640-0": "fuse-overlayfs-0.7.2-5.module+el8.2.0+7659+b700d80e.x86_64"
        },
        "glusterfs": {
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202010011740-0": "glusterfs-6.0-37.el8.x86_64",
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202011260640-0": "glusterfs-6.0-20.el8.x86_64"
        },
        "glusterfs-client-xlators": {
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202010011740-0": "glusterfs-client-xlators-6.0-37.el8.x86_64",
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202011260640-0": "glusterfs-client-xlators-6.0-20.el8.x86_64"
        },
        "glusterfs-fuse": {
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202010011740-0": "glusterfs-fuse-6.0-37.el8.x86_64",
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202011260640-0": "glusterfs-fuse-6.0-20.el8.x86_64"
        },
        "glusterfs-libs": {
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202010011740-0": "glusterfs-libs-6.0-37.el8.x86_64",
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202011260640-0": "glusterfs-libs-6.0-20.el8.x86_64"
        },
        "grub2-common": {
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202010011740-0": "grub2-common-2.02-87.el8_2.noarch",
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202011260640-0": "grub2-common-2.02-87.el8_2.2.noarch"
        },
        "grub2-efi-x64": {
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202010011740-0": "grub2-efi-x64-2.02-87.el8_2.x86_64",
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202011260640-0": "grub2-efi-x64-2.02-87.el8_2.2.x86_64"
        },
        "grub2-pc": {
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202010011740-0": "grub2-pc-2.02-87.el8_2.x86_64",
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202011260640-0": "grub2-pc-2.02-87.el8_2.2.x86_64"
        },
        "grub2-pc-modules": {
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202010011740-0": "grub2-pc-[modules-2](https://issues.redhat.com/browse/modules-2).02-87.el8_2.noarch",
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202011260640-0": "grub2-pc-[modules-2](https://issues.redhat.com/browse/modules-2).02-87.el8_2.2.noarch"
        },
        "grub2-tools": {
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202010011740-0": "grub2-tools-2.02-87.el8_2.x86_64",
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202011260640-0": "grub2-tools-2.02-87.el8_2.2.x86_64"
        },
        "grub2-tools-extra": {
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202010011740-0": "grub2-tools-extra-2.02-87.el8_2.x86_64",
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202011260640-0": "grub2-tools-extra-2.02-87.el8_2.2.x86_64"
        },
        "grub2-tools-minimal": {
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202010011740-0": "grub2-tools-minimal-2.02-87.el8_2.x86_64",
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202011260640-0": "grub2-tools-minimal-2.02-87.el8_2.2.x86_64"
        },
        "ignition": {
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202010011740-0": "ignition-2.6.0-5.rhaos4.6.git947598e.el8.x86_64",
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202011260640-0": "ignition-2.6.0-6.rhaos4.6.git947598e.el8.x86_64"
        },
        "iptables": {
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202010011740-0": "iptables-1.8.4-10.el8_2.1.x86_64",
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202011260640-0": "iptables-1.8.4-10.el8_2.4.x86_64"
        },
        "iptables-libs": {
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202010011740-0": "iptables-libs-1.8.4-10.el8_2.1.x86_64",
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202011260640-0": "iptables-libs-1.8.4-10.el8_2.4.x86_64"
        },
        "kernel": {
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202010011740-0": "kernel-4.18.0-193.24.1.el8_2.dt1.x86_64",
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202011260640-0": "kernel-4.18.0-193.29.1.el8_2.x86_64"
        },
        "kernel-core": {
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202010011740-0": "kernel-core-4.18.0-193.24.1.el8_2.dt1.x86_64",
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202011260640-0": "kernel-core-4.18.0-193.29.1.el8_2.x86_64"
        },
        "kernel-modules": {
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202010011740-0": "kernel-[modules-4](https://issues.redhat.com/browse/modules-4).18.0-193.24.1.el8_2.dt1.x86_64",
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202011260640-0": "kernel-[modules-4](https://issues.redhat.com/browse/modules-4).18.0-193.29.1.el8_2.x86_64"
        },
        "kernel-modules-extra": {
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202010011740-0": "kernel-modules-extra-4.18.0-193.24.1.el8_2.dt1.x86_64",
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202011260640-0": "kernel-modules-extra-4.18.0-193.29.1.el8_2.x86_64"
        },
        "libslirp": {
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202010011740-0": "libslirp-4.3.0-3.module+el8.2.1+6816+bedf4f91.x86_64",
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202011260640-0": "Not present"
        },
        "microcode_ctl": {
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202010011740-0": "microcode_ctl-20191115-4.20200609.1.el8_2.x86_64",
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202011260640-0": "microcode_ctl-20191115-4.20201112.1.el8_2.x86_64"
        },
        "nftables": {
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202010011740-0": "nftables-0.9.3-12.el8.x86_64",
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202011260640-0": "nftables-0.9.3-12.el8_2.1.x86_64"
        },
        "open-vm-tools": {
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202010011740-0": "open-vm-tools-11.0.5-3.el8.x86_64",
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202011260640-0": "open-vm-tools-11.0.0-4.el8.x86_64"
        },
        "openshift-clients": {
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202010011740-0": "openshift-clients-4.6.0-202009302026.p0.git.3788.4b35f95.el8.x86_64",
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202011260640-0": "openshift-clients-4.6.0-202011260456.p0.git.3798.fcf58ff.el8.x86_64"
        },
        "openshift-hyperkube": {
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202010011740-0": "openshift-hyperkube-4.6.0-202009292315.p0.git.94026.088ba37.el8.x86_64",
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202011260640-0": "openshift-hyperkube-4.6.0-202011260456.p0.git.94222.2edb87d.el8.x86_64"
        },
        "openvswitch2.13": {
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202010011740-0": "openvswitch2.13-2.13.0-57.el8fdp.x86_64",
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202011260640-0": "openvswitch2.13-2.13.0-71.el8fdp.x86_64"
        },
        "selinux-policy": {
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202010011740-0": "selinux-policy-3.14.3-41.el8_2.6.noarch",
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202011260640-0": "selinux-policy-3.14.3-41.el8_2.8.noarch"
        },
        "selinux-policy-targeted": {
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202010011740-0": "selinux-policy-targeted-3.14.3-41.el8_2.6.noarch",
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202011260640-0": "selinux-policy-targeted-3.14.3-41.el8_2.8.noarch"
        },
        "shim-x64": {
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202010011740-0": "shim-x64-15-15.el8_2.x86_64",
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202011260640-0": "shim-x64-15-16.el8.x86_64"
        },
        "slirp4netns": {
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202010011740-0": "slirp4netns-1.0.1-1.module+el8.2.1+6595+03641d72.x86_64",
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202011260640-0": "slirp4netns-0.4.2-3.git21fdece.module+el8.2.0+7659+b700d80e.x86_64"
        },
        "tzdata": {
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202010011740-0": "tzdata-2020a-1.el8.noarch",
            "[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6/46.82.202011260640-0": "tzdata-2020d-1.el8.noarch"
        }
    }
}
```

### CODE REVIEW

**Comment by jlebon** [comment]
@Prashanth684 I tried to update the s390x and ppc64le bootimages too here, but getting 403, e.g.:

```
./hack/update-rhcos-bootimage.py https://releases-art-rhcos.svc.ci.openshift.org/
art/storage/releases/rhcos-4.6/46.82.202011261339-0/s390x/meta.json s390x
Traceback (most recent call last):
  File "/home/jlebon/Code/github.com/openshift/installer/./hack/update-rhcos-bootimage.py", line 21, in <module>
    with urllib.request.urlopen(args.meta) as f:
  File "/usr/lib64/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/lib64/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/lib64/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/lib64/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

I'm guessing they use a different endpoint?

**Comment by jlebon** [comment]
> expected Bugzilla bug 1899361 to depend on a bug targeting a release in 4.7.0 and in one of the following states: VERIFIED, RELEASE_PENDING, CLOSED (ERRATA), but no dependents were found

I think we'll need to override that. As mentioned in https://bugzilla.redhat.com/show_bug.cgi?id=1899342#c4, the bug isn't present in 4.7.

**Comment by Prashanth684** [comment]
> https://releases-art-rhcos.svc.ci.openshift.org/
> art/storage/releases/rhcos-4.6/46.82.202011261339-0/s390x/meta.json

@jlebon it's `[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6-s390x` and `[rhcos-4](https://issues.redhat.com/browse/rhcos-4).6-ppc64le`. 
so for s390x: https://releases-art-rhcos.svc.ci.openshift.org/art/storage/releases/rhcos-4.6-s390x/46.82.202011261339-0/s390x/meta.json
and for ppc64le : https://releases-art-rhcos.svc.ci.openshift.org/art/storage/releases/rhcos-4.6-ppc64le/46.82.202011260639-0/ppc64le/meta.json
the ppc64le has  a slightly different timestamp. thanks for updating these!!

**Comment by jlebon** [comment]
And now with 200% more architectures!

**Comment by sdodson** [comment]
/lgtm
/approve
All of the major platforms have at least installed, there's some sort of build issue w/ many of the UPI jobs but that's not a result of this change.

**Comment by sdodson** [comment]
/retitle Bug 1899176: Bump RHCOS bootimages to 46.82.202011260640-0

**Comment by sdodson** [comment]
Overriding bugzilla/valid-bug, there will be a separate 8.3 based bootimage bump on master branch. This should be ready to go.

**Comment by sdodson** [comment]
@rgolangh @Gal-Zaidman Can you take a look at the ovirt failures? It's complaining of storage domain problems.

**Comment by sdodson** [comment]
/override ci/prow/e2e-metal
random smattering of e2e failures after successful installation
/override ci/prow/vsphere-upi
this hasn't passed in recent history
/override ci/prow/vsphere
Can't schedule the test pod, test infra problem

**Comment by rgolangh** [comment]
@Gal-Zaidman @eslutsky ptal

**Comment by Gal-Zaidman** [comment]
/unhold

Works for us, tests failed over the weekend due to unrelated CI infrastructure problems

**Comment by sdodson** [comment]
/override ci/prow/e2e-vsphere-upi
permafailure on that one
/override ci/prow/e2e-aws-upgrade
/override ci/prow/e2e-azuir-upi
/override ci/prow/e2e-metal-ipi
these all passed previously

**Comment by sdodson** [comment]
/override ci/prow/e2e-vsphere-upi
permafailure on that one
/override ci/prow/e2e-aws-upgrade
/override ci/prow/e2e-azure-upi
/override ci/prow/e2e-metal-ipi
these all passed previously

**Pull request merged**
