### PR TITLE
tests/run: Use one Python invocation (no jq) for editing the config

### PR DESCRIPTION
**Pull request by wking**
We've used the Python -> `jq` (-> `jq`) -> Python approach to editing the config file since this script landed in a2405e4d (coreos/tectonic-installer#3284).  But it's more efficient and almost equally compact to perform those edits directly in Python.

This commit uses a [here-document][1] to inject the Python script.

Once this PR lands, I'll file follow-up work to add `expirationDate` to `extraTags` (like we have for the e2e-aws tests since openshift/release#1103).

[1]: http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_07_04

### CODE REVIEW

**Comment by wking** [comment]
retest this please

**Comment by crawford** [comment]
Can we merge this after https://github.com/openshift/installer/pull/162 (assuming the tests pass on this round)?

**Comment by crawford** [comment]
retest this please

**Comment by crawford** [comment]
The tests on #162 are still giving me trouble.

/lgtm

**Comment by wking** [comment]
>     time="2018-08-24T03:46:47Z" level=error msg="error 1: open : no such file or directory" 

Heh, I'd accidentally dropped the pull-secret update.  Fixed with 64ba786 -> d8f296c.  This sort of thing will be easier to spot once we address #108.

**Comment by wking** [comment]
> Once this PR lands, I'll file follow-up work to add `expirationDate` to `extraTags`...

Filed as #169.

**Pull request merged**
