### PR TITLE
Bug 1766739: rhcos: Bump to 43.81.201911011153.0

### PR DESCRIPTION
**Pull request by cgwalters**
This build contains some networking fixes we want for the bootimage,
among other things.

This build has already passed promotion to `machine-os-content`.

### CODE REVIEW

**Comment by yuqi-zhang** [comment]
Note that this bumps `cri-o` again from:

 1.14.11-0.23.dev.rhaos4.2.gitc41de67.el8  →  1.16.0-0.3.dev.rhaos4.3.gita1639b5.el8

**Comment by yuqi-zhang** [comment]
/test e2e-metal

Although this one is less likely to pass

**Comment by cgwalters** [comment]
> Note that this bumps cri-o again from:

Right but...only for the bootimage.  So it's only relevant on the bootstrap node.  crio 1.16 landed in `machine-os-content` a day or two ago already.

**Comment by cgwalters** [comment]
Those three jobs seem mostly like persistent failures unrelated to this PR.

Let's get this in?

That said @jcpowermac do you want to test https://bugzilla.redhat.com/show_bug.cgi?id=1762509 with this?

**Comment by ashcrow** [comment]
@abhinavdahiya would you mind :+1: / :-1:?

**Comment by abhinavdahiya** [comment]
/hold

With feature freeze in effect, we can not bump the boot-images, unless we think it solves a bug.

**Comment by ashcrow** [comment]
> This build contains some networking fixes we want for the bootimage,
among other things.

It does, and was submitted before freeze.

**Comment by abhinavdahiya** [comment]
> > This build contains some networking fixes we want for the bootimage,
> > among other things.
> 
> It does,

If we can attach the BZ to the PR then we can most definitely move ahead.

> and was submitted before freeze.

i'm sorry about the delay, but bumping the boot-image requires openstack and baremetal-ipi(kni) teams to also approve as it has chance to break them.

and since it was not in merge queue on Nov 1, we cannot merge the PR unless it has a BZ attached or is a doc fixed

**Comment by cgwalters** [comment]
Sure, updated with BZ link.

**Comment by cgwalters** [comment]
Hm, not sure what went wrong with the tests on that e2e-aws run.
/test e2e-aws

**Comment by abhinavdahiya** [comment]
https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_installer/2609/pull-ci-openshift-installer-master-e2e-vsphere/68#1:build-log.txt%3A1075

^^ the attched BZ doesn't seem to have fixed, as the vsphere CI is still failing..?

**Comment by cgwalters** [comment]
OK, I don't know why vsphere isn't working, but I know for 100% sure this update fixes *this* other related bug https://bugzilla.redhat.com/show_bug.cgi?id=1766739 which is definitely impacting people - I just re-verified it again in qemu.  I retitled the bug to claim that instead.

**Comment by abhinavdahiya** [comment]
/retitle Bug 1766739: rhcos: Bump to 43.81.201911011153.0

**Comment by cgwalters** [comment]
Hmm, the metrics one looks exactly like the one from broken crio, but we should be pivoting.

**Comment by sdodson** [comment]
/test e2e-aws
Not marked as required but blocking merge? :confused:

**Comment by ashcrow** [comment]
>  Not marked as required but blocking merge? confused

:man_shrugging: :slightly_smiling_face:

**Pull request merged**
