### PR TITLE
hack/build: Pin to RHCOS 47.297 and quay.io/openshift-release-dev/ocp-release:4.0.0-0.3

### PR DESCRIPTION
**Pull request by wking**
DO NOT MERGE! This PR is just for CI coverage (like #1134 and similar before it).

The bump from RHCOS 47.280 to 47.297 brings in, among other things, v0.12 kubelets.

@smarterclayton pushed `4.0.0-0.nightly-2019-01-30-145955` to quay.io/openshift-release-dev/ocp-release:4.0.0-0.3.

/hold

### CODE REVIEW

**Comment by wking** [comment]
[e2e-aws][1]:

```
level=info msg="Waiting up to 30m0s for the Kubernetes API..."
level=fatal msg="waiting for Kubernetes API: context deadline exceeded"
```

Likely cause from [bootkube.service][2]:

```
Feb 05 04:17:31 ip-10-0-13-99 bootkube.sh[5859]: F0205 04:17:31.722174       1 main.go:32] Error executing mcc: unknown flag: --machine-config-oscontent-image
```

That flag is from openshift/machine-config-operator@77ed063cc5 (openshift/machine-config-operator#355).  I'm still trying to figure out why there's a mismatch between setting it and respecting it.

[1]: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_installer/1192/pull-ci-openshift-installer-master-e2e-aws/3431/build-log.txt
[2]: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_installer/1192/pull-ci-openshift-installer-master-e2e-aws/3431/artifacts/e2e-aws/bootstrap/bootkube.service

**Comment by wking** [comment]
> That flag is from openshift/machine-config-operator@77ed063...

```console
$ oc adm release info --commits quay.io/openshift-release-dev/ocp-release:4.0.0-0.3 | grep ' machine-config-operator'
  machine-config-operator                       https://github.com/openshift/machine-config-operator                       96228eb286a36944b8a729abeea0442ed73af776
$ git log --first-parent --decorate --oneline -3 77ed063
77ed063 (origin/pr/355) operator: Add bootstrap arg --machine-config-oscontent-image
71ace53 Merge pull request #343 from abhinavdahiya/controller_images
96228eb Merge pull request #352 from rphillips/fix/file_validation_for_overwritten_file
```

So that explains why the flag is not supported.  So who's setting it?

```console
$ oc adm release extract --from=quay.io/openshift-release-dev/ocp-release:4.0.0-0.3 --to=/tmp/manifests
Extracted release payload from digest sha256:5b7d1c80f75a7703b5622de7273d63b4939dbfae1986b87b3fee436a1dacab44 created at 2019-02-04T15:49:32Z
$ grep -r oscontent /tmp/manifests  # no hits
```

Hmm.

```console
$ git log --decorate --oneline -U0 -G machine-config-oscontent-image origin/master
e2b31b2 (origin/pr/1149) bootkube: Supply machine-os-content to MCO
diff --git a/data/data/bootstrap/files/usr/local/bin/bootkube.sh.template b/data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
index a2fe578..7bc5270 100755
--- a/data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
+++ b/data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
@@ -22,0 +23 @@ MACHINE_CONFIG_DAEMON_IMAGE=$(podman run --rm ${release} image machine-config-da
+MACHINE_CONFIG_OSCONTENT=$(podman run --rm ${release} image machine-os-content)
@@ -131,0 +133 @@ then
+                       --machine-config-oscontent-image=${MACHINE_CONFIG_OSCONTENT}
```

Wait, that commit isn't part of this branch:

```console
$ git log --graph --oneline --decorate -5 origin/master origin/pr/1192 | cat
* 3c581f5 (HEAD, wking/version-0.12.0-pins, origin/pr/1192, version-0.12.0-pins) hack/build: Pin to RHCOS 47.297 and quay.io/openshift-release-dev/ocp-release:4.0.0-0.3
* 2e5acd0 (wking/version-0.12.0, origin/pr/1191, version-0.12.0) CHANGELOG: Document changes since 0.11.0
| *   d1e59b3 (origin/master, origin/HEAD) Merge pull request #1149 from cgwalters/bootkube-osimageurl
| |\  
|/ /  
| * e2b31b2 (origin/pr/1149) bootkube: Supply machine-os-content to MCO
* |   da6d45b Merge pull request #890 from staebler/asset_loading_tests
|\ \  
```

So how is logic from #1149 ending up in my unit tests here?

**Comment by wking** [comment]
> So how is logic from #1149 ending up in my unit tests here?

Ah, the commit under test is this branch merged into the current master.  So to test this PR in its own right we'd need to point it at a new `master-0.12.0` branch or similar.

**Comment by abhinavdahiya** [comment]
> DO NOT MERGE! This PR is just for CI coverage (like #1134 and similar before it).
> 
> The bump from RHCOS 47.280 to 47.297 brings in, among other things, v0.12 kubelets.
> 
> @smarterclayton pushed `4.0.0-0.nightly-2019-01-30-145955` to quay.io/openshift-release-dev/ocp-release:4.0.0-0.3.

the release image is 7 days old :( it would be nice if we pin to somewhat latest ... ?

> /hold

**Comment by wking** [comment]
This is 0.12.0 now, so...

/close

> the release image is 7 days old :( it would be nice if we pin to somewhat latest ... ?

There was some sort or ART hiccup, so this was the somewhat-latest when it was selected for QE on Friday.  It just took us a bit to turn this around ;).

**Pull request closed without merging**
