### PR TITLE
Bug 1749276: OpenStack: remove volumes along with other resources

### PR DESCRIPTION
**Pull request by Fedosin**
At the time of deleting the cluster, we also need to delete all cluster volumes.

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
> https://github.com/openshift/installer/pull/2329/commits/318dff7f80248a43836d6596dd971405ba151ec0

/approve

/hold

@mandre drop the hold if you think the other commit is +1

**Comment by mandre** [comment]
/hold cancel

Thanks @abhinavdahiya, everything's in order :+1:

**Pull request merged**
