### PR TITLE
OCPBUGS-4038: bootstrap: Enable gatewayd units only on RHCOS

### PR DESCRIPTION
**Pull request by LorbusChris**
Next iteration of https://github.com/openshift/installer/pull/7505

/cc @andfasano @vrutkovs

### CODE REVIEW

**Comment by LorbusChris** [comment]
Progress, this bootstraps with OCP. OKD not so far..
/retest

**Comment by LorbusChris** [comment]
This change now still seems to break OKD IPI bootstrap.

Shouldn't the bootstrap host rebase to the OKD OS (SCOS or FCOS+OKD layer) first, and then activate all the services? And only skip them in case of an ABI install?

**Comment by andfasano** [comment]
The aws OKD jobs look broken also in other PRs, so not sure the failures observed here are due the current patch. 
Just for a one-off test, `openshiftInstallInvoker` it could be used to apply the login only when ABI is used (so equal to `"agent-installer"`)

**Comment by LorbusChris** [comment]
okd-scos-e2e-agent-sno-ipv6 passed  :eyes: IPI bootstrapping on OKD seems broken still though

**Comment by andfasano** [comment]
Rechecking aws jobs - from ABI perspective the patch looks fine.

/test okd-scos-e2e-aws-ovn
/test okd-e2e-aws-ovn

**Comment by andfasano** [comment]
/approve

@LorbusChris do you still have any point for this patch? As per the latest tests (also [here](https://github.com/openshift/installer/pull/7586)) the failures on okd aws ovn jobs seems related to something else, so it seems to me that we could proceed with this one.

**Review by vrutkovs — APPROVED** [review]
/lgtm

**Comment by LorbusChris** [comment]
@andfasano's change from https://github.com/openshift/installer/pull/7586 was missed here, adding another PR to OCPBUGS-4038: https://github.com/openshift/installer/pull/7629

**Pull request merged**
