### PR TITLE
Revert #8221 "SPLAT-1553: Added multi vCenter support for capi installer."

### PR DESCRIPTION
**Pull request by neisw**
Reverts #8221 ; tracked by https://issues.redhat.com/browse/OCPBUGS-35766

Per [OpenShift policy](https://github.com/openshift/enhancements/blob/master/enhancements/release/improving-ci-signal.md#quick-revert), we are reverting this breaking change to get CI and/or nightly payloads flowing again.

Investigating VSphere TechPreview Install Failures

To unrevert this, revert this PR, and layer an additional separate commit on top that addresses the problem. Before merging the unrevert, please run these jobs on the PR and check the result of these jobs to confirm the fix has corrected the problem:

```
/payload-job periodic-ci-openshift-release-master-nightly-4.17-e2e-vsphere-ovn-techpreview
```

CC: @vr4manta

<div align="right">
PR created by <a href="https://github.com/stbenjam/revertomatic">Revertomatic<sup>:tm:</sup></a>
</div>

### CODE REVIEW

**Comment by neisw** [comment]
Noted that https://github.com/openshift/installer/pull/8221 had vsphere techpreview bootstrap failures, testing a revert to see if we the job installs.

https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_installer/8221/pull-ci-openshift-installer-master-e2e-vsphere-ovn-zones-techpreview/1801209546388017152

**Comment by neisw** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.17-e2e-vsphere-ovn-techpreview

**Comment by neisw** [comment]
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/logs/openshift-installer-8630-nightly-4.17-e2e-vsphere-ovn-techpreview/1803195576171368448/artifacts/e2e-vsphere-ovn-techpreview/ipi-install-install/build-log.txt has completed the install

**Comment by r4f4** [comment]
/override ci/prow/okd-unit
This was supposed to be disabled/removed.

**Comment by dgoodwin** [comment]
I'm going to override the missing job, because we're going back to a known good state, technically we can override all cloud presubmits. 

/override ci/prow/e2e-azure-ovn

**Pull request merged**
