### PR TITLE
Revert "Revert #8221 "SPLAT-1553: Added multi vCenter support for capi installer.""

### PR DESCRIPTION
**Pull request by vr4manta**
Reverts openshift/installer#8630

### Notes

Note 1:
Original PR was reverted due to existing yaml logic in the installer always setting the labels in the config.  This PR will revert the revert and fix the yaml config logic to no longer include labels if failure domain list is not greater than 1.

Note 2:
Due to the nature of how the TechPreview jobs are (TechPreview enables all feature gates), the VSphereMultiVCenters feature gate still has several PRs that need to merged to prevent any installation issues.

- https://github.com/openshift/vmware-vsphere-csi-driver-operator/pull/228
- https://github.com/openshift/vsphere-problem-detector/pull/158

The CSO was updated to allow multiple vCenters, but the vSphere CSI driver operator needs a config update to complete install.

This PR will stay in draft until review and merge is completed for the CSI Driver Operator PR.

Note 3:
A new CI Job is being created to catch the install scenario of single / no FD with TechPreview enabled.  Also, it is ideal to make sure the new CI Job runs in a vCenter / datacenter / computecluster with no zonal tags to make sure we do not miss any breakages.

- https://github.com/openshift/release/pull/53497

### CODE REVIEW

**Comment by vr4manta** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.17-e2e-vsphere-ovn-techpreview

**Comment by rvanderp3** [comment]
setting hold while tests are performed

**Comment by vr4manta** [comment]
/payload-job-with-prs periodic-ci-openshift-installer-master-altinfra-periodics-e2e-vsphere-capi-ovn vmware-vsphere-csi-driver#117 openshift/vmware-vsphere-csi-driver-operator#228 openshift/vsphere-problem-detector#158

**Comment by vr4manta** [comment]
/payload-job-with-prs periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-ovn-techpreview openshift/vmware-vsphere-csi-driver#117 openshift/vmware-vsphere-csi-driver-operator#228 openshift/vsphere-problem-detector#158

**Comment by vr4manta** [comment]
/payload-job-with-prs periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-ovn-techpreview openshift/vmware-vsphere-csi-driver#117 openshift/vmware-vsphere-csi-driver-operator#228 openshift/vsphere-problem-detector#158

**Comment by vr4manta** [comment]
/payload-job-with-prs periodic-ci-openshift-release-master-nightly-4.17-e2e-vsphere-ovn-techpreview openshift/vmware-vsphere-csi-driver-operator#228 openshift/vsphere-problem-detector#158

**Comment by vr4manta** [comment]
/payload-job-with-prs periodic-ci-openshift-release-master-nightly-4.17-e2e-vsphere-ovn-techpreview openshift/vmware-vsphere-csi-driver-operator#228 openshift/vsphere-problem-detector#158

**Comment by vr4manta** [comment]
/assign @r4f4 
Ready for approval.  I'll release hold once the csi driver operator gets approved.

**Review by r4f4 — COMMENTED** [review]
/approve

**Comment by vr4manta** [comment]
/hold
fixing unit tests

**Comment by jcpowermac** [comment]
/hold cancel
unit tests are passing

**Comment by jcpowermac** [comment]
/hold

techpreview is unhappy

**Comment by jcpowermac** [comment]
/hold cancel

The initial issue with yaml-based configuration is resolved and install is completing

**Pull request merged**
