### PR TITLE
Bug 1943500: Bump gophercloud utils

### PR DESCRIPTION
**Pull request by mandre**
Bump gophercloud/utils to include gophercloud/utils#149.

This commit ensures gophercloud keeps working fine when using a custom
CA cert and Proxy at the same time.

Bumping gophercloud utils breaks the Terraform provider, which must then
be updated. I'm pinning to the same version that we're using in 4.8.

    go get github.com/gophercloud/utils
    go get github.com/terraform-provider-openstack/terraform-provider-openstack@v1.37.0
    go mod vendor

Incidentally, also includes the necessary code to fix https://bugzilla.redhat.com/show_bug.cgi?id=1786314 for 4.7.

### CODE REVIEW

**Comment by staebler** [comment]
Tests that should not be required.
/override ci/prow/e2e-kubevirt
/override ci/prow/e2e-metal-assisted
/override ci/prow/e2e-vsphere-upi

**Review by EmilienM — COMMENTED** [review]
/retest

**Comment by mandre** [comment]
I'm moving the 4.7 e2e-openstack job over to vexxhost with https://github.com/openshift/release/pull/17543, that should hopefully get us a green CI.

**Comment by mandre** [comment]
Note to patch master,  please ignore the `e2e-openstack-ipi` job, this is our step-registry job and it has never worked (we're still working on it). The `e2e-openstack` job was successful.

**Pull request merged**
