### PR TITLE
Bug 2042036: remove options for existing resources which are currently not supported

### PR DESCRIPTION
**Pull request by jeffnowicki**
The only supported 'existing resource' for 4.10 is a resource group. The additional existing resource options for vpc and subnets will be a future release consideration. Those options will be removed as options at this time. How soon those options can be supported will be a prioritization activity based on other considerations and available resources.

### CODE REVIEW

**Review by pamoedom — APPROVED** [review]

**Review by kirankt — COMMENTED** [review]
/lgtm

**Comment by hasueki** [comment]
@jeffnowicki IIRC, the contents for `data/data/install.openshift.io_installconfigs.yaml` are auto-gen'd. I think we should remove the definitions from https://github.com/openshift/installer/blob/master/pkg/types/ibmcloud/platform.go#L4, and then generate the above file.

**Comment by jeffnowicki** [comment]
Thanks Hide... I'll correct the fix.

**Comment by kirankt** [comment]
@jeffnowicki. These removed options are being checked during validation. Please remove references there as well. Thanks.
https://github.com/openshift/installer/blob/master/pkg/types/ibmcloud/validation/platform.go#L56-L64

**Comment by jeffnowicki** [comment]
@kirankt Thank you for the review/comments. I updated validation code per your comment.

**Comment by jeffnowicki** [comment]
I still have some work todo to untangle and cleanup verification code... a bit more gnarly than I anticipated.

**Comment by pamoedom** [comment]
Hi @jeffnowicki, I'm trying to locally compile your branch with the changes but errors arose, can you please double check?
~~~
[pamoedo@p50 jeffnowicki-remove-unsupported-options] $ hack/build.sh 
+ minimum_go_version=1.17
++ go version
++ cut -d ' ' -f 3
+ current_go_version=go1.17.3
++ version 1.17.3
++ IFS=.
++ printf '%03d%03d%03d\n' 1 17 3
++ unset IFS
++ version 1.17
++ IFS=.
++ printf '%03d%03d%03d\n' 1 17
++ unset IFS
+ '[' 001017003 -lt 001017000 ']'
+ MODE=release
++ git rev-parse --verify 'HEAD^{commit}'
+ GIT_COMMIT=e5d628dc70cf4df03b3adb80d96e7c63a3511288
++ git describe --always --abbrev=40 --dirty
+ GIT_TAG=unreleased-master-5521-ge5d628dc70cf4df03b3adb80d96e7c63a3511288
+ DEFAULT_ARCH=amd64
+ GOFLAGS=-mod=vendor
+ LDFLAGS=' -X github.com/openshift/installer/pkg/version.Raw=unreleased-master-5521-ge5d628dc70cf4df03b3adb80d96e7c63a3511288 -X github.com/openshift/installer/pkg/version.Commit=e5d628dc70cf4df03b3adb80d96e7c63a3511288 -X github.com/openshift/installer/pkg/version.defaultArch=amd64'
+ TAGS=
+ OUTPUT=bin/openshift-install
+ export CGO_ENABLED=0
+ CGO_ENABLED=0
+ case "${MODE}" in
+ LDFLAGS=' -X github.com/openshift/installer/pkg/version.Raw=unreleased-master-5521-ge5d628dc70cf4df03b3adb80d96e7c63a3511288 -X github.com/openshift/installer/pkg/version.Commit=e5d628dc70cf4df03b3adb80d96e7c63a3511288 -X github.com/openshift/installer/pkg/version.defaultArch=amd64 -s -w'
+ TAGS=' release'
+ test '' '!=' y
+ go generate ./data
writing assets_vfsdata.go
+ echo ' release'
+ grep -q libvirt
+ go build -mod=vendor -ldflags ' -X github.com/openshift/installer/pkg/version.Raw=unreleased-master-5521-ge5d628dc70cf4df03b3adb80d96e7c63a3511288 -X github.com/openshift/installer/pkg/version.Commit=e5d628dc70cf4df03b3adb80d96e7c63a3511288 -X github.com/openshift/installer/pkg/version.defaultArch=amd64 -s -w' -tags ' release' -o bin/openshift-install ./cmd/openshift-install
# github.com/openshift/installer/pkg/asset/installconfig/ibmcloud
pkg/asset/installconfig/ibmcloud/validation.go:45:25: ic.Platform.IBMCloud.VPC undefined (type *ibmcloud.Platform has no field or method VPC)
pkg/asset/installconfig/ibmcloud/validation.go:229:50: platform.VPC undefined (type *ibmcloud.Platform has no field or method VPC)
pkg/asset/installconfig/ibmcloud/validation.go:232:72: platform.VPC undefined (type *ibmcloud.Platform has no field or method VPC)
pkg/asset/installconfig/ibmcloud/validation.go:238:64: platform.Subnets undefined (type *ibmcloud.Platform has no field or method Subnets)
~~~
Regards.

**Comment by pamoedom** [comment]
Hi @jeffnowicki, with your latest changes I was able to locally compile the installer and the tests are successful, the options are no longer present nor accepted, thanks:
~~~
$ ./openshift-install-local version
./openshift-install-local unreleased-master-5524-g55a9f62e2693962bd4340917efded7407570d95a
built from commit 55a9f62e2693962bd4340917efded7407570d95a
release image registry.ci.openshift.org/origin/release:4.10
release architecture amd64

$ ./openshift-install-local explain installconfig.platform.ibmcloud
KIND:     InstallConfig
VERSION:  v1

RESOURCE: <object>
  IBMCloud is the configuration used when installing on IBM Cloud.

FIELDS:
    defaultMachinePlatform <object>
      DefaultMachinePlatform is the default configuration used when installing on IBM Cloud for machine pools which do not define their own platform configuration.

    region <string> -required-
      Region specifies the IBM Cloud region where the cluster will be created.

    resourceGroupName <string>
      ResourceGroupName is the name of an already existing resource group where the cluster should be installed. This resource group should only be used for this specific cluster and the cluster components will assume ownership of all resources in the resource group. Destroying the cluster using installer will delete this resource group. 
 This resource group must be empty with no other resources when trying to use it for creating a cluster. If empty, a new resource group will be created for the cluster.

$ ./openshift-install-local create manifests --dir test52/
FATAL failed to fetch Master Machines: failed to load asset "Install Config": failed to unmarshal install-config.yaml: failed to parse first occurence of unknown field: error unmarshaling JSON: while decoding JSON: json: unknown field "subnets"

$ ./openshift-install-local create manifests --dir test52/
FATAL failed to fetch Master Machines: failed to load asset "Install Config": failed to unmarshal install-config.yaml: failed to parse first occurence of unknown field: error unmarshaling JSON: while decoding JSON: json: unknown field "vpc"

$ ./openshift-install-local create manifests --dir test52/
FATAL failed to fetch Master Machines: failed to load asset "Install Config": failed to unmarshal install-config.yaml: failed to parse first occurence of unknown field: error unmarshaling JSON: while decoding JSON: json: unknown field "vpcResourceGroupName"
~~~
Regards.

**Review by pamoedom — APPROVED** [review]

**Comment by jeffnowicki** [comment]
@kirankt would you review/add labels? Thank you!

**Comment by jstuever** [comment]
/approve
I'll leave the lgtm for kirankt

**Review by kirankt — APPROVED** [review]
/lgtm

**Pull request merged**
