### PR TITLE
GCP add external dns zone

### LINKED ISSUE #2628: GCP instller does not produce public DNS zone
# Version

master branch

# Platform:

gcp

# What happened?

When creating DNS GCP does not use Public DNS zone in the same way as AWS does.
image

A records are public by default in GCP private zones, this is why it works.

# What you expected to happen?

Expect to have 2 DNS zones:
image

# Anything else we need to know?

This is needed if we want to use providers like "letsEncrypt" to provide certificates and use the TXT challenge to validate DNS. This works only with Public DNS zones. This is an OSD use-case. 

@aaronlevy @rafael-azevedo @cblecker

### PR DESCRIPTION
**Pull request by mjudeikis**
Add external dns zone for GCP

Adding external GCP zone for consistency.

Fixes #2628

### CODE REVIEW

**Comment by mjudeikis** [comment]
Before:
image

It even overrides internal ILB IP's

After:
image
image

**Comment by patrickdillon** [comment]
A public DNS zone is a prerequisite for installation which must be passed to the installer: https://github.com/openshift/installer/blob/master/docs/user/gcp/dns.md#step-2-create-public-zone

Wouldn't this change prevent users from installing into their existing public zones?

It seems that you are demonstrating that the installer is failing to validate that a zone is private when a public zone is needed. I will try to verify this behavior.

**Comment by mjudeikis** [comment]
@patrickdillon this implies different behaviour for AWS, and GCP for the installer and this makes OSD flow difficult as now we have to have different pre-requisite flows in Hive for the same flow.

I would better like to see this being modular and configurable (default being - create DNS group)

**Pull request closed without merging**
