### PR TITLE
WIP [FCOS] pkg/asset/machines: avoid generating duplicate MC with ssh keys

### PR DESCRIPTION
**Pull request by vrutkovs**
`pkg/asset/installconfig/ssh.go` already generates MC with ssh keys.
Ignition v2 skips duplicate files, but Ignition v3 throws an error during
boot.

Duplicate ssh keys are injected in bootstrap node during `create manifests && create cluster` commands

Fixes https://github.com/openshift/okd/issues/63

### CODE REVIEW

**Comment by LorbusChris** [comment]
@vrutkovs does this mean the change should be made on master as well?

**Comment by vrutkovs** [comment]
https://github.com/openshift/installer/pull/3061

**Pull request closed without merging**
