### PR TITLE
Update vsphere permissions file

### LINKED ISSUE #5298: Additional vSphere permissions needed for IPI install
# Version

```console
$ ./openshift-install version
./openshift-install 4.8.13
built from commit 450e95767d89f809cb1afe5a142e9c824a269de8
release image quay.io/openshift-release-dev/ocp-release@sha256:5d396ad7d5f3cb527580c735e87dfd3b853bbb531e7f03e3a184d0accc223cdf
```

# Platform:

vSphere 7.0.2

IPI
# What happened?

Ran through multiple installs with errors related to permissions needed that are not documented.
```
ERROR
ERROR Error: failed to mark vm as template: ServerFaultCode: Permission to perform this operation was denied.
ERROR
ERROR   on ../../tmp/openshift-install-053661408/main.tf line 44, in resource "vsphereprivate_import_ova" "import":
ERROR   44: resource "vsphereprivate_import_ova" "import" {
ERROR
ERROR
FATAL failed to fetch Cluster: failed to generate asset "Cluster": failed to create cluster: failed to apply Terraform: failed to complete the change
```
```
ERROR
ERROR Error: error cloning virtual machine: ServerFaultCode: Permission to perform this operation was denied.
ERROR
ERROR   on ../../tmp/openshift-install-560732005/bootstrap/main.tf line 5, in resource "vsphere_virtual_machine" "vm":
ERROR    5: resource "vsphere_virtual_machine" "vm" {
ERROR
ERROR
ERROR
ERROR Error: error cloning virtual machine: ServerFaultCode: Permission to perform this operation was denied.
ERROR
ERROR   on ../../tmp/openshift-install-560732005/master/main.tf line 5, in resource "vsphere_virtual_machine" "vm":
ERROR    5: resource "vsphere_virtual_machine" "vm" {
ERROR
ERROR
ERROR
ERROR Error: error cloning virtual machine: ServerFaultCode: Permission to perform this operation was denied.
ERROR
ERROR   on ../../tmp/openshift-install-560732005/master/main.tf line 5, in resource "vsphere_virtual_machine" "vm":
ERROR    5: resource "vsphere_virtual_machine" "vm" {
ERROR
ERROR
ERROR
ERROR Error: error cloning virtual machine: ServerFaultCode: Permission to perform this operation was denied.
ERROR
ERROR   on ../../tmp/openshift-install-560732005/master/main.tf line 5, in resource "vsphere_virtual_machine" "vm":
ERROR    5: resource "vsphere_virtual_machine" "vm" {
ERROR
ERROR
FATAL failed to fetch Cluster: failed to generate asset "Cluster": failed to create cluster: failed to apply Terraform: failed to complete the change
```
Additional looking through vSphere logs determined that additional permissions were needed.
```
Privilege check failed for user VSPHERE.LOCAL\service-account for missing permission VirtualMachine.Provisioning.MarkAsTemplate.
```
```
Privilege check failed for user VSPHERE.LOCAL\service-account for missing permission VirtualMachine.Provisioning.DeployTemplate.
```

# What you expected to happen?

Installed and running Openshift cluster on my vSphere cluster

# How to reproduce it (as minimally and precisely as possible)?

Add role and service account in vSphere as described within documentation. Run through install.

# Anything else we need to know?

Permissions that need added are as follows -

`VirtualMachine.Provisioning.MarkAsTemplate`
`VirtualMachine.Provisioning.DeployTemplate`

### PR DESCRIPTION
**Pull request by aarongreen85**
This PR fixes #5298. Instead of keeping a vsphere permissions file up to date in this repo as well, updated the vsphere README to reference the permissions file in the openshif-docs repo instead.

### CODE REVIEW

**Review by staebler — COMMENTED** [review]
This is backwards from what is desired. The openshift/openshift-docs repo should be driven from the docs in the openshift/installer repo rather than the other way around.

**Comment by aarongreen85** [comment]
@staebler understood. Is there a mechanism to keep these files in sync between the 2 repos? Right now, it seems that both repos are needing to keep the same information up to date. I had the thought that it would make more sense to update in one place but if that's not how it's been then I'll update my PR to make the appropriate changes to this repo and leave the cross reference to openshift-docs out.

**Comment by staebler** [comment]
I'm not sure what the details are of whatever mechanisms there are to sync information from this repo into the official docs. I know that there are some mechanisms. It seems that this permissions table is not one of the things that is currently synced, but it seems like a good candidate to be.

**Comment by aarongreen85** [comment]
I've rebased this PR and only updated the privileges file to reflect the necessary additional permissions needed during a vSphere IPI install.

**Comment by sadasu** [comment]
@aarongreen85 & @dav1x are you still interested in this PR?

**Comment by aarongreen85** [comment]
@sadasu This PR is still valid and I think should be merged. The current documentation that this PR updates is incorrect without the following vSphere privs - 
VirtualMachine.Provisioning.DeployTemplate
VirtualMachine.Provisioning.MarkAsTemplate

**Comment by aarongreen85** [comment]
@sadasu This PR will bring this part of the docs within this repo in line with the openshift-docs repo as seen here - https://github.com/openshift/openshift-docs/blob/main/modules/installation-vsphere-installer-infra-requirements.adoc

**Pull request merged**
