### PR TITLE
CORS-3283: IBMCloud: Add IBM Cloud CAPI Cluster manifest

### PR DESCRIPTION
**Pull request by cjschaef**
Add support to create the necessary IBM Cloud VPC Cluster
manifest for CAPI.

https://issues.redhat.com/browse/CORS-3283

### CODE REVIEW

**Comment by cjschaef** [comment]
/test altinfra-e2e-ibmcloud-capi-ovn

At this point, I don't expect `alt-infra-e2e-ibmcloud-capi-ovn` nor `e2e-ibmlcoud-ovn` tests to pass, as the state of both tests are in a bad state (CAPI support isn't complete and TF based MonitorTests seem to not work as expected).

**Comment by cjschaef** [comment]
/retitle CORS-3283: IBMCloud: Add IBM Cloud CAPI Cluster manifest

**Comment by cjschaef** [comment]
`altinfra-e2e-ibmcloud-capi-ovn` test, first failure looks as expected, CAPI Machine provisioning currently does not work as expected on IBM Cloud VPC.
```
level=info msg=Creating infra manifests...
level=info msg=Created manifest *v1.Namespace, namespace= name=openshift-cluster-api-guests
level=info msg=Created manifest *v1beta1.Cluster, namespace=openshift-cluster-api-guests name=ci-op-klk7lpyj-6483a-rqbqg
level=info msg=Created manifest *v1beta2.IBMVPCCluster, namespace=openshift-cluster-api-guests name=ci-op-klk7lpyj-6483a-rqbqg
level=info msg=Done creating infra manifests
level=info msg=Creating kubeconfig entry for capi cluster ci-op-klk7lpyj-6483a-rqbqg
level=info msg=Waiting up to 15m0s (until 5:07AM UTC) for network infrastructure to become ready...
level=info msg=Network infrastructure is ready
level=info msg=Created manifest *v1beta2.IBMVPCMachine, namespace=openshift-cluster-api-guests name=ci-op-klk7lpyj-6483a-rqbqg-bootstrap
level=info msg=Created manifest *v1beta2.IBMVPCMachine, namespace=openshift-cluster-api-guests name=ci-op-klk7lpyj-6483a-rqbqg-master-0
level=info msg=Created manifest *v1beta2.IBMVPCMachine, namespace=openshift-cluster-api-guests name=ci-op-klk7lpyj-6483a-rqbqg-master-1
level=info msg=Created manifest *v1beta2.IBMVPCMachine, namespace=openshift-cluster-api-guests name=ci-op-klk7lpyj-6483a-rqbqg-master-2
level=info msg=Created manifest *v1beta1.Machine, namespace=openshift-cluster-api-guests name=ci-op-klk7lpyj-6483a-rqbqg-bootstrap
level=info msg=Created manifest *v1beta1.Machine, namespace=openshift-cluster-api-guests name=ci-op-klk7lpyj-6483a-rqbqg-master-0
level=info msg=Created manifest *v1beta1.Machine, namespace=openshift-cluster-api-guests name=ci-op-klk7lpyj-6483a-rqbqg-master-1
level=info msg=Created manifest *v1beta1.Machine, namespace=openshift-cluster-api-guests name=ci-op-klk7lpyj-6483a-rqbqg-master-2
level=info msg=Created manifest *v1.Secret, namespace=openshift-cluster-api-guests name=ci-op-klk7lpyj-6483a-rqbqg-bootstrap
level=info msg=Created manifest *v1.Secret, namespace=openshift-cluster-api-guests name=ci-op-klk7lpyj-6483a-rqbqg-master
level=info msg=Waiting up to 15m0s (until 5:12AM UTC) for machines [ci-op-klk7lpyj-6483a-rqbqg-bootstrap ci-op-klk7lpyj-6483a-rqbqg-master-0 ci-op-klk7lpyj-6483a-rqbqg-master-1 ci-op-klk7lpyj-6483a-rqbqg-master-2] to provision...
level=error msg=failed to fetch Cluster: failed to generate asset "Cluster": failed to create cluster: control-plane machines were not provisioned within 15m0s: client rate limiter Wait returned an error: context deadline exceeded
```
Other failures see on followup attempts, are due to an issue where the previous attempt's COS resources are being deleted, but the status isn't updated yet.
```
level=info msg=Reclaimed c3b9dbd4-6ba2-4aa4-aa6e-115f90af323b
level=info msg=Deleted COS instance ci-op-klk7lpyj-6483a-rqbqg-cos
```
```
level=error msg=failed to fetch Cluster: failed to generate asset "Cluster": failed to create cluster: failed during pre-provisioning: failed creating RHCOS image COS bucket: failed to create cos bucket: BucketAlreadyExists: The requested bucket name is not available. The bucket namespace is shared by all users of the system. Please select a different name and try again.
level=error msg=	status code: 409, request id: 3db4dfcb-2aa5-4c12-9cc3-3b2c8aa4732e, host id: 
Installer exit with code 4
```

Will need to resolve either the create logic in IPI, or fix wait time between `*-e2e-ibmcloud-ovn` test attempts.

**Comment by hamzy** [comment]
PowerVS cloud had problems so far.  We need a good run before I would be comfortable approving it...

**Comment by cjschaef** [comment]
@hamzy Anything specific I can do or review to see why the test failed?
Best I have found yet is
```
time="2024-10-22T12:39:23Z" level=error msg="Bootstrap failed to complete: Get \"https://api.p-mad02-0-capi-master.ipi-ppc64le.cis.ibm.net:6443/version\": dial tcp: lookup api.p-mad02-0-capi-master.ipi-ppc64le.cis.ibm.net on 172.30.0.10:53: no such host"
time="2024-10-22T12:39:23Z" level=error msg="Failed waiting for Kubernetes API. This error usually happens when there is a problem on the bootstrap host that prevents creating a temporary control plane."
time="2024-10-22T12:39:23Z" level=error msg="Invalid log bundle or the bootstrap machine could not be reached and bootstrap logs were not collected"
```
which unfortunately didn't help determine why the temp CP didn't deploy on the bootstrap node.

**Comment by hamzy** [comment]
What I look at to debug is https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_installer/9118/pull-ci-openshift-installer-master-e2e-powervs-capi-ovn/1848675214683017216/artifacts/e2e-powervs-capi-ovn/ipi-install-powervs-install/build-log.txt

The "LB MCS Pool" section is empty.  So the master nodes never got their ignition files.
The "DHCP networks" section had two entries.  Maybe a DHCP server was not cleaned up properly?

**Comment by hamzy** [comment]
When I test my own PR, I have access to the OpenShift build cluster job.  Sadly, when I test other's PRs, I don't get access.  So I can't debug in realtime with a lot more introspection.

**Comment by hamzy** [comment]
This run got farther: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_installer/9118/pull-ci-openshift-installer-master-e2e-powervs-capi-ovn/1848763105627082752/artifacts/e2e-powervs-capi-ovn/ipi-install-powervs-install/build-log.txt

I don't know why none of the Cluster Operators started.  cloud-controller-manager should have been the first.

**Comment by cjschaef** [comment]
I see the CCMO is failing to get created:
```
openshift-cloud-controller-manager-operator        13m         Warning   FailedCreate                             replicaset/cluster-cloud-controller-manager-operator-7544948bbd   Error creating: pods "cluster-cloud-controller-manager-operator-7544948bbd-" is forbidden: autoscaling.openshift.io/ManagementCPUsOverride the cluster does not have any nodes
openshift-cloud-controller-manager-operator        74s         Warning   FailedCreate                             replicaset/cluster-cloud-controller-manager-operator-7544948bbd   Error creating: pods "cluster-cloud-controller-manager-operator-7544948bbd-" is forbidden: autoscaling.openshift.io/ManagementCPUsOverride the cluster does not have any nodes
openshift-cloud-controller-manager-operator        2m56s       Warning   FailedCreate                             replicaset/cluster-cloud-controller-manager-operator-7544948bbd   Error creating: Post "https://localhost:6443/api/v1/namespaces/openshift-cloud-controller-manager-operator/pods": dial tcp [::1]:6443: connect: connection refused
```

I see the temporary CP apiserver gets restarted every 20 mins, but doesn't appear to have any other issues, at first glance.
Perhaps a connection issue between the temp CP (bootstrap) and the CP nodes?

**Comment by hamzy** [comment]
Watching this run, the master nodes cannot get their ignition files.
The internal LB is active.  The port 22623 pool has the BS node in it.  The SG allows 22623.
I don't know what else is wrong.

**Comment by hamzy** [comment]
Okay, when we get to https://github.com/openshift/installer/blob/master/pkg/infrastructure/powervs/clusterapi/powervs.go#L172 we only know about the public LB and it seems that the internal LB has not been created yet.

**Comment by hamzy** [comment]
For this run, the install step succeeded.
/lgtm

**Comment by hamzy** [comment]
@cjschaef The IBM CAPI folks asked me to test on the latest version.
https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/2026

Would you be willing to update to the latest version?

**Comment by cjschaef** [comment]
@hamzy Sure, I will try to update today, but maybe not until Monday.

**Comment by hamzy** [comment]
FYI It looks like the version you already use is close enough to main.  We still have the problem, so when they fix it,  We will need to bump again.  I'm pretty sure you will also have this problem that I am seeing.

**Comment by r4f4** [comment]
I know it's a minor bump, but let's make sure the capi bump isn't affecting any provider:

/test e2e-azure-ovn e2e-gcp-ovn e2e-nutanix-ovn e2e-vsphere-ovn

**Comment by r4f4** [comment]
Installs for all the other providers succeeded.

/approve

**Pull request merged**
