### PR TITLE
Power VS: Change server deletion criteria

### PR DESCRIPTION
**Pull request by mjturek**
Currently we only delete VMs whose names contain the InfraID. However the machine API can launch VMs that don't meet this criteria. [0]

To ensure that we delete all VMs related to a cluster, we will instead delete any VM that uses the boot image imported for the cluster.

[0] https://github.com/openshift/verification-tests/blob/b7c9c081e619c01db65aa44f6573e6f022bc30a1/features/upgrade/machines/machines.feature#L142-L156

### CODE REVIEW

**Review by mkumatag — CHANGES_REQUESTED** [review]
we shouldn't be doing this, I see a threat doing this. There are scenario where you are using the same boot image for multiple clusters or even image can be remove post installation(there is no hard dependency on keeping the image).

Rather we should delete the machinesets gracefully so that it knows how to take care of this during the uninstallation.

/hold

**Comment by mjturek** [comment]
@mkumatag I've changed this to also check the network that's used. Basically if a server uses any resource that was created for the cluster, it will get deleted.

**Comment by AshwinHIBM** [comment]
lgtm

**Review by barbacbd — COMMENTED** [review]
Is it possible to tag/label these instances and use that as a lookup?

**Comment by sadasu** [comment]
@mjturek do you still need these changes?

**Comment by mjturek** [comment]
> @mjturek do you still need these changes?

I think we can close this one for now. We could not come to a consensus on the right solution here. If we decide on the correct implementation in the future, we'll open a new PR. Thanks!

**Pull request closed without merging**
