### PR TITLE
Bug 1827667: openstack: Add jq to the CI image

### PR DESCRIPTION
**Pull request by pierreprinetti**
Using jq will simplify the CI scripts where we currently use `awk` to parse JSON.

### CODE REVIEW

**Comment by pierreprinetti** [comment]
/retitle Bug 1827667: openstack: Add jq to the CI image

**Comment by pierreprinetti** [comment]
Installing from the Centos7 RDO repository gives the same [dependency mismatch](https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_installer/3503/pull-ci-openshift-installer-master-images/9285/build-log.txt) than with the stock repositories.

Installing from URL with checksum.

**Comment by pierreprinetti** [comment]
/test e2e-openstack-upi
just for fun

**Comment by mandre** [comment]
> Installing from the Centos7 RDO repository gives the same [dependency mismatch](https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_installer/3503/pull-ci-openshift-installer-master-images/9285/build-log.txt) than with the stock repositories.
> 
> Installing from URL with checksum.

It's still trying to install jq from the `rhel-server-ose` repository:

Error: Package: jq-1.6-2.el7.x86_64 (@rhel-server-ose)

You might need to do:
```
yum install --setopt=tsflags=nodocs --disablerepo="*" --enablerepo=delorean-master-build-deps -y jq
```

**Pull request merged**
