### PR TITLE
Bug 1826475: baremetal: vendor: bump baremetal-operator to include latest hardware profiles

### PR DESCRIPTION
**Pull request by honza**
We are upgrading the openshift/baremetal-operator dependency to
https://github.com/openshift/baremetal-operator/commit/d24ad611372b0ca5cb15b81f950f32664212daf8.  This is done by updating the
entry in the `replace` clause of the go.mod file.  Then, we run `go mod
tidy`, followed by `go mod vendor`.  This breaks because the requested
version of google.golang.org/grpc, v1.27.0, changes the API in
backwards-incompatible ways.  Thus, we also include a new pin for this
dependency to the previously requested version, v1.25.0, which yields a
working build.

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
I'm failing to see why this bump is required? Esp during freeze we were would like to keep bumps to the minimum.

The attached bz also doesn't provide the details.

**Comment by honza** [comment]
> The attached bz also doesn't provide the details.

The BZ actually blocks [1826418](https://bugzilla.redhat.com/show_bug.cgi?id=1826418). We've added an [Openstack profile](https://github.com/metal3-io/baremetal-operator/pull/486), and we're integrating it into the installer here.

**Comment by stbenjam** [comment]
Since we don't have configurable root devices yet, we needed a profile to support some people testing the platform on openstack (cc: @schmaustech). This could probably wait to merge until 4.6 is open, but I know the folks who were using this were requesting it be backported all the way to 4.4.

**Comment by schmaustech** [comment]
Just to add more detail:  The addition of the Openstack profile will enable hackfests, labs and GPTE enabled training for OCP Baremetal IPI in an OpenStack cloud.

**Comment by abhinavdahiya** [comment]
> Just to add more detail: The addition of the Openstack profile will enable hackfests, labs and GPTE enabled training for OCP Baremetal IPI in an OpenStack cloud.

If you can include a summary of what steps these are in the PR desciption, it will be a lot clearer what this vendor enables, since this there is no actual code change that would show how in usual cases.

**Comment by schmaustech** [comment]
@abhinavdahiya I am not clear exactly what you are looking but if you look at the PR for the BMO [https://github.com/openshift/baremetal-operator/pull/62](https://github.com/openshift/baremetal-operator/pull/62)  - that is the exact same modification one needs to do to the installer in order to enable the openstack profile which references the vdb device needed in order to perform a OCP baremetal IPI install inside of Openstack.

**Comment by stbenjam** [comment]
@honza If you want to update the reasoning to include something like, "This updates baremetal-operator to pull in the latest changes including hardware profiles. The installer vendors hardware profiles from baremetal-operator to keep the interface the same between terraform-provisioned baremetal hosts and those provisioned by the machine-api"

**Comment by honza** [comment]
Commit message updated

**Comment by stbenjam** [comment]
> /test e2e-metal-ipi

There's some on-going etcd issues that probably won't be resolved until early next week. I'd like to see this pass though before merging it.

**Comment by sdodson** [comment]
@honza Needs rebase.

**Comment by honza** [comment]
Now using a newer commit https://github.com/openshift/baremetal-operator/commit/d997d9c06ba813739373a40e975140c90360a5e1

**Comment by honza** [comment]
/test e2e-aws-scaleup-rhel7

Looks pretty green to me at this point

**Pull request merged**
