### PR TITLE
assets/manifests: add Scheduler to operator dependencies

### PR DESCRIPTION
**Pull request by sjenning**
forgot this in https://github.com/openshift/installer/pull/1405

@abhinavdahiya @wking @ravisantoshgudimetla

### CODE REVIEW

**Comment by wking** [comment]
I still don't see it in the bootstrap Ignition config

```console
$ curl -s https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_in
staller/1461/pull-ci-openshift-installer-master-e2e-aws/4625/artifacts/e2e-aws/installer/.openshift_install.log | grep -o '\(manifests\|openshift\)/[^.]*\.yaml'
openshift/manifests/04-openshift-machine-config-operator.yaml
openshift/manifests/cluster-config.yaml
openshift/manifests/cvo-overrides.yaml
openshift/manifests/etcd-service.yaml
openshift/manifests/host-etcd-service-endpoints.yaml
openshift/manifests/host-etcd-service.yaml
openshift/manifests/kube-cloud-config.yaml
openshift/manifests/kube-system-configmap-etcd-ca-bundle.yaml
openshift/manifests/kube-system-configmap-etcd-serving-ca.yaml
openshift/manifests/kube-system-configmap-root-ca.yaml
openshift/manifests/kube-system-secret-etcd-client-ca-deprecated.yaml
openshift/manifests/kube-system-secret-etcd-client.yaml
openshift/manifests/kube-system-secret-etcd-signer-client.yaml
openshift/manifests/kube-system-secret-etcd-signer.yaml
openshift/manifests/machine-config-server-tls-secret.yaml
openshift/manifests/openshift-config-configmap-etcd-metrics-serving-ca.yaml
openshift/manifests/openshift-config-secret-etcd-metrics-client.yaml
openshift/openshift/99_binding-discovery.yaml
openshift/openshift/99_cloud-creds-secret.yaml
openshift/openshift/99_kubeadmin-password-secret.yaml
openshift/openshift/99_openshift-cluster-api_worker-machineset.yaml
openshift/openshift/99_openshift-cluster-api_worker-user-data-secret.yaml
openshift/openshift/99_role-cloud-creds-secret-reader.yaml
openshift/openshift/99_openshift-cluster-api_master-user-data-secret.yaml
openshift/openshift/99_openshift-cluster-api_master-machines-0.yaml
openshift/openshift/99_openshift-cluster-api_master-machines-1.yaml
openshift/openshift/99_openshift-cluster-api_master-machines-2.yaml
```

I can work up a fixup tomorrow.

**Comment by sjenning** [comment]
@wking I think it worked.  From the e2e installer log:
```
time="2019-03-26T03:48:44Z" level=debug msg="        Loading \"Install Config\"..."
time="2019-03-26T03:48:44Z" level=debug msg="        Loading \"Network CRDs\"..."
time="2019-03-26T03:48:44Z" level=debug msg="      Loading \"Scheduler Config\"..." <---
time="2019-03-26T03:48:44Z" level=debug msg="      Loading \"Root CA\"..."
time="2019-03-26T03:48:44Z" level=debug msg="      Loading \"Certificate (etcd)\"..."
```

**Comment by wking** [comment]
You built the asset, but didn't include it in the Ignition config, so it's just sitting on your install host.

**Comment by wking** [comment]
[test-platform flake][1]:

```
could not wait for template instance to be ready: could not determine if template instance was ready: failed to create objects: object is being deleted: pods "e2e-aws" already exists
```

/retest

[1]: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_installer/1461/pull-ci-openshift-installer-master-e2e-aws/4750

**Comment by sjenning** [comment]
i think prow missed this
/retest

**Comment by sjenning** [comment]
e2e-aws is in shambles :disappointed:

**Comment by wking** [comment]
[e2e-aws][1]:

```
level=fatal msg="failed to wait for bootstrap-complete event: timed out waiting for the condition"
```

/retest

[1]: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_installer/1461/pull-ci-openshift-installer-master-e2e-aws/4755

**Comment by wking** [comment]
Hrm [bootstrap-complete timeout again][1].  Maybe its real, and not a flake?

[1]: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_installer/1461/pull-ci-openshift-installer-master-e2e-aws/4772

**Comment by sjenning** [comment]
superseded by https://github.com/openshift/cluster-config-operator/pull/36

**Comment by sjenning** [comment]
nevermind, we still need this

**Comment by sjenning** [comment]
nope, wrong again

**Pull request closed without merging**
