### PR TITLE
Fix ineffassign

### PR DESCRIPTION
**Pull request by zhouhao3**

### CODE REVIEW

**Comment by zhouhao3** [comment]
@staebler rebased, PTAL

**Comment by sadasu** [comment]
/lgtm
Rebase earlier removed it. So adding it back.

**Comment by sadasu** [comment]
/hold
Need https://github.com/openshift/release/pull/30871 to merge for the aws-upi job to pass

**Comment by sadasu** [comment]
/skip
The change is in aws destroy code and has nothing to do with the azure UPI failure.

**Pull request merged**
