### PR TITLE
data/rhcos.json: Update boot images

### PR DESCRIPTION
**Pull request by ashcrow**
- amd64:   47.83.202102050944-0
- s390x:   47.83.202102051212-0
- ppc64le: 47.83.202102051010-0

I will open related backports shortly as well.

### CODE REVIEW

**Comment by andymcc** [comment]
/lgtm
Versions across architectures match up - from a package version perspective.

**Review by andymcc — APPROVED** [review]

**Review by staebler — COMMENTED** [review]
/approve

**Comment by miabbott** [comment]
/approve

Looks sane to me

**Comment by ashcrow** [comment]
This will be replaced with a new build shortly.

**Pull request closed without merging**
