### PR TITLE
*: Drop Jenkins

### PR DESCRIPTION
**Pull request by wking**
Builds on #229, review that first.

Since openshift/release#1317 we've been running the smoke tests on AWS via Prow, so we can drop our Jenkins bindings.  This commit also drops Dockerfiles for some images which have been supplanted in Prow by #223.

CC @sallyom

### CODE REVIEW

**Comment by crawford** [comment]
/lgtm

@openshift-ci-robot you're not the boss of me!

**Comment by wking** [comment]
[The smoke error][1]:

```
Waiting for API at https://ci-op-lnd42lyr-b28c4-api.origin-ci-int-aws.dev.rhcloud.com:6443 to respond ...
Interrupted
```

/retest

[1]: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_installer/230/pull-ci-origin-installer-e2e-aws-smoke/31/build-log.txt

**Pull request merged**
