### PR TITLE
WIP: RHCOS without LUKS

### PR DESCRIPTION
**Pull request by darkmuggle**
TEST -- DO NOT MERGE UNDER ANY CIRCUMSTANCES -- TEST
Modern RHCOS with LUKS code paths disabled.

Hack to test:
https://bugzilla.redhat.com/show_bug.cgi?id=1775878

/hold

### CODE REVIEW

**Comment by wking** [comment]
[e2e-aws][1]:

```
level=error msg="Error: InvalidRequest: You do not have permission to access the storage of this ami" level=error msg="\tstatus code: 400, request id: cf738c8e-483d-489d-8218-1689607a4c51"
```

So still can't reach this AMI.

[1]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_installer/2816/pull-ci-openshift-installer-master-e2e-aws/9068

**Comment by cgwalters** [comment]
Looks like the bootstrap failed to come up at all in that one?

**Comment by cgwalters** [comment]
/hold
I bet I know why this is broken; going to do a build myself.

**Comment by cgwalters** [comment]
I took a swing at this in https://github.com/openshift/installer/pull/2824

**Pull request closed without merging**
