### PR TITLE
Bug 1793618: Bump RHCOS to 43.81.202002131553.0

### PR DESCRIPTION
**Pull request by jlebon**
```
./hack/update-rhcos-bootimage.py https://releases-art-rhcos.svc.ci.openshift.org/art/storage/releases/rhcos-4.3/43.81.202002131553.0/x86_64/meta.json
```

Notably, this includes a fix for IPv6 single-stack:
https://bugzilla.redhat.com/show_bug.cgi?id=1793618

```
$ ./differ.py --first-endpoint art --first-version 43.81.202001142154.0 --second-endpoint art --second-version 43.81.202002131553.0
{
    "sources": {
        "43.81.202001142154.0": "https://releases-rhcos-art.cloud.privileged.psi.redhat.com/storage/releases/rhcos-4.3/43.81.202001142154.0/x86_64/commitmeta.json",
        "43.81.202002131553.0": "https://releases-rhcos-art.cloud.privileged.psi.redhat.com/storage/releases/rhcos-4.3/43.81.202002131553.0/x86_64/commitmeta.json"
    },
    "diff": {
        "container-selinux": {
            "43.81.202001142154.0": "container-selinux-2.124.0-1.el8.noarch",
            "43.81.202002131553.0": "container-selinux-2.124.0-1.module+el8.1.1+5259+bcdd613a.noarch"
        },
        "containernetworking-plugins": {
            "43.81.202001142154.0": "containernetworking-plugins-0.8.3-1.el8.x86_64",
            "43.81.202002131553.0": "containernetworking-plugins-0.8.3-4.module+el8.1.1+5259+bcdd613a.x86_64"
        },
        "containers-common": {
            "43.81.202001142154.0": "containers-common-0.1.40-2.el8.x86_64",
            "43.81.202002131553.0": "containers-common-0.1.40-8.module+el8.1.1+5351+506397b0.x86_64"
        },
        "cri-o": {
            "43.81.202001142154.0": "cri-o-1.16.2-6.dev.rhaos4.3.git9e3db66.el8.x86_64",
            "43.81.202002131553.0": "cri-o-1.16.3-19.dev.rhaos4.3.git6c1f4bd.el8.x86_64"
        },
        "dracut": {
            "43.81.202001142154.0": "dracut-049-27.git20190906.el8_1.1.x86_64",
            "43.81.202002131553.0": "dracut-049-64.git20200123.el8.x86_64"
        },
        "dracut-network": {
            "43.81.202001142154.0": "dracut-network-049-27.git20190906.el8_1.1.x86_64",
            "43.81.202002131553.0": "dracut-network-049-64.git20200123.el8.x86_64"
        },
        "fuse-overlayfs": {
            "43.81.202001142154.0": "fuse-overlayfs-0.4.1-1.module+el8.1.0+4081+b29780af.x86_64",
            "43.81.202002131553.0": "fuse-overlayfs-0.7.2-1.module+el8.1.1+5259+bcdd613a.x86_64"
        },
        "glibc": {
            "43.81.202001142154.0": "glibc-2.28-72.el8.x86_64",
            "43.81.202002131553.0": "glibc-2.28-72.el8_1.1.x86_64"
        },
        "glibc-all-langpacks": {
            "43.81.202001142154.0": "glibc-all-langpacks-2.28-72.el8.x86_64",
            "43.81.202002131553.0": "glibc-all-langpacks-2.28-72.el8_1.1.x86_64"
        },
        "glibc-common": {
            "43.81.202001142154.0": "glibc-common-2.28-72.el8.x86_64",
            "43.81.202002131553.0": "glibc-common-2.28-72.el8_1.1.x86_64"
        },
        "grub2-common": {
            "43.81.202001142154.0": "grub2-common-2.02-78.el8.noarch",
            "43.81.202002131553.0": "grub2-common-2.02-78.el8_1.1.noarch"
        },
        "grub2-efi-x64": {
            "43.81.202001142154.0": "grub2-efi-x64-2.02-78.el8.x86_64",
            "43.81.202002131553.0": "grub2-efi-x64-2.02-78.el8_1.1.x86_64"
        },
        "grub2-pc": {
            "43.81.202001142154.0": "grub2-pc-2.02-78.el8.x86_64",
            "43.81.202002131553.0": "grub2-pc-2.02-78.el8_1.1.x86_64"
        },
        "grub2-pc-modules": {
            "43.81.202001142154.0": "grub2-pc-modules-2.02-78.el8.noarch",
            "43.81.202002131553.0": "grub2-pc-modules-2.02-78.el8_1.1.noarch"
        },
        "grub2-tools": {
            "43.81.202001142154.0": "grub2-tools-2.02-78.el8.x86_64",
            "43.81.202002131553.0": "grub2-tools-2.02-78.el8_1.1.x86_64"
        },
        "grub2-tools-extra": {
            "43.81.202001142154.0": "grub2-tools-extra-2.02-78.el8.x86_64",
            "43.81.202002131553.0": "grub2-tools-extra-2.02-78.el8_1.1.x86_64"
        },
        "grub2-tools-minimal": {
            "43.81.202001142154.0": "grub2-tools-minimal-2.02-78.el8.x86_64",
            "43.81.202002131553.0": "grub2-tools-minimal-2.02-78.el8_1.1.x86_64"
        },
        "ignition": {
            "43.81.202001142154.0": "ignition-0.34.0-1.rhaos4.3.git92f874c.el8.x86_64",
            "43.81.202002131553.0": "ignition-0.34.0-2.rhaos4.3.git92f874c.el8.x86_64"
        },
        "kernel": {
            "43.81.202001142154.0": "kernel-4.18.0-147.3.1.el8_1.x86_64",
            "43.81.202002131553.0": "kernel-4.18.0-147.5.1.el8_1.x86_64"
        },
        "kernel-core": {
            "43.81.202001142154.0": "kernel-core-4.18.0-147.3.1.el8_1.x86_64",
            "43.81.202002131553.0": "kernel-core-4.18.0-147.5.1.el8_1.x86_64"
        },
        "kernel-modules": {
            "43.81.202001142154.0": "kernel-modules-4.18.0-147.3.1.el8_1.x86_64",
            "43.81.202002131553.0": "kernel-modules-4.18.0-147.5.1.el8_1.x86_64"
        },
        "kernel-modules-extra": {
            "43.81.202001142154.0": "kernel-modules-extra-4.18.0-147.3.1.el8_1.x86_64",
            "43.81.202002131553.0": "kernel-modules-extra-4.18.0-147.5.1.el8_1.x86_64"
        },
        "libarchive": {
            "43.81.202001142154.0": "libarchive-3.3.2-7.el8.x86_64",
            "43.81.202002131553.0": "libarchive-3.3.2-8.el8_1.x86_64"
        },
        "machine-config-daemon": {
            "43.81.202001142154.0": "machine-config-daemon-4.3.0-202001131753.git.1.e2edc36.el8.x86_64",
            "43.81.202002131553.0": "machine-config-daemon-4.3.2-202002100501.git.1.c04d5aa.el8.x86_64"
        },
        "openldap": {
            "43.81.202001142154.0": "openldap-2.4.46-10.el8.x86_64",
            "43.81.202002131553.0": "openldap-2.4.46-11.el8_1.x86_64"
        },
        "openshift-clients": {
            "43.81.202001142154.0": "openshift-clients-4.3.0-202001030600.git.1.5e09fe6.el8.x86_64",
            "43.81.202002131553.0": "openshift-clients-4.3.2-202002070552.git.1.a322635.el8.x86_64"
        },
        "openshift-hyperkube": {
            "43.81.202001142154.0": "openshift-hyperkube-4.3.0-202001131753.git.0.0aee6a8.el8.x86_64",
            "43.81.202002131553.0": "openshift-hyperkube-4.3.2-202002091901.git.0.f9fe502.el8.x86_64"
        },
        "openssh": {
            "43.81.202001142154.0": "openssh-8.0p1-3.el8.x86_64",
            "43.81.202002131553.0": "openssh-8.0p1-4.el8_1.x86_64"
        },
        "openssh-clients": {
            "43.81.202001142154.0": "openssh-clients-8.0p1-3.el8.x86_64",
            "43.81.202002131553.0": "openssh-clients-8.0p1-4.el8_1.x86_64"
        },
        "openssh-server": {
            "43.81.202001142154.0": "openssh-server-8.0p1-3.el8.x86_64",
            "43.81.202002131553.0": "openssh-server-8.0p1-4.el8_1.x86_64"
        },
        "openvswitch2.11": {
            "43.81.202001142154.0": "openvswitch2.11-2.11.0-35.el8fdp.x86_64",
            "43.81.202002131553.0": "openvswitch2.11-2.11.0-47.el8fdp.x86_64"
        },
        "podman": {
            "43.81.202001142154.0": "podman-1.6.4-1.el8.x86_64",
            "43.81.202002131553.0": "podman-1.6.4-2.module+el8.1.1+5363+bf8ff1af.x86_64"
        },
        "podman-manpages": {
            "43.81.202001142154.0": "podman-manpages-1.6.4-1.el8.noarch",
            "43.81.202002131553.0": "podman-manpages-1.6.4-2.module+el8.1.1+5363+bf8ff1af.noarch"
        },
        "policycoreutils": {
            "43.81.202001142154.0": "policycoreutils-2.9-3.el8.x86_64",
            "43.81.202002131553.0": "policycoreutils-2.9-3.el8_1.1.x86_64"
        },
        "policycoreutils-python-utils": {
            "43.81.202001142154.0": "policycoreutils-python-utils-2.9-3.el8.noarch",
            "43.81.202002131553.0": "policycoreutils-python-utils-2.9-3.el8_1.1.noarch"
        },
        "python3-policycoreutils": {
            "43.81.202001142154.0": "python3-policycoreutils-2.9-3.el8.noarch",
            "43.81.202002131553.0": "python3-policycoreutils-2.9-3.el8_1.1.noarch"
        },
        "runc": {
            "43.81.202001142154.0": "runc-1.0.0-64.rc9.el8.x86_64",
            "43.81.202002131553.0": "runc-1.0.0-64.rc9.module+el8.1.1+5259+bcdd613a.x86_64"
        },
        "skopeo": {
            "43.81.202001142154.0": "skopeo-0.1.40-2.el8.x86_64",
            "43.81.202002131553.0": "skopeo-0.1.40-8.module+el8.1.1+5351+506397b0.x86_64"
        },
        "slirp4netns": {
            "43.81.202001142154.0": "slirp4netns-0.4.2-1.git21fdece.el8.x86_64",
            "43.81.202002131553.0": "slirp4netns-0.4.2-4.git21fdece.el8.x86_64"
        },
        "sqlite-libs": {
            "43.81.202001142154.0": "sqlite-libs-3.26.0-3.el8.x86_64",
            "43.81.202002131553.0": "sqlite-libs-3.26.0-4.el8_1.x86_64"
        },
        "sudo": {
            "43.81.202001142154.0": "sudo-1.8.25p1-8.el8_1.x86_64",
            "43.81.202002131553.0": "sudo-1.8.25p1-8.el8_1.1.x86_64"
        },
        "systemd": {
            "43.81.202001142154.0": "systemd-239-18.el8_1.1.x86_64",
            "43.81.202002131553.0": "systemd-239-18.el8_1.2.x86_64"
        },
        "systemd-journal-remote": {
            "43.81.202001142154.0": "systemd-journal-remote-239-18.el8_1.1.x86_64",
            "43.81.202002131553.0": "systemd-journal-remote-239-18.el8_1.2.x86_64"
        },
        "systemd-libs": {
            "43.81.202001142154.0": "systemd-libs-239-18.el8_1.1.x86_64",
            "43.81.202002131553.0": "systemd-libs-239-18.el8_1.2.x86_64"
        },
        "systemd-pam": {
            "43.81.202001142154.0": "systemd-pam-239-18.el8_1.1.x86_64",
            "43.81.202002131553.0": "systemd-pam-239-18.el8_1.2.x86_64"
        },
        "systemd-udev": {
            "43.81.202001142154.0": "systemd-udev-239-18.el8_1.1.x86_64",
            "43.81.202002131553.0": "systemd-udev-239-18.el8_1.2.x86_64"
        },
        "toolbox": {
            "43.81.202001142154.0": "toolbox-0.0.5-1.rhaos4.2.el8.noarch",
            "43.81.202002131553.0": "toolbox-0.0.6-1.rhaos4.3.el8.noarch"
        }
    }
}
```

### CODE REVIEW

**Comment by miabbott** [comment]
HItting 404s trying to build the installer:

```
http://base-4-3.ocp.svc/rhel-server-ose/repodata/5777b95147aad9827fc449cd8d54059cd0db42d32d8d90159b01cf8b47ad3bf7-primary.sqlite.bz2: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
To address this issue please refer to the below knowledge base article 

https://access.redhat.com/articles/1320623

If above article doesn't help to resolve this issue please open a ticket with Red Hat Support.

http://base-4-3.ocp.svc/rhel-server-ose/repodata/5777b95147aad9827fc449cd8d54059cd0db42d32d8d90159b01cf8b47ad3bf7-primary.sqlite.bz2: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
http://base-4-3.ocp.svc/rhel-server-ose/repodata/5777b95147aad9827fc449cd8d54059cd0db42d32d8d90159b01cf8b47ad3bf7-primary.sqlite.bz2: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
```

**Comment by jlebon** [comment]
Closing this. Will open a separate one with updated bootimages once the ipv4/ipv6 regressions have been addressed.

**Pull request closed without merging**
