### PR TITLE
Bug 1824172: enable ppc64le & s390x bootimage support

### PR DESCRIPTION
**Pull request by andymcc**
This is a port of the 2 PRs:

b7d7474
d27e3d7

### CODE REVIEW

**Comment by crawford** [comment]
This is missing changes to `rhcos.json`.

/hold

Are any of the other commits from the original PRs needed?

**Comment by andymcc** [comment]
@crawford for 4.5+ we'll need to rework the terraform libvirt provider PR ( https://github.com/openshift/installer/commit/791f248d8675c8ae44af46778497eaa65fd70eae ) - otherwise that should be it, as far as we know. The rhcos.json images are not ready for 4.5 on s390x just yet thats why they aren't included here.
My aim was to get the machinery required to make those files and the other required PRs in to master so they can then be backported cleanly to 4.4 - but if you'd prefer we can hold off on 4.5+ and just focus on 4.4, until we have everything ready and do 1 big PR including all the other commits when the time comes?

**Comment by andymcc** [comment]
I've fixed up the backports properly - and added the rhcos file for ppc64le. We could hold this until the 4.5 for s390x are building and do it in 1 go.
I'll also be working on the terraform libvirt fix which is the last change i believe required.

**Comment by Prashanth684** [comment]
@crawford can the hold be removed on this. the rhcos images are included and all tests passed.

**Comment by wking** [comment]
Trying to understand the forward-picks from #2933 and #3233, I see:

* 45de9b95c (4.2, #2933), 05a3e852d (4.3, #2463), 05a3e852d (4.4, master, #2463)
* efaeb0c06 (4.2, #2933), be27b9470 (4.3, #3233), 8428471c6 (4.4, master, #2885)
* f283ffc56 (4.2, #2933), 84d91bc81 (4.3, #3233), b1726d2c5 (4.4, master, #2885)
* ceabdbe67 (4.2, #2933), 63e788234 (4.3, #3233), 2583ba4df (4.4, master, #2885)
* b7d747408 (4.2, #2933), a7dc41cc4 (4.3, #3233), 4.4 in flight with #3457, 928ab9022
* b1381e5f9 (4.2, #2933), 77dfa336f (4.3, #3233), 4.4 in flight with #3457, a8a48b4a1 (obviously using different RHCOS data)
* d27e3d748 (4.3, #3233), 4.4 in flight with #3457, 923e55162
* 84608d9fd (4.3, #3233), 4.4 in flight with #3457, b11dca010 (obviously using different RHCOS data)
* 4.4 in flight with #3457, 25e0be9ae
* 4.4 in flight with #3457, 0c50e71ad
* Similar bump in flight for 4.4 with #3457, c5726a461

**Comment by wking** [comment]
Ah, 4.3's 84608d9 was split in this PR, feeding both b11dca0 and 25e0be9.

nit: commit message for 25e0be9 has "(cherry picked from commit 28fb0bd)", but should probably be talking about 84608d9, because 28fb0bd is not a commit from any production installer branch or PR.

**Comment by wking** [comment]
I'm a bit fuzzy on vendor bumps, but all the other commits look good to me, and @crawford's concerns have been addressed.

/lgtm
/approve
/hold cancel

**Comment by Prashanth684** [comment]
> Ah, 4.3's [84608d9](https://github.com/openshift/installer/commit/84608d9fd4cedc599f077d1b7cc3cd1a4cf8ec03) was split in this PR, feeding both [b11dca0](https://github.com/openshift/installer/commit/b11dca010576d5deeeacbe91b0af7a6a122d5158) and [25e0be9](https://github.com/openshift/installer/commit/25e0be9aeb3e3a903af5510dda92e2c54f6dddd7).
> 
> nit: commit message for [25e0be9](https://github.com/openshift/installer/commit/25e0be9aeb3e3a903af5510dda92e2c54f6dddd7) has "(cherry picked from commit [28fb0bd](https://github.com/openshift/installer/commit/28fb0bd40ce2071ca2bc3768fb20591895a4d559))", but should probably be talking about [84608d9](https://github.com/openshift/installer/commit/84608d9fd4cedc599f077d1b7cc3cd1a4cf8ec03), because [28fb0bd](https://github.com/openshift/installer/commit/28fb0bd40ce2071ca2bc3768fb20591895a4d559) is not a commit from any production installer branch or PR.

Yes 4.3 did not have any of the initial commits for the bootimage support whereas 4.4 already had it (as it was master at the time @crawford 's initial PR landed). So what was needed for 4.4 was the addition of the rhcos images and the terraform bump.

**Pull request merged**
