### PR TITLE
no-jira: destroy/azure: avoid cancelling main context

### PR DESCRIPTION
**Pull request by r4f4**
Instead of using `wait.UntilWithContext` and cancelling than recreating the main context, let's use `wait.PollUntilContextCancel` which takes a callback function returning true/false to signify whether the callback is done.

### CODE REVIEW

**Comment by r4f4** [comment]
Update: dropped a `errors.Wrap` -> `fmt.Errorf` change. I can add that as a separate commit or in a follow-up PR.

**Comment by flavianmissi** [comment]
Nice!
I'm still confused about the deferring though... We are overriding `waitCtx` (the parent) with a new context, which also gives it a new `cancel`, but we are not deferring that because we already defer the parent `cancel`.
It's correct that the parent cancel will also cause the children contexts to be cancelled, but it is also harmless to defer the cancel call for each child context.
What am I missing? 🤔

**Comment by r4f4** [comment]
> Nice! I'm still confused about the deferring though... We are overriding `waitCtx` (the parent) with a new context, which also gives it a new `cancel`, but we are not deferring that because we already defer the parent `cancel`. It's correct that the parent cancel will also cause the children contexts to be cancelled, but it is also harmless to defer the cancel call for each child context. What am I missing? 🤔

IIUC, in the previous code, `cancel` was being called inside `wait.UntilWithContext` to signify the wait was over. Therefore, a new context was created and its cancel closure was then re-assigned to `cancel`. Think of the _variable_ `cancel` as a pointer to a closure and the closure it points to changed every time we created a new context. If I'm wrong on this assessment, then the code was wrong and this PR should fix it.

**Comment by flavianmissi** [comment]
aha, right that makes sense!

**Comment by flavianmissi** [comment]
@r4f4 do you intend to merge this before https://github.com/openshift/installer/pull/7611? just wondering how to handle the context cancellation there meanwhile.

**Review by barbacbd — COMMENTED** [review]
/lgtm

We should consider moving this other destroy code blocks.

**Comment by r4f4** [comment]
/retitle no-jira: destroy/azure: avoid cancelling main context

**Pull request merged**
