### PR TITLE
images: Cleanup CI Dockerfiles

### PR DESCRIPTION
**Pull request by LorbusChris**
- remove unused Dockerfile.ci.rhel7
- replace Dockerfile.upi.ci with Dockerfile.upi.ci.rhel8
- replace Dockerfile.upi.ci.rhel8 with symlink to Dockerfile.upi.ci
- update to FROM directives to pull from registry.ci.openshift.org/ocp/4.15

Requires: https://github.com/openshift/release/pull/43624

### CODE REVIEW

**Comment by LorbusChris** [comment]
Looks like the config fixups might have to go in first, so OKD/FCOS' upi-installer isn't getting a 4.10 base...

**Comment by LorbusChris** [comment]
/hold 
now needs https://github.com/openshift/release/pull/43557 first

**Comment by LorbusChris** [comment]
/assign @andfasano 

for approval and LGTM

**Comment by sadasu** [comment]
@LorbusChris, @andfasano, do these changes need to be back ported to older versions (4.14)? In that case, we would need a Jira issue opened for this to facilitate the backport.

**Comment by LorbusChris** [comment]
> @LorbusChris, @andfasano, do these changes need to be back ported to older versions (4.14)? In that case, we would need a Jira issue opened for this to facilitate the backport.

@sadasu not sure it's required. are you seeing the okd-images failures on release-4.14? Do you have an example link?

**Comment by LorbusChris** [comment]
This PR was not really supposed fix a known issue. It's solely a cleanup change with no intended functional effect, and I'm not sure it'll fix the issue.

This PR was made before the `-amd64` image-name suffixes were introduced, so is it still adequate?

let's
/retest okd-images
/retest okd-scos-images

**Comment by sadasu** [comment]
> This PR was not really supposed fix a known issue. It's solely a cleanup change with no intended functional effect, and I'm not sure it'll fix the issue.
> 
I noticed that the upi-installer-amd64 images were failing at:
https://github.com/openshift/installer/pull/7507/files#diff-b6825bbac221d8a688bd04adf109e93e31ddbc78198db9a1859a59f793272e3fL28. Since your changes are removing that install step, I am hopeful that okd-images would have a better success rate (it is currently not perma-failing). 

> This PR was made before the `-amd64` image-name suffixes were introduced, so is it still adequate?
> 
I am not sure it is adequate.

**Comment by LorbusChris** [comment]
I think you're right. Something's definitely up with the upi images. Let's see :crossed_fingers:

**Comment by LorbusChris** [comment]
@sadasu looks like this does indeed fix the image builds.

/retest-required

**Comment by sadasu** [comment]
@LorbusChris
1.  Both upi image builds that are failing have the same error:
`operator "cluster-network-operator" contained an invalid image-references file: no input image tag named "kuryr-cni"`
2. Do you want to create a Jira issue so that these changes can be backported?

**Comment by r4f4** [comment]
`e2e-gcp-ovn-upi`: just a few e2e failures. I can see similiar failures in the periodic job: https://testgrid.k8s.io/redhat-openshift-ocp-release-4.15-informing#periodic-ci-openshift-release-master-nightly-4.15-e2e-gcp-ovn-upi
`e2e-azure-ovn-upi`: just a few e2e failures. Similar to those in the periodic job: https://testgrid.k8s.io/redhat-openshift-ocp-release-4.15-informing#periodic-ci-openshift-release-master-nightly-4.15-e2e-azure-ovn-upi

They don't look related to the PR changes.

**Comment by LorbusChris** [comment]
@sadasu looks like the kuryr image issue was resolved? (It looks like it's a new image that hadn't made it into OKD yet - OKD imagestreams are currently gated by OCP CI releases, so they only get updated upon a successful OCP CI releaase. The image is in the OKD 4.15 IS now: https://console-openshift-console.apps.ci.l2s4.p1.openshiftapps.com/k8s/ns/origin/imagestreams/scos-4.15)

**Comment by LorbusChris** [comment]
The `e2e-azure-ovn-upi` test hasn't succeeded in ages, the failure looks unrelated to me.
Prow requires it though, so let's
/retest-required

**Comment by r4f4** [comment]
/override ci/prow/e2e-openstack-ovn
Previous run had one e2e test failure not related to this PR.

**Pull request merged**
