### PR TITLE
bug 1925343: upi/metal: add more configuration options for bare metal

### PR DESCRIPTION
**Pull request by staebler**
Allow facilities, plan and hardware_reservation_id to be configured.

### CODE REVIEW

**Comment by staebler** [comment]
@jhixson74 This is working now. I've run 3 installs without issue. I did not change anything, so I don't have any clue why it was always failing before. I confirm that the machines are being created in ny5 using reserved c3.small.x86 instances.

**Review by mtnbikenc — APPROVED** [review]
/lgtm

**Pull request merged**
