### PR TITLE
no-jira: doc: minor update to installation doc

### PR DESCRIPTION
**Pull request by radeksm**
1. Replace yum by dnf.
2. Add zip to installation dependencies as it's really needed and not installed by default.
3. Update requitred golang version in does base what is currently in go.mod.

### CODE REVIEW

**Comment by r4f4** [comment]
/retitle no-jira: doc: minor update to installation doc

**Review by r4f4 — COMMENTED** [review]
/lgtm

Thank you for the contribution!

**Comment by radeksm** [comment]
Looks like pipelines failed because of 
```
received unexpected HTTP status: 504 Gateway Time-out
```

/retest please

**Comment by radeksm** [comment]
CI still failing on:
`error: unable to read image registry.build02.ci.openshift.org/ci-op-z3c6zrd3/stable@sha256:ba92bac2f3774d57bd9316ec856b7a81c46ba3500e2b0c36f656479bd695370d: received unexpected HTTP status: 504 Gateway Time-out`

Maybe this time.

/retest

**Pull request merged**
