### PR TITLE
OCPBUGS-36293: aws: bump capa to fix EIP leak on bootstrap when BYOIP

### PR DESCRIPTION
**Pull request by mtulio**
This change bumps CAPA to latest version (`main`/[`3f3ce56102048a3c58937c3964feb2d3da826743`][3f3ce56102048a3c58937c3964feb2d3da826743]) with fixes of EIP leak when provisioning Machine (bootstrap) with public IP using Public IPv4 pool, merged on PR https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/5039.

This is the diff commits from the version used currently on installer: https://github.com/kubernetes-sigs/cluster-api-provider-aws/compare/v2.6.1...main

https://issues.redhat.com/browse/OCPBUGS-36293

Tests: all e2e-aws* jobs running on us-east-1 should receive a lease, when there is available, to acquire an BYO IPv4 pool ID to CAPA provisioning resources consuming public IP from that pool, see the step for more information. The job `e2e-aws-ovn-public-ipv4-pool-disabled` is enforcing to not use the pool while ensuring the test without BYO IP feature.

[3f3ce56102048a3c58937c3964feb2d3da826743]: https://github.com/kubernetes-sigs/cluster-api-provider-aws/tree/3f3ce56102048a3c58937c3964feb2d3da826743

[e2e-aws-ovn-public-ipv4-pool-disabled]: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_installer/8676/pull-ci-openshift-installer-master-e2e-aws-ovn-public-ipv4-pool-disabled/1833517297344450560/artifacts/e2e-aws-ovn-public-ipv4-pool-disabled/ipi-conf-aws-byo-ipv4-pool-public/build-log.txt

### CODE REVIEW

**Comment by mtulio** [comment]
feedback addressed in upstream PR to improve the reconciliation loop by not show error messages while the instance isn't running (expected):

/test altinfra-e2e-aws-ovn-public-ipv4-pool

**Comment by mtulio** [comment]
I am seeing upstream e2e issues, ensuring downstream are ok:

/test altinfra-e2e-aws-ovn-public-ipv4-pool

/test altinfra-e2e-aws-ovn

**Comment by mtulio** [comment]
https://github.com/openshift/release/pull/56114 merged. Checking if I can run a job that the pool is disabled in CAPI:

/test e2e-aws-ovn-public-ipv4-pool-disabled

**Comment by patrickdillon** [comment]
Does this need a bump of https://github.com/openshift/installer/blob/master/data/data/cluster-api/aws-infrastructure-components.yaml?

**Comment by patrickdillon** [comment]
/approve

but lets

/hold

for the ipv4 pool test as it is non blocking. feel free to drop the hold

**Comment by mtulio** [comment]
> Does this need a bump of https://github.com/openshift/installer/blob/master/data/data/cluster-api/aws-infrastructure-components.yaml?

As chatted on Slack, probably we don't need to update it.

Looks like the updates on [aws-infrastructure-components.yaml](https://github.com/openshift/installer/blob/master/data/data/cluster-api/aws-infrastructure-components.yaml)
are mostly changes adding new capabilities like second CIDR block for IPv6 and advanced configuration for extra volumes, no removals, not impacting this change.

**Comment by mtulio** [comment]
> /approve
> 
> but lets
> 
> /hold
> 
> for the ipv4 pool test as it is non blocking. feel free to drop the hold

From the CI jobs, I can see the job forcing to skip BYO IP Pool config (default on CI) [1], and the job enforcing[2] to use the pool, ignoring the quota assignment. Both are working as expected. cc @jupierce @patrickdillon 

/hold cancel

The following tests are passing:
- 1/ [e2e-aws-ovn-public-ipv4-pool-disabled](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_installer/8676/pull-ci-openshift-installer-master-e2e-aws-ovn-public-ipv4-pool-disabled/1833517297344450560): Bootstrap got IP `\"publicIp\":\"18.188.159.227\",\...:{\"MachineName\":\"openshift-cluster-api-guests/ci-op-cfkbr9vz-4ba8c-hkwr2-bootstrap\"`
- 2/ [e2e-aws-ovn-public-ipv4-pool](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_installer/8676/pull-ci-openshift-installer-master-e2e-aws-ovn-public-ipv4-pool/1833572328479395840/artifacts/e2e-aws-ovn-public-ipv4-pool/ipi-install-install/artifacts/.openshift_install-1725997373.log)
```
356 eip.go:51] \"Machine is already associated with an Elastic IP with custom Public IPv4 pool\" 
controller=\"awsmachine\" .... controllerKind=\"AWSMachine\" ... 
machine=\"openshift-cluster-api-guests/ci-op-p7tyw9c7-0d850-dzfd9-bootstrap\" 
cluster=\"openshift-cluster-api-guests/ci-op-p7tyw9c7-0d850-dzfd9\" 
eip=\"eipalloc-026314129f08c2a06\" eip-address=\"157.254.217.103\"
```

**Pull request merged**
