### PR TITLE
[release-4.11] Bug 2101015: go getter update for terraform & terraform providers

### PR DESCRIPTION
**Pull request by jhixson74**
Backports https://github.com/openshift/installer/pull/6352

### CODE REVIEW

**Comment by patrickdillon** [comment]
/approve

To get the valid bug label you'll need to set the bz to be dependent on the 4.12 bz

**Comment by sdodson** [comment]
Adding `bugzilla/valid-bug` as this backports changes which merged into master which had no bug associated at the time. Since we can no longer create bugzillas we've created a JIRA requesting that QE test that https://issues.redhat.com/browse/OCPBUGS-2211

**Pull request merged**
