### PR TITLE
CORS-3580: Update GCP Disk Types

### PR DESCRIPTION
**Pull request by barbacbd**
** Update the version of the machine api so that the validation for the new gcp machine types are included.
** Update the enumeration for GCP disks to include hyperdisk-balanced.
** Update the allowed disk types of compute nodes for gcp. This will now include hyperdisk-balanced.

### CODE REVIEW

**Comment by barbacbd** [comment]
Note: This is only for compute nodes. The control planes can be either separate commits or another PR (if we decide to allow control plane nodes to use additional disk types).

**Comment by bfournie** [comment]
Wonder if need a change here?https://github.com/openshift/installer/blob/master/pkg/destroy/gcp/gcp.go#L242-L251

**Pull request merged**
