### PR TITLE
SPLAT-1460: Make vSphere default ResourcePool formatting not contain double slash.

### PR DESCRIPTION
**Pull request by vr4manta**
[SPLAT-1460](https://issues.redhat.com/browse/SPLAT-1460)

## Changes
- Modified default ResourcePool definition to prevent double "/" in path

### CODE REVIEW

**Comment by jcpowermac** [comment]
/approve
/hold

@vr4manta remove the hold whenever you feel like this is ready

**Comment by vr4manta** [comment]
/assign @rwsu
Ready for review. Thanks!

**Comment by patrickdillon** [comment]
looks like agent compact is failing due to https://github.com/ovn-org/ovn-kubernetes/pull/4168

**Comment by vr4manta** [comment]
true	/test e2e-vsphere-ovn

**Pull request merged**
