### PR TITLE
[release-4.4] Bug 1806576: bump rhcos for crio fix

### PR DESCRIPTION
**Pull request by rphillips**
backport https://github.com/openshift/installer/pull/3173 to 4.4

### CODE REVIEW

**Comment by rphillips** [comment]
aws throttle, we may want to pause for a little bit

**Comment by rphillips** [comment]
Sorry all, new branches were cut in the middle of this pr chain... I need to backport the original patch into 4.4. My bad.

**Comment by rphillips** [comment]
https://github.com/openshift/origin/pull/24596

**Comment by rphillips** [comment]
QE is going to take another day to test the Kubelet fix... We need to get this into 4.4 for the crio fix.

**Comment by sdodson** [comment]
Nevermind, openstack looks good.
vsphere looks dire but that doesn't appear to be a regression as everything vsphere 4.4 is red https://prow.svc.ci.openshift.org/?job=*vsphere*4.4
I'd like to see another e2e-metal run before we push this through, not sure why the bot is being unresponsive.

**Comment by sdodson** [comment]
/override ci/prow/e2e-gcp-upi
normal e2e-gcp has passed

**Comment by sdodson** [comment]
vsphere failed on e2e tests, which shouldn't be a direct result of this change

**Pull request merged**
