### PR TITLE
OCPBUGS-43674: ABI cluster installation fails for external OCI platform

### PR DESCRIPTION
**Pull request by pawanpinjarkar**
- Correctly maps agentClusterInstall with cloudControllerManager value 
- Updated integrations tests

### CODE REVIEW

**Comment by mhanss** [comment]
The bug has been pre-merge tested, and it’s working fine.
/label qe-approved

**Review by rwsu — COMMENTED** [review]
/lgtm

**Comment by pawanpinjarkar** [comment]
> @pawanpinjarkar: #9141 failed to apply on top of branch "release-4.17":
> 
> ```
> Applying: OCPBUGS-43674: ABI cluster installation fails for external OCI platform Correctly maps agentClusterInstall with cloudControllerManager value Updated integrations tests
> Using index info to reconstruct a base tree...
> M	pkg/asset/agent/manifests/agentclusterinstall.go
> M	pkg/asset/agent/manifests/agentclusterinstall_test.go
> Falling back to patching base and 3-way merge...
> Auto-merging pkg/asset/agent/manifests/agentclusterinstall_test.go
> CONFLICT (content): Merge conflict in pkg/asset/agent/manifests/agentclusterinstall_test.go
> Auto-merging pkg/asset/agent/manifests/agentclusterinstall.go
> error: Failed to merge in the changes.
> hint: Use 'git am --show-current-patch=diff' to see the failed patch
> hint: When you have resolved this problem, run "git am --continue".
> hint: If you prefer to skip this patch, run "git am --skip" instead.
> hint: To restore the original branch and stop patching, run "git am --abort".
> hint: Disable this message with "git config advice.mergeConflict false"
> Patch failed at 0001 OCPBUGS-43674: ABI cluster installation fails for external OCI platform Correctly maps agentClusterInstall with cloudControllerManager value Updated integrations tests
> ```

Manually cherrypicked via https://github.com/openshift/installer/pull/9152

**Pull request merged**
