### PR TITLE
Remove cluster-api cluster object dependency

### PR DESCRIPTION
**Pull request by enxebre**
Fix https://jira.coreos.com/browse/CLOUD-357
The cluster object was necessary for the machine controllers to function. This dep is being removed and there's no reason for this object to exist at the moment
Needs: 
https://github.com/openshift/cluster-kube-apiserver-operator/pull/351
https://github.com/openshift/cluster-kube-controller-manager-operator/pull/196
This won't go green until the changes in these two PRs make it to the payload

### CODE REVIEW

**Comment by enxebre** [comment]
second PR went through here https://origin-release.svc.ci.openshift.org/releasestream/4.0.0-0.alpha/release/4.0.0-0.alpha-2019-03-22-231511
/retest

**Comment by enxebre** [comment]
ping @abhinavdahiya @wking

**Comment by abhinavdahiya** [comment]
it looks like you might have to re-roll https://github.com/openshift/installer/blob/88901fa7fbeec8e42a918cc69d989af0b52f7c64/pkg/asset/manifests/network.go#L128 to remove dep on `cluster1a1`

**Comment by abhinavdahiya** [comment]
> /lgtm

> it looks like you might have to re-roll
> 
> [installer/pkg/asset/manifests/network.go](https://github.com/openshift/installer/blob/88901fa7fbeec8e42a918cc69d989af0b52f7c64/pkg/asset/manifests/network.go#L128)
> 
> Line 128 in [88901fa](/openshift/installer/commit/88901fa7fbeec8e42a918cc69d989af0b52f7c64)
>  func (no *Networking) ClusterNetwork() (*clusterv1a1.ClusterNetworkingConfig, error) { 
> to remove dep on `cluster1a1`

^^ this function seems to be not used at all. maybe just drop this. it was being consumed https://github.com/openshift/installer/pull/1449/commits/88901fa7fbeec8e42a918cc69d989af0b52f7c64#diff-a25ec653fe393c89c4ccac5a1edfe38fL42

/lgtm cancel

**Comment by enxebre** [comment]
back to green @abhinavdahiya

**Pull request merged**
