### PR TITLE
SPLAT-1345: Remove alibaba

### PR DESCRIPTION
**Pull request by jcpowermac**

### CODE REVIEW

**Comment by jcpowermac** [comment]
will add back reviewers/approvers after all tests pass

/uncc @patrickdillon @bfournie

**Comment by jcpowermac** [comment]
removed `e2e-alibaba`
https://github.com/openshift/release/pull/46730

**Comment by jcpowermac** [comment]
/hold

This is step number two. Once we are ready I will release the hold

**Comment by jsafrane** [comment]
lgtm from storage side

**Pull request merged**
