### PR TITLE
update registry.ci.openshift.org/ocp and origin images to 4.10

### PR DESCRIPTION
**Pull request by jstuever**
Update the default release payload to 4.10

### CODE REVIEW

**Comment by jstuever** [comment]
This may clash with https://github.com/openshift/installer/pull/5237

**Comment by yselkowitz** [comment]
This will also clash with PRs to bump golang to 1.17.

**Comment by staebler** [comment]
> This will also clash with PRs to bump golang to 1.17.

@jstuever Do you want to wait for the 1.17 bump? Or do you want to merge this now and bump to 1.17 later?

**Comment by jstuever** [comment]
> @jstuever Do you want to wait for the 1.17 bump? Or do you want to merge this now and bump to 1.17 later?

Considering the 1.17 is stalled, I recommend we run this one through first.

**Review by staebler — APPROVED** [review]
/lgtm

**Pull request merged**
