### PR TITLE
Install cgroups config for bootstrap

### PR DESCRIPTION
**Pull request by LorbusChris**
Equivalent to https://github.com/openshift/machine-config-operator/pull/581,
cherry-picked from fcos branch

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
How if this useful on bootstrap host?

**Comment by LorbusChris** [comment]
I guess this may have been a precaution.
I'd be happy to drop this from `fcos` as well.
/cc @vrutkovs

**Comment by vrutkovs** [comment]
AFAIK this file is present in RHCOS from the start, so it doesn't need to be re-created

**Comment by LorbusChris** [comment]
Are you sure? Then MCO wouldn't have to add it either...
What is the benefit of this on bootstrap hosts?
Could we drop this from `fcos`?

**Comment by LorbusChris** [comment]
@vrutkovs closing. Feel free to reopen.

**Pull request closed without merging**
