### PR TITLE
OCPBUGS-24521: set vmType in azure cloud config [release-4.14]

### PR DESCRIPTION
**Pull request by patrickdillon**
Manual cherry-pick of #7793

### CODE REVIEW

**Review by damdo — COMMENTED** [review]
Awesome thanks!
/lgtm

**Comment by patrickdillon** [comment]
/hold
This needs ratelimitconfig: https://issues.redhat.com/browse/OCPBUGS-25024

**Comment by tiguelu** [comment]
> /hold This needs ratelimitconfig: https://issues.redhat.com/browse/OCPBUGS-25024

OCPBUGS-25024 is now closed. Is the `hold` ok to be lifted?

**Comment by patrickdillon** [comment]
> > /hold This needs ratelimitconfig: https://issues.redhat.com/browse/OCPBUGS-25024
> 
> OCPBUGS-25024 is now closed. Is the `hold` ok to be lifted?

Yes, but the dependent bug has not been verified by QE: https://issues.redhat.com//browse/OCPBUGS-24191 Would you be able to work with them to verify the bug or resolve the issue? 

/approve

**Comment by tiguelu** [comment]
> > > /hold This needs ratelimitconfig: https://issues.redhat.com/browse/OCPBUGS-25024
> > 
> > 
> > OCPBUGS-25024 is now closed. Is the `hold` ok to be lifted?
> 
> Yes, but the dependent bug has not been verified by QE: https://issues.redhat.com//browse/OCPBUGS-24191 Would you be able to work with them to verify the bug or resolve the issue?

Thank you Patrick. The dependent bug has been now marked as verified by QE:
 https://issues.redhat.com//browse/OCPBUGS-24191

**Pull request merged**
