### PR TITLE
Bug 1965468: Revert "Bug 1909136: OpenStack: delete volume snapshots"

### PR DESCRIPTION
**Pull request by stephenfin**
This reverts commit a272e59b99f8549a0ad4371151222c0f309b759b. As noted in the corresponding bug [1], the expectation was always to revert this once cloud-provided-openstack started providing cluster ID information in snapshot metadata, which has been the case for some time now [2].

[1] https://bugzilla.redhat.com/show_bug.cgi?id=1965468
[2] https://github.com/kubernetes/cloud-provider-openstack/pull/1544

### CODE REVIEW

**Comment by pierreprinetti** [comment]
errored machines in the CI.
/retest

**Comment by mandre** [comment]
I believe the openstack job failed because the boskos quota lease is not really representative of the underlying infra. One more try before we reduce the number of boskos leases.
/test e2e-openstack

**Review by mandre — COMMENTED** [review]
The e2e-openstack job failed because of infra slowness, nothing related to this patch. All we cared about was the cluster deprovisioning and it was successful:

https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_installer/5923/pull-ci-openshift-installer-master-e2e-openstack/1528746575952613376/artifacts/e2e-openstack/ipi-deprovision-deprovision/

/lgtm
/approve

**Pull request merged**
