### PR TITLE
pkg/asset/machines: avoid generating duplicate MC with ssh keys

### PR DESCRIPTION
**Pull request by LorbusChris**
Cherry-pick of https://github.com/openshift/installer/pull/3061

`pkg/asset/installconfig/ssh.go` already generates MC with ssh keys.
Ignition v2 skips duplicate files, but Ignition v3 throws an error during
boot.

Duplicate ssh keys are injected in bootstrap node during `create manifests && create cluster` commands

### CODE REVIEW

**Comment by vrutkovs** [comment]
/hold

I've realised this makes bootstrap unable to ssh onto masters

**Comment by LorbusChris** [comment]
/close
so we need to revert #3061?

**Comment by vrutkovs** [comment]
>so we need to revert #3061?

most likely, yeah :/ I'll come up with a proper fix

**Comment by LorbusChris** [comment]
Follow up in https://github.com/openshift/installer/pull/3078

**Pull request closed without merging**
