### PR TITLE
OCPBUGS-36904: aws: bump CAPA for subnet tagging fix

### PR DESCRIPTION
**Pull request by r4f4**
This bump includes the following fix:

* https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/5051

### CODE REVIEW

**Comment by r4f4** [comment]
Marking as WIP until the upstream PR is accepted.

**Comment by r4f4** [comment]
/uncc @patrickdillon @sadasu 
Will cc back in when it's ready for review.

**Comment by r4f4** [comment]
/retitle OCPBUGS-36904: aws: bump CAPA for subnet tagging fix

Upstream PR has merged, removing WIP.

**Comment by r4f4** [comment]
/cc @patrickdillon @sadasu 
This is ready for review now.

**Review by barbacbd — COMMENTED** [review]
/lgtm

**Pull request merged**
