### PR TITLE
Kubelet bootstrap signer

### PR DESCRIPTION
**Pull request by deads2k**
The MCO appears to never rotate the credentials used to request CSRs for kubelets. This gives them a long lived certificate with a separate chain of trust they could later choose to rotate.

@sjenning @openshift/sig-pod 
/assign @abhinavdahiya

### CODE REVIEW

**Comment by deads2k** [comment]
rebased and updated https://docs.google.com/document/d/1ZrriFDniXPnDLwogusJD7tVsX6nXTW5jlvkJSHh50Uk/edit

**Comment by cgwalters** [comment]
Hmm.  There's a conceptual issue here of whether the MCO data should be a "bootstrap" to cluster-controlled state, or whether just because it happens to write a file, it should own the code to update it afterwards.

In this case I'd kind of expect that there'd be e.g. a static pod that could come from anywhere that owned rotating the certs for the kubelet or so?

**Pull request merged**
