### PR TITLE
[release-4.15]: OCPBUGS-36400: PowerVS: add ibmcloud plugins

### PR DESCRIPTION
**Pull request by hamzy**
Add ibmcloud plugins used by the PowerVS CI.

### CODE REVIEW

**Review by r4f4 — COMMENTED** [review]
/approve

**Comment by hamzy** [comment]
@sadasu Could you please /label backport-risk-assessed

**Comment by hamzy** [comment]
@gpei Could you please/label cherry-pick-approved

**Comment by hamzy** [comment]
@r4f4 Could you please override ci/prow/altinfra-e2e-aws-ovn-upi?

**Comment by r4f4** [comment]
/override ci/prow/altinfra-e2e-aws-ovn-upi
e2e test failures not related to PR changes.

**Comment by hamzy** [comment]
e2e-gcp-ovn-upi, e2e-azure-ovn-upi, and e2e-aws-ovn-upi are still failing

**Comment by r4f4** [comment]
/override ci/prow/e2e-gcp-ovn-upi ci/prow/e2e-aws-ovn-upi
e2e test failures not related to PR changes.

**Comment by r4f4** [comment]
/override ci/prow/e2e-azure-ovn-upi
e2e failures not related to PR changes.

**Pull request merged**
