### PR TITLE
Bug 1843587: baremetal: verify that provisioning IP's are not in DHCP range

### PR DESCRIPTION
**Pull request by stbenjam**
Currently there's no verification that user-supplied bootstrap or
cluster provisionig IP's don't overlap with the DHCP range. This would
allow a user to incorrectly consume the entire subnet for DHCP leases,
and cause a conflict between the IP's used for provisioning services.

### CODE REVIEW

**Comment by kirankt** [comment]
gofmt is failing on plaform.go. Other than that, works great in my local test.
/approve

**Comment by stbenjam** [comment]
/assign @hardys 

Could you take a look? Thanks!

**Pull request merged**
