### PR TITLE
Added memory/cpu variables for libvirt

### PR DESCRIPTION
**Pull request by e-minguez**

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
@e-minguez any reason why the defaults are not enough? OR why you would want to change these values?

**Comment by eparis** [comment]
we actually ripped these out a while ago...

**Comment by wking** [comment]
Cross linking #163, where we switched to the current hardcoded approach.

**Comment by crawford** [comment]
We can re-open this if there is a good justification.

/close

**Pull request closed without merging**
