### PR TITLE
OCPBUGS-34220: [release-4.16] Reintroduce CAPI-installer

### PR DESCRIPTION
**Pull request by patrickdillon**
4.16 version of #8427 

- bumps AWS timeout due to [OCPBUGS-33874](https://issues.redhat.com//browse/OCPBUGS-33874)
- reverts #8434

### CODE REVIEW

**Comment by patrickdillon** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.17-e2e-aws-ovn-upgrade 10

**Comment by neisw** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.16-e2e-aws-ovn 10

**Comment by patrickdillon** [comment]
> /payload-aggregate periodic-ci-openshift-release-master-ci-4.16-e2e-aws-ovn 10

doh! I triggered 4.17. Thanks.

**Pull request closed without merging**
