### PR TITLE
WIP: Install OpenShift with Cluster API (AWS only)

### PR DESCRIPTION
**Pull request by vincepri**

### CODE REVIEW

**Comment by vincepri** [comment]
`openshift-install create capi-cluster`

**Comment by patrickdillon** [comment]
Latest run (which landed in us-west-1 which only has two azs) failed because we couldn't get workers:
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_installer/7579/pull-ci-openshift-installer-master-e2e-aws-ovn/1712323903122051072/artifacts/e2e-aws-ovn/gather-extra/artifacts/machines.json

They couldn't find subnets, perhaps the filter in the machine/machineset manifests is wrong

**Pull request closed without merging**
