### PR TITLE
Bug 1867165: baremetal: allow configuring bootstrap mac addresses

### PR DESCRIPTION
**Pull request by stbenjam**
If users are unable to define the mac addresses for the bootstrap host,
they won't be able to set static DHCP reservations for the host. Many
corporate environments do not allow unrestricted DHCP.

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
Also IMO this is not a change that we should be doing in code freeze-reduce bugs cycle. The attached bug is not a bug rather a feature request and should probably be prioritized through our JIRA processes.

**Comment by stbenjam** [comment]
> Also IMO this is not a change that we should be doing in code freeze-reduce bugs cycle. The attached bug is not a bug rather a feature request and should probably be prioritized through our JIRA processes.

The platform is unusable in some environments without this which IMHO makes it a bug -- accessing hardware BMC's (baseboard management controllers) is something you want to restrict and you can't without being able to assign a specific IP to the bootstrap.

This is even more important in light of https://github.com/openshift/installer/pull/3929, as a user installing without a provisioning network no longer has a dedicated, private provisioning network.

/cc @celebdor

**Comment by stbenjam** [comment]
This needs an installer team member to approve, as we're touching a few files outside our directories (e.g., data/data/install.openshift.io_installconfigs.yaml)

/assign @abhinavdahiya @staebler

**Review by staebler — COMMENTED** [review]
Looks fine to me. I just have a couple nits.

**Review by staebler — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
