### PR TITLE
DNM: OCPBUGS-30860: test RHCOS 416.94.202405091525-0

### PR DESCRIPTION
**Pull request by jlebon**
This is purely for running Azure tests in CI in the context of OCPBUGS-30860. This build hasn't gone through the process to be a bootimage update.

### CODE REVIEW

**Comment by rphillips** [comment]
/payload periodic-ci-openshift-release-master-ci-4.17-e2e-azure-ovn-upgrade

**Comment by rphillips** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.17-e2e-azure-ovn-upgrade 5

**Comment by jlebon** [comment]
Closing. Tests were successful. See https://github.com/openshift/installer/pull/8409 for an official bootimage bump containing this fix.

**Pull request closed without merging**
