### PR TITLE
rhcos: Bump to 420.8.20190624.0

### PR DESCRIPTION
**Pull request by ashcrow**
This moves `master` off of `410` builds as a base and on to `420` builds.

/cc @cgwalters @runcom @miabbott @darkmuggle @abhinavdahiya @imcleod

### CODE REVIEW

**Comment by ashcrow** [comment]
Bootstrap timed out on openstack:
```
 level=fatal msg="failed to wait for bootstrapping to complete: timed out waiting for the condition" 
```

**Comment by cgwalters** [comment]
/approve

One thing to note is this version of RHCOS drops `/usr/bin/pivot` which is part of https://github.com/openshift/machine-config-operator/issues/798

Everything *should* work but the interaction between that and the MCO is tricky.

**Comment by cgwalters** [comment]
So as a general procedural note...do RHCOS version bumps wait for an installer team `lgtm` or do you mind if e.g. RHCOS/MCO team does it too?

**Comment by ashcrow** [comment]
> So as a general procedural note...do RHCOS version bumps wait for an installer team `lgtm` or do you mind if e.g. RHCOS/MCO team does it too?

I don't think we formalized it, but I've personally awaited a `lgtm` from an installer member. I'm OK with either waiting or allowing RHCOS members to `lgtm` depending on @abhinavdahiya's / @crawford's thoughts.

**Pull request merged**
