### PR TITLE
[wip] Ibmcloud build troubleshoot

### PR DESCRIPTION
**Pull request by rvanderp3**
Troubleshooting build issue and need access to build pod launched in CI.  This PR will be closed when done.

### CODE REVIEW

**Comment by patrickdillon** [comment]
This one is a head scratcher.

**Comment by rvanderp3** [comment]
> This build failure is a head scratcher.

Yeah, it is.  @jcpowermac and I have been looking at this one.

**Comment by rvanderp3** [comment]
opened PR https://github.com/IBM/ibm-hpcs-tke-sdk/pull/7 to address the issue which resulted in this PR being opened for investigation.  Closing this PR.

**Pull request closed without merging**
