### PR TITLE
pkg/types/config: Prefix "pull secret" in validatePullSecret

### PR DESCRIPTION
**Pull request by wking**
To match a lot of other error handling in this package and give more useful error messages (if we somehow get past the input validation in `pkg/asset/installconfig`).

/assign @crawford

Dunno if you're tearing this out with your overhaul, but here it is in case it doesn't collide ;).

### CODE REVIEW

**Comment by wking** [comment]
Rebased around 496c5ab (#342) with 28ec9f7 -> 5f0e2a4.

**Comment by crawford** [comment]
CI is failing with:

```
pkg/types/config/validate.go:255:23: undefined: PrefixError
```

**Comment by wking** [comment]
Green now ;)

**Pull request merged**
