### PR TITLE
OCPBUGS-2738: Uplift terraform-provider-ironic to 0.3.0

### PR DESCRIPTION
**Pull request by elfosardo**
Use GO 1.18
Update to terraform SDK to 2.0
Remove go-getter dependency

### CODE REVIEW

**Comment by elfosardo** [comment]
this has passed on bare metal platforms so it should be good to go

**Review by r4f4 — APPROVED** [review]

**Comment by r4f4** [comment]
/override e2e-azure-ovn
A few e2e failures. Whole job unrelated to the PR changes.

**Comment by r4f4** [comment]
/override ci/prow/e2e-vsphere-ovn ci/prow/e2e-azure-ovn
Few e2e failures. Whole job unrelated to the PR.

**Comment by elfosardo** [comment]
@sadasu @patrickdillon when you have a moment can you please check this and give an LGTM if appropriates? thanks!

**Comment by elfosardo** [comment]
the e2e-vsphere-ovn test is failing for reasons not related to this change, if it fails again I suggest to skip it and merge the PR, this is long due

**Comment by r4f4** [comment]
@elfosardo which jobs are expected to pass? I can start overriding jobs that are not related but I want to make sure I don't end up overriding important ones.

**Comment by r4f4** [comment]
/override ci/prow/e2e-vsphere-ovn
Just a few e2e failures and job is unrelated to PR.

**Pull request merged**
