### PR TITLE
Bug 2038166: openstack: Fix invalid-https-certificate detection

### PR DESCRIPTION
**Pull request by pierreprinetti**
Fix the reference to an unbound variable; avoid incrementing the invalid
certificate counter in a subshell.

/cc mandre

### CODE REVIEW

**Comment by pierreprinetti** [comment]
/skip
docs PR

**Review by mandre — COMMENTED** [review]
/lgtm
/approve

**Comment by maxwelldb** [comment]
@pierreprinetti Noted. Incorporating into https://github.com/openshift/openshift-docs/pull/40785.

**Pull request merged**
