### PR TITLE
data/data/coreos: bump FCOS to F38 stable

### PR DESCRIPTION
**Pull request by vrutkovs**
Use latest stable FCOS for OKD builds

### CODE REVIEW

**Review by dustymabe — APPROVED** [review]
LGTM

**Comment by vrutkovs** [comment]
/cc @travier 

Seems another LGTM is required

**Comment by patrickdillon** [comment]
/lgtm 
based on dusty's, which the bot so rudely ignored!

**Comment by travier** [comment]
I don't know why Dusty's LGTM was ignored by the bot as he is in https://github.com/openshift/installer/blob/master/OWNERS_ALIASES#L111

**Pull request merged**
