### PR TITLE
move waitFor* logic into pkg

### PR DESCRIPTION
**Pull request by mjudeikis**
Moves reusable waitFor*  code blocks into `pkg` 

This enables re-use "waitFor" logic into the package for re-usability

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
Please use https://github.com/openshift/installer/blob/master/CONTRIBUTING.md#commit-message-format for commit messages.

I don't think `pkg/health` is appropriate for the functions. Maybe `pkg/wait` ? Also since this PR is making the functions **public** i would like to use this opportunity to ask for more testing, and better design like using interfaces? maybe each waitfor as chainable? each waitfor allows some troubleshooting actions on failures?

**Comment by mjudeikis** [comment]
@abhinavdahiya I agree with name. Testing would require either mocked api or running cluster for it. Do we have something like this available in the current code base?

**Comment by abhinavdahiya** [comment]
The code move all `waitFor*` package but the commit message and PR title do not make sense or align with the changes.

**Comment by mjudeikis** [comment]
moved/renamed

**Comment by mjudeikis** [comment]
Anything missing from this?

**Pull request closed without merging**
