### PR TITLE
[fcos] pkg/asset/releaseimage/default: set default release image to 4.4

### PR DESCRIPTION
**Pull request by vrutkovs**
This would be helpful for those who have to rebuild the installer from source

### CODE REVIEW

**Comment by sgreene570** [comment]
Nice catch !

**Comment by vrutkovs** [comment]
/override ci/prow/e2e-vsphere

Known bootstrap issue on vsphere

**Comment by LorbusChris** [comment]
included in https://github.com/openshift/installer/pull/3013

/close

**Pull request closed without merging**
