### PR TITLE
Bug 1835795: downport disk extension support for masters/workers 

### PR DESCRIPTION
**Pull request by rgolangh**
Depends-on: https://github.com/openshift/cluster-api-provider-ovirt/pull/48

### CODE REVIEW

**Comment by michalskrivanek** [comment]
this is tracked in https://bugzilla.redhat.com/show_bug.cgi?id=1835795, correct? if so please add the bug #

**Comment by rgolangh** [comment]
@patrickdillon PTAL

**Comment by sdodson** [comment]
/override ci/prow/e2e-aws-upgrade
All changes localized to ovirt

**Pull request merged**
