### PR TITLE
update the vm types OCPQE-8674

### PR DESCRIPTION
**Pull request by MayXuQQ**
tested vm @yunjiang29

### CODE REVIEW

**Comment by yunjiang29** [comment]
@staebler @patrickdillon can you help review this PR? these instances types will be auto-included in the document by https://github.com/openshift/openshift-docs/pull/41796, thanks.

**Comment by patrickdillon** [comment]
/approve

@MayXuQQ Can you: 
1. Squash the commits
2. Add a little more description to the commit message: I would suggest:

```
Docs: update list of supported Azure instance types

Updated list and switched list to use instance-type families.
```

**Comment by MayXuQQ** [comment]
> 
https://deploy-preview-41796--osdocs.netlify.app/openshift-enterprise/latest/installing/installing_azure/installing-azure-customizations.html#installation-azure-tested-machine-types_installing-azure-customizations

ref https://github.com/openshift/openshift-docs/pull/41796

**Pull request merged**
