### PR TITLE
OCPBUGS-35818: baremetal: bootstrap: bind icc to localhost

### PR DESCRIPTION
**Pull request by dtantsur**
This fixes deployments with proxy enabled.

(cherry picked from commit fa42f0535f550c6f9319ddbcd3fa37ec4f4b39d1)

### CODE REVIEW

**Comment by zaneb** [comment]
/approve
/label backport-risk-assessed

Not adding staff-eng-approved for now, as there may be a workaround (which would mean this is not a release blocker).

**Comment by dtantsur** [comment]
/test e2e-metal-ipi-ovn-ipv6

Known issue with image building

**Pull request merged**
