### PR TITLE
docs: Note how to auth kubectl on the master

### PR DESCRIPTION
**Pull request by cgwalters**
I didn't set up DNS (I tried once, it broke my "pet container" with
podman), complex story.

Documenting how to do this from the master is useful for other reasons.

### CODE REVIEW

**Comment by crawford** [comment]
Note that this will only work on RHCOS. This won't be a big deal once we remove Container Linux.

**Comment by wking** [comment]
[The e2e-aws job][1] timed out:

```
Waiting for API at https://ci-op-ittk6wnq-68485-api.origin-ci-int-aws.dev.rhcloud.com:6443 to respond ...
Waiting for API at https://ci-op-ittk6wnq-68485-api.origin-ci-int-aws.dev.rhcloud.com:6443 to respond ...
Interrupted
2018/08/02 01:44:48 Container setup in pod e2e-aws failed, exit code 1, reason Error
Another process exited
```

/retest

[1]: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_installer/93/pull-ci-origin-installer-e2e-aws/348/build-log.txt

**Pull request merged**
