### PR TITLE
Bug 1861917: Add cpc config to bootstrap

### PR DESCRIPTION
**Pull request by tnozicka**
Follow up to https://github.com/openshift/installer/pull/4131

Requires:
 - [ ] https://github.com/openshift/cluster-kube-controller-manager-operator/pull/449

/hold

### CODE REVIEW

**Comment by tnozicka** [comment]
https://github.com/openshift/cluster-kube-controller-manager-operator/pull/449 merged
/retest

**Comment by abhinavdahiya** [comment]
/override ci/prow/e2e-aws-upgrade

Upgrade job doesn't test installer changes.

**Pull request merged**
