### PR TITLE
bootkube: remove duplicate CRD manifests

### PR DESCRIPTION
**Pull request by deads2k**
cluster-config-operator is rendered and it produces CRD manifests, the ones
in the installer are duplicates.  This eliminates the cruft.

/assign @wking @abhinavdahiya

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
:yay: /approve

If the CI goes green i'll `lgtm`

**Comment by deads2k** [comment]
Known flake failures, well past bootstrapping.  This completes work to clean up our CRD manifest story.  Merging.

**Comment by abhinavdahiya** [comment]
Talking to @ironcladlou the previous failure 
from [e2e-aws](https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_installer/1254/pull-ci-openshift-installer-master-e2e-aws/3708)

was known flake, so should be safe to override for you @deads2k

**Pull request merged**
