### PR TITLE
[release-4.12] OCPBUGS-4542: Azure: use azidentity with an adapter

### PR DESCRIPTION
**Pull request by r4f4**
This is a manual cherry-pick of https://github.com/openshift/installer/pull/6003

### CODE REVIEW

**Review by barbacbd — COMMENTED** [review]
This looks good, but I thought we try to not go through with major version updates

```
github.com/Azure/azure-sdk-for-go/sdk/internal v1.0.1
```

**Comment by r4f4** [comment]
> This looks good, but I thought we try to not go through with major version updates
> 
> ```
> github.com/Azure/azure-sdk-for-go/sdk/internal v1.0.1
> ```

In this case we have to since Stack and GovCloud support are present in the official release (v1.0). `azure-sdk-for-go/sdk` is where the new SDK V2 clients live and we're not yet using any of them. However that's about to change when we backport https://github.com/openshift/installer/pull/6614 to replace `graphrbac`  (also being deprecated) with the new `msgraphsdk` API.

**Comment by r4f4** [comment]
/hold
Not sure yet if we want this sooner or later

**Comment by patrickdillon** [comment]
Given that usptream kubernetes still depends on ADAL in 4.12, I don't think we should backport this. Contrary to the messaging regarding ADAL EOL at the end of this month, it seems like we should begin to think about this as future proofing instead.

**Pull request closed without merging**
