### PR TITLE
maintenance: update openshift/api

### PR DESCRIPTION
**Pull request by EmilienM**
- vendoring: update openshift/api to latest
- `go generate ./pkg/types/installconfig.go`

### CODE REVIEW

**Comment by patrickdillon** [comment]
`e2e-openstack-ovn` is failing with:

>  level=info msg=Obtaining RHCOS image file from 'https://rhcos.mirror.openshift.com/art/storage/prod/streams/4.14-9.2/builds/414.92.202307070025-0/x86_64/rhcos-414.92.202307070025-0-openstack.x86_64.qcow2.gz?sha256=1a466c8c1134da8a20c1fa3a19f4180bbf6f2e7373c471f04cd522f4a20b5e57'
level=fatal msg=failed to fetch Terraform Variables: failed to generate asset "Terraform Variables": failed to get openstack Terraform variables: gzip: invalid checksum
Installer exit with code 1

Does not look related to these changes...

**Comment by EmilienM** [comment]
> `e2e-openstack-ovn` is failing with:
> 
> > level=info msg=Obtaining RHCOS image file from 'https://rhcos.mirror.openshift.com/art/storage/prod/streams/4.14-9.2/builds/414.92.202307070025-0/x86_64/rhcos-414.92.202307070025-0-openstack.x86_64.qcow2.gz?sha256=1a466c8c1134da8a20c1fa3a19f4180bbf6f2e7373c471f04cd522f4a20b5e57'
> > level=fatal msg=failed to fetch Terraform Variables: failed to generate asset "Terraform Variables": failed to get openstack Terraform variables: gzip: invalid checksum
> > Installer exit with code 1
> 
> Does not look related to these changes... is this a known issue?

Not related to that PR, and we are aware of this random error. We actually saw it on the libvirt platform too for instance.

I looked in Jira and we don't have a bug report for this one so I went ahead and created one, we'll look at it at some point: https://issues.redhat.com/browse/OCPBUGS-17434

**Comment by mandre** [comment]
> I looked in Jira and we don't have a bug report for this one so I went ahead and created one, we'll look at it at some point: https://issues.redhat.com/browse/OCPBUGS-17434

Actually we already had https://issues.redhat.com/browse/OCPBUGS-9066 for it, with an open patch at https://github.com/openshift/installer/pull/7106.

**Comment by mandre** [comment]
Infra issue when pushing container image
/retest-required

**Comment by patrickdillon** [comment]
/override ci/prow/okd-scos-images

Failing due to infra issues. Confident this PR is not breaking okd builds.

**Pull request merged**
