### PR TITLE
Renamed OptionalInstallConfig and removed Supplied field

### PR DESCRIPTION
**Pull request by pawanpinjarkar**
Signed-off-by: Pawan Pinjarkar <ppinjark@redhat.com>

### CODE REVIEW

**Comment by celebdor** [comment]
/hold

Let's keep it for after the freeze. Otherwise it might get in before other PRs and force lots of rebasing.

**Comment by pawanpinjarkar** [comment]
@zaneb Are we still interested in this change?

**Comment by zaneb** [comment]
It's probably not a high priority.

**Pull request closed without merging**
