### PR TITLE
Bug 2023839: data/data/coreos/fcos.json: update initial FCOS to 34.20211031.3.0

### PR DESCRIPTION
**Pull request by vrutkovs**
This should resolve https://github.com/openshift/okd/issues/783

### CODE REVIEW

**Review by bgilbert — APPROVED** [review]
LGTM

**Comment by vrutkovs** [comment]
/hold
Blocked by https://github.com/coreos/fedora-coreos-tracker/issues/1004

**Comment by vrutkovs** [comment]
Superseded by #5567

**Pull request closed without merging**
