### PR TITLE
isolate terraform

### PR DESCRIPTION
**Pull request by staebler**
More progress on #5481 for removing terraform and terraform providers from the installer's module dependencies.

- [x] Terraform and all providers removed from go.mod.
- [x] All providers that are published in a public registry are downloaded from that registry rather than built locally. The exceptions are azurestack and vsphere for which we are carrying patches. All of the downloaded providers have been updated to the most recent version available.
- [x] Support for other architectures and OSes.

Follow-up work:
- [x] Add verification scripts for downloaded and vendored providers.
- [x] Add developer documentation for adding, updating, and maintaining providers.

### CODE REVIEW

**Comment by staebler** [comment]
Platforms with successful terraform creation in CI:

- [ ] alibabacloud
- [ ] aws
- [ ] azure
- [ ] azurestack
- [ ] baremetal
- [ ] gcp
- [ ] ibmcloud
- [ ] libvirt
- [ ] openstack
- [ ] ovirt
- [ ] vsphere

**Comment by staebler** [comment]
All platforms have had successful installs save for alibabacloud and azurestack, both of which are broken in CI. I will run manual installs on those 2 platforms to verify them.

**Comment by staebler** [comment]
Install on alibaba cloud made it past terraform.
```
INFO Consuming Install Config from target directory 
INFO Creating infrastructure resources...         
creating /tmp/openshift-install-cluster-789536500/plugins/registry.terraform.io/hashicorp/alicloud directory
creating /tmp/openshift-install-bootstrap-480445665/plugins/registry.terraform.io/hashicorp/alicloud directory
INFO Waiting up to 20m0s (until 4:39PM) for the Kubernetes API at https://api.mstaeble.alicloud-dev.devcluster.openshift.com:6443... 
```

**Comment by staebler** [comment]
Local install on azure stack made it past terraform, too.
```
INFO Creating infrastructure resources...         
creating /tmp/openshift-install-vnet-1044433546/plugins/openshift/local/azurestack directory
creating /tmp/openshift-install-vnet-1044433546/plugins/registry.terraform.io/hashicorp/random directory
creating /tmp/openshift-install-bootstrap-3700783851/plugins/openshift/local/azurestack directory
creating /tmp/openshift-install-bootstrap-3700783851/plugins/openshift/local/ignition directory
creating /tmp/openshift-install-bootstrap-3700783851/plugins/registry.terraform.io/hashicorp/local directory
creating /tmp/openshift-install-cluster-1335738773/plugins/openshift/local/azurestack directory
INFO Waiting up to 20m0s (until 5:49PM) for the Kubernetes API at https://api.mstaeble-2.ppe.azurestack.devcluster.openshift.com:6443... 
```

**Review by jhixson74 — CHANGES_REQUESTED** [review]
Can you add FreeBSD hashes here? The installer can be built on FreeBSD. I know because I maintain the port ;-) Though it's few, there are users.

**Review by jhixson74 — APPROVED** [review]

**Comment by staebler** [comment]
> Can you add FreeBSD hashes here? The installer can be built on FreeBSD. I know because I maintain the port ;-) Though it's few, there are users.

9ca9c4331..2164afd71
* Added support for installing on FreeBSD.

**Comment by staebler** [comment]
/assign @patrickdillon 
This is a very big, impactful PR. It would be nice to get another set of eyes on it at least from a design perspective. Could you give this a cursory glance with an eye towards approving the PR? I can go over details with you if you like.

**Comment by yselkowitz** [comment]
This has broken the builds of installer on !x86.  `linux_arm64` could be added to `TARGET_OS_ARCHES` in `hack/download-terraform.sh`, but there doesn't seem to be anything available to download for ppc64le or s390x.

**Pull request merged**
