### PR TITLE
update terraform-provider-ironic to v0.2.5 to get better error handling

### PR DESCRIPTION
**Pull request by asalkeld**
/cc @stbenjam

### CODE REVIEW

**Comment by stbenjam** [comment]
v0.2.4 in title/commit should be v0.2.5

/label platform/baremetal

**Comment by stbenjam** [comment]
/assign @staebler 

Could you please take a look? Thanks!

**Comment by staebler** [comment]
> /assign @staebler
> 
> Could you please take a look? Thanks!

I am trying to land https://github.com/openshift/installer/pull/4729. That is going to conflict with this. I would prefer to wait for #4729.

**Comment by staebler** [comment]
> > /assign @staebler
> > Could you please take a look? Thanks!
> 
> I am trying to land #4729. That is going to conflict with this. I would prefer to wait for #4729.

#4729 is not going to land any time soon. This PR can go in first.

**Pull request merged**
