### PR TITLE
OCPBUGS-24995: Revert "Merge pull request #7642 from AnnaZivkovic/azure_duplicate_im…

### PR DESCRIPTION
**Pull request by r4f4**
…age_gallery"

This reverts commit e2504abb0f8533d5d55592d90d051df9b7a5a56d, reversing changes made to 04a22e6157ace4ecf8a1603cc10481844caf0b82.

The PR https://github.com/openshift/installer/pull/7642 broke using Gen1-only instance types for bootstrap since it's hardcoding the usage of Gen2 images. It also breaks using marketplace image for bootstrap.

### CODE REVIEW

**Comment by r4f4** [comment]
The revert should also fix the breakage of storage account encryption: https://issues.redhat.com/browse/OCPBUGS-25007

**Comment by patrickdillon** [comment]
/approve

Will LGTM after tests. We should probably just drop the idea of implementing this in Terraform considering that it is not directly related to any customer asks.

**Pull request merged**
