### PR TITLE
hack/build: Pin to RHCOS 47.330 and quay.io/openshift-release-dev/ocp-release:4.0.0-0.6

### PR DESCRIPTION
**Pull request by wking**
DO NOT MERGE! This PR is just for CI coverage (like #1271 and similar before it), with pins on top of the change-log in #1344.

@smarterclayton pushed 4.0.0-0.nightly-2019-02-27-213933 to quay.io/openshift-release-dev/ocp-release:4.0.0-0.6.  Extracting the associated RHCOS build:

```console
$ oc adm release info --pullspecs quay.io/openshift-release-dev/ocp-release:4.0.0-0.6 | grep machine-os-content
 machine-os-content  registry.svc.ci.openshift.org/ocp/4.0-art-latest-2019-02-27-213933@sha256:1262533e31a427917f94babeef2774c98373409897863ae742ff04120f32f79b
$ oc image info registry.svc.ci.openshift.org/ocp/4.0-art-latest-2019-02-26-125216@sha256:1262533e31a427917f94babeef2774c98373409897863ae742ff04120f32f79b | grep version
           version=47.330
````

that's the same `machine-os-content` image referenced from 4.0.0-0.5, which we used for installer v0.13.0 (#1271).

/hold

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
LGTM

**Comment by wking** [comment]
[e2e-aws][1]:

```
level=error msg="\t* aws_route.to_nat_gw.2: Error creating route: timeout while waiting for state to become 'success' (timeout: 2m0s)"
```

/retest

[1]: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_installer/1345/pull-ci-openshift-installer-master-e2e-aws/4306/build-log.txt

**Comment by abhinavdahiya** [comment]
[e2e-aws](https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_installer/1345/pull-ci-openshift-installer-master-e2e-aws/4308):
```console
Failing tests:

[sig-api-machinery] CustomResourcePublishOpenAPI [Feature:CustomResourcePublishOpenAPI] works for CRD without validation schema [Suite:openshift/conformance/parallel] [Suite:k8s]
```

/retest

**Comment by wking** [comment]
[e2e-aws][1]:

```
Flaky tests:

[k8s.io] Probing container should be restarted with a exec "cat /tmp/health" liveness probe [NodeConformance] [Conformance] [Suite:openshift/conformance/parallel/minimal] [Suite:k8s]

Failing tests:

[sig-api-machinery] CustomResourcePublishOpenAPI [Feature:CustomResourcePublishOpenAPI] works for CRD without validation schema [Suite:openshift/conformance/parallel] [Suite:k8s]
```

Good enough for me.  But run one more while I upload the tag and binaries:

/retest

[1]: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_installer/1345/pull-ci-openshift-installer-master-e2e-aws/4311/build-log.txt

**Comment by wking** [comment]
[e2e-aws][1]:

```
level=fatal msg="failed to initialize the cluster: Cluster operator cluster-autoscaler has not yet reported success"
```

But whatever, this commit is [0.13.1][2].

/close

[1]: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_installer/1345/pull-ci-openshift-installer-master-e2e-aws/4314/build-log.txt
[2]: https://github.com/openshift/installer/releases/tag/v0.13.1

**Pull request closed without merging**
