### PR TITLE
WIP: master-elb: switch to target type instance

### PR DESCRIPTION
**Pull request by sttts**
This allows to preserve source IPs, important for auditing.

### CODE REVIEW

**Comment by wking** [comment]
How does this help with auditing?

**Comment by wking** [comment]
@abhinavdahiya pointed out that using the `instance` type [causes loopback problems][1].  But @sttts pointed out that we could still do this for the external Kubernetes API load balancer.  It's still not clear to me who's logging and auditing the source IP for this final layer-4 hop.

[1]: https://aws.amazon.com/premiumsupport/knowledge-center/target-connection-fails-load-balancer/

**Comment by abhinavdahiya** [comment]
I would prefer to keep the LBs same for now.
@sttts do you have a bug report that needs this to be solved or is this is a new feature request. If latter we should go through the exception process for this.

**Comment by DanyC97** [comment]
@sttts just a minor note regarding the instance type limit - i suspect you are aware of the [limits](https://docs.aws.amazon.com/elasticloadbalancing/latest/network/target-group-register-targets.html)

* _You cannot register instances by instance ID if they have the following instance types: C1, CC1, CC2, CG1, CG2, CR1, G1, G2, HI1, HS1, M1, M2, M3, and T1. You can register instances of these types by IP address._

* _You cannot register instances in a peered VPC by instance ID, you must register them by IP address._

so i'd be caution about it since that implies restrictions on what the users can use .. my 0.02$

**Comment by abhinavdahiya** [comment]
This looks abandoned. Please feel free to reopen if you think this is still something you would like to pursue

/close

**Pull request closed without merging**
