### PR TITLE
OCPBUGS-36242: vSphere - If the folder pre-exists do not tag

### PR DESCRIPTION
**Pull request by jcpowermac**
There are multiple issues resolved by this pr:

In terraform-versions of the installer we did not tag pre-existing folders. The change to capi/capv
we introduced always tagging a folder which causes failures on deprovision. This PR checks if the folder pre-exists and skips the folder create and tag attach functions.

While in development for 4.16  we created two versions of the folder validation one for terraform-based installs and another for capi/capv. That now needs to be removed - if `altinfra` tag is not defined the legacy terraform folder validation is used and will cause validation to fail if a custom folder is defined in the platform spec.

### CODE REVIEW

**Comment by jcpowermac** [comment]
found another issue, increased the priority to major
/jira refresh

**Comment by jcpowermac** [comment]
Tested with multiple executions of, when foo4 existed and did not

```
    failureDomains:
    - name: generated-failure-domain
      region: generated-region
      server: 10.93.60.138
      topology:
        computeCluster: /nested8-datacenter/host/nested8-cluster
        datacenter: nested8-datacenter
        networks:
        - VM Network
        resourcePool: /nested8-datacenter/host/nested8-cluster/Resources
        folder: /nested8-datacenter/vm/foo/foo2/foo3/foo4
```
        
and when folder did not exist
```        
 failureDomains:
    - name: generated-failure-domain
      region: generated-region
      server: 10.93.60.138
      topology:
        computeCluster: /nested8-datacenter/host/nested8-cluster
        datacenter: nested8-datacenter
        networks:
        - VM Network
        resourcePool: /nested8-datacenter/host/nested8-cluster/Resources
        ```

**Comment by jcpowermac** [comment]
/cc @vr4manta
when you have a moment can you ptal?

**Comment by jcpowermac** [comment]
Both tech preview jobs are passed the folder create portion of the installer.

**Review by r4f4 — COMMENTED** [review]
/approve

**Comment by jcpowermac** [comment]
the aws job - some image is failing to build
/retest-required

**Pull request merged**
