### PR TITLE
[vendoring] update gophercloud/utils & terraform/provider-openstack

### PR DESCRIPTION
**Pull request by EmilienM**
In order to get a change from gophercloud-utils (TLS options when
creating a service, see https://github.com/gophercloud/utils/pull/131),
we also need to update terraform-provider-openstack since mutexkv and
hashcode were moved to their own packages in gophercloud/utils and
these modules need to be updated together or we end-up with an error
like:

`plugin.terraform-provider-openstack: panic: assignment to entry in nil
map`

Signed-off-by: Emilien Macchi <emilien@redhat.com>

### CODE REVIEW

**Comment by staebler** [comment]
/hold

There are a number of features waiting on https://github.com/openshift/installer/pull/4450 to merge. This PR and that PR will conflict. So let's wait for #4450 to merge first.

**Review by Fedosin — APPROVED** [review]
/lgtm

**Comment by staebler** [comment]
The other dependency changes have merged.

/hold cancel

**Comment by EmilienM** [comment]
> The other dependency changes have merged.

ack, doing the rebase now.

**Review by staebler — COMMENTED** [review]
/approve

**Pull request merged**
