### PR TITLE
MULTIARCH-4076: PowerVS: Default region bug fix

### PR DESCRIPTION
**Pull request by AshwinHIBM**
If I press the enter key at the first option in the region survey
? Region  [Use arrows to move, type to filter, ? for more help]
\> Account Region 1
\> Account Region 2

I get the following error
X Sorry, your reply was invalid: invalid region ""

This patch fixes this error.

### CODE REVIEW

**Comment by mjturek** [comment]
I've hit this before and this looks like the proper fix, however maybe we should be more explicit on which default we want to use. As the powervs_regions.go list changes, we might find that the first entry in the list changes. We should probably always use the same default.

I think dal10 is a sane default, can you adjust for that?

**Comment by AshwinHIBM** [comment]
> > I've hit this before and this looks like the proper fix, however maybe we should be more explicit on which default we want to use. As the powervs_regions.go list changes, we might find that the first entry in the list changes. We should probably always use the same default.
> > I think dal10 is a sane default, can you adjust for that?
> 
> @mjturek had this comment been addressed? I see the default currently is `dal` and not `dal10`.

The bug is with the `region` which is just `dal`.

**Comment by AshwinHIBM** [comment]
/unhold
/test okd-images
/test e2e-aws-ovn

@mjturek These extraneous CI checks are consistently failing. What should be done?

**Comment by r4f4** [comment]
@mjturek what about we move the Jira issue to the OCPBUGS project so we can backport this if capi/PowerVS becomes the default in 4.16?

**Comment by r4f4** [comment]
/override ci/prow/okd-images
Known issue

/hold cancel

**Comment by r4f4** [comment]
/override ci/prow/e2e-aws-ovn
e2e failure not related to PR changes.

**Pull request merged**
