### PR TITLE
baremetal: correct the cacheImageURL when we don't have a provisioningIP

### PR DESCRIPTION
**Pull request by asalkeld**
/cc @zaneb

### CODE REVIEW

**Comment by zaneb** [comment]
Look legit (note this will only be useful once a future change has merged to cluster-baremetal-operator).
/approve

**Comment by hardys** [comment]
Looks good - should hold this until the CBO change is merged?

Also perhaps we should add a comment or link to explain why cacheImagePort is different?

/approve
/cc @stbenjam

**Comment by stbenjam** [comment]
This code isn't really reachable without tricks until we remove the validation on ClusterProvisioningIP. It can be tested manually if you're editing the provisioning CR before running create cluster, so there's some value in getting it in now.

Let's test disabled networking though:

/test e2e-metal-ipi-virtualmedia

**Comment by stbenjam** [comment]
https://github.com/openshift/release/pull/13852 adds virtualmedia to this repo

**Pull request merged**
