### PR TITLE
PowerVS: Add 60 sec wait time after VPC creation.

### PR DESCRIPTION
**Pull request by cs-zhang**
Signed-off-by: CS Zhang <zhangcho@us.ibm.com>

### CODE REVIEW

**Comment by mjturek** [comment]
@cs-zhang Thanks! Can you make a variable with a default of 60s rather than hardcoding the 60s?

**Review by sadasu — COMMENTED** [review]
/lgtm

**Review by jstuever — APPROVED** [review]
/approve

**Comment by mjturek** [comment]
thanks @cs-zhang

**Pull request merged**
