### PR TITLE
terraform: azurerm bump provider to v3.19.1

### PR DESCRIPTION
**Pull request by r4f4**
This is the first step needed for enabling arm64 support.

/cc @Prashanth684

### CODE REVIEW

**Comment by patrickdillon** [comment]
This LGTM, but how does this enable ARM instances/shared gallery images? The VM resource is already using the `image_source_id` attribute, which is--I believe--how we would pass a gallery image. 

Do we need to read the gallery image as a data source source or something?

**Comment by patrickdillon** [comment]
> This LGTM, but how does this enable ARM instances/shared gallery images? The VM resource is already using the `image_source_id` attribute, which is--I believe--how we would pass a gallery image.
> 
> Do we need to read the gallery image as a data source source or something?

I found the answer in a jira comment, which points to this: https://github.com/hashicorp/terraform-provider-azurerm/pull/17768

**Comment by r4f4** [comment]
The gallery image work will come in future PRs. @Prashanth684 is working on them.

**Comment by Prashanth684** [comment]
https://issues.redhat.com/browse/ARMOCP-429 has details about the changes needed for bootimage creation for arm64. The next step will be to add creation of arm64 bootimages using the image gallery.

**Comment by Prashanth684** [comment]
@patrickdillon are we good for an approval?

**Comment by Prashanth684** [comment]
@sadasu took a brief look at the e2e-azurestack error logs. the nodes are all up and all the operators are up except the csi driver and monitoring . the csi driver pods are failing with `CreateContainerConfigError` and this message:
```
secret \"azure-disk-credentials\" not found
```
i don't think it is related to this change.

**Pull request merged**
