### PR TITLE
Bug 2045927: Add proxy for ironic-agent.service

### PR DESCRIPTION
**Pull request by zhouhao3**
Avoid the issue that ironic agent image cannot be downloaded due to network proxy.

See #5552 for details.

Signed-off-by: Zhou Hao <zhouhao@fujitsu.com>

### CODE REVIEW

**Comment by ardaguclu** [comment]
Failing 2 test are perm-failing.

/approve

**Comment by ardaguclu** [comment]
e2e-alibaba looks broken. But metal-ipi-ovn-ipv6 should pass.

/override e2e-alibaba

**Comment by ardaguclu** [comment]
@staebler this e2e-alibaba job was added very recently but it is permanently failing.

Would you mind to override it?, because it is in required list. Thanks.

**Comment by hardys** [comment]
> @staebler this e2e-alibaba job was added very recently but it is permanently failing.
> 
> Would you mind to override it?, because it is in required list. Thanks.

+1 I see several PRs with fixes for alibaba but this change is clearly only impacting baremetal platform, so IMO overriding would be reasonable (the bz associated with this PR has been identified as a blocker)

The e2e-metal-ipi-ovn-dualstack job has been broken recently and several fixes have been in progress, so I think we can ignore that failure (the other metal-ipi jobs passed)

Perhaps @staebler or @patrickdillon can take a look and confirm if they're happy to override so this can merge :)

**Comment by patrickdillon** [comment]
/override ci/prow/e2e-alibaba

This job was marked required by accident

**Pull request merged**
