### PR TITLE
WIP azure: test bumping to Standard_D32s_v3

### PR DESCRIPTION
**Pull request by hexfusion**
testing only `Standard_D32s_v3`

### CODE REVIEW

**Comment by hexfusion** [comment]
> Message=\"Operation results in exceeding quota limits of standardDSv3Family Cores. Maximum allowed: 200, Current in use: 170, Additional requested: 32.

**Comment by kikisdeliveryservice** [comment]
well that's not good.

**Comment by abhinavdahiya** [comment]
Closed in favor of https://github.com/openshift/installer/pull/2367

/close

**Pull request closed without merging**
