### PR TITLE
Bug 2047935: bump RHCOS 4.11 bootimage metadata

### PR DESCRIPTION
**Pull request by aaradhak**
These changes will update the RHCOS 4.11 bootimage metadata in the installer.
This change includes fixes for the following BZs:

Bug 2032717: Unable to download ignition after coreos-installer install --copy-network

This change will also introduce artifacts for for Aliyun, AWS GovCloud regions,
and Nutanix.

Changes generated with:
```
plume cosa2stream --target data/data/coreos/rhcos.json --distro rhcos  x86_64=411.85.202203181601-0 s390x=411.85.202203181515-0 ppc64le=411.85.202203181612-0 --url https://rhcos-redirector.apps.art.xq1c.p1.openshiftapps.com/art/storage/releases --no-signatures

```

### CODE REVIEW

**Comment by miabbott** [comment]
`e2e-azure-upi` has [been red/yellow for over a week](https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/pull-ci-openshift-installer-master-e2e-azure-upi?buildId=).  The failing tests on this run are:

```
[sig-arch][bz-etcd][Late] Alerts alert/etcdHighNumberOfFailedGRPCRequests should not be at or above info [Suite:openshift/conformance/parallel]
[sig-network-edge][Conformance][Area:Networking][Feature:Router] The HAProxy router should pass the gRPC interoperability tests [Suite:openshift/conformance/parallel/minimal]
[sig-network-edge][Conformance][Area:Networking][Feature:Router] The HAProxy router should pass the h2spec conformance tests [Suite:openshift/conformance/parallel/minimal]
[sig-network-edge][Conformance][Area:Networking][Feature:Router] The HAProxy router should pass the http2 tests [Suite:openshift/conformance/parallel/minimal]
[sig-storage] In-tree Volumes [Driver: azure-disk] [Testpattern: Dynamic PV (delayed binding)] topology should provision a volume and schedule a pod with AllowedTopologies [Suite:openshift/conformance/parallel] [Suite:k8s]
```

These look like the same tests that have been failing in other runs of the job and don't appear to be correlated with this PR.

**Comment by miabbott** [comment]
`e2e-crc` has been [red/yellow for over a week.](https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/pull-ci-openshift-installer-master-e2e-crc?buildId=)  The failing job can't even start successfully as the `e2e-crc-openshift-e2e-gcp-crc-test` step is failing:

```
++ curl -L https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp-dev-preview//candidate-4.10/release.txt
++ sed -n 's/^ *Version: *//p'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    52  100    52    0     0     22      0  0:00:02  0:00:02 --:--:--    22
100    52  100    52    0     0     22      0  0:00:02  0:00:02 --:--:--    22
Unable to determine an OpenShift release version.  You may want to set the OPENSHIFT_VERSION environment variable explicitly.
+ OPENSHIFT_RELEASE_VERSION=
+ test -n ''
+ echo 'Unable to determine an OpenShift release version.  You may want to set the OPENSHIFT_VERSION environment variable explicitly.'
+ exit 1
+ jobs=($(jobs -p))
++ jobs -p
+ '[' -n '' ']'
+ true
{"component":"entrypoint","error":"wrapped process failed: exit status 1","file":"k8s.io/test-infra/prow/entrypoint/run.go:80","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2022-03-22T04:43:44Z"}
error: failed to execute wrapped command: exit status 1
```

This looks unrelated to this PR.

**Comment by miabbott** [comment]
`e2e-ibmcloud` has been [red/yellow for over a week](https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/pull-ci-openshift-installer-master-e2e-ibmcloud?buildId=).  It looks like the `e2e-ibmcloud-ipi-install-install` is failing because it can't setup the DNS config:

`level=fatal msg=failed to fetch Common Manifests: failed to fetch dependency of "Common Manifests": failed to generate asset "DNS Config": failed ot get DNS zone ID: failed to list DNS zones: Exactly one of ApiKey or RefreshToken must be specified.`

This looks unrelated to this PR

**Comment by miabbott** [comment]
`e2e-metal-ipi-ovn-ipv6` looks like it has been mostly [red for over a week](https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/pull-ci-openshift-installer-master-e2e-metal-ipi-ovn-ipv6?buildId=).  It looks like the `baremetalds-devscripts-setup` step but I'm having a hard time sifting through the logs.

The failure modes for the past failed jobs are not consistent, either.

From what I can tell in the `journal` from a control plane node in the `gather-extra` subdir, it looks like this job is using it's own definition for boot images, because the output from the pivot to the new `machine-os-content` shows packages upgraded from `el8_4` to `el8_5`.

`NetworkManager 1:1.30.0-13.el8_4 -> 1:1.32.10-4.el8`

So I'm not sure this is a good job to validate the new bootimage that is introduced by this change.

**Comment by miabbott** [comment]
`okd-e2e-aws-upgrade` isn't valid for this PR since OKD uses FCOS.

**Comment by miabbott** [comment]
> `e2e-azure-upi` has [been red/yellow for over a week](https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/pull-ci-openshift-installer-master-e2e-azure-upi?buildId=). The failing tests on this run are:
> 
> ```
> [sig-arch][bz-etcd][Late] Alerts alert/etcdHighNumberOfFailedGRPCRequests should not be at or above info [Suite:openshift/conformance/parallel]
> [sig-network-edge][Conformance][Area:Networking][Feature:Router] The HAProxy router should pass the gRPC interoperability tests [Suite:openshift/conformance/parallel/minimal]
> [sig-network-edge][Conformance][Area:Networking][Feature:Router] The HAProxy router should pass the h2spec conformance tests [Suite:openshift/conformance/parallel/minimal]
> [sig-network-edge][Conformance][Area:Networking][Feature:Router] The HAProxy router should pass the http2 tests [Suite:openshift/conformance/parallel/minimal]
> [sig-storage] In-tree Volumes [Driver: azure-disk] [Testpattern: Dynamic PV (delayed binding)] topology should provision a volume and schedule a pod with AllowedTopologies [Suite:openshift/conformance/parallel] [Suite:k8s]
> ```
> 
> These look like the same tests that have been failing in other runs of the job and don't appear to be correlated with this PR.

Filed https://bugzilla.redhat.com/show_bug.cgi?id=2067323 for the HAProxy failures

https://bugzilla.redhat.com/show_bug.cgi?id=2066865 exists for the Dynamic PV failure

**Comment by miabbott** [comment]
> `e2e-ibmcloud` has been [red/yellow for over a week](https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/pull-ci-openshift-installer-master-e2e-ibmcloud?buildId=). It looks like the `e2e-ibmcloud-ipi-install-install` is failing because it can't setup the DNS config:
> 
> `level=fatal msg=failed to fetch Common Manifests: failed to fetch dependency of "Common Manifests": failed to generate asset "DNS Config": failed ot get DNS zone ID: failed to list DNS zones: Exactly one of ApiKey or RefreshToken must be specified.`
> 
> This looks unrelated to this PR

Looks like https://bugzilla.redhat.com/show_bug.cgi?id=2066463

**Comment by miabbott** [comment]
> `e2e-crc` has been [red/yellow for over a week.](https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/pull-ci-openshift-installer-master-e2e-crc?buildId=) The failing job can't even start successfully as the `e2e-crc-openshift-e2e-gcp-crc-test` step is failing:
> 
> ```
> ++ curl -L https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp-dev-preview//candidate-4.10/release.txt
> ++ sed -n 's/^ *Version: *//p'
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> 100    52  100    52    0     0     22      0  0:00:02  0:00:02 --:--:--    22
> 100    52  100    52    0     0     22      0  0:00:02  0:00:02 --:--:--    22
> Unable to determine an OpenShift release version.  You may want to set the OPENSHIFT_VERSION environment variable explicitly.
> + OPENSHIFT_RELEASE_VERSION=
> + test -n ''
> + echo 'Unable to determine an OpenShift release version.  You may want to set the OPENSHIFT_VERSION environment variable explicitly.'
> + exit 1
> + jobs=($(jobs -p))
> ++ jobs -p
> + '[' -n '' ']'
> + true
> {"component":"entrypoint","error":"wrapped process failed: exit status 1","file":"k8s.io/test-infra/prow/entrypoint/run.go:80","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2022-03-22T04:43:44Z"}
> error: failed to execute wrapped command: exit status 1
> ```
> 
> This looks unrelated to this PR.

https://bugzilla.redhat.com/show_bug.cgi?id=2067327

**Review by saqibali-2k — APPROVED** [review]
/lgtm

**Review by mike-nguyen — APPROVED** [review]

**Pull request merged**
