### PR TITLE
openstack UPI: Automate Security Group creation

### PR DESCRIPTION
**Pull request by pierreprinetti**
Create an Ansible playbook for deploying the Security Groups required
for a User Provided Infrastructure installation.

Implements https://jira.coreos.com/browse/OSASINFRA-785

Depends on #2580

### CODE REVIEW

**Comment by pierreprinetti** [comment]
/hold

while we figure out if this can be merged during Feature Freeze.

**Comment by gageorsburn** [comment]
Curiosity question, why is this done with ansible and not terraform?

**Comment by pierreprinetti** [comment]
@gageorsburn 

I believe it could have been either way; the [RFE](https://github.com/openshift/enhancements/pull/23) goes like this:

> Ansible is a tool system administrators already tend to be familiar with

**Comment by gageorsburn** [comment]
Thanks for the information!

**Comment by pierreprinetti** [comment]
Don't give up, @openshift-bot!

**Pull request merged**
