### PR TITLE
Correcting normal typos

### PR DESCRIPTION
**Pull request by Shivkumar13**
Fixed the typo under data/data/bootstrap/baremetal/README.md 

To have a better reader experience  fixed this typo.

### CODE REVIEW

**Review by staebler — COMMENTED** [review]
Thanks for the typo fix. Please fix up the commit message to adhere to the [contributing guidelines](https://github.com/openshift/installer/blob/master/CONTRIBUTING.md#commit-message-format).

**Review by stbenjam — CHANGES_REQUESTED** [review]
This looks fine to me, but as @staebler said please fix commit message

**Comment by Shivkumar13** [comment]
@staebler @stbenjam I have done the necessary changes to commit message, please verify and let me know in case of any changes needed.

**Review by staebler — APPROVED** [review]
/ok-to-test
/lgtm
/approve

**Pull request merged**
