### PR TITLE
CORS-3419,OCPBUGS-30941: Include baremetal IPI in openshift-installer

### PR DESCRIPTION
**Pull request by zaneb**
Now that we do not dynamically link to libvirt, there is no need to restrict baremetal IPI to the openshift-baremetal-installer binary and it can be included in all builds of the installer.

### CODE REVIEW

**Comment by zaneb** [comment]
/retitle CORS-3419,OCPBUGS-30941: Include baremetal IPI in openshift-installer

**Review by sadasu — APPROVED** [review]

**Comment by sadasu** [comment]
@zaneb should https://github.com/openshift/installer/blob/master/images/baremetal/Dockerfile.ci be modified as part of these changes?

See https://github.com/openshift/installer/pull/8240

**Comment by zaneb** [comment]
> @zaneb should https://github.com/openshift/installer/blob/master/images/baremetal/Dockerfile.ci be modified as part of these changes?

This change shouldn't affect openshift-baremetal-install at all, but there will be changes to that upcoming.

**Comment by r4f4** [comment]
It would be good if we could update one of the metal jobs to use the `openshift-install` binary instead of the `baremetal-install` one to validate the PR changes.

**Comment by r4f4** [comment]
> It would be good if we could update one of the metal jobs to use the `openshift-install` binary instead of the `baremetal-install` one to validate the PR changes.

It seems `openshift-install` selection happens in the `dev-scripts` code [1] so we can't easily changed that in CI for a particular job.

/lgtm

[1] https://github.com/openshift-metal3/dev-scripts/blob/a19f80f69c7bce68fc5a68c743c1745ba18651ac/common.sh#L209

**Pull request merged**
