### PR TITLE
OCPBUGS-30005: remove github.com/IBM-Cloud/bluemix-go/api/account/accountv2

### PR DESCRIPTION
**Pull request by hamzy**
The following go module:
"github.com/IBM-Cloud/bluemix-go/api/account/accountv2" is now failing dues to Cloud Foundry being removed. Remove it!

### CODE REVIEW

**Comment by r4f4** [comment]
Shouldn't you run `go mod vendor` to delete the unused lib?

**Comment by hamzy** [comment]
Unfortunately, we use the other parts of the module a lot in PowerVS.  We can't rely on one section of it.

**Comment by r4f4** [comment]
> Unfortunately, we use the other parts of the module a lot in PowerVS. We can't rely on one section of it.

If I run `go mod vendor` on your PR, I get:
```
$ git status
On branch pr/8072
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	deleted:    vendor/github.com/IBM-Cloud/bluemix-go/api/account/accountv2/accounts.go
	deleted:    vendor/github.com/IBM-Cloud/bluemix-go/api/account/accountv2/api_service.go
	deleted:    vendor/github.com/IBM-Cloud/bluemix-go/api/account/accountv2/paginate.go
	modified:   vendor/modules.txt

no changes added to commit (use "git add" and/or "git commit -a")
```

/test verify-vendor

**Comment by hamzy** [comment]
Interesting, I did not think go vendoring was so fine grained!

**Review by r4f4 — COMMENTED** [review]
/approve

**Comment by r4f4** [comment]
@hamzy it seems you need to do the cherry-pick manually. Remember to use `/jira cherrypick OCPBUGS-30005` in the new PR for proper bug cloning.

**Comment by hamzy** [comment]
@r4f4 It was worth a shot and thanks for the reminder! :)

**Pull request merged**
