### PR TITLE
openstack UPI: Use ansible-galaxy

### PR DESCRIPTION
**Pull request by pierreprinetti**
Document the use of ansible-galaxy as a dependency manager for the
Ansible playbooks in UPI.

Implements [OSASINFRA-2169](https://issues.redhat.com/browse/OSASINFRA-2169)

### CODE REVIEW

**Comment by EmilienM** [comment]
Looking at the CI logs for e2e-openstack-upi, the Ansible portion worked fine: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_installer/4379/pull-ci-openshift-installer-master-e2e-openstack-upi/1327395066704039936

It failed later with a timeout during OCP install, but I don't think this is related to this patch.

/lgtm
/approve

**Review by EmilienM — APPROVED** [review]

**Comment by pierreprinetti** [comment]
CC @maxwelldb

**Comment by maxwelldb** [comment]
@pierreprinetti What's the target release for this? 4.7+? I don't see it in OSASINFRA-2169.

**Comment by pierreprinetti** [comment]
@maxwelldb That would be 4.7, but I'm trying to understand whether I need to revert this change actually.

**Pull request merged**
