### PR TITLE
CORS-3426, CORS-3308, CORS-3289: Bump CAPA provider for various fixes

### PR DESCRIPTION
**Pull request by r4f4**
Some PRs were merged fixing the following issues:
 * S3 object deletion failing with NotFound errors
 * assigning public IP to machines
 * Secondary LBs security groups not being applied
 * health check parameters updated

### CODE REVIEW

**Comment by r4f4** [comment]
/hold
If there is a 2.4.z release soon, I'll bump to that.

**Comment by r4f4** [comment]
Update: changed the bumped version to the latest `main` since it contains fixes needed to unblock edge networks ongoing work.

I have also decided to not wait for a 2.4.z release since soon we'll have to bump the provider again with upstream fixes needed to support other features like BYOIP.

/hold cancel

**Comment by r4f4** [comment]
`shared-vpc` and `custom-security-groups` from the `altinfra` variant both passed the cluster install stage.

/hold cancel

**Comment by patrickdillon** [comment]
> `shared-vpc` and `custom-security-groups` from the `altinfra` variant both passed the cluster install stage.
> 
> /hold cancel

They also passed e2es!

/approve

**Pull request merged**
