### PR TITLE
Bug 1841066: OpenStack: Remove DNS VIP

### PR DESCRIPTION
**Pull request by mandre**
Depends on https://github.com/openshift/machine-config-operator/pull/1666

### CODE REVIEW

**Comment by mandre** [comment]
We need openshift/machine-config-operator#1666 to merge first.

**Comment by mandre** [comment]
/hold cancel
tests are passing

**Comment by mandre** [comment]
/assign sdodson
for approval :)

**Comment by jichenjc** [comment]
@mandre do we plan to backport this PR to 4.5 or keep it to master (so it will be 4.6?)
seems https://github.com/openshift/installer/blob/release-4.5/data/data/openstack/bootstrap/main.tf still has DNS VIP in the code

**Pull request merged**
