### PR TITLE
Bug 1824991: Update vSphere and Metal UPI for terraform 0.12

### PR DESCRIPTION
**Pull request by jcpowermac**
Cherry-pick: https://github.com/openshift/installer/pull/3429

### CODE REVIEW

**Comment by jcpowermac** [comment]
Not enough resources
/test e2e-vsphere

**Comment by jcpowermac** [comment]
@varungur is there something that needs to be done with this PR to make sure metal is not broken once this is approved?

**Comment by sdodson** [comment]
Can you pick a7ca3ffa80461b880ff91d7d15b8e964b5ae8902 into this?

**Comment by sdodson** [comment]
Will `cherry-pick-approve` this later once the branch opens. The installation completed successfully but there are e2e failures in vsphere.

**Comment by sdodson** [comment]
/retitle Bug 1824991: Update vSphere and Metal UPI for terraform 0.12

**Pull request merged**
