### PR TITLE
Provide the correct console URL

### PR DESCRIPTION
**Pull request by wgordon17**

### CODE REVIEW

**Comment by wgordon17** [comment]
@sallyom Awesome! It still doesn't appear to update the README.md with the correct console path, so this PR is probably still beneficial

**Comment by abhinavdahiya** [comment]
@wgordon17 do you think the installer output regarding the console url on succesfull install is not sufficient and requires more documentation in `README.md` ?

**Comment by wgordon17** [comment]
@abhinavdahiya It honestly probably is sufficient! Perhaps I should change my PR to remove the console URL section from the README.md then?

**Comment by wking** [comment]
> Perhaps I should change my PR to remove the console URL section from the README.md then?

Yeah, can you remove the whole `Connect to the cluster` section?  Or replace it with something that shows the tail end of the `create cluster` output with the lines from #806, and then talks about using that information (so folks who are just reading along can see what the next steps after running the command would be).

**Comment by wking** [comment]
> Or replace it with something that shows the tail end of the `create cluster` output...

If you want to go this route, they currently look like:

```
level=info msg="Install complete!"
level=info msg="Run 'export KUBECONFIG=/tmp/artifacts/installer/auth/kubeconfig' to manage the cluster with 'oc', the OpenShift CLI."
level=info msg="The cluster is ready when 'oc login -u kubeadmin -p yQBMF-Ahp9Q-naycI-3H7tB' succeeds (wait a few minutes)."
level=info msg="Access the OpenShift web-console here: https://console-openshift-console.apps.ci-op-siing9c6-1d3f3.origin-ci-int-aws.dev.rhcloud.com"
level=info msg="Login to the console with user: kubeadmin, password: yQBMF-Ahp9Q-naycI-3H7tB"
```

**Comment by wgordon17** [comment]
@wking I've updated the content

**Pull request merged**
