### PR TITLE
vsphereprivate: update to v2 terraform sdk

### PR DESCRIPTION
**Pull request by jcpowermac**

### CODE REVIEW

**Comment by patrickdillon** [comment]
/approve

This LGTM. I'll give it some time in case any one else wants to take a look.

**Comment by patrickdillon** [comment]
/hold
Let's sort out the relatoinship between this and #5357 because it looks like these changes are being pulled in there, which may make more sense as it has the relevant context.

**Comment by patrickdillon** [comment]
Rereading the comments from #5357 I see that there is no connection which is the reason this was split out. My mistake.

/hold cancle

**Review by staebler — COMMENTED** [review]
/lgtm

**Pull request merged**
