### PR TITLE
OCPBUGS-16415: Sync nmstateconfig script with assisted-service changes

### PR DESCRIPTION
**Pull request by bfournie**
There have been some recent changes to the script used for nmstateconfig in assisted-service/internal/constants/scripts.go that would be useful to pick up. This fix will sync network-scripts.sh with assisted-service.

The changes that will be included are the following: https://github.com/openshift/assisted-service/pull/4859 https://github.com/openshift/assisted-service/pull/5233 https://github.com/openshift/assisted-service/pull/5107

### CODE REVIEW

**Comment by bfournie** [comment]
Tested in dev-scripts with:
- COMPACT_IPV4
- COMPACT_IPV4V6
- COMPACT_IPV4_DHCP
- SNO_IPV6

**Review by rwsu — COMMENTED** [review]
/lgtm

**Review by rwsu — COMMENTED** [review]
/lgtm

**Pull request merged**
