### PR TITLE
[4.3] Increase the amount of memory for control plane nodes on vsphere upi

### PR DESCRIPTION
**Pull request by jcpowermac**
Modified the machine module to take memory as an option.
Modified main adding memory values per type.

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
these match more closely to the minimum resource required for vsphere https://docs.openshift.com/container-platform/4.1/installing/installing_vsphere/installing-vsphere.html#minimum-resource-requirements_installing-vsphere

**Comment by adambkaplan** [comment]
@jcpowermac is this the right BZ? Report was related to builds, which don't run on control plane nodes.

**Comment by adambkaplan** [comment]
/retitle Increase the amount of memory for control plane nodes on vsphere upi

@jcpowermac if you need a BZ for this, please create a new one.

**Comment by jcpowermac** [comment]
@adambkaplan will do.  Thanks

**Comment by jcpowermac** [comment]
@abhinavdahiya do we still need this PR?  If so I can create a BZ for the issue.

**Comment by abhinavdahiya** [comment]
/hold

Candidate for 4.3

**Comment by jcpowermac** [comment]
@abhinavdahiya can we unhold this now that 4.3 is open?  Would like to see if this helps CI.

**Comment by jcpowermac** [comment]
Closing in favor of https://github.com/openshift/installer/pull/2397

**Pull request closed without merging**
