### PR TITLE
CORS-2340: hack: replace deprecated go-lint

### PR DESCRIPTION
**Pull request by r4f4**
Use golangci-lint instead, which is an aggregator of linters.

Resolves https://issues.redhat.com/browse/CORS-2340

### CODE REVIEW

**Comment by r4f4** [comment]
CI change: https://github.com/openshift/release/pull/34150

**Review by barbacbd — COMMENTED** [review]
/lgtm

Talked to Rafael about edging down the number of warnings and there is a plan in place, so I am good here.

**Comment by r4f4** [comment]
/hold
Needs the PR in the release repo in first.

**Comment by r4f4** [comment]
> /lgtm
> 
> Talked to Rafael about edging down the number of warnings and there is a plan in place, so I am good here.

Just to expand on this, the plan is to use `--new-from-rev=$master_commit` (see https://github.com/openshift/release/pull/34150) , so the linter should only report warnings on newly added code. I'm not hard-coding this option to `hack/go-lint.sh` since it can easily be passed in by the devs during local development.

**Comment by r4f4** [comment]
/override ci/prow/golint
I will fix linting issues in a follow-up PR.

**Comment by r4f4** [comment]
/override ci/prow/e2e-azure-ovn
Test timeout after 4h, install succeeded.

**Comment by r4f4** [comment]
/override ci/prow/e2e-aws-ovn ci/prow/e2e-gcp-ovn ci/prow/e2e-vsphere-ovn ci/prow/images

**Pull request merged**
