### PR TITLE
OCPBUGS-34037: bump github.com/container/images for CVE fix

### PR DESCRIPTION
**Pull request by r4f4**
SSIA

### CODE REVIEW

**Comment by r4f4** [comment]
/cherry-pick release-4.16 release-4.15 release-4.14 release-4.13 release-4.12

**Comment by r4f4** [comment]
/hold
I always forget about the unit tests.

**Comment by sadasu** [comment]
/lgtm

unit tests have passed

**Comment by r4f4** [comment]
/hold cancel
Fixed now.

**Comment by r4f4** [comment]
`e2e-agent-compact-ipv4` passed before in this PR. The agent team inspected the error and it doesn't look related to the PR changes.

**Comment by r4f4** [comment]
Update: rebased to fix merge conflicts.

**Review by barbacbd — COMMENTED** [review]
/lgtm

**Comment by r4f4** [comment]
/override  ci/prow/e2e-agent-compact-ipv4 ci/prow/okd-e2e-agent-compact-ipv4
Known to fail right now and the job passed in a previous run

**Comment by r4f4** [comment]
Out of 8 runs of `e2e-aws-ovn` in this PR:
* 2 failed because of infra issues importing image streams: [1](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_installer/8564/pull-ci-openshift-installer-master-e2e-aws-ovn/1800371357553266688), [2](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_installer/8564/pull-ci-openshift-installer-master-e2e-aws-ovn/1800565213964013568)
* 1 failed because of network issues importing the release image: [1](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_installer/8564/pull-ci-openshift-installer-master-e2e-aws-ovn/1801347512628416512)
* 1 failed while waiting for cluster operators: [1](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_installer/8564/pull-ci-openshift-installer-master-e2e-aws-ovn/1801588340462456832)
* 4 succeeded: [1](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_installer/8564/pull-ci-openshift-installer-master-e2e-aws-ovn/1800599205534765056), [2](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_installer/8564/pull-ci-openshift-installer-master-e2e-aws-ovn/1800293118285713408), [3](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_installer/8564/pull-ci-openshift-installer-master-e2e-aws-ovn/1800255749729816576), [4](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_installer/8564/pull-ci-openshift-installer-master-e2e-aws-ovn/1800215464668827648)

**Comment by r4f4** [comment]
/cherry-pick release-4.16 release-4.15 release-4.14 release-4.13 release-4.12

**Comment by r4f4** [comment]
/cherrypick release-4.16 release-4.15 release-4.14 release-4.13 release-4.12

**Pull request merged**
