### PR TITLE
OCPBUGS-33542: images: do not force terraform-providers to be statically linked

### PR DESCRIPTION
**Pull request by r4f4**
They should be dynamically linked as the rest of the binaries for FIPS support.

### CODE REVIEW

**Comment by r4f4** [comment]
/retitle OCPBUGS-33542: images: do not force terraform-providers to be statically linked

**Comment by LorbusChris** [comment]
apologies for the noise, just testing something unrelated
/test okd-scos-images

**Comment by patrickdillon** [comment]
/approve
/lgtm
/label backport-risk-assessed

This change is skipping 4.15 and going directly into 4.16 right? So the expectation is that @zaneb will apply the valid bug label?

**Comment by r4f4** [comment]
> This change is skipping 4.15 and going directly into 4.16 right? So the expectation is that @zaneb will apply the valid bug label?

The other way around, yes. We want it to be static in 4.16+ so we're skipping 4.16 and going directly to 4.15.

**Comment by r4f4** [comment]
> /label jira/valid-bug Did we ever establish why this is not getting built with the same toolchain as everything else (that would have forced CGO_ENABLED=1)?

I have not dug into it. I'd conjecture that's because the image is not itself a release artifact.

**Pull request merged**
