### PR TITLE
Bug 1826688: Add bootstrap FIP and masters IPs to terraform output

### PR DESCRIPTION
**Pull request by Fedosin**

### CODE REVIEW

**Comment by Fedosin** [comment]
From the logs:

> DEBUG Outputs:                                     
> DEBUG                                              
> DEBUG bootstrap_floating_ip = 10.0.109.253         
> DEBUG master_ips = [                               
> DEBUG   "10.0.128.15",                             
> DEBUG   "10.0.128.32",                             
> DEBUG   "10.0.128.23",                             
> DEBUG ]  

From `terraform.tfstate`

``` json
  "outputs": {
    "bootstrap_floating_ip": {
      "value": "10.0.109.253",
      "type": "string"
    },
    "master_ips": {
      "value": [
        "10.0.128.15",
        "10.0.128.32",
        "10.0.128.23"
      ],
      "type": [
        "tuple",
        [
          "string",
          "string",
          "string"
        ]
      ]
    }
  },
```

**Comment by abhinavdahiya** [comment]
can you explain why https://github.com/openshift/installer/blob/master/pkg/terraform/gather/openstack/ip.go is not sufficient?

openshift-install --dir <> gather bootstrap should automatically use above to get the IPs.

**Comment by abhinavdahiya** [comment]
> can you explain why https://github.com/openshift/installer/blob/master/pkg/terraform/gather/openstack/ip.go is not sufficient?
> 
> openshift-install --dir <> gather bootstrap should automatically use above to get the IPs.

/hold

no terraform output should be user _consumable_, it is only designed to be used by openshift-install binary. So adding outputs fall into that bucket and shouldn't be added.

**Comment by Fedosin** [comment]
@abhinavdahiya good to know :) Let's wait for what @morenod says.

**Comment by Fedosin** [comment]
Seems like we don't need these values in the output. So, I'm closing this PR.

**Pull request closed without merging**
