### PR TITLE
CORS-3417: capa bump fallout

### PR DESCRIPTION
**Pull request by r4f4**
Fallout from https://github.com/openshift/installer/pull/8114. I missed the `replace` pinning the CAPA version to 2.4.0.

We need the newer version to be able to specify ignition proxy information.

### CODE REVIEW

**Comment by r4f4** [comment]
/label acknowledge-critical-fixes-only
CAPI changes are behind a feature gate.

**Review by mtulio — COMMENTED** [review]
/lgtm

**Pull request merged**
