### PR TITLE
[WIP]: hyperthreading option

### PR DESCRIPTION
**Pull request by staebler**
Add a `hyperthreading` field to machine pools. Valid values are `Enabled` and `Disabled`, with the default being `Disabled`.

If hyperthreading is enabled for a machine pool, then a manifest will be added that includes a `MachineConfig` to supplement the ignition config to enable hyperthreading.

TODO:
* Fill out the ignition config with the specifics of how hyperthreading is enabled.
* Use the machine pool name instead of the role for the `MachineConfig`. As it is now, there is only a single ignition config used by all compute pools. This does not offer the necessary granularity to enabled hyperthreading for subsets of the compute machine pools.

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
Can you open this on master-4.1 branch

**Comment by cgwalters** [comment]
You should really CC the MCO team on PRs like this.

First, this ends up being [a kernel argument](https://github.com/openshift/machine-config-operator/issues/388) `nosmt` right?

I think we should have a sub-controller of the MCO that reacts to `operatingsystemconfig` or something.

A `MachineConfigPool` is a view of the status of a config, it shouldn't affect config generation.

**Comment by kikisdeliveryservice** [comment]
>     * Fill out the ignition config with the specifics of how hyperthreading is enabled.

If ignition doesn't support kernel arguments, what will you be doing in the ignition config?

**Comment by ajeddeloh** [comment]
Setting kernel args is out of scope for Ignition. It's bootloader (and bootloader config) specific. Setting them could involve calling some part of an api (i.e. with ostree), writing a file, appending to a file, or might be impossible. In the event we need to write files, Ignition supports that already and we should just use that. In the event we need to call out to some other tool, we should use systemd units.

In any event it's not ideal since we'd need to reboot to take effect.

**Pull request closed without merging**
