### PR TITLE
Pass baremetal infra images to MCO bootstrap

### PR DESCRIPTION
**Pull request by cybertron**
In order for the baremetal infra services to use the images from the
release, we need to look up the correct image during bootstrap and
pass that in to the MCO.

### CODE REVIEW

**Comment by russellb** [comment]
Please add a reference to the related issue in your commit message - #2067

**Comment by metal3ci** [comment]
Build SUCCESS, see build http://10.8.144.11:8080/job/dev-tools/923/

**Comment by metal3ci** [comment]
Build SUCCESS, see build http://10.8.144.11:8080/job/dev-tools/926/

**Comment by russellb** [comment]
Is this still WIP? I would expect this as part of a patch series that also removes all of the bootstrap assets from the installer.

Another helpful reference for this commit would be the change on the MCO side to support these new options.

**Comment by cybertron** [comment]
This is no longer WIP as of this morning. We got the master and worker templates sorted out in MCO yesterday and the PR merged today. I'll add a reference to it in the commit message.

I didn't include the bootstrap change in this PR because I didn't want to block it on the bootstrap MCO change since we did that separately. If that change merges before this one then I'll go ahead and add the bootstrap changes to this PR. Otherwise we'll submit a followup.

**Comment by russellb** [comment]
@abhinavdahiya ready for you to take a look to approve

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/952/

**Comment by stbenjam** [comment]
e2e-aws-scaleup-rhel7 is ok to fail, I'm not sure I've actually seen it pass... We just need an approval to get this  in.

/assign @smarterclayton

**Comment by abhinavdahiya** [comment]
Needs reference to the machine-config-operator PR that added these flags.

**Comment by abhinavdahiya** [comment]
https://github.com/openshift/machine-config-operator/pull/795

**Pull request merged**
