### PR TITLE
Revendor with golang 1.18

### PR DESCRIPTION
**Pull request by r4f4**
Golang >= 1.18 is needed to use newer Azure APIs.

### CODE REVIEW

**Review by barbacbd — COMMENTED** [review]
The go.sum file appears to have a lot of removals with this change to go 1.18. Are any of these going to break what is currently expected to execute?

**Comment by r4f4** [comment]
The UPI images haven't been updated to use golang-1.18 yet. See https://github.com/openshift/installer/pull/6163

**Comment by patrickdillon** [comment]
This LGTM. Just needs a rebase

/approve

**Pull request merged**
