### PR TITLE
BUG 1831717: Ensure AWS PublicIP is omitted from MachineSet when empty

### PR DESCRIPTION
**Pull request by JoelSpeed**
This is a UX improvement for MachineSets created by the installer on AWS

Related to https://github.com/openshift/cluster-api-provider-aws/pull/320

PR opened so that I can test this and track updating from BZ, will need to revert back to the openshift fork once the dependent PR is merged

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
needs rebase i guess...? @JoelSpeed 

/approve

**Comment by enxebre** [comment]
/hold
to stop retest spamming until we rebase it.

**Pull request merged**
