### PR TITLE
Update initial FCOS to 31.20200505.3.0

### PR DESCRIPTION
**Pull request by vrutkovs**
/approve
/cc @LorbusChris 

Fixes https://github.com/openshift/okd/issues/153

### CODE REVIEW

**Comment by cgruver** [comment]
I don't know if this issue will affect us or not: https://github.com/coreos/fedora-coreos-tracker/issues/496

I did successfully build 2 UPI OKD 4.4 clusters using iPXE this weekend using FCOS v. 31.20200517.2.0 from the testing stream, which in theory would be affected by the same issue.

**Comment by vrutkovs** [comment]
It doesn't seem to affect us - masters/workers boot with ssh keys, probably MCD's path is different and doesn't trigger the bug

**Pull request merged**
