### PR TITLE
openstack: Rely on Go's stdlib for errors

### PR DESCRIPTION
**Pull request by pierreprinetti**
The package github.com/pkg/errors has been archived and its functionality integrated in Go's standard library.

### CODE REVIEW

**Comment by pierreprinetti** [comment]
The failing test in [e2e-openstack](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_installer/6656/pull-ci-openshift-installer-master-e2e-openstack/1599496859083083776) is not related.

**Comment by pierreprinetti** [comment]
e2e-openstack's failure is unrelated. This should be good to merge

/cc mandre

**Review by mandre — COMMENTED** [review]
Thanks!
/lgtm
/approve

**Pull request merged**
