### PR TITLE
rhcos: Pin to previous version

### PR DESCRIPTION
**Pull request by cgwalters**
Something went wrong with our new build system; looks like broken
networking in the initramfs.  Pin for now.

### CODE REVIEW

**Comment by cgwalters** [comment]
I verified with a local libvirt run this got my master machine to Ignite again.  Going to dive into what changed in the builds now.

**Comment by cgwalters** [comment]
This passed the installer just fine, so if it flakes on e2e-aws I vote we force it in.

**Comment by crawford** [comment]
/hold

I don't like the precedent this sets. The installer cannot be the backstop for a CI failure. Give me a few minutes to figure out the next move. I want to hold this for a second though.

**Comment by cgwalters** [comment]
> The installer cannot be the backstop for a CI failure.

Agreed, and we have plans to fix it.  

As far as "right now" fixes we could revert the build...it's also ugly.

**Comment by ashcrow** [comment]
> As far as "right now" fixes we could revert the build...it's also ugly.

Agreed.

**Comment by crawford** [comment]
We're going to hold here and wait for an OS fix. I'm going to leave this open in case something goes very wrong and we end up needing this change, but I do not intend to merge this at this point.

/approve cancel
/lgtm cancel

**Comment by wking** [comment]
> We're going to hold here and wait for an OS fix.

Do we have a time estimate on that fix?  Even if it's just reverting something, I expect it will take time to build a new image and push it through the RHCOS release pipeline.  Are we ok with an org-wide e2e-aws outage while we wait for that?  I'm personally fine landing this as a temporary stop-gap, reverting it once the RHCOS pipeline is fixed for this particular issue, and then using #1286 consuming e2e-aws-gated RHCOS pins to avoid issues like this in the future.

**Comment by ashcrow** [comment]
It's as soon as possible. In the meantime @darkmuggle is pausing the pipeline and removing the offending build.

**Comment by wking** [comment]
> In the meantime @darkmuggle is pausing the pipeline and removing the offending build.

Do we have a time estimate on that?  Might be faster than waiting on CI here anyway ;)

**Comment by ashcrow** [comment]
He's doing it right now ... My guess is around 10 minutes.

**Comment by cgwalters** [comment]
https://github.com/coreos/coreos-assembler/pull/375

**Comment by ashcrow** [comment]
The offending build has been removed, the current pipeline is frozen while we test a fix that just merged to `coreos-assembler`.

The latest listed image from the pipeline should be stable again.

**Comment by ashcrow** [comment]
Latest listed build is `47.334` which is what this PR wanted to pin on. :smile:

**Pull request closed without merging**
