### PR TITLE
OCPBUGS-1881: vsphere/destroy: improve logs when folder is not empty

### PR DESCRIPTION
**Pull request by r4f4**
If the folder is not empty and it contains anything other than "virtualmachine" objects, the installer might be stuck in a loop and the only message we get about it is:

level=debug msg="Folder: Expected Folder $folder to be empty"

Let's improve that message by expanding on which objects in the folder are preventing the installer from destroying the cluster.

### CODE REVIEW

**Comment by sadasu** [comment]
/approve
@r4f4 nice fix! Do you think this needs to be back ported to older releases?

**Comment by r4f4** [comment]
> /approve @r4f4 nice fix! Do you think this needs to be back ported to older releases?

That's a good question. I think it would be useful and it's a low risk change. The only caveat is that there was a big rewrite on the destroy code in 4.11, so 4.10 and earlier will most likely require manual cherry-picking. But I have no problem with doing that.

**Pull request merged**
