### PR TITLE
Transition to Terraform 0.12 for installer

### PR DESCRIPTION
**Pull request by abhinavdahiya**
Terraform community is getting ready for 0.12 release that introduces wide variety of improvements in the language
and fixes a lot of the subtle plan and apply bugs. see here [1] for official announcement

New platforms like Azure require that installer moves to 0.12 version of terraform as it provides the required `dynamic` blocks in HCL2 [2]. For example,
Azure `dns_srv` record requires use of `foreach` to create dynamic count of records for control plane [3]. `RHHI` platform owners have also requested 0.12 terraform version to
simplify their terraform templates. Therefore, moving the installer to 0.12-rc.1 sets us up to switch to final release of 0.12 which is very close [4].

**NOTE:** This PR is restricted to the minimum set of changes that are required for use to move to 0.12. All work to utilize the new hcl2 specification for current templates is out of scope for this and can be done as a follow-up.

**NOTE:** I have also left the terraform templates in the `upi` directory for vsphere and metal as is, as we can migrate them to 0.12 at a later stage. 

[1]: https://www.hashicorp.com/resources/introducing-terraform-0-12
[2]: https://www.terraform.io/upgrade-guides/0-12.html#attributes-vs-blocks
[3]: https://github.com/openshift/installer/pull/1454/files#diff-764adb23dcc0edbbebc09192eb233e9aR46
[4]: https://github.com/hashicorp/terraform/pulls?q=is%3Aopen+is%3Apr+milestone%3Av0.12.0

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
using this to get initial testing feedback.

**Comment by praveenkumar** [comment]
For past 3 run libvirt e2e failing because of timeout https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_installer/1739/pull-ci-openshift-installer-master-e2e-libvirt/454/artifacts/e2e-libvirt/installer/.openshift_install.log I am going to execute it one more time, is there anything change recently for 1 master and 1 worker ?

/test e2e-libvirt

**Comment by abhinavdahiya** [comment]
Hoping this was a flake [e2e-aws](https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_installer/1739/pull-ci-openshift-installer-master-e2e-aws/5834)

```
Failing tests:

[sig-storage] In-tree Volumes [Driver: nfs] [Testpattern: Inline-volume (ext4)] volumes should allow exec of files on the volume [Suite:openshift/conformance/parallel] [Suite:k8s]

Writing JUnit report to /tmp/artifacts/junit/junit_e2e_20190516-053734.xml
```

/retest

**Comment by praveenkumar** [comment]
libvirt succeed finally 👍

**Comment by abhinavdahiya** [comment]
🥳🥳

**Pull request merged**
