### PR TITLE
vendor/terraform-provider-vsphere: Verify DiskPostCloneOperation patch carry

### PR DESCRIPTION
**Pull request by mtnbikenc**
Verify https://github.com/openshift/terraform-provider-vsphere/pull/3

### CODE REVIEW

**Comment by mtnbikenc** [comment]
Just for verification
/hold

**Comment by mtnbikenc** [comment]
My git branch source was not based on the current branch of the openshift fork.  I'll need to fix that to resolve the verify-vendor test.  Essentially, I didn't have Joe's commit in my branch so verification failed.

**Comment by mtnbikenc** [comment]
Terraform succeeded, cluster install failed
/test e2e-vsphere

**Comment by mtnbikenc** [comment]
Looking again at the history for the e2e-vsphere job, it has not passed in a long time so I don't think it will really give us much validation.  We do see that terraform completes, but that doesn't necessarily confirm anything.

**Comment by wking** [comment]
4.5 backport for additional testing: #4049.

**Pull request closed without merging**
