### PR TITLE
[WIP] Add the Packet provider

### PR DESCRIPTION
**Pull request by displague**
_I'm drafting this PR early to facilitate conversation and to add context to any provider creation questions that come up in the process._

_I've included #1112 from @smarterclayton in this PR with the intention of addressing PR feedback fro #1112 while adding my own observations._

_I am happy to rebase and squash away the messy commits that will make their way into this PR along the way._

---

**Maintainers, it's not clear to me what todo items I should aim for here.  Feel free to edit this PR description to include appropriate bullets for a Platform integration**

This PR:
* [ ] Implements the enhancement described in https://github.com/openshift/enhancements/pull/436
* [ ] Establishes the Packet Platform configuration using common parameters from the [Packet API](https://www.packet.com/developers/api/).
* [ ] Depends on https://github.com/openshift/machine-api-operator/pull/753
* [ ] Depends on https://github.com/openshift/api/pull/784
* [ ] Depends on https://github.com/openshift/cluster-api-provider-packet/pull/1

### CODE REVIEW

**Comment by russellb** [comment]
Hi @displague !  It would be great to start by writing up an enhancement here: https://github.com/openshift/enhancement

I think a design document would be appropriate to discuss the various important decision points about how the packet platform will be integrated.  Those questions span more than just the installer repository.  There's a document we wrote that highlighted some of the areas we expect to discuss for packet.  Hopefully you have it?

Thanks!

**Comment by displague** [comment]
Hi @russellb! I have received a few documents about this and we broadly have approaches in mind for the expectations.

I'd be happy to start by opening an enhancements issue, but I don't appear to have access to that repository (404).

**Comment by russellb** [comment]
> Hi @russellb! I have received a few documents about this and we broadly have approaches in mind for the expectations.
> 
> I'd be happy to start by opening an enhancements issue, but I don't appear to have access to that repository (404).

sorry, I had a typo in the repo name.  Give it another try.

**Comment by displague** [comment]
@russellb I see it now (typo).  What makes the most sense for this?

A single document here:
https://github.com/openshift/enhancements/tree/master/enhancements/installer

This is what I generally see for providers.  `BareMetal` documents appear in a few other locations, but I'm not sure if I will need to explore additional enhancement areas outside of the provider scope.

**Comment by russellb** [comment]
> @russellb I see it now (typo). What makes the most sense for this?
> 
> A single document here:
> https://github.com/openshift/enhancements/tree/master/enhancements/installer
> 
> This is what I generally see for providers. `BareMetal` documents appear in a few other locations, but I'm not sure if I will need to explore additional enhancement areas outside of the provider scope.

This repo didn't always exist, so there may not be a perfect example to follow.  I'd create a document just in the root `enhancements` directory since it applies to more than a single category.  For example, it probably touches on things related to `installer, `network`, `machine-config`, `machine-api`, `rhcos`,  and `storage`.  Don't worry about getting it perfect.  I'm just hoping we can touch on all the important design points before you have to write all of the code.

**Comment by displague** [comment]
Moving to https://github.com/openshift/installer/pull/4472

**Pull request closed without merging**
