### PR TITLE
pkg/asset: Do not generate Files() slices with nil entries

### LINKED ISSUE #1547: invalid memory address or nil pointer dereference running destroy cluster
```
$ ./bin/openshift-install version
./bin/openshift-install ee5d518c27c00d46a411725fd6e29e3f6ce7608a
built from commit ee5d518c27c00d46a411725fd6e29e3f6ce7608a
release image registry.svc.ci.openshift.org/openshift/origin-release:v4.0
```

```
$ ./bin/openshift-install destroy cluster --dir=cluster
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xf909e2]

goroutine 1 [running]:
github.com/openshift/installer/pkg/asset.DeleteAssetFromDisk(0x5dd8cc0, 0xaaab7a0, 0x7ffed47e1678, 0x7, 0xaaab7a0, 0xc00083b201)
	/home/cdaley/go/src/github.com/openshift/installer/pkg/asset/asset.go:67 +0x182
github.com/openshift/installer/pkg/asset/store.(*storeImpl).Destroy(0xc00083b230, 0x5dbb4c0, 0xaaab7a0, 0x5dbb4c0, 0xaaab7a0)
	/home/cdaley/go/src/github.com/openshift/installer/pkg/asset/store/store.go:103 +0x400
main.runDestroyCmd(0x7ffed47e1678, 0x7, 0xc000a09f00, 0xc0008b3bc8)
	/home/cdaley/go/src/github.com/openshift/installer/cmd/openshift-install/destroy.go:60 +0x180
main.newDestroyClusterCmd.func1(0xc0009b1180, 0xc0009a2a10, 0x0, 0x1)
	/home/cdaley/go/src/github.com/openshift/installer/cmd/openshift-install/destroy.go:38 +0x73
github.com/openshift/installer/vendor/github.com/spf13/cobra.(*Command).execute(0xc0009b1180, 0xc0009a29e0, 0x1, 0x1, 0xc0009b1180, 0xc0009a29e0)
	/home/cdaley/go/src/github.com/openshift/installer/vendor/github.com/spf13/cobra/command.go:766 +0x2cc
github.com/openshift/installer/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0009b0780, 0x8, 0x0, 0xc000a0e280)
	/home/cdaley/go/src/github.com/openshift/installer/vendor/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/openshift/installer/vendor/github.com/spf13/cobra.(*Command).Execute(0xc0009b0780, 0xc0008b3ee0, 0x1)
	/home/cdaley/go/src/github.com/openshift/installer/vendor/github.com/spf13/cobra/command.go:800 +0x2b
main.installerMain()
	/home/cdaley/go/src/github.com/openshift/installer/cmd/openshift-install/main.go:57 +0x14f
main.main()
	/home/cdaley/go/src/github.com/openshift/installer/cmd/openshift-install/main.go:40 +0x99
```

### PR DESCRIPTION
**Pull request by eparis**
Most asset Files() functions would return an empty list if they didn't have a
file. A couple would instead return a list of length 1 with a nil entry. This
would cause a panic in the file delete code:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x100c8b5]

goroutine 1 [running]:
github.com/openshift/installer/pkg/asset.DeleteAssetFromDisk(0x6dea6c0, 0xc0f8578, 0x7ffdb1fbb99c, 0x1b, 0xc0f8578, 0x5a13001)
	/home/eparis/go/src/github.com/openshift/installer/pkg/asset/asset.go:69 +0x185
github.com/openshift/installer/pkg/asset/store.(*storeImpl).Destroy(0xc000f9e540, 0x7f42d5057770, 0xc0f8578, 0x7f42d5057770, 0xc0f8578)
	/home/eparis/go/src/github.com/openshift/installer/pkg/asset/store/store.go:103 +0x3ee
main.runDestroyCmd(0x7ffdb1fbb99c, 0x1b, 0xc0003e5ec0, 0xc0009b9c60)
	/home/eparis/go/src/github.com/openshift/installer/cmd/openshift-install/destroy.go:60 +0x171
main.newDestroyClusterCmd.func1(0xc0003a3180, 0xc00066ab30, 0x0, 0x1)
	/home/eparis/go/src/github.com/openshift/installer/cmd/openshift-install/destroy.go:38 +0x77
github.com/openshift/installer/vendor/github.com/spf13/cobra.(*Command).execute(0xc0003a3180, 0xc00066ab00, 0x1, 0x1, 0xc0003a3180, 0xc00066ab00)
	/home/eparis/go/src/github.com/openshift/installer/vendor/github.com/spf13/cobra/command.go:766 +0x2ae
github.com/openshift/installer/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0003a2780, 0xc0009b9ee0, 0x1, 0x1)
	/home/eparis/go/src/github.com/openshift/installer/vendor/github.com/spf13/cobra/command.go:852 +0x2ec
github.com/openshift/installer/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/home/eparis/go/src/github.com/openshift/installer/vendor/github.com/spf13/cobra/command.go:800
main.installerMain()
	/home/eparis/go/src/github.com/openshift/installer/cmd/openshift-install/main.go:57 +0x1f3
main.main()
	/home/eparis/go/src/github.com/openshift/installer/cmd/openshift-install/main.go:40 +0x99
```

Fixes #1547.

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
IMO we should also make the calling site aware that Files returns a list of pointers that can be nil.. https://github.com/abhinavdahiya/installer/commit/16eaac2353fcbed3f432025d2262916c3f4df838

**Comment by staebler** [comment]
Can we replace the `File *asset.File` field with a `FileList []*asset.File` field instead?

Ultimately, the issue that we really need to address is that we read in assets blindly from json without any validation on what was read in.

**Comment by eparis** [comment]
We could do a FileList instead of a file, but that would make the `KubeadminPassword` struct kinda odd, to have a single password and hash, but a list of files.

I see this pattern used about 5 other places in `Files()` so at least this seems to have some precedent.

**Pull request merged**
