### PR TITLE
 Bug 1957700: None Platform - set Kubelet's node-ip param based on service net CIDR

### PR DESCRIPTION
**Pull request by yboaron**
This PR addressed issue similar to [1] for the None platform,
since API VIP isn't used for None platform, the UseIPv6ForNodeIP
parameter should be calculated based on the content of service CIDR.

[1] https://github.com/openshift/installer/pull/4756

### CODE REVIEW

**Comment by yboaron** [comment]
cc @celebdor

**Review by cybertron — CHANGES_REQUESTED** [review]
This doesn't match the behavior of the masters in UPI: https://github.com/openshift/machine-config-operator/blob/847e2216cc324cfc17904e6afa6a18a47c565674/pkg/operator/render.go#L156 and https://github.com/openshift/machine-config-operator/blob/ecb3c0e03652049b5c37d9f5d5678e9d6dc24301/templates/common/_base/units/nodeip-configuration.service.yaml#L25

The difference is that on the nodes it only forces ipv6 for single-stack deployments. For dual-stack it will still use ipv4 (which should be fine since both are available). I'm not sure whether it matters since in dual-stack either should work, but I think it would be safer to be consistent.

Also, need to fix the fmt failure.

**Comment by staebler** [comment]
> [](https://github.com/openshift/machine-config-operator/blob/ecb3c0e03652049b5c37d9f5d5678e9d6dc24301/templates/common/_base/units/nodeip-configuration.service.yaml#L25)
> 
> The difference is that on the nodes it only forces ipv6 for single-stack deployments. For dual-stack it will still use ipv4 (which should be fine since both are available). I'm not sure whether it matters since in dual-stack either should work, but I think it would be safer to be consistent.

Let's stay consistent with what is done in nodeip-configuration and only force ipv6 in single-stack.

**Comment by staebler** [comment]
Can you help me understand why we care about the service network for this? The errors in the bug are with connecting to the API server. The service network is not relevant to that. Why wouldn't we be looking at the machine network instead?

**Comment by cybertron** [comment]
/test e2e-vsphere-upi

I'm not entirely sure why we're using the service network for this, but it's what was used in MCO for determining whether kubelet should use ipv6.

**Comment by sadasu** [comment]
/close
Feel free to re-open it when needed.

**Pull request closed without merging**
