### PR TITLE
Updating golang version to fix gofmt issues

### PR DESCRIPTION
**Pull request by sadasu**
gofmt issues are preventing https://github.com/openshift/installer/pull/6447, https://github.com/openshift/installer/pull/6448 and https://github.com/openshift/installer/pull/6449 from merging.

Fixing gofmt issues arising from upgrading to golang 1.19

### CODE REVIEW

**Review by r4f4 — COMMENTED** [review]
/lgtm
It looks like all the formatting changes are happening in comments.

**Comment by sadasu** [comment]
/skip
gofmt only made changes to comments

**Pull request merged**
