### PR TITLE
CORS-3250: images/altinfra: add etcd/kas binaries from containers

### PR DESCRIPTION
**Pull request by r4f4**
When building the altinfra image for inclusion in the release payload, we cannot download any binaries as it is currently done for etcd/kas. Instead let's copy those binaries from their existing container images.

### CODE REVIEW

**Comment by r4f4** [comment]
Depends on https://github.com/openshift/installer/pull/8196

**Comment by r4f4** [comment]
With this we'll only support native installs, that is, it won't be possible yet to deploy an arm64 cluster from an amd64 one.
Cross-arch installs are currently blocked by https://github.com/openshift-eng/ocp-build-data/pull/4644

**Comment by r4f4** [comment]
In the build log for the `installer-altinfra` image:
```
2024-04-24T11:48:00.600210991Z [3/4] STEP 7/12: COPY --from=etcd /usr/bin/etcd /usr/bin/etcd
2024-04-24T11:48:01.185792907Z [3/4] STEP 8/12: COPY --from=kas /usr/bin/kube-apiserver /usr/bin/kube-apiserver
2024-04-24T11:48:02.051976133Z [3/4] STEP 9/12: COPY . .
2024-04-24T11:48:39.297155275Z [3/4] STEP 10/12: RUN mkdir -p cluster-api/bin/$(go env GOOS)_$(go env GOHOSTARCH) && 	mv /usr/bin/etcd /usr/bin/kube-apiserver -t cluster-api/bin/$(go env GOOS)_$(go env GOHOSTARCH)/
[...]
2024-04-24T11:55:38.942848425Z + sync_envtest
2024-04-24T11:55:38.942910659Z + '[' -f /go/src/github.com/openshift/installer/cluster-api/bin/linux_amd64/kube-apiserver ']'
2024-04-24T11:55:38.943712021Z ++ /go/src/github.com/openshift/installer/cluster-api/bin/linux_amd64/kube-apiserver --version
2024-04-24T11:55:38.943931675Z ++ sed 's/Kubernetes //'
2024-04-24T11:55:39.059477607Z + version=v1.29.0-rc.1.3931+d9d45306df052a-dirty
2024-04-24T11:55:39.059524820Z + echo 'Found envtest binaries with version: v1.29.0-rc.1.3931+d9d45306df052a-dirty'
2024-04-24T11:55:39.059524820Z Found envtest binaries with version: v1.29.0-rc.1.3931+d9d45306df052a-dirty
2024-04-24T11:55:39.060029524Z + printf '%s\n%s' v1.28.0 v1.29.0-rc.1.3931+d9d45306df052a-dirty
2024-04-24T11:55:39.060111817Z + sort -V -C
2024-04-24T11:55:39.062207416Z + return
[...]
2024-04-24T11:55:51.671599292Z   adding: etcd (deflated 50%)
2024-04-24T11:55:52.551685950Z   adding: kube-apiserver (deflated 69%)
```
So the binaries are there. Let's see if they are working:

/test altinfra-e2e-aws-ovn

**Comment by r4f4** [comment]
Annnd cluster is up! https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_installer/8309/pull-ci-openshift-installer-master-altinfra-e2e-aws-ovn/1783105641041104896/artifacts/e2e-aws-ovn/ipi-install-install/artifacts/.openshift_install-1713964641.log

I'm going to send a fix to shellcheck soon.

**Comment by r4f4** [comment]
Actually let's wait to sync this with ART.

/hold

**Comment by patrickdillon** [comment]
/approve
/lgtm

for when we sync with ART. 

Along with this, I think we may want to always build CAPI providers https://github.com/openshift/installer/pull/8273?

**Comment by r4f4** [comment]
> Along with this, I think we may want to always build CAPI providers #8273?

I can set `OPENSHIFT_INSTALL_CLUSTER_API=y` in this PR to always build the capi providers in the altinfra image, but I think we should wait with 8273 because it's adding capi to the regular installer image and that one needs to move to rhel9 first which is blocked on https://github.com/openshift/installer/pull/8196

**Pull request merged**
