### PR TITLE
OCPBUGS-38070: Azure: Add master and worker VM IPs to both the backend pools API LoadBalancer

### PR DESCRIPTION
**Pull request by sadasu**

### CODE REVIEW

**Comment by JoelSpeed** [comment]
Will MAPI continue to add workers/masters to the backend pools when new workers are scaled up/down? For that, I think you need to set the internal load balancer right? Does CAPI support this?

**Comment by patrickdillon** [comment]
> Will MAPI continue to add workers/masters to the backend pools when new workers are scaled up/down? For that, I think you need to set the internal load balancer right? Does CAPI support this?

Despite the title of the PR, I don't think this PR changes anything related to the worker nodes. It just ensures that the control plane nodes are joined to both backend pools, which the compute nodes are joined to as well. 

https://github.com/openshift/installer/blob/d61300fbc2107236d85ecb7e60bd1d2fabc8ed51/pkg/asset/machines/azure/machines.go#L272

I don't see anything for the internal load balancer--so I'm not sure how this works in private clusters? Will check it out further.

**Pull request merged**
