### PR TITLE
go getter update for terraform & terraform providers

### PR DESCRIPTION
**Pull request by jhixson74**
This updates go-getter to v1.6.2 to address several vulnerabilities 

This can be cherry-picked into 4.13, 4.12, and 4.11.

### CODE REVIEW

**Comment by r4f4** [comment]
`e2e-azurestack`: passed the terraform stage, should be enough to validate the changes in this PR
`e2e-gcp-ovn`: passed the cluster install phase, enough for this PR.
`e2e-ibmcloud-ovn`: passed e2e tests, failed in post-test steps. Enough for this PR.
`e2e-libvirt`: failed when gathering test results in a known permafailing spot. Enough for this PR.

I'm waiting on `e2e-aws-ovn` and `e2e-azure-ovn` results before giving a LGTM.

**Review by r4f4 — COMMENTED** [review]
terraform phase was successfull in the relevant test jobs.

/lgtm

**Comment by r4f4** [comment]
/override ci/prow/e2e-azure-ovn
Only one e2e test failed, no need to run the entire job until it passes. The terraform change has been already tested by a successful install

**Comment by sadasu** [comment]
/retitle OCPBUGS-2211: go getter update for terraform & terraform providers

**Pull request merged**
