### PR TITLE
Bug 1821151: oVirt, add os_type to ovirt templates

### PR DESCRIPTION
**Pull request by Gal-Zaidman**
On RHV 4.3.9 we have change the ignition handling and API,
to recognize an ignition is passed to the VM we need to specify the os_type as RHCOS.
During the installation the installer creates a ovirt templates to be used by the nodes,
so we need to create the template with os_type = "rchos".

Signed-off-by: Gal Zaidman <gzaidman@redhat.com>

### CODE REVIEW

**Comment by rgolangh** [comment]
@Gal-Zaidman a nit - in the PR message you say "os_type=rchos"  fix that so it won't confuse future readers.

**Comment by patrickdillon** [comment]
@abhinavdahiya or @sdodson this needs approval, please

**Pull request merged**
