### PR TITLE
[release-4.14] OCPBUGS-22315: bootstrap: Skip gatewayd units on OKD agent-installer

### PR DESCRIPTION
**Pull request by LorbusChris**
Cherrypicks of
- https://github.com/openshift/installer/pull/7580
- https://github.com/openshift/installer/pull/7629

### CODE REVIEW

**Comment by LorbusChris** [comment]
@andfasano looks like this'll require a backport of https://github.com/openshift/installer/pull/7508

**Comment by vrutkovs** [comment]
```
 # github.com/openshift/installer/pkg/asset/ignition/bootstrap
pkg/asset/ignition/bootstrap/common.go:182:42: templateData.Invoker undefined (type *bootstrapTemplateData has no field or method Invoker) 
```

**Comment by LorbusChris** [comment]
/hold
checking whether the second commit is really required in https://github.com/openshift/installer/pull/7628

**Pull request closed without merging**
