### PR TITLE
gcp: collapse the firewall rules

### PR DESCRIPTION
**Pull request by jstuever**
Before this change, gcp used individual firewall rules for each
service/port used. This caused quota issues where multiple clusters were
provisoned to the same project.

This change collapses the firewall rules where approperiate to reduce
the number of firewall rules used.

### CODE REVIEW

**Comment by jstuever** [comment]
I do have a question if `internal_services_master` and `internal_services_master` can be folded into `internal_cluster`. In other words, do the services ports (30000-32767) need to maintain separation such that masters can only talk to masters and workers to workers, or can masters also talk to workers and workers to masters?

**Comment by abhinavdahiya** [comment]
/approve

let's wait for e2e-gcp to succeed

**Comment by jstuever** [comment]
/hold
Want to make sure e2e-gcp succeeds before this merges.

**Comment by patrickdillon** [comment]
Recreate nodes test in e2e-gap is broken. I created a bz today.

**Comment by abhinavdahiya** [comment]
The test failures are known bugs that we are fixing.

/hold cancel

/lgtm

**Pull request merged**
