### PR TITLE
[FCOS] data/data/bootstrap/vsphere: prepend DNS VIP via NM script instead of…

### PR DESCRIPTION
**Pull request by vrutkovs**
… dhclient

`dhclient` is not available in FCOS and removed in RHCOS 4.6. This would
ensure local resolver is used by bootstrap service when it attempts
to reach to API via `api-int` endpoint.

/cc @LorbusChris

### CODE REVIEW

**Comment by vrutkovs** [comment]
vSphere UPI is broken (see https://github.com/openshift/installer/pull/3759)

/override ci/prow/e2e-vsphere

**Comment by LorbusChris** [comment]
/approve

Before lgtm'ing, I'd like to verify this works by seeing the PR to master with these changes pass e2e (#3777)

**Pull request merged**
