### PR TITLE
Bug 1760616: pkg/destroy/aws: Print attachment information on net interface deletion failure

### PR DESCRIPTION
**Pull request by wking**
One of our CI runs hung up deleting a network interface in a tagged subnet.  I don't have logs for the leaking run, but we have a backstop job that runs `destroy cluster`, and it has [logs][1]:

    time="2019-10-10T22:51:55Z" level=debug msg="deleting EC2 network interface eni-0e1fb781cd0ab4302: InvalidParameterValue: Network interface 'eni-0e1fb781cd0ab4302' is currently in use.\n\tstatus code: 400, request id: 920952d6-55d0-4415-9506-ed311162c7ab" arn="arn:aws:ec2:us-east-1:460538899914:vpc/vpc-0b1ee898254467b2f"

Trying to delete locally:

```console
$ aws ec2 describe-network-interface-attribute --attribute attachment --network-interface-id eni-0e1fb781cd0ab4302
{
    "NetworkInterfaceId": "eni-0e1fb781cd0ab4302",
    "Attachment": {
        "Status": "attached",
        "DeviceIndex": 1,
        "DeleteOnTermination": false,
        "AttachmentId": "ela-attach-5d8c6a62",
        "InstanceOwnerId": "amazon-aws"
    }
}
$ aws --debug ec2 detach-network-interface --attachment-id ela-attach-5d8c6a62 --force 2>&1 | grep '<Response>'
<Response><Errors><Error><Code>OperationNotPermitted</Code><Message>You are not allowed to manage 'ela-attach' attachments.</Message></Error></Errors><RequestID>0f96afd4-dc0b-4996-baeb-ebdd9a9f484a</RequestID></Response>
```

I filed a ticket with AWS, and Yang L. responded [with][2]:

On Thu, Oct 10, 2019 at 3:57 PM Yang L. wrote:
> In your case, eni-0e1fb781cd0ab4302 is still existing under your ENI after you delete the NLB "net/ci-op-vyvqc0d6-d7573-hh2sl-ext/c6d4f881a5f60160". After I checked the internal logs, I found, you were deleting couple NLBs in a row and the backend deletion is still processing, because of this, you cannot see that NLB anymore under the ELB console, while this ENI still there as the full deletion process for the NLB has not been done.
>
> Please wait some more time there, the ENI should get deleted after our internal process get done. I will also keep checking the delete status for you, if it consistently stuck there, I will reach to our ELB team to take further actions.

But it's been 20+ hours since our nominally successful deletion request:

```csv
"eventtime","eventname","username","useragent","requestid","requestparameters","errorcode","errormessage"
"2019-10-10T08:47:42Z","DeleteLoadBalancer","origin-ci-robot-provision","aws-sdk-go/1.16.14 (go1.10.8; linux; amd64) OpenShift/4.x Installer/unreleased-master-1796-g90ccb37ac1f85ae811c50a29f9bb7e779c5045fb-dirty OpenShift/4.x Destroyer/unreleased-master-1796-g90ccb37ac1f85ae811c50a29f9bb7e779c5045fb-dirty","5eceed7d-7d0b-463e-a80f-754de543d668","{""loadBalancerArn"":""arn:aws:elasticloadbalancing:us-east-1:460538899914:loadbalancer/net/ci-op-vyvqc0d6-d7573-hh2sl-ext/c6d4f881a5f60160""}",,
```

With this pull request, the deletion logs will look like:

```
DEBUG Failed to delete type network_load_balancer network interface  arn="arn:aws:ec2:us-east-1:460538899914:vpc/vpc-0b1ee898254467b2f" description="ELB net/ci-op-vyvqc0d6-d7573-hh2sl-ext/c6d4f881a5f60160" id=vpc-0b1ee898254467b2f network interface=eni-0e1fb781cd0ab4302 owner=amazon-aws
DEBUG deleting EC2 network interface eni-0e1fb781cd0ab4302: InvalidParameterValue: Network interface 'eni-0e1fb781cd0ab4302' is currently in use.
  status code: 400, request id: c64ea4dc-4a02-47a8-9aec-247d535ff0e9  arn="arn:aws:ec2:us-east-1:460538899914:vpc/vpc-0b1ee898254467b2f"
```

That provides more guidance than `currently in use`, including the type of association (`network_load_balancer`) and the owner of the associated resource (`amazon-aws`), which will make it easier for folks who hit the error to look it up in Bugzilla and see that they may need to file an AWS ticket to get AWS to clear out a stuck, nominially deleted load balancer.

[1]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/periodic-ipi-deprovision/18084
[2]: https://bugzilla.redhat.com/show_bug.cgi?id=1760616#c0

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
I disagree with this approach in general. The original error is enough to provide user the action item. These get/list requests after error are going to stack up and set a precedent to run there per error troubleshooting requests that is not sustainable.

**Comment by wking** [comment]
> The original error is enough to provide user the action item.

Original error is not enough to distinguish between "user created but forgot to tag `owned` an instance in the VPC, and we're unable to remove that instances network interface until the instance itself is removed" and "AWS got hung up and isn't actually removing the load balancer like they said they would".  Only the latter requires you to file an AWS ticket to get resolution.

> These get/list requests after error are going to stack up and set a precedent to run there per error troubleshooting requests that is not sustainable.

I think we should handle this on a case-by-case basis.  For example, I think there's consensus around post-error debug helping in #2450.  For this PR, a fingerprint that let you search for and find rhbz#1760616 would have saved @hongkailiu and me around 30 minutes of head-scratching yesterday, and since it's just one network call to generate the fingerprint, I think it's an acceptable tradeoff.  But it's not definitive, so I don't think it's a slam dunk, and am fine with you closing this PR if you are still unconvinced ;).

**Comment by abhinavdahiya** [comment]
>  For example, I think there's consensus around post-error debug helping in #2450.

If you can move this to one-time-before exit (which is what 2450 is), i am fine with that. but in the current form where we do GET after each error is not sustainable.

> and since it's just one network call to generate the fingerprint,

But it's not though, we keep trying to delete the net-if and then immediately follow that with a get.

**Comment by wking** [comment]
> But it's not though, we keep trying to delete the net-if and then immediately follow that with a get.

Hmm.  How would you feel about me pre-flighting a GET (before the delete attempt) and erroring out if the associated owner was `amazon-aws`?  Then in this case we'd spend a query to save a delete (which helps with API throttling, we think).  The downside would be that we would also be spending a new GET for network-interface deletions which would succeed or fail for reasons besides `currently in use`.

**Comment by abhinavdahiya** [comment]
> > But it's not though, we keep trying to delete the net-if and then immediately follow that with a get.
> 
> Hmm. How would you feel about me pre-flighting a GET (before the delete attempt) and erroring out if the associated owner was `amazon-aws`? Then in this case we'd spend a query to save a delete (which helps with API throttling, we think). The downside would be that we would also be spending a new GET for network-interface deletions which would succeed or fail for reasons besides `currently in use`.

the GET before net-if is better. But what would be best is if we can spend some time to find out how many of out DELETE calls end up this owned-by-aws-error and then decide if GET before all interfaces is good/bad maybe.

**Comment by abhinavdahiya** [comment]
Closing due to this being open for a long time, Please feel free to reopen

/close

**Pull request closed without merging**
