### PR TITLE
CORS-2840: promote capi-installers to default feature set

### PR DESCRIPTION
**Pull request by patrickdillon**
Vendors API changes to enable capi-installs by default for aws, nutanix, openstack, & vsphere.

Removes Terraform providers for aws, nutanix, openstack & ovirt, which was still lingering around. vsphere has a separate PR.  Will remove the rest of the Terraform code in followup, but getting the providers out ASAP will help relieve pressure on ART/OSBS.

### CODE REVIEW

**Comment by patrickdillon** [comment]
Added commits to remove terraform providers. Vsphere will be handled separately in #8254

**Comment by patrickdillon** [comment]
/test okd-unit

weird failure for powervs dns?

**Comment by patrickdillon** [comment]
/retest

tests are slow/weird

**Comment by jhixson74** [comment]
LGTM. Straight forward. Waiting to see how the tests go ;-)

**Review by barbacbd — COMMENTED** [review]
/lgtm

**Pull request merged**
