### PR TITLE
OCPBUGS-34819: capi/aws: bump provider for fixes

### PR DESCRIPTION
**Pull request by r4f4**
This version brings in 2 important fixes:
 * Fix duplicated target group names
 * Fix reconciling load balancer in case of errors.

### CODE REVIEW

**Comment by r4f4** [comment]
/uncc @patrickdillon @sadasu 
Will CC again when ready to review.

**Comment by r4f4** [comment]
/retitle OCPBUGS-34819: capi/aws: bump provider for fixes

**Comment by r4f4** [comment]
/hold
We've identified another issue that needs fixing: https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/5015

**Comment by r4f4** [comment]
Update: capa fix merged upstream. Bumped capa version to include:
* the target group creation fix
* BYOIPv4 feature.

**Comment by r4f4** [comment]
I can see in the console that https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_installer/8545/pull-ci-openshift-installer-master-altinfra-e2e-aws-ovn/1801221037195530240 is past the bootstrap phase, so the target group creation issue is fixed.

**Comment by r4f4** [comment]
/hold cancel
Most aws jobs already passed the install phase.

**Comment by patrickdillon** [comment]
/refresh

this never works but hey

**Comment by r4f4** [comment]
For the record, these are the fixes and features included in this bump:
* https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4905
* https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4991
* https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/5004
* https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/5017
* https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4988
* https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4990

**Pull request merged**
