### PR TITLE
libvirt: Add Terraform variables for bootstrap node memory/CPU

### PR DESCRIPTION
**Pull request by sjug**
Similar to https://github.com/openshift/installer/pull/785, but for the bootstrap node.

### CODE REVIEW

**Comment by sjug** [comment]
Would be nice to have the `terraform fmt` also show `-diff`.

**Comment by sjug** [comment]
@wking It's not OOMing, more so I'm just trying to give it more resources to speed things up a bit.

**Comment by wking** [comment]
I'd expect we're network-limited by all the images we pull (especially if you aren't installing from a local registry).  Can you post some benchmarks of time until `bootstrap-complete` on you system before and after this commit?

**Comment by abhinavdahiya** [comment]
> I'd expect we're network-limited by all the images we pull (especially if you aren't installing from a local registry). Can you post some benchmarks of time until `bootstrap-complete` on you system before and after this commit?

+1 I don't think we should add knobs for bootstrap node. If we see that we need more memory lets just use that.

**Comment by abhinavdahiya** [comment]
@sjug I don't think we can accept this change of adding this tunable. But if you have some metrics that the current setup of bootstrap node is not adequate in terms of cpu / memory we can accept changing the defaults in this PR itself or close this one and open another with change to defaults. 
Whatever you think is more appropriate. :innocent:

**Comment by sjug** [comment]
The install time is not very consistent so it was a bit challenging to measure any improvement or lack of.

As we increase cores:
2 cores | 4 cores | 6 cores
-- | -- | --
0:04:59 | 0:03:52 | 0:03:45

As we increase memory:
2G | 4G | 8G
-- | -- | --
0:04:59 | 0:04:45 | 0:04:10

**Comment by wking** [comment]
> It looks like we should change the number of cores from two to four on the bootstrap domain.

Memory should have a reasonable cap, but won't CPUs just be "the more, the merrier"?  I don't know if bootstrap CPU allocation is something we want to try to fine-tune.

> Is that valid for hosts which have less than four cores?

Check by setting it to 256?  If that works, maybe we should make 256 the default ;).

**Comment by cgwalters** [comment]
> It looks like we should change the number of cores from two to four on the bootstrap domain. 

Sanest thing is to match the host.  On this topic, see https://pagure.io/standard-test-roles/pull-request/223

**Comment by wking** [comment]
> What about the worker nodes, btw?

Worker nodes are created by the [libvirt cluster-API provider][1], not by Terraform.  So adjust their MachineSet objects just like you'd manage other Kubernetes resources (and ping the libvirt-provider maintainers if something isn't working ;).

[1]: https://github.com/openshift/cluster-api-provider-libvirt

**Comment by mykaul** [comment]
@wking - how do I fix the 1st worker though? It's created and overloaded with 93% of its memory consumed! I can ping them of course.

**Comment by wking** [comment]
> how do I fix the 1st worker though...

We shouldn't distract here.  Spin off to a libvirt-provider or separate installer issue?  There may already be issues discussing this; I haven't checked

**Comment by sjug** [comment]
No longer have any variables for bootstrap node cpu or memory, closing.

**Pull request closed without merging**
