### PR TITLE
[release 4.4] Bug 1813004: etcd: remove etcd DNS entries because etcd no longer uses DNS

### PR DESCRIPTION
**Pull request by retroflexer**
This is a manual cherry pick of https://github.com/openshift/installer/pull/3265

Starting in 4.4, etcd does not rely on DNS entries.

### CODE REVIEW

**Comment by hexfusion** [comment]
/test e2e-azure
/test e2e-gcp

cc @abhinavdahiya 

We should probably run metal3 on 4.4?

**Comment by abhinavdahiya** [comment]
needs a BZ?

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/1623/

**Comment by hexfusion** [comment]
@abhinavdahiya added BZ

**Comment by wking** [comment]
/bugzilla refresh

The master/4.5 bug is now ON_QA

**Comment by wking** [comment]
Heh, I guess that's no longer good enough to unblock the 4.4 backport :p

**Comment by hexfusion** [comment]
cc @sdodson

**Pull request merged**
