### PR TITLE
[release-4.16] OCPBUGS-39196: Power VS: Add support for persistent Transit Gateways

### PR DESCRIPTION
**Pull request by AshwinHIBM**
Provide support for a user created TG when creating an OpenShift cluster.

### CODE REVIEW

**Comment by AshwinHIBM** [comment]
@r4f4 Would like your review on this.

**Comment by r4f4** [comment]
Is this a manual backport of https://github.com/openshift/installer/pull/8774? For this to merge, you need to fix the issue in master, then backport to 4.17 and then 4.16. l see the PR against master is still WIP...

**Comment by hamzy** [comment]
I was under the impression that Ashwin was working on the TF side of this.  So I would think that this PR would wait for my PR to merge.  And then modify the PowerVS TF code in master.  And then do the backports of two PRs.

**Pull request closed without merging**
