### PR TITLE
OCPBUGS-1695: OKD: Update to FCOS 36.20220906.3.2

### PR DESCRIPTION
**Pull request by vrutkovs**
Use latest available stable

### CODE REVIEW

**Comment by HuijingHei** [comment]
Check the same error logs about gcp-ovn and libvirt, I can download the rpm locally
```
[4/4] STEP 10/35: RUN yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm -y
Loaded plugins: ovl, product-id, search-disabled-repos, subscription-manager
This system is not receiving updates. You can use subscription-manager on the host to register and assign subscriptions.
Cannot open: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm. Skipping.
Error: Nothing to do
```

**Comment by vrutkovs** [comment]
>Check the same error logs about gcp-ovn and libvirt, I can download the rpm locally

Must be some CI quirk

/retest

**Comment by vrutkovs** [comment]
/close

This includes rpm-ostree 2022.13, which has a known issue - https://github.com/coreos/rpm-ostree/issues/4032

**Pull request closed without merging**
