### PR TITLE
OCPBUGS-32690: AWS: bump CCO for permission fix

### PR DESCRIPTION
**Pull request by r4f4**
CCO was requiring the `s3:HeadBucket` permission which doesn't actually exist [1][2]. The issue has been fixed in the lasted version.

[1] https://github.com/openshift/cloud-credential-operator/pull/691
[2] https://github.com/openshift/openshift-docs/pull/70926

### CODE REVIEW

**Comment by r4f4** [comment]
This is a manual backport of https://github.com/openshift/installer/pull/8233

/cc @jianping-shu

**Comment by jianping-shu** [comment]
Tested on CCO side successfully, see [comment](https://issues.redhat.com/browse/OCPBUGS-31924?focusedId=24587657&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-24587657)

**Comment by r4f4** [comment]
/assign @patrickdillon 
for the backport label

**Comment by r4f4** [comment]
/test unit
It's failing with a known issue of wrong nmstate version.

**Comment by r4f4** [comment]
The unit test needs https://github.com/openshift/installer/pull/8285

**Pull request merged**
