### PR TITLE
Download `yq` in upi installer containers

### PR DESCRIPTION
**Pull request by stbenjam**
[TRT-319](https://issues.redhat.com//browse/TRT-319)

Various CI steps use the upi-installer container for it's access to the
aws cli tools among other things.  However, most of those steps also
curl `yq` directly from GitHub.  We can save ourselves some headaches
when GitHub is down by just embedding the binary in the image already.

### CODE REVIEW

**Comment by jianlinliu** [comment]
> this also removes the python yq which I am not sure if it's used,

Someplace calling the python yq, e.g: in ci-operator/step-registry/ipi/conf/azurestack/rhcos/ipi-conf-azurestack-rhcos-commands.sh:
```
yq --arg url "${vhd_blob_url}" -i -y '.platform.azure.ClusterOSImage=$url' "${SHARED_DIR}/install-config.yaml"
```

**Comment by patrickdillon** [comment]
Python yq is used in azure(stack) upi jobs. Perhaps upi jobs on other platforms.

/lgtm cancel

**Comment by jianlinliu** [comment]
maybe we can save the yq to a different filename, just like what I did in https://github.com/openshift/installer/pull/6006

**Comment by jianlinliu** [comment]
> maybe we can save the yq to a different filename, just like what I did in #6006 ?

@stbenjam any thought on this proposal? I hit yq download issues for several times, so I also want this PR to fix that.

**Comment by stbenjam** [comment]
/hold cancel

I wrote go yq to a different path (/bin/yq-go).

**Comment by jianlinliu** [comment]
What else we can do to get this PR merged?

**Comment by jianlinliu** [comment]
I checked some failed e2e jobs, most of them are from e2e testing, not related with the upi installer, and robot hold the PR merge automatically, how do we move on?

**Comment by jianlinliu** [comment]
@stbenjam I just created a bug for this issue, can you help update the title to "Bug 2104337: Download yq in upi installer containers". Maybe that will let robot get know its importance to speed up the merge process.

**Comment by jianlinliu** [comment]
Recently we hit yq download issue again, how can move forward to merge the PR?

**Pull request merged**
