### PR TITLE
Bug 1823487: openstack: Pass the master server group by name

### PR DESCRIPTION
**Pull request by pierreprinetti**
Create the Control Plane server group in Terraform and pass the server
group by name, and not by UUID, in the machine spec.

/label platform/openstack
/cc mandre Fedosin iamemilio adduarte

Includes a CAPO bump to include ServerGroupName in the Machine spec: https://github.com/openshift/cluster-api-provider-openstack/pull/97

### CODE REVIEW

**Comment by pierreprinetti** [comment]
/assign @abhinavdahiya
for the CAPO bump

**Comment by abhinavdahiya** [comment]
> /assign @abhinavdahiya
> for the CAPO bump

/approve

**Pull request merged**
