### PR TITLE
DNM - This is a test PR

### PR DESCRIPTION
**Pull request by smarterclayton**
Verifying that we can gate merge based on the latest release payload (one built on the fly for the PR)

### CODE REVIEW

**Comment by wking** [comment]
/hold

^adding a label so this PR won't show up in my "[blocked on review][1]" list (which also includes "waiting on CI" ;).

[1]: https://github.com/openshift/installer/pulls?utf8=%E2%9C%93&q=is%3Aopen+-label%3Ado-not-merge%2Fwork-in-progress+-label%3Ado-not-merge%2Fhold+-label%3Aneeds-rebase+status%3Apending+

**Comment by crawford** [comment]
Go ahead and reopen this when you need to test again. I'm just trying to reduce the clutter.

/close

**Pull request closed without merging**
