### PR TITLE
cmd/openshift-install/waitfor: Rename bootstrap-complete -> control-plane-ready

### PR DESCRIPTION
**Pull request by wking**
There is concern that "bootstrap" will be a less-familiar idea for users, while "control-plane" will be more familiar.  This commit pivots the subcommand name and its short description to use the latter terminology.  We have decided to stick with `bootstrap-complete` internally, and we consider the `bootstrap-complete` event to be part of our internal API, so I've left all of the other code using bootstrap-complete and derivatives (e.g. I'm still using `newWaitForBootstrapCompleteCmd`).  This makes the rename as superficial as possible.

### CODE REVIEW

**Comment by wking** [comment]
CC @abhinavdahiya

**Comment by sdodson** [comment]
/approve
@derekwaynecarr Can you please confirm that `openshift-installer wait-for control-plane-ready` and `openshift-installer wait-for cluster-ready` provide the clarity you're looking for?

**Comment by wking** [comment]
Hey, look, [a useful CVO error][1] :)

```
level=fatal msg="failed to initialize the cluster: Could not update servicemonitor \"openshift-kube-apiserver-operator/kube-apiserver-operator\" (294 of 307): the server does not recognize this resource, check extension API servers: timed out waiting for the condition"
```

But there's no way that's related to this PR, so...

/retest

[1]: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_installer/1568/pull-ci-openshift-installer-master-e2e-aws/5060

**Comment by wking** [comment]
@smarterclayton, @eparis, @derekwaynecarr, and @crawford talked this over and now want to stick with `bootstrap-complete`, since this is mainly a gate for running `destroy bootstrap` in user-provided-infrastructure installs.  Also in this space, we my want to eventually make `wait-for bootstrap-complete` a level check and not an edge trigger, [rhbz#1698573][1].  But we're pretty clear that we no longer want this change.

/close

[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1698573

**Pull request closed without merging**
