### PR TITLE
Bug 1775388: rhcos: Bump to latest RHCOS

### PR DESCRIPTION
**Pull request by cgwalters**
This has encryption/FIPS fixes.

### CODE REVIEW

**Comment by cgwalters** [comment]
4.3 equivalent https://github.com/openshift/installer/pull/2777

**Comment by vrutkovs** [comment]
This build downgrades podman - `1.6.3-1.el8 → 1.4.2-5.module+el8.1.0+4240+893c1ab8`. This seems to be causing MCD to [desync](https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_installer/2776/pull-ci-openshift-installer-master-e2e-aws-upgrade/3658/artifacts/e2e-aws-upgrade/pods/openshift-machine-config-operator_machine-config-daemon-dzwtf_machine-config-daemon.log) during e2e-upgrade.

Is this change intended?

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/1363/

**Comment by cgwalters** [comment]
/hold
podman broke

**Comment by cgwalters** [comment]
- https://gitlab.cee.redhat.com/coreos/redhat-coreos/merge_requests/751
- https://gitlab.cee.redhat.com/coreos/redhat-coreos/merge_requests/745

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/1365/

**Comment by cgwalters** [comment]
It looks like we got pretty far in e2e-metal, but may need more RAM?
> panic: write /tmp/fixture-testdata-dir398484679/test/extended/testdata/builds/valuefrom/test-is.json: cannot allocate memory

**Comment by sdodson** [comment]
> It looks like we got pretty far in e2e-metal, but may need more RAM?

Hmm, perhaps. I'm happy enough that it's just installing. I can work on killing flakes outside of this PR, which is where I'd started looking at e2e-metal before it went from flakes to non-functional :-)

**Comment by sdodson** [comment]
/retitle Bug 1775388 : rhcos: Bump to latest RHCOS

**Comment by sdodson** [comment]
/bugzilla refresh
Waited 5 minutes.

**Comment by sdodson** [comment]
/retitle Bug 1775388: rhcos: Bump to latest RHCOS

**Comment by sdodson** [comment]
AWS Infra flake
/test e2e-aws-upgrade

**Comment by sdodson** [comment]
CI Infra flake
/test e2e-aws-upgrade

**Comment by abhinavdahiya** [comment]
This change are looking pretty good for metal and vsphere.

/test e2e-metal
/test e2e-vsphere
/test e2e-aws-upgrade

**Pull request merged**
