### PR TITLE
OCPBUGS-41938: PowerVS update capi ibmcloud c6bcd313

### PR DESCRIPTION
**Pull request by hamzy**
Update the installer to use commit c6bcd313bce0fc9866e41bb9e3487d9f61c628a3 of cluster-api-provider-ibmcloud
This includes a couple of necessary Transit Gateway fixes.

### CODE REVIEW

**Comment by hamzy** [comment]
This is the same failure for a test run of 
https://github.com/openshift/installer/pull/8774

The e2e-ibmcloud-ovn failure due to
: [sig-arch] events should not repeat pathologically for ns/openshift-cloud-controller-manager
Which requires this change to fix the liveness probe
https://github.com/openshift/cluster-cloud-controller-manager-operator/pull/360

**Comment by patrickdillon** [comment]
do you need to update crds https://github.com/openshift/installer/blob/master/data/data/cluster-api/ibmcloud-infrastructure-components.yaml?

**Comment by hamzy** [comment]
> do you need to update crds https://github.com/openshift/installer/blob/master/data/data/cluster-api/ibmcloud-infrastructure-components.yaml?

Yes.  :(  Updated the PR.

**Pull request merged**
