### PR TITLE
OCPBUGS-34220: Reintroduce CAPI-installer to 4.16

### PR DESCRIPTION
**Pull request by patrickdillon**
4.16 version of https://github.com/openshift/installer/pull/8427

- bumps AWS timeout due to [OCPBUGS-33874](https://issues.redhat.com//browse/OCPBUGS-33874)
- reverts https://github.com/openshift/installer/pull/8434

prow was stuck and would not run tests on #8448 so reopening here

### CODE REVIEW

**Comment by patrickdillon** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.16-e2e-aws-ovn 10

**Review by barbacbd — COMMENTED** [review]
/lgtm

**Comment by neisw** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.16-e2e-aws-ovn 10

**Comment by sdodson** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.16-e2e-aws-ovn 10

**Comment by patrickdillon** [comment]
> @sdodson: trigger 1 job(s) for the /payload-(with-prs|job|aggregate|job-with-prs|aggregate-with-prs) command
> 
>     * periodic-ci-openshift-release-master-ci-4.16-e2e-aws-ovn
> 
> 
> See details on https://pr-payload-tests.ci.openshift.org/runs/ci/4f415260-1886-11ef-8e31-4ed142f152fa-0

Looking at the summary here: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/logs/aggregator-periodic-ci-openshift-release-master-ci-4.16-e2e-aws-ovn/1793400908759961600/artifacts/release-analysis-prpqr-aggregator/openshift-release-analysis-prpqr-aggregator/artifacts/release-analysis-aggregator/aggregation-testrun-summary.html

- for some reason only 9 tests--not 10--were run
- all installs succeeded but e2es failed in 2 of the runs

**Comment by patrickdillon** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.16-e2e-aws-ovn 10

**Pull request merged**
