### PR TITLE
OCPBUGS-36327: bump capa for instance register fix

### PR DESCRIPTION
**Pull request by r4f4**
Bumping CAPA for the following fix:
* https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/5040

WIP until the fix is accepted and merged upstream.

### CODE REVIEW

**Comment by r4f4** [comment]
/uncc @rna-afk @rwsu 
Will CC back in once I remove the WIP.

**Comment by r4f4** [comment]
/retitle OCPBUGS-36327: bump capa for instance register fix

**Review by barbacbd — COMMENTED** [review]
/lgtm

**Pull request merged**
