### PR TITLE
OCPBUGS-21720: images/libvirt/Dockerfile.ci: Use centos stream instead centos:7

### PR DESCRIPTION
**Pull request by praveenkumar**

### CODE REVIEW

**Comment by praveenkumar** [comment]
/hold

till e2e-libvirt is green.

**Comment by barbacbd** [comment]
can you either add the tag to squash these commits or manually squash them ? thank you.

**Comment by praveenkumar** [comment]
> can you either add the tag to squash these commits or manually squash them ? thank you.

@barbacbd Updated the commit and now it only consist of centos stream change.

**Comment by praveenkumar** [comment]
@sadasu we can ignore `e2e-libvirt` test because it is not failed because of this PR but something on cluster api side. Also this is blocking now https://github.com/openshift/installer/pull/6252 so may be we need to cherry-pick it for `release-4.11`.

**Comment by sadasu** [comment]
> @sadasu we can ignore `e2e-libvirt` test because it is not failed because of this PR but something on cluster api side. Also this is blocking now #6252 so may be we need to cherry-pick it for `release-4.11`.

@praveenkumar are able to open a jira issue for this so that we can backport?

**Comment by sadasu** [comment]
@praveenkumar do you need help with creating the Jira card in OCPBUGS?

**Comment by sadasu** [comment]
It appears that the fix in 4.11 https://github.com/openshift/installer/pull/6252 merged but not in master?

**Comment by sadasu** [comment]
/retitle OCPBUGS-21720: images/libvirt/Dockerfile.ci: Use centos stream instead centos:7

**Review by barbacbd — COMMENTED** [review]
/approve

**Comment by barbacbd** [comment]
@praveenkumar  I don't think that the job error is caused by the image. Probably something that does need to be investigated in another PR.

**Pull request merged**
