### PR TITLE
bug 1924701: Fix FIP detach from Router

### PR DESCRIPTION
**Pull request by MaysaMacedo**
During a FIP less installation VMs that were not
created by the installer can get a FIP detached when
the cluster in being destroyed. This commit fixes the
issue by detaching only FIPs that were created by
installer or Kuryr during a FIP less installation.

### CODE REVIEW

**Comment by dulek** [comment]
/retest

OpenStack test failure is related to authentication failure which doesn't seem related.

**Comment by dulek** [comment]
@MaysaMacedo: Do I understand correctly that the point is that this will now remove all the FIPs required to remove the router and all the FIPs that are tagged? I have hard time trying to grasp this.

**Comment by MaysaMacedo** [comment]
> nd correctly that the point is that this will now remove all the FIPs required to remove the router and all the FIPs that are tagged? I have hard time trying to grasp this.

@dulek it detaches all FIPs that were created by Kuryr (meaning that are tagged https://github.com/openstack/kuryr-kubernetes/blob/master/kuryr_kubernetes/controller/drivers/public_ip.py#L133) when installing on byo with/without fipless where a custom router is present, otherwise the router clean up would hang.
When no byo/fipless is in place a router is created by the installer and the FIPs detachment should continue to be handled as it was before.

**Pull request merged**
