### PR TITLE
WIP: OCPBUGS-35898: capi/aws: bump provider for LB DNS fix

### PR DESCRIPTION
**Pull request by r4f4**
* Fix for DNS name resolution too early: https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/5033

### CODE REVIEW

**Comment by r4f4** [comment]
Marked as WIP until the upstream fix is accepted and merged.

**Comment by r4f4** [comment]
/uncc @rwsu @barbacbd 
Will cc again when this is ready for review.

**Comment by jianlinliu** [comment]
Run some pre-merge testing, the behavior get improved. 
```
06-24 10:56:19.215  level=debug msg=I0624 02:56:18.766373    1879 loadbalancer.go:128] "Created new network load balancer for apiserver" controller="awscluster" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="AWSCluster" AWSCluster="openshift-cluster-api-guests/jialiubug1-sf7kw" namespace="openshift-cluster-api-guests" name="jialiubug1-sf7kw" reconcileID="3b09c07c-1823-4dde-9107-5a4f7b411ff9" cluster="openshift-cluster-api-guests/jialiubug1-sf7kw" api-server-lb-name="jialiubug1-sf7kw-int"
06-24 10:56:19.216  level=debug msg=I0624 02:56:18.766396    1879 loadbalancer.go:134] "Waiting for network load balancer dns name to propagate" controller="awscluster" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="AWSCluster" AWSCluster="openshift-cluster-api-guests/jialiubug1-sf7kw" namespace="openshift-cluster-api-guests" name="jialiubug1-sf7kw" reconcileID="3b09c07c-1823-4dde-9107-5a4f7b411ff9" cluster="openshift-cluster-api-guests/jialiubug1-sf7kw" api-server-lb-name="jialiubug1-sf7kw-int"
...
06-24 10:58:19.052  level=debug msg=I0624 02:58:18.767030    1879 loadbalancer.go:134] "Waiting for network load balancer dns name to propagate" controller="awscluster" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="AWSCluster" AWSCluster="openshift-cluster-api-guests/jialiubug1-sf7kw" namespace="openshift-cluster-api-guests" name="jialiubug1-sf7kw" reconcileID="3b09c07c-1823-4dde-9107-5a4f7b411ff9" cluster="openshift-cluster-api-guests/jialiubug1-sf7kw" api-server-lb-name="jialiubug1-sf7kw-int"
06-24 10:58:19.616  level=debug msg=I0624 02:58:19.515376    1879 loadbalancer.go:1723] "creating target group" controller="awscluster" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="AWSCluster" AWSCluster="openshift-cluster-api-guests/jialiubug1-sf7kw" namespace="openshift-cluster-api-guests" name="jialiubug1-sf7kw" reconcileID="3b09c07c-1823-4dde-9107-5a4f7b411ff9" cluster="openshift-cluster-api-guests/jialiubug1-sf7kw" group=<
```

The LB dns get resolved in 120s, the installation move forwards.

**Comment by r4f4** [comment]
The issue has been fixed by https://github.com/openshift/installer/pull/8927

/close

**Pull request closed without merging**
