### PR TITLE
Bump RHCOS to 44.81.202001240222.0

### PR DESCRIPTION
**Pull request by sinnykumari**
Contains required machine-config-daemon package needed to
support realtime kernel through MachineConfig during
cluster install.

### CODE REVIEW

**Comment by sinnykumari** [comment]
Reference - https://github.com/openshift/machine-config-operator/commit/d27a05db94356917b5aa0ce4f3d2aed3c14c6265 , https://github.com/openshift/enhancements/pull/166

**Comment by Fedosin** [comment]
My bump was a little bit earlier https://github.com/openshift/installer/pull/2971, but I don't mind to close that PR if this one will be merged today

**Comment by Fedosin** [comment]
@sinnykumari they asked me to update the commit message:
https://github.com/openshift/installer/pull/2971#issuecomment-578000817
https://github.com/openshift/installer/pull/2971#issuecomment-578001593

Maybe you should do the same

**Comment by sinnykumari** [comment]
@Fedosin I missed your PR before creating mine, please update the one you already created and I will close mine.

Closing in favor of https://github.com/openshift/installer/pull/2971

**Pull request closed without merging**
