### PR TITLE
OCPBUGS-6727: Nutanix Hostname of the VM is not set when using DHCP network config

### PR DESCRIPTION
**Pull request by yanhua121**
Fix OCPBUGS-6727: Nutanix Hostname of the VM is not set when using DHCP network config

### CODE REVIEW

**Comment by rvanderp3** [comment]
@yanhua121 the tf-fmt test needs some attention.  My question is, while not necessarily related to this PR, how does the machine API handle this for the compute nodes?

**Comment by yanhua121** [comment]
> @yanhua121 the tf-fmt test needs some attention. My question is, while not necessarily related to this PR, how does the machine API handle this for the compute nodes?

@rvanderp3 Addressed the tf-fmt and the test now passed. 
The mapi-nutanix-controller change for the worker nodes is here: https://github.com/openshift/machine-api-provider-nutanix/pull/43/files#diff-335b80e6abb1a41cdc4ae4413b95cfd8740dadb1d00753e0e00e11e94f948dbb. Basically, the fix is to add the "/etc/hostname" file with content of the Machine name to the ignition config data, before passing it to create the worker node VM.

**Pull request merged**
