### PR TITLE
Bug 1813354: OpenStack: Fix the cacert trustbundle parser

### PR DESCRIPTION
**Pull request by pierreprinetti**
Fix a bug where a trailing empty line caused an error.

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
Hmm.. personally I feel like the consumer should be tolerating this...

/approve

**Comment by pierreprinetti** [comment]
>the consumer should be tolerating this

And indeed, the problem was in the loop that parsed the certificate chain. I have amended the patch, thanks.

/assign mandre

**Comment by pierreprinetti** [comment]
/retitle Bug 1813354: OpenStack: Fix the cacert trustbundle parser

**Comment by pierreprinetti** [comment]
/test e2e-openstack
:(

**Comment by mandre** [comment]
/test e2e-openstack
Aww come on e2e-openstack, now what??

**Comment by pierreprinetti** [comment]
@mandre PTAL

**Comment by mandre** [comment]
Looks good. Can we also add a test case for invalid certificate?

**Pull request merged**
