### PR TITLE
OWNERS: Fix 'aaronlevey' typo and promote abhinavdahiya and wking to approvers

### PR DESCRIPTION
**Pull request by wking**
I can't spell.  Typo is from 49779c3e (#71).

/assign @aaronlevy

### CODE REVIEW

**Comment by wking** [comment]
Ah, @aaronlevy can't actually approve this because of the typo :p.

/assign @yifan-gu

**Comment by wking** [comment]
I've stuffed in another commit to promote @abhinavdahiya and myself to approvers.  CC @openshift/installer.

**Comment by crawford** [comment]
Waiting on the e2e tests... :sob:

**Pull request merged**
