### PR TITLE
Mao deps update

### PR DESCRIPTION
**Pull request by staebler**
This commit updates various MAO dependencies.

This is a copy of https://github.com/openshift/installer/pull/4434 except with the bump of the controller-tools taken out. The newer version of controller-tools does not like the IPNet custom serialization when generating the install config CRD.

### CODE REVIEW

**Comment by staebler** [comment]
The GCP installation succeeded [1] but the e2e tests failed. The e2e-gcp job has been failing for a while now in the same way. It is not related to these changes.

[1] https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_installer/4450/pull-ci-openshift-installer-master-e2e-gcp/1334709733973561344

**Comment by stbenjam** [comment]
/test e2e-metal-ipi-ovn-ipv6

Not sure why oauth didn't come up on metal IPI. Control plane and workers are up and healthy.

```
OAuthVersionRouteAvailable: HTTP request to "https://oauth-openshift.apps.ostest.test.metalkube.org/healthz" failed: dial tcp [fd2e:6f44:5dd8:c956::4]:443: connect: connection refused
      OAuthRouteCheckEndpointAccessibleControllerAvailable: Get "https://oauth-openshift.apps.ostest.test.metalkube.org/healthz": dial tcp [fd2e:6f44:5dd8:c956::4]:443: connect: connection refused
```

**Comment by staebler** [comment]
I had to do some very ugly hacks to, in the very near term, get us past the cluster-api-provider-kubevirt repo still using the non-existent bitbucket.org/ww/goautoneg repo. I copied the files that the installer needs into a `vendor2` directory and added a replace in the go.mod file to pull from that directory rather than pulling from github.

**Comment by iamemilio** [comment]
Let me just merge the changes here: https://github.com/openshift/installer/pull/4346

I fixed all the merge conflicts that this creates

**Comment by staebler** [comment]
> Let me just merge the changes here: #4346
> 
> I fixed all the merge conflicts and bugs that this creates

/close

**Pull request closed without merging**
