### PR TITLE
cmd: Add timeout arg to `wait-for install-complete`

### PR DESCRIPTION
**Pull request by zeenix**
Let's allow users to specify how much further they want to wait for install completion.

### CODE REVIEW

**Comment by patrickdillon** [comment]
Based on ironcladlou/openshift4-libvirt-gcp#19 it seems that 30 minutes is too short but an hour is too long? Is there an advantage to doing this change rather than just using `timeout`?

**Comment by abhinavdahiya** [comment]
Can you provide a use case for when this timeout will be useful.

**Comment by cgwalters** [comment]
> Can you provide a use case for when this timeout will be useful.

People on slower Internet connections for one.

**Comment by abhinavdahiya** [comment]
> > Can you provide a use case for when this timeout will be useful.
> 
> People on slower Internet connections for one.

Cloud with slower internet??

**Comment by cgwalters** [comment]
> Cloud with slower internet??

No, people doing libvirt locally.

**Comment by patrickdillon** [comment]
> People on slower Internet connections for one.

Is that a use case where you need to increase the timeout (so you need more than an hour total)? Of course you could run wait-for again to get to an hour and a half. The initial implied use case was for decreasing the interval.

**Comment by abhinavdahiya** [comment]
prev discussion https://github.com/openshift/installer/pull/1830#issuecomment-499944478

1. If this is for libvirt IPI only, feel free to make a PR that justifies the need for timeout increase for a *specific* phase
2. The wait-for subcommands exit early if success happens, and these are easily rentrant, ie you can create a retry around them, and I think 30 mins is a good internal for the work it's waiting for.

/close

**Comment by zeenix** [comment]
> Can you provide a use case for when this timeout will be useful.

People use this command (please correct me if I'm wrong) *after* installer had already timedout and has waited at least 30m already so I don't believe 30m is a good default here and hence this PR so people can decide how much *additional* time they want to wait after 30m wasn't good enough.

**Pull request closed without merging**
