### PR TITLE
vendor: bump apimachinery to 1.11.3

### PR DESCRIPTION
**Pull request by squeed**
Also had to manually add vfsutil to testImports because glide didn't pick it up for some reason.

Commands run:

```
rm glide.lock
glide install --strip-vendor
glide-vc --use-lock-file --no-tests --only-code
```

### CODE REVIEW

**Comment by squeed** [comment]
I added this because our k8s version is so old that it's making it impossible to actually successfully use glide to pull in some new operator configuration repos. (e.g. the cluster-network-operator)

**Comment by abhinavdahiya** [comment]
@squeed i think this commit should be part of the PR that adds the configs for `cluster-network-operator` and `cluster-dns-operator`

cc @crawford

**Comment by squeed** [comment]
@abhinavdahiya yeah, I thought about that, but glide is so fragile, I personally dislike long-running branches. Up to you.

**Comment by squeed** [comment]
For additional context, this is because glide is unable to handle the case where an operator, using `dep`, depends on kubernetes 1.11. It just crashes with a file not found error.

Wanted to just merge this now so we can all make progress. Normally I put `vendor` updates in with the real PR.

**Pull request merged**
