### PR TITLE
CORS-3594: MOVE GCP CAPI to default feature set

### PR DESCRIPTION
**Pull request by barbacbd**
** Set the default gcp install to use CAPI not terraform. 
** Remove the terraform stages (not the terraform files) for gcp.

### CODE REVIEW

**Comment by patrickdillon** [comment]
the process for graduating a feature gate to the default feature set should be done by changing the feature in openshift/api and then vendoring that change into the installer:

https://github.com/openshift/api/blob/465787efd0d69f12beaad9410a3812d823e78c2b/features/features.go#L495

**Comment by r4f4** [comment]
> the process for graduating a feature gate to the default feature set should be done by changing the feature in openshift/api and then vendoring that change into the installer:

Agreed. Let's move the gate to the default feature set first, then we can go ahead with this PR and remove terraform + the need for the gate.

/hold

**Comment by barbacbd** [comment]
https://github.com/openshift/api/pull/1958

**Comment by 2uasimojo** [comment]
/payload-job-with-prs periodic-ci-openshift-hive-master-periodic-e2e-gcp-weekly https://github.com/openshift/api/pull/1958 https://github.com/openshift/installer/pull/8723

**Comment by 2uasimojo** [comment]
/payload-job-with-prs periodic-ci-openshift-hive-master-periodic-e2e-gcp-weekly openshift/api#1958

**Comment by patrickdillon** [comment]
verify vendor test is failing

**Pull request merged**
