### PR TITLE
Bug 1813012: remove resources and branches we don't need because maintenance is hard

### PR DESCRIPTION
**Pull request by hexfusion**
> These are causing maintenance headaches as they aren't used, but end up broken and stale. We will update our operator actually handle removal in running clusters.

Continued from https://github.com/openshift/installer/pull/3608

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
I think it's missing https://github.com/openshift/installer/pull/3060/files#diff-ce82c1d8a44f7dfc41dfc024085ccfeeL23

**Comment by abhinavdahiya** [comment]
also it seems like you need to remove
https://github.com/openshift/installer/blob/79dae77251693ad5eac0f3619efa983e589121a1/pkg/asset/manifests/operators.go#L178-L179
https://github.com/openshift/installer/blob/79dae77251693ad5eac0f3619efa983e589121a1/pkg/asset/manifests/operators.go#L169-L173

https://github.com/openshift/installer/blob/4d880b7a444e06ff6a9aaa70bdb7b172bbee2759/pkg/asset/manifests/template.go#L62-L63

**Comment by hexfusion** [comment]
@abhinavdahiya thanks, updated.

**Comment by hexfusion** [comment]
CI is flakey going to wait until Weds.

**Comment by hexfusion** [comment]
CI has recently thawed 
/test e2e-aws

**Comment by hexfusion** [comment]
/hold
This needs more thought

**Comment by hexfusion** [comment]
> E0618 21:15:18.805041       1 base_controller.go:180] "EtcdCertSignerController" controller failed to sync "key", err: infrastructures.config.openshit.io/cluster missing .status.etcdDiscoveryDomain

probably time we removed all need for this data from operator.

**Comment by hexfusion** [comment]
Looking at history these seem flakey but lets get another run of logs to review.

/test e2e-openstack
/test e2e-metal-ipi
/test e2e-azure
/test e2e-ovirt

**Comment by hexfusion** [comment]
/hold

@abhinavdahiya any input on the failures above. Is it possible that they use forked installers or some automated build proccess that we would need to adjust?

**Comment by hexfusion** [comment]
looks like azure is perma fail ...

**Comment by hexfusion** [comment]
azure..
```
           "apiVersion": "v1",
            "involvedObject": {
                "kind": "Deployment",
                "name": "etcd-operator",
                "namespace": "openshift-etcd-operator",
            },
            "kind": "Event",
            "message": "no image found for operand pod",
```

**Comment by retroflexer** [comment]
/test e2e-aws
--

**Comment by retroflexer** [comment]
/retest 
---

**Pull request closed without merging**
