### PR TITLE
Revert "pkg/destroy: data/aws: delete undiscoverable AWS objects"

### PR DESCRIPTION
**Pull request by wking**
This reverts commit 6ae7598063863c2f318b137e1b2354aef2514fc1, #1268.

That was a workaround to recover from openshift-dev clusters where an in-house pruner is removing instances but not their associated instance profiles.  Folks using the installer's destroy code won't need it, and while the risk of accidental name collision is low, I don't think it's worth taking that risk.  With this commit, folks using external reapers are responsible for ensuring that they reap instance profiles when they reap instances, and we get deletion logic that is easier to explain to folks mixing multiple clusters in the same account.

### CODE REVIEW

**Comment by jstuever** [comment]
This looks good to me... I defer to @eparis per @abhinavdahiya request above.

**Comment by eparis** [comment]
Since we now include part of the clusterid in the name the original problem this solved is less painful (the original problem was that it was impossible to install a cluster and extremely difficult to get out of the situation.) While I believe this patch is the wrong thing to do I won't hold it up.

I don't see a reason that the risk of leaving this code would be any different given vpc re-use (which was the reason I was told this was being considered.) We know for a fact that this code cleans up resources for 100's of people in the world. I, at least, know of no problem this code causes.

But if the team believes what's best for our users is to leak resources I don't have the fight in me to disagree.

**Comment by abhinavdahiya** [comment]
> I don't see a reason that the risk of leaving this code would be any different given vpc re-use (which was the reason I was told this was being considered.)

hmm, yeah looking at this more closely _i skipped the part of clusterid prefix_ , we are only deleting resources prefixed with clusterID, which is unique in shared-vpc case too.

So I think i agree with @eparis that this deletion is fine to continue to keep unless we get bugs or requests from users.

/approve cancel

**Comment by wking** [comment]
/close

I'm still not excited about explaining this in docs, but we can always re-open if/when some else prompts us to simplify.

**Pull request closed without merging**
