### PR TITLE
Bug 1988794: Backport BZ 1925203, add auto pin and hugepages support

### PR DESCRIPTION
**Pull request by Gal-Zaidman**
This is a manual backport of PR https://github.com/openshift/installer/pull/4873.
This is a feature we for 4.8 and the installer parts got delayed due to changes on oVirt.
A manual backport was needed due to changes in the go mod

### CODE REVIEW

**Comment by sdodson** [comment]
I've asked for confirmation in the bug as to who has approved this feature backport.

**Comment by Gal-Zaidman** [comment]
We deiced to not push for backporting since there are no customer requests for the feature on 4.8.
QE,PM and DEV are in the loop

**Pull request closed without merging**
