### PR TITLE
tectonic manifests

### PR DESCRIPTION
**Pull request by rajatchopra**
asset/manifests: tectonic manifests

1. tectonic manifest creation
2. move file structure to match current installer flow

@crawford @abhinavdahiya PTAL. Tested by hand.

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
> move file structure to match current installer flow

Not sure what you mean by that.

These files don't end up in `modules/*/resouces`; these files go into `manifests/` and `tectonic/` dirs.

Also can you leave the previous manifest package as is, and all tectonic manifests in `tectonic` asset.

**Comment by crawford** [comment]
Please break this into multiple commits if you are going to move stuff and add stuff in this PR.

**Comment by rajatchopra** [comment]
> > move file structure to match current installer flow
> 
> Not sure what you mean by that.
> 
> These files don't end up in `modules/*/resouces`; these files go into `manifests/` and `tectonic/` dirs.
> 
> Also can you leave the previous manifest package as is, and all tectonic manifests in `tectonic` asset.
> 

I was going to move the manifests to their respective operators as well. Just splitting into manifests and tectonic is enough then?


> Also take a look at this , [53b40ce](https://github.com/openshift/installer/commit/53b40ce1a80c36d799b959760711a786af062c6d), you should be naming Contents accordingly

**Comment by crawford** [comment]
> Just splitting into manifests and tectonic is enough then?

Yes, for now that is fine.

**Comment by rajatchopra** [comment]
> Also can you leave the previous manifest package as is, and all tectonic manifests in tectonic asset.

Done. Its a new asset. And is called from the top level target as a step.

**Comment by abhinavdahiya** [comment]
/lgtm
/hold
@crawford `/hold cancel` when you think its `/lgtm`

**Pull request merged**
