### PR TITLE
CORS-2898: capi/aws: configure IMDS

### PR DESCRIPTION
**Pull request by r4f4**

### CODE REVIEW

**Review by mtulio — COMMENTED** [review]
/lgtm

FWIW AWS is complaining about `optional` mode, I created a card to spike how we can improve this alert.  [SPLAT-1456](https://issues.redhat.com/browse/SPLAT-1456)

**Comment by r4f4** [comment]
Update: Change `GenerateMachines` so it can be used for both control plane and bootstrap. As a result, bootstrap should have the IMDS configure too.

**Comment by r4f4** [comment]
/hold 
Depends on https://github.com/openshift/installer/pull/8193

**Comment by r4f4** [comment]
Update: rebased on master.

**Pull request merged**
