### PR TITLE
OCPBUGS-44312: Power VS: Add new zones

### PR DESCRIPTION
**Pull request by AshwinHIBM**
- [x] syd05
- [x] us-east (i.e. wdc04)
- [x] us-south (i.e. dal13)
- [x] tor01

### CODE REVIEW

**Comment by AshwinHIBM** [comment]
/retitle OCPBUGS-44312: Power VS: Add new zones

**Comment by mjturek** [comment]
`us-east` is wdc, not dal

**Review by r4f4 — COMMENTED** [review]
/approve

**Pull request merged**
