### PR TITLE
data/data/manifests/bootkube/cvo-overrides: Move to stable-4.1

### PR DESCRIPTION
**Pull request by wking**
This is the channel that the beta4 drop and later will be in.

CC @abhinavdahiya, @smarterclayton, @steveeJ.  We may need to wait on the production Cincinnati to also switch.

/hold

### CODE REVIEW

**Comment by smarterclayton** [comment]
beta4 will have a 4.1.0 moniker (maybe rc0) and we will iterate from that.  CI will be moving to 4.1.0 shortly, 4.1.0 nightlies are being created.

**Comment by wking** [comment]
Cross-linking openshift/console#1419 in case I need to find that code later ;).

**Comment by steveeJ** [comment]
> We may need to wait on the production Cincinnati to also switch.

Cincinnati doesn't know any channel names, but it will
* only give you releases from the channel you requested (this might mean it gives you an empty graph if your channel has no releases)
* give you an error if you provide no channel parameter or the empty string

So AFAIK it is settled between these:
* installer default (taken care here)
* consoler UI (taken care in the PR you linked in the comment above mine)
* _channels_ labels on releases (taken care by @smarterclayton)

**Comment by wking** [comment]
We might end up wanting to go with prerelease-4.1 here until we have an image stable enough to grow a stable-4.1 track.  So one more reason to hold this while we hash that out.

**Comment by steveeJ** [comment]
gg

> We might end up wanting to go with prerelease-4.1 here until we have an image stable enough to grow a stable-4.1 track. So one more reason to hold this while we hash that out.

I second that. That would also require to add that channel to openshift/console#1419, right?

**Comment by steveeJ** [comment]
> That would also require to add that channel to [openshift/console#1419](https://github.com/openshift/console/pull/1419), right?

Nevermind, openshift/console#1419 already contains _pre-release-4.1_ as a channel.

**Comment by wking** [comment]
/hold cancel
/retest

With `stable-4.0` no longer appropriate (#1677), we might as well land this now, even though we don't have any stable images in `stable-4.1` yet.  @smarterclayton suggests `pre-release-4.1` for folks who want to silence the error, but it looks like that's currently empty too:

```console
 $ curl -sH 'Accept: application/json' 'https://api.openshift.com/api/upgrades_info/v1/graph?channel=pre-release-4.1' | jq .
{
  "nodes": [],
  "edges": []
}
```

Anyhow, no need to hold off on this PR any longer.

**Comment by wking** [comment]
[images][1]:

```
could not copy stable-initial imagestreamtag: Timeout: request did not complete within allowed duration
```

/retest

And now we do have the release in the prerelease channel (turns out we don't want a hyphen):

```console
$ curl -sH 'Accept: application/json' 'https://api.openshift.com/api/upgrades_info/v1/graph?channel=prerelease-4.1' | jq -S .
{
  "edges": [],
  "nodes": [
    {
      "metadata": {
        "com.openshift.upgrades.graph.release.channels": "prerelease-4.1",
        "com.openshift.upgrades.graph.release.manifestref": "sha256:345ec9351ecc1d78c16cf0853fe0ef2d9f48dd493da5fdffc18fa18f45707867",
        "description": "Beta 4"
      },
      "payload": "quay.io/openshift-release-dev/ocp-release@sha256:345ec9351ecc1d78c16cf0853fe0ef2d9f48dd493da5fdffc18fa18f45707867",
      "version": "4.1.0-rc.0"
    }
  ]
}
```

Still waiting for a `/lgtm` here...

[1]: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_installer/1599/pull-ci-openshift-installer-master-images/4068

**Pull request merged**
