### PR TITLE
[fcos] gcp-routes: update gcp routes

### PR DESCRIPTION
**Pull request by vrutkovs**
Sync gcp routes script with RHCOS 4.4.

TODO:
* [ ] Fetch the service and the route from MCD container in bootkube

Fixes https://github.com/openshift/okd/issues/121

### CODE REVIEW

**Comment by vrutkovs** [comment]
/cc @LorbusChris

I've ensured this fixes GCP bootstrap

**Comment by LorbusChris** [comment]
This essentially reverts the changes I made to fix shellcheck. Those must've been borked somewhere. If we're fine with shellcheck failing until the gcp-routes functionality is moved elsewhere, I'm fine with this.
/lgtm

**Comment by LorbusChris** [comment]
or did you want to fix that? :)
/hold

**Comment by vrutkovs** [comment]
Superceded by #3432

**Pull request closed without merging**
