### PR TITLE
OCPBUGS-33702: baremetal: bootstrap: bind icc to localhost

### PR DESCRIPTION
**Pull request by honza**
This fixes deployments with proxy enabled.

### CODE REVIEW

**Comment by dtantsur** [comment]
/approve

ICC is only accessed by Ironic, there is no point to expose it to everyone.

**Comment by tiraboschi** [comment]
`okd-images` is perma-failing due to unrelated issues building some of the images for OKD 
/override okd-images

**Comment by r4f4** [comment]
/override ci/prow/okd-images
Known to fail.

**Comment by dtantsur** [comment]
4.16 backport: https://github.com/openshift/installer/pull/8632

**Comment by r4f4** [comment]
There are issues with the `build04` cluster: https://issues.redhat.com/browse/OHSS-35619

**Pull request merged**
