### PR TITLE
OCPBUGS-16640: [release-4.13] Update azure cli version to 2.49.0

### PR DESCRIPTION
**Pull request by jinyunma**
Due to [security vulnerability](https://github.com/Azure/azure-cli/security/advisories/GHSA-47xc-9rr2-q7p4) affecting Azure CLI versions previous to 2.40.0, it is recommended to update azure cli to higher version to avoid this issue.

### CODE REVIEW

**Comment by r4f4** [comment]
/approve
But this won't do anything by itself. We also need https://github.com/openshift/release/pull/41040

**Review by pawanpinjarkar — COMMENTED** [review]
/lgtm

**Comment by r4f4** [comment]
/override ci/prow/e2e-azure-ovn-upi
Two e2e failures not related to the PR

**Comment by r4f4** [comment]
/override ci/prow/e2e-gcp-ovn-upi
The e2e test failures are not related to the az cli.

**Comment by r4f4** [comment]
/override ci/prow/e2e-azure-ovn-upi
Just 2 e2e failures not cause by the PR
/override ci/prow/e2e-aws-ovn-upi 
Not affected by the changes in this PR

**Pull request merged**
