### PR TITLE
bootkube: drop phase-2 for kube-controller-manager

### PR DESCRIPTION
**Pull request by sttts**
This depends on https://github.com/openshift/cluster-kube-apiserver-operator/pull/98 to be merged.

### CODE REVIEW

**Comment by sttts** [comment]
@abhinavdahiya approved as well?

I guess CI has quota issues again. So we won't see this green soon.

**Comment by abhinavdahiya** [comment]
/hold

[e2e-aws](https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_installer/580/pull-ci-openshift-installer-master-e2e-aws/1049)
```
Waiting for API at https://ci-op-jrlj8np4-1d3f3-api.origin-ci-int-aws.dev.rhcloud.com:6443 to respond ...
Waiting for API at https://ci-op-jrlj8np4-1d3f3-api.origin-ci-int-aws.dev.rhcloud.com:6443 to respond ...
Waiting for API at https://ci-op-jrlj8np4-1d3f3-api.origin-ci-int-aws.dev.rhcloud.com:6443 to respond ...
Waiting for API at https://ci-op-jrlj8np4-1d3f3-api.origin-ci-int-aws.dev.rhcloud.com:6443 to respond ...
Waiting for API at https://ci-op-jrlj8np4-1d3f3-api.origin-ci-int-aws.dev.rhcloud.com:6443 to respond ...
Waiting for API at https://ci-op-jrlj8np4-1d3f3-api.origin-ci-int-aws.dev.rhcloud.com:6443 to respond ...
Waiting for API at https://ci-op-jrlj8np4-1d3f3-api.origin-ci-int-aws.dev.rhcloud.com:6443 to respond ...
Waiting for API at https://ci-op-jrlj8np4-1d3f3-api.origin-ci-int-aws.dev.rhcloud.com:6443 to respond ...
Another process exited
2018/10/31 22:10:38 Container test in pod e2e-aws failed, exit code 1, reason Error
```

is not a known flake, and this branch has never passed. Can you make sure it works and paste local success for these changes before we retest again ?

**Comment by deads2k** [comment]
There was an operator problem.  It is now fixed.

/retest

**Comment by wking** [comment]
[e2e-aws][1] API never came up:

```
Waiting for API at https://ci-op-9rykxpmg-1d3f3-api.origin-ci-int-aws.dev.rhcloud.com:6443 to respond ...
Another process exited
```

[1]: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_installer/580/pull-ci-openshift-installer-master-e2e-aws/1076/build-log.txt

**Comment by sttts** [comment]
Waiting for https://github.com/openshift/cluster-kube-controller-manager-operator/pull/73 to merge which fixes the phase 3 controller manager by adding missing certs+keys. It was the reason that the ingress-operator service account did not get a token and hence the pod did not start up. Therefore, the e2e-aws – which tests ingress – failed.

**Comment by sttts** [comment]
/retest

Images should be rebuilt by now.

**Comment by deads2k** [comment]
simple rebase and now the other operators are working so it's green.

**Comment by deads2k** [comment]
yay!

**Pull request merged**
