### PR TITLE
Bug 1871795: bump RHCOS images to fix SSH authentication

### PR DESCRIPTION
**Pull request by bgilbert**

### CODE REVIEW

**Comment by cgwalters** [comment]
In prior bootimage bumps we've had a rough rule of requiring aws/gcp/azure, best effort debugging vsphere, metal and others.  You can usually take other ones as e2e-aws-workers-rhel7 as totally optional.

A good rule is to look at the latest periodics, e.g. [the last currently accepted release image for 4.6](https://openshift-release.apps.ci.l2s4.p1.openshiftapps.com/releasestream/4.6.0-0.nightly/release/4.6.0-0.nightly-2020-08-26-103641) had e2e-metal passing, so we know that is working.

**Comment by cgwalters** [comment]
The current e2e-aws failure looks like some sort of test infrastructure failure.

**Comment by cgwalters** [comment]
Hm, not clear to me what's going on here - e2e-aws for example seems good on other repositories.  I don't see anything in [recently merged openshift/release PRs](https://github.com/openshift/release/pulls?q=is%3Apr+is%3Aclosed+sort%3Aupdated-desc) that look relevant.

**Comment by cgwalters** [comment]
/retest
The failures here were a CI infrastructure or release issue that should be fixed.

**Comment by sdodson** [comment]
/approve
even though i'm perpetually slower than abhinav

**Comment by cgwalters** [comment]
Blah, azure is hitting rate limits.

**Comment by cgwalters** [comment]
It'd be good to get this to pass, even though it's *very* unlikely we somehow broke just Azure in this.
/test e2e-azure

**Comment by cgwalters** [comment]
Ugh looks like something fell over in...one of the centos7 repos?
```
No match for argument: pyOpenSSL
No match for argument: PyYAML 
```

**Comment by cgwalters** [comment]
Took a stab at fixing this in https://github.com/openshift/installer/pull/4106

**Pull request merged**
