### PR TITLE
Bump rhcos images for s390x

### PR DESCRIPTION
**Pull request by Prashanth684**
Bump RHCOS images for s390x with the latest pipeline image similar to #4021

### CODE REVIEW

**Comment by Prashanth684** [comment]
Diff:

```
{
    "sources": {
        "rhcos-4.6-s390x/46.82.202006241639-0": "https://releases-rhcos-art.cloud.privileged.psi.redhat.com/storage/releases/rhcos-4.6-s390x/46.82.202006241639-0/s390x/commitmeta.json",
        "rhcos-4.6-s390x/46.82.202008121739-0": "https://releases-rhcos-art.cloud.privileged.psi.redhat.com/storage/releases/rhcos-4.6-s390x/46.82.202008121739-0/s390x/commitmeta.json"
    },
    "diff": {
        "NetworkManager": {
            "rhcos-4.6-s390x/46.82.202006241639-0": "NetworkManager-1.22.8-4.el8.s390x",
            "rhcos-4.6-s390x/46.82.202008121739-0": "NetworkManager-1.22.8-6.el8_2.s390x"
        },
        "NetworkManager-libnm": {
            "rhcos-4.6-s390x/46.82.202006241639-0": "NetworkManager-libnm-1.22.8-4.el8.s390x",
            "rhcos-4.6-s390x/46.82.202008121739-0": "NetworkManager-libnm-1.22.8-6.el8_2.s390x"
        },
        "NetworkManager-ovs": {
            "rhcos-4.6-s390x/46.82.202006241639-0": "NetworkManager-ovs-1.22.8-4.el8.s390x",
            "rhcos-4.6-s390x/46.82.202008121739-0": "NetworkManager-ovs-1.22.8-6.el8_2.s390x"
        },
        "NetworkManager-team": {
            "rhcos-4.6-s390x/46.82.202006241639-0": "NetworkManager-team-1.22.8-4.el8.s390x",
            "rhcos-4.6-s390x/46.82.202008121739-0": "NetworkManager-team-1.22.8-6.el8_2.s390x"
        },
        "NetworkManager-tui": {
            "rhcos-4.6-s390x/46.82.202006241639-0": "NetworkManager-tui-1.22.8-4.el8.s390x",
            "rhcos-4.6-s390x/46.82.202008121739-0": "NetworkManager-tui-1.22.8-6.el8_2.s390x"
        },
        "afterburn": {
            "rhcos-4.6-s390x/46.82.202006241639-0": "afterburn-4.4.0-1.rhaos4.6.el8.s390x",
            "rhcos-4.6-s390x/46.82.202008121739-0": "afterburn-4.5.0-1.rhaos4.6.el8.s390x"
        },
        "bind-export-libs": {
            "rhcos-4.6-s390x/46.82.202006241639-0": "bind-export-libs-9.11.13-3.el8.s390x",
            "rhcos-4.6-s390x/46.82.202008121739-0": "bind-export-libs-9.11.13-5.el8_2.s390x"
        },
        "bind-libs": {
            "rhcos-4.6-s390x/46.82.202006241639-0": "bind-libs-9.11.13-3.el8.s390x",
            "rhcos-4.6-s390x/46.82.202008121739-0": "bind-libs-9.11.13-5.el8_2.s390x"
        },
        "bind-libs-lite": {
            "rhcos-4.6-s390x/46.82.202006241639-0": "bind-libs-lite-9.11.13-3.el8.s390x",
            "rhcos-4.6-s390x/46.82.202008121739-0": "bind-libs-lite-9.11.13-5.el8_2.s390x"
        },
        "bind-license": {
            "rhcos-4.6-s390x/46.82.202006241639-0": "bind-license-9.11.13-3.el8.noarch",
            "rhcos-4.6-s390x/46.82.202008121739-0": "bind-license-9.11.13-5.el8_2.noarch"
        },
        "bind-utils": {
            "rhcos-4.6-s390x/46.82.202006241639-0": "bind-utils-9.11.13-3.el8.s390x",
            "rhcos-4.6-s390x/46.82.202008121739-0": "bind-utils-9.11.13-5.el8_2.s390x"
        },
        "ca-certificates": {
            "rhcos-4.6-s390x/46.82.202006241639-0": "ca-certificates-2019.2.32-80.0.el8_1.noarch",
            "rhcos-4.6-s390x/46.82.202008121739-0": "ca-certificates-2020.2.41-80.0.el8_2.noarch"
        },
        "conmon": {
            "rhcos-4.6-s390x/46.82.202006241639-0": "conmon-2.0.17-1.rhaos4.5.el8.s390x",
            "rhcos-4.6-s390x/46.82.202008121739-0": "conmon-2.0.20-1.rhaos4.6.el8.s390x"
        },
        "console-login-helper-messages": {
            "rhcos-4.6-s390x/46.82.202006241639-0": "console-login-helper-messages-0.18-1.rhaos4.5.el8.noarch",
            "rhcos-4.6-s390x/46.82.202008121739-0": "console-login-helper-messages-0.18.2-1.rhaos4.6.el8.noarch"
        },
        "console-login-helper-messages-issuegen": {
            "rhcos-4.6-s390x/46.82.202006241639-0": "console-login-helper-messages-issuegen-0.18-1.rhaos4.5.el8.noarch",
            "rhcos-4.6-s390x/46.82.202008121739-0": "console-login-helper-messages-issuegen-0.18.2-1.rhaos4.6.el8.noarch"
        },
        "console-login-helper-messages-profile": {
            "rhcos-4.6-s390x/46.82.202006241639-0": "console-login-helper-messages-profile-0.18-1.rhaos4.5.el8.noarch",
            "rhcos-4.6-s390x/46.82.202008121739-0": "console-login-helper-messages-profile-0.18.2-1.rhaos4.6.el8.noarch"
        },
        "container-selinux": {
            "rhcos-4.6-s390x/46.82.202006241639-0": "container-selinux-2.132.0-1.rhaos4.5.el8.noarch",
            "rhcos-4.6-s390x/46.82.202008121739-0": "container-selinux-2.135.0-1.module+el8.2.1+6849+893e4f4a.noarch"
        },
        "containers-common": {
            "rhcos-4.6-s390x/46.82.202006241639-0": "containers-common-0.1.40-10.module+el8.2.0+5955+6cd70ceb.s390x",
            "rhcos-4.6-s390x/46.82.202008121739-0": "containers-common-1.1.1-2.rhaos4.6.el8.s390x"
        },
        "coreos-installer": {
            "rhcos-4.6-s390x/46.82.202006241639-0": "coreos-installer-0.2.0-4.rhaos4.6.el8.s390x",
            "rhcos-4.6-s390x/46.82.202008121739-0": "coreos-installer-0.5.0-1.rhaos4.6.el8.s390x"
        },
        "coreos-installer-systemd": {
            "rhcos-4.6-s390x/46.82.202006241639-0": "coreos-installer-systemd-0.2.0-4.rhaos4.6.el8.s390x",
            "rhcos-4.6-s390x/46.82.202008121739-0": "Not present"
        },
        "coreutils": {
            "rhcos-4.6-s390x/46.82.202006241639-0": "coreutils-8.30-6.el8_1.1.s390x",
            "rhcos-4.6-s390x/46.82.202008121739-0": "coreutils-8.30-7.el8_2.1.s390x"
        },
        "coreutils-common": {
            "rhcos-4.6-s390x/46.82.202006241639-0": "coreutils-common-8.30-6.el8_1.1.s390x",
            "rhcos-4.6-s390x/46.82.202008121739-0": "coreutils-common-8.30-7.el8_2.1.s390x"
        },
        "cri-o": {
            "rhcos-4.6-s390x/46.82.202006241639-0": "cri-o-1.19.0-28.dev.rhaos4.6.git55e534e.el8.s390x",
            "rhcos-4.6-s390x/46.82.202008121739-0": "cri-o-1.19.0-73.rhaos4.6.gitd00b217.el8.s390x"
        },
        "criu": {
            "rhcos-4.6-s390x/46.82.202006241639-0": "criu-3.12-9.module+el8.2.0+5030+403b061b.s390x",
            "rhcos-4.6-s390x/46.82.202008121739-0": "criu-3.14-2.module+el8.2.1+6750+e53a300c.s390x"
        },
        "dbus": {
            "rhcos-4.6-s390x/46.82.202006241639-0": "dbus-1.12.8-9.el8.s390x",
            "rhcos-4.6-s390x/46.82.202008121739-0": "dbus-1.12.8-10.el8_2.s390x"
        },
        "dbus-common": {
            "rhcos-4.6-s390x/46.82.202006241639-0": "dbus-common-1.12.8-9.el8.noarch",
            "rhcos-4.6-s390x/46.82.202008121739-0": "dbus-common-1.12.8-10.el8_2.noarch"
        },
        "dbus-daemon": {
            "rhcos-4.6-s390x/46.82.202006241639-0": "dbus-daemon-1.12.8-9.el8.s390x",
            "rhcos-4.6-s390x/46.82.202008121739-0": "dbus-daemon-1.12.8-10.el8_2.s390x"
        },
        "dbus-libs": {
            "rhcos-4.6-s390x/46.82.202006241639-0": "dbus-libs-1.12.8-9.el8.s390x",
            "rhcos-4.6-s390x/46.82.202008121739-0": "dbus-libs-1.12.8-10.el8_2.s390x"
        },
        "dbus-tools": {
            "rhcos-4.6-s390x/46.82.202006241639-0": "dbus-tools-1.12.8-9.el8.s390x",
            "rhcos-4.6-s390x/46.82.202008121739-0": "dbus-tools-1.12.8-10.el8_2.s390x"
        },
        "dnsmasq": {
            "rhcos-4.6-s390x/46.82.202006241639-0": "dnsmasq-2.79-11.el8.s390x",
            "rhcos-4.6-s390x/46.82.202008121739-0": "dnsmasq-2.79-11.el8_2.1.s390x"
        },
        "fuse-overlayfs": {
            "rhcos-4.6-s390x/46.82.202006241639-0": "fuse-overlayfs-0.7.2-5.module+el8.2.0+6060+9dbc027d.s390x",
            "rhcos-4.6-s390x/46.82.202008121739-0": "fuse-overlayfs-1.0.0-2.module+el8.2.1+6465+1a51e8b6.s390x"
        },
        "git-core": {
            "rhcos-4.6-s390x/46.82.202006241639-0": "git-core-2.18.2-2.el8_1.s390x",
            "rhcos-4.6-s390x/46.82.202008121739-0": "git-core-2.18.4-2.el8_2.s390x"
        },
        "glusterfs": {
            "rhcos-4.6-s390x/46.82.202006241639-0": "glusterfs-6.0-20.el8.s390x",
            "rhcos-4.6-s390x/46.82.202008121739-0": "glusterfs-6.0-37.el8.s390x"
        },
        "glusterfs-client-xlators": {
            "rhcos-4.6-s390x/46.82.202006241639-0": "glusterfs-client-xlators-6.0-20.el8.s390x",
            "rhcos-4.6-s390x/46.82.202008121739-0": "glusterfs-client-xlators-6.0-37.el8.s390x"
        },
        "glusterfs-fuse": {
            "rhcos-4.6-s390x/46.82.202006241639-0": "glusterfs-fuse-6.0-20.el8.s390x",
            "rhcos-4.6-s390x/46.82.202008121739-0": "glusterfs-fuse-6.0-37.el8.s390x"
        },
        "glusterfs-libs": {
            "rhcos-4.6-s390x/46.82.202006241639-0": "glusterfs-libs-6.0-20.el8.s390x",
            "rhcos-4.6-s390x/46.82.202008121739-0": "glusterfs-libs-6.0-37.el8.s390x"
        },
        "gnutls": {
            "rhcos-4.6-s390x/46.82.202006241639-0": "gnutls-3.6.8-9.el8.s390x",
            "rhcos-4.6-s390x/46.82.202008121739-0": "gnutls-3.6.8-11.el8_2.s390x"
        },
        "ignition": {
            "rhcos-4.6-s390x/46.82.202006241639-0": "ignition-0.35.1-14.rhaos4.6.gitb4d18ad.el8.s390x",
            "rhcos-4.6-s390x/46.82.202008121739-0": "ignition-2.6.0-2.rhaos4.6.git947598e.el8.s390x"
        },
        "initscripts": {
            "rhcos-4.6-s390x/46.82.202006241639-0": "initscripts-10.00.6-1.el8.s390x",
            "rhcos-4.6-s390x/46.82.202008121739-0": "initscripts-10.00.6-1.el8_2.1.s390x"
        },
        "iptables": {
            "rhcos-4.6-s390x/46.82.202006241639-0": "iptables-1.8.4-10.el8.s390x",
            "rhcos-4.6-s390x/46.82.202008121739-0": "iptables-1.8.4-10.el8_2.1.s390x"
        },
        "iptables-libs": {
            "rhcos-4.6-s390x/46.82.202006241639-0": "iptables-libs-1.8.4-10.el8.s390x",
            "rhcos-4.6-s390x/46.82.202008121739-0": "iptables-libs-1.8.4-10.el8_2.1.s390x"
        },
        "jq": {
            "rhcos-4.6-s390x/46.82.202006241639-0": "jq-1.5-12.el8.s390x",
            "rhcos-4.6-s390x/46.82.202008121739-0": "jq-1.6-2.el8.s390x"
        },
        "libmodulemd1": {
            "rhcos-4.6-s390x/46.82.202006241639-0": "libmodulemd1-1.8.16-0.2.8.2.1.s390x",
            "rhcos-4.6-s390x/46.82.202008121739-0": "Not present"
        },
        "libnghttp2": {
            "rhcos-4.6-s390x/46.82.202006241639-0": "libnghttp2-1.33.0-1.el8_0.1.s390x",
            "rhcos-4.6-s390x/46.82.202008121739-0": "libnghttp2-1.33.0-3.el8_2.1.s390x"
        },
        "machine-config-daemon": {
            "rhcos-4.6-s390x/46.82.202006241639-0": "machine-config-daemon-4.6.0-202006240615.p0.git.2604.224d66c.el8.s390x",
            "rhcos-4.6-s390x/46.82.202008121739-0": "Not present"
        },
        "network-scripts": {
            "rhcos-4.6-s390x/46.82.202006241639-0": "network-scripts-10.00.6-1.el8.s390x",
            "rhcos-4.6-s390x/46.82.202008121739-0": "network-scripts-10.00.6-1.el8_2.1.s390x"
        },
        "network-scripts-openvswitch2.13": {
            "rhcos-4.6-s390x/46.82.202006241639-0": "network-scripts-openvswitch2.13-2.13.0-25.el8fdp.1.s390x",
            "rhcos-4.6-s390x/46.82.202008121739-0": "network-scripts-openvswitch2.13-2.13.0-49.el8fdp.s390x"
        },
        "openshift-clients": {
            "rhcos-4.6-s390x/46.82.202006241639-0": "openshift-clients-4.6.0-202006240916.p0.git.3628.f3074ca.el8.s390x",
            "rhcos-4.6-s390x/46.82.202008121739-0": "openshift-clients-4.6.0-202008120152.p0.git.3705.c2ba791.el8.s390x"
        },
        "openshift-hyperkube": {
            "rhcos-4.6-s390x/46.82.202006241639-0": "openshift-hyperkube-4.6.0-202006240916.p0.git.0.9774336.el8.s390x",
            "rhcos-4.6-s390x/46.82.202008121739-0": "openshift-hyperkube-4.6.0-202008120512.p0.git.93417.47f7df4.el8.s390x"
        },
        "openvswitch2.13": {
            "rhcos-4.6-s390x/46.82.202006241639-0": "openvswitch2.13-2.13.0-25.el8fdp.1.s390x",
            "rhcos-4.6-s390x/46.82.202008121739-0": "openvswitch2.13-2.13.0-49.el8fdp.s390x"
        },
        "podman": {
            "rhcos-4.6-s390x/46.82.202006241639-0": "podman-1.9.3-1.rhaos4.6.el8.s390x",
            "rhcos-4.6-s390x/46.82.202008121739-0": "podman-1.9.3-2.rhaos4.6.el8.s390x"
        },
        "python3-bind": {
            "rhcos-4.6-s390x/46.82.202006241639-0": "python3-bind-9.11.13-3.el8.noarch",
            "rhcos-4.6-s390x/46.82.202008121739-0": "python3-bind-9.11.13-5.el8_2.noarch"
        },
        "rpm-ostree": {
            "rhcos-4.6-s390x/46.82.202006241639-0": "rpm-ostree-2020.2-2.el8.s390x",
            "rhcos-4.6-s390x/46.82.202008121739-0": "rpm-ostree-2020.4-1.el8.s390x"
        },
        "rpm-ostree-libs": {
            "rhcos-4.6-s390x/46.82.202006241639-0": "rpm-ostree-libs-2020.2-2.el8.s390x",
            "rhcos-4.6-s390x/46.82.202008121739-0": "rpm-ostree-libs-2020.4-1.el8.s390x"
        },
        "selinux-policy": {
            "rhcos-4.6-s390x/46.82.202006241639-0": "selinux-policy-3.14.3-41.el8.noarch",
            "rhcos-4.6-s390x/46.82.202008121739-0": "selinux-policy-3.14.3-41.el8_2.5.noarch"
        },
        "selinux-policy-targeted": {
            "rhcos-4.6-s390x/46.82.202006241639-0": "selinux-policy-targeted-3.14.3-41.el8.noarch",
            "rhcos-4.6-s390x/46.82.202008121739-0": "selinux-policy-targeted-3.14.3-41.el8_2.5.noarch"
        },
        "skopeo": {
            "rhcos-4.6-s390x/46.82.202006241639-0": "skopeo-0.1.40-10.module+el8.2.0+5955+6cd70ceb.s390x",
            "rhcos-4.6-s390x/46.82.202008121739-0": "skopeo-1.1.1-2.rhaos4.6.el8.s390x"
        },
        "slirp4netns": {
            "rhcos-4.6-s390x/46.82.202006241639-0": "slirp4netns-0.4.2-3.git21fdece.module+el8.2.0+5658+9a15711d.s390x",
            "rhcos-4.6-s390x/46.82.202008121739-0": "slirp4netns-1.0.1-1.module+el8.2.1+6595+03641d72.s390x"
        },
        "subscription-manager-rhsm-certificates": {
            "rhcos-4.6-s390x/46.82.202006241639-0": "subscription-manager-rhsm-certificates-1.26.16-1.el8.s390x",
            "rhcos-4.6-s390x/46.82.202008121739-0": "subscription-manager-rhsm-certificates-1.26.17-1.el8_2.s390x"
        },
        "systemd": {
            "rhcos-4.6-s390x/46.82.202006241639-0": "systemd-239-29.el8.s390x",
            "rhcos-4.6-s390x/46.82.202008121739-0": "systemd-239-31.el8_2.2.s390x"
        },
        "systemd-journal-remote": {
            "rhcos-4.6-s390x/46.82.202006241639-0": "systemd-journal-remote-239-29.el8.s390x",
            "rhcos-4.6-s390x/46.82.202008121739-0": "systemd-journal-remote-239-31.el8_2.2.s390x"
        },
        "systemd-libs": {
            "rhcos-4.6-s390x/46.82.202006241639-0": "systemd-libs-239-29.el8.s390x",
            "rhcos-4.6-s390x/46.82.202008121739-0": "systemd-libs-239-31.el8_2.2.s390x"
        },
        "systemd-pam": {
            "rhcos-4.6-s390x/46.82.202006241639-0": "systemd-pam-239-29.el8.s390x",
            "rhcos-4.6-s390x/46.82.202008121739-0": "systemd-pam-239-31.el8_2.2.s390x"
        },
        "systemd-udev": {
            "rhcos-4.6-s390x/46.82.202006241639-0": "systemd-udev-239-29.el8.s390x",
            "rhcos-4.6-s390x/46.82.202008121739-0": "systemd-udev-239-31.el8_2.2.s390x"
        },
        "toolbox": {
            "rhcos-4.6-s390x/46.82.202006241639-0": "toolbox-0.0.7-1.rhaos4.5.el8.noarch",
            "rhcos-4.6-s390x/46.82.202008121739-0": "toolbox-0.0.8-1.rhaos4.6.el8.noarch"
        },
        "tzdata": {
            "rhcos-4.6-s390x/46.82.202006241639-0": "tzdata-2019c-1.el8.noarch",
            "rhcos-4.6-s390x/46.82.202008121739-0": "tzdata-2020a-1.el8.noarch"
        },
        "unbound-libs": {
            "rhcos-4.6-s390x/46.82.202006241639-0": "unbound-libs-1.7.3-10.el8.s390x",
            "rhcos-4.6-s390x/46.82.202008121739-0": "unbound-libs-1.7.3-11.el8_2.s390x"
        },
        "bsdtar": {
            "rhcos-4.6-s390x/46.82.202006241639-0": "Not present",
            "rhcos-4.6-s390x/46.82.202008121739-0": "bsdtar-3.3.2-8.el8_1.s390x"
        },
        "coreos-installer-bootinfra": {
            "rhcos-4.6-s390x/46.82.202006241639-0": "Not present",
            "rhcos-4.6-s390x/46.82.202008121739-0": "coreos-installer-bootinfra-0.5.0-1.rhaos4.6.el8.s390x"
        },
        "libslirp": {
            "rhcos-4.6-s390x/46.82.202006241639-0": "Not present",
            "rhcos-4.6-s390x/46.82.202008121739-0": "libslirp-4.3.0-3.module+el8.2.1+6816+bedf4f91.s390x"
        }
    }
}
```

**Comment by sdodson** [comment]
@Prashanth684 I'm correct that nothing in CI actually deploys to these platforms? At least as a pre-submit on the installer repo? If such jobs exist can they be added to installer repo as optional jobs that only run when triggered so that you may test these changes via CI?

**Comment by Prashanth684** [comment]
> @Prashanth684 I'm correct that nothing in CI actually deploys to these platforms? At least as a pre-submit on the installer repo? If such jobs exist can they be added to installer repo as optional jobs that only run when triggered so that you may test these changes via CI?

@sdodson, yes currently nothing in the installer CI deploys on s390x/ppc64le. that sounds like a good idea. @jaypoulz in the future, would it be possible to run the s390x/ppc64le CI as pre-submit jobs for the installer that we can trigger ?

**Pull request merged**
