### PR TITLE
Bug 2094902: Simplify cross-compiling

### PR DESCRIPTION
**Pull request by yselkowitz**
- Always run go generate natively
- Add GOOS_GOARCH to all terraform build paths

### CODE REVIEW

**Comment by yselkowitz** [comment]
@jhixson74 thanks for the review.  Since we're now past feature freeze, should I file a BZ to get this in 4.11, or does this need to wait until 4.12?

**Comment by yselkowitz** [comment]
pending the previous question
/hold

**Comment by patrickdillon** [comment]
> @jhixson74 thanks for the review. Since we're now past feature freeze, should I file a BZ to get this in 4.11, or does this need to wait until 4.12?

I think we can put this in 4.11 with a BZ. We might be interested in backporting too.

**Pull request merged**
