### PR TITLE
No-Issue: Temporarily set none authenticator

### PR DESCRIPTION
**Pull request by pawanpinjarkar**

### CODE REVIEW

**Comment by zaneb** [comment]
An alternative approach (that avoids disabling auth altogether) would be to add something like https://github.com/zaneb/openshift-installer/commit/authz-compat to #9039 to allow both patches to merge, and then revert it.

**Comment by pawanpinjarkar** [comment]
> An alternative approach (that avoids disabling auth altogether) would be to add something like [zaneb@authz-compat](https://github.com/zaneb/openshift-installer/commit/authz-compat) to #9039 to allow both PRs to merge, and then revert that patch again.

Thank you @zaneb for the patch. I successfully tested [openshift/installer PR #9198](https://github.com/openshift/installer/pull/9198) together with the [assisted-service authorization PR #6784](https://github.com/openshift/assisted-service/pull/6784), and the cluster installed without issues.

With PR #9198, the changes we’ll need to revert are minimal. Since we’re using the none authenticator, the new authorization PR in assisted-service doesn’t require a value for USER_AUTH_TYPE; it defaults to empty. This prevents any authentication or authorization code from running, as these flows are temporarily disabled, allowing the cluster installation to complete successfully.

**Pull request merged**
