### PR TITLE
Add infra-image to MCO bootstrap

### PR DESCRIPTION
**Pull request by umohnani8**
Need to get the pod image for the MCO so that it can be set
in crio.conf.

Signed-off-by: Urvashi Mohnani <umohnani@redhat.com>

### CODE REVIEW

**Comment by umohnani8** [comment]
@runcom @mrunalp PTAL
@sjenning what should the infra image be? We couldn't find pod in an of the payloads.

**Comment by mrunalp** [comment]
@wking @abhinavdahiya ptal.

**Comment by rphillips** [comment]
I don't think this PR will pass until the MCO PR is merged to populate the pod field:

```
$ docker run   registry.svc.ci.openshift.org/openshift/origin-release:v4.0 image pod
F0222 18:00:48.439865       1 image.go:36] error: error: Unknown name requested, could not find pod in UpdatePayload
```

**Comment by cgwalters** [comment]
Dependent PR https://github.com/openshift/machine-config-operator/pull/494 merged.

/lgtm

**Comment by wking** [comment]
From [the `bootkube.service` logs][1]:

```
Feb 25 20:13:25 ip-10-0-5-161 bootkube.sh[4506]: Pulling release image...
Feb 25 20:13:36 ip-10-0-5-161 bootkube.sh[4506]: d23e828e6bb262f668b7d635910dc4d4651208cb2a50271687be4111c957c48a
Feb 25 20:13:42 ip-10-0-5-161 bootkube.sh[4506]: F0225 20:13:42.919053       1 image.go:36] error: error: Unknown name requested, could not find pod in UpdatePayload
```

Who's injecting the `pod` image?  And just in case it has come in since that test run...

/retest

[1]: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_installer/1292/pull-ci-openshift-installer-master-e2e-aws/4183/artifacts/e2e-aws/bootstrap/bootkube.service

**Comment by runcom** [comment]
The pod image will be injected by the MCO. AIUI this PR is required for the MCO pr which injects the image to land. And that error is expected (unless everything else fails cause of that)

**Comment by wking** [comment]
> And that error is expected (unless everything else fails cause of that)

Yeah, currently this failure is blocking further `bootkube.service` progress as shown in [the logs][1].  Is there a reason you can't inject the image yet?

[1]: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_installer/1292/pull-ci-openshift-installer-master-e2e-aws/4198/artifacts/e2e-aws/bootstrap/bootkube.service

**Comment by cgwalters** [comment]
OK yes sorry, I was wrong in [this comment](https://github.com/openshift/machine-config-operator/pull/471#issuecomment-467154348).  We do need to add it to `image-references` but ensure it's *not* substituted in the MCD yet.

**Comment by umohnani8** [comment]
@cgwalters so open a PR in MCO with just the image-references change?

**Comment by cgwalters** [comment]
> @cgwalters so open a PR in MCO with just the image-references change?

Right.  Sorry about this...it is *very* confusing I know.

**Comment by umohnani8** [comment]
Still seeing the same thing in `bootkube.service` even after https://github.com/openshift/machine-config-operator/pull/500 got in. @cgwalters anything else I am missing?
re-running again just to double check.
/retest

**Comment by umohnani8** [comment]
Still failing with
```
Feb 26 19:20:14 ip-10-0-6-84 bootkube.sh[4521]: Pulling release image...
Feb 26 19:20:26 ip-10-0-6-84 bootkube.sh[4521]: 10e7b38024340e2ebdbc10854fb3583c221340390cd1b4173c0ee39b9988339c
Feb 26 19:20:32 ip-10-0-6-84 bootkube.sh[4521]: F0226 19:20:32.450118       1 image.go:36] error: error: Unknown name requested, could not find pod in UpdatePayload
```

**Comment by umohnani8** [comment]
@runcom @cgwalters aws still failing. Seeing similar failure to what was happening in https://github.com/openshift/machine-config-operator/pull/471

**Comment by cgwalters** [comment]
>  @runcom @cgwalters aws still failing. Seeing similar failure to what was happening in [openshift/machine-config-operator#471](https://github.com/openshift/machine-config-operator/pull/471)

It's probably

https://github.com/openshift/machine-config-operator/pull/508

**Comment by cgwalters** [comment]
Can someone approve this?  It's definitely for 4.0.

**Comment by runcom** [comment]
oh gosh, realized this is not MCO repo (too fast)

**Comment by cgwalters** [comment]
And then the crazy dance should finally conclude with https://github.com/openshift/machine-config-operator/pull/518 after this merges.  Hopefully!

**Pull request merged**
