### PR TITLE
CORS-2764: AWS Shared VPC Backport [release-4.13]

### PR DESCRIPTION
**Pull request by patrickdillon**
4.13 Backport of the AWS Shared VPC with cross-account private hosted zone

### CODE REVIEW

**Comment by patrickdillon** [comment]
/retitle CORS-2764: AWS Shared VPC Backport [release-4.13]

**Review by barbacbd — COMMENTED** [review]
/lgtm

**Comment by patrickdillon** [comment]
/label backport-risk-assessed

QE has verified with pre-merge testing.

**Pull request merged**
