### PR TITLE
OSDOCS-6999: tested machine series 'C3', 'C2D'

### PR DESCRIPTION
**Pull request by jianli-wei**
We also tested machine series `C3` and `C2D` during 4.14, and machine series `Tau T2A` during 4.14 ARM testing. So add them to "Tested instance types for GCP".

### CODE REVIEW

**Comment by jianli-wei** [comment]
I believe the failure `ci/prow/e2e-gcp-ovn-shared-vpc` has nothing to do with my changes, thanks! 

/assign @patrickdillon

**Comment by kelbrown20** [comment]
Hello @jianli-wei! For the OCP documentation, we are using a separate `md` file for the ARM machine types, I created one in #7320. So the ARM instance types do not need to be in this `tested_instance_types.md` file

**Comment by jianli-wei** [comment]
> Hello @jianli-wei! For the OCP documentation, we are using a separate `md` file for the ARM machine types, I created one in #7320. So the ARM instance types do not need to be in this `tested_instance_types.md` file

Thank you @kelbrown20 ! I removed `Tau T2A` here.

**Pull request merged**
