### PR TITLE
verify-vendor: add go mod tidy

### PR DESCRIPTION
**Pull request by patrickdillon**
Running go mod tidy before vendoring ensures all necessary dependencies are included in go.mod.

https://github.com/openshift/installer/pull/5023/commits/e1646dd3a33b225b6289d590592cbffb1520a615 introduced dependencies that failed to vendor locally but passed our verify-vendor test. 

Including `go mod tidy` exposes these errors.

### CODE REVIEW

**Comment by patrickdillon** [comment]
/hold cancel
Enforcing `go mod tidy` makes sense to me

**Comment by jhixson74** [comment]
> /hold cancel
> Enforcing `go mod tidy` makes sense to me

I agree. Any idea why verify-vendor is failing?

**Comment by mtnbikenc** [comment]
Agreed.
/lgtm

**Comment by patrickdillon** [comment]
> I agree. Any idea why verify-vendor is failing?

Master is broken due to the changes in e1646dd. That PR passed the verify-vendor test, which prompted this PR.

So verify-vendor in this PR is correctly identifying the broken state of master.

I have a couple of PRs open to resolve the issue with master but these PRs are upstream. Hopefully we can merge them quickly.

**Pull request merged**
