### PR TITLE
Bug 1829409: Update vsphere machine api to beta

### PR DESCRIPTION
**Pull request by alexander-demichev**
This PR updates vsphere machine api to beta

### CODE REVIEW

**Comment by jcpowermac** [comment]
cc:
@patrickdillon 
@mtnbikenc

**Comment by enxebre** [comment]
@alexander-demichev can we please tag the relevant bugzilla for this?
/lgtm

**Comment by abhinavdahiya** [comment]
/approve

For the vendor bump

**Comment by abhinavdahiya** [comment]
/hold

To get review from vsphere approvers.. @jcpowermac @patrickdillon

**Comment by jcpowermac** [comment]
Looking at vSphere environment and CI logs
/lgtm

**Pull request merged**
