### PR TITLE
[gcp] Change bootstrap ignition storage bucket access

### PR DESCRIPTION
**Pull request by jcpowermac**
As requested from this RFE:

https://issues.redhat.com/browse/RFE-1516

`uniform_bucket_level_access` is unavailable in the currently vendored
terraform-provider-google. Using `bucket_policy_only` instead.

### CODE REVIEW

**Comment by sdodson** [comment]
/retitle Bug 1922451: Change bootstrap ignition storage bucket access

**Comment by sdodson** [comment]
/retitle [wip][gcp] Change bootstrap ignition storage bucket access

**Comment by staebler** [comment]
/lgtm
/approve
/label tide/merge-method-squash
/retitle [gcp] Change bootstrap ignition storage bucket access

**Comment by staebler** [comment]
These changes are specific to gcp clusters.

/override  ci/prow/e2e-aws-upgrade
/skip ci/prow/e2e-aws-workers-rhel7

**Pull request merged**
