### PR TITLE
Bug 1706689: asset/manifests: update infrastructure to set public apiserver url

### PR DESCRIPTION
**Pull request by abhinavdahiya**
PR [1] kept the `apiServerURL` field unchanged ie set to internal url for Kubernetes API so that
the consumers of the field can move away from it. With KAS-O [2] change merged, we can move forward

[1]: #1718
[2]: openshift/cluster-kube-apiserver-operator#465

Builds on #1718 and Requires https://github.com/openshift/cluster-kube-apiserver-operator/pull/465

### CODE REVIEW

**Comment by deads2k** [comment]
1730 merged

/retest

**Comment by wking** [comment]
#1730 landed.

/retest

**Comment by wking** [comment]
I'm not clear on why AWS is getting retested now.  We were green [here][1] and [here][2], and at least the e2e-aws job kicked off after the last master bump:

```console
$ git log --first-parent --format='%ad %h %d %s' --date=iso -2 origin/master
2019-05-08 19:56:40 +0200 c91435c84  (origin/release-4.2, origin/release-4.1, origin/master, origin/HEAD) Merge pull request #1730 from abhinavdahiya/upi_image_fix
2019-05-08 05:06:26 +0200 23aac5288  Merge pull request #1718 from abhinavdahiya/infra_api_changes
$ date --iso=m --utc --date '2019-05-08 19:56:40 +0200'
2019-05-08T17:56+0000
$ date --iso=m --utc --date "@$(curl -s https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_installer/1727/pull-ci-openshift-installer-master-e2e-aws/5738/started.json | jq -r .timestamp)"
2019-05-08T18:06+0000
```

Anyhow, with that UPI image the only bump, I'm ok force-merging this to unstick the beta release.

[1]: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_installer/1727/pull-ci-openshift-installer-master-e2e-aws/5738/
[2]: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_installer/1727/pull-ci-openshift-installer-master-e2e-aws-upgrade/298/

**Comment by wking** [comment]
Ah, maybe [a delayed Prow trigger][1]:

Screenshot from 2019-05-08 12-58-31


[1]: https://prow.svc.ci.openshift.org/tide-history?repo=openshift%2Finstaller&branch=master

**Pull request merged**
