### PR TITLE
upi/vsphere: multiple terraform updates

### PR DESCRIPTION
**Pull request by staebler**
* Add DNS records for the control plane and compute hostnames so that they are resolvable from within the cluster.
* Use IP addresses reserved from an IPAM server.

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
> * Add DNS records for the control plane and compute hostnames so that they are resolvable from within the cluster.
> * Put pull secret directly in VM ignition config.

The bootstrap ignition has pull secret in multiple locations, secret object, files etc. What about the kubeconfig? IMO users need to make sure the security of the endpoint serving them because ignition doesn't....

Why are we doing this?

> * Use static IP addresses.

**Comment by staebler** [comment]
> The bootstrap ignition has pull secret in multiple locations, secret object, files etc. What about the kubeconfig? IMO users need to make sure the security of the endpoint serving them because ignition doesn't....
> 
> Why are we doing this?

@abhinavdahiya How do we provide a URL that the bootstrap VM can access but is not accessible publicly? I don't see a way to provide credentials in the ignition file. The only thing that I see is a way to provide a cert to verify the ignition file pulled from the URL. In AWS, the ignition config is stored in S3 to make it secure. In OpenStack, the ignition config is stored in objectstorage. VSphere does not have that capability.

**Comment by staebler** [comment]
I'll take out the commit for dealing with the pull secret. There is clearly more work that needs to be done to address the issue of exposing the pull secret. The ignition config fed from the machine config operator also contains the pull secret and is publicly accessible.

**Comment by staebler** [comment]
a31370864...cc8f9f70a removed the changes dealing with the pull secret

**Comment by staebler** [comment]
cc8f9f70a..041b00f79 switches to reserving IP addresses from an IPAM server.

**Pull request merged**
