### PR TITLE
baremetal: Add example of rootDeviceHints usage

### PR DESCRIPTION
**Pull request by derekhiggins**
And remove example of hardwareProfile as it is deprecated.

### CODE REVIEW

**Comment by rlopez133** [comment]
Thanks for this @derekhiggins . When is hardwareprofile officially deprecated? Is it with 4.5? 4.6?

**Comment by stbenjam** [comment]
Is there any use for hardware profile going forward? Doesn't it also set some fields like root disk size?

**Comment by dhellmann** [comment]
> Is there any use for hardware profile going forward? Doesn't it also set some fields like root disk partition size?

All of those size values happen to be the same, right now. I think if we want different values we should add an API to allow them to be set explicitly, and we should drop the use of the hardware profile as it stands. We may want to adopt the metal3 hardware-classification-controller at some point to replace it.

Actually removing the profile field from the BareMetalHost will be a non-trivial amount of work, but it might be possible to drop it from the installer more easily.

**Comment by rlopez133** [comment]
> > Is there any use for hardware profile going forward? Doesn't it also set some fields like root disk partition size?
> 
> All of those size values happen to be the same, right now. I think if we want different values we should add an API to allow them to be set explicitly, and we should drop the use of the hardware profile as it stands. We may want to adopt the metal3 hardware-classification-controller at some point to replace it.
> 
> Actually removing the profile field from the BareMetalHost will be a non-trivial amount of work, but it might be possible to drop it from the installer more easily.

The sucky part about just dropping it means you have people testing IPI right now that your going to break if its just completely removed. Unless it just ignores it when it sees hardwareProfile as part of the install-config yaml? I just want to make sure that whatever is chosen also considers backward compatibility and give people a chance to adjust (my 2 cents).

**Comment by dhellmann** [comment]
> > > Is there any use for hardware profile going forward? Doesn't it also set some fields like root disk partition size?
> > 
> > 
> > All of those size values happen to be the same, right now. I think if we want different values we should add an API to allow them to be set explicitly, and we should drop the use of the hardware profile as it stands. We may want to adopt the metal3 hardware-classification-controller at some point to replace it.
> > Actually removing the profile field from the BareMetalHost will be a non-trivial amount of work, but it might be possible to drop it from the installer more easily.
> 
> The sucky part about just dropping it means you have people testing IPI right now that your going to break if its just completely removed. Unless it just ignores it when it sees hardwareProfile as part of the install-config yaml? I just want to make sure that whatever is chosen also considers backward compatibility and give people a chance to adjust (my 2 cents).

The BMH API ignores the profile for root device hints if something more explicit is given, but uses the profile otherwise. I think we're going to want to do the same for the installer for 3.6. We can consider dropping profiles in a later release when we have more time to work through the implications.

**Comment by stbenjam** [comment]
Generally I think the approach is prefer the newer field, if it's not set and the old one is, handle the conversion and log that the field is deprecated: https://github.com/openshift/installer/blob/master/pkg/types/conversion/installconfig.go 

There's not any examples of platforms doing it that I know of, just the one that changed how MachineCIDR was specified.

**Comment by derekhiggins** [comment]
> > > > Is there any use for hardware profile going forward? Doesn't it also set some fields like root disk partition size?
> > > 
> > > 
> > > All of those size values happen to be the same, right now. I think if we want different values we should add an API to allow them to be set explicitly, and we should drop the use of the hardware profile as it stands. We may want to adopt the metal3 hardware-classification-controller at some point to replace it.
> > > Actually removing the profile field from the BareMetalHost will be a non-trivial amount of work, but it might be possible to drop it from the installer more easily.
> > 
> > 
> > The sucky part about just dropping it means you have people testing IPI right now that your going to break if its just completely removed. Unless it just ignores it when it sees hardwareProfile as part of the install-config yaml? I just want to make sure that whatever is chosen also considers backward compatibility and give people a chance to adjust (my 2 cents).
> 
> The BMH API ignores the profile for root device hints if something more explicit is given, but uses the profile otherwise. I think we're going to want to do the same for the installer for 3.6. We can consider dropping profiles in a later release when we have more time to work through the implications.

The installer code does the same, if RootDeviceHints is set then use it, if not use the profile.

**Pull request merged**
