### PR TITLE
CORS-2797: images: move container images to RHEL 9

### PR DESCRIPTION
**Pull request by r4f4**
Use RHEL 9 as a base for all our container images.

### CODE REVIEW

**Comment by r4f4** [comment]
It seems the test is running from a rhel-8 builder?
```
openshift-install: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by openshift-install)
openshift-install: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by openshift-install) 
```

**Comment by r4f4** [comment]
Updates:
* I'd forgotten to update the last layer image (`base`) which was causing the rhel-9 binaries to run inside a rhel8 container
* Update the google cloud cli repo as in https://cloud.google.com/sdk/docs/install#rpm
* Explicitly install python3-pip
* Removed all python2 packages

/hold
Still need to figure out the `openstack` and `libvirt` images fixes.

**Comment by r4f4** [comment]
`e2e-gcp-ovn-upi`: seems to need python3-pyOpenSSL lib
```
CommandException: The signurl command requires the pyopenssl library (try pip install pyopenssl or easy_install pyopenssl)
```
`e2e-metal-*`: The installer is being run on some rhel8 along the way.

**Comment by r4f4** [comment]
/cc @cfergeau @jaypoulz 
For the libvirt image changes
/cc @pierreprinetti 
For the openstack image changes

**Comment by jaypoulz** [comment]
/lgtm
For the changes specific to the libvirt installer. As long as the CI/prow/images job is building, the multi-arch team should be clear. CC @tvardema

**Comment by pierreprinetti** [comment]
[`e2e-openstack-nfv-intel`](https://prow.ci.openshift.org/job-history/gs/test-platform-results/logs/periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.16-e2e-openstack-nfv-intel) and [`e2e-openstack-proxy`](https://prow.ci.openshift.org/job-history/gs/test-platform-results/logs/periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.16-e2e-openstack-proxy) are not providing a clean signal in 4.16 yet; their failure here resembles what we get in periodics (we're working on that). The other tests look good.

/test altinfra-e2e-openstack-capi-ovn

For OpenStack:
/approve
Thank you!

**Comment by cfergeau** [comment]
> /cc @cfergeau @jaypoulz For the libvirt image changes /cc 

/lgtm

**Comment by r4f4** [comment]
/cc @vrutkovs 
for the OKD jobs. 
I think we'll have to update/drop https://github.com/openshift/release/blob/master/ci-operator/config/openshift/installer/openshift-installer-master__okd-scos.yaml#L25 so the OKD-SCOS jobs use rhel9/centos9

**Comment by vrutkovs** [comment]
Not involved in OKD anymore
/uncc
/cc @LorbusChris

**Comment by derekhiggins** [comment]
IPI jobs failing because they are running on an EL8 host
Testing ipi jobs on EL9 here https://github.com/openshift/release/pull/50285

**Comment by r4f4** [comment]
This is for now blocked on https://github.com/openshift/installer/pull/8215

**Comment by r4f4** [comment]
The metal jobs will fail whenever a RHEL-8 VM is used until https://github.com/openshift/installer/pull/8161 merges and the tests steps are changed to use the `upi-installer` image.

**Comment by r4f4** [comment]
Update: rebased on top of master and updated fips instructions to say rhel9 instead of rhel8.

**Comment by r4f4** [comment]
Depends on https://github.com/openshift-metal3/dev-scripts/pull/1653. Will rebase and fix merge conflicts once 1653 merges.

**Comment by zaneb** [comment]
Baremetal tests don't seem to have picked up [the change](https://github.com/openshift/installer/blob/master/images/installer/Dockerfile.ci#L26) to dev-scripts:

```
 ++(common.sh:209): source(): export OPENSHIFT_INSTALLER=ocp/ostest/openshift-baremetal-install
```

/retest

**Comment by r4f4** [comment]
Update: added a commit to fix `gsutil` failure because of pyopenssl version.

**Comment by r4f4** [comment]
/hold
I want to check the e2e tests before this merges.

**Comment by zaneb** [comment]
agent-compact job failure is expected, because it has FIPS enabled. We need to merge https://github.com/openshift/assisted-service/pull/5792 as soon as possible before/after this to get it to work.
/override ci/prow/e2e-agent-compact-ipv4

**Comment by r4f4** [comment]
e2e looks good but I'm waiting on https://github.com/openshift-eng/ocp-build-data/pull/4709 since we'll have to merge both PRs in as much sync as we can.

**Comment by r4f4** [comment]
Updated: rebased after https://github.com/openshift/installer/pull/8309 merged.

**Comment by r4f4** [comment]
/override ci/prow/altinfra-openstack-capi-manifests
The job is permafailing due to reasons unrelated to this PR.

**Comment by r4f4** [comment]
`e2e-gcp-ovn-upi`: cluster installed. Few e2e failures.
`e2e-metal-ipi-ovn-swapped-hosts`: e2e failures.
`e2e-openstack-dualstack-upi`: e2e failures.
`e2e-vsphere-upi`: e2e failures.

We need this to merge soon so we can coordinate other PRs that need to merge in succession.
/override ci/prow/e2e-azure-ovn-upi ci/prow/e2e-gcp-ovn-upi ci/prow/e2e-vsphere-upi
/skip

**Comment by r4f4** [comment]
/override ci/prow/e2e-aws-ovn ci/prow/e2e-aws-ovn-upi ci/prow/e2e-gcp-ovn ci/prow/e2e-openstack-ovn
cluster installed

**Comment by r4f4** [comment]
/override ci/prow/e2e-vsphere-upi 
e2e failures.

**Pull request merged**
