### PR TITLE
CORS-2167: Remove UPI Metal TF references

### PR DESCRIPTION
**Pull request by barbacbd**
** Removed the Example and terraform data in upi/metal
** Updated the docs in docs/user/metal to reflect the changes above. Pointing the user towards the official docs.

### CODE REVIEW

**Comment by r4f4** [comment]
Is there a reason to keep the empty `metal` directory around?

**Comment by barbacbd** [comment]
There is not. I dont know why it remained I deleted it.

**Comment by barbacbd** [comment]
Git does not track directories that are empty. I think this is just a local copy from your system. I cannot delete something from git that git does not think exists at this point.

**Pull request merged**
