### PR TITLE
CORS-3601: Bump api, client-go, library-go for k8s 1.31

### PR DESCRIPTION
**Pull request by jcpowermac**
```
go get github.com/openshift/client-go@master
go get github.com/openshift/machine-api-operator@master
go get sigs.k8s.io/controller-runtime@v0.19.0

go mod tidy;go mod vendor;go mod verify
```

### CODE REVIEW

**Comment by jcpowermac** [comment]
If anyone needs api changes for 4.18 they will run into issues since pkgs have been updated

example
```
 vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/webhook.go:158:9: not enough arguments in call to fn
	have (interface{})
	want (context.Context, interface{})
# sigs.k8s.io/controller-runtime/pkg/internal/controller
vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:103:9: not enough arguments in call to fn
	have (interface{})
	want (context.Context, interface{}) 
```

**Comment by jcpowermac** [comment]
machine-api-operator has been recently changed as well
https://github.com/openshift/machine-api-operator/pull/1292

which additionally caused an issue when using updated commits of api, client-go and library-go

**Comment by r4f4** [comment]
Can you also update the k8s tools used when building capi in https://github.com/openshift/installer/blob/master/hack/build-cluster-api.sh#L8 ?

I think it's safer if we can keep them in sync.

**Comment by jcpowermac** [comment]
> Can you also update the k8s tools used when building capi in https://github.com/openshift/installer/blob/master/hack/build-cluster-api.sh#L8 ?
> 
> I think it's safer if we can keep them in sync.

Updated, I also tested the build local, didn't see any issues but all the tests will rerun anyways

**Comment by jcpowermac** [comment]
Took a look at the jira and noticed the note about informing hive 
fyi: @2uasimojo @jstuever @lleshchi

**Pull request merged**
