### PR TITLE
Update installer images to use golang 1.18

### PR DESCRIPTION
**Pull request by r4f4**

### CODE REVIEW

**Comment by jhixson74** [comment]
/lgtm

I assume this is waiting for https://github.com/openshift/installer/pull/6175 to merge?

**Comment by r4f4** [comment]
> /lgtm
> 
> I assume this is waiting for #6175 to merge?

I was actually waiting for https://github.com/openshift/release/pull/30871 to fix the UPI jobs

**Comment by sadasu** [comment]
/skip
e2e-azure-upi jobs are consistently failing for other reasons. No reason this PR should block on that.

**Pull request merged**
