### PR TITLE
WIP: rhcos: 4.3 but with kernel-4.18.0-147

### PR DESCRIPTION
**Pull request by miabbott**
Hack to test https://bugzilla.redhat.com/show_bug.cgi?id=1775878

DO NOT MERGE

### CODE REVIEW

**Comment by miabbott** [comment]
PLEASE DO NOT MERGE THIS

This is only a hack to test for https://bugzilla.redhat.com/show_bug.cgi?id=1775878

/hold

**Comment by wking** [comment]
7 `max(etcd_server_leader_changes_seen_total)` from [e2e-aws][1] :(.

[1]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_installer/2817/pull-ci-openshift-installer-release-4.3-e2e-aws/112

**Comment by miabbott** [comment]
Same result with older kernel; 7 `max(etcd_server_leader_changes_seen_total)`

**Comment by ashcrow** [comment]
> Same result with older kernel; 7 `max(etcd_server_leader_changes_seen_total)`

IE: passes CI, fails our test

**Pull request closed without merging**
