### PR TITLE
terraform/openstack: remove unused extra_tags

### PR DESCRIPTION
**Pull request by eb4x**
Since commit 63f7a03d8967d754a9e2110ccd6a1d5cf321515d the
extra_tags seem to go unused

### CODE REVIEW

**Review by mandre — COMMENTED** [review]
Thanks for the patch.

While you're at it, do you mind running `terraform fmt` on the openstack files as a separate commit, to keep the `tf-fmt` job happy? You can do it by running the following command:
```
terraform fmt -list -diff '-write=true' -recursive data/data/openstack/
```

**Comment by eb4x** [comment]
I don't quite understand what happened to the tf-fmt job. Last time it looked like it wanted indentation, now looks like it wants to undo the indentation? (fmt done with terraform 1.0.6)

**Comment by mandre** [comment]
> I don't quite understand what happened to the tf-fmt job. Last time it looked like it wanted indentation, now looks like it wants to undo the indentation? (fmt done with terraform 1.0.6)

According to [the logs](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_installer/5226/pull-ci-openshift-installer-master-tf-fmt/1439868914883366912/prowjob.json) the CI job is using quay.io/coreos/terraform-alpine:v0.12.0-rc1, that would explain the different formatting rules.

You should be able to make the tf-fmt happy _for real this time_ with:
```
  podman run --rm \                                                                                                                                    
    --volume "${PWD}:${PWD}:z" \
    --workdir "${PWD}" \
    quay.io/coreos/terraform-alpine:v0.12.0-rc1 \
    terraform fmt -list -diff '-write=true' -recursive data/data/openstack/
```

**Review by mandre — COMMENTED** [review]
/lgtm
/approve
/hold for CI to come back

**Pull request merged**
