### PR TITLE
OCPBUGS-4328:  images: updating images to be consistent with ART

### PR DESCRIPTION
**Pull request by r4f4**
Manual PR for https://github.com/openshift/installer/pull/6449 https://github.com/openshift/installer/pull/6448 https://github.com/openshift/installer/pull/6447 against master (4.13)

### CODE REVIEW

**Comment by r4f4** [comment]
/retitle OCPBUGS-4328:  images: updating images to be consistent with ART

**Comment by r4f4** [comment]
/override ci/prow/e2e-azure-ovn
Just some e2e failures, install succeeded

**Comment by derekhiggins** [comment]
proposing a revert here, images arn't building
https://github.com/openshift/installer/pull/6657

**Pull request merged**
