### PR TITLE
OCPBUGS-32519: Fix appliance CI jobs

### PR DESCRIPTION
**Pull request by zaneb**
The `agent-register-cluster` systemd service is disabled in the unconfigured ignition since #8093, which broke the appliance CI jobs.

### CODE REVIEW

**Comment by zaneb** [comment]
I'm not sure if this will work, but we'll see.

**Comment by zaneb** [comment]
I am attempting to take advantage of the pre-https://github.com/openshift/installer/commit/204c4ae561127220d296a52a575d2103ff18f90a implementation here, which [still exists](https://github.com/openshift/installer/blob/master/data/data/agent/files/usr/local/bin/load-config-iso.sh#L77-L87). This is preferable to a trivial fix in the ignition because we'll need it for [AGENT-838](https://issues.redhat.com/browse/AGENT-838).

However, despite the service now getting enabled as expected:

```
Apr 23 18:11:51 master-0 load-config-iso.sh[1400]: Service start-cluster-installation.service is disabled, enabling it
Apr 23 18:11:51 master-0 systemctl[1467]: Created symlink /etc/systemd/system/multi-user.target.wants/start-cluster-installation.service → /etc/systemd/system/start-cluster-installation.service.
Apr 23 18:11:51 master-0 systemctl[1467]: Created symlink /etc/systemd/system/multi-user.target.wants/agent-register-cluster.service → /etc/systemd/system/agent-register-cluster.service.
Apr 23 18:11:51 master-0 systemd[1]: Reloading.
```

`agent-register-cluster.service` never starts.

@rwsu did you have this working at one point? If so, what was the trick? Or did you make the switch in 204c4ae561127220d296a52a575d2103ff18f90a because it didn't work at all?

**Comment by rwsu** [comment]
agent-register-cluster.service never starts because it was removed as default enabled service in one of the day2 PRs: https://github.com/openshift/installer/commit/9716c1f6046e225647e67af616a211f47b995e90#diff-51bfa26054a56aa6871696bdc34e443b2ea944e5df9420c2e96db85595099ea2L302-L312

Since they were enabled by default before in the unconfigured ignition, I'm not sure what affect re-enabling the service in load-config-iso.sh was having. Perhaps that code block should be removed unless @bfournie remembers another reason for it.

The switch was having us not rely on enabling/disabling services but have the services be conditional on files being present on the file system. After /etc/assisted/rendezvous-host.env is copied from the config ISO, node-zero.service goes to success and writes out /etc/assisted/node0 which then triggers the other agent services to start.

**Comment by andfasano** [comment]
/lgtm

Thanks @zaneb  for the fix. I've also quickly verified the add-node workflow and it seems ok. @rwsu could you please have a run on the patch with the add-node workflow? Thanks

**Review by rwsu — APPROVED** [review]
I verified the appliance workflow is working again and the day-2 add nodes workflow is good with this patch.

/approve

**Pull request merged**
