### PR TITLE
Bug 2048028: [Alibaba] fix the deletion of private zone records

### PR DESCRIPTION
**Pull request by bd233**
If a user created cluster uses an existing privatezone, the private zone records should also be deleted when the cluster is destroyed.

### CODE REVIEW

**Comment by sadasu** [comment]
@bd233 are the e2e-alibaba failures related to this change?

**Comment by bd233** [comment]
> @bd233 are the e2e-alibaba failures related to this change?

@sadasu Do you know what this test e2e-alibaba is about, I got the same error on other PRs:

- [5668](https://github.com/openshift/installer/pull/5668)
- [5671](https://github.com/openshift/installer/pull/5671)
- [6179](https://github.com/openshift/installer/pull/6179)

**Comment by r4f4** [comment]
> > @bd233 are the e2e-alibaba failures related to this change?
> 
> @sadasu Do you know what this test e2e-alibaba is about, I got the same error on other PRs:
> 
>     * [5668](https://github.com/openshift/installer/pull/5668)
> 
>     * [5671](https://github.com/openshift/installer/pull/5671)
> 
>     * [6179](https://github.com/openshift/installer/pull/6179)

It's an IPI installation of OCP on Alibaba + e2e tests. But the issue is that we don't even reach the e2e tests because bootstrap fails to complete. The kubelet logs of the control plane nodes are full of 
```
Oct 19 01:45:05 ci-op-s9bt145y-920ba-92jsm-master-1 kubenswrapper[2056]: E1019 01:45:05.566052    2056 kubelet.go:2396] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: No CNI configuration file in /etc/kubernetes/cni/net.d/. Has your network provider started?"
```

**Pull request closed without merging**
