### PR TITLE
OCPBUGS-29765: Fills CIS or DNS CRN in Metadata, never both

### PR DESCRIPTION
**Pull request by miyamotoh**
Implementing the [same fix](#7987) as IBM Cloud proposes for PowerVS.

### CODE REVIEW

**Review by barbacbd — COMMENTED** [review]
I may be mistaken, but this doesn't seem to change setting CIS or DNS. The title of the PR makes me think that they are mutually exclusive. Only one should be set. The checks here only changed to ensure that the publish strategy was external.

**Comment by miyamotoh** [comment]
This is a little confusing situation where the (base)domain in private DNS actually conflicts with public DNS (ie. CIS), while the installer is deploying a private cluster. Because the base domain is found in the public DNS also, the code sets the CRN of CIS, though unnecessary and confusing, which later the destroy logic takes it as public cluster because public DNS CRN is found in Metadata. 

So, the fix implemented in IBM Cloud and also being proposed to copy to PowerVS here is to keep the "other" CRN as empty, by checking the publishing strategy and doing the lookup only for the matching DNS. Hope this helps clarify.

**Pull request merged**
