### PR TITLE
[OKD] pkg/tfvars/azure: cache FCOS image

### PR DESCRIPTION
**Pull request by jomeier**
Add FCOS decompression code.

### CODE REVIEW

**Comment by jomeier** [comment]
@LorbusChris @vrutkovs 
Once again. PR for Azure fix. 

Every few months it gets force pushed by someone.

**Comment by LorbusChris** [comment]
@jomeier my apologies that happened again. We'll make sure to keep an eye out for this from now on.
Could you please retitle the commit message to `UPSTREAM: <carry>: [OKD] pkg/tfvars/azure: cache FCOS image`
to make it easier to spot?

/retitle [OKD] pkg/tfvars/azure: cache FCOS image

**Comment by jomeier** [comment]
> Could you please retitle the commit message to `UPSTREAM: <carry>: [OKD] pkg/tfvars/azure: cache FCOS image`
> to make it easier to spot?
> 
> /retitle [OKD] pkg/tfvars/azure: cache FCOS image

Hi Christian, done.

I hope my changes were correct.

**Comment by LorbusChris** [comment]
Looks good, thanks!
/ok-to-test

**Comment by LorbusChris** [comment]
Since we don't have an e2e test for this, and AWS is not affected by the change:
/override ci/prow/e2e-aws

**Comment by LorbusChris** [comment]
@jomeier there's an extra whitespace. You can see the fix in the `gofmt` test logs. Please fix.

**Comment by jomeier** [comment]
> @jomeier there's an extra whitespace. You can see the fix in the `gofmt` test logs. Please fix.

Ups. Fixed it :-)

**Comment by LorbusChris** [comment]
Thank you :) 
/override ci/prow/e2e-aws
/lgtm

**Comment by vrutkovs** [comment]
This needs to be reworked to run when `IsOKD` is enabled only :/ This will ensure we can merge with installer master cleanly

**Pull request merged**
