### PR TITLE
bootkube.sh: remove disfunctional --disable-phase-2 for scheduler

### PR DESCRIPTION
**Pull request by sttts**
We had forgotten this one for the scheduler. We used that to transition from 3 to 2 phases in October.

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
/lgtm

/hold
/cc @crawford
This looks like a bug fix.

**Comment by ravisantoshgudimetla** [comment]
Thanks for the PR @sttts. Let's wait for @crawford for weigh in here.

**Comment by crawford** [comment]
@sttts @ravisantoshgudimetla can you give me a link to the bug that is addressed by this PR? Or if there is no report, can you describe the bug here?

**Comment by ravisantoshgudimetla** [comment]
@crawford - Any other concerns here?

**Pull request merged**
