### PR TITLE
fixes missed in PR #372

### PR DESCRIPTION
**Pull request by abhinavdahiya**
/cc @crawford

### CODE REVIEW

**Comment by crawford** [comment]
Can we rename "URI" to "Libvirt Connection URI"?

**Comment by abhinavdahiya** [comment]
@wking recommended `Libvirtd URI`. Any preference between `Libvirt Connection URI` and `Libvirtd URI`

**Comment by crawford** [comment]
https://libvirt.org/uri.html refers to them as Connection URIs.

**Comment by wking** [comment]
/hold

Wait on #379.

**Pull request merged**
