### PR TITLE
update openshift/api for network config changes

### PR DESCRIPTION
**Pull request by danwinship**
Followup to https://github.com/openshift/api/pull/239.

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
/hold

These are just vendor updates. Why does the installer need this bump?

**Comment by danwinship** [comment]
@abhinavdahiya the installer generates a network config object, which it marshals to yaml at one point; it needs the `omitempty`s that are added to `config/v1/types_network.go` to generate *correct* yaml.

Currently it is outputting something like

    status:
      clusterNetwork: null
      clusterNetworkMTU: 0
      networkType: ""
      serviceNetwork: null

Previously this caused errors when trying to create an object from the yaml because the `null`s made CRD validation fail. https://github.com/openshift/api/pull/237 and https://github.com/openshift/cluster-config-operator/pull/23 fixed this by making those fields allow `null`, but this was the wrong fix. https://github.com/openshift/api/pull/239 changed the fields to be marked `omitempty` instead, so now with this PR the installer will write out `status: {}` instead, which is what it really means.

**Comment by abhinavdahiya** [comment]
> @abhinavdahiya the installer generates a network config object, which it marshals to yaml at one point; it needs the `omitempty`s that are added to `config/v1/types_network.go` to generate _correct_ yaml.
> 
> Currently it is outputting something like
> 
> ```
> status:
>   clusterNetwork: null
>   clusterNetworkMTU: 0
>   networkType: ""
>   serviceNetwork: null
> ```
> 
> Previously this caused errors when trying to create an object from the yaml because the `null`s made CRD validation fail. [openshift/api#237](https://github.com/openshift/api/pull/237) and [openshift/cluster-config-operator#23](https://github.com/openshift/cluster-config-operator/pull/23) fixed this by making those fields allow `null`, but this was the wrong fix. [openshift/api#239](https://github.com/openshift/api/pull/239) changed the fields to be marked `omitempty` instead, so now with this PR the installer will write out `status: {}` instead, which is what it really means.

can you that in the commit https://github.com/openshift/installer/blob/master/CONTRIBUTING.md#commit-message-format :pray: Thanks!

**Comment by danwinship** [comment]
updated (without the saga of the abandoned original fix). AFAIK there was no actual bug filed anywhere about the original "fails CRD validation" problem so there was nothing to point to for that.

**Comment by abhinavdahiya** [comment]
> updated (without the saga of the abandoned original fix). AFAIK there was no actual bug filed anywhere about the original "fails CRD validation" problem so there was nothing to point to for that.

/hold cancel
/lgtm

**Pull request merged**
