### PR TITLE
add timeout arguments to creation

### PR DESCRIPTION
**Pull request by mrjoshuap**
I was encountering problems (arguably only on libvirt) where certain timeouts were reached and it only needed a little bit more time.  I found myself changing the hard coded values a few times and figured I'd get this out there to support others who might need to do the same.

I'm also not a profound go developer, so this might need to be reworked and am open to suggestions.

I also debated just using a straight up time.Duration for the flags, but prefer working in integers for consistency with my other workflows...

Output from the help:

```
$ openshift-install create --help
Create part of an OpenShift cluster

Usage:
  openshift-install create [flags]
  openshift-install create [command]

Available Commands:
  cluster          Create an OpenShift cluster
  ignition-configs Generates the Ignition Config asset
  install-config   Generates the Install Config asset
  manifests        Generates the Kubernetes manifests

Flags:
      **--bootstrap-timeout int        Minutes to wait for bootstrapping to complete (default 30)**
      **--cluster-timeout int          Minutes to wait timeout for the cluster to initialize (default 30)**
      **--console-timeout int          Minutes to wait timeout for the console to be up (default 15)**
  -h, --help                         help for create
      **--kubernetes-api-timeout int   Minutes to wait for the Kubernetes API to be up (default 30)**

Global Flags:
      --dir string         assets directory (default ".")
      --log-level string   log level (e.g. "debug | info | warn | error") (default "info")

Use "openshift-install create [command] --help" for more information about a command.
```

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
If a cluster fails in given hard coded time. It is a bug on the platform.

Look at previous PRs that increase timeouts were rejected. like https://github.com/openshift/installer/pull/1553

The approach of adding timeout flags is a no-go.

Also look at `wait-for` subcommands.

I'm not closing this PR _for now_

**Comment by wking** [comment]
I still feel like we need a solid understanding of the delay before we bump or add options for the hard-coded timeouts.  What was making your runs slow?  How slow?  Which phases?

**Comment by crawford** [comment]
I'm against adding options or flags unless it's absolutely necessary and agree that if a cluster takes longer than our timeouts, it's a bug. Please open an issue with more detail about your timeouts so we can start to address the underlying problem.

/close

**Pull request closed without merging**
