### PR TITLE
Generic libvirt installer image for CI

### PR DESCRIPTION
**Pull request by jaypoulz**
A libvirt image to support both nested libvirt through GCE and remote libvirt directly.

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
Can you provide details on how this is different from `image/nested-libvirt` and why we cannot use that.

**Comment by jaypoulz** [comment]
Absolutely @abhinavdahiya!

So basically, the current implementation of the libvirt tests work through the nested-libvirt image, which somewhat of a misleading name. It's really an image capable of SSH and gcloud API commands. See diagram below:
https://drive.google.com/open?id=19jZh8CpoWF5cOJ6bYfladXj39IyMl5Fb

The remote libvirt installer is different in that it actually runs the openshift-install binary on itself. Since it can't deploy a bunch of KVM nodes to itself, it needs to target a remote host running a libvirt process. See the diagram below for details:
https://drive.google.com/open?id=1qg2vEhNt_LoHczI4vHYtaOGedd3nwAug

**Comment by jaypoulz** [comment]
It's not that we couldn't update the nested-libvirt container to fit our use case - it's just that it would add extra bloat to that container because all of the libvirt shared objects and client libraries would need to be installed on it. I didn't want to mess with the libvirt development setup since our workflow is completely different, and I was being mindful of container size.

In a lot of ways, this image is a cross-breed between the nested-libvirt and baremetal installers.

**Comment by crawford** [comment]
@abhinavdahiya we are going to introduce a generic libvirt image instead. We can then migrate off of the nested-libvirt image and eventually remove it.

**Comment by crawford** [comment]
/approve
/lgtm

The end-to-end tests (failing or not) have nothing to do with this change, which will only affect CI for Z (not in place yet). We don’t need to wait for their results.

/override ci/prow/e2e-aws-scaleup-rhel7
/override ci/prow/e2e-aws-fips 
/override ci/prow/e2e-aws
/override ci/prow/e2e-libvirt
/override ci/prow/e2e-openstack
/override ci/prow/e2e-aws-upgrade

**Pull request merged**
