### PR TITLE
remove unused email and password from installconfig

### PR DESCRIPTION
**Pull request by sallyom**
@wking these aren't used anywhere, right?
@enj is working on configuring an initial user for which a password will be created, rather than a user providing a password.  

https://jira.coreos.com/browse/AUTH-165

### CODE REVIEW

**Comment by crawford** [comment]
/hold

@derekwaynecarr wanted to keep these around so that the new console used them.

**Comment by crawford** [comment]
@sallyom oops, I just got caught up on my email and I see that discussion now.

/unhold

**Comment by sallyom** [comment]
closing, in favor of this: https://github.com/openshift/installer/pull/771

**Pull request closed without merging**
