### PR TITLE
OCPBUGS-34368: OCPBUGS-34325: OCPBUGS-34311: OCPBUGS-34221: Bump golang 1.22

### PR DESCRIPTION
**Pull request by r4f4**
With the kube rebase to 1.30, golang 1.22+ is now required. The ART bot has been creating PRs to update both golang to 1.22 and openshift to 1.17, but it's doing it on a per-image basis. That won't work for the Installer because we have to bump *all* our images at once, including images used in CI and used as intermediary build steps which ART doesn't know about.

Moving to golang-1.22 also brings other benefits, like the fix for the reuse of loop variables.

### CODE REVIEW

**Comment by r4f4** [comment]
/retitle OCPBUGS-34368: OCPBUGS-34325: OCPBUGS-34311: OCPBUGS-34221: Bump golang 1.22

**Comment by r4f4** [comment]
Update: fixed an issue with verify-vendor.

**Comment by r4f4** [comment]
Note: `golint` will fail until we can bump the linter to a version with support for golang 1.22.

**Review by barbacbd — COMMENTED** [review]
/approve

**Comment by patrickdillon** [comment]
/hold

golint errors are legit

**Comment by r4f4** [comment]
> /hold
> 
> golint errors are legit

Yes I said so and pointed you to a thread with the tpt team about a newer golangci-lint version.

**Comment by patrickdillon** [comment]
> > /hold
> > golint errors are legit
> 
> Yes I said so and pointed you to a thread with the tpt team about a newer golangci-lint version.

We pull directly from dockerhub for this one ao we dont need dptp’s help. We can just update https://github.com/openshift/installer/blob/master/hack/go-lint.sh

to, say, the most recent version. @barbacbd you approved this pr. Can i reward your work with more work and ask you bump this in another pr? That one should unblock this. Then @r4f4 can enjoy his vacation 😄

**Comment by r4f4** [comment]
> > > /hold
> > > golint errors are legit
> > 
> > Yes I said so and pointed you to a thread with the tpt team about a newer golangci-lint version.
> 
> We pull directly from dockerhub for this one ao we dont need dptp’s help. We can just update https://github.com/openshift/installer/blob/master/hack/go-lint.sh

No we don't. That's only for local dev. I'm CI we use a golangci-lint that's mirrored in the internal image stream. See the golint job definition in the installer configs in the release repo.

> to, say, the most recent version. @barbacbd you approved this pr. Can i reward your work with more work and ask you bump this in another pr? That one should unblock this. 
> we got this @r4f4. enjoy your pto😄

Yeah sorry I forgot to add the bump in this PR.

**Comment by barbacbd** [comment]
Looking at the gcp logs, I see the debug statement. It still looks like it failed to pull the logs due to connection issues with the bootstrap node. 
```
level=info msg=Pulling Cluster API manifests
level=info msg=Failed to gather Cluster API manifests: either Cluster API manifests not generated or terraform provision
level=info msg=Pulling VM console logs
level=info msg=Pulling debug logs from the bootstrap machine
level=info msg=Failed to gather bootstrap logs: failed to connect to the bootstrap machine: dial tcp 35.223.230.188:22: connect: connection timed out
level=error msg=Attempted to gather ClusterOperator status after installation failure: listing ClusterOperator objects: Get "https://api.ci-op-s32ttmdt-6a305.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:6443/apis/config.openshift.io/v1/clusteroperators": dial tcp 34.135.64.243:6443: i/o timeout
level=error msg=Bootstrap failed to complete: DEBUGGIN
```

**Comment by patrickdillon** [comment]
> Looking at the gcp logs, I see the debug statement. It still looks like it failed to pull the logs due to connection issues with the bootstrap node.
> 
> ```
> level=info msg=Pulling Cluster API manifests
> level=info msg=Failed to gather Cluster API manifests: either Cluster API manifests not generated or terraform provision
> level=info msg=Pulling VM console logs
> level=info msg=Pulling debug logs from the bootstrap machine
> level=info msg=Failed to gather bootstrap logs: failed to connect to the bootstrap machine: dial tcp 35.223.230.188:22: connect: connection timed out
> level=error msg=Attempted to gather ClusterOperator status after installation failure: listing ClusterOperator objects: Get "https://api.ci-op-s32ttmdt-6a305.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:6443/apis/config.openshift.io/v1/clusteroperators": dial tcp 34.135.64.243:6443: i/o timeout
> level=error msg=Bootstrap failed to complete: DEBUGGIN
> ```

I think this comment is intended for a different PR, #8450

**Comment by pierreprinetti** [comment]
Just in case...
/test golint

**Comment by r4f4** [comment]
> Just in case... /test golint

We just created a golangci-lint image with a version supporting golang 1.22 but it's not yet used by the Installer configs. So this test won't pass just yet.

**Comment by r4f4** [comment]
Depends on https://github.com/openshift/release/pull/52723

**Comment by r4f4** [comment]
PR just merged, let's see now
/test golint

**Comment by sadasu** [comment]
Can we update https://github.com/openshift/installer/blob/master/hack/go-lint.sh#L8 to v1.59.0 as in https://github.com/openshift/release/pull/52723 in a commit to this PR?

**Comment by r4f4** [comment]
> Can we update https://github.com/openshift/installer/blob/master/hack/go-lint.sh#L8 to v1.59.0 as in [openshift/release#52723](https://github.com/openshift/release/pull/52723) in a commit to this PR?

I'm doing it in a follow-up https://github.com/openshift/installer/pull/8535 to not delay this PR from merging any longer.

**Pull request merged**
