### PR TITLE
OCPBUGS-28203: Power VS: Add sleep to allow workspace to configure PER

### PR DESCRIPTION
**Pull request by mjturek**

### CODE REVIEW

**Review by barbacbd — COMMENTED** [review]
There may be a default value, but is there any point in having these input variables to terraform if the installer doesn't supply the data? 

`pkg/tfvars/powervs/powervs.go`

**Comment by mjturek** [comment]
> There may be a default value, but is there any point in having these input variables to terraform if the installer doesn't supply the data?
> 
> `pkg/tfvars/powervs/powervs.go`

Mostly for consistency. We generally try not to keep values in variables for our terraform (though there are probably cases where we broke this convention). Making it configurable in the future would also be easier.

**Comment by miyamotoh** [comment]
/lgtm
as long as this is verified working in most, if not all, regions we support.

**Review by r4f4 — COMMENTED** [review]
/approve

**Pull request merged**
