### PR TITLE
Revert "pkg/asset: Introduce Load() into the Asset interface that loads assets (from disk)"

### PR DESCRIPTION
**Pull request by deads2k**
Reverts openshift/installer#374

sorry @stevekuznetsov I don't know how to create this pull locally.

Multiple reports of: I run with libvirt and after this pull merged I see
```
[deads@deads-02 installer]$ bin/openshift-install cluster
FATAL Error executing openshift-install: open tests/smoke/vendor/github.com/prometheus/procfs/fixtures/26231/fd/0: no such file or directory
```

resetting to bf0fa6d909b2c9c4f20fd90551bf6a42c77b13d9 gives me a working binary

@sallyom @djzager @yifan-gu @wking @abhinavdahiya 

This is one option.  If we know how to push through, I'm fine with that too.

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
The error is because #374 allowed installer to read intermediate assets from the `--dir`. It looks like your `--dir` is set to root of repo, so it tries to read the files from tests dir... The deafult is `.`
@deads2k can you try `--dir my-cluster` when running the installer?

**Comment by wking** [comment]
Can we adjust to only load files that match paths from the graph?

**Comment by abhinavdahiya** [comment]
Yifans PR preloads the dir on startup and then serves the asset from internal cache.

**Comment by wking** [comment]
Would it be hard to populate on demand?

**Comment by crawford** [comment]
@wking is working on an alternate fix.

/hold

**Comment by wking** [comment]
Ok, I've pushed #497 replacing the early `Walk` loading with on-demand loading.  I'm still testing locally, but it's up for other folks to start looking over.

**Comment by rajatchopra** [comment]
.

> Ok, I've pushed #497 replacing the early `Walk` loading with on-demand loading. I'm still testing locally, but it's up for other folks to start looking over.

On-demand is clean, but it will be much slower. Can't we make Walk more robust? No need to error.. just put only valid values in the cache.

**Comment by wking** [comment]
> On-demand is clean, but it will be much slower. Can't we make Walk more robust? No need to error.. just put only valid values in the cache.

How many files are we loading?  Should be a handful of explicit files and a few globs.  I can benchmark if you like, but I'm guessing this will be performant enough.

**Comment by stevekuznetsov** [comment]
@deads2k your git fu is bad and you should feel bad :)

**Pull request closed without merging**
