### PR TITLE
Bug 1851069: rhcos/ppc64le, s390x: Bump to 45.82.202006240558-0 and 45.82.202006240257-0

### PR DESCRIPTION
**Pull request by Prashanth684**
Keep in sync with x86_64 to pull in the new machine-os-content and other changes

### CODE REVIEW

**Comment by Prashanth684** [comment]
/retitle: Bug 1851069: rhcos/ppc64le, s390x: Bump to 45.82.202006240558-0 and 45.82.202006240257-0

**Comment by ashcrow** [comment]
Reviewing package diffs now.

xref: https://github.com/openshift/installer/pull/3791

**Comment by ashcrow** [comment]
Seems reasonable :+1:

**Pull request merged**
