### PR TITLE
OCPBUGS-7699: CVE: go-getter vulnerable to denial of service via malicious compressed archive

### PR DESCRIPTION
**Pull request by r4f4**
Depends on https://github.com/openshift/installer/pull/6892 for the terraform bump/fix.

/hold

### CODE REVIEW

**Comment by r4f4** [comment]
Rebased to fix merge conflicts.
/hold cancel

**Comment by r4f4** [comment]
Rebased to fix merge conflicts.

**Review by barbacbd — COMMENTED** [review]
/lgtm

**Pull request merged**
