### PR TITLE
Revendor for cluster-api

### PR DESCRIPTION
**Pull request by enxebre**
Revendor to accommodate https://github.com/openshift/cluster-api/pull/34 for the machine renderered manifests so they pass CRD validation once they are updated https://github.com/openshift/machine-api-operator/pull/305

### CODE REVIEW

**Comment by enxebre** [comment]
cc @derekwaynecarr

**Comment by ingvagabund** [comment]
As long as the installer does not set all the fields that got removed, we are fine. Though, I would assume all the fields not defined in machine(set) CRD and present in machine(set) manifests will be ignored when decoding to go types.

**Pull request merged**
