### PR TITLE
OPNET-357: Populate network configuration at install-time

### PR DESCRIPTION
**Pull request by mkowalski**

### CODE REVIEW

**Comment by mkowalski** [comment]
Metal and vSphere succeded. OpenStack failed because of my copy-paste error that I have already fixed. Now we are only waiting for https://github.com/openshift/api/pull/1593 to merge so that the custom vendor hack is not needed here.

**Comment by mkowalski** [comment]
/cc @cybertron 
Ready to review, OpenStack installed successfully (failed on unrelated conformance) and Metal passed completely

**Comment by cybertron** [comment]
/lgtm

/test e2e-vsphere-ovn
/test e2e-metal-ipi
/test e2e-openstack-ovn

I think this was only rebased since the metal and OpenStack jobs passed, but we should make sure to get a VSphere pass on this too since we're touching that code.

**Comment by jcpowermac** [comment]
There is issue with the csi driver w/zonal.

/lgtm

@rvanderp3 @vr4manta for awareness

**Comment by mkowalski** [comment]
/cc @cybertron 

Ready to review. Metal, vSphere and OpenStack job passed

**Comment by mkowalski** [comment]
/cc @jcpowermac
As previous reviewer (https://github.com/openshift/installer/pull/7604#issuecomment-1834632860), this has been rebased

**Comment by mkowalski** [comment]
Hey @sadasu, any chance you look at this here as you approved the recent API bump?

**Pull request merged**
