### PR TITLE
Bug 1817717: Backport Azure UPI to 4.3

### PR DESCRIPTION
**Pull request by fabianofranz**
This PR backports Azure UPI to the 4.3 release by cherry-picking all related commits as-is, with no code changes.

Fixes story https://issues.redhat.com/browse/CORS-1407 (Azure upi: Backport to 4.3.z)

### CODE REVIEW

**Comment by fabianofranz** [comment]
@abhinavdahiya and @jhixson74 please review, thanks!

**Comment by fabianofranz** [comment]
@sdodson do I need a BZ here? Since the original one is in master and 4.4 for quite some time already and never had a BZ, it was based in a Jira story. cc @e-tienne

**Comment by sdodson** [comment]
> @sdodson do I need a BZ here? Since the original one is in master and 4.4 for quite some time already and never had a BZ, it was based in a Jira story. cc @e-tienne

Yes, you'll need a 4.5.0, 4.4.0, and 4.3.z bug to get this merged. Will sync up with you on and Etienne on slack.

**Comment by sdodson** [comment]
/lgtm
Unsure why the bot ignored @jhixson74

**Comment by e-tienne** [comment]
LGTM as well

Confirmed working latest nightly

**Pull request merged**
