### PR TITLE
Fixed the problem of cursor position (CPR)

### PR DESCRIPTION
**Pull request by shlao**
A few months ago, I opened an Issue 
https://github.com/AlecAivazis/survey/issues/183

The upstream has fixed that problem
https://github.com/AlecAivazis/survey/pull/203

The CPR is important for the Qe automation.
Please, review the pr and help us to improve the automation

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
Do we have a Bugzilla for this? If not can you  open a Bugzilla and title the PR `Bug xxxx: <normal guidelines>`

**Comment by shlao** [comment]
@abhinavdahiya , Thanks! At fist, I am sorry for the late reply, there are lots of tests for me to run. I will try to find if there is a bug that has been reported.

**Comment by abhinavdahiya** [comment]
> @abhinavdahiya , Thanks! At first, I am sorry for the late reply, there are lots of tests for me to run. I will try to find if there is a bug that has been reported.

Thanks, I think a Bugzilla would be required to merge this.

**Comment by abhinavdahiya** [comment]
/hold

The master is open only for bug fixes as we prepare for 4.2 release. this need a bugzilla targeted for 4.2 to merge.

**Comment by abhinavdahiya** [comment]
@shlao will https://github.com/openshift/installer/pull/2297 fix the issue.

**Comment by shlao** [comment]
@abhinavdahiya  yes, It's fixed in that pr, thanks so much.
The whole qe team is busy in running tests for GA.

**Pull request closed without merging**
