### PR TITLE
data/rhcos.json: Update boot images

### PR DESCRIPTION
**Pull request by ashcrow**
- amd64:   47.83.202102090044-0
- s390x:   47.83.202102090311-0
- ppc64le: 47.83.202102091015-0

4.8: https://github.com/openshift/installer/pull/4634
4.7: https://github.com/openshift/installer/pull/4635

### CODE REVIEW

**Review by andymcc — APPROVED** [review]
Checked multi-arch builds vs x86 and they all match, so LGTM!

**Comment by sdodson** [comment]
/lgtm
/approve
Merging based on the positive tests from https://github.com/openshift/installer/pull/4634

**Comment by sdodson** [comment]
/override ci/prow/e2e-ovirt
/override ci/prow/openstack-manifests
All of these overrides are based on the tests from the 4.8 branch pr

**Pull request merged**
