### PR TITLE
pkg/asset: update tectonic-operators to drop all openshift apis

### PR DESCRIPTION
**Pull request by abhinavdahiya**
https://github.com/coreos-inc/tectonic-operators/pull/464 merged changes that drop openshift-api.

/cc @deads2k @juanvallejo

### CODE REVIEW

**Comment by wking** [comment]
/hold

Actually, do we need to remove [this][1] too?

[1]: https://github.com/openshift/installer/blob/5a708e283e2ea1c38a82d0d1cd3bcc2760ba81e9/pkg/asset/manifests/content/bootkube/cvo-overrides.go#L34-L37

**Comment by wking** [comment]
Also, do we need #298 for this?  coreos-inc/tectonic-operators#464 claims it as a dependency.

**Comment by wking** [comment]
[e2e][1]:

```
• Failure in Spec Setup (BeforeEach) [127.975 seconds]
[sig-storage] Secrets
/tmp/openshift/build-rpms/rpm/BUILD/origin-4.0.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/common/secrets_volume.go:33
  should be consumable from pods in volume with defaultMode set [NodeConformance] [Conformance] [Suite:openshift/conformance/parallel/minimal] [Suite:k8s] [BeforeEach]
  /tmp/openshift/build-rpms/rpm/BUILD/origin-4.0.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/framework.go:684

  Expected error:
      <*errors.errorString | 0xc420093570>: {
          s: "timed out waiting for the condition",
      }
      timed out waiting for the condition
  not to have occurred

  /tmp/openshift/build-rpms/rpm/BUILD/origin-4.0.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/framework.go:217
```

Dunno if that's a flake or not.

[1]: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_installer/421/pull-ci-openshift-installer-master-e2e-aws/513/build-log.txt

**Comment by abhinavdahiya** [comment]
investigating locally.

**Comment by abhinavdahiya** [comment]
Requires https://github.com/openshift/origin/pull/21183

**Comment by deads2k** [comment]
> Requires [openshift/origin#21183](https://github.com/openshift/origin/pull/21183)

origin pull merged and images have pushed.

**Comment by deads2k** [comment]
> /retest

needs a rebase.

**Pull request merged**
