### PR TITLE
OCPBUGS-262: UPI image download govc rate limit failure

### PR DESCRIPTION
**Pull request by jcpowermac**
Removing the downloading of `govc` to
workaround rate limit errors

### CODE REVIEW

**Comment by jcpowermac** [comment]
openshift/release#29826

**Comment by r4f4** [comment]
/override ci/prow/e2e-azure-upi

`e2e-azure-upi` has some permafailing tests (see [1]) and the PR is passing the `upi-installer` build phase anyway.

[1] https://testgrid.k8s.io/redhat-openshift-ocp-release-4.11-informing#periodic-ci-openshift-release-master-nightly-4.11-e2e-azure-upi

**Pull request merged**
