### PR TITLE
OSASINFRA-3193: Update openstack/Dockerfile.ci for ansible-core

### PR DESCRIPTION
**Pull request by EmilienM**
Ansible 2.9 is going EOL later this year, we need to use ansible-core
and until we get RPMs for openstack collections, we'll install them from
source.

TODO:

* [ ] Update the doc in docs/user/openstack/install_upi.md

### CODE REVIEW

**Comment by EmilienM** [comment]
We need to watch for `e2e-openstack-upi ` job (at very least).

**Comment by EmilienM** [comment]
I'm making progress and doing step by step as soon as I see errors in logs.

**Comment by EmilienM** [comment]
UPI job working: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_installer/7346/pull-ci-openshift-installer-master-e2e-openstack-upi/1682408919860776960

Now we need to update the doc at some point to change Ansible version.

**Review by mandre — COMMENTED** [review]
/lgtm
/approve

**Comment by MaysaMacedo** [comment]
Will the docs be updated as well?

**Comment by EmilienM** [comment]
@MaysaMacedo yes, I didn't expect this PR to land now! but it's not a big deal. I'm now working on another one with doc and some other improvements for UPI.

**Pull request merged**
