### PR TITLE
[release-4.8] Bug 2098162: Bootstrap timeout

### PR DESCRIPTION
**Pull request by honza**

### CODE REVIEW

**Comment by sadasu** [comment]
We can achieve this backport with just 1 commit with the timeout added to the correct location. But, I notice there are 2 commits. Any specific reason for this that I am missing?

**Comment by sdodson** [comment]
Given the urgency and simplicity of this and the fact that it's been verified in 4.10 to resolve a customer issue I'm overriding bugzilla/valid-bug to accelerate the merge process.

**Pull request merged**
