### PR TITLE
Bug 1684670: data/data/bootstrap: add kube-client-agent-image flag

### PR DESCRIPTION
**Pull request by hexfusion**
* adds new flag and populate with release image metadata

This is a cherry-pick of the original reverted PR #1401 reverted by #1424 

/hold

### CODE REVIEW

**Comment by hexfusion** [comment]
/cc @wking @abhinavdahiya manually verified images I think we can merge this.

* registry.reg-aws.openshift.com:443/openshift/ose-kube-etcd-signer-server:v4.0.0-0.0.0.666.12
* registry.reg-aws.openshift.com:443/openshift/ose-kube-client-agent:v4.0.0-0.0.0.666.12

**Comment by hexfusion** [comment]
manually verified images I think we can merge this.

* registry.reg-aws.openshift.com:443/openshift/ose-kube-etcd-signer-server:v4.0.0-0.0.0.666.12
* registry.reg-aws.openshift.com:443/openshift/ose-kube-client-agent:v4.0.0-0.0.0.666.12

/cc @wking @abhinavdahiya

**Comment by hexfusion** [comment]
Maybe @smarterclayton you want to take a look at this as well. Do we need to address `kube-etcd-signer-server` here as well?

**Comment by hexfusion** [comment]
I raised https://github.com/openshift/cluster-bootstrap/pull/22 perhaps this needs to land first?

**Comment by wking** [comment]
> Do we need to address kube-etcd-signer-server here as well?

I'm fine handling that in a separate PR.

/lgtm

**Pull request merged**
