### PR TITLE
Bug 1747519: pkg/destroy/aws: Delete security groups and subnets by VPC

### PR DESCRIPTION
**Pull request by wking**
Sometimes CI leaks untagged security groups and subnets.  Because we are allowed to remove all resources from within a cluster-owned VPC, add `*ByVPC` walkers to remove these indirectly-owned resources.

### CODE REVIEW

**Comment by wking** [comment]
This approach is fine for CI, where we own the whole VPC.  It's going to break down when we get to bring-your-own-VPC, so we may want to consider another approach now.

* We might be able to get the AWS Terraform provider patched to fake atomic create-and-tag behavior, by having it delete the created object if a job failed or was aborted before tagging completed.
* We could use Terraform to completely tear down clusters that fail during Terraform provisioning, although we currently leave the resources up to help with debugging and allow the possibility of users manually completing the cluster by adding the remaining resources.

However, neither of *those* approaches are going to work cleanly with creation runs that are killed (e.g. by a power outage on the install host) without recording the Terraform state.  So we might want the belt-and-suspenders of these `*ByVPC` helpers to cover the cluster-owned-VPC case *and* later Terraform-based (partial) deletion to cover the "we're still alive with the Terraform state" case.  And we'll just continue to leak the "borrowed VPC and lost the Terraform state" case.

**Comment by wking** [comment]
Hrm.  [The upgrade job][1] passed, and from its installer log we can see that the one round seems to include successful results for the earlier `deleteEC2RouteTablesByVPC` and the later `deleteEC2VPCEndpointsByVPC` but with nothing (successful or otherwise) from `deleteEC2SecurityGroupsByVPC` or `deleteEC2SubnetsByVPC`:

```console
$ curl -s https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_installer/2214/pull-ci-openshift-installer-master-e2e-aws-upgrade/1828/artifacts/e2e-aws-upgrade/installer/.openshift_install.log | grep '2019-08-14T08:47:16'
time="2019-08-14T08:47:16Z" level=info msg=Deleted arn="arn:aws:ec2:us-east-1:460538899914:vpc/vpc-028406fc8261cde53" id=vpc-028406fc8261cde53 network interface=eni-0e11139a671c067c2
time="2019-08-14T08:47:16Z" level=info msg=Deleted arn="arn:aws:ec2:us-east-1:460538899914:vpc/vpc-028406fc8261cde53" id=vpc-028406fc8261cde53 network interface=eni-06f4f3ec769ccc88e
time="2019-08-14T08:47:16Z" level=info msg=Deleted arn="arn:aws:ec2:us-east-1:460538899914:vpc/vpc-028406fc8261cde53" id=vpc-028406fc8261cde53 network interface=eni-0be8a73d9a5bcdc9a
time="2019-08-14T08:47:16Z" level=info msg=Deleted arn="arn:aws:ec2:us-east-1:460538899914:vpc/vpc-028406fc8261cde53" id=vpc-028406fc8261cde53 table=rtb-02f4cc762db95fa77
time="2019-08-14T08:47:16Z" level=info msg=Deleted VPC endpoint=vpce-0ae761076c8a81705 arn="arn:aws:ec2:us-east-1:460538899914:vpc/vpc-028406fc8261cde53" id=vpc-028406fc8261cde53
time="2019-08-14T08:47:16Z" level=debug msg="DependencyViolation: The vpc 'vpc-028406fc8261cde53' has dependencies and cannot be deleted.\n\tstatus code: 400, request id: 2cb00845-55f8-4dd4-9b17-3cff5cb78102" arn="arn:aws:ec2:us-east-1:460538899914:vpc/vpc-028406fc8261cde53"
```

[1]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_installer/2214/pull-ci-openshift-installer-master-e2e-aws-upgrade/1828

**Comment by wking** [comment]
I think I fixed the teardown hang with 7de50d2bb -> 55630a304, which no longer attempts to delete security groups with the reserved `default` name.

**Comment by wking** [comment]
[e2e-aws][1] has lots of:

```
 Aug 22 21:17:28.789: INFO: Couldn't delete ns: "e2e-svcaccounts-2381": namespace e2e-svcaccounts-2381 was not deleted with limit: timed out waiting for the condition, namespace is empty but is not yet removed (&errors.errorString{s:"namespace e2e-svcaccounts-2381 was not deleted with limit: timed out waiting for the condition, namespace is empty but is not yet removed"}) 
```

which is [rhbz#1727090][2].

/test e2e-aws

[1]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_installer/2214/pull-ci-openshift-installer-master-e2e-aws/7366
[2]: https://bugzilla.redhat.com/show_bug.cgi?id=1727090

**Comment by wking** [comment]
Retest request didn't stick.  Trying again:

/test e2e-aws

**Comment by wking** [comment]
Green enough (just scaleup still in flight).  CC @abhinavdahiya for review.

**Comment by abhinavdahiya** [comment]
Do we have an idea on how many calls it adds to our already `on-the-edge` rate limiting..? VPC is usually the last resource, and this `ByVPC` is pretty expensive.

**Comment by wking** [comment]
> Do we have an idea on how many calls it adds...

Comparing [e2e-aws][1] (which used the new code for teardown) and [e2e-aws-upgrade][2] (which used whatever was in master at the time):

```console
$ curl -s https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_installer/2214/pull-ci-openshift-installer-master-e2e-aws/7377/artifacts/e2e-aws/installer/.openshift_install.log | grep 'DependencyViolation.*\(sg-\|subnet\|vpc\)' | wc -l
38
$ curl -s https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_installer/2214/pull-ci-openshift-installer-master-e2e-aws-upgrade/1934/artifacts/e2e-aws-upgrade/installer/.openshift_install.log | grep 'DependencyViolation.*\(sg-\|subnet\|vpc\)' | wc -l
36
```

So perhaps a 6% increase, although I haven't dug deeper to see if one or the other had especially slow instance removal or similar.

[1]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_installer/2214/pull-ci-openshift-installer-master-e2e-aws/7377
[2]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_installer/2214/pull-ci-openshift-installer-master-e2e-aws-upgrade/1934

**Comment by wking** [comment]
If we pick this back to release-4.1, we want to pick #2346 back too.  This change alone is still an improvement, but #2346 closes a preexisting hole that this PR missed.

**Pull request merged**
