### PR TITLE
OCPBUGS-29388: upi: aws: fix typo in worker templates

### PR DESCRIPTION
**Pull request by r4f4**
The description should say "worker" not "master".

### CODE REVIEW

**Comment by sadasu** [comment]
/override ci/prow/e2e-aws-ovn-upi 

ci/prow/e2e-aws-ovn-upi is permafailing. Opening a bug to take care of it.

**Comment by r4f4** [comment]
/override ci/prow/e2e-aws-ovn-upi 

`e2e-aws-ovn-upi`: deployed a cluster before https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_installer/8112/pull-ci-openshift-installer-master-e2e-aws-ovn-upi/1765794393047961600 and this PR only changes descriptions in the template, no functional changes

**Pull request merged**
