### PR TITLE
NO-JIRA: ignition/bootstrap/common: account for templated files when setting mode

### PR DESCRIPTION
**Pull request by jlebon**
The if chain just after this expects the final filename and not the
possibly templated version. Strip the suffix in case it's a templated
file.

This notably fixes the mode for `registries.conf`, which became a
templated file and so went from 0644 to 0600. This patch brings it back
to 0644.

### CODE REVIEW

**Comment by jlebon** [comment]
Do I need a Jira for this or is NO-JIRA acceptable?

**Comment by r4f4** [comment]
> Do I need a Jira for this or is NO-JIRA acceptable?

`no-jira` is fine as long as we don't need to backport this fix to previous releases.

**Pull request merged**
