### PR TITLE
Bug 1964753: Bump RHCOS 4.7 boot image

### PR DESCRIPTION
**Pull request by gursewak1997**
Changes generated with:
```
./hack/update-rhcos-bootimage.py https://rhcos-redirector.apps.art.xq1c.p1.openshiftapps.com/art/storage/releases/rhcos-4.7-ppc64le/47.84.202109242011-0/ppc64le/meta.json ppc64le
./hack/update-rhcos-bootimage.py https://rhcos-redirector.apps.art.xq1c.p1.openshiftapps.com/art/storage/releases/rhcos-4.7-s390x/47.84.202109242305-0/s390x/meta.json s390x
./hack/update-rhcos-bootimage.py https://rhcos-redirector.apps.art.xq1c.p1.openshiftapps.com/art/storage/releases/rhcos-4.7/47.84.202109241831-0/x86_64/meta.json amd64
```

### CODE REVIEW

**Comment by miabbott** [comment]
/hold

The RHCOS pipeline isn't currently building 4.6 boot media.  We'll need to re-enable that and update this PR.

**Comment by miabbott** [comment]
/test e2e-gcp
/test/e2e-vsphere

**Comment by sdodson** [comment]
Actually, GCP install was successful. Reaching out to openstack folks about their build/install failures.

**Comment by mandre** [comment]
The failure on OpenStack is legit:
```
time="2021-09-23T04:57:39Z" level=info msg="Obtaining RHCOS image file from 'https://rhcos-redirector.apps.art.xq1c.p1.openshiftapps.com/art/storage/releases/rhcos-4.7/47.84.202109171532-0/x86_64/?sha256='"
time="2021-09-23T04:57:39Z" level=fatal msg="failed to fetch Terraform Variables: failed to generate asset \"Terraform Variables\": failed to get openstack Terraform variables: bad status: 403 Forbidden"
```
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_inst[…]nstall-install/artifacts/.openshift_install.log

We're getting a 403 fetching the new image.

**Comment by sdodson** [comment]
Most recent openstack and gcp jobs have all completed their installation.

**Comment by sdodson** [comment]
/lgtm
overriding bugzilla/valid-bug

**Pull request merged**
