### PR TITLE
Fix goautoneg 404

### PR DESCRIPTION
**Pull request by hamzy**
When I build the 4.5 release I see the following error:

[hamzy@C155F2U35 openshift]$ git clone https://github.com/openshift/installer.git
[hamzy@C155F2U35 installer]$ git checkout release-4.5
[hamzy@C155F2U35 installer]$ TAGS=libvirt hack/build.sh 2>&1 | tee output.build
...
+ go generate ./data
go: github.com/openshift/library-go@v0.0.0-20200324092245-db2a8546af81 requires
        bitbucket.org/ww/goautoneg@v0.0.0-20120707110453-75cd24fc2f2c: reading https://api.bitbucket.org/2.0/repositories/ww/goautoneg?fields=scm: 404 Not Found

The following will fix it:

[hamzy@C155F2U35 installer]$ go mod edit -replace bitbucket.org/ww/goautoneg@v0.0.0-20120707110453-75cd24fc2f2c=github.com/munnerz/goautoneg@v0.0.0-20120707110453-a547fc61f48d
[hamzy@C155F2U35 installer]$ go list -m all
...
bitbucket.org/ww/goautoneg v0.0.0-20120707110453-75cd24fc2f2c => github.com/munnerz/goautoneg v0.0.0-20120707110453-a547fc61f48d
...
github.com/munnerz/goautoneg v0.0.0-20191010083416-a7dc8b61c822
...

### CODE REVIEW

**Comment by hamzy** [comment]
This is the first time I've tried a fix for a specific branch (4.5) and not the master branch.  I guess what I did was wrong.

**Comment by staebler** [comment]
> This is the first time I've tried a fix for a specific branch (4.5) and not the master branch. I guess what I did was wrong.

Yep, you need the target branch to be release-4.5.

However, To merge a fix into 4.5, there would need to be a valid bugzilla bug and enough impact of the bug to warrant inclusion in a 4.5 z-stream release. I do not expect that this change is going to meet those standards.

Which version of go are you using? You should be able to build with the modules in the vendor directory without having to download the no-longer-existent goautoneg module. If you are using go1.13, you can add `-mod=vendor` to your `GOFLAGS` environment variable.

**Comment by hamzy** [comment]
Hi @staebler, thanks for your help!  I meant to get back to you with a minor question.

For targeting a specific branch, I did the following:
git checkout --track origin/release-4.5; git checkout -b fix-goautoneg-404
I guess that wasn't right?  

Your suggestion did work by the way:
export GOFLAGS="-mod=vendor"; export TAGS="libvirt"; hack/build.sh

PS.  You can leave this PR closed.  Hopefully people will find it in a Google search.

**Comment by staebler** [comment]
> For targeting a specific branch, I did the following:
> git checkout --track origin/release-4.5; git checkout -b fix-goautoneg-404
> I guess that wasn't right?

That was fine for creating your local branch. But when you created the PR, you needed to select `release-4.5` as the base branch, rather than leaving it as the default of `master`.

**Pull request closed without merging**
