### PR TITLE
Remove global logger

### PR DESCRIPTION
**Pull request by mjudeikis**
Removes global logrus logger object and replaces it with customer provided one.

Enables to consume installer as a package and provide custom logrus Entry object with fields for request tracking. 
Moves logger parameter to beginning of the function calls to match pattern `func([ctx], logger, args...)`
Aligns all assets generates functions to have the same variable names and parameters.
Changes `Generate` interface to accept `*logrus.Entry` as an arg

Part of: https://github.com/openshift/installer/issues/1864

### CODE REVIEW

**Comment by mjudeikis** [comment]
This is initial work to align the installer for ARO work so we could use it as a package and wrap it in either microservice web service or vendor in into bigger control plane.

**Comment by abhinavdahiya** [comment]
The logger to Generate is a little bit intrusive, and not all assets want the logger. Would it be possible to come up with something that doesn't involve changing all assets or even a common type that can hold general global information?

**Comment by mjudeikis** [comment]
Solutions would be to remove ALL logging from assets and return errors instead and handle logging only on errors only. Which is not very intuitive. 

Otherwise, because assets are the implementation of the interface we need to make sure parallel executions get unique identifiers. Hence no global logger is possible here.

**Comment by abhinavdahiya** [comment]
> Otherwise, because assets are the implementation of the interface we need to make sure parallel executions get unique identifiers. Hence no global logger is possible here.

The standard logger is already global...?

**Comment by mjudeikis** [comment]
> > Otherwise, because assets are the implementation of the interface we need to make sure parallel executions get unique identifiers. Hence no global logger is possible here.
> 
> The standard logger is already global...?

It is. But we use `StandardLogger` only in `cmd` package in the installer as its single process execution. When re-using `installer` we would not use anything from `cmd` folder and just call methods directly and will be providing `logrus.Entry` to each go routine executing/creating a cluster.

**Pull request closed without merging**
