### PR TITLE
Remove glide and switch it to dep

### PR DESCRIPTION
**Pull request by abhinavdahiya**
> Glide will continue to be supported for some time but is considered to be in a state of support rather than active feature development.

From https://github.com/Masterminds/glide#golang-dep
* For root `vendor` directory

```console
$ rm -rf tests
$ dep init
// edit Gopkg.toml to add.
// [prune]
//   non-go = true
//   go-tests = true
//   unused-packages = true
$ dep ensure
$ git checkout tests
```

* For `vendor` in `tests/smoke`

```console
$ dep init
// edit Gopkg.toml to add.
// [prune]
//   non-go = true
//   go-tests = true
//   unused-packages = true
$ dep ensure
```

### CODE REVIEW

**Comment by wking** [comment]
While I like the `vendor/` updates you have in this PR, note that [dep also has][1]:

> The Go toolchain, as of 1.11, has (experimentally) adopted an approach that sharply diverges from `dep`.  As a result, we are continuing development of `dep`, but gearing work primarily towards the development of an alternative prototype for versioning behavior in the toolchain.

So we may want to stick with Glide until we can bump to Go 1.11 here (which we may be able to do already?  openshift/release#1365).

[1]: https://github.com/golang/dep/tree/v0.5.0#dep

**Comment by abhinavdahiya** [comment]
@wking 
`dep` has better semantics around constraints and overrides.

Also there is not a reason to believe that we can vendor kubernetes libraries with experimental go mod in 1.11. https://github.com/kubernetes/kubernetes/issues/63607
I don't think go mod are going to be default until https://github.com/golang/go/milestone/65 late Jan 2019.

**Comment by wking** [comment]
> `dep` has better semantics around constraints and overrides.

Yeah, I'm not arguing Glide vs. `dep` long-term.  I'm just not sure it's worth spending time on `dep` if we are going to switch to modules in the next few months.  But...

> Also there is not a reason to believe that we can vendor kubernetes libraries with experimental go mod in go1.11. kubernetes/kubernetes#63607

This issues seems to be about Kubernetes supporting modules cleanly.  Which would be awesome.  But in the meantime, I expect we can pin to specific commits.  For example, see [this][1] in my very-WIP [go-modules branch][2] from my initial poking around back in August.

> I don't think go mod are going to be default until https://github.com/golang/go/milestone/65 late Jan 2019.

No, but the Go folks have [committed to forward compat][3].

So I don't have enough experience with the modules approach to know if it will work out or not.  But I'm not yet convinced it's *not* workable ;).

[1]: https://github.com/wking/openshift-installer/commit/8cf9ea3c5894f8e96d4ec478bbcb0987da5e659d#diff-37aff102a57d3d7b797f152915a6dc16R36
[2]: https://github.com/wking/openshift-installer/tree/go-modules
[3]: https://golang.org/doc/go1.11#modules

**Comment by crawford** [comment]
I see the following when I run `dep ensure`:

```
# Gopkg.lock is out of sync with Gopkg.toml and project imports:
k8s.io/apimachinery/pkg/apis/meta/v1/unstructured: imported or required, but missing from Gopkg.lock's input-imports
k8s.io/apimachinery/pkg/util/errors: imported or required, but missing from Gopkg.lock's input-imports
k8s.io/client-go/kubernetes: imported or required, but missing from Gopkg.lock's input-imports
k8s.io/client-go/pkg/api/v1: imported or required, but missing from Gopkg.lock's input-imports
k8s.io/client-go/tools/clientcmd: imported or required, but missing from Gopkg.lock's input-imports
k8s.io/kubernetes/pkg/kubectl/cmd/util: imported or required, but missing from Gopkg.lock's input-imports
k8s.io/kubernetes/pkg/kubectl/resource: imported or required, but missing from Gopkg.lock's input-imports
```

**Comment by crawford** [comment]
I'm in favor of switch to dep, even if we end up switching to go modules relatively soon.

**Pull request merged**
