### PR TITLE
vendor: update cluster API dependency to latest changes

### PR DESCRIPTION
**Pull request by cynepco3hahue**
`cluster-api` master renamed `providerConfig` to `providerSpec`,
we must align with these changes

Depends on:
- [ ] https://github.com/openshift/machine-api-operator/pull/155

### CODE REVIEW

**Comment by crawford** [comment]
Your commit messages need to follow the style specified in the contribution docs. Take a look at the repo's history for examples. It also looks like a5a23a13e pulled in more than it should have. What command did you use to update the dependencies (this sort of information should be included in the commit message)?

**Comment by cynepco3hahue** [comment]
> Your commit messages need to follow the style specified in the contribution docs. Take a look at the repo's history for examples. It also looks like [a5a23a1](https://github.com/openshift/installer/commit/a5a23a13e26998d8808c57b2775ca141bd53889c) pulled in more than it should have. What command did you use to update the dependencies (this sort of information should be included in the commit message)?

I updated commit messages give me know if it is enough, or I need to make some other changes.
I updated dependencies with `dep ensure -update`

**Comment by ingvagabund** [comment]
@cynepco3hahue. can you change the PR name so it aligns with the `.providerConfig` -> `.providerSpec` renaming. Updating vendored deps does not say much about the main intent.

**Comment by cynepco3hahue** [comment]
> @cynepco3hahue. can you change the PR name so it aligns with the `.providerConfig` -> `.providerSpec` renaming? Updating vendored deps does not say much about the main intent.

Hm, @crawford asked to follow commit naming convention, in this case, the main update is happening under the vendor directory. Also, we have PR description, will it be enough in this case?

**Comment by crawford** [comment]
@cynepco3hahue I can't tell you what the title of this PR should be since I cannot tell the significance of each commit. There is no reasoning provided and this is the most important part (I can already tell you _what_ changed; that's what git does). Please update your commit messages to explain _why_ you are making these changes. The audience of that message is us six months from now (assume we've forgotten everything in the meantime).

**Comment by ingvagabund** [comment]
@enxebre was faster. Merged as part of https://github.com/openshift/installer/pull/1027. @cynepco3hahue sorry for that. This PR is no longer needed then.

**Comment by cynepco3hahue** [comment]
@ingvagabund np:) but it is strange that I have a lot of changes after `dep ensure -update` vs https://github.com/openshift/installer/pull/1027 PR.

**Comment by ingvagabund** [comment]
`dep ensure` is not too deterministic :-|

**Pull request closed without merging**
