### PR TITLE
no-jira: vendor: capi-installer in tech preview

### PR DESCRIPTION
**Pull request by patrickdillon**
Vendors changes from openshift/api to add capi installations to tech preview.

Currently pointing to my local copy as proof for openshift/api#1880

### CODE REVIEW

**Comment by patrickdillon** [comment]
Tested locally and confirmed clusterapi runs as part of techpreview:

```
[root@153753f6a57c /]# cat c/install-config.yaml | head -n 5
apiVersion: v1
baseDomain: devcluster.openshift.com
featureSet: TechPreviewNoUpgrade
metadata:
  name: padillon-05081601
[root@153753f6a57c /]# ./openshift-install create cluster --dir c
INFO Credentials loaded from the "default" profile in file "/root/.aws/credentials" 
WARNING Found override for release image (quay.io/openshift-release-dev/ocp-release:4.16.0-ec.6-x86_64). Please be warned, this is not advised 
INFO Consuming Install Config from target directory 
WARNING FeatureSet "TechPreviewNoUpgrade" is enabled. This FeatureSet does not allow upgrades and may affect the supportability of the cluster. 
INFO Creating infrastructure resources...         
INFO Creating IAM roles for control-plane and compute nodes 
INFO Started local control plane with envtest     
INFO Stored kubeconfig for envtest in: /c/auth/envtest.kubeconfig 
INFO Running process: Cluster API with args [-v=2 --diagnostics-address=0 --health-addr=127.0.0.1:46243 --webhook-port=34809 --webhook-cert-dir=/tmp/envtest-serving-certs-2560545074] 
INFO Running process: aws infrastructure provider with args [-v=4 --diagnostics-address=0 --health-addr=127.0.0.1:37445 --webhook-port=44743 --webhook-cert-dir=/tmp/envtest-serving-certs-1467407592 --feature-gates=BootstrapFormatIgnition=true,ExternalResourceGC=true] 
INFO Created manifest *v1.Namespace, namespace= name=openshift-cluster-api-guests 
```

**Review by r4f4 — COMMENTED** [review]
LGTM but will tag once it bumps to  `openshift/api`.

**Comment by patrickdillon** [comment]
/hold cancel
https://github.com/openshift/api/pull/1880 is now incorporated

**Review by r4f4 — COMMENTED** [review]
/lgtm

**Comment by r4f4** [comment]
/override ci/prow/shellcheck
Failing with a known issue not related to this PR.

**Comment by r4f4** [comment]
/retitle no-jira: vendor: capi-installer in tech preview

**Pull request merged**
