### PR TITLE
CORS-1994: Update Installer Dependencies

### PR DESCRIPTION
**Pull request by barbacbd**
** Updating all dependencies for the installer project
** Updated all with go mod tidy and go mod vendor.

** NOTE: Requires go v1.18+
#6163 
#6077

### CODE REVIEW

**Comment by jhixson74** [comment]
This should be broken up into go mod vendor and go mod tidy commits.

**Comment by barbacbd** [comment]
depends on https://github.com/openshift/installer/pull/6077

**Comment by patrickdillon** [comment]
/approve
/retest

LGTM with successful test runs.

**Review by r4f4 — APPROVED** [review]

**Pull request merged**
