### PR TITLE
OCPBUGS-38966: Skip private managed zone creation for xpn installs

### PR DESCRIPTION
**Pull request by barbacbd**
** Skip the creation of private zone when a private zone already exists in the domain provided. This only applies to shared vpc installs.

### CODE REVIEW

**Review by r4f4 — COMMENTED** [review]
/lgtm

**Comment by patrickdillon** [comment]
The PR looks good to me, so I don't want to hold it up to much, but compute nodes are failing to join the cluster in e2e-gcp-ovn-xpn. Perhaps failure to pull ignition, but no serial console logs...

/test ci/prow/e2e-gcp-ovn-xpn

**Pull request merged**
