### PR TITLE
Bug 1879081: OpenStack: Switch to train/centos8 repos

### PR DESCRIPTION
**Pull request by mandre**
This will be necessary after changing the base image to rhel8:
openshift/release#11839

### CODE REVIEW

**Comment by pierreprinetti** [comment]
> changing the base image to rhel8

We might need to do both at the same time?

https://github.com/openshift/installer/blob/3c130f21348caddc37f4458378e6bf288b00d69e/images/installer/Dockerfile.ci#L4

**Comment by mandre** [comment]
> > changing the base image to rhel8
> 
> We might need to do both at the same time?
> 
> https://github.com/openshift/installer/blob/3c130f21348caddc37f4458378e6bf288b00d69e/images/installer/Dockerfile.ci#L4

No, I believe we'll need openshift/release#11839 to merge first. The images job is failing because the base image for openstack-installer is still rhel-7.

**Comment by mandre** [comment]
The image is now building and the job starts. However it fails with invalid python syntax now that python 3 is the default interpreter.
We'll need https://github.com/openshift/release/pull/11855.

**Comment by pierreprinetti** [comment]
jq in the release repos! 👌

/approve
/lgtm
/hold

**Comment by mandre** [comment]
/hold cancel
The jobs are still failing, but for different reasons.

**Pull request merged**
