### PR TITLE
Bug 2065808: stop considering Mint mode as supported on Azure (#5699)

### PR DESCRIPTION
**Pull request by r4f4**
Co-authored-by: Joel Diaz <jdiaz@redhat.com>

### CODE REVIEW

**Comment by patrickdillon** [comment]
@r4f4 what you should do is create a bugzilla for #5699 and then cherry pick from that PR. The bot will create the needed bugzillas correctly. Let me know if I can help you with that.

**Comment by r4f4** [comment]
> @r4f4 what you should do is create a bugzilla for #5699 and then cherry pick from that PR. The bot will create the needed bugzillas correctly. Let me know if I can help you with that.

@patrickdillon I tried cherry-picking from the PR but there are merge conflicts https://github.com/openshift/installer/pull/5699#issuecomment-1069589272. That's why I did the cherry-pick manually and submitted a new PR.

**Comment by patrickdillon** [comment]
> I tried cherry-picking from the PR but there are merge conflicts [#5699 (comment)](https://github.com/openshift/installer/pull/5699#issuecomment-1069589272). That's why I did the cherry-pick manually and submitted a new PR.

Got it, then this is correct. You will still need to create a BZ for the master branch for the cherry picks.

**Comment by jianping-shu** [comment]
Verified with Flexy-install with the following LAUNCHER_VARS:
credentials_mode: "Mint"
installer_payload_image: registry.build01.ci.openshift.org/ci-ln-8wg6m9k/release:latest(build openshift/installer#5717)

The install failed with the following error info, Passed

03-21 11:00:13.294  [INFO] Generating manifests files.....
03-21 11:00:13.294  level=fatal msg=failed to fetch Master Machines: failed to load asset "Install Config": invalid "install-config.yaml" file: credentialsMode: Unsupported value: "Mint": supported values: "Manual", "Passthrough"

**Comment by jianping-shu** [comment]
Verification done, passed

**Review by staebler — COMMENTED** [review]
/lgtm
/approve
/labal backport-risk-assessed

**Pull request merged**
