### PR TITLE
terraform: add terraform verification to ./hack/verify-vendor.sh

### PR DESCRIPTION
**Pull request by staebler**
Add verification that the vendoring of the terraform sub-modules is in-sync with what is needed for building the sub-modules.
    
https://issues.redhat.com/browse/CORS-1909

### CODE REVIEW

**Comment by staebler** [comment]
This builds on https://github.com/openshift/installer/pull/5672, which should be merged first.

**Comment by staebler** [comment]
> This builds on #5672, which should be merged first.

/hold

**Comment by staebler** [comment]
I am getting an error running `./hack/verify-vendor.sh` locally.
```
$ ./hack/verify-vendor.sh 
+ verify_module /go/src/github.com/openshift/installer
+ pushd /go/src/github.com/openshift/installer
/go/src/github.com/openshift/installer /go/src/github.com/openshift/installer
+ tidy_args=()
+ '[' -n '' ']'
./hack/verify-vendor.sh: line 10: tidy_args[@]: unbound variable
```
/hold

**Comment by staebler** [comment]
a2302d7b8...744db7ded
* Rebased after 75ac8baad3f45d63cbcd84fdd75dfc4e0f1f8db

The change of images used by hack/verify-vendor.sh also fixed the issue that was blocking local executions of the script.
/hold cancel

**Comment by staebler** [comment]
744db7ded...a5907a773
* Rebased to master branch to resolve conflicts with https://github.com/openshift/installer/pull/5716.
* Update the go.mod for the vsphereprivate terraform provider to use v2 of the terraform plugin sdk. This was a required update that was missed in https://github.com/openshift/installer/pull/5716.

**Comment by patrickdillon** [comment]
`verify-vendor` [is failing ](https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_installer/5675/pull-ci-openshift-installer-master-verify-vendor/1506316212341051392/build-log.txt)but the error is not obvious to me:

```
 golang.org/x/xerrors v0.0.0-20200804184101-5ec99f83aff1 h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=
-golang.org/x/xerrors v0.0.0-20200804184101-5ec99f83aff1/go.mod h1:I/5z698sn9Ka8TeJc9MKroUUfqBBauWjQqLJ2OPfmY0=
 google.golang.org/api v0.4.0/go.mod h1:8k5glujaEP+g9n7WNsDg8QP6cUVNI86fCNMcbazEtwE=
 google.golang.org/api v0.7.0/go.mod h1:WtwebWUNSVBH/HAw79HIFXZNqEvBhG+Ra+ax0hx3E3M=
 google.golang.org/api v0.8.0/go.mod h1:o4eAsZoiT+ibD93RtjEohWalFOjRDx6CVaqeizhEnKg=
{"component":"entrypoint","error":"wrapped process failed: exit status 1","file":"k8s.io/test-infra/prow/entrypoint/run.go:80","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2022-03-22T17:15:17Z"} 
[36mINFO[0m[2022-03-22T17:15:21Z] Ran for 8m38s                                
[31mERRO[0m[2022-03-22T17:15:21Z] Some steps failed:                           
[31mERRO[0m[2022-03-22T17:15:21Z] 
  * could not run steps: step verify-vendor failed: test "verify-vendor" failed: the pod ci-op-45nf63v8/verify-vendor failed after 4m37s (failed containers: test): ContainerFailed one or more containers exited

```

/retest

**Comment by staebler** [comment]
> `verify-vendor` [is failing ](https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_installer/5675/pull-ci-openshift-installer-master-verify-vendor/1506316212341051392/build-log.txt)but the error is not obvious to me:

Changes to go.sum from https://github.com/openshift/installer/pull/5719, which did not use the `--compat=1.17` flag for `go mod tidy`.

Resolved in a5907a773...fb18dab8c.

**Pull request merged**
