### PR TITLE
Bug 1796930: [release-4.3] baremetal: make provisioning networks more configurable

### PR DESCRIPTION
**Pull request by stbenjam**
Backport of https://github.com/openshift/installer/pull/2895

This change adds 4 new options to the baremetal platform:

        - ProvisioningNetworkInterface
        - ProvisioningNetworkCIDR
        - ProvisioningDHCPExternal
        - ProvisioningDHCPRange

This makes the provisioning network more configurable, by allowing users
to specify a specific network interface, which network, and settings for
whether the cluster should provide DHCP services on the provisioning
network, or if it will be managed externally. If we will provide DHCP
services on the network, the user may further customize which range to
use.

This change is a prerequisite to a number of additional high-priority
work items for the baremetal IPI platform, including single-stack IPv6
provisioning, external DHCP support, and end-to-end seamless deployment
without a manually created config map.

Co-authored-by: Ian Main <imain@redhat.com>
Co-authored-by: Stephen Benjamin <stephen@redhat.com>

### CODE REVIEW

**Comment by stbenjam** [comment]
/hold

Need to verify what's in the 4.3 ironic containers first

**Comment by stbenjam** [comment]
/close

Not required in 4.3.

**Comment by stbenjam** [comment]
/hold

Actually still valid, need to check ironic containers in 4.3

**Comment by russellb** [comment]
Can you link to the corresponding master PR(s)?

**Comment by stbenjam** [comment]
@russellb I added it to the description, this is a backport of https://github.com/openshift/installer/pull/2895

**Comment by sdodson** [comment]
/approve
Still has a hold on it though, clear that?

**Comment by bparees** [comment]
@stbenjam still held so not currently being considered for cherry pick approval

**Comment by hardys** [comment]
@stbenjam looks like we need to cherry-pick https://github.com/openshift/ironic-image/pull/45 to unblock this?

**Comment by stbenjam** [comment]
Since we are about to get iPXE images for ironic-image, I was going to get that in ironic-image and backport all the IPv6 things together.

**Comment by bparees** [comment]
skipping this one for approval this week anyway due to the number of other changes already accepted.

**Comment by sdodson** [comment]
@stbenjam Are we moving forward with this PR?

**Comment by stbenjam** [comment]
No - this was tightly coupled to the IPv6 work in the ironic-image, and we're not going to split this out. Only in 4.4+ will provisioning networks be configurable.

/close

**Pull request closed without merging**
