### PR TITLE
Azure provider: only validate premiumio when specified in install con…

### PR DESCRIPTION
**Pull request by kwoodson**
…fig.

This PR is to address BZ https://bugzilla.redhat.com/show_bug.cgi?id=2084441.  In order to address API calls that might not include their vm capabilities, I suggest only attempting to validate the capability for `Premium_LRS` when specified in the install config. This gives the ability to attempt best effort validation. If the value is not found in the capability then we create a log message and proceed on with the installation.

### CODE REVIEW

**Review by r4f4 — COMMENTED** [review]
I wonder if we should add unit tests to cover this case

**Comment by kwoodson** [comment]
@MayXuQQ This is my proposal for the fix for the PremiumIO issue. [BZ ](https://bugzilla.redhat.com/show_bug.cgi?id=2084441)

**Comment by MayXuQQ** [comment]
[[IPI on azure]fail to check the vm capabilities in private cluster](https://bugzilla.redhat.com/show_bug.cgi?id=2084441) fixed , check with registry.build01.ci.openshift.org/ci-ln-kn91cg2/release:latest (067098)

**Comment by kwoodson** [comment]
@patrickdillon Mind reviewing? Looks like May has verified this fix. I can update the title for a bz if that helps, thanks.

**Comment by r4f4** [comment]
I completely forgot about this and opened https://github.com/openshift/installer/pull/5924 to solve the same problem :man_facepalming:

**Comment by r4f4** [comment]
> @r4f4 That's fine, should I close this PR?

If that's ok with you. The other one ended up getting the needed labels. Feel free to leave any comments/concerns on #5924

**Pull request closed without merging**
