### PR TITLE
OpenStack: Fix default for openstack_worker_server_group_names

### PR DESCRIPTION
**Pull request by mandre**
A follow-up to https://github.com/openshift/installer/pull/7356.

### CODE REVIEW

**Comment by mandre** [comment]
/hold
Waiting for https://github.com/openshift/release/pull/41564 to be able to test.

**Comment by EmilienM** [comment]
```
{  Downloading current MachineSet for workers
No resources found in openshift-machine-api namespace.
```

https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_installer/7359/pull-ci-openshift-installer-master-e2e-openstack-nfv-intel/1684961780448628736

**Comment by EmilienM** [comment]
/lgtm
/hold cancel
/test okd-images

The error in is [e2e-openstack-nfv-intel](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_installer/7359/pull-ci-openshift-installer-master-e2e-openstack-nfv-intel/1685349431001485312) not related to the PR, and we need this patch anyway.

**Pull request merged**
