### PR TITLE
azure: removes dummy outbound service

### PR DESCRIPTION
**Pull request by m1kola**
This dummy outbound service is no longer needed as VMs for clusters with OutboundType=Loadbalancer will always be added to a public load balancer which has an outbound rule.

Relevant code:

https://github.com/openshift/installer/blob/aba60410f3530cdf18cc73dfe290c2bd546ed357/pkg/asset/machines/azure/machines.go#L99-L131

### CODE REVIEW

**Comment by m1kola** [comment]
Assigning to @staebler for approval.

/assign @staebler

**Review by e-tienne — COMMENTED** [review]
/lgtm

**Comment by m1kola** [comment]
Hey @jhixson74, could you please lgtm this PR again? I had to rebase to fix conflicts.

**Pull request merged**
