### PR TITLE
OCPBUGS-35763: [release-4.13] aws: terraform: add spot instance support for masters

### PR DESCRIPTION
**Pull request by r4f4**
Manual cherry-pick of https://github.com/openshift/installer/pull/8605

### CODE REVIEW

**Review by 2uasimojo — COMMENTED** [review]
/lgtm

**Comment by r4f4** [comment]
/assign @gpei 
for the cherry-pick label

**Comment by r4f4** [comment]
/hold

The terraform-provider-aws version used in 4.13 doesn't support spot options in the `aws_instance` resource.

**Comment by r4f4** [comment]
There is no way to add spot instance support in 4.13 without changing the terraform-provider-aws version and complicating our terraform configs. I don't think it's worth it, so I'm closing this backport.

/close

**Pull request closed without merging**
