### PR TITLE
WIP: Allow masters in Azure LB backend pools

### PR DESCRIPTION
**Pull request by ironcladlou**

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
I don't think we should be setting this in our configuration, I think we turned this on by default for other ks8 cloud providers using the LegacyNodeRoleBehavior feature flag..

And i think we might want to do the same for Azure..  cc @smarterclayton

**Comment by ironcladlou** [comment]
@abhinavdahiya 
>I don't think we should be setting this in our configuration, I think we turned this on by default for other ks8 cloud providers using the LegacyNodeRoleBehavior feature flag..

Can you help me understand how we can avoid setting the cloud provider config given 
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/legacy-cloud-providers/azure/azure_standard.go#L810?

Maybe I'm not clear about what you're proposing.

**Comment by abhinavdahiya** [comment]
> @abhinavdahiya
> 
> > I don't think we should be setting this in our configuration, I think we turned this on by default for other ks8 cloud providers using the LegacyNodeRoleBehavior feature flag..
> 
> Can you help me understand how we can avoid setting the cloud provider config given
> https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/legacy-cloud-providers/azure/azure_standard.go#L810?

that code is specifically for availability set, AFAIK i don't think we use those

> 
> Maybe I'm not clear about what you're proposing.

`LegacyNodeRoleBehavior` when that feature flag is set to false, all cloud provider implementations should put control plane nodes in the LB backend without any extra configuration.

**Comment by ironcladlou** [comment]
@abhinavdahiya 

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/legacy-cloud-providers/azure/azure_loadbalancer.go#L983
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/legacy-cloud-providers/azure/azure_vmss.go#L1048

Is this the right code path?

**Comment by ironcladlou** [comment]
I don't see any cloud provider code honoring LegacyNodeRoleBehavior — I thought the service controller used it to drive the node set fed to the cloud providers, but it sure looks like at least Azure does secondary master-checking unrelated to the feature gate...

**Comment by ironcladlou** [comment]
Are cloud providers supposed to ignore the master label completely when LegacyNodeRoleBehavior is enabled?

**Comment by ironcladlou** [comment]
I think we're going to have to submit an upstream patch to honor LegacyNodeRoleBehavior in the Azure cloud provider code.

**Pull request closed without merging**
