### PR TITLE
Wait for all operators

### PR DESCRIPTION
**Pull request by deads2k**
Bringing back https://github.com/openshift/installer/pull/7289 with a new commit correcting the problem observed in https://github.com/openshift/installer/pull/7318

### CODE REVIEW

**Comment by deads2k** [comment]
many of the payload runs failed with messages like

```
{  configuration has 2 errors:

  * images[2]: duplicate image name 'libvirt-installer' (previously defined by field 'base_images[libvirt-installer]')
  * images[3]: duplicate image name 'upi-installer' (previously defined by field 'base_images[upi-installer]')
}
```

is that normal?

**Comment by r4f4** [comment]
> many of the payload runs failed with messages like
> 
> ```
> {  configuration has 2 errors:
> 
>   * images[2]: duplicate image name 'libvirt-installer' (previously defined by field 'base_images[libvirt-installer]')
>   * images[3]: duplicate image name 'upi-installer' (previously defined by field 'base_images[upi-installer]')
> }
> ```
> 
> is that normal?

It seems the payload job is trying to import installer images but the namespace for this PR already has its own built images. Or something like that. Same thing happened last time when I tried to run payload jobs. I'll report to the testplatform team.

**Comment by deads2k** [comment]
> It seems the payload job is trying to import installer images but the namespace for this PR already has its own built images. Or something like that. Same thing happened last time when I tried to run payload jobs. I'll report to the testplatform team.

Thanks.  That's worth fixing in general, but means we may have to merge based on the data we are able to collect.

**Comment by deads2k** [comment]
closing in favor of https://github.com/openshift/installer/pull/7535

**Pull request closed without merging**
