### PR TITLE
[fcos] add vrutkovs and LorbusChris to owners

### PR DESCRIPTION
**Pull request by vrutkovs**
Removed the rest of the team to avoid unnecessary review requests

### CODE REVIEW

**Comment by patrickdillon** [comment]
maybe you want to add an `fcos-` or `okd-` alias?

**Comment by vrutkovs** [comment]
>maybe you want to add an fcos- or okd- alias?

I don't think a separate group is required really, hopefully this is the last time we fork installer

**Comment by vrutkovs** [comment]
```http://base-4-5.ocp.svc/rhel-fast-datapath-beta/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found```

Hopefully its a flake?

/retest

**Pull request merged**
