### PR TITLE
WiP: Support custom Azure environment installation

### PR DESCRIPTION
**Pull request by cfBrianMiller**
Creating azure environment customization options with the openshift-installer. Added the ability to add the environment variable AZURE_ENVIRONMENT that when set will configure the correct endpoints for the installer to point to.

This is the baseline for future changes that will fully enable custom azure governments.
 
==Known Issues==
This is only targeted at the create install-config command to be used with the UPI azure mag documentation.

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
Few general things,

we only consume credentials using env variables or user's host environment, because those are not technically configuration. and therefore the environment for Azure should be an install-config.yaml configuration.

secondly, since this PR is trying to target UPI only for this configuration, we should add validations to https://github.com/openshift/installer/blob/master/pkg/asset/installconfig/platformprovisioncheck.go such that any non-public environment is not allowed for creating clusters by the installer.

lastly, we do not prefer providing a shell script, rather a walk through of various steps in a document. like https://github.com/openshift/installer/blob/master/docs/user/azure/install_upi.md
- each step should be defined in the document most importantly, but additionaly you can include a script to do that step too.
- the document should never say `run this script`, rather include the script contents in the doc. this provides a much better ux for users
- please try to document all the per-requisites.

**Comment by abhinavdahiya** [comment]
Also if you are interested in driving the conversation of how to get the platform to support this natively,
here is an example of enhancement the is currently driving the aws custom endpoints work https://github.com/openshift/enhancements/blob/master/enhancements/installer/aws-custom-region-and-endpoints.md

**Comment by cfBrianMiller** [comment]
@abhinavdahiya 

I'll pull the changes I made to the go code as the primary target of this branch is to support UPI on Azure Government. It is probably best to submit all the go code required for an environment deployment in one go rather than pieces.
 
As you can tell by the provided shell script the tasks are non-trivial and would make the supporting document very long by including every step, not to mention the shell script makes it easy for users to consume. Is there a middle ground that can be reached here?

I like the enhancement feature, I'll create one a little bit later.

**Comment by abhinavdahiya** [comment]
> Also if you are interested in driving the conversation of how to get the platform to support this natively,
> here is an example of enhancement the is currently driving the aws custom endpoints work https://github.com/openshift/enhancements/blob/master/enhancements/installer/aws-custom-region-and-endpoints.md

https://github.com/openshift/enhancements/pull/321

I created an enhancement that should detail the long term plan for known azure cloud environments like MAG

PTAL @cfBrianMiller

**Comment by abhinavdahiya** [comment]
/close

in favor of https://github.com/openshift/installer/pull/3634

**Pull request closed without merging**
