### PR TITLE
Documentation: update installconfig

### PR DESCRIPTION
**Pull request by abhinavdahiya**
also drops previous work as it confuses people and serves little purpose.

/cc @yifan-gu @wking 
/assign @wking @yifan-gu 

NOTE: switch on `hide whitespaces changes` for better visibility.

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
A lot of PRs (ex: [this](https://github.com/openshift/installer/pull/92/files#diff-db64c23922de1e4f6076ff9bcfe918ebL263)) try to sync previous work to match this doc, which was not its purpose. @crawford suggested we don't need this section.

**Comment by wking** [comment]
Needs a rebase with #188 landed, but otherwise looks good to me :).

**Comment by abhinavdahiya** [comment]
@wking rebased against master. PTAL.

**Pull request merged**
