### PR TITLE
WIP: pass sshKey to ironic

### PR DESCRIPTION
**Pull request by derekhiggins**
Use the ssh key from install-config to allow ssh to
running IPA instances.

### CODE REVIEW

**Comment by hardys** [comment]
nice, this could certainly make debugging IPA issues easier :)

**Comment by dhellmann** [comment]
Is there some way to do this for day 2 deployments, too?

**Comment by derekhiggins** [comment]
> Is there some way to do this for day 2 deployments, too?

For worker deployments? If the machine-api-operator has access to the ssh-key we could add it.

**Comment by abhinavdahiya** [comment]
Closing this as it has stalled for very long. Please feel free to re-open in case you intent to keep working on it, or consider tracking the work in an issue if this requires agreement for implementation.

/close

**Pull request closed without merging**
