### PR TITLE
pkg/asset/installconfig/aws: Ask for AWS access key and secret

### PR DESCRIPTION
**Pull request by wking**
Builds on #688; review that first.

For folks who forgot to setup `~/.aws/credentials` before calling the installer.  Now we'll give them a nice prompt and a link into the AWS docs instead of dying.  I'm also saving any provided creds into the usual location for later AWS access during this and future installer runs.

### CODE REVIEW

**Comment by crawford** [comment]
The unique commit in this PR looks good to me. Waiting on #688.

**Comment by wking** [comment]
I've pushed 3359da54a -> 4aee1144d, rebasing onto master so GitHub just shows the one commit.

**Comment by wking** [comment]
[e2e-aws][1]:

```
error: unable to connect to image repository registry.svc.ci.openshift.org/ci-op-5hbh92jn/stable@sha256:5eb1e9b2c4c0e4b7c2beda1372a039c44db4b694f567b91ccaf44df1a16cc6aa: Get https://registry.svc.ci.openshift.org/v2/: net/http: request canceled (Client.Timeout exceeded while awaiting headers) 
```

/retest

[1]: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_installer/798/pull-ci-openshift-installer-master-e2e-aws/1976/build-log.txt

**Comment by wking** [comment]
Three [e2e-aws][1] errors:

```
fail [github.com/openshift/origin/test/extended/builds/labels.go:59]: Expected
    <bool>: false
to be true

....
failed: (1m47s) 2018-12-06T05:03:58 "[Feature:Builds][Smoke] result image should have proper labels set  S2I build from a template should create a image from \"test-s2i-build.json\" template with proper Docker labels [Suite:openshift/conformance/parallel] [Suite:openshift/smoke-4]"
```

```
fail [github.com/openshift/origin/test/extended/builds/labels.go:87]: Expected
    <bool>: false
to be true

...
failed: (1m57s) 2018-12-06T05:04:08 "[Feature:Builds][Smoke] result image should have proper labels set  Docker build from a template should create a image from \"test-docker-build.json\" template with proper Docker labels [Suite:openshift/conformance/parallel] [Suite:openshift/smoke-4]"
```

and:

```
fail [github.com/openshift/origin/test/extended/builds/new_app.go:63]: Expected error:
    <*errors.errorString | 0xc420590340>: {
        s: "The build \"a234567890123456789012345678901234567890123456789012345678-1\" status is \"Failed\"",
    }
    The build "a234567890123456789012345678901234567890123456789012345678-1" status is "Failed"
not to have occurred

...
failed: (2m4s) 2018-12-06T05:12:02 "[Feature:Builds][Conformance] oc new-app  should succeed with a --name of 58 characters [Suite:openshift/conformance/parallel/minimal] [Suite:openshift/smoke-4]"
```

/retest

[1]: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_installer/798/pull-ci-openshift-installer-master-e2e-aws/1977/build-log.txt

**Comment by wking** [comment]
Hrm, [same failures][1] as last time:

```

Failing tests:

[Feature:Builds][Conformance] oc new-app  should succeed with a --name of 58 characters [Suite:openshift/conformance/parallel/minimal] [Suite:openshift/smoke-4]
[Feature:Builds][Smoke] result image should have proper labels set  Docker build from a template should create a image from "test-docker-build.json" template with proper Docker labels [Suite:openshift/conformance/parallel] [Suite:openshift/smoke-4]
[Feature:Builds][Smoke] result image should have proper labels set  S2I build from a template should create a image from "test-s2i-build.json" template with proper Docker labels [Suite:openshift/conformance/parallel] [Suite:openshift/smoke-4]
```

/retest

[1]: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_installer/798/pull-ci-openshift-installer-master-e2e-aws/1978/build-log.txt

**Comment by crawford** [comment]
```
E1206 07:28:33.675471     398 streamwatcher.go:109] Unable to decode an event from the watch stream: http2: server sent GOAWAY and closed the connection; LastStreamID=5, ErrCode=NO_ERROR, debug=""
error: watch closed before Until timeout
error openshift-ingress/deploy/router-default did not come up
Waiting for deployment "router-default" rollout to finish: 0 of 1 updated replicas are available...
E1206 07:31:08.615712     417 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
error: watch closed before Until timeout
error openshift-ingress/deploy/router-default did not come up
sleep: invalid option -- '3'
Try 'sleep --help' for more information.
2018/12/06 07:31:09 Container test in pod e2e-aws failed, exit code 1, reason Error
```

/retest

**Comment by wking** [comment]
>     sleep: invalid option -- '3'

openshift/release#2321

**Comment by jeremyeder** [comment]
Here are my notes and the logs that you requested on slack:
https://gist.github.com/jeremyeder/041b1414711a6442775d494144f08ad7

**Pull request merged**
