### PR TITLE
CORS-2785: images: decouple installer and installer-artifacts

### PR DESCRIPTION
**Pull request by r4f4**
The installer-artifacts image depends on the installer image, which means they cannot be built in parallel. The effect of this dependency is that the installer-artifacts image contains the linux amd64 builds in addition to the mac/linux amd64/arm64 builds present in the installer-artifacts image.

Breaking the dependency results in a more efficient build process because they can be built in parallel as well as no duplication of the linux amd64 binary in the release image (before this change the binary would be present in both images within the release image).

The risk, though, is that clients are inconsistently grabbing the linux amd64 binary from either image, rather than only the installer image, in which case we would break any client trying to get that binary from the installer-artifacts image.

### CODE REVIEW

**Comment by r4f4** [comment]
Reopening https://github.com/openshift/installer/pull/7159 with commits squashed and conflicts resolved.

**Comment by patrickdillon** [comment]
It looks like we would need to update `oc` to extract the linux amd64 binary from the installer image:
https://github.com/openshift/oc/blob/d76174f58c86b2ad27f99f3ebdb3eaa5c945256a/pkg/cli/admin/release/extract_tools.go#L327-L338

**Comment by r4f4** [comment]
> It looks like we would need to update `oc` to extract the linux amd64 binary from the installer image:
> 
> https://github.com/openshift/oc/blob/d76174f58c86b2ad27f99f3ebdb3eaa5c945256a/pkg/cli/admin/release/extract_tools.go#L327-L338

@patrickdillon I thought you had already determined that `oc` is fine? https://github.com/openshift/installer/pull/7159#issuecomment-1533278539

**Comment by r4f4** [comment]
@patrickdillon What about https://github.com/openshift/oc/pull/1608 ?

**Comment by patrickdillon** [comment]
> It looks like we would need to update `oc` to extract the linux amd64 binary from the installer image:
> 
> https://github.com/openshift/oc/blob/d76174f58c86b2ad27f99f3ebdb3eaa5c945256a/pkg/cli/admin/release/extract_tools.go#L327-L338

> > It looks like we would need to update `oc` to extract the linux amd64 binary from the installer image:
> > https://github.com/openshift/oc/blob/d76174f58c86b2ad27f99f3ebdb3eaa5c945256a/pkg/cli/admin/release/extract_tools.go#L327-L338
> 
> @patrickdillon I thought you had already determined that `oc` is fine? [#7159 (comment)](https://github.com/openshift/installer/pull/7159#issuecomment-1533278539)


After rereading I see that my initial comments misunderstood what was happening as a result of this PR. I misunderstood and thought that we would only have linux amd64 in the `installer` image, which is incorrect: linux amd64 will still be in `installer-artifacts` as well.

> @patrickdillon What about [openshift/oc#1608](https://github.com/openshift/oc/pull/1608) ?

I believe my original comment was based on a misunderstanding so do we still need it? If we don't, I'd rather leave it alone.

Sorry for the confusion.

**Comment by r4f4** [comment]
> > @patrickdillon What about [openshift/oc#1608](https://github.com/openshift/oc/pull/1608) ?
> 
> I believe my original comment was based on a misunderstanding so do we still need it? If we don't, I'd rather leave it alone.

I think with that PR we can build only `installer-artifacts` for the release payload, no need for `installer`. At least I fail to see for what else would we need `installer`.

**Comment by patrickdillon** [comment]
> > > @patrickdillon What about [openshift/oc#1608](https://github.com/openshift/oc/pull/1608) ?
> > 
> > 
> > I believe my original comment was based on a misunderstanding so do we still need it? If we don't, I'd rather leave it alone.
> 
> I think with that PR we can build only `installer-artifacts` for the release payload, no need for `installer`. At least I fail to see for what else would we need `installer`.

Interesting idea. I think we need these coreos manifests as well, but that would be it: https://github.com/openshift/installer/blob/master/images/installer/Dockerfile.ci#L9

**Comment by patrickdillon** [comment]
Well, and we would need to update whatever clients depend on those coreos manifests

**Comment by r4f4** [comment]
> > > > @patrickdillon What about [openshift/oc#1608](https://github.com/openshift/oc/pull/1608) ?
> > > 
> > > 
> > > I believe my original comment was based on a misunderstanding so do we still need it? If we don't, I'd rather leave it alone.
> > 
> > 
> > I think with that PR we can build only `installer-artifacts` for the release payload, no need for `installer`. At least I fail to see for what else would we need `installer`.
> 
> Interesting idea. I think we need these coreos manifests as well, but that would be it: https://github.com/openshift/installer/blob/master/images/installer/Dockerfile.ci#L9

I've added https://github.com/openshift/installer/pull/7782/commits/bdd396425c167a2fbc9b314a85df593236f9c6bc so now `installer-artifacts` also contains the manifests. That way we can build artifacts independently without breaking any workflow looking for them.

**Comment by r4f4** [comment]
@patrickdillon I've decided to drop the idea of changing `oc` for now. I think just not having `installer-artifacts` depend on the `installer` image is enough for now. It shouldn't break anything since `oc` will still be able to grab the `openshift-installer` binary either from the `installer-artifacts` or the `installer` image. The only difference is that the images can be built in parallel both in CI and during release. WDYT?

**Comment by patrickdillon** [comment]
>I've added https://github.com/openshift/installer/commit/bdd396425c167a2fbc9b314a85df593236f9c6bc so now installer-artifacts also contains the manifests. That way we can build artifacts independently without breaking any workflow looking for them.

Did you drop this commit from the PR? 

IIUC, prior to this PR the coreos manifests are included in installer-artifacts because we are using installer as a base image. With the changes in this PR, the installer-artifacts PR would no longer include those manifests. 

I'm not sure exactly how the manifests are used, but I think it's safer to continue to include them in the image.

**Comment by r4f4** [comment]
> > I've added [bdd3964](https://github.com/openshift/installer/commit/bdd396425c167a2fbc9b314a85df593236f9c6bc) so now installer-artifacts also contains the manifests. That way we can build artifacts independently without breaking any workflow looking for them.
> 
> Did you drop this commit from the PR?
> 
> IIUC, prior to this PR the coreos manifests are included in installer-artifacts because we are using installer as a base image. With the changes in this PR, the installer-artifacts PR would no longer include those manifests.
> 
> I'm not sure exactly how the manifests are used, but I think it's safer to continue to include them in the image.

@patrickdillon I somehow misunderstood the manifests were being consumed from the `installer` image. I've brought the commit back.

**Pull request merged**
