### PR TITLE
Bug 1836098: add a delay before creating API floating IP.

### PR DESCRIPTION
**Pull request by Fedosin**
This commits adds an artificial delay to prevent race conditions in overloaded Neutron.
Despite the fact the service says the port was created and returns its ID, when we try to assotiate a floating IP with this port, it may return 404.

### CODE REVIEW

**Comment by mandre** [comment]
/hold
How is it different from https://github.com/openshift/installer/pull/2868? My comment at https://github.com/openshift/installer/pull/2868#issuecomment-571498883 still holds, I'd like to avoid hacky workarounds. The only way to eradicate this class of failures is to make the openstack terraform provider more resilient.

**Comment by Fedosin** [comment]
@mandre there we have vague dependencies between resources and can't guarantee the delay time. Here it's more clear and predictable. If you want, I can add a TODO to remove this part, when the bug is fixed in Neutron.

**Pull request closed without merging**
