### PR TITLE
OSASINFRA-3237: move controlPlanePort API to GA

### PR DESCRIPTION
**Pull request by MaysaMacedo**
This API has not moved and there is no plan to make any changes that would be backward incompatible in the future.

### CODE REVIEW

**Comment by MaysaMacedo** [comment]
/hold
waiting for some initial ack from QE

**Comment by MaysaMacedo** [comment]
/cc @rlobillo  @itzikb-redhat 
hey guys, when you see we can mark the API related to dual-stack as GA, can you ack on this PR?

**Review by barbacbd — COMMENTED** [review]
/approve

**Pull request merged**
