### PR TITLE
CORS-3294: CAPA health check configuration for control plane ELBv2

### PR DESCRIPTION
**Pull request by mtulio**
This PR implements in CAPA the target health check attributes used in Terraform for API[1] and MCS[2].

Upstream tracking PR (blocker): https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4849

[1] Kube API listener's target health check configuration on Terraform:
https://github.com/openshift/installer/blob/b4e19a04f7298cb1b65c78672d7f862772dc778b/data/data/aws/cluster/vpc/master-elb.tf#L85-L94

[2] Machine Config Server listener's target health check configuration on Terraform:
https://github.com/openshift/installer/blob/b4e19a04f7298cb1b65c78672d7f862772dc778b/data/data/aws/cluster/vpc/master-elb.tf#L139-L147

### CODE REVIEW

**Comment by mtulio** [comment]
@r4f4 @patrickdillon PTAL in the change [pkg/asset/manifests/aws/cluster.go](https://github.com/openshift/installer/pull/8223/files#diff-7a97ca0145cd8d7695349f7651c313441a31342441d03ee93da15220e81ca530) ?

**Review by r4f4 — COMMENTED** [review]
> @r4f4 @patrickdillon PTAL in the change [pkg/asset/manifests/aws/cluster.go](https://github.com/openshift/installer/pull/8223/files#diff-7a97ca0145cd8d7695349f7651c313441a31342441d03ee93da15220e81ca530) ?
Values are consistent with what we do in terraform, so LGTM.

**Comment by mtulio** [comment]
Local tests are passing with custom health check attributes:

- API
Screenshot from 2024-04-24 13-31-18

- MCS
Screenshot from 2024-04-24 13-31-25

Keeping on-old until https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4948 is merged and vendor updated to `main`.

cc @r4f4 @nrb @damdo

**Comment by mtulio** [comment]
This PR is ready for review. The CAPA vendor is mapping to current main branch including the fixes, LB health check attributes and Local Zones.
/assign @r4f4 @patrickdillon

**Comment by mtulio** [comment]
Missing CAPA vendoring.
/hold

**Comment by mtulio** [comment]
Not getting issues running `hack/go-lint.sh` locally:

/test golint
/test altinfra-e2e-aws-ovn

**Review by r4f4 — COMMENTED** [review]
/approve

**Pull request merged**
