### PR TITLE
CORS-3617: Make Azure CAPI the default (& only) install option

### PR DESCRIPTION
**Pull request by sadasu**
Depends on https://github.com/openshift/api/pull/1987

### CODE REVIEW

**Comment by r4f4** [comment]
Since we're making capi/azure the only choice, we can also remove `terraform/providers/azurerm` which will bring us compile time savings both in CI and in the release pipeline.

**Comment by sadasu** [comment]
> Since we're making capi/azure the only choice, we can also remove `terraform/providers/azurerm` which will bring us compile time savings both in CI and in the release pipeline.

That is already handled by https://github.com/openshift/installer/pull/8764. Didn't want to step on that.

**Review by r4f4 — COMMENTED** [review]
/lgtm

**Pull request merged**
