### PR TITLE
OCPBUGS-30860: bootstrap: hit readyz when checking LB status

### PR DESCRIPTION
**Pull request by vrutkovs**
Improve API server readiness before leaving bootstrap

### CODE REVIEW

**Review by sadasu — COMMENTED** [review]
Waiting for shellcheck to pass.

**Comment by sadasu** [comment]
/label acknowledge-critical-fixes-only

We would benefit from having this fix now.

**Comment by patrickdillon** [comment]
/hold

I think we're preferring the approach in https://github.com/openshift/installer/pull/8404 over this

**Comment by patrickdillon** [comment]
Change seems simple enough no reason to wait 

/hold cancel
/lgtm

**Comment by sadasu** [comment]
/override ci/prow/okd-images

Known issue

**Comment by sadasu** [comment]
//hold cancel

**Pull request merged**
