### PR TITLE
Repin libvirt-version

### PR DESCRIPTION
**Pull request by elfosardo**
Also use a shared ARG to keep it consistent between stages

This should fix the downstream build pipeline

### CODE REVIEW

**Comment by elfosardo** [comment]
/cc @sosiouxme @joepvd
Luke pinned it in the past for the same reason

**Comment by elfosardo** [comment]
/hold
backward compatibility under discussion

**Comment by hardys** [comment]
/lgtm

We need this to unblock CI - we will have to address the issue of backwards compatibility afterwards prior to GA, since we probably can't expect users to have a beta RHEL version in the baremetal IPI flow

**Comment by stbenjam** [comment]
Prow seems to be ignoring me.

/test ci/prow/e2e-metal-ipi-ovn-ipv6-required

**Comment by deads2k** [comment]
I think I understand what happened.  Updating base images to 8.6 (not this repo), broke this, so we need to unstick it.

**Comment by hardys** [comment]
> I think I understand what happened. Updating base images to 8.6 (not this repo), broke this, so we need to unstick it.

Yes that's my understanding too - but if we can make the GA libvirt version available for upstream and downstream builds ref https://github.com/openshift/ocp-build-data/pull/1508 this can potentially be reverted in future (which may be preferable prior to GA as we probably don't want to require users to install a beta RHEL version when using the baremetal IPI installer)

**Pull request merged**
