### PR TITLE
[fcos] Fix unavailable forked deps and update vendor

### PR DESCRIPTION
**Pull request by LorbusChris**
/assign @vrutkovs

### CODE REVIEW

**Comment by rarguello** [comment]
That branch doesn't build either:

go: github.com/openshift/machine-config-operator@v4.2.0-alpha.0.0.20190917115525-033375cbe820+incompatible requires
	golang.org/x/tools@v0.0.0-20191002234911-9ade4c73f2af: invalid version: unknown revision 9ade4c73f2af

**Comment by vrutkovs** [comment]
/lgtm

>go: github.com/openshift/machine-config-operator@v4.2.0-alpha.0.0.20190917115525-033375cbe820+incompatible requires
golang.org/x/tools@v0.0.0-20191002234911-9ade4c73f2af: invalid version: unknown revision 9ade4c73f2af

That's not related to this PR

**Pull request merged**
