### PR TITLE
Bug 2029409: Update defaultReleaseImageOriginal to 4.9

### PR DESCRIPTION
**Pull request by LorbusChris**

### CODE REVIEW

**Comment by LorbusChris** [comment]
@staebler this only affects 4.9, in master/4.10 the default version has been updated correctly. Not sure how to proceed here with the missing BZ dependency
/bugzilla refresh

**Review by staebler — COMMENTED** [review]
/lgtm
/approve
/label backport-risk-assessed

**Comment by staebler** [comment]
@gpei Please review to add cherry-pick-approved. This change does not affect any OCP releases as the release image is set explicitly as part of the release build process.

**Pull request merged**
