### PR TITLE
quota: gcp: replace deprecated monitoring package and fix linting issues

### PR DESCRIPTION
**Pull request by r4f4**
"cloud.google.com/go/monitoring/apiv3" is deprecated. We should use "cloud.google.com/go/monitoring/apiv3/v2" instead.

### CODE REVIEW

**Comment by r4f4** [comment]
Updated to fix one more typo: `ans` -> `and`.

**Review by barbacbd — COMMENTED** [review]
/lgtm

**Comment by r4f4** [comment]
Rebased to fix merge conflicts.

**Review by barbacbd — COMMENTED** [review]
/lgtm

**Pull request merged**
