### PR TITLE
Set cluster timeout to 60 and allow further customization

### LINKED ISSUE #1428: [libvirt] Default time for 30m for the cluster to initialize not enough
# Version

```console
$ openshift-install version
openshift-install unreleased-master-569-g660f2bbf74431775c0677449bc5487572b069d26
built from commit 660f2bbf74431775c0677449bc5487572b069d26
```

# Platform (aws|libvirt|openstack):

libvirt

# What happened?

Cluster initialisation time out after 30m and cluster is taking around 45-50 mins to become healthy in libvirt provider.

# What you expected to happen?

Cluster should have taken 30 mins only for libvirt also like it is taking for aws.

# How to reproduce it (as minimally and precisely as possible)?

```console
$ openshift-install create cluster
[...]
level=info msg="Waiting up to 30m0s for the cluster at https://api.test1.openshift.testing:6443 to initialize..."
level=debug msg="Still waiting for the cluster to initialize..."
level=debug msg="Still waiting for the cluster to initialize..."
level=debug msg="Still waiting for the cluster to initialize..."
level=debug msg="Still waiting for the cluster to initialize..."
level=debug msg="Still waiting for the cluster to initialize..."
level=debug msg="Still waiting for the cluster to initialize..."
level=debug msg="Still waiting for the cluster to initialize..."
level=debug msg="Still waiting for the cluster to initialize..."
level=debug msg="Still waiting for the cluster to initialize..."
level=debug msg="Still waiting for the cluster to initialize..."
level=debug msg="Still waiting for the cluster to initialize..."
level=debug msg="Still waiting for the cluster to initialize: Could not update servicemonitor \"openshift-kube-scheduler-operator/kube-scheduler-operator\" (299 of 306): the server does not recognize this resource, check extension API servers"
level=debug msg="Still waiting for the cluster to initialize..."
level=debug msg="Still waiting for the cluster to initialize..."
level=fatal msg="failed to initialize the cluster: timed out waiting for the condition"

$ oc get co
NAME                                  VERSION                           AVAILABLE   PROGRESSING   FAILING   SINCE
authentication                        4.0.0-0.alpha-2019-03-17-071624   True        False         False     112s
cluster-autoscaler                    4.0.0-0.alpha-2019-03-17-071624   True        False         False     2m3s
console                               4.0.0-0.alpha-2019-03-17-071624   True        False         False     116s
dns                                   4.0.0-0.alpha-2019-03-17-071624   True        False         False     63m
image-registry                        4.0.0-0.alpha-2019-03-17-071624   True        False         False     55m
ingress                               4.0.0-0.alpha-2019-03-17-071624   True        False         False     54m
kube-apiserver                        4.0.0-0.alpha-2019-03-17-071624   True        True          True      106s
kube-controller-manager               4.0.0-0.alpha-2019-03-17-071624   True        False         False     109s
kube-scheduler                        4.0.0-0.alpha-2019-03-17-071624   True        False         False     109s
machine-api                           4.0.0-0.alpha-2019-03-17-071624   True        False         False     64m
machine-config                        4.0.0-0.alpha-2019-03-17-071624   True        False         False     63m
marketplace-operator                  4.0.0-0.alpha-2019-03-17-071624   True        False         False     58m
monitoring                            4.0.0-0.alpha-2019-03-17-071624   True        False         False     12m
network                               4.0.0-0.alpha-2019-03-17-071624   True        True          False     64m
node-tuning                           4.0.0-0.alpha-2019-03-17-071624   True        False         False     58m
openshift-apiserver                   4.0.0-0.alpha-2019-03-17-071624   True        False         False     7m48s
openshift-cloud-credential-operator   4.0.0-0.alpha-2019-03-17-071624   True        False         False     62m
openshift-controller-manager          4.0.0-0.alpha-2019-03-17-071624   True        False         False     116s
openshift-samples                     4.0.0-0.alpha-2019-03-17-071624   True        False         False     53m
operator-lifecycle-manager            4.0.0-0.alpha-2019-03-17-071624   True        False         False     64m
service-ca                                                              True        False         False     99s
service-catalog-apiserver             4.0.0-0.alpha-2019-03-17-071624   True        False         False     105s
service-catalog-controller-manager    4.0.0-0.alpha-2019-03-17-071624   True        False         False     111s
storage                                                                 True        False         False     54m

$ oc logs kube-apiserver-operator-7d7b576bd6-xbtrh -n openshift-kube-apiserver-operator
E0318 06:42:28.447175       1 reflector.go:134] github.com/openshift/client-go/config/informers/externalversions/factory.go:101: Failed to list *v1.Network: Get https://172.30.0.1:443/apis/config.openshift.io/v1/networks?limit=500&resourceVersion=0: dial tcp 172.30.0.1:443: connect: connection refused
E0318 06:42:28.447380       1 reflector.go:134] github.com/openshift/client-go/config/informers/externalversions/factory.go:101: Failed to list *v1.Infrastructure: Get https://172.30.0.1:443/apis/config.openshift.io/v1/infrastructures?limit=500&resourceVersion=0: dial tcp 172.30.0.1:443: connect: connection refused
E0318 06:42:28.474647       1 reflector.go:134] k8s.io/client-go/informers/factory.go:131: Failed to list *v1.ServiceAccount: Get https://172.30.0.1:443/api/v1/namespaces/openshift-kube-apiserver/serviceaccounts?limit=500&resourceVersion=0: dial tcp 172.30.0.1:443: connect: connection refused
E0318 06:42:35.703268       1 event.go:259] Could not construct reference to: '&v1.ConfigMap{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, Data:map[string]string(nil), BinaryData:map[string][]uint8(nil)}' due to: 'selfLink was empty, can't make reference'. Will not report event: 'Normal' 'LeaderElection' 'e320aa8f-4948-11e9-9b3e-0a580a80000d stopped leading'
I0318 06:42:35.703428       1 leaderelection.go:249] failed to renew lease openshift-kube-apiserver-operator/kube-apiserver-operator-lock: failed to tryAcquireOrRenew context deadline exceeded
F0318 06:42:35.703502       1 leaderelection.go:65] leaderelection lost
I0318 06:42:35.758575       1 backing_resource_controller.go:155] Shutting down BackingResourceController
I0318 06:42:35.758751       1 client_cert_rotation_controller.go:168] Shutting down CertRotationController - "KubeSchedulerClient"
I0318 06:42:35.758769       1 client_cert_rotation_controller.go:168] Shutting down CertRotationController - "KubeControllerManagerClient"
I0318 06:42:35.758793       1 client_cert_rotation_controller.go:168] Shutting down CertRotationController - "ServiceNetworkServing"
I0318 06:42:35.758805       1 client_cert_rotation_controller.go:168] Shutting down CertRotationController - "LocalhostServing"
I0318 06:42:35.758817       1 client_cert_rotation_controller.go:168] Shutting down CertRotationController - "AggregatorProxyClientCert"
I0318 06:42:35.758827       1 client_cert_rotation_controller.go:168] Shutting down CertRotationController - "LoadBalancerServing"
I0318 06:42:35.758840       1 client_cert_rotation_controller.go:168] Shutting down CertRotationController - "KubeAPIServerCertSyncer"
I0318 06:42:35.758850       1 resourcesync_controller.go:211] Shutting down ResourceSyncController
I0318 06:42:35.758885       1 monitoring_resource_controller.go:163] Shutting down MonitoringResourceController
I0318 06:42:35.758893       1 config_observer_controller.go:159] Shutting down ConfigObserver
I0318 06:42:35.758902       1 unsupportedconfigoverrides_controller.go:164] Shutting down UnsupportedConfigOverridesController
I0318 06:42:35.758911       1 node_controller.go:133] Shutting down NodeController
I0318 06:42:35.759139       1 targetconfigcontroller.go:317] Shutting down TargetConfigController
I0318 06:42:35.759149       1 prune_controller.go:288] Shutting down PruneController
I0318 06:42:35.759156       1 staticpodstate_controller.go:178] Shutting down StaticPodStateController
I0318 06:42:35.759163       1 installer_controller.go:742] Shutting down InstallerController
I0318 06:42:35.759172       1 revision_controller.go:296] Shutting down RevisionController
I0318 06:42:35.759400       1 status_controller.go:189] Shutting down StatusSyncer-kube-apiserver
F0318 06:42:35.759664       1 builder.go:240] stopped

$ oc get pods --all-namespaces | grep -i crash
openshift-authentication-operator                       openshift-authentication-operator-5cdb858474-mscb8                0/1     CrashLoopBackOff   11         63m
openshift-console-operator                              console-operator-6969dc4d65-plgbj                                 0/1     CrashLoopBackOff   11         63m
openshift-controller-manager-operator                   openshift-controller-manager-operator-d54df77d7-9bw5t             0/1     CrashLoopBackOff   14         68m
openshift-controller-manager                            controller-manager-wgd5x                                          0/1     CrashLoopBackOff   9          59m
openshift-kube-apiserver-operator                       kube-apiserver-operator-7d7b576bd6-xbtrh                          0/1     CrashLoopBackOff   14         68m
openshift-kube-controller-manager-operator              kube-controller-manager-operator-7fd685cf44-7v7rb                 0/1     CrashLoopBackOff   14         68m
openshift-machine-api                                   cluster-autoscaler-operator-5dfb8c9c49-wpxrw                      0/1     CrashLoopBackOff   13         68m
openshift-sdn                                           sdn-controller-t5q9b                                              0/1     CrashLoopBackOff   13         68m
openshift-service-ca-operator                           openshift-service-ca-operator-7b56d9576d-vhfvd                    0/1     CrashLoopBackOff   13         68m
openshift-service-ca                                    apiservice-cabundle-injector-5f4598456-vmkgn                      0/1     CrashLoopBackOff   13         67m
openshift-service-ca                                    configmap-cabundle-injector-6db5fd6746-6dr8h                      0/1     CrashLoopBackOff   13         67m
openshift-service-ca                                    service-serving-cert-signer-7f54646c5-znlst                       0/1     CrashLoopBackOff   13         67m
openshift-service-catalog-controller-manager-operator   openshift-service-catalog-controller-manager-operator-596b4mphw   0/1     CrashLoopBackOff   11         63m

```

### PR DESCRIPTION
**Pull request by stbenjam**
We frequently see issues where 30m isn't enough for the cluster to come
up. Waiting another 10-15 minutes would probaly resolve the issue for
us. This bumps the cluster timeout to 60, and lets users override all
timeouts with environment variables.

Fixes #1428

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
the installer should finish in 30 mins. please point us to BZs with failures that do not finish in 30 mins

/close

**Comment by stbenjam** [comment]
@abhinavdahiya See #1428, the issue linked to this ver yPR.  As well as https://github.com/openshift-metalkube/dev-scripts/pull/308.  We would prefer not to have a solution in our installer fork.  What's the objection to making the timeout at least configurable, even if you object to the 60m increase?

**Comment by wking** [comment]
> See #1428, the issue linked to this very PR.

There are many possible reasons for slow clusters.  Network speed is one.  Broken components that spend time flapping is another.  We want to make sure the latter turns up in CI so we can fix it.

> What's the objection to making the timeout at least configurable, even if you object to the 60m increase?

If the installer times out, you can use other subcommands to manually finish up (see #1552 renaming some of them).  Since there is no time that will never result in false-negatives, I think robust clients will need to be making their own calls about if/when to retry or give up based on more information than just elapsed wall time.  Just bumping the timeout to 60m will make for a poor experience for folks whose cluster is actually broken and never going to come up.

**Comment by hardys** [comment]
> There are many possible reasons for slow clusters. Network speed is one.

We can possibly optimize in the metalkube CI by caching container images, does the openshift installer CI do that, and if so can anyone please point to how it's configured?

I know it's easy to configure a docker-distribution registry as a pull-through cache, but I've not been able to figure out how we can do that with a local quay instance, maybe a squid proxy would be enough?

I think network performance is part of the problem in the metalkube case, as well as running in VMs on a relatively resource-constrained environment, and both are probably common for developer/CI usage (and also for baremetal environments where you may want to deploy $many nodes in parallel and you won't have infinite bandwidth to download everything from the internet)

**Pull request closed without merging**
