### PR TITLE
OCPBUGS-33890: SPLAT-1469: Remove vsphere terraform

### PR DESCRIPTION
**Pull request by jcpowermac**
This PR:
- Removes all vSphere terraform providers
- Removes all vSphere-specific terraform project files
- Modifies vsphere-specific installer terraform stages and asset generation.

### CODE REVIEW

**Comment by jcpowermac** [comment]
@r4f4 since time is short can you take a look and see if this seems sane? 

Since this PR will break periodics we can't actually merge this until capi is built by default.

**Comment by r4f4** [comment]
LGTM. I'll tag when we're closer to merging it.

**Comment by r4f4** [comment]
@jcpowermac sorry for the delay on getting back to you on this.
I don't have access to a vcenter, so I couldn't test it with vsphere. Instead, I did the same to AWS. Here's what I suggest:
1. On `pkg/asset/cluster/tfvars/tfvars.go` you go back to what you had before with `return nil`
2. On `pkg/infrastructure/platform/platform.go` you change the line:
```diff
-               return terraform.InitializeProvider(vsphere.PlatformStages), nil
+               return nil, fmt.Errorf("installing on vSphere via terraform is no longer supported")
```
3. As a bonus of 2), you can now remove `pkg/terraform/stages/vsphere`

This is what I can with the above changes for AWS:
```
 ./openshift-install create cluster
INFO Credentials loaded from the "default" profile in file "/run/secrets/aws_credentials"
INFO Creating infrastructure resources...
FATAL failed to fetch Cluster: failed to generate asset "Cluster": error getting infrastructure provider: installing on AWS via terraform is no longer supported
```
and the capi install works as expected.

In the end I think none of this will matter because capi-vsphere will be the default path and there will be no way to trigger the tf path.

**Comment by jcpowermac** [comment]
/test altinfra-e2e-vsphere-capi-ovn

> @jcpowermac sorry for the delay on getting back to you on this. 

no worries, thanks for sending suggestions!

**Comment by jcpowermac** [comment]
:wave: buh bye terraform

**Comment by sadasu** [comment]
> /override ci/prow/shellcheck

shellcheck was failing due to:
`./docs/user/agent/add-node/node-joiner-monitor.sh:10:13: warning: Assigning an array to a string! Assign as array, or use * instead of @ to concatenate. [SC2124]`
which is unrelated to these changes.

**Comment by jcpowermac** [comment]
@sadasu @patrickdillon can we override okd-images?

**Comment by jcpowermac** [comment]
its going to work this time right? :crossed_fingers: 
/cherrypick release-4.16

**Pull request merged**
