### PR TITLE
[release-4.15] OCPBUGS-33402, OCPBUGS-33354: Fix ISO boot on IBM Z

### PR DESCRIPTION
**Pull request by Neeraj8418**
Updated assisted-image-service version to pickup latest ISO changes from 4.16 to enable on IBMZ.
Picked ISO boot changes from this PR (https://github.com/openshift/installer/pull/8205).

### CODE REVIEW

**Comment by phani2898** [comment]
Hey @zaneb  

All the required tests are successful with the changes, Can you please review and provide labels if there are no other changes required from our end ?

**Review by djslavens — APPROVED** [review]
/lgtm

**Comment by zaneb** [comment]
I'm not able to easily to review this because of the number of commits here, many of which include merge conflict markers.
There are 3 commits named "Update to latest assisted-image-service".
There are 2 commits named "Remove prometheus client replace directive".
One of the "Update to latest assisted-image-service" commits contains the full text of the commit message from the cherry-picked "Remove prometheus client replace directive".
There is a merge commit.
There are 3 changes to pushclient.go, flip-flopping between 2 different versions (unsynchronised with the actual module changes).

Nobody looking at the history in the future is going to be able to understand what was going on, and I am struggling now.

Please force-push with a branch that starts at the latest `release-4.15` and contains only the commits needed.

**Comment by Neeraj8418** [comment]
> I'm not able to easily to review this because of the number of commits here, many of which include merge conflict markers. There are 3 commits named "Update to latest assisted-image-service". There are 2 commits named "Remove prometheus client replace directive". One of the "Update to latest assisted-image-service" commits contains the full text of the commit message from the cherry-picked "Remove prometheus client replace directive". There is a merge commit. There are 3 changes to pushclient.go, flip-flopping between 2 different versions (unsynchronised with the actual module changes).
> 
> Nobody looking at the history in the future is going to be able to understand what was going on, and I am struggling now.
> 
> Please force-push with a branch that starts at the latest `release-4.15` and contains only the commits needed.

Squashed all the commits into one.

**Comment by zaneb** [comment]
Both commits have merge conflict markers.
The actual code change is missing.

**Comment by zaneb** [comment]
The first commit still contains merge conflict markers.
Keeping the code change in a separate commit from the library upgrade would be preferable.
The commit message from the first commit still appears inside the second commit message.

**Comment by Neeraj8418** [comment]
> The first commit still contains merge conflict markers. Keeping the code change in a separate commit from the library upgrade would be preferable. The commit message from the first commit still appears inside the second commit message.

@zaneb , After squashing all the commits the branch doesn't allows us to update any commit messages or descriptions and all the merge conflict markers which you are seeing are present as a part of description of first commit (not as a commit) due to squashing of previous commits.

**Comment by zaneb** [comment]
> After squashing all the commits the branch doesn't allows us to update any commit messages

No, it absolutely does.
You can always edit the latest commit with `git commit --amend`.
You can edit _any_ commit with an [interactive rebase](https://docs.github.com/en/get-started/using-git/about-git-rebase).
In the worst case scenario you can create a new local branch with the right commits and push that one to the same target.
There is no technical obstacle to having a clean history of intentional changes and their corresponding commit messages.

**Comment by Neeraj8418** [comment]
> > After squashing all the commits the branch doesn't allows us to update any commit messages
> 
> No, it absolutely does. You can always edit the latest commit with `git commit --amend`. You can edit _any_ commit with an [interactive rebase](https://docs.github.com/en/get-started/using-git/about-git-rebase). In the worst case scenario you can create a new local branch with the right commits and push that one to the same target. There is no technical obstacle to having a clean history of intentional changes and their corresponding commit messages.

Updated the description to have only one commit message.

**Comment by Neeraj8418** [comment]
@zaneb,
All the required tests are successful with the changes, Can you please review and provide labels if there are no other changes required from our end ?

**Comment by zaneb** [comment]
The code looks ok, but the commits are still misleading because the backports of https://github.com/openshift/installer/pull/8205/commits/1d65e25d2beda1d6505bc7112163e30d2190bbc7 and https://github.com/openshift/installer/pull/8205/commits/85509894541f3c6edb16d7433f62e34313c294fe are unnecessarily squashed together, as mentioned in https://github.com/openshift/installer/pull/8447#issuecomment-2140901962

**Comment by Neeraj8418** [comment]
> The code looks ok, but the commits are still misleading because the backports of [1d65e25](https://github.com/openshift/installer/commit/1d65e25d2beda1d6505bc7112163e30d2190bbc7) and [8550989](https://github.com/openshift/installer/commit/85509894541f3c6edb16d7433f62e34313c294fe) are unnecessarily squashed together, as mentioned in [#8447 (comment)](https://github.com/openshift/installer/pull/8447#issuecomment-2140901962)



> The code looks ok, but the commits are still misleading because the backports of [1d65e25](https://github.com/openshift/installer/commit/1d65e25d2beda1d6505bc7112163e30d2190bbc7) and [8550989](https://github.com/openshift/installer/commit/85509894541f3c6edb16d7433f62e34313c294fe) are unnecessarily squashed together, as mentioned in [#8447 (comment)](https://github.com/openshift/installer/pull/8447#issuecomment-2140901962)

Seperated the commits as suggested.

**Comment by zaneb** [comment]
We're back to 5 commits and merge conflicts being added and removed.
I gave up and opened a PR with the 3 commits from 4.16 cherry-picked: #8635
/close

**Pull request closed without merging**
