### PR TITLE
Bug 1791332: rhcos: Bump to 43.81.202001142154.0 for signed packages

### PR DESCRIPTION
**Pull request by ashcrow**
Signed version of https://github.com/openshift/installer/pull/2914.

/cc @sdodson @jtligon @cuppett @miabbott @crawford

### CODE REVIEW

**Comment by sdodson** [comment]
/retitle WIP: Bug 1791332: rhcos: Bump to 43.81.202001142154.0 for signed packages

**Comment by sdodson** [comment]
I've confirmed that there's no difference in packageset between the two RHCOS builds. Overriding bugzilla flags because of rhcos divergence from master branch this change is not relevant to master branch.

**Comment by ashcrow** [comment]
Per conversation with @sdodson and @miabbott I'm removing WIP _without_ the `4.4` PR in place.

**Comment by ashcrow** [comment]
Looks like lots of infra flakes:

```
 Jan 15 15:47:29.627: INFO:  > ERROR: (gcloud.compute.instance-groups.list-instances) could not parse resource [] 
```

**Comment by ashcrow** [comment]
Metal failure:
```
 panic: open /tmp/fixture-testdata-dir204812478/examples/db-templates/postgresql-ephemeral-template.json: permission denied
<snip>
INFO: read /tmp/configfile089997202: cannot allocate memory 
```

**Comment by ashcrow** [comment]
Leaving e2e-gcp-upi alone:
```
 Waiting for create [operation-1579106355439-59c305960e8db-aba85daf-f0d4edd4]...
.......................................................failed.
ERROR: (gcloud.deployment-manager.deployments.create) Error in Operation [operation-1579106355439-59c305960e8db-aba85daf-f0d4edd4]: errors:
- code: RESOURCE_ERROR
  location: /deployments/ci-op-zqh3mzgg-51609-control-plane/resources/ci-op-c4nwq-m-2
  message: "{\"ResourceType\":\"compute.v1.instance\",\"ResourceErrorCode\":\"QUOTA_EXCEEDED\"\
    ,\"ResourceErrorMessage\":\"Quota 'CPUS' exceeded.  Limit: 2400.0 in region us-east1.\"\
    }" 
```

**Comment by sdodson** [comment]
e2e-metal in general doesn't have a high pass rate right now, so long as the installation is completing lets not block on that.

**Comment by wking** [comment]
[GCP UPI][1]:

```
ERROR: (gcloud.projects.add-iam-policy-binding) Resource in project [openshift-gce-devel-ci:setIamPolicy] is the subject of a conflict: There were concurrent policy changes. Please retry the whole read-modify-write with exponential backoff. 
```

which [is a flake][2].

/test e2e-gcp-upi

[1]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_installer/2928/pull-ci-openshift-installer-release-4.3-e2e-gcp-upi/93
[2]: https://bugzilla.redhat.com/show_bug.cgi?id=1767161

**Comment by sdodson** [comment]
/override ci/prow/e2e-gcp-upi
Other gcp jobs have passed

**Pull request merged**
