### PR TITLE
[fcos] fix GCP errors during bootstrap

### PR DESCRIPTION
**Pull request by vrutkovs**
* remove duplicate `report-progress.sh` script
* ensure `gcp-routes.service` is enabled before pivot

In order to avoid merge conflicts I also sneaked in a similar fix for vSphere:

* ensure `vmtoolsd.service` is enabled before bootstrap pivot

This would need a similar fix in MCD to have it enabled on masters / workers

Fixes https://github.com/openshift/okd/issues/37
Fixes https://github.com/openshift/okd/issues/38
Ref https://github.com/openshift/okd/issues/46

### CODE REVIEW

**Comment by LorbusChris** [comment]
@vrutkovs the report-progress.sh scripts don't contain the same code on gcp vs everywhere else.

**Comment by LorbusChris** [comment]
see the comment above, `report-progress.sh` isn't really a duplicate, as its contents are different on gcp.
https://github.com/openshift/installer/pull/3078 will fix de duplication issue.

For gcp-routes.sh, we're probably moving towards including that functionality in the MCD, and not shipping it in installer/as an MCO template.



/hold

**Comment by vrutkovs** [comment]
>#3078 will fix de duplication issue.

Awesome, thanks!

>For gcp-routes.sh, we're probably moving towards including that functionality in the MCD, and not shipping it in installer/as an MCO template.

Right, these commits are short term solution. I'll create a new PR for these then

**Pull request closed without merging**
