### PR TITLE
Bug 1962850: Bump RHCOS bootimages for various fixes

### PR DESCRIPTION
**Pull request by jlebon**
aarch64=48.84.202106091220-0
ppc64le=48.84.202106091427-0
s390x=48.84.202106091721-0
x86_64=48.84.202106091622-0

This bootimage bump contains fixes for the following RHBZs:
- https://bugzilla.redhat.com/show_bug.cgi?id=1944660
- https://bugzilla.redhat.com/show_bug.cgi?id=1954025
- https://bugzilla.redhat.com/show_bug.cgi?id=1958930
- https://bugzilla.redhat.com/show_bug.cgi?id=1969208

### CODE REVIEW

**Review by cgwalters — APPROVED** [review]

**Comment by miabbott** [comment]
@jlebon you'll need to update the `rhcos-stream.json` file too

https://github.com/openshift/installer/blob/6d778f911e79afad8ba2ff4301eda5b5cf4d8e9e/docs/dev/pinned-coreos.md#origin-of-stream-metadata

**Comment by jlebon** [comment]
> @jlebon you'll need to update the `rhcos-stream.json` file too
> 
> [`6d778f9`/docs/dev/pinned-coreos.md#origin-of-stream-metadata](https://github.com/openshift/installer/blob/6d778f911e79afad8ba2ff4301eda5b5cf4d8e9e/docs/dev/pinned-coreos.md#origin-of-stream-metadata)

Thanks, done!

**Comment by miabbott** [comment]
`e2e-aws-fips` failed on quota issues 

`could not run steps: step e2e-aws-fips failed: failed to acquire lease for "aws-quota-slice": resources not found `

`e2e-crc` failing on network timeouts

```
[36mINFO[0m[2021-06-07T16:08:44Z] Errors during downloading metadata for repository 'rhui-rhel-8-for-x86_64-baseos-rhui-rpms': 
[36mINFO[0m[2021-06-07T16:08:44Z]   - Curl error (28): Timeout was reached for https://cds.rhel.updates.googlecloud.com/pulp/mirror//content/dist/rhel8/rhui/8/x86_64/baseos/os [Operation timed out after 30000 milliseconds with 0 out of 0 bytes received] 
[36mINFO[0m[2021-06-07T16:08:44Z]   - Curl error (35): SSL connect error for https://cds.rhel.updates.googlecloud.com/pulp/repos/content/dist/rhel8/rhui/8/x86_64/baseos/os/repodata/19d341b63c8ae74747c1317c9eaf0c3952c773115362836b51fef4ea2bd96fb5-filelists.xml.gz [OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to cds.rhel.updates.googlecloud.com:443 ] 
[36mINFO[0m[2021-06-07T16:08:44Z]   - Curl error (28): Timeout was reached for https://cds.rhel.updates.googlecloud.com/pulp/repos/content/dist/rhel8/rhui/8/x86_64/baseos/os/repodata/19d341b63c8ae74747c1317c9eaf0c3952c773115362836b51fef4ea2bd96fb5-filelists.xml.gz [Operation timed out after 30000 milliseconds with 0 out of 0 bytes received] 
[36mINFO[0m[2021-06-07T16:08:44Z]   - Curl error (35): SSL connect error for https://cds.rhel.updates.googlecloud.com/pulp/repos/content/dist/rhel8/rhui/8/x86_64/baseos/os/repodata/repomd.xml [OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to cds.rhel.updates.googlecloud.com:443 ] 
[36mINFO[0m[2021-06-07T16:08:44Z]   - Curl error (35): SSL connect error for https://cds.rhel.updates.googlecloud.com/pulp/repos/content/dist/rhel8/rhui/8/x86_64/baseos/os/repodata/0fc6da969cfc177fa3e5d3234709561d0799ffd368968815c081575124cd1d98-primary.xml.gz [OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to cds.rhel.updates.googlecloud.com:443 ] 
[36mINFO[0m[2021-06-07T16:08:44Z]   - Curl error (35): SSL connect error for https://cds.rhel.updates.googlecloud.com/pulp/mirror//content/dist/rhel8/rhui/8/x86_64/baseos/os [OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to cds.rhel.updates.googlecloud.com:443 ] 
[36mINFO[0m[2021-06-07T16:08:44Z] Error: Failed to download metadata for repo 'rhui-rhel-8-for-x86_64-baseos-rhui-rpms': Yum repo downloading error: Downloading error(s): repodata/19d341b63c8ae74747c1317c9eaf0c3952c773115362836b51fef4ea2bd96fb5-filelists.xml.gz - Cannot download, all mirrors were already tried without success
```

**Comment by jlebon** [comment]
We have another fix we'd like to squeeze in here (https://github.com/coreos/fedora-coreos-config/pull/1047), so

/hold

**Comment by jlebon** [comment]
Hmm right OK, I think we need to adapt `hack/update-rhcos-bootimage.py` for https://github.com/openshift/installer/pull/4928. Looking at that.

**Comment by jlebon** [comment]
This is ready to go now!
/hold cancel

**Comment by jlebon** [comment]
Also updated instructions in `pinned-coreos.md` to use the new base URL.

**Comment by miabbott** [comment]
`e2e-aws-fips` looks to be encountering https://bugzilla.redhat.com/show_bug.cgi?id=1953798 and maybe https://bugzilla.redhat.com/show_bug.cgi?id=1928856

**Comment by miabbott** [comment]
`e2e-aws-upgrade` failed to create Route53 entries during the Terraform stage

```[31mERRO[0m[2021-06-10T03:42:47Z] level=info msg=Creating infrastructure resources... 
[31mERRO[0m[2021-06-10T03:42:47Z] level=error                                  
[31mERRO[0m[2021-06-10T03:42:47Z] level=error msg=Error: [ERR]: Error building changeset: InvalidChangeBatch: [Tried to create resource record set [name='api-int.ci-op-hkqnwtj3-76f5e.origin-ci-int-aws.dev.rhcloud.com.', type='A'] but it already exists] 
[31mERRO[0m[2021-06-10T03:42:47Z] level=error msg=	status code: 400, request id: 4906a648-275a-4085-9559-00e8a500cd41 
[31mERRO[0m[2021-06-10T03:42:47Z] level=error                                  
[31mERRO[0m[2021-06-10T03:42:47Z] level=error msg=  on ../tmp/openshift-install-530241491/route53/base.tf line 56, in resource "aws_route53_record" "api_internal_alias": 
[31mERRO[0m[2021-06-10T03:42:47Z] level=error msg=  56: resource "aws_route53_record" "api_internal_alias" { 
[31mERRO[0m[2021-06-10T03:42:47Z] level=error                                  
[31mERRO[0m[2021-06-10T03:42:47Z] level=error                                  
[31mERRO[0m[2021-06-10T03:42:47Z] level=fatal msg=failed to fetch Cluster: failed to generate asset "Cluster": failed to create cluster: failed to apply Terraform: failed to complete the change ```

**Comment by miabbott** [comment]
`e2e-aws-workers-rhel7` ran into issues with Route53 too

```[31mERRO[0m[2021-06-10T03:19:07Z] level=info msg=Creating infrastructure resources... 
[31mERRO[0m[2021-06-10T03:19:07Z] level=error                                  
[31mERRO[0m[2021-06-10T03:19:07Z] level=error msg=Error: error waiting for Route53 Hosted Zone (Z089522938I1FZQFT7VMK) creation: timeout while waiting for state to become 'INSYNC' (last state: 'PENDING', timeout: 15m0s) 
[31mERRO[0m[2021-06-10T03:19:07Z] level=error                                  
[31mERRO[0m[2021-06-10T03:19:07Z] level=error msg=  on ../tmp/openshift-install-430344814/route53/base.tf line 22, in resource "aws_route53_zone" "new_int": 
[31mERRO[0m[2021-06-10T03:19:07Z] level=error msg=  22: resource "aws_route53_zone" "new_int" { 
[31mERRO[0m[2021-06-10T03:19:07Z] level=error                                  
[31mERRO[0m[2021-06-10T03:19:07Z] level=error                                  
[31mERRO[0m[2021-06-10T03:19:07Z] level=fatal msg=failed to fetch Cluster: failed to generate asset "Cluster": failed to create cluster: failed to apply Terraform: failed to complete the change ```

**Comment by miabbott** [comment]
`e2e-crc` failed to get the control plane up, looks like a network problem preventing access to the API

`time="2021-06-09T02:18:47Z" level=debug msg="Still waiting for the Kubernetes API: Get \"https://api.crc.testing:6443/version?timeout=32s\": dial tcp 192.168.126.11:6443: connect: no route to host"`

**Comment by jlebon** [comment]
> @jlebon: This pull request references [Bugzilla bug 1962850](https://bugzilla.redhat.com/show_bug.cgi?id=1962850), which is invalid:
> 
>     * expected the bug to target the "4.9.0" release, but it targets "4.8.0" instead

Ahh, we missed the cut on Friday. So is the approach here: clone RHBZ and target it at 4.9.0, update PR title to reference new RHBZ, then cherry-pick to 4.8 branch with original RHBZ still targeting 4.8.0? Is there a way to short-circuit this?

**Comment by cgwalters** [comment]
> Ahh, we missed the cut on Friday. So is the approach here: clone RHBZ and target it at 4.9.0, update PR title to reference new RHBZ, then cherry-pick to 4.8 branch with original RHBZ still targeting 4.8.0? Is there a way to short-circuit this?

We need a distinct PR for 4.9-based RHCOS images anyways, so I'd say:

- Retarget this PR for 4.8
- Create a new PR for master that references new 4.9 images (not the same images as here)

**Comment by jlebon** [comment]
OK, now targeting release-4.8!

**Comment by cgwalters** [comment]
> openshift-machine-api   ci-op-l0yjrxk9-ecf61-mznnw-worker-us-east-2c-6t8mf   Failed    m5.xlarge   us-east-2   us-east-2c   58m                                                aws:///us-east-2c/i-02f2815bfd9b1bab6   Unknown

Hum...doesn't seem obviously related.
/retest

**Comment by cgwalters** [comment]
In case anyone else is confused looking at the PR test history, wondering why the comment above says `e2e-aws` failed but the PR test history says it passed: it appears when we changed the target branch to `release-4.8` that changed the PR test contexts to include `4.8`.

**Comment by cgwalters** [comment]
>  Needs bugzilla/valid-bug, group-lead-approved labels. 

Ping @eparis for the former (we need to skip BZ verification since the exact same code can't land in master because there are separate RHCOS 4.8 and 4.9 builds),
And ping @ashcrow for the latter

**Comment by ashcrow** [comment]
@sdodson thank you :pray:

**Pull request merged**
