### PR TITLE
OCPBUGS-35097: Add 4 new regions for PowerVS

### PR DESCRIPTION
**Pull request by miyamotoh**
- [x] osa21
- [x] syd04
- [x] lon06
- [x] sao01

Signed-off-by: Hiro Miyamoto <miyamotoh@us.ibm.com>

### CODE REVIEW

**Review by r4f4 — COMMENTED** [review]
/approve

**Comment by mjturek** [comment]
/retitle OCPBUGS-35097: Add 4 new regions for PowerVS

**Pull request merged**
