### PR TITLE
OSASINFRA-3236: deps: Bump gophercloud to v1.6.0

### PR DESCRIPTION
**Pull request by pierreprinetti**
Among other changes: use faster object-storage bulk-deletion.

### CODE REVIEW

**Review by mandre — COMMENTED** [review]
/lgtm

**Review by mandre — COMMENTED** [review]
/lgtm

**Review by mandre — COMMENTED** [review]
/lgtm

**Comment by pierreprinetti** [comment]
CI failures:
* `ci/prow/e2e-openstack-ovn`: transient
* `ci/prow/e2e-openstack-nfv-intel`: unrelated (known issue)
* `ci/prow/okd-e2e-aws-ovn`: does not look related
* `ci/prow/okd-e2e-aws-ovn-upgrade`: does not look related
* `ci/prow/okd-scos-e2e-aws-ovn`: does not look related

I think this PR is ready to be merged.

/assign sadasu patrickdillon

**Comment by pierreprinetti** [comment]
@patrickdillon Is there anything we can do to help this PR be approved?

**Pull request merged**
