### PR TITLE
OCPBUGS-34024: go.mod: bump aws-sdk-go for ca-west-1 support

### PR DESCRIPTION
**Pull request by r4f4**
Manual cherry-pick of https://github.com/openshift/installer/pull/8381

### CODE REVIEW

**Comment by r4f4** [comment]
/assign @sadasu
For the backport label

**Review by barbacbd — COMMENTED** [review]
/lgtm

**Comment by r4f4** [comment]
/override ci/prow/e2e-vsphere-ovn-upi
Not related to PR changes.

**Pull request merged**
