### PR TITLE
Bug 1818140: Backport adding groundwork for multi-arch images

### PR DESCRIPTION
**Pull request by Prashanth684**
A backport of https://github.com/openshift/installer/pull/2885 and backport of one commit from https://github.com/openshift/installer/pull/2933 - which is to enable s390x boot image support.

List of commits which are being backported:
https://github.com/openshift/installer/pull/2885/commits/2583ba4dfb6199860ef57055b8d27f5d53026fa4
https://github.com/openshift/installer/pull/2885/commits/8428471c622f8372acc9068cc2a4b7a59d47214d
https://github.com/openshift/installer/pull/2885/commits/b1726d2c5e819310e3dab26510e776a5e84f4bf4
https://github.com/openshift/installer/commit/b7d74740800b6f8e754a91d2934ffbfca0dd6b8f

/cc @crawford @jaypoulz

### CODE REVIEW

**Comment by crawford** [comment]
I don't see the s390x image variants. Is that intentional?

I want to double check the amd64 variants as well.

/hold

**Comment by Prashanth684** [comment]
> I don't see the s390x image variants. Is that intentional?
> 
> I want to double check the amd64 variants as well.
> 
> /hold

Yes. the 4.3 s390x images need to be put in `releases-art-rhcos.svc.ci.openshift.org` and they are not present as of yet. I was thinking of putting that in another PR. The amd64 variants are the exact same as the ones in rhcos.json.

**Comment by crawford** [comment]
/hold cancel
/retest

Can you drop that last commit (enabling s390x as a valid platform) until we have the build metadata?

**Comment by Prashanth684** [comment]
> /hold cancel
> /retest
> 
> Can you drop that last commit (enabling s390x as a valid platform) until we have the build metadata?

I added the build metadata for s390x. I was just not aware that the URL used for getting the metadata was a public version of the internal URL.

**Comment by crawford** [comment]
@miabbott is the RHCOS team comfortable with this version being used for s390x?

@Prashanth684 does the QEMU variant of this image use the config-drive or do we need a similar hack to the one we used in 4.2?

**Comment by Prashanth684** [comment]
> @miabbott is the RHCOS team comfortable with this version being used for s390x?
> 
> @Prashanth684 does the QEMU variant of this image use the config-drive or do we need a similar hack to the one we used in 4.2?

we need https://github.com/coreos/ignition/pull/905 (or something similar) for the QEMU variant to use config drive

**Comment by crawford** [comment]
> we need coreos/ignition#905 (or something similar) for the QEMU variant to use config drive

Okay, let's hold this PR for now. We'll need to get a fix into the OS and then update the build metadata. Same goes for ppc64.

/hold

**Comment by miabbott** [comment]
> @miabbott is the RHCOS team comfortable with this version being used for s390x?

Comparing the `s390x` and `ppc64le` versions noted in this PR, it looks like they roughly line up with version ` 43.81.202003021026.0` from the `x86_64` pipeline.

But the `s390x` and `ppc64le` versions have a slighty different content set; I'd say the `s390x` version should be `43.81.202003091812.0` to have better alignment across arches.

Of course, this is moot if we need a fix to Ignition and have to respin everything anyways...

**Comment by Prashanth684** [comment]
> > @miabbott is the RHCOS team comfortable with this version being used for s390x?
> 
> Comparing the `s390x` and `ppc64le` versions noted in this PR, it looks like they roughly line up with version ` 43.81.202003021026.0` from the `x86_64` pipeline.
> 
> But the `s390x` and `ppc64le` versions have a slighty different content set; I'd say the `s390x` version should be `43.81.202003091812.0` to have better alignment across arches.
> 
> Of course, this is moot if we need a fix to Ignition and have to respin everything anyways...

exactly. i am waiting for https://github.com/coreos/ignition/pull/905 to merge and then re-spin ignition for 4.3.

**Comment by Prashanth684** [comment]
@crawford @miabbott updated PR with latest bootimage for s390x and ppc64le which includes support in ignition for https://github.com/coreos/ignition/pull/936

**Comment by miabbott** [comment]
The versions for `s390x` and `ppc64le` look good to me;  they have the updated `ignition` and a fixed version of `iptables`, too.

The versions roughly align with `43.81.202003172344.0` from the `x86_64` pipeline;  that version (and newer) have been consumed by the OCP CI machines already and no errors have been reported.

/approve

**Comment by Prashanth684** [comment]
@crawford bumped terraform with the latest commit. We have all that we need. Should be good to go.

**Comment by Prashanth684** [comment]
/retitle Bug 1818140: [release-4.3]: Backport adding groundwork for multi-arch images

**Pull request merged**
