### PR TITLE
OSASINFRA-3199: Configure User-Agent for OpenStack API calls

### PR DESCRIPTION
**Pull request by stephenfin**
gophercloud provides the ability to configure a User-Agent header for all API calls. This is a very helpful breadcrumb when debugging issues with the various OpenStack components. Configure it for all OpenStack API clients in the installer.

### CODE REVIEW

**Comment by stephenfin** [comment]
/cc @mandre @pierreprinetti @EmilienM 

Also, wuh wuh, looks like CI is borked. I don't think this is me.

**Comment by pierreprinetti** [comment]
Looks great, thanks!
/hold cancel
/approve
/lgtm
/meow

**Pull request merged**
