### PR TITLE
Bug 1791280: Bump RHCOS to 44.81.202001171431.0

### PR DESCRIPTION
**Pull request by sdodson**

### CODE REVIEW

**Comment by sdodson** [comment]
/cc @jlebon @miabbott 
Unknown if this would also include fixes for https://bugzilla.redhat.com/show_bug.cgi?id=1791279
Can you please confirm whether or not that's the case?

**Comment by ashcrow** [comment]
@sdodson It does. I checked the build and it does indeed have `ignition-0.34.0-1.rhaos4.3.git92f874c.el8` which has the enhancement.

Ref: https://url.corp.redhat.com/44-81-202001171431-0-contents

**Comment by ashcrow** [comment]
**NOTE**: Title and commit message version here does NOT match the change.

Title/Commit: `44.81.202001030903.0`
Content: `44.81.202001171431.0`

**Comment by sdodson** [comment]
> **NOTE**: Title and commit message version here do NOT match the content change.

Thank you, I've fixed that.

**Pull request merged**
