### PR TITLE
Bug 1775728: rhcos: Bump to 43.81.201911221453.0

### PR DESCRIPTION
**Pull request by cgwalters**
This has fixes for encryption, see e.g.:

- https://bugzilla.redhat.com/show_bug.cgi?id=1775728

### CODE REVIEW

**Comment by sdodson** [comment]
/test e2e-metal
It will likely fail due to other problems but I'm curious.

**Comment by cgwalters** [comment]
Leasing
/test e2e-gcp

Some sort of networking issue, probably real but not likely related to this
/test e2e-azure

**Comment by jcpowermac** [comment]
vSphere is failing on the usual tests.  The install completed bootstrap and cluster complete.  lgtm

**Comment by cgwalters** [comment]
Looks like a transient Prow issue
/test e2e-azure

**Comment by stbenjam** [comment]
/label platform/baremetal

Is this working?

**Comment by metal3ci** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/1332/

**Comment by patrickdillon** [comment]
Seeing 
```
[systemd]
Failed Units: 1
  multipathd.service
```
in GCP. Seems like this should help that as well...

**Comment by cgwalters** [comment]
Horray, have a :heavy_check_mark: `e2e-azure`.  Let's get this in?

**Comment by abhinavdahiya** [comment]
/retest

does it solve the metal failures?

**Comment by cgwalters** [comment]
> does it solve the metal failures?

No, because at least the machines we're getting from Packet.net only have a TPM1.2 - and we don't make it easy to disable the encryption requirement on the bootstrap. See https://github.com/openshift/enhancements/issues/98#
(There are other packet issues being worked through in https://github.com/openshift/installer/pull/2695 )

**Comment by abhinavdahiya** [comment]
> No, because at least the machines we're getting from Packet.net only have a TPM1.2 -

but the PR description says that it's fixing that bug...? Can we remove that if that's not the case.

/cc @wking 
we might have to bump the AMI for upi tests

**Comment by cgwalters** [comment]
> but the PR description says that it's fixing that bug...? Can we remove that if that's not the case.

Sure, done.

**Comment by cgwalters** [comment]
Known busted
/override e2e-metal
/override e2e-aws-scaleup-rhel7
Known to have some failing tests
/override e2e-vsphere

**Pull request merged**
