### PR TITLE
OCPBUGS-8468: aws: bump aws-sdk-go version

### PR DESCRIPTION
**Pull request by r4f4**
So we can support new AWS regions.

### CODE REVIEW

**Comment by r4f4** [comment]
RHCOS was published to newer regions as part of https://github.com/openshift/installer/pull/6861

**Comment by r4f4** [comment]
Rebased to fix vendoring (I ran `go get -u` but forgot to run `go mod tidy`).

**Review by barbacbd — COMMENTED** [review]
/lgtm

**Pull request merged**
