### PR TITLE
Bug 1851067: rhcos/ppc64le,s390x: Bump to 46.82.202006241544-0 and 46.82.202006241639-0

### PR DESCRIPTION
**Pull request by Prashanth684**
Bump to the latest 4.6 builds

### CODE REVIEW

**Comment by Prashanth684** [comment]
/retitle Bug 1851067: rhcos/ppc64le,s390x: Bump to 46.82.202006241544-0 and 46.82.202006241639-0

**Comment by ashcrow** [comment]
Reviewing the packages now

**Pull request merged**
