### PR TITLE
remove unnecessary scc

### PR DESCRIPTION
**Pull request by deads2k**
SCCs don't exist before the CVO runs the openshift-apiserver-operator, so nothing in tectonic.sh  can depend on them.

/assign @steveeJ @abhinavdahiya 
/cc @mfojtik

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
@deads2k this is not bootube. We have a separate script tectonic.sh that installs objects that cannot be installed by bootube.

**Comment by abhinavdahiya** [comment]
I'm fine dropping this as seems unused. Can you change this PR description?

**Comment by deads2k** [comment]
> I'm fine dropping this as seems unused. Can you change this PR description?

fixed

/retest

**Pull request merged**
