### PR TITLE
types/vsphere: simplify vsphere platform

### PR DESCRIPTION
**Pull request by staebler**
Remove most of the configuration from the vSphere platform, leaving only the options that a basic customer would need to get a cluster running.

### CODE REVIEW

**Comment by staebler** [comment]
```console
$ cat <<EOF > install-config.yaml 
apiVersion: v1beta4
baseDomain: devcluster.openshift.com 
metadata:
  name: mstaeble
networking:
  machineCIDR: "139.178.89.192/26"
platform:
  vsphere:
    vCenter: vcsa.vmware.devcluster.openshift.com
    username: me@e2e.local
    password: you will never guess
    datacenter: dc1
    defaultDatastore: nvme-ds1
pullSecret: redacted
sshKey: redacted

$ openshift-install create manifests
INFO Consuming "Install Config" from target directory 

$ cat openshift/99_cloud-creds-secret.yaml 
kind: Secret
apiVersion: v1
metadata:
  namespace: kube-system
  name: vsphere-creds
data:
  vcsa.vmware.devcluster.openshift.com.username: bWVAZTJlLmxvY2Fs
  vcsa.vmware.devcluster.openshift.com.password: eW91IHdpbGwgbmV2ZXIgZ3Vlc3M=

$ cat openshift/99_role-cloud-creds-secret-reader.yaml 
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: kube-system
  name: vsphere-creds-secret-reader
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["vsphere-creds"]
  verbs: ["get"]
```

**Comment by abhinavdahiya** [comment]
[e2e-failure](https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_installer/1591/pull-ci-openshift-installer-master-e2e-aws/5124):

```console
Failing tests:

[sig-storage] In-tree Volumes [Driver: emptydir] [Testpattern: Dynamic PV (default fs)] volumes should be mountable [Suite:openshift/conformance/parallel] [Suite:k8s]
```

/retest

**Comment by vrutkovs** [comment]
```
level=fatal msg="failed to wait for bootstrap-complete event: timed out waiting for the condition"
```
/retest

**Comment by vrutkovs** [comment]
`VpcLimitExceeded: The maximum number of VPCs has been reached`

/retest

**Comment by abhinavdahiya** [comment]
`could not create target imagestream: an empty namespace may not be set during creation`

/retest

**Pull request merged**
