### PR TITLE
baremetal: Add etcd SRV record lookup

### PR DESCRIPTION
**Pull request by cybertron**
On baremetal we don't know the names of the etcd nodes ahead of time
because they are assigned by the customer's DHCP. As a result, we
can't populate the list of etcd cluster members before bootstrap and
need to do the lookup during bootstrap.

This change moves the MCO bootstrap earlier in the process because
that is what configures the nodes to start advertising their DNS
names. It also adds a baremetal-specific call to baremetal-runtimecfg
to do the lookup of the etcd cluster names.

Note that currently we get around this by requiring specific names
to be configured in the customer DHCP, which is rather rigid and
requires more configuration on their side than is desirable. This
change improves the baremetal install experience by removing that
requirement.

### CODE REVIEW

**Comment by cybertron** [comment]
This depends on https://github.com/openshift/baremetal-runtimecfg/pull/25 That will need to merge first.

**Comment by abhinavdahiya** [comment]
/hold

this needs to validated by the etcd team that is working on the cluster-etcd-operator so cc @hexfusion . 

Also this changes the behavior for all other platforms, lets try to minimise collateral change.

**Comment by jstuever** [comment]
Defer to baremetal folks
/cc @celebdor 
/uncc @jstuever

**Comment by hexfusion** [comment]
We have a call scheduled on this for the 14th to discuss.

**Comment by abhinavdahiya** [comment]
So we had discussion out-of-band and it looks like the baremetal-ipi team is working with etcd team to align.

/close

if that's not true, please feel free to re-open

**Pull request closed without merging**
