### PR TITLE
WIP: Use the kubelet on RHCOS instead of from origin-node image

### PR DESCRIPTION
**Pull request by eparis**
This would break CL....

### CODE REVIEW

**Comment by wking** [comment]
/retest

#181 fixed the gofmt stuff.  Also kick Jenkins for smoke tests:

retest this please

**Comment by wking** [comment]
Can we drop this from `modules/tectonic/resources/tectonic-wrapper.sh` too?  I don't understand where that script is being run yet, but it would be nice to drop our dependency on the hyperkube image completely.

**Comment by eparis** [comment]
/retest
I can try to see what uses that script (and in turn image) as my next side project...

**Comment by eparis** [comment]
Can we merge this? If I promise to come back and look at the (unrelated) tectonic-wrapper.sh? and start ripping out CL entirely...

**Comment by wking** [comment]
[The smoke test errors][1] included:

```
 smoke_test.go:113: retrying in 10s
 smoke_test.go:112: failed with error: failed to connect to API server: the server could not find the requested resource
 smoke_test.go:113: retrying in 10s
 common_test.go:18: Failed to connect to API server in 15m0s.
```

I don't know if that's related or not.  Maybe you need to bump [the RHCOS AMI][2] before using the system kubelet?

[1]: https://jenkins-tectonic-installer.prod.coreos.systems/job/openshift-installer/view/change-requests/job/PR-180/3/consoleText
[2]: https://github.com/openshift/release/blob/00cfc5ab81496cef8568b3d96fba44926ae10390/ci-operator/templates/cluster-launch-installer-e2e.yaml#L198

**Comment by wking** [comment]
> I don't know if that's related or not.  Maybe you need to bump the RHCOS AMI before using the system kubelet?  [Edit: actually, the smoke tests don't use that config, so I have no idea what's broken :/]

Now that I've finished my coffee, I've remembered ;).  The smoke tests are currently running via Jenkins in a separate AWS account (Prow is in 460538899914, Jenkins/smoke is in 846518947292).  The RHCOS AMIs aren't public, and only the Prow account has the access credentials for them.  So the smoke-test failures are probably because the CoreOS AMI being used is missing a host kubelet, and everything after that hangs.  In order to get this PR to work, we need to do one of:

a. Add a native kubelet to the CoreOS stable series.
b. Move the smoke tests over to Prow and/or the Prow AWS account, from which they'll have access to the RHCOS AMIs.
c. Drop the smoke tests in favor of more e2e-aws coverage.  Work in progress on this front in openshift/release#1271.

In general, moving the default to use a private AMI stream is going to make it harder for devs and others to use the installer.  Is there a public stream that is similiar enough to the RHCOS stream that we can use for development?

**Comment by wking** [comment]
> The `tectonic-wrapper.sh` allows `tectonic.sh` to run inside a container that has `oc` binary.

Hyperkube seems like a heavy dependency if that's all we'll need it for.  Do the origin folks publish an image that only `oc`, `kubectl`, and enough-of-POSIX (e.g. via BusyBox)?  Effectively that would be an origin-client image.  Or maybe I'm overestimating the size of hyperkube?

**Comment by abhinavdahiya** [comment]
> Hyperkube seems like a heavy dependency if that's all we'll need it for.

We needed `hyperkube` on host for kubelet anyways; So it wasn't a problem. But moving forward as we would not need `hyperkube` image, i think we can move to minimal image.

But `oc` is required; `kubectl` does not work well with `securitycontextconstraints` objects.

**Comment by eparis** [comment]
https://github.com/coreos-inc/tectonic-operators/pull/447 would need to merge, and then this get updated.

**Comment by eparis** [comment]
/retest
now that my forked the tectonic-operators are public

**Comment by sjenning** [comment]
fyi me @rphillips @derekwaynecarr

**Comment by crawford** [comment]
@eparis I'm working on stripping Container Linux from the installer. Do you mind if I close this out in favor of a future PR?

**Pull request closed without merging**
