### PR TITLE
Bug 1820575: Cherry-pick oVirt PR 3406 vNIC profiles

### PR DESCRIPTION
**Pull request by patrickdillon**
manual cherry-pick of #3406 as it is failing due to merge conflict: 
https://github.com/openshift/installer/pull/3406#issuecomment-624766116

merge conflict was simple... pkg/asset/installconfig in master has a single check for vsphere and related import which I removed. everything else picks cleanly

cc @rgolangh

### CODE REVIEW

**Comment by patrickdillon** [comment]
Regarding CI failures we could be missing cherry picks in other repos. This is simply a guess but perhaps something like https://github.com/openshift/machine-config-operator/pull/1717

**Comment by rgolangh** [comment]
libvirt failures doesn't look related. In general it libvirt seem to fail a lot lately https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/?type=presubmit&job=*libvirt*
Can we please skip libvirt?

**Pull request merged**
