### PR TITLE
Removing no-longer-needed DNS etcd stuff

### PR DESCRIPTION
**Pull request by pamoedom**
This PR supersedes broken https://github.com/openshift/installer/pull/4795

cc @staebler

### CODE REVIEW

**Comment by staebler** [comment]
For e2e-aws-upi, from https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_installer/5764/pull-ci-openshift-installer-master-e2e-aws-upi/1509521301092438016/artifacts/e2e-aws-upi/upi-install-aws-cluster/build-log.txt
```
level=info msg=Install complete!
```
/lgtm
/approve

**Comment by pamoedom** [comment]
@staebler, thanks for merging the PR, one question, shall we also backport (cherrypick) the changes to all current supported versions (>=4.6) ?

**Comment by staebler** [comment]
> @staebler, thanks for merging the PR, one question, shall we also backport (cherrypick) the changes to all current supported versions (>=4.6) ?

I do not think it warrants backporting. There are no side effects of this other than some unnecessary DNS records in the private hosted zone.

**Comment by pamoedom** [comment]
Hi @staebler, thanks for your response, I was thinking on backporting not for the side effects but based on BZ#1852798 request. This BZ was "closed deferred" pending on previous https://github.com/openshift/installer/pull/4795 progress, shall we reopen it and target 4.11 with this PR to close the loop?

**Comment by staebler** [comment]
> Hi @staebler, thanks for your response, I was thinking on backporting not for the side effects but based on [BZ#1852798](https://bugzilla.redhat.com/show_bug.cgi?id=1852798) request. This BZ was "closed deferred" pending on previous #4795 progress, shall we reopen it and target 4.11 with this PR to close the loop?

That sounds like the right thing to do.

**Comment by pamoedom** [comment]
ACK @staebler, I'll do that, thanks.

**Pull request merged**
