### PR TITLE
Bug 1789601: rhcos: Bump to 43.81.202001141554.0

### PR DESCRIPTION
**Pull request by ashcrow**
This bump fixes an updated issue with NIC bonding as well as the `growpart` issue.

Fixes:
- https://bugzilla.redhat.com/show_bug.cgi?id=1789601
- https://bugzilla.redhat.com/show_bug.cgi?id=1789014

**NOTE**: Another PR to master will take place soon which will be different artifacts :slightly_smiling_face: 

/cc @imcleod @cuppett @crawford @miabbott @jlebon

### CODE REVIEW

**Comment by sdodson** [comment]
In its current state this does or does not fix https://bugzilla.redhat.com/show_bug.cgi?id=1789014 ?
/test e2e-metal

**Comment by ashcrow** [comment]
> In its current state this does or does not fix https://bugzilla.redhat.com/show_bug.cgi?id=1789014 ?
> /test e2e-metal

It should https://bugzilla.redhat.com/show_bug.cgi?id=1789014#c15 ... I'm running around updating all the things right now :-)

**Comment by sdodson** [comment]
I don't think there's any automated method to have one PR fix multiple bugs. Lets just pick one and we can link things up on the bugzilla side after the fact.

**Comment by miabbott** [comment]
Note: we are still waiting for `ignition-0.34.0-1` to make it into the signed RPM repo for RHCOS.  Once that happens, we will switch the RHCOS manifest to use that signed RPM repo, get a new RHCOS build, and will have likely have to rev this patch again.

**Comment by ashcrow** [comment]
ci/prow/e2e-gcp-upi is a gcloud error:
```
There were concurrent policy changes. Please retry the whole read-modify-write with exponential backoff.
```

**Comment by ashcrow** [comment]
Same `e2e-gcp-upi` error. History for the job looks like it's a pretty common infra failure.

**Comment by ashcrow** [comment]
Looks like e2e-metal failed running out of available memory in a test and couldn't write nor read it's test file.

**Comment by jlebon** [comment]
Well, the good news is that the `e2e-metal` *didn't* fail because of https://bugzilla.redhat.com/show_bug.cgi?id=1789014. We can see the growpart clearly happening before the MCD starts up:

```
Jan 14 19:54:30 master-2.ci-op-2730r560-4d792.origin-ci-int-aws.dev.rhcloud.com systemd[1]: Starting Resize root partition...
...
Jan 14 19:54:30 master-2.ci-op-2730r560-4d792.origin-ci-int-aws.dev.rhcloud.com rhcos-growpart[3523]: meta-data=/dev/mapper/coreos-luks-root-nocrypt isize=512    agcount=4, agsize=170047 blks
Jan 14 19:54:30 master-2.ci-op-2730r560-4d792.origin-ci-int-aws.dev.rhcloud.com rhcos-growpart[3523]:          =                       sectsz=512   attr=2, projid32bit=1
Jan 14 19:54:30 master-2.ci-op-2730r560-4d792.origin-ci-int-aws.dev.rhcloud.com rhcos-growpart[3523]:          =                       crc=1        finobt=1, sparse=1, rmapbt=0
Jan 14 19:54:30 master-2.ci-op-2730r560-4d792.origin-ci-int-aws.dev.rhcloud.com rhcos-growpart[3523]:          =                       reflink=1
Jan 14 19:54:30 master-2.ci-op-2730r560-4d792.origin-ci-int-aws.dev.rhcloud.com rhcos-growpart[3523]: data     =                       bsize=4096   blocks=680187, imaxpct=25
Jan 14 19:54:30 master-2.ci-op-2730r560-4d792.origin-ci-int-aws.dev.rhcloud.com rhcos-growpart[3523]:          =                       sunit=0      swidth=0 blks
Jan 14 19:54:30 master-2.ci-op-2730r560-4d792.origin-ci-int-aws.dev.rhcloud.com rhcos-growpart[3523]: naming   =version 2              bsize=4096   ascii-ci=0, ftype=1
Jan 14 19:54:30 master-2.ci-op-2730r560-4d792.origin-ci-int-aws.dev.rhcloud.com rhcos-growpart[3523]: log      =internal log           bsize=4096   blocks=2560, version=2
Jan 14 19:54:30 master-2.ci-op-2730r560-4d792.origin-ci-int-aws.dev.rhcloud.com rhcos-growpart[3523]:          =                       sectsz=512   sunit=0 blks, lazy-count=1
Jan 14 19:54:30 master-2.ci-op-2730r560-4d792.origin-ci-int-aws.dev.rhcloud.com rhcos-growpart[3523]: realtime =none                   extsz=4096   blocks=0, rtextents=0
Jan 14 19:54:30 master-2.ci-op-2730r560-4d792.origin-ci-int-aws.dev.rhcloud.com rhcos-growpart[3523]: data blocks changed from 680187 to 58472337
Jan 14 19:54:30 master-2.ci-op-2730r560-4d792.origin-ci-int-aws.dev.rhcloud.com systemd[1]: Started Resize root partition.
Jan 14 19:54:30 master-2.ci-op-2730r560-4d792.origin-ci-int-aws.dev.rhcloud.com systemd[1]: Starting Machine Config Daemon Firstboot...
```

**Comment by ashcrow** [comment]
- e2e-metal failed due to "invalid aws credentials"
- e2e-gcp-upi same infra policy error

**Comment by sdodson** [comment]
I've overridden bugzilla labels and cherrpick approval because this addresses multiple blocker bugs and rhcos base images have diverged between master branch and this branch. I'll reach out tomorrow to see how we can avoid requiring such exceptions around rhcos bootimages.

**Pull request merged**
