### PR TITLE
OCPBUGS-3985: Pass featureset to kas

### PR DESCRIPTION
**Pull request by deads2k**
cargo culted from https://github.com/openshift/installer/pull/6576, created for https://github.com/openshift/cluster-kube-apiserver-operator/pull/1403

### CODE REVIEW

**Comment by stlaz** [comment]
was this merged as a part of https://github.com/openshift/installer/pull/6576?

**Comment by stlaz** [comment]
Looks good, I believe we may need https://github.com/openshift/cluster-kube-apiserver-operator/pull/1409 to merge first, though

**Comment by deads2k** [comment]
Need to see techpreview function.

/payload 4.13 nightly informing

**Comment by deads2k** [comment]
tech preview clusters installed too.

**Comment by deads2k** [comment]
The vsphere errors look consistent across the entire job on the repo.  Generally broken?

https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/pull-ci-openshift-installer-master-e2e-vsphere-ovn

**Pull request merged**
