### PR TITLE
[fcos] pkg/asset/machines: avoid generating duplicate MC with ssh keys

### PR DESCRIPTION
**Pull request by vrutkovs**
pkg/asset/installconfig/ssh.go already generates MC with ssh keys.
Ignition v2 skips duplicate files, but Ignition v3 throws an error during
boot.

Duplicate ssh keys are injected in bootstrap node during create manifests && create cluster commands

Fixes openshift/okd#63

### CODE REVIEW

**Comment by LorbusChris** [comment]
Is this a candidate to go into master as well? AFAICT we also duplicate them there, but it's just not caught by Ign Spec v2.

**Comment by vrutkovs** [comment]
+1 on cherrypicking to master, not sure if that breaks any other test though

**Comment by vrutkovs** [comment]
/override ci/prow/vsphere

Known tests failing

**Comment by vrutkovs** [comment]
/override ci/prow/e2e-vsphere

Known test failures

**Comment by vrutkovs** [comment]
/override ci/prow/e2e-vsphere

known issues

**Comment by vrutkovs** [comment]
/override ci/prow/e2e-vsphere

known issues

**Pull request merged**
