### PR TITLE
upi: Post TF 0.12.x migration fixups

### PR DESCRIPTION
**Pull request by LorbusChris**
In this PR:
- upi/vsphere/lb: Use decimal file mode for haproxy.conf
To align with the other files written by the Terraform Ignition provider.
This also changes the file mode to 0644 as it does not need the
executable bit.
- upi/vsphere: Update README.md and example tfvars
This reflects recent changes
- ~~Dockerfile.upi.ci: Update govmomi to v0.22.2 
This aligns it with the version currently vendored via go.mod~~ this release doesn't provide all the binaries

NOT in this PR:
- Updates needed for `docs/user/vsphere/install_upi.md` to reflect recent changes

### CODE REVIEW

**Comment by jcpowermac** [comment]
@LorbusChris 
https://www.terraform.io/docs/providers/ignition/d/file.html#mode
did you see an issue because of the octal vs decimal?

**Comment by LorbusChris** [comment]
I did not, and I haven't checked whether it might actually supported in the tf ignition provider. This however aligns it with the other files

**Comment by LorbusChris** [comment]
the default is 0644, in case this were invalid. does this file have to be executable anyway?

**Comment by LorbusChris** [comment]
sorry, on the phone, only just now saw the docs. looks like it is supported after all :) I'll close if you prefer

**Comment by jcpowermac** [comment]
> the default is 0644, in case this were invalid. does this file have to be executable anyway?

you are right it doesn't need to be executable.  So its up to you if you want to still fix it or close.

**Comment by LorbusChris** [comment]
@jcpowermac I added another commit to reflect some of the recent changes in the README and example tfvars. There's also `docs/user/vsphere/install_upi.md` which to me looks like it would need a bigger overhaul.

As this doesn't have a BZ I don't expect expect this to get merged before master/4.6 opens.

**Comment by jcpowermac** [comment]
@LorbusChris thanks for doing this!

**Comment by jcpowermac** [comment]
vSphere failed from removed commit retry and is running into vSphere CI env limits
/test e2e-vsphere-upi

**Comment by jcpowermac** [comment]
I am not sure what is up with this. I can download the file and extract perfectly fine.
```
could not run steps: step upi-installer failed: could not wait for build: the build upi-installer failed after 7m50s with reason DockerBuildFailed: Docker build strategy has failed.

Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --...9    0     0     30      0 --:--:-- --:--:-- --:--:--    30

gzip: govc_linux_amd64.gz: not in gzip format
error: build error: running 'curl -L -O https://github.com...4 && mv govc_linux_amd64 /bin/govc' failed with exit code 1
```

**Comment by LorbusChris** [comment]
I've seen that a few times before, so far it's always been a transient infra issue

**Comment by LorbusChris** [comment]
prom didn't come up
/test e2e-vsphere-upi

**Comment by LorbusChris** [comment]
/test e2e-vsphere-upi
/cc @jcpowermac

Now that 4.6 is open, do you mind having another look at this?

**Pull request merged**
