### PR TITLE
[release-4.15] CORS-3166: GCP: Update DNSType within GCP PlatformStatus based on UserProvisionedDNS

### PR DESCRIPTION
**Pull request by sadasu**
This is a manual cherry-pick of https://github.com/openshift/installer/pull/7837

### CODE REVIEW

**Review by barbacbd — COMMENTED** [review]
/lgtm

**Comment by sadasu** [comment]
@yunjiang29 could you PTAL and add the cherry-pick-approved label?

**Comment by r4f4** [comment]
@sadasu I think you need a Jira in the OCPBUGS project to get the label.

**Comment by r4f4** [comment]
Or maybe just setting the target version for CORS-3166 could work 
```
Warning: The referenced jira issue has an invalid target version for the target branch this PR targets: expected the bug to target the "4.15.0" version, but no target version was set.
```

**Comment by r4f4** [comment]
Actually, we are already passed the Feature Freeze. If this is not a feature, it must be a bug so an OCPBUGS Jira card is appropriate in this case.

**Pull request merged**
