### PR TITLE
Bug 1820434: OpenStack: Allow Booting bootstrap node from volume

### PR DESCRIPTION
**Pull request by mandre**
Some OpenStack environments might enforce a policy where VMs can't boot
with ephemeral disks and need to boot from a cinder volume. In these
cases, it would be impossible to install OCP because even though we
configured the master and worker nodes to boot from volume using the
`rootVolume` setting, the bootstrap node would still boot from
ephemeral disk.

With this change, the bootstrap node follows the `rootVolume` settings
from controlPlane machine pool. This shouldn't be a surprising behavior
since the bootstrap node is already using the same flavor and security
groups as the control plane nodes.

### CODE REVIEW

**Comment by iamemilio** [comment]
/hold
I think it might be confusing that whether or not bootstrap nodes boot from volume is determined by a setting on the master machine pool. Also, needs docs.

**Comment by mandre** [comment]
> /hold
> I think it might be confusing that whether or not bootstrap nodes boot from volume is determined by a setting on the master machine pool. Also, needs docs.

I do not think we need docs around this. The boostrap node is ephemeral and we don't really care how it's provisioned or how it works, as long as it works - it's a black box. This patch makes it work in environment where you're not allowed to provision VMs with ephemeral disks, by following the settings from the control plane machine pool. I believe this is the expected behavior since we're already using the flavor and security groups from the control plane for the bootstrap node.

**Pull request merged**
