### PR TITLE
OCPBUGS-32174: save correct bootstrap public IP

### PR DESCRIPTION
**Pull request by r4f4**
When the BYOIPv4 feature was introduced to the terraform provisioning in 50c0a9d8221, a new EIP resource was created unconditionally. The bootstrap VM was first getting a public IP from the `associate_public_ip_address` config in the instance and that IP was then discarded when the EIP was created and associated with the instance.

However, a "race" could happen in which, at the end of the bootstrap stage, we saved the first (and now dead) IP Address:
```
DEBUG Outputs:
DEBUG
DEBUG bootstrap_ip = "18.222.119.149"
DEBUG [INFO] running Terraform command: /c/terraform/bin/terraform output -no-color -json
DEBUG {
DEBUG   "bootstrap_ip": {
DEBUG     "sensitive": false,
DEBUG     "type": "string",
DEBUG     "value": "18.222.119.149"
DEBUG   }
DEBUG }
```
In case of bootstrap failure, the `gather bootstrap` would use the stale IP address and fail to connect:
```
time="2024-04-12T15:08:49Z" level=info msg="Failed to gather bootstrap logs: failed to connect to the bootstrap machine: dial tcp 18.222.119.149:22: connect: connection timed out"
```
instead of using the actual EIP address "18.225.29.102".

This changes proposes the following fixes:

1. Only create an EIP if a public IPv4 pool has been specified.
2. Only `associate_public_ip_address` to the bootstrap instance if public IPv4 pools have *not* been specified.
3. At the end of the bootstrap stage, save the correct IP address by considering whether the bootstrap EIP was created or not.
4. Tag the EIP, when created, so it can be properly deleted even when bootstrap fails.

### CODE REVIEW

**Comment by r4f4** [comment]
/retitle OCPBUGS-32174: save correct bootstrap public IP

**Comment by r4f4** [comment]
/hold

Until I remove https://github.com/openshift/installer/pull/8264/commits/9ade8b98139e8608f384b31ca451d833aa617739

**Comment by r4f4** [comment]
Example of failure before the fix: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_installer/8264/pull-ci-openshift-installer-master-e2e-aws-ovn/1778790262227603456

**Comment by mtulio** [comment]
waiting for triggered jobs. Overall LGTM
/hold
/lgtm

**Comment by r4f4** [comment]
`e2e-aws-ovn`: ssh connection succeeded and log bundle collected: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_installer/8264/pull-ci-openshift-installer-master-e2e-aws-ovn/1778849920040570880/artifacts/e2e-aws-ovn/ipi-install-install/artifacts/

`e2e-aws-ovn-public-ipv4-pool`: ssh connection succeeded and log bundle collected: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_installer/8264/pull-ci-openshift-installer-master-e2e-aws-ovn-public-ipv4-pool/1778852236667916288/artifacts/e2e-aws-ovn-public-ipv4-pool/ipi-install-install/artifacts/

**Comment by r4f4** [comment]
The `public-ipv4-pool` didn't actually use the ip pools: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_installer/8264/pull-ci-openshift-installer-master-e2e-aws-ovn-public-ipv4-pool/1778852236667916288/artifacts/e2e-aws-ovn-public-ipv4-pool/ipi-conf-aws-byo-ipv4-pool-public/build-log.txt

Let's try again:
/test e2e-aws-ovn-public-ipv4-pool

**Comment by r4f4** [comment]
`public-ipv4-pool`: 
this time it acquire an ip pool
 `    publicIpv4Pool: "ipv4pool-ec2-0768267342e327ea9"`
ssh connection succeeded and log bundle collected:
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_installer/8264/pull-ci-openshift-installer-master-e2e-aws-ovn-public-ipv4-pool/1778879239303467008/artifacts/e2e-aws-ovn-public-ipv4-pool/ipi-install-install/artifacts/
bootstrap EIP created:
 `time="2024-04-12T21:02:57Z" level=debug msg="aws_eip.bootstrap[0]: Creation complete after 2s [id=eipalloc-0efabd4442838e949]"`
bootstrap destroy:
 `time="2024-04-12T21:30:04Z" level=info msg=Released id=eipalloc-0efabd4442838e949 resourceType=elastic-ip`

**Comment by r4f4** [comment]
Commit forcing a bootkube failure has been removed.

/hold cancel

**Pull request merged**
