### PR TITLE
[FCOS] bootstrap: support systemd-resolved when setting a prepender 

### PR DESCRIPTION
**Pull request by vrutkovs**
This reverts commit 84dd12e03e98fc9ea58b2d1b096a34869bfc36ca and includes systemd-resolved support for all IPI on-prem platforms.

Fixes https://github.com/openshift/okd/issues/502
Fixes https://github.com/openshift/okd/issues/509

### CODE REVIEW

**Comment by vrutkovs** [comment]
/hold

for testing

**Comment by jomeier** [comment]
> This reverts commit [84dd12e](https://github.com/openshift/installer/commit/84dd12e03e98fc9ea58b2d1b096a34869bfc36ca) and includes systemd-resolved support for all IPI on-prem platforms.
> 
> Fixes [openshift/okd#502](https://github.com/openshift/okd/issues/502)

Does this also support vSphereUPI ?

**Comment by vrutkovs** [comment]
I don't think this relevant for UPI - afaik mDNS runs in IPI mode only

**Review by mandre — COMMENTED** [review]
/approve for openstack

**Comment by vrutkovs** [comment]
/skip

vsphere test flakes

/approve

**Pull request merged**
