### PR TITLE
[OpenStack] make optional ingress floating ip on board for out of box experience

### PR DESCRIPTION
**Pull request by wjiangjay**
I suppose we need to provide the ingress floating IP as we did with the API floating IP for out of box experience.

### CODE REVIEW

**Comment by wjiangjay** [comment]
@mandre  @adduarte Help review this, thanks

**Comment by wjiangjay** [comment]
And seems like there are some conflicts with https://github.com/openshift/installer/pull/3822

**Comment by mandre** [comment]
Hi @wjiangjay, this seems to duplicate https://github.com/openshift/installer/pull/3855. Could you perhaps review it to check we haven't missed anything?
We'll take care or deprecating `lbFloatingIP` in favor of `apiFloatingIP` in a separate commit as we can't simply rename it.

**Comment by wjiangjay** [comment]
@mandre yes, dup with https://github.com/openshift/installer/pull/3855, Thanks, will close this

**Pull request closed without merging**
