### PR TITLE
SPLAT-1750: Add support for multiple NICs for vSphere day 0

### PR DESCRIPTION
**Pull request by rvanderp3**
**Description:**
This PR introduces day-0 configuration of multiple NICs for VMware. [`NodeNetworking` fields](https://github.com/openshift/api/blob/master/config/v1/types_infrastructure.go#L1299C6-L1299C39) are being introduced to the platform spec and allow the intended to subnet to be used to determine the node address.

If NodeNetworking is not defined, the machine network CIDR is used as a default for `nodeNetworking.[internal/external].networkSubnetCIDR`.

#### Payload testing for this PR only
- [x] periodic-ci-openshift-release-master-nightly-4.18-e2e-vsphere-ovn-techpreview: [69196a70-6667-4c68-8716-4d2ce1b1ee77](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/openshift-installer-8890-nightly-4.18-e2e-vsphere-ovn-techpreview/1832137051961561088) *
- [x] periodic-ci-openshift-release-master-nightly-4.18-e2e-vsphere-ovn: [7045ffb5-f88a-4058-8fa9-7590ff92f5f4](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/openshift-installer-8890-nightly-4.18-e2e-vsphere-ovn/1832137052506820608)

#### Payload testing incorporating vendor bump and associated feature PRs
- [x] periodic-ci-openshift-release-master-nightly-4.18-e2e-vsphere-ovn-multi-network: [b5cf064b-6068-4798-bc61-364e8bf514e1](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/openshift-machine-config-operator-4538-openshift-machine-api-operator-1276-openshift-cluster-control-plane-machine-set-operator-323-openshift-installer-8890-nightly-4.18-e2e-vsphere-ovn-multi-network/1831795592557236224)
- [x] periodic-ci-openshift-release-master-nightly-4.18-e2e-vsphere-ovn-techpreview: [61937e70-e43f-440a-8ea8-88c0b2be9e52](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/openshift-machine-api-operator-1276-openshift-cluster-control-plane-machine-set-operator-323-openshift-machine-config-operator-4538-openshift-installer-8890-nightly-4.18-e2e-vsphere-ovn-techpreview/1831341316567470080)
- [x] periodic-ci-openshift-release-master-nightly-4.18-e2e-vsphere-ovn: [044829d5-3916-42fd-9b34-8d1bed65842b](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/openshift-machine-config-operator-4538-openshift-machine-api-operator-1276-openshift-cluster-control-plane-machine-set-operator-323-openshift-installer-8890-nightly-4.18-e2e-vsphere-ovn/1831341722827755520) 

\* test failed due to unrelated flake

### CODE REVIEW

**Comment by rvanderp3** [comment]
/assign @mkowalski 

@mkowalski would you mind taking a look at what is being done here and let me if you have any concerns?  I wanted to make sure what were doing here made sense.  https://github.com/openshift/cluster-cloud-controller-manager-operator/pull/299 seems to transform the cloud config as well but it wasn't clear to me if this could conflict.

**Comment by mkowalski** [comment]
A very very quick look tells me that this should be safe if I cross-check with https://github.com/openshift/cluster-cloud-controller-manager-operator/pull/299; `IPFamilyPriority` does not exist here so all good and `ExcludeNetworkSubnetCIDR` transformer-trick we do in CCCM should still work

**Comment by rvanderp3** [comment]
/payload-job-with-prs periodic-ci-openshift-release-master-nightly-4.18-e2e-vsphere-ovn-techpreview openshift/machine-config-operator#4538 openshift/machine-api-operator#1276 openshift/cluster-control-plane-machine-set-operator#323
/payload-job-with-prs periodic-ci-openshift-release-master-nightly-4.18-e2e-vsphere-ovn openshift/machine-config-operator#4538 openshift/machine-api-operator#1276 openshift/cluster-control-plane-machine-set-operator#323
/payload-job-with-prs periodic-ci-openshift-release-master-nightly-4.18-e2e-vsphere-multi-network openshift/machine-config-operator#4538 openshift/machine-api-operator#1276 openshift/cluster-control-plane-machine-set-operator#323

**Comment by rvanderp3** [comment]
/payload-job-with-prs periodic-ci-openshift-release-master-nightly-4.18-e2e-vsphere-ovn-techpreview https://github.com/openshift/machine-config-operator/pull/4538 https://github.com/openshift/machine-api-operator/pull/1276 https://github.com/openshift/cluster-control-plane-machine-set-operator/pull/323

**Comment by rvanderp3** [comment]
/payload-job-with-prs periodic-ci-openshift-release-master-nightly-4.18-e2e-vsphere-ovn-techpreview openshift/machine-config-operator#4538 openshift/machine-api-operator#1276 openshift/cluster-control-plane-machine-set-operator#323

**Comment by rvanderp3** [comment]
/payload-job-with-prs periodic-ci-openshift-release-master-nightly-4.18-e2e-vsphere-ovn openshift/machine-config-operator#4538 openshift/machine-api-operator#1276 openshift/cluster-control-plane-machine-set-operator#323

**Comment by rvanderp3** [comment]
/payload-job-with-prs periodic-ci-openshift-release-master-nightly-4.18-e2e-vsphere-ovn-multi-network openshift/machine-config-operator#4538 openshift/machine-api-operator#1276 openshift/cluster-control-plane-machine-set-operator#323

**Comment by rvanderp3** [comment]
/payload-job-with-prs periodic-ci-openshift-release-master-nightly-4.18-e2e-vsphere-ovn-multi-network openshift/machine-config-operator#4538 openshift/machine-api-operator#1276 openshift/cluster-control-plane-machine-set-operator#323

**Comment by rvanderp3** [comment]
/payload-job-with-prs periodic-ci-openshift-release-master-nightly-4.18-e2e-vsphere-ovn-multi-network https://github.com/openshift/machine-config-operator/pull/4538 https://github.com/openshift/machine-api-operator/pull/1276 https://github.com/openshift/cluster-control-plane-machine-set-operator/pull/323

**Comment by rvanderp3** [comment]
/payload-job-with-prs periodic-ci-openshift-release-master-nightly-4.18-e2e-vsphere-ovn-multi-network openshift/machine-config-operator#4538 openshift/machine-api-operator#1276 openshift/cluster-control-plane-machine-set-operator#323

**Comment by rvanderp3** [comment]
/payload-job-with-prs periodic-ci-openshift-release-master-nightly-4.18-e2e-vsphere-ovn-multi-network openshift/machine-config-operator#4538 openshift/machine-api-operator#1276 openshift/cluster-control-plane-machine-set-operator#323

**Comment by rvanderp3** [comment]
/payload-job-with-prs periodic-ci-openshift-release-master-nightly-4.18-e2e-vsphere-ovn-multi-network https://github.com/openshift/machine-config-operator/pull/4538 https://github.com/openshift/machine-api-operator/pull/1276

**Comment by rvanderp3** [comment]
/payload-job-with-prs periodic-ci-openshift-release-master-nightly-4.18-e2e-vsphere-ovn-multi-network openshift/machine-config-operator#4538 openshift/machine-api-operator#1276 openshift/cluster-control-plane-machine-set-operator#323

**Comment by rvanderp3** [comment]
/payload-job-with-prs periodic-ci-openshift-release-master-nightly-4.18-e2e-vsphere-ovn-multi-network https://github.com/openshift/machine-config-operator/pull/4538 https://github.com/openshift/machine-api-operator/pull/1276 https://github.com/openshift/cluster-control-plane-machine-set-operator/pull/323

**Comment by rvanderp3** [comment]
/payload-job-with-prs periodic-ci-openshift-release-master-nightly-4.18-e2e-vsphere-ovn-multi-network openshift/machine-config-operator#4538 openshift/machine-api-operator#1276 openshift/cluster-control-plane-machine-set-operator#323

**Comment by rvanderp3** [comment]
/payload-job-with-prs periodic-ci-openshift-release-master-nightly-4.18-e2e-vsphere-ovn-multi-network openshift/machine-config-operator#4538 openshift/machine-api-operator#1276 openshift/cluster-control-plane-machine-set-operator#323

**Comment by rvanderp3** [comment]
/payload-job-with-prs periodic-ci-openshift-release-master-nightly-4.18-e2e-vsphere-ovn-multi-network openshift/machine-config-operator#4538 openshift/machine-api-operator#1276 openshift/cluster-control-plane-machine-set-operator#323

**Comment by rvanderp3** [comment]
/payload-job-with-prs periodic-ci-openshift-release-master-nightly-4.18-e2e-vsphere-ovn-multi-network openshift/machine-config-operator#4538 openshift/machine-api-operator#1276 openshift/cluster-control-plane-machine-set-operator#323

**Comment by rvanderp3** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.18-e2e-vsphere-ovn-techpreview periodic-ci-openshift-release-master-nightly-4.18-e2e-vsphere-ovn

**Pull request merged**
