### PR TITLE
Bug 1908489: azure: adhere to new regex requirements for nic names

### PR DESCRIPTION
**Pull request by staebler**
With https://github.com/kubernetes/kubernetes/pull/95542, NIC names must matches the regex (.+)-nic-(.+).

### CODE REVIEW

**Comment by wking** [comment]
UPI template will need a bump too (`upi/azure/05_masters.json` and similar), right?

```console
$ git --no-pager grep -- -nic 
data/data/azure/bootstrap/main.tf:  bootstrap_nic_ip_v4_configuration_name = "bootstrap-nic-ip-v4"
data/data/azure/bootstrap/main.tf:  bootstrap_nic_ip_v6_configuration_name = "bootstrap-nic-ip-v6"
data/data/azure/bootstrap/main.tf:  name                = "${var.cluster_id}-bootstrap-nic"
data/data/azure/master/master.tf:  name                = "${var.cluster_id}-master${count.index}-nic"
docs/user/azure/install_upi.md:az network nic delete -g $RESOURCE_GROUP --name ${INFRA_ID}-bootstrap-nic --no-wait
upi/azure/04_bootstrap.json:    "nicName" : "[concat(variables('vmName'), '-nic')]",
upi/azure/05_masters.json:      "name" : "[concat(variables('vmNames')[copyIndex()], '-nic')]",
upi/azure/05_masters.json:        "[concat('Microsoft.Network/networkInterfaces/', concat(variables('vmNames')[copyIndex()], '-nic'))]"
...
```

**Comment by staebler** [comment]
Somehow some of the files did not make it into the commit. They should all be there now.

**Comment by wking** [comment]
aa4a230e6c23 covers everything I could find, so if this passes CI, you can't find any Azure approvers, and you want a naive :lgtm:, let me know :)

**Comment by wking** [comment]
[e2e-azure-upi][1]:

```
ResourceNotFoundError: The Resource 'Microsoft.Network/networkInterfaces/ci-op-j54q7yx0-ba9fa-kpxpg-master-0-nic' under resource group 'ci-op-j54q7yx0-ba9fa-kpxpg-rg' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix
```

So there must still be one out there that needs the suffix.

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_installer/4490/pull-ci-openshift-installer-master-e2e-azure-upi/1339343353396858880

**Comment by wking** [comment]
Aha, the Azure template [expects the old-style names][1].  Not sure what to do about that.  Would be nice to have the Azure CI ported to multi-step too ;).

[1]: https://github.com/openshift/release/blob/076426438800446270376d2011ae30bd514f9dce/ci-operator/templates/openshift/installer/cluster-launch-installer-upi-e2e.yaml#L2099-L2102

**Comment by staebler** [comment]
> Aha, the Azure template [expects the old-style names](https://github.com/openshift/release/blob/076426438800446270376d2011ae30bd514f9dce/ci-operator/templates/openshift/installer/cluster-launch-installer-upi-e2e.yaml#L2099-L2102). Not sure what to do about that. Would be nice to have the Azure CI ported to multi-step too ;).

This is the fix to the e2e-azure-upi template to be resilient to the change to the format of the NIC names.
https://github.com/openshift/release/pull/14432

**Comment by fabianofranz** [comment]
/lgtm

Installer changes LGTM and I see @staebler has a PR to fix the names in the CI job, but have we considered how this affects existing clusters and their LB's after an upgrade? cc @wking

**Comment by staebler** [comment]
> /test e2e-azure

The e2e-azure test is not going to pass. It is failing with the following from the azure cloud provider.

```
azure_loadbalancer.go:193] reconcileLoadBalancer(openshift-ingress/router-default) failed: cannot get the availability set ID from the virtual machine with node name ci-op-bpk9gm56-2dc90-lw6kr-master-1
```

**Comment by wking** [comment]
We can probably close this, because the upstream cloud-provider is planning to [soften their regexp][1].

[1]: https://github.com/kubernetes-sigs/cloud-provider-azure/pull/443/files#diff-0bcfc79694dbf29ed477ca98b63ae5b8c086e3195ee643088759ab8dddeb0b31R78

**Comment by sdodson** [comment]
we're only fixing the cloud provider

**Pull request closed without merging**
