### PR TITLE
WIP - Move tectonic-ingress to openshift-ingress

### PR DESCRIPTION
**Pull request by smarterclayton**
Makes installer consistent with 4.0 direction.

Going to open the PRs against the other repos

### CODE REVIEW

**Comment by smarterclayton** [comment]
As part of move prep adding https://github.com/openshift/release/pull/1221

**Comment by openshift-docker** [comment]
Last run passed (router came up in a namespace).

I'm going to rerun when https://github.com/openshift/origin/pull/20703
merges which should ensure that at least one router e2e test passes, and
then when this merges we can verify that it still passes

**Comment by crawford** [comment]
Included in https://github.com/openshift/installer/pull/162.

/close

**Pull request closed without merging**
