### PR TITLE
azure: avoid timeouts due to growfs

### PR DESCRIPTION
**Pull request by r4f4**
Using the workaround in [1] until the issue is fixed in RHCOS.

[1] https://github.com/coreos/fedora-coreos-tracker/issues/1183#issuecomment-1150140690

### CODE REVIEW

**Comment by patrickdillon** [comment]
@r4f4 what about adding to control plane nodes too? 

@jlebon wonder if you could ptal

**Comment by jlebon** [comment]
/approve

It looks fine to me. Just to be clear though, this is only required for very large disks. Not sure on how conditionalized this code path here is/needs to be based on that. (I vaguely recall that on Azure we always provision 1T disks to get the higher IOPS tier? If that's the case, then this is fine.)

**Comment by r4f4** [comment]
There is an alternative implementation with a separate `/var` partition at https://github.com/openshift/installer/pull/9310

**Comment by r4f4** [comment]
/close

I'm going to close this in favor of https://github.com/openshift/installer/pull/9310. If 9310 ends up not being the way forward, we can reopen this PR.

**Pull request closed without merging**
