### PR TITLE
Bug 1881487: data/rhcos.json: Update to 46.82.202009220041-0

### PR DESCRIPTION
**Pull request by cgwalters**
This fixes numerous bugs, such as:

- https://bugzilla.redhat.com/show_bug.cgi?id=1879690
- https://github.com/coreos/ignition/issues/1081
- https://bugzilla.redhat.com/show_bug.cgi?id=1875567

### CODE REVIEW

**Review by ashcrow — APPROVED** [review]
:+1:

**Comment by cgwalters** [comment]
OK I just made a new bug rather than fight to claim an existing one.

**Comment by cgwalters** [comment]
/test e2e-openstack
Looks like OpenStack is pretty red in general right now though.

**Comment by miabbott** [comment]
Azure look like it is hitting the provisioning timeout discussed in https://bugzilla.redhat.com/show_bug.cgi?id=1878323 and https://bugzilla.redhat.com/show_bug.cgi?id=1779375

GCP test history looks very red overall; seeing a lot of timeouts trying to setup a mount - `MountVolume.SetUp failed for volume "default-token-s55xw" : failed to sync secret cache: timed out waiting for the condition`.  No obvious BZ in Sippy.

/test e2e-azure
/test e2e-gcp

**Comment by miabbott** [comment]
/hold

The RHCOS build has the wrong version of `ostree` included; need to get a new RHCOS build made

**Review by ashcrow — APPROVED** [review]

**Comment by cgwalters** [comment]
Console operator didn't come up at all, not sure what's up with that
/test e2e-aws

**Comment by cgwalters** [comment]
OK the gcp run is failing e2e tests - as a general rule, I don't think we should try hard to block bootimage updates on those because basically the bootimage can't really affect them.  The [promotion for this content](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/promote-release-openshift-machine-os-content-e2e-aws-4.6/1308831061748224000) has flaked on different storage tests.  (The rare case here is when we switched to the LUKS container by default and *that* regressed etcd performance until we did dm-linear instead)

**Comment by cgwalters** [comment]
Azure failed on the marketplace operator...hm, not [any other hits for that in CI runs](https://search.ci.openshift.org/?search=failed+to+initialize+the+cluster%3A+Cluster+operator+marketplace+is+still+updating&maxAge=48h&context=1&type=bug%2Bjunit&name=&maxMatches=5&maxBytes=20971520&groupBy=job) but I suspect that's at least partially a function of how few Azure CI runs there are.
/test e2e-azure

**Comment by cgwalters** [comment]
e2e-metal died from https://bugzilla.redhat.com/show_bug.cgi?id=1882111 - again almost certainly unrelated.

**Comment by cgwalters** [comment]
I'm not finding out what's going wrong with the vsphere-upi run.  The fact that vsphere-ipi passed is a good sign at least.

Took a swing at fixing the vsphere-upi test in https://github.com/openshift/release/pull/12186

**Comment by cgwalters** [comment]
As for e2e-ovirt...well, hmm.  It looks like the workers didn't come up, control plane too seems...broken?
At least one periodic for e2e-ovirt passed so let's see:
/test e2e-ovirt

**Comment by cgwalters** [comment]
So...I think my overall conclusion here is let's get this in - we're fixing a whole ton of things here and if there really are any regressions we can shake those out as followups.

**Comment by sdodson** [comment]
All of those major platforms that failed did so in e2e tests after successful installation, so going ahead.
/approve

**Comment by bgilbert** [comment]
Contrary to https://github.com/openshift/installer/pull/4206#issue-490885411, this PR does not fix https://github.com/coreos/ignition/issues/1081.  That fix has not yet landed in an Ignition release or an Ignition RPM.

**Pull request merged**
