### PR TITLE
images/nested-libvirt/Dockerfile: Fix build to builder typo

### PR DESCRIPTION
**Pull request by praveenkumar**

### CODE REVIEW

**Comment by zeenix** [comment]
@praveenkumar I know it's a simple fix but a bit of context in the commit message and PR would be great. Something like "This fixes the build, broken by a typo in commit 77ef472453".

**Comment by wking** [comment]
[images][1]:

```
release "release-latest" failed: pod release-latest was already deleted
```

/retest

[1]: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_installer/1699/pull-ci-openshift-installer-master-images/4121

**Pull request merged**
