### PR TITLE
Introduce gosec for security checks

### PR DESCRIPTION
**Pull request by JAORMX**
gosec does static code analysis and checks for common security issues in
golang codebases.

This PR introduces a script that will run gosec similarly to other check
tools.

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
Do you have an example of what kind of security flaws does this script highlight on this repo's master.

I would like top avoid yet another `comment` to skip the test, if there are toomany false positives with this for installer repo as installer deals with files etc.

And if there is an effort to bring this check in all OpenShift repos, i would expect this to be backed by an enhancement.

**Comment by JAORMX** [comment]
> Do you have an example of what kind of security flaws does this script highlight on this repo's master.

I switched the configuration to only highlight critical security flaws with high confidence (as opposed to the previous attempt, which was medium flaws with medium confidence). With this configuration, the tool doesn't find any issues in the codebase (which is good!).

Here's the output:

```
hack/go-sec.sh                                                                                                                                                              add-gosec  
+ '[' '' '!=' '' ']'
+ podman run --rm --env IS_CONTAINER=TRUE --volume /home/josorior/go/src/github.com/openshift/installer:/go/src/github.com/openshift/installer:z --workdir /go/src/github.com/openshift/installer docker.io/openshift/origin-release:golang-1.12 ./hack/go-sec.sh
+ '[' TRUE '!=' '' ']'
++ command -v gosec
+ '[' '!' '' ']'
+ go get github.com/securego/gosec/cmd/gosec
+ gosec -severity high -confidence high -exclude G304 ./cmd/... ./data/... ./pkg/...
[gosec] 2019/10/21 09:56:14 Including rules: default
[gosec] 2019/10/21 09:56:14 Excluding rules: G304
[gosec] 2019/10/21 09:56:14 Import directory: /go/src/github.com/openshift/installer/cmd/openshift-install
[gosec] 2019/10/21 09:58:40 Checking package: main
[gosec] 2019/10/21 09:58:40 Checking file: /go/src/github.com/openshift/installer/cmd/openshift-install/completions.go
[gosec] 2019/10/21 09:58:40 Checking file: /go/src/github.com/openshift/installer/cmd/openshift-install/create.go
...
Results:


Summary:
   Files: 301
   Lines: 27020
   Nosec: 0
  Issues: 0
```
> 
> I would like top avoid yet another `comment` to skip the test, if there are toomany false positives with this for installer repo as installer deals with files etc.
> 
> And if there is an effort to bring this check in all OpenShift repos, i would expect this to be backed by an enhancement.

There is no PR in the enhancements repo as of yet.

**Pull request merged**
