### PR TITLE
Bug 1881703: Revert "Have the MCO manage the ignition stub config"

### PR DESCRIPTION
**Pull request by runcom**
This reverts commit 8d278d258f9eb16788cc8c4bda842018e28625d7 following findings in https://docs.google.com/document/d/1TnnfPgFim-e895MD0msOGN9tyPBk3CM8cmSewFmgzDQ/edit# and https://bugzilla.redhat.com/show_bug.cgi?id=1881703

### CODE REVIEW

**Comment by yuqi-zhang** [comment]
cross linking https://github.com/openshift/machine-api-operator/pull/715 and https://github.com/openshift/machine-config-operator/pull/2126

**Comment by yuqi-zhang** [comment]
/approve

based on our conversations in the MCO PR

**Comment by runcom** [comment]
@abhinavdahiya ptal - this is needed for the current release and currently blocks https://github.com/openshift/machine-config-operator/pull/2126

**Pull request merged**
