### PR TITLE
CORS-3288:  bump CAPA for LB scheme fix

### PR DESCRIPTION
**Pull request by r4f4**
This makes it possible to have public subnets associated with an external secondary LB.

### CODE REVIEW

**Comment by r4f4** [comment]
Update: somehow I missed a "go mod tidy". Fixed.

**Comment by patrickdillon** [comment]
/approve

Does it require updates to infrastructure-components.yaml?

**Comment by r4f4** [comment]
> Does it require updates to infrastructure-components.yaml?

Good point. I see some upstream changes to support ignition proxy, so I'll update it.

**Review by barbacbd — COMMENTED** [review]
/lgtm

Since this is not an official release of CAPA the CRD and infrastructures will not match the upstream (they were generated here), and this is ok.

**Pull request merged**
