### PR TITLE
libvirt: Document workaround for CSR not getting approved

### PR DESCRIPTION
**Pull request by zeenix**
This is a persistent issue for slow hosts (think nested-virt) so best to document this workaround.

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
I think we should open bugs with auto-approver to handle slow cases.. even on AWS i3 instances take long to boot and get CSR approved.. I would like to move to correct solutions than work-arounds.

If there are already open bugs I can take a look at pushing it higher in priority.

**Comment by zeenix** [comment]
> I think we should open bugs with auto-approver to handle slow cases

That's on my TODO for today. I should have done that before this so that we can reference it in the document.

**Comment by zeenix** [comment]
[Issue filed](https://github.com/openshift/cluster-machine-approver/issues/36) and reference added to the document.

**Comment by zeenix** [comment]
Could this go in now?

/assign @abhinavdahiya

**Comment by abhinavdahiya** [comment]
> Could this go in now?
> 
> /assign @abhinavdahiya

https://github.com/openshift/cluster-machine-approver/pull/37 is open, do we want to wait for it or go ahead and remove the workaround later?

**Comment by zeenix** [comment]
> [openshift/cluster-machine-approver#37](https://github.com/openshift/cluster-machine-approver/pull/37) is open, do we want to wait for it or go ahead and remove the workaround later?

Oh I completely missed that since it doesn't reference https://github.com/openshift/cluster-machine-approver/issues/36. Let's wait for that first indeed.

**Comment by zeenix** [comment]
With https://github.com/openshift/cluster-machine-approver/pull/37 merged, hopefully this is no longer needed.

**Pull request closed without merging**
