### PR TITLE
[FCOS] use stable Fedora CoreOS boot images

### PR DESCRIPTION
**Pull request by vrutkovs**
/cc @LorbusChris

### CODE REVIEW

**Comment by LorbusChris** [comment]
/lgtm

@vrutkovs can you override the vsphere e2e here?

**Comment by vrutkovs** [comment]
I'd rather have it fixed it in https://github.com/openshift/installer/pull/2671 first.

/hold
for now, as it might need a rebase

**Comment by LorbusChris** [comment]
I'm fine with that :) Maybe we can hold it even until the OKD installer rebase on top of the #2745 has been merged (or force-pushed rather) - this here could then be the last commit before Beta 1.

**Comment by vrutkovs** [comment]
Updated OVA path, since UPI support got merged

**Comment by vrutkovs** [comment]
`govc: unexpected EOF` - network error during OVA upload

/retest

**Pull request merged**
