### PR TITLE
extend waitForInitializedCluster for libvirt installs

### PR DESCRIPTION
**Pull request by sallyom**
@wking wdyt? 
https://github.com/openshift/installer/issues/3043

### CODE REVIEW

**Comment by stbenjam** [comment]
baremetal is a specific case because physical hardware has long POST that extends provisioning to 10-15 minutes.  When we're in virtualized baremetal environments it works fine. Are you sure it's not a problem with not using virtio for all your devices like disks and networks? That seems to be the common problem for a virtualized install not completing in the allowed timeframe.

**Comment by wking** [comment]
do we understand the recent increased delays in install time?  We usually try to put a finger on why we're suddenly slower before bumping timeouts, to avoid ignoring possible regressions.

**Comment by sallyom** [comment]
> Are you sure it's not a problem with not using virtio for all your devices like disks and networks? That seems to be the common problem for a virtualized install not completing in the allowed timeframe.

I'm following the installer docs for libvirt, not sure about virtio-looking...

**Comment by sallyom** [comment]
> do we understand the recent increased delays in install time? We usually try to put a finger on why we're suddenly slower before bumping timeouts, to avoid ignoring possible regressions.

I don't know when libvirt was last know to consistently finish within the installer timeout.  I stepped away from using libvirt installs for ~ a year, but recently I found they are timing out.

**Comment by abhinavdahiya** [comment]
a dev workflow that takes > 30 minutes is not really useful, i think our time is better spent on seeing what's slow and fixing that. libvirt doesn't fall into the bucket of baremetal which supposedly takes > 30 minutes due to machine-post-time being very high.

**Comment by sallyom** [comment]
> a dev workflow that takes > 30 minutes is not really useful, i think our time is better spent on seeing what's slow and fixing that. libvirt doesn't fall into the bucket of baremetal which supposedly takes > 30 minutes due to machine-post-time being very high.
closing!

**Pull request closed without merging**
