### PR TITLE
Bug 1837039: rhcos: Bump to 45.81.202005181029-0

### PR DESCRIPTION
**Pull request by cgwalters**
A lot of fixes here, for example time synchronization, see
https://bugzilla.redhat.com/show_bug.cgi?id=1828342
and entropy:
https://bugzilla.redhat.com/show_bug.cgi?id=1830280

In particular, we definitely need time sync on the bootstrap
node.

### CODE REVIEW

**Comment by ashcrow** [comment]
**Note**: openvswitch looks removed at first glance but it's not. It bumped from `openvswitch2.11` :arrow_right: `openvswitch2.13`

Package diff:
```
"diff": {
    "afterburn": {
        "rhcos-4.4/44.81.202004250133-0": "afterburn-4.1.1-3.rhaos4.2.el8.x86_64",
        "rhcos-4.5/45.81.202005181029-0": "afterburn-4.3.3-1.rhaos4.5.el8.x86_64"
    },
    "conmon": {
        "rhcos-4.4/44.81.202004250133-0": "conmon-2.0.15-1.rhaos4.4.el8.x86_64",
        "rhcos-4.5/45.81.202005181029-0": "conmon-2.0.15-1.rhaos4.5.el8.x86_64"
    },
    "console-login-helper-messages": {
        "rhcos-4.4/44.81.202004250133-0": "console-login-helper-messages-0.16-1.rhaos4.2.el8.noarch",
        "rhcos-4.5/45.81.202005181029-0": "console-login-helper-messages-0.18-1.rhaos4.5.el8.noarch"
    },
    "console-login-helper-messages-issuegen": {
        "rhcos-4.4/44.81.202004250133-0": "console-login-helper-messages-issuegen-0.16-1.rhaos4.2.el8.noarch",
        "rhcos-4.5/45.81.202005181029-0": "console-login-helper-messages-issuegen-0.18-1.rhaos4.5.el8.noarch"
    },
    "console-login-helper-messages-profile": {
        "rhcos-4.4/44.81.202004250133-0": "console-login-helper-messages-profile-0.16-1.rhaos4.2.el8.noarch",
        "rhcos-4.5/45.81.202005181029-0": "console-login-helper-messages-profile-0.18-1.rhaos4.5.el8.noarch"
    },
    "container-selinux": {
        "rhcos-4.4/44.81.202004250133-0": "container-selinux-2.124.0-1.module+el8.1.1+5259+bcdd613a.noarch",
        "rhcos-4.5/45.81.202005181029-0": "container-selinux-2.132.0-1.rhaos4.5.el8.noarch"
    },
    "coreos-installer": {
        "rhcos-4.4/44.81.202004250133-0": "coreos-installer-0-13.rhaos4.3.gite5aa5dc.el8.noarch",
        "rhcos-4.5/45.81.202005181029-0": "coreos-installer-0-2.rhaos4.4.gite5aa5dc.el8.noarch"
    },
    "coreos-installer-dracut": {
        "rhcos-4.4/44.81.202004250133-0": "coreos-installer-dracut-0-13.rhaos4.3.gite5aa5dc.el8.noarch",
        "rhcos-4.5/45.81.202005181029-0": "coreos-installer-dracut-0-2.rhaos4.4.gite5aa5dc.el8.noarch"
    },
    "cri-o": {
        "rhcos-4.4/44.81.202004250133-0": "cri-o-1.17.4-6.dev.rhaos4.4.gitb5c490c.el8.x86_64",
        "rhcos-4.5/45.81.202005181029-0": "cri-o-1.18.0-17.dev.rhaos4.5.gitdea34b9.el8.x86_64"
    },
    "ignition": {
        "rhcos-4.4/44.81.202004250133-0": "ignition-0.35.0-5.rhaos4.4.git7afbeba.el8.x86_64",
        "rhcos-4.5/45.81.202005181029-0": "ignition-0.35.1-10.rhaos4.5.git73ff2d7.el8.x86_64"
    },
    "machine-config-daemon": {
        "rhcos-4.4/44.81.202004250133-0": "machine-config-daemon-4.4.0-202004242317.git.1.8dcae93.el8.x86_64",
        "rhcos-4.5/45.81.202005181029-0": "machine-config-daemon-4.5.0-202005180918.git.1.0d16cc9.el8.x86_64"
    },
    "nss-altfiles": {
        "rhcos-4.4/44.81.202004250133-0": "nss-altfiles-2.18.1-12.rhaos4.2.el8.x86_64",
        "rhcos-4.5/45.81.202005181029-0": "nss-altfiles-2.18.1-12.el8.x86_64"
    },
    "openshift-clients": {
        "rhcos-4.4/44.81.202004250133-0": "openshift-clients-4.4.0-202004221411.git.1.9902124.el8.x86_64",
        "rhcos-4.5/45.81.202005181029-0": "openshift-clients-4.5.0-202005180117.git.1.1415dcf.el8.x86_64"
    },
    "openshift-hyperkube": {
        "rhcos-4.4/44.81.202004250133-0": "openshift-hyperkube-4.4.0-202004241258.git.1.bfb96d1.el8.x86_64",
        "rhcos-4.5/45.81.202005181029-0": "openshift-hyperkube-4.5.0-202005180017.git.1.9a0bd5b.el8.x86_64"
    },
    "openvswitch-selinux-extra-policy": {
        "rhcos-4.4/44.81.202004250133-0": "openvswitch-selinux-extra-policy-1.0-22.el8fdp.noarch",
        "rhcos-4.5/45.81.202005181029-0": "openvswitch-selinux-extra-policy-1.0-23.el8fdp.noarch"
    },
    "openvswitch2.11": {
        "rhcos-4.4/44.81.202004250133-0": "openvswitch2.11-2.11.0-50.el8fdp.x86_64",
        "rhcos-4.5/45.81.202005181029-0": "Not present"
    },
    "podman": {
        "rhcos-4.4/44.81.202004250133-0": "podman-1.6.4-12.rhaos4.4.el8.x86_64",
        "rhcos-4.5/45.81.202005181029-0": "podman-1.6.4-13.rhaos4.5.el8.x86_64"
    },
    "podman-manpages": {
        "rhcos-4.4/44.81.202004250133-0": "podman-manpages-1.6.4-12.rhaos4.4.el8.noarch",
        "rhcos-4.5/45.81.202005181029-0": "podman-manpages-1.6.4-13.rhaos4.5.el8.noarch"
    },
    "redhat-release-coreos": {
        "rhcos-4.4/44.81.202004250133-0": "redhat-release-coreos-44.81-4.el8.x86_64",
        "rhcos-4.5/45.81.202005181029-0": "redhat-release-coreos-45.82-5.el8.x86_64"
    },
    "runc": {
        "rhcos-4.4/44.81.202004250133-0": "runc-1.0.0-65.rc10.rhaos4.4.el8.x86_64",
        "rhcos-4.5/45.81.202005181029-0": "runc-1.0.0-69.rhaos4.5.gita70f354.el8.x86_64"
    },
    "slirp4netns": {
        "rhcos-4.4/44.81.202004250133-0": "slirp4netns-0.4.2-4.git21fdece.el8.x86_64",
        "rhcos-4.5/45.81.202005181029-0": "slirp4netns-0.4.2-3.git21fdece.module+el8.1.1+5657+524a77d7.x86_64"
    },
    "toolbox": {
        "rhcos-4.4/44.81.202004250133-0": "toolbox-0.0.7-1.rhaos4.4.el8.noarch",
        "rhcos-4.5/45.81.202005181029-0": "toolbox-0.0.7-1.rhaos4.5.el8.noarch"
    },
    "kernel-devel": {
        "rhcos-4.4/44.81.202004250133-0": "Not present",
        "rhcos-4.5/45.81.202005181029-0": "kernel-devel-4.18.0-147.8.1.el8_1.x86_64"
    },
    "kernel-headers": {
        "rhcos-4.4/44.81.202004250133-0": "Not present",
        "rhcos-4.5/45.81.202005181029-0": "kernel-headers-4.18.0-147.8.1.el8_1.x86_64"
    },
    "libibverbs": {
        "rhcos-4.4/44.81.202004250133-0": "Not present",
        "rhcos-4.5/45.81.202005181029-0": "libibverbs-22.3-1.el8.x86_64"
    },
    "openvswitch2.13": {
        "rhcos-4.4/44.81.202004250133-0": "Not present",
        "rhcos-4.5/45.81.202005181029-0": "openvswitch2.13-2.13.0-25.el8fdp.1.x86_64"
    },
    "perl-Carp": {
        "rhcos-4.4/44.81.202004250133-0": "Not present",
        "rhcos-4.5/45.81.202005181029-0": "perl-Carp-1.42-396.el8.noarch"
    },
    "perl-Errno": {
        "rhcos-4.4/44.81.202004250133-0": "Not present",
        "rhcos-4.5/45.81.202005181029-0": "perl-Errno-1.28-416.el8.x86_64"
    },
    "perl-Exporter": {
        "rhcos-4.4/44.81.202004250133-0": "Not present",
        "rhcos-4.5/45.81.202005181029-0": "perl-Exporter-5.72-396.el8.noarch"
    },
    "perl-File-Path": {
        "rhcos-4.4/44.81.202004250133-0": "Not present",
        "rhcos-4.5/45.81.202005181029-0": "perl-File-Path-2.15-2.el8.noarch"
    },
    "perl-IO": {
        "rhcos-4.4/44.81.202004250133-0": "Not present",
        "rhcos-4.5/45.81.202005181029-0": "perl-IO-1.38-416.el8.x86_64"
    },
    "perl-PathTools": {
        "rhcos-4.4/44.81.202004250133-0": "Not present",
        "rhcos-4.5/45.81.202005181029-0": "perl-PathTools-3.74-1.el8.x86_64"
    },
    "perl-Scalar-List-Utils": {
        "rhcos-4.4/44.81.202004250133-0": "Not present",
        "rhcos-4.5/45.81.202005181029-0": "perl-Scalar-List-Utils-1.49-2.el8.x86_64"
    },
    "perl-Socket": {
        "rhcos-4.4/44.81.202004250133-0": "Not present",
        "rhcos-4.5/45.81.202005181029-0": "perl-Socket-2.027-3.el8.x86_64"
    },
    "perl-Text-Tabs+Wrap": {
        "rhcos-4.4/44.81.202004250133-0": "Not present",
        "rhcos-4.5/45.81.202005181029-0": "perl-Text-Tabs+Wrap-2013.0523-395.el8.noarch"
    },
    "perl-Unicode-Normalize": {
        "rhcos-4.4/44.81.202004250133-0": "Not present",
        "rhcos-4.5/45.81.202005181029-0": "perl-Unicode-Normalize-1.25-396.el8.x86_64"
    },
    "perl-constant": {
        "rhcos-4.4/44.81.202004250133-0": "Not present",
        "rhcos-4.5/45.81.202005181029-0": "perl-constant-1.33-396.el8.noarch"
    },
    "perl-interpreter": {
        "rhcos-4.4/44.81.202004250133-0": "Not present",
        "rhcos-4.5/45.81.202005181029-0": "perl-interpreter-5.26.3-416.el8.x86_64"
    },
    "perl-libs": {
        "rhcos-4.4/44.81.202004250133-0": "Not present",
        "rhcos-4.5/45.81.202005181029-0": "perl-libs-5.26.3-416.el8.x86_64"
    },
    "perl-macros": {
        "rhcos-4.4/44.81.202004250133-0": "Not present",
        "rhcos-4.5/45.81.202005181029-0": "perl-macros-5.26.3-416.el8.x86_64"
    },
    "perl-parent": {
        "rhcos-4.4/44.81.202004250133-0": "Not present",
        "rhcos-4.5/45.81.202005181029-0": "perl-parent-0.237-1.el8.noarch"
    },
    "perl-threads": {
        "rhcos-4.4/44.81.202004250133-0": "Not present",
        "rhcos-4.5/45.81.202005181029-0": "perl-threads-2.21-2.el8.x86_64"
    },
    "perl-threads-shared": {
        "rhcos-4.4/44.81.202004250133-0": "Not present",
        "rhcos-4.5/45.81.202005181029-0": "perl-threads-shared-1.58-2.el8.x86_64"
    }
}
```

**Comment by miabbott** [comment]
Oh the addition of `kernel-devel` and all it's Perl deps  :cry:

**Comment by cgwalters** [comment]
/bugzilla refresh
Whee I love this process of fighting web forms instead of writing code!

**Comment by cgwalters** [comment]
A lot of red for these failing jobs across other commits and repos; failures don't seem related to this change AFAICS.

But I would like to see e2e-azure pass, and ideally e2e-vsphere.  The azure one seems like a likely machineAPI regression?

**Comment by stbenjam** [comment]
e2e-metal-ipi is busted until https://github.com/openshift/cluster-etcd-operator/pull/354 lands

**Comment by cgwalters** [comment]
/hold
https://gitlab.cee.redhat.com/coreos/redhat-coreos/merge_requests/955 should merge for this

**Comment by ashcrow** [comment]
955 has merged

**Comment by jlebon** [comment]
We'll want to backport this to 4.5 once this is in for https://bugzilla.redhat.com/show_bug.cgi?id=1833335.

**Comment by cgwalters** [comment]
/hold cancel
Updated with the fix for time sync.

**Comment by cgwalters** [comment]
OK Azure passed which makes me happier.  I looked at the metal and vsphere failures briefly.  AFAICS vsphere is known failures; being discussed elsewhere.  Metal looks like networking flakes, although I don't see many of those in the periodics.

Overall I think we should get this in because there are a whole lot of fixes, doesn't seem like a good idea to block on debugging those.

**Comment by ashcrow** [comment]
> OK Azure passed which makes me happier. I looked at the metal and vsphere failures briefly. AFAICS vsphere is known failures; being discussed elsewhere. Metal looks like networking flakes, although I don't see many of those in the periodics.
> 
> Overall I think we should get this in because there are a whole lot of fixes, doesn't seem like a good idea to block on debugging those.

Agreed.

cc @abhinavdahiya @sdodson

**Comment by sdodson** [comment]
/lgtm
Failing platforms have at least completed installation phases, so lgtm.

**Comment by lcnsir** [comment]
Hi @cgwalters refer to this PR the kernel-devel will by default exist in this new version of RHCOS  after 45.81.202005181029-0 ?

Thanks

**Comment by cgwalters** [comment]
Please see https://github.com/openshift/enhancements/pull/317 for the future way this will work.

**Pull request merged**
