### PR TITLE
OCPCLOUD-2130: Fix Failuredomains check on manifests test

### PR DESCRIPTION
**Pull request by RadekManak**
CPMS API changed to allow FailureDomains to be a nil value. The openstack manifests tests need to be updated to allow to handle this.

### CODE REVIEW

**Comment by RadekManak** [comment]
All required test passed and non-required look unrelated to me.
/assign @jhixson74

**Comment by RadekManak** [comment]
The API commit got included elsewhere via override of the manifest test. This PR now only contains the change to the manifest test. I have updated the title and description accordingly.

**Comment by r4f4** [comment]
/override ci/prow/altinfra-e2e-aws-ovn-upi
Not related to this PR.

**Comment by RadekManak** [comment]
The API was reverted by https://github.com/openshift/installer/pull/7708. I've added the API changes here again.

**Review by r4f4 — COMMENTED** [review]
/approve

**Pull request merged**
