### PR TITLE
Go.mod: Re-add vfsgen code gen dependency

### PR DESCRIPTION
**Pull request by sgreene570**
`go generate` needs `github.com/shurcool/vsfgen`, which is ignored by the `// +build ignore` tag. 
This changes the build tag so that go mod recognizes the import.

### CODE REVIEW

**Comment by vrutkovs** [comment]
Awesome, thanks!

@LorbusChris do you think this needs to be included in https://github.com/openshift/installer/pull/2745?

**Comment by LorbusChris** [comment]
@sgreene570 could you change the `ignore` tag in `master` as well?

**Comment by vrutkovs** [comment]
/override  ci/prow/e2e-aws 

Known issues

**Comment by sgreene570** [comment]
> @sgreene570 could you change the `ignore` tag in `master` as well?

@LorbusChris, should I make this PR against master before #2745 lands? Dep does not respect build tags like go mod does, so the PR might seem out of place until master is on go mod. We could put these changes into #2745, or just make a PR after #2745 merges.

**Comment by LorbusChris** [comment]
@sgreene570 #2745 needs a rebase now anyway, I'll include it there :)

**Pull request merged**
