### PR TITLE
OCPBUGS-33561,OCPBUGS-33615: capv - missing cores/socket,disk type

### PR DESCRIPTION
**Pull request by jcpowermac**
When implementing capv changes for the installer we missed two features. Enabling the quantity of cores per socket and the disk type of the template (and that of the cloned virtual machines). This PR resolves those two issues.

### CODE REVIEW

**Review by r4f4 — COMMENTED** [review]
/approve

**Comment by jcpowermac** [comment]
issues with https://redhat-internal.slack.com/archives/CFUGK0K9R/p1716901207134199

/test e2e-aws-ovn

**Pull request merged**
