### PR TITLE
OpenStack: Add subnet pools destroy

### PR DESCRIPTION
**Pull request by MaysaMacedo**
This PR adds support for subnet pool deletion on cluster destroy. It uses tags to filter the subnet pools and delete them.

### CODE REVIEW

**Comment by tomassedovic** [comment]
LGTM

I can't merge this since this touches code outside of OpenStack.

**Comment by abhinavdahiya** [comment]
> https://github.com/openshift/installer/pull/1953/commits/fb1cc0d334b803fe2299e14dcca5a451bbe102ea

/approve

the vendor changes look good

would fall back on openstack-approvers to require `approve and lgtm` too.

**Comment by MaysaMacedo** [comment]
ci/prow/e2e-aws-upgrade

**Pull request merged**
