### PR TITLE
OCPBUGS-13104: openstack: Add netcat to the Installer image

### PR DESCRIPTION
**Pull request by pierreprinetti**
This is a manual cherry-pick of e38b029bf526c4f9961d86d87dcf3ca1297e6d75 (https://github.com/openshift/installer/pull/7148)

### CODE REVIEW

**Comment by pierreprinetti** [comment]
Actually it's @mandre I should have assigned

/unassign itzikb-redhat
/assign mandre

**Review by mandre — COMMENTED** [review]
/lgtm
/approve
/label backport-risk-assessed

**Pull request merged**
