### PR TITLE
OCPBUGS-32792: update resolv.conf every time on bootstrap node

### PR DESCRIPTION
**Pull request by yatanaka-1007**
Currently, /etc/resolv.conf on bootstrap node is updated only once. Because of this, /etc/resolv.conf may be incorrect due to timing issues. By this change, /etc/resolv.conf is updtaed at all "up", "dhcp4-update", "dhcp6-update" events.

### CODE REVIEW

**Comment by MaysaMacedo** [comment]
While I agree we should fix this for all platforms, as the fix needs to be backported for OpenStack, I believe we want to extract the OpenStack portion to another PR to facilitate the backporting process.

Tagging folks for thoughts on the above @mkowalski @mandre

**Comment by cybertron** [comment]
Given that this is in response to a race, I wonder if we want to switch the bootstrap node to use the dns-change event. That was added by NetworkManager precisely because relying on other events to update DNS was racy. See the change for cluster nodes here: https://github.com/openshift/machine-config-operator/commit/c3993098c7a3b31bf77ccdae3beb47221eb7d239 We should have the necessary versions of NetworkManager everywhere now so I don't think we need the migration logic from that PR either.

Also, I strongly prefer not to diverge the platforms if we can help it. Debugging becomes much more difficult when there is platform-specific logic in play. It's also likely that if this can happen on OpenStack it can happen anywhere with a similar network configuration.

**Comment by mandre** [comment]
@cybertron For OpenStack, we'll want to backport this fix to at least 4.14. I understand your concerns about consistency across platforms, but at the same time, I'd like to avoid the backport being slowed down by one of the on-prem platforms bugfix verification. Can we assume that if the fix is validated on OpenStack, it's good to backport further?

**Comment by mkowalski** [comment]
>Can we assume that if the fix is validated on OpenStack, it's good to backport further?

Till now we never saw a case of one platform handling this differently than another (this == NM events). I am eager to say that if you validate on OpenStack quicker than we on Baremetal, we may just piggyback on your results

**Comment by yatanaka-1007** [comment]
Thank you all for your comments.
I added "dns-changes" event to the bash script.

I tested "dns-changes" in my OCP 4.15 lab, but it didn't work even though it's using a NetworkManager which should have "dns-changes".

```
[root@yatanaka-ocp-b88m7-bootstrap ~]# journalctl |grep TEST
Apr 24 12:25:32 yatanaka-ocp-b88m7-bootstrap nm-dispatcher[2003]: yatanaka TEST: none hostname
Apr 24 12:25:32 yatanaka-ocp-b88m7-bootstrap nm-dispatcher[2034]: yatanaka TEST:  connectivity-change
Apr 24 12:25:32 yatanaka-ocp-b88m7-bootstrap nm-dispatcher[2052]: yatanaka TEST: lo up
Apr 24 12:25:32 yatanaka-ocp-b88m7-bootstrap nm-dispatcher[2073]: yatanaka TEST: enp3s0 dhcp4-change
Apr 24 12:25:32 yatanaka-ocp-b88m7-bootstrap nm-dispatcher[2088]: yatanaka TEST: enp3s0 up
Apr 24 12:25:32 yatanaka-ocp-b88m7-bootstrap nm-dispatcher[2110]: yatanaka TEST:  connectivity-change
Apr 24 12:25:37 yatanaka-ocp-b88m7-bootstrap nm-dispatcher[3831]: yatanaka TEST: enp3s0 dhcp6-change

  ===> dns-change event was not raised.

[root@yatanaka-ocp-b88m7-bootstrap ~]# rpm -q NetworkManager
NetworkManager-1.42.2-12.el9_2.x86_64

[root@yatanaka-ocp-b88m7-bootstrap ~]# rpm -q --changelog  NetworkManager|head -n9
  :
* Fri Nov 17 2023 Íñigo Huguet <ihuguet@redhat.com> - 1:1.42.2-11
- Add 'dns-change' dispatch event (RHEL-14888)
  :
```

And if we backport this change to older versions, I thought it's possible that "dns-changes" is not implemented.
That's why I'm keeping up, dhcp*-change events.

**Comment by cybertron** [comment]
/retest-required
/test e2e-metal-ipi-ovn
/test e2e-metal-ipi-ovn-dualstack

Failures look unrelated, but I would like to see the various scenarios pass. Otherwise lgtm.

**Comment by MaysaMacedo** [comment]
/lgtm
/test e2e-openstack-dualstack

Failures on the openstack job looks unrelated

**Comment by mkowalski** [comment]
Please note we decided to start moving to systemd path-based activation and rely less on NetworkManager events - https://github.com/openshift/machine-config-operator/pull/4488

It will take time till this propagates, but in principle I don't see a reason why the same mechanism couldn't be used on the bootstrap node.

**Comment by sadasu** [comment]
/hold

Re-evaluating based on https://github.com/openshift/installer/pull/8430#issuecomment-2272176791

**Comment by mkowalski** [comment]
> /hold
> 
> Re-evaluating based on [#8430 (comment)](https://github.com/openshift/installer/pull/8430#issuecomment-2272176791)

I would not hold this PR here. It still fixes the problem that is not handling `dns-change` event and no matter what happens aside, it needs to be handled.

**Comment by sadasu** [comment]
/hold cancel

Thanks for the clarification @mkowalski

**Comment by sadasu** [comment]
/override ci/prow/okd-images

Has been perma-failing.

**Comment by MaysaMacedo** [comment]
@sadasu Looks like the hold is still enforced. Can you try to hold cancel again if you see fit?

**Pull request merged**
