### PR TITLE
OCPBUGS-31813: AWS: bump CCO for permission fix

### PR DESCRIPTION
**Pull request by r4f4**
CCO was requiring the `s3:HeadBucket` permission which doesn't actually exist [1][2]. The issue has been fixed in the lasted version.

[1] https://github.com/openshift/cloud-credential-operator/pull/690
[2] https://github.com/openshift/openshift-docs/pull/70926

### CODE REVIEW

**Comment by r4f4** [comment]
/cc @jhixson74 @rna-afk 
For awareness on the `github.com/microsoft/kiota-authentication-azure-go` and `github.com/microsoftgraph/msgraph-sdk-go` bumps.

**Comment by r4f4** [comment]
/retitle OCPBUGS-31813: AWS: bump CCO for permission fix

**Comment by jianping-shu** [comment]
@r4f4 Can you help backport to 4.15? I need to verify this cco [PR](https://github.com/openshift/cloud-credential-operator/pull/691) with the backporting together.

**Comment by r4f4** [comment]
@jianping-shu actually, I cannot backport this until the CCO backport to 4.15 is merged.

**Comment by jianping-shu** [comment]
> I cannot backport this until the CCO backport to 4.15 is merged.
You are right. I just added cherry-pick-approved label on the CCO backport PR.

**Pull request merged**
