### PR TITLE
Dockerfile.upi.ci: install ipcalc

### PR DESCRIPTION
**Pull request by vrutkovs**
ipcalc util is required for vsphere tests in CI

### CODE REVIEW

**Comment by vrutkovs** [comment]
/hold

Waiting for ART to add the RPM

**Comment by vrutkovs** [comment]
/hold cancel

UPI image is being built on request only, so its safe to merge now

**Comment by vrutkovs** [comment]
/lgtm cancel

`ipcalc` is provided by `initscripts` in RHEL7

**Comment by vrutkovs** [comment]
/hold

RCM needs to tag `initscripts` too. Meanwhile vsphere UPI tests would attempt to avoid using ipcalc binary

**Comment by staebler** [comment]
#1578 removes the dependency on ipcalc.

**Comment by vrutkovs** [comment]
Superseded by #1578

**Pull request closed without merging**
