### PR TITLE
Azure console logs gathering

### PR DESCRIPTION
**Pull request by r4f4**
https://github.com/openshift/installer/pull/5807 should merge first

### CODE REVIEW

**Comment by r4f4** [comment]
verify vendor is now fixed.

**Comment by patrickdillon** [comment]
> verify vendor is now fixed.

What was the issue/solution?

**Comment by r4f4** [comment]
> > verify vendor is now fixed.
> 
> What was the issue/solution?

I'm not really sure tbh. I rebased on top of the current master, ran `go mod tidy && go mod vendor` and saw the same diff that was showing up in CI. Adding thoses changes fixed the problem.

**Pull request merged**
