### PR TITLE
OCPBUGS-31546: azure: use filter when listing SKUs

### PR DESCRIPTION
**Pull request by patrickdillon**
Prior to this commit, most calls to list() in the azure resource sku client were using a package version that did not support filtering list calls. This commit updates all calls to use the location filter and greatly speeds up the performance for validation. In local testing, the total time to generate ignition configs was almost 2 minutes prior to these changes, which reduced the running time to 20 seconds.

### CODE REVIEW

**Comment by patrickdillon** [comment]
/test e2e-azurestack

Looks like it got past the part that would fail in this pr

**Review by r4f4 — COMMENTED** [review]
/lgtm

**Comment by patrickdillon** [comment]
fixed up unit tests in ddb4c483aee64ae5270cdd8705e9d34a4b5523bc

**Comment by patrickdillon** [comment]
removed unused packages in 9ff7906e0600c0411e07abd6acaa0e5e86b61fef

**Comment by patrickdillon** [comment]
Azurestack environment appears to be down

**Pull request merged**
