### PR TITLE
CORS-3282: IBMCloud: CAPI Machines

### PR DESCRIPTION
**Pull request by cjschaef**
Add IBM Cloud VPC CAPI Machine definitions.

Related: https://issues.redhat.com/browse/CORS-3282

### CODE REVIEW

**Review by r4f4 — COMMENTED** [review]
/approve

**Comment by cjschaef** [comment]
This PR is dependent on at least one CAPI update PR:  https://github.com/openshift/installer/pull/9203
Another is likely required, once CAPI is updated further.

**Comment by sadasu** [comment]
altinfra-e2e-ibmcloud-capi-ovn is currently failing with the error:

`level=error msg=failed to fetch Cluster: failed to generate asset "Cluster": failed to create cluster: failed during pre-provisioning: failed creating RHCOS image COS bucket: failed to create cos bucket: BucketAlreadyExists: The requested bucket name is not available. The bucket namespace is shared by all users of the system. Please select a different name and try again.`

**Comment by cjschaef** [comment]
The initial failure of `altinfra-e2e-ibmcloud-capi-ovn` is
```
level=error msg=Attempted to gather debug logs after installation failure: must provide bootstrap host address
level=error msg=failed to fetch Cluster: failed to generate asset "Cluster": failed to create cluster: failed to provision control-plane machines within 15m0s: client rate limiter Wait returned an error: context deadline exceeded
```

This is because, while CAPI was bumped just recently to get the LB reconciliation functionality added (to complete Infra provisioning), the Machine reconciliation is still incomplete, this PR is needed:
https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/pull/2042

Another CAPI update would be required to pull those changes in, to get Machines to properly deploy.

The 2-5 CI test attempts run into issues where previous resources (such as the COS Bucket) do not completely delete prior to the next attempt running.
This needs to be fixed in the CI if I recall (had this discussion in a previous PR, but have not had time to resolve that CI issue).

**Comment by cjschaef** [comment]
I have added in a bump to CAPI as part of this PR, that includes the new VPC Machine reconciliation logic.
This should allow things to progress more than previously.
/test altinfra-e2e-ibmcloud-capi-ovn

I will be asking Power team to review this addition (probably run the CI test for Power), due to bumping CAPI.

**Comment by cjschaef** [comment]
I'm assuming there is a bug in IBM Cloud CAPI VPC Machine reconciliation, I will have to test things out on that side to verify if something needs to be fixed there, on Machines reporting ready.
```
level=error msg=Attempted to gather debug logs after installation failure: must provide bootstrap host address
level=error msg=failed to fetch Cluster: failed to generate asset "Cluster": failed to create cluster: failed to provision control-plane machines within 25m0s: client rate limiter Wait returned an error: context deadline exceeded
```
```
time="2024-11-20T08:31:14Z" level=debug msg="I1120 08:31:14.252035     496 machine.go:638] \"created load balancer backend pool member\" logger=\"controllers.IBMVPCMachine\" ibmvpcmachine=\"openshift-cluster-api-guests/ci-op-gv61n4fv-6483a-dpvrr-master-1\" cluster=\"ci-op-gv61n4fv-6483a-dpvrr\" instanceID=\"0767_473f59de-766c-425e-b203-ca972a52a1f3\" loadBalancerID=\"r014-304baa34-790e-45ea-b8ce-da4d3cf64cd0\" loadBalancerBackendPoolID=\"r014-36c7fe19-8e3c-4a75-84ee-e24c40b70814\" port=6443 loadBalancerBackendPoolMemberID=\"r014-25436178-f68d-415d-b438-fdcb73e1c948\""
time="2024-11-20T08:31:16Z" level=debug msg="E1120 08:31:16.708078     496 controller.go:324] \"Reconciler error\" err=\"error failed to reconcile machine's pool member: error failed creating load balancer backend pool member: The load balancer with ID 'r014-304baa34-790e-45ea-b8ce-da4d3cf64cd0' cannot be updated because its status is 'UPDATE_PENDING'.\" controller=\"ibmvpcmachine\" controllerGroup=\"infrastructure.cluster.x-k8s.io\" controllerKind=\"IBMVPCMachine\" IBMVPCMachine=\"openshift-cluster-api-guests/ci-op-gv61n4fv-6483a-dpvrr-master-1\" namespace=\"openshift-cluster-api-guests\" name=\"ci-op-gv61n4fv-6483a-dpvrr-master-1\" reconcileID=\"840e5c1b-3905-45db-9243-f1c746653450\""
time="2024-11-20T08:31:16Z" level=debug msg="I1120 08:31:16.708860     475 machine_controller_phases.go:306] \"Waiting for infrastructure provider to create machine infrastructure and report status.ready\" controller=\"machine\" controllerGroup=\"cluster.x-k8s.io\" controllerKind=\"Machine\" Machine=\"openshift-cluster-api-guests/ci-op-gv61n4fv-6483a-dpvrr-master-1\" namespace=\"openshift-cluster-api-guests\" name=\"ci-op-gv61n4fv-6483a-dpvrr-master-1\" reconcileID=\"5326550d-ecfe-49fd-974b-ec8b41bd293c\" Cluster=\"openshift-cluster-api-guests/ci-op-gv61n4fv-6483a-dpvrr\" Cluster=\"openshift-cluster-api-guests/ci-op-gv61n4fv-6483a-dpvrr\" IBMVPCMachine=\"openshift-cluster-api-guests/ci-op-gv61n4fv-6483a-dpvrr-master-1\""
time="2024-11-20T08:31:16Z" level=debug msg="I1120 08:31:16.708896     475 machine_controller_noderef.go:61] \"Waiting for infrastructure provider to report spec.providerID\" controller=\"machine\" controllerGroup=\"cluster.x-k8s.io\" controllerKind=\"Machine\" Machine=\"openshift-cluster-api-guests/ci-op-gv61n4fv-6483a-dpvrr-master-1\" namespace=\"openshift-cluster-api-guests\" name=\"ci-op-gv61n4fv-6483a-dpvrr-master-1\" reconcileID=\"5326550d-ecfe-49fd-974b-ec8b41bd293c\" Cluster=\"openshift-cluster-api-guests/ci-op-gv61n4fv-6483a-dpvrr\" Cluster=\"openshift-cluster-api-guests/ci-op-gv61n4fv-6483a-dpvrr\" IBMVPCMachine=\"openshift-cluster-api-guests/ci-op-gv61n4fv-6483a-dpvrr-master-1\""
time="2024-11-20T08:31:21Z" level=debug msg="I1120 08:31:21.001770     496 machine.go:594] \"found existing load balancer pool member for machine\" logger=\"controllers.IBMVPCMachine\" ibmvpcmachine=\"openshift-cluster-api-guests/ci-op-gv61n4fv-6483a-dpvrr-master-2\" cluster=\"ci-op-gv61n4fv-6483a-dpvrr\" machineName=\"ci-op-gv61n4fv-6483a-dpvrr-master-2\" internalIP=\"10.241.128.4\" poolID=\"r014-36c7fe19-8e3c-4a75-84ee-e24c40b70814\" loadBalancerID=\"r014-304baa34-790e-45ea-b8ce-da4d3cf64cd0\""
time="2024-11-20T08:31:25Z" level=debug msg="Checking that machine ci-op-gv61n4fv-6483a-dpvrr-bootstrap has provisioned..."
time="2024-11-20T08:31:25Z" level=debug msg="Machine ci-op-gv61n4fv-6483a-dpvrr-bootstrap has not yet provisioned: Pending"
time="2024-11-20T08:31:25Z" level=debug msg="Checking that machine ci-op-gv61n4fv-6483a-dpvrr-master-0 has provisioned..."
time="2024-11-20T08:31:25Z" level=debug msg="Machine ci-op-gv61n4fv-6483a-dpvrr-master-0 has status: Provisioned"
time="2024-11-20T08:31:25Z" level=debug msg="Checking that IP addresses are populated in the status of machine ci-op-gv61n4fv-6483a-dpvrr-master-0..."
time="2024-11-20T08:31:25Z" level=debug msg="Checked IP InternalDNS: ci-op-gv61n4fv-6483a-dpvrr-master-0"
time="2024-11-20T08:31:25Z" level=debug msg="Checked IP Hostname: ci-op-gv61n4fv-6483a-dpvrr-master-0"
time="2024-11-20T08:31:25Z" level=debug msg="Found internal IP address: 10.241.0.6"
time="2024-11-20T08:31:25Z" level=debug msg="Machine ci-op-gv61n4fv-6483a-dpvrr-master-0 is ready. Phase: Provisioned"
time="2024-11-20T08:31:25Z" level=debug msg="Checking that machine ci-op-gv61n4fv-6483a-dpvrr-master-1 has provisioned..."
time="2024-11-20T08:31:25Z" level=debug msg="Machine ci-op-gv61n4fv-6483a-dpvrr-master-1 has not yet provisioned: Pending"
time="2024-11-20T08:31:25Z" level=debug msg="Checking that machine ci-op-gv61n4fv-6483a-dpvrr-master-2 has provisioned..."
time="2024-11-20T08:31:25Z" level=debug msg="Machine ci-op-gv61n4fv-6483a-dpvrr-master-2 has not yet provisioned: Pending"
time="2024-11-20T08:31:26Z" level=debug msg="E1120 08:31:26.124852     496 controller.go:324] \"Reconciler error\" err=\"error failed to reconcile machine's pool member: error failed creating load balancer backend pool member: The load balancer with ID 'r014-304baa34-790e-45ea-b8ce-da4d3cf64cd0' cannot be updated because its status is 'UPDATE_PENDING'.\" controller=\"ibmvpcmachine\" controllerGroup=\"infrastructure.cluster.x-k8s.io\" controllerKind=\"IBMVPCMachine\" IBMVPCMachine=\"openshift-cluster-api-guests/ci-op-gv61n4fv-6483a-dpvrr-master-2\" namespace=\"openshift-cluster-api-guests\" name=\"ci-op-gv61n4fv-6483a-dpvrr-master-2\" reconcileID=\"bd97873e-a362-4b35-90a1-c57d5b0ca3e3\""
time="2024-11-20T08:31:36Z" level=debug msg="E1120 08:31:36.353721     496 controller.go:324] \"Reconciler error\" err=\"error failed to reconcile machine's pool member: error failed creating load balancer backend pool member: The load balancer with ID 'r014-304baa34-790e-45ea-b8ce-da4d3cf64cd0' cannot be updated because its status is 'UPDATE_PENDING'.\" controller=\"ibmvpcmachine\" controllerGroup=\"infrastructure.cluster.x-k8s.io\" controllerKind=\"IBMVPCMachine\" IBMVPCMachine=\"openshift-cluster-api-guests/ci-op-gv61n4fv-6483a-dpvrr-bootstrap\" namespace=\"openshift-cluster-api-guests\" name=\"ci-op-gv61n4fv-6483a-dpvrr-bootstrap\" reconcileID=\"28db2954-6ab8-4c70-8bad-abb7db511658\""
```

Or, it is simply not enough time to allow the LB updates to complete to mark the Machines ready.

Otherwise, the `installer` side appears to be okay, I think. So, I don't see any reason to hold this up currently (especially since this merging would make future testing significantly easier).

**Comment by patrickdillon** [comment]
I'm ok with merging this from the IBMCloud side (it's feature gated), but I don't want to break powervs, so want to see the tests pass...

Also, do we need to update the infrastructure components as part of your capi provider bump https://github.com/openshift/installer/blob/master/data/data/cluster-api/ibmcloud-infrastructure-components.yaml?

**Comment by jeffnowicki** [comment]
@mjturek Mike - can you please evaluate the capi powervs failure? determine if it's related to code changes or not? thank you

**Comment by cjschaef** [comment]
It didn't appear to be any changes to the `infrastructure-components`, when I bumped the CAPI version (after rebuilding them using the matching commit level).
```
% diff data/data/cluster-api/ibmcloud-infrastructure-components.yaml ../../../sigs.k8s.io/cluster-api-provider-ibmcloud/out/infrastructure-components.yaml
%
```

**Pull request merged**
