### PR TITLE
Fix azure install blob, cached images issues

### PR DESCRIPTION
**Pull request by walidshaari**
fix issue #4034
Revert azure terraform installation to pre-beta5

### CODE REVIEW

**Comment by walidshaari** [comment]
Followed @jomeier instructions and tested it after building the openshift-install
tested the installation, see attached the installation log file.

[openshift_install.log](https://github.com/openshift/installer/files/5077659/openshift_install.log)
image
image

credits to @jomeier for guiding me and walking me through the whole process serval times

**Comment by jomeier** [comment]
@walidshaari 
This seems to be a duplicate of my PR https://github.com/openshift/installer/pull/4054 ;-)

**Comment by walidshaari** [comment]
This is duplicate for PR #4054, closing it

**Pull request closed without merging**
