### PR TITLE
Update installconfig validation for Nutanix

### PR DESCRIPTION
**Pull request by thunderboltsid**
Expect credentialsMode for Nutanix to be Manual.

### CODE REVIEW

**Review by staebler — COMMENTED** [review]
Is this change necessary? Are we planning to have CredentialsRequests for Nutanix? If the answers to the previous are yes, then we also need changes to the description of the `credentialsMode` field.
https://github.com/openshift/installer/blob/73522dd14c8f0c8b905056624dc96ef3a2e632df/pkg/types/installconfig.go#L159

**Comment by thunderboltsid** [comment]
> 

We do have CredentialsRequest for Nutanix. Good catch on the description. Will fix that.

**Comment by thunderboltsid** [comment]
> Is this change necessary? Are we planning to have CredentialsRequests for Nutanix? If the answers to the previous are yes, then we also need changes to the description of the `credentialsMode` field.
> 
> https://github.com/openshift/installer/blob/73522dd14c8f0c8b905056624dc96ef3a2e632df/pkg/types/installconfig.go#L159

We do have CredentialsRequest for Nutanix. Good catch on the description. Will fix that.

**Pull request merged**
