### PR TITLE
OCPBUGS-2130: vSphere - finding networks use full path cluster

### PR DESCRIPTION
**Pull request by jcpowermac**
In previous releases we didn't use full paths for
cluster. Since we are now using full paths generating the path is incorrect. This PR removes that.

### CODE REVIEW

**Comment by rvanderp3** [comment]
/lgtm
/approve
/hold

placing a hold pending CI

**Comment by jinyunma** [comment]
pre-merge test is passed, details can be found from comments in bug.
/label qe-approved

**Pull request merged**
