### PR TITLE
Bug 2037209: update alibaba for provider spec api changes

### PR DESCRIPTION
**Pull request by elmiko**
This change updates the alibaba provider spec usage related to the
vswitch, security groups, and resource group. The API for the provider
spec is changing to use a discriminated union to capture the various
methods for finding resources (by id, name, or tags).

It also updates several machine api references to note the bifurcated
nature of the api version between v1beta1 and v1.

### CODE REVIEW

**Comment by elmiko** [comment]
this change will require https://github.com/openshift/api/pull/1096 to merge first, it will not build until we can vendor those changes here.
/hold

**Comment by elmiko** [comment]
this will also need the actuator updated to work properly, see https://github.com/openshift/cluster-api-provider-alibaba/pull/26

**Comment by elmiko** [comment]
i have added a second commit to vendor from my branch of the api, this is only for testing and should be replaced before we merge.

**Review by staebler — COMMENTED** [review]
/approve
These changes look good, but I need to do some locally testing for validation.

**Comment by elmiko** [comment]
this will need an update to the vendor to match k8s 1.23, i am coordinating with @staebler to get that change in a separate PR and then we will rebase this PR on top of it.

**Comment by elmiko** [comment]
i have rebuilt this on top of #5563

**Comment by JoelSpeed** [comment]
Changes LGTM once we have the API change merged

**Comment by elmiko** [comment]
i have revendored for the API changes, we will still need to manually test this one more time and also it will need to wait for #5563

**Comment by elmiko** [comment]
update
* added fix for version on line https://github.com/openshift/installer/blob/master/pkg/asset/machines/alibabacloud/machines.go#L93

**Comment by elmiko** [comment]
update
* fixed group type for AlibabaCloudMachineProviderSpec
* rebased on top of #5563

**Comment by elmiko** [comment]
i am removing the hold here since #5563 has merged
/hold cancel

**Comment by kwoodson** [comment]
I was able to successfully deploy nodes:
```
test-rx6ff-worker-us-east-1a-vdr6m   Ready    worker   12m   v1.23.0+06791f6
test-rx6ff-worker-us-east-1b-8l777   Ready    worker   12m   v1.23.0+06791f6
test-rx6ff-worker-us-east-1b-plcst   Ready    worker   15m   v1.23.0+06791f6
```
New fields used:
```
        resourceGroup:
          id: rg-xxxxxxxx
          type: ID
```

/lgtm

**Comment by elmiko** [comment]
removing the hold as we have all pieces in place and good manual testing
/hold cancel

**Pull request merged**
