### PR TITLE
Use string as the asset map key instead of the object itself

### PR DESCRIPTION
**Pull request by rajatchopra**
The store has a map of assets and states, where the key is the asset object currently. This is an issue with json serialization and deserialization.
If we move the key to be the Name() or Type(), then deserialization can happen assuming there are only singleton asset objects (which they are in this project).
This PR only changes the asset map key to be the Name() of the asset. We can use reflect.TypeOf(assetObj).String() but for that we need at least #344 and some normalization of package reference paths and pointers.

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
@rajatchopra this should be done after https://github.com/openshift/installer/pull/344; maybe just rebase on that for now.

**Comment by abhinavdahiya** [comment]
Also with the install core moving towards #344 ; i would like to see this change in https://github.com/openshift/installer/pull/388 than a separate PR. unless you think we can go ahead with this without conflicting with #344

**Comment by rajatchopra** [comment]
> Also with the install core moving towards #344 ; i would like to see this change in #388 than a separate PR. unless you think we can go ahead with this without conflicting with #344

If we use Name() as the string, then this does not need to wait for #344. If we choose to use Type() as the key string, then we need to wait for #344. #388 will depend on both this PR and #344. I have put up this PR to this particular feedback: do we use type? Or do we use name()?

The problem with type is that no two assets can be of type UserProvided for example or even CertKey as another example. They have to be their own asset object though they can use UserProvided/CertKey as part of Generate.
The problem with Name() is only that it should be unique. But that can be a problem if the Name is dynamically generated (as an example ingress certKey).

**Comment by abhinavdahiya** [comment]
@rajatchopra all this is still falls under #388, it would makes sense to make decision in #388 based on the fact that what is colliding and easy for serialization and deserialization. This change is not a concern for #344 i suppose.

**Comment by rajatchopra** [comment]
Closing this out. The commit has been cherry picked into #388.

**Pull request closed without merging**
