### PR TITLE
Bug 1738354: pkg/asset/machines/aws/machines: Request encrypted root volumes

### PR DESCRIPTION
**Pull request by wking**
The AWS cluster-API provider just started respecting this property in openshift/cluster-api-provider-aws@99de8f2015 (openshift/cluster-api-provider-aws#245).  By asking for it, we'll get encrypted root volumes for compute machines and remove the need for copy-and-encrypting the control-plane machines.

This PR also partially reverts 0c370dd811 (#1296).  This isn't a clean revert; for example, I left the ability to destroy images which are tagged as owned by the cluster.  And we're still copy-and-encrypting for the bootstrap machine until the AWS Terraform provider supports requesting encrypted root volumes (terraform-providers/terraform-provider-aws#8624).  But with this commit, we no longer use the copied AMI for control-plane nodes, which gets us one step closer to having the cluster API provision them without installer intervention.

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
The control-plane is still created by the installer right, so this change is a regression that control-plane is not encrypted anymore...

/hold

**Comment by wking** [comment]
[e2e-aws][1] failed on:

```
[Feature:Image][triggers] Image change build triggers TestSimpleImageChangeBuildTriggerFromImageStreamTagSTI [Suite:openshift/conformance/parallel]

fail [k8s.io/kubernetes/test/e2e/framework/framework.go:338]: Aug 5 19:37:52.094: Couldn't delete ns: "e2e-test-image-change-build-triggger-75f82": namespace e2e-test-image-change-build-triggger-75f82 was not deleted with limit: timed out waiting for the condition, namespace is empty but is not yet removed (&errors.errorString{s:"namespace e2e-test-image-change-build-triggger-75f82 was not deleted with limit: timed out waiting for the condition, namespace is empty but is not yet removed"})
```

Seems unrelated (and like [rhbz#1713135][2]).

/retest

[1]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_installer/2160/pull-ci-openshift-installer-master-e2e-aws/7063
[2]: https://bugzilla.redhat.com/show_bug.cgi?id=1713135

**Comment by abhinavdahiya** [comment]
Also looking at https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSEncryption.html#encryption-by-default and other docs it looks like the setting needs to be enabled region level before the API can use this??

**Comment by wking** [comment]
> The control-plane is still created by the installer right, so this change is a regression that control-plane is not encrypted anymore...

Ah, right :p.  I'll roll that part back and keep passing the encrypted AMI to Terraform for those machines.

>  ... other docs it looks like the setting needs to be enabled region level before the API can use this??

Yeah, and that's obviously not great.  But this PR isn't about that setting (although I've mentioned it in the past in this space); this PR is about explicitly setting a given root volume encrypted.  Which Terraform doesn't support yet (terraform-providers/terraform-provider-aws#8624), but which the cluster-API provider now does support.

**Comment by wking** [comment]
Back to copy-and-encrypt AMI IDs for control-plane machines with dc74ef7c5 -> 58c641323.

**Comment by abhinavdahiya** [comment]
https://github.com/openshift/installer/pull/2160/commits/58c641323b309e9fe0ea43143056d410060de19d

doesn't capture the reality that we are still copying AMIs.

**Comment by sdodson** [comment]
/close
deferred until PM asks for this

**Comment by wking** [comment]
Terraform 2.23.0 (which we're pulling in with #2676 is getting us terraform-providers/terraform-provider-aws#7757 which might also let us drop the copy-and-encrypt.  Worth reopening this now that we have that on the table?

**Pull request closed without merging**
