### PR TITLE
OCPBUGS-36092: bump go-retryablehttp for CVE fix

### PR DESCRIPTION
**Pull request by r4f4**
SSIA

### CODE REVIEW

**Comment by patrickdillon** [comment]
You're bumping the module versions in the indirect dependencies. Will those be overwritten next time the direct dependency (IBM go sdk) is updated?

**Comment by r4f4** [comment]
> You're bumping the module versions in the indirect dependencies. Will those be overwritten next time the direct dependency (IBM go sdk) is updated?

Good question. I did the following experiment:
```bash
 $ go get sigs.k8s.io/cluster-api-provider-ibmcloud@104ee47 # latest master
go: downloading sigs.k8s.io/cluster-api-provider-ibmcloud v0.9.0-alpha.0.0.20240621125855-104ee4757436
go: downloading github.com/IBM/vpc-go-sdk v0.52.0
go: downloading github.com/ppc64le-cloud/powervs-utils v0.0.0-20240610070307-1c0d75a5c247
go: downloading github.com/IBM/ibm-cos-sdk-go v1.11.0
go: downloading github.com/IBM/platform-services-go-sdk v0.64.0
go: downloading github.com/coreos/ignition/v2 v2.19.0
go: downloading github.com/spf13/cobra v1.8.1
go: downloading google.golang.org/protobuf v1.34.1
go: downloading google.golang.org/genproto/googleapis/rpc v0.0.0-20240513163218-0867130af1f8
go: downloading github.com/aws/aws-sdk-go v1.53.5
go: downloading google.golang.org/genproto/googleapis/api v0.0.0-20240506185236-b8a5c65736ae
go: downloading google.golang.org/genproto v0.0.0-20240401170217-c3f982113cda
go: upgraded github.com/IBM/ibm-cos-sdk-go v1.10.3 => v1.11.0
go: upgraded github.com/IBM/platform-services-go-sdk v0.62.11 => v0.64.0
go: upgraded github.com/IBM/vpc-go-sdk v0.51.0 => v0.52.0
go: upgraded github.com/aws/aws-sdk-go v1.50.25 => v1.53.5
go: upgraded github.com/coreos/ignition/v2 v2.18.0 => v2.19.0
go: added github.com/ppc64le-cloud/powervs-utils v0.0.0-20240610070307-1c0d75a5c247
go: upgraded github.com/spf13/cobra v1.8.0 => v1.8.1
go: upgraded go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp v0.48.0 => v0.49.0
go: upgraded go.opentelemetry.io/otel v1.23.0 => v1.24.0
go: upgraded go.opentelemetry.io/otel/metric v1.23.0 => v1.24.0
go: upgraded go.opentelemetry.io/otel/trace v1.23.0 => v1.24.0
go: upgraded golang.org/x/crypto v0.23.0 => v0.24.0
go: upgraded golang.org/x/net v0.25.0 => v0.26.0
go: upgraded golang.org/x/oauth2 v0.18.0 => v0.20.0
go: upgraded golang.org/x/sync v0.6.0 => v0.7.0
go: upgraded golang.org/x/sys v0.20.0 => v0.21.0
go: upgraded golang.org/x/term v0.20.0 => v0.21.0
go: upgraded golang.org/x/text v0.15.0 => v0.16.0
go: upgraded google.golang.org/genproto/googleapis/api v0.0.0-20240205150955-31a09d347014 => v0.0.0-20240506185236-b8a5c65736ae
go: upgraded google.golang.org/genproto/googleapis/rpc v0.0.0-20240213162025-012b6fc9bca9 => v0.0.0-20240513163218-0867130af1f8
go: upgraded google.golang.org/grpc v1.61.1 => v1.63.2
go: upgraded google.golang.org/protobuf v1.33.0 => v1.34.1
go: upgraded sigs.k8s.io/cluster-api v1.7.1 => v1.7.3
go: upgraded sigs.k8s.io/cluster-api-provider-ibmcloud v0.8.0 => v0.9.0-alpha.0.0.20240621125855-104ee4757436

 $ go mod tidy
 $
 $ git cdiff | grep retryablehttp
 $
```
So no downgrades. Is that enough or should I keep checking?

**Review by barbacbd — COMMENTED** [review]
/lgtm

**Comment by r4f4** [comment]
/hold

Until Patrick confirms if https://github.com/openshift/installer/pull/8653#issuecomment-2189066554 is enough to convince him.

**Comment by patrickdillon** [comment]
/hold cancel

WFM!

**Pull request merged**
