### PR TITLE
Bug 1902059: Bound SA keys: add default key in case user did not supply it

### PR DESCRIPTION
**Pull request by stlaz**
/cc @sttts @tnozicka

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
I would personally like to see this key being generated in the operator when none is provided. Keeping the keys generated in installer to minimum.

**Comment by stlaz** [comment]
The interfaces of the installer appear to be made exactly for this purpose, is there a reason to move the logic to the operator?

**Comment by stlaz** [comment]
/close
closing for now in favour of https://github.com/openshift/cluster-kube-apiserver-operator/pull/1019 which generates the keypair inside the render command

**Pull request closed without merging**
