### PR TITLE
CORS-3593: go.mod: bump k8s dependencies

### PR DESCRIPTION
**Pull request by r4f4**
As part of the 4.17 branching list.

### CODE REVIEW

**Comment by patrickdillon** [comment]
/approve

LGTM based on tests

**Comment by patrickdillon** [comment]
none of the test failures  look related.

/lgtm

**Comment by patrickdillon** [comment]
@2uasimojo I think hive likes to know when we bump these depencies...

**Comment by 2uasimojo** [comment]
> @2uasimojo I think hive likes to know when we bump these depencies...

Thanks Patrick! cc @lleshchi

**Comment by r4f4** [comment]
> > @2uasimojo I think hive likes to know when we bump these depencies...
> 
> Thanks Patrick! cc @lleshchi

Good to know. I'll add to the story description that we should notify Hive when we do the bump after branching.

**Pull request merged**
