### PR TITLE
Rename labels from sigs.k8s.io to machine.openshift.io

### PR DESCRIPTION
**Pull request by spangenberg**
/cc bison

### CODE REVIEW

**Comment by enxebre** [comment]
/hold
needs https://github.com/openshift/cluster-api-provider-aws/pull/161#issuecomment-465275282

**Comment by enxebre** [comment]
this is blocked by https://github.com/openshift/machine-api-operator/pull/213

**Comment by ingvagabund** [comment]
@abhinavdahiya PTAL

**Comment by abhinavdahiya** [comment]
/approve

cc @flaper87 will changes to openstack manifests look good.

**Pull request merged**
