### PR TITLE
BUG 1707096: gather: collect secret names for failure analysis

### PR DESCRIPTION
**Pull request by deads2k**
This lists all secret names and then annotations for all but the SA token and dockercfg secrets.

Related to https://bugzilla.redhat.com/show_bug.cgi?id=1707096

### CODE REVIEW

**Comment by wking** [comment]
/hold

This is not a release blocker, while #1727 [is][1].  The hold will keep the merge queue clear until #1727 lands.

[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1707877

**Comment by wking** [comment]
#1727 has landed.

/hold cancel
/retest

**Comment by wking** [comment]
[e2e-aws-upgrade][1]:

```
May  8 21:53:40.362: Could not reach HTTP service through a6c482ad171db11e998ba0ac6288c268-241050195.us-east-1.elb.amazonaws.com:80 after 2m0s
```

That's https://bugzilla.redhat.com/show_bug.cgi?id=1690087

/retest

[1]: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_installer/1722/pull-ci-openshift-installer-master-e2e-aws-upgrade/327

**Comment by smarterclayton** [comment]
As we get closer to release, please ensure code changes have a bug and the bug is associated in the PR title - follow the conventions described in previous emails about how to associate bugs with PRs.  The PR title must be `Bug XXXX: <description>`.

This PR has an extra colon between `Bug` and the number, causing it to not match.

**Pull request merged**
