### PR TITLE
docs: update OWNERS for baremetal and openstack docs

### PR DESCRIPTION
**Pull request by stbenjam**
This adds an OWNERS file to docs/user/metal.

### CODE REVIEW

**Comment by patrickdillon** [comment]
Why no `baremetal-reviewers`?

**Comment by stbenjam** [comment]
> Why no `baremetal-reviewers`?

This PR is identical to the other OWNERS for platforms

**Comment by abhinavdahiya** [comment]
This differs from https://github.com/openshift/installer/blob/master/docs/design/baremetal/OWNERS

**Comment by stbenjam** [comment]
/shrug

I've fixed it. Why is it inconsistent? Would you like me to fix the other platforms while I'm here?

**Comment by patrickdillon** [comment]
> I've fixed it. Why is it inconsistent? Would you like me to fix the other platforms while I'm here?

Thanks. I think fixing OpenStack could be a good idea.

**Comment by stbenjam** [comment]
I've fixed OpenStack as well.

**Pull request merged**
