### PR TITLE
[GCP] Bootstrap Signed URL Service Account Key Removal - CORS-2853

### PR DESCRIPTION
**Pull request by ArthurVardevanyan**
This PR is to remove the need for using Service Account Keys to sign URLs in GCP, a custom provider needs to be used, since Google presently does not support this withi  theirs.

Required Change for GCP Service Account used for Installing OpenShit in GCP
- Replace ```roles/iam.serviceAccountKeyAdmin``` with  ```roles/iam.serviceAccountTokenCreator```

Custom Terraform Provider with Support for using SignBlobs with Signed URLs: 
 - https://github.com/ArthurVardevanyan/terraform-provider-avgcp

Presently, set the Installer to always create the bootstrap service account, due to some environments not being able to auto determine the service account currently in use.

### CODE REVIEW

**Review by barbacbd — COMMENTED** [review]
@ArthurVardevanyan can you split up the commits into the vendor changes and then the commits to the installer code base?

**Comment by barbacbd** [comment]
/retitle [GCP] Bootstrap Signed URL Service Account Key Removal - CORS-2853

**Comment by patrickdillon** [comment]
It would be better if we could generate the ignition stub & signed URL in go code (like we do with AWS) and pass it into Terraform. I believe @ArthurVardevanyan you mentioned that there is already support for generating signed urls without keys in the gcp sdk. 

This approach would be preferable for a variety of reasons: Terraform providers are making it difficult to build the installer, we are moving away from Terraform imminently due to the BSL license change so we will need to rewrite this for 4.16, it will be trivial to introduce ignition proxy support.

That said, deadlines are tight so we will need to find the best path forward given the circumstances.

**Comment by ArthurVardevanyan** [comment]
@patrickdillon That makes sense, I went with this route initially since it appeared to be more of a drop in replacement. 

Regardless of  implementation method, their is a difference in the the automated test environment and our environment that is causing a failure during the automated tests here for this google library. 
Still trying to figure out the delta.  I assume it is related to the service account key. I only tested with Compute Engine Metadata and OpenShift Federated Identitys so far.

Signed URL REF: https://github.com/ArthurVardevanyan/terraform-provider-avgcp/blob/v0.0.0/internal/provider/gcs_object_url_sign_blob__resource.go#L108-L145

**Review by barbacbd — COMMENTED** [review]
@ArthurVardevanyan release 4.16 is progressing with the alternate install using cluster API. As patrick mentioned, the go gcp sdk will be used to accomplish something similar to this PR. Leaving this PR open as a reference.

**Comment by barbacbd** [comment]
/close
In favor of https://github.com/openshift/installer/pull/8248

**Pull request closed without merging**
