### PR TITLE
permissions.go: configure crendential check with installer session

### PR DESCRIPTION
**Pull request by abhinavdahiya**
previously the credential checker created an independent session, therefore all the configuration
done by installer like increasing MaxRetries etc were skipped.

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
/hold cancel

23333a60e74f1cb1a1c2b0e8468b51d88addb2a2 brings in correct vendor update.

**Comment by wking** [comment]
Mitigates [rhbz#1767936](https://bugzilla.redhat.com/show_bug.cgi?id=1767936).

**Pull request merged**
