### PR TITLE
[release-4.16] OCPBUGS-43967: Revendor assisted service external platform oci

### PR DESCRIPTION
**Pull request by pawanpinjarkar**
Manual cherry-pick of https://github.com/openshift/installer/pull/9147

### CODE REVIEW

**Comment by zaneb** [comment]
This is revendoring to the same commit as the 4.17 PR, which is presumably in the 4.17 (or worse, 4.18) branch. That seems risky to me as it will pick up far more commits than we are intending, with unknown consequences.
What is that patch that we actually need? It would be safer to backport that patch to the 4.16 branch of assisted-installer and then rebase to that.

**Comment by pawanpinjarkar** [comment]
> This is revendoring to the same commit as the 4.17 PR, which is presumably in the 4.17 (or worse, 4.18) branch. That seems risky to me as it will pick up far more commits than we are intending, with unknown consequences. What is that patch that we actually need? It would be safer to backport that patch to the 4.16 branch of assisted-installer and then rebase to that.

in 4.17 PR, we only revendored this specific commit [openshift/assisted-service@d41f536](https://github.com/openshift/assisted-service/commit/d41f53691d6e19b87fb5adffdb88ce3568fb0c82) 

If it is safer to not cherrypick from 4.17 but do a seperate revendoring of assisted-service in 4.16 (this specific commit [openshift/assisted-service@d41f536](https://github.com/openshift/assisted-service/commit/d41f53691d6e19b87fb5adffdb88ce3568fb0c82) ), I can close this PR and open a new one.

**Comment by zaneb** [comment]
The specific point we are revendoring to (https://github.com/openshift/assisted-service/commit/6573b5d7021d) is already part of the release-4.16 branch, so we are not pulling in any changes to assisted-service that post-date this release. A manual review of the diff shows nothing too alarming.
/label backport-risk-assessed

**Pull request merged**
