### PR TITLE
data/aws/vpc: Add an S3 endpoint to new VPCs

### PR DESCRIPTION
**Pull request by wking**
As suggested by @cuppett, this allows registry <-> S3 transfers to bypass the (NAT) gateways.  Traffic over the NAT gateways costs money, so the new endpoint should make S3 access from the cluster cheaper (and possibly more reliable).  This also allows for additional security policy flexibility, although I'm not taking advantage of that in this commit.  Docs for VPC endpoints are [here][1], [here][2], [here][3], and [here][4].

Endpoints [do not currently support cross-region requests][1].  And based on discussion with @cuppett, adding an endpoint may *break* access to S3 on other regions.  But I can't find docs to back that up, and [the docs][3] say:

> We use the most specific route that matches the traffic to determine how to route the traffic (longest prefix match).  If you have an existing route in your route table for all internet traffic (0.0.0.0/0) that points to an internet gateway, the endpoint route takes precedence for all traffic destined for the service, because the IP address range for the service is more specific than 0.0.0.0/0.  All other internet traffic goes to your internet gateway, including traffic that's destined for the service in other regions.

which suggests that access to S3 on other regions may be unaffected.  In any case, our registry buckets, and likely any other buckets associated with the cluster, will be living in the same region.

`concat` is documented [here][5].

[1]: https://docs.aws.amazon.com/vpc/latest/userguide/vpc-endpoints-s3.html
[2]: https://docs.aws.amazon.com/vpc/latest/userguide/vpc-endpoints.html
[3]: https://docs.aws.amazon.com/vpc/latest/userguide/vpce-gateway.html
[4]: https://www.terraform.io/docs/providers/aws/r/vpc_endpoint.html
[5]: https://www.terraform.io/docs/configuration/interpolation.html#concat-list1-list2-

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
https://www.terraform.io/docs/providers/aws/r/vpc_endpoint.html#subnet_ids vs https://www.terraform.io/docs/providers/aws/r/vpc_endpoint.html#route_table_ids

**Comment by wking** [comment]
Only `route_table_ids` applies to Gateway mode.

**Comment by abhinavdahiya** [comment]
> Only `route_table_ids` applies to Gateway mode.

Oh, and `Gateway` is deafult https://www.terraform.io/docs/providers/aws/r/vpc_endpoint.html#vpc_endpoint_type :+1:

**Comment by abhinavdahiya** [comment]
Is there a precedent for this kind of setup in OpenShift @cuppett ?

**Comment by cuppett** [comment]
Not in our hosted environments. Those and our reference architectures have historically taken a much more vanilla approach to each cloud.

Using ALBs, NAT gateways and VPC endpoints is new and applies optimizations and competencies to this cloud. Excited to bring more maturity to our offering. All are relatively new within AWS (last couple years) and is helping to catch us up.

**Comment by abhinavdahiya** [comment]
@dgoodwin not sure who keeps track of all these *unmanaged* things. heads up.

/approve

**Comment by dgoodwin** [comment]
Will this come out tagged with the expected tags?

And I assume we need to add VPC endpoint cleanup to hiveutil's code.

**Comment by wking** [comment]
> Will this come out tagged with the expected tags?

At least [Terraform][1] does not seem to allow tagging for this resource.  It may be untaggable in AWS.

> And I assume we need to add VPC endpoint cleanup to hiveutil's code.

Maybe it doesn't block VPC deletion and is automatically removed when the VPC is deleted (in which case we would not need Hive changes).  I'll see if I can tell from the CI logs.

[1]: https://www.terraform.io/docs/providers/aws/r/vpc_endpoint.html

**Comment by abhinavdahiya** [comment]
> The logs won't be particularly helpful until #730 lands. I'll circle back to this after that happens.

deletion doesn't need that right?

**Comment by wking** [comment]
> > The logs won't be particularly helpful until #730 lands. I'll circle back to this after that happens.
>
> deletion doesn't need that right?

No, but we're not going to see anything about this endpoint in the deletion logs.  What I want is to see *creation* (and ideally an ID) for the new resource, and then I'll check to make sure it's gone after CI wraps up.

**Comment by abhinavdahiya** [comment]
/hold
need :+1: from `hive` team @joelddiaz

**Comment by joelddiaz** [comment]
I looked at this a bit, and adding the endpoint does case panics in the uninstall due to some assumptions about the kinds of default fields found in a route table (easy fix).

You can't leave the endpoint hanging around as that will block the VPC from ever being deleted. Unfortunately, the endpoints don't appear to be taggable objects, so we'll need to add a dependency in the VPC deletion path to find any endpoints associated with the VPC being deleted.

**Comment by joelddiaz** [comment]
FWIW, we've got the endpoint deletion merged now. so we're ready for this on the uninstall side of things https://github.com/openshift/hive/pull/122

**Comment by wking** [comment]
I've rebased onto master and pulled in openshift/hive#122 with 1a1dc49 -> e205898.

**Comment by abhinavdahiya** [comment]
> I've rebased onto master and pulled in [openshift/hive#122](https://github.com/openshift/hive/pull/122) with [1a1dc49](https://github.com/openshift/installer/commit/1a1dc49b91eb4e1446d6e7bf8e56a52f309fed5e) -> [e205898](https://github.com/openshift/installer/commit/e20589814f8a059b2889e0517c949b5ce0e2b6c6).

/lgtm

/retest

**Pull request merged**
