### PR TITLE
[release-4.15] OCPBUGS-33402, OCPBUGS-33354: Use assisted-image-service for ignition editing

### PR DESCRIPTION
**Pull request by zaneb**
Use assisted-image-service's implementation of ignition editing to decide the correct files to edit. This does the Right Thing for s390, and also expands the ignition image when required to allow for oversized ignition.

### CODE REVIEW

**Comment by zaneb** [comment]
/retitle [release-4.15] OCPBUGS-33402, OCPBUGS-33354: Use assisted-image-service for ignition editing
/label backport-risk-assessed
/retest
/cc @andfasano

**Review by djslavens — APPROVED** [review]
/lgtm

**Comment by zaneb** [comment]
/assign @bmanzari 
just need cherry-pick-approved please

**Pull request merged**
