### PR TITLE
OCPBUGS-34974: IBMCloud: Add service overrides

### PR DESCRIPTION
**Pull request by cjschaef**
Add additional IBM Cloud service override support for COS Config
and Global Catalog, for IBM Cloud Terraform plugin and any
Cluster Operators.

Related: https://issues.redhat.com/browse/OCPBUGS-34974

### CODE REVIEW

**Comment by cjschaef** [comment]
/jira refresh

`e2e-ibmcloud-ovn` failure due to know issue:  https://issues.redhat.com/browse/OCPBUGS-42869
Sounds like it is related to etcd issues, unrelated to this PR's changes.

**Review by MayXuQQ — APPROVED** [review]

**Comment by MayXuQQ** [comment]
pre-merge test with the following eps in the install-config, create private cluster success
  region: us-east
  serviceEndpoints:
  - name: IAM
    url: https://private.iam.cloud.ibm.com
  - name: VPC
    url: https://us-east.private.iaas.cloud.ibm.com/v1
  - name: ResourceController
    url: https://private.resource-controller.cloud.ibm.com
  - name: ResourceManager
    url: https://private.resource-controller.cloud.ibm.com
  - name: DNSServices
    url: https://api.private.dns-svcs.cloud.ibm.com/v1
  - name: COS
    url: https://s3.direct.us-east.cloud-object-storage.appdomain.cloud
  - name: GlobalSearch
    url: https://api.private.global-search-tagging.cloud.ibm.com
  - name: GlobalTagging
    url: https://tags.private.global-search-tagging.cloud.ibm.com
  - name: COSConfig
    url: https://config.direct.cloud-object-storage.cloud.ibm.com/v1
  - name: GlobalCatalog
    url: https://private.globalcatalog.cloud.ibm.com
  - name: KeyProtect
    url: https://private.us-east.kms.cloud.ibm.com

**Comment by sadasu** [comment]
@cjschaef do you think adding some unit tests would be useful here?

**Comment by cjschaef** [comment]
@sadasu I don't think that is necessary, as the API already has restrictions on service names, and there isn't anything for the JSON file generated for IBM Cloud Terraform plugin.

If you think something verifying the JSON file would be helpful, I could add that in another PR, after I work out some of the nuances of setting that up.

**Comment by MayXuQQ** [comment]
I will cover the following new eps in prow ci https://steps.ci.openshift.org/reference/ibmcloud-provision-vpc-endpoints-gateway
 "COSConfig" "GlobalCatalog" "KeyProtect"

**Pull request merged**
