### PR TITLE
DO NOT MERGE. Testing CI

### PR DESCRIPTION
**Pull request by kwoodson**
Testing Alibaba CI

### CODE REVIEW

**Comment by kwoodson** [comment]
image

**Comment by jsafrane** [comment]
/test e2e-alibaba
Checking if pull- tests work, I got weird error when adding a periodic job in https://github.com/openshift/release/pull/26954

**Comment by kwoodson** [comment]
@jsafrane We need this fix #5682. This is causing failures in the CI as the bootstrap teardown is removing the SLB backend control plane nodes.

**Comment by kwoodson** [comment]
@jsafrane Wow, `e2e-alibaba` passed!!

**Comment by sadasu** [comment]
/close
Based on https://github.com/openshift/installer/pull/5604#issuecomment-1104655932, it appears that this PR is no longer needed.

**Pull request closed without merging**
