### PR TITLE
vendor: update baremetal-operator to latest

### PR DESCRIPTION
**Pull request by stbenjam**
Metal3 is currently failing due to the BMO vendored in the installer
being out of date.

See: https://github.com/openshift-metal3/dev-scripts/issues/829

Command run: `dep ensure -update github.com/metal3-io/baremetal-operator`

### CODE REVIEW

**Comment by metal3ci** [comment]
Build SUCCESS, see build http://10.8.144.11:8080/job/dev-tools/1234/

**Comment by hardys** [comment]
This seems to update some vendored things other than the BMO but I guess that's just the dependency resolution - I tested locally with this applied via https://github.com/openshift-metal3/dev-scripts/pull/809 and it worked so lgtm

**Comment by stbenjam** [comment]
> This seems to update some vendored things other than the BMO but I guess that's just the dependency resolution - I tested locally with this applied via openshift-metal3/dev-scripts#809 and it worked so lgtm

Yea unfortunately dep seemed to pull in a lot.  vendoring this much always makes me nervous, but skimming it, the changes looked fine (and everyone's CI is still passing)

**Comment by abhinavdahiya** [comment]
All these new additions are from `https://github.com/metal3-io/baremetal-operator/blob/fc67cc20e40be272f440cf9ff45ba9adb4823b55/pkg/apis/metal3/v1alpha1/zz_generated.openapi.go` :(

Are these required to be in api package?

**Comment by stbenjam** [comment]
> All these new additions are from `https://github.com/metal3-io/baremetal-operator/blob/fc67cc20e40be272f440cf9ff45ba9adb4823b55/pkg/apis/metal3/v1alpha1/zz_generated.openapi.go` :(
> 
> Are these required to be in api package?

I don't believe we have an option, it's generated code from the operator-sdk - any chance you could confirm @dhellmann @zaneb?

**Comment by dhellmann** [comment]
> > All these new additions are from `https://github.com/metal3-io/baremetal-operator/blob/fc67cc20e40be272f440cf9ff45ba9adb4823b55/pkg/apis/metal3/v1alpha1/zz_generated.openapi.go` :(
> > Are these required to be in api package?
> 
> I don't believe we have an option, it's generated code from the operator-sdk - any chance you could confirm @dhellmann @zaneb?

It's definitely generated code. 

I don't know if we could benefit by putting the host types code in a separate package somehow. I assume go is figuring out what it needs, though, either when we vendor the code or when it compiles.

**Comment by stbenjam** [comment]
If this is ok then it just needs someone to lgtm it.

/cc @abhinavdahiya

**Pull request merged**
