### PR TITLE
OpenStack UPI: Add options for network types

### PR DESCRIPTION
**Pull request by gyohuangxin**
This change allows users to chose openstack network type between vlan and flat.

### CODE REVIEW

**Comment by gyohuangxin** [comment]
@pierreprinetti 
Hi, I think these test failures were not related to my changes, could you pls have a look? Thanks.

**Comment by pierreprinetti** [comment]
@gyohuangxin 
Correct, we are fixing the UPI test suite in https://github.com/openshift/release/pull/10944

**Comment by gyohuangxin** [comment]
> @gyohuangxin
> Correct, we are fixing the UPI test suite in [openshift/release#10944](https://github.com/openshift/release/pull/10944)

Thanks.

**Comment by gyohuangxin** [comment]
@pierreprinetti  Are UPI tests still being fixed?

**Comment by pierreprinetti** [comment]
@gyohuangxin 
The UPI tests should be fine now; the failure may be legit

> (rule:create_network and rule:create_network:provider:network_type) is disallowed by policy

/retest

**Comment by pierreprinetti** [comment]
@gyohuangxin

The CI test is failing with:
>(rule:create_network and rule:create_network:provider:network_type) is disallowed by policy

This is a legitimate error: provider networks are a prerogative of administrative users of OpenStack, and we only target installations carried over with a non-administrative OpenStack access.

For this reason, I don't think that these playbooks should create provider networks.

If this is a case you want to support, would you like to turn this PR into a documentation change, and edit [the UPI instructions](https://github.com/openshift/installer/blob/master/docs/user/openstack/install_upi.md) to include this case?

**Comment by gyohuangxin** [comment]
@pierreprinetti 
Thank you for your reply, the original purpose of this PR is to let users can create "flat" type network instead of "vlan".  As you said, it's not allowed to create it, so I will consider to mention it in documentation

**Comment by pierreprinetti** [comment]
Closing in favor of a documentation PR if you are willing to file it @gyohuangxin 

/close

**Pull request closed without merging**
