### PR TITLE
Bug 1871653: baremetal: set root device hints on host resources

### PR DESCRIPTION
**Pull request by dhellmann**
Pass the root device hints given by the user in the install-config to
the BareMetalHost resources created in the cluster.

### CODE REVIEW

**Comment by stbenjam** [comment]
Nit, I'd mention 'baremetal' in the commit title, but otherwise lgtm

**Comment by dhellmann** [comment]
> Nit, I'd mention 'baremetal' in the commit title, but otherwise lgtm

I updated the commit and PR title.

**Comment by dhellmann** [comment]
The only jobs that are failing are for unrelated platforms.

/retest

**Pull request merged**
