### PR TITLE
CFE-686 : Update openshift/api package to latest version

### PR DESCRIPTION
**Pull request by bharath-b-rh**
PR is for updating the openshift/api package to the latest version which contains the API changes for supporting GCP labels & tags made in https://github.com/openshift/api/pull/1445

### CODE REVIEW

**Comment by patrickdillon** [comment]
#7401 is pulling in a newer API version. We should probably defer this PR for that one.

**Comment by bharath-b-rh** [comment]
Closing in favor of https://github.com/openshift/installer/pull/7401

**Pull request closed without merging**
