### PR TITLE
 WIP: Bug 1945674: default to insecure false on user questions

### PR DESCRIPTION
**Pull request by Gal-Zaidman**
When the user uses questions most of our defaults are insecure true.
Which should never be the case.

### CODE REVIEW

**Comment by dougsland** [comment]
looks sane from what I can see.

**Review by janoszen — APPROVED** [review]

**Comment by janoszen** [comment]
@Gal-Zaidman it seems we dropped the ball on this one, can we pick it up?

**Comment by sadasu** [comment]
@Gal-Zaidman is there still interest in this work?

**Comment by sadasu** [comment]
@dougsland, @Gal-Zaidman how to we proceed with this?

**Comment by dougsland** [comment]
@sadasu this patch seems WIP more than 1 year. Probably good candidate to be deprecated.

**Comment by sadasu** [comment]
/close
Please see comment https://github.com/openshift/installer/pull/4810#issuecomment-1202831803

**Pull request closed without merging**
