### PR TITLE
no-jira: PowerVS: Fix CAPI created service instance case

### PR DESCRIPTION
**Pull request by hamzy**
We should be passing in the ServiceInstance structure which handles
both pre-existing and CAPI created versions.  Also we did not properly
get the service instance GUID.

### CODE REVIEW

**Review by r4f4 — COMMENTED** [review]
/approve

Don't you need to update `ibmcloud-infrastructure-components.yaml`

**Comment by hamzy** [comment]
> /approve
> 
> Don't you need to update `ibmcloud-infrastructure-components.yaml`

I assumed not, because they just added a couple of lines of code in a function.  I can check though...

**Comment by hamzy** [comment]
Okay, so not that one PR for the provider but other PRs did change the file.  Thanks for the reminder!

**Pull request merged**
