### PR TITLE
Bug 1868350: Backport new feature to bypass problems with AWS Accounts using SCP

### PR DESCRIPTION
**Pull request by dgoodwin**
Limited backport to 4.5 that will not be documented, but was requested for Service Delivery.

Bug: https://bugzilla.redhat.com/show_bug.cgi?id=1868350 but fix spans 3 repos.

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
needs approval from @sdodson

**Comment by sdodson** [comment]
/approve
/hold
Once we have all of these reviewed we need to coordinate with patch manager to ensure that the PRs all merge within the same window or at least in the required order.

**Comment by sdodson** [comment]
/hold cancel
This can merge without the others per slack conversation.

**Pull request merged**
