### PR TITLE
Update openshift/api to latest

### PR DESCRIPTION
**Pull request by Karthik-K-N**
To support [cluster-control-plane-machine-set-operator](https://github.com/openshift/cluster-control-plane-machine-set-operator) to Power VS platform PowerVS provider spec is updated via PR: https://github.com/openshift/api/pull/1415.

This PR updates openshift/api to latest version to fetch the newly added fields.

### CODE REVIEW

**Review by r4f4 — COMMENTED** [review]
/lgtm

**Comment by r4f4** [comment]
This should now be covered by https://github.com/openshift/installer/pull/7220

**Comment by Karthik-K-N** [comment]
/close

Closing this as another PR https://github.com/openshift/installer/pull/7220 got merged and which updates the openshift/api

**Pull request closed without merging**
