### PR TITLE
Bug 2098252: locations fix

### PR DESCRIPTION
**Pull request by RyanJenkins99**
Inside the rhcos-stream.json file the locations needed to be updated to the most current version

### CODE REVIEW

**Comment by mike-nguyen** [comment]
All required tests have passed.

@patrickdillon can we get a backport-risk-assessed and approve label on this?  The only change here is the redirector to the RHCOS artifacts.

**Comment by sdodson** [comment]
I've confirmed that the docs for 4.8 mention the new endpoint so moving this on.

**Pull request merged**
