### PR TITLE
fetch router CA secret instead of configmap, until configmap is reliably created

### PR DESCRIPTION
**Pull request by sallyom**
There have been reports of router-ca configmap not being created, due to ingress-operator reconciliation errors.  This will be resolved when [this](https://github.com/openshift/cluster-ingress-operator/pull/118) lands, so ingress-operator will publish `router-ca` even if reconciliation has errors.

Until then, this PR will prevent CI from breaking, since  CI depends on router CA being added to kubeconfig, to ensure `oc login -u kubeadmin -p blah` succeeds (once [this](https://github.com/openshift/cluster-authentication-operator/pull/59) merges, CI will break w/out addition of router-ca crt)

In the future, it's possible that router-ca configmap will be absent (but only if launching with a custom default router crt).  However, in our internal CI, this should never be the case (and it won't once that ingress-operator fix is in), and furthermore, the ability to bring your own router crt doesn't exist yet.  

related: https://github.com/openshift/installer/issues/1261
@Miciah if 118 is a few days away, we should merge this

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
please make sure the commit message matches https://github.com/openshift/installer/blob/master/CONTRIBUTING.md#commit-message-format

**Comment by sallyom** [comment]
@staebler removed commented code, stored in GH issue for convenience

**Comment by abhinavdahiya** [comment]
@sallyom since this is not being tested right now as https://github.com/openshift/cluster-authentication-operator/pull/59 is not merged yet. Can you test this works locally and show that this works.. ?

**Comment by enj** [comment]
@sallyom if we are deadlocking multiple PRs on CA issues it may make more sense to temporarily change the bootstrap user test to ignore cert errors.  That way we still know the OAuth server is working and can resolve the CA issues without blocking everyone else.  Also, I would expect the installer to poll for a little bit instead of just doing a single fetch for the router CA (I only scanned this code a little so maybe I missed that functionality).

**Comment by sallyom** [comment]
@enj the problem is that while the router-ca secret is always created, the configmap is only created if/when cluster-ingress-operator concludes it should trust the CA, and that, atm, is not happening 100% of the time, but will be resolved by [this commit](https://github.com/openshift/cluster-ingress-operator/pull/118/commits/0e45baafdc795155234b39d604352c8484541b91)  FWIU.
Checking for the router-ca secret will never be the wrong thing to do for our CI purposes, since we know that CA 100% of the time should be trusted.  However, for another user, if they provide a custom default router crt, that install should not create the configmap, so that is why, in general, installer needs to fetch from configmap, not secret (but for now, to unblock everyone, it's ok to check for secret that will _always_ be there)

**Comment by sallyom** [comment]
test-flake I think: `[Conformance][Area:Networking][Feature:Router] The HAProxy router should enable openshift-monitoring to pull metrics [Suite:openshift/conformance/parallel/minimal]`

**Comment by sallyom** [comment]
confirmed w/ cluster launched fetching secret rather than configmap and with htpasswd configured with a user:test pw: test
```console
$ oc login -u test -p test
Login successful.

You don't have any projects. You can try to create a new project, by running

    oc new-project <projectname>
```

**Comment by sallyom** [comment]
[this](https://github.com/openshift/cluster-ingress-operator/pull/118) is merged, so closing, hopefully this is no longer needed.

**Pull request closed without merging**
