### PR TITLE
OCPBUGS-5234: azurestack: upi: fix compute scale up

### PR DESCRIPTION
**Pull request by r4f4**
Scaling up a compute machineset will fail in AzureStack UPI with:

```
Message:               failed to create vm $clusterID-worker-mtcazs-2gjsl: failure sending request for machine $clusterID-worker-mtcazs-2gjsl: cannot create vm: compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=404 -- Original Error: Code="NotFound" Message="The Availability Set '/subscriptions/$subID/resourceGroups/$clusterID-rg/providers/Microsoft.Compute/availabilitySets/$clusterID-cluster' cannot be found."
```

because machinesets follow the IPI pattern of using "$clusterID-cluster" as the availabilitySet's name, whereas UPI uses "$clusterID-avset". So let's change UPI to be consistent with IPI.

### CODE REVIEW

**Comment by MayXuQQ** [comment]
"imageName" : "[parameters('baseName')]",

**Comment by r4f4** [comment]
> "imageName" : "[parameters('baseName')]",

Nice catch! Done.

**Review by MayXuQQ — APPROVED** [review]

**Comment by sadasu** [comment]
Thanks for taking care of this. I would like to see the azure upi jobs pass before approve.

**Comment by r4f4** [comment]
/override ci/prow/e2e-azure-ovn-upi
Not affected by this change.

**Comment by r4f4** [comment]
azurestack-upi jobs seem to have been perma-failing with no worker nodes https://testgrid.k8s.io/redhat-openshift-ocp-release-4.13-informing#periodic-ci-openshift-release-master-nightly-4.13-e2e-azurestack-ovn-upi

**Comment by r4f4** [comment]
I'm waiting for https://github.com/openshift/release/pull/35755 to fix the azurestack UPI jobs.

**Comment by r4f4** [comment]
Successful install on azurestack-upi job
/hold cancel

**Comment by r4f4** [comment]
/override ci/prow/e2e-azure-ovn-upi
Just a few e2e failures and not affected by this change anyway

**Comment by r4f4** [comment]
/override ci/prow/e2e-azure-ovn
Few e2e failures and not affected by the changes in this PR.

**Pull request merged**
