### PR TITLE
*: replace master/worker terms with control-plane/compute

### PR DESCRIPTION
**Pull request by staebler**
Replace references to master and worker with control plane and compute throughout the installer.

Remaining references:
* Machine labels `sigs.k8s.io/cluster-api-machine-role` and `sigs.k8s.io/cluster-api-machine-type` still use the `master` and `worker` values.
* The URL to query for ignition config files still ends in `/config/master` and `/config/worker`.
* The Admin cert key is still created with an Organization value of `system:masters`.

### CODE REVIEW

**Comment by staebler** [comment]
/hold

Pending feature exception approval.

**Comment by staebler** [comment]
/hold cancel

The feature exception for this has been approved.

**Comment by staebler** [comment]
> error: could not run steps: test "release-latest" failed: pod release-latest was already deleted

/retest

**Comment by staebler** [comment]
openshift.service
> Feb 15 21:57:48 ip-10-0-6-213 openshift.sh[4476]: kubectl create --filename ./99_openshift-cluster-api_cluster.yaml failed. Retrying in 5 seconds...
> Feb 15 21:57:53 ip-10-0-6-213 openshift.sh[4476]: error: unable to recognize "./99_openshift-cluster-api_cluster.yaml": no matches for kind "Cluster" in version "cluster.k8s.io/v1alpha1"

Bootstrapping did not complete because the openshift service could not create the `Cluster` resource with version `cluster.k8s.io/v1alpha1`.

**Comment by staebler** [comment]
> level=error msg="\t* module.vpc.aws_route.to_nat_gw[0]: 1 error occurred:"
> level=error msg="\t* aws_route.to_nat_gw.0: Error creating route: timeout while waiting for state to become 'success' (timeout: 2m0s)"

Rate-limit errors

/test e2e-aws

**Comment by staebler** [comment]
> level=fatal msg="failed to initialize the cluster: Cluster operator machine-config is reporting a failure: Failed to resync 3.11.0-665-gd2c44d7c-dirty because: error syncing: Get https://172.30.0.1:443/apis/rbac.authorization.k8s.io/v1/clusterroles/machine-config-daemon: dial tcp 172.30.0.1:443: connect: connection refused"

/retest

**Comment by staebler** [comment]
> level=info msg="Destroying the bootstrap resources..."
> level=error
> level=error msg="Error: Error applying plan:"
> level=error
> level=error msg="1 error occurred:"
> level=error msg="\t* module.bootstrap.aws_iam_role.bootstrap (destroy): 1 error occurred:"
> level=error msg="\t* aws_iam_role.bootstrap: Error deleting IAM Role ci-op-ddklyji6-1d3f3-bootstrap-role: NoSuchEntity: The role with name ci-op-ddklyji6-1d3f3-bootstrap-role cannot be found."
> level=error msg="\tstatus code: 404, request id: 757e8538-3193-11e9-a0b0-dfe339fc73f7"

Failure when cleaning up bootstrap resources.

/retest

**Comment by cgwalters** [comment]
> This is part of the overall effort to replace the terms master and worker with control plane and compute throughout the installer.

I'm a fan but...it's not just the installer but (eventually) OpenShift in general right?  We're going to have...a lot of work to do for that.  In the MCO for example renaming everything as part of an upgrade would get...tricky.

**Comment by staebler** [comment]
> > This is part of the overall effort to replace the terms master and worker with control plane and compute throughout the installer.
> 
> I'm a fan but...it's not just the installer but (eventually) OpenShift in general right? We're going to have...a lot of work to do for that. In the MCO for example renaming everything as part of an upgrade would get...tricky.

My expectation is that, yes, eventually OpenShift in general will switch to using the control plane and compute terms. However, I would not expect that an update would change the names of existing resources. Code should generally not be relying on the names of resources but instead on labels on those resources. For the MCO in particular, I'm not sure what more would need to be done beyond serving the config from, for example, both master and control-plane endpoints. Can you elaborate on some other things in upgrading after terms change that you anticipate being tricky?

**Comment by staebler** [comment]
/hold

Hold for 4.1.

**Pull request closed without merging**
