### PR TITLE
 create new serving cert for internal loadbalancer

### PR DESCRIPTION
**Pull request by deads2k**
This creates a serving cert for a new DNS name to reach the kube-apiserver.  We're doing this because the kubelets don't have a way to customize the CA bundle they use to trust the kube-apiserver.  This means that right now a cluster-admin cannot specify a new loadbalancer serving certificate because it causes all kubelets in the cluster no longer trust the kube-apiserver.  By having a different name, the customers can override the public LB serving cert and not the private DNS name for it.

@sjenning @eparis @derekwaynecarr 
/assign @abhinavdahiya

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
/hold

there is no exception request and this in itself is not useful.

**Comment by deads2k** [comment]
> /hold
> 
> there is no exception request and this in itself is not useful.

/hold cancel

Without this we cannot use our own product

**Comment by wking** [comment]
This mitigates [rhbz#1685704][1], by giving kubelets a stable cert that users are unlikely to care about even if they customize the external API cert.  We'll be able to drop it once kubelets grow the ability to configure custom CAs.  Is there a migration plan to get `api-int` back to `api` once that happens?

[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1685704

**Comment by wking** [comment]
Implementation looks fine, so I'm ok dropping a `/lgtm` to mitigate rhbz#1685704 once we are clear on how we'll drop `api-int` in a future upgrade.

**Comment by deads2k** [comment]
> Implementation looks fine, so I'm ok dropping a `/lgtm` to mitigate rhbz#1685704 once we are clear on how we'll drop `api-int` in a future upgrade.

I don't think we ever will.  I think having kubelets reference kube-apiservers differently gives us desireable characteristics for cert control.

**Comment by wking** [comment]
>  I think having kubelets reference kube-apiservers differently gives us desireable characteristics for cert control.

Wait, what sort of desirable characteristics?  Now you have two certs to maintain?  What about other cluster components besides the kubelet that are hitting the internal API?  What about folks that aren't making an internal/external load balancer distinction and now have to maintain two DNS names that point to the same load balancer?

**Comment by wking** [comment]
On that front, will this new split scheme work with libvirt?  I expect we'll need changes there to at least add DNS entries for `api-int`.

**Comment by sdodson** [comment]
> I don't think we ever will. I think having kubelets reference kube-apiservers differently gives us desireable characteristics for cert control.

:+1: to that having a very clear line of demarcation between internal and external was valuable during 3.x.

> Now you have two certs to maintain? What about other cluster components besides the kubelet that are hitting the internal API?

I'd think we only need to worry about preserving cluster availability while rolling `api-int` certs, nothing inside the cluster should reference `api`.

**Comment by wking** [comment]
> I'd think we only need to worry about preserving cluster availability while rolling `api-int` certs, nothing inside the cluster should reference `api`.

Wait, so this is really a fairly big architecture change that happens to mitigate rhbz#1685704?  Not primarily a rhbz#1685704 mitigation?  Can we get a formal exception request then?  And loop in folks from other platforms, unless there is a simple knob we can set to keep them on `api` while AWS moves to `api-int`?

**Comment by derekwaynecarr** [comment]
@wking we will get an exception sent out that communicates the problem and the required change today.

**Comment by wking** [comment]
/lgtm

This is a dead resource until we have internal consumers, so we can land this while we hash out the exception grant.

**Comment by sjenning** [comment]
Unauthorized flake
/retest

**Comment by wking** [comment]
[e2e-aws][1]:

```
Failing tests:

[Feature:Platform] Managed cluster should have no crashlooping pods in core namespaces over two minutes [Suite:openshift/conformance/parallel]
```

Crash-looping openshift-kube-scheduler is [rhbz#1698251][2].

/retest

[1]: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_installer/1581/pull-ci-openshift-installer-master-e2e-aws/5199
[2]: https://bugzilla.redhat.com/show_bug.cgi?id=1698251

**Comment by abhinavdahiya** [comment]
failed to bootstrap due to the known CRI-O bug https://bugzilla.redhat.com/show_bug.cgi?id=1698253

```console
$ curl -s https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_installer/1581/pull-ci-openshift-installer-master-e2e-aws/5236/artifacts/e2e-aws/pods.json | rg 'Failed to inspect image'
                                "message": "Failed to inspect image \"registry.svc.ci.openshift.org/ci-op-7wgp3ky8/stable@sha256:07fe56e6d90d2a18b9dd9eb8afa58f085972509e3426f86d7fdb8f2c09429ae6\": rpc error: code = Unknown desc = Manifest does not match provided manifest digest sha256:07fe56e6d90d2a18b9dd9eb8afa58f085972509e3426f86d7fdb8f2c09429ae6",
                                "message": "Failed to inspect image \"registry.svc.ci.openshift.org/ci-op-7wgp3ky8/stable@sha256:07fe56e6d90d2a18b9dd9eb8afa58f085972509e3426f86d7fdb8f2c09429ae6\": rpc error: code = Unknown desc = Manifest does not match provided manifest digest sha256:07fe56e6d90d2a18b9dd9eb8afa58f085972509e3426f86d7fdb8f2c09429ae6",
```

/retest

**Comment by wking** [comment]
[e2e-aws][1]:

```
fail [github.com/openshift/origin/test/extended/operators/cluster.go:109]: Expected
    <[]string | len:2, cap:2>: [
        "Pod openshift-kube-controller-manager/kube-controller-manager-ip-10-0-146-207.ec2.internal is not healthy: container kube-controller-manager-5 has restarted more than 5 times",
        "Pod openshift-marketplace/certified-operators-68b86bb6ff-mt5kz is not healthy: Back-off 5m0s restarting failed container=certified-operators pod=certified-operators-68b86bb6ff-mt5kz_openshift-marketplace(113fe363-5d73-11e9-b6a2-0edf0651cfc4)",
    ]
to be empty
...
Flaky tests:

[sig-node] Downward API should provide host IP as an env var [NodeConformance] [Conformance] [Suite:openshift/conformance/parallel/minimal] [Suite:k8s]

Failing tests:

[Feature:Platform] Managed cluster should have no crashlooping pods in core namespaces over two minutes [Suite:openshift/conformance/parallel]
```

This was some kind of issue with Quay namespaces, since resolved.

/retest

[1]: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_installer/1581/pull-ci-openshift-installer-master-e2e-aws/5268

**Comment by wking** [comment]
[e2e-aws][1]:

```
fail [github.com/openshift/origin/test/extended/operators/cluster.go:109]: Expected
    <[]string | len:1, cap:1>: [
        "Pod openshift-kube-controller-manager/kube-controller-manager-ip-10-0-165-110.ec2.internal is not healthy: container kube-controller-manager-5 has restarted more than 5 times",
    ]
to be empty
...
Failing tests:

[Feature:Platform] Managed cluster should have no crashlooping pods in core namespaces over two minutes [Suite:openshift/conformance/parallel]
```

/retest

[1]: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_installer/1581/pull-ci-openshift-installer-master-e2e-aws/5290

**Pull request merged**
