### PR TITLE
[WIP] ensure health probes are HTTPS in Azure

### PR DESCRIPTION
**Pull request by fabianofranz**
https://issues.redhat.com/browse/CORS-1096

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
I think we need to use HTTP(S) for the ign server too right ?
https://github.com/openshift/installer/blob/f86c37597828cc019e67d16d390521a831170259/data/data/azure/vnet/internal-lb.tf#L121-L129

**Comment by fabianofranz** [comment]
Closing in favor of https://github.com/openshift/installer/pull/3600.

**Pull request closed without merging**
