### PR TITLE
link to ansible role for setting up libvirt dev environment

### PR DESCRIPTION
**Pull request by dhellmann**
Add a section to the libvirt howto that points to an ansible role for
managing the system configuration steps automatically.

Signed-off-by: Doug Hellmann <doug@doughellmann.com>

### CODE REVIEW

**Comment by wking** [comment]
Previous Ansible tooling for our libvirt setup in #636.  My concern is still around portability (e.g. [RHEL 7.5 CSB support][1]).  From [your README][2], it looks like you are targeting CentOS?  Can you call that out in your link (mentioning the version?)?  Or are you comfortable fielding issues from folks with RHEL systems?  Fedora?  Debian? ...

[1]: https://github.com/openshift/installer/pull/636#issuecomment-436884655
[2]: https://github.com/dhellmann/ansible-openshift-libvirt/blame/070c896216cecebce504ac9646e1f9d85baa2a85/README.md#L4

**Comment by dhellmann** [comment]
I wasn't aware of that other pull request, so thanks for the link.

The role only supports CentOS now but I'd be happy to accept patches if someone wanted to expand that to support other platforms. I can make that clear in the readme for the role.

Should I still update the link to say CentOS, or leave it open to avoid having to update it in the future? Either is fine, just let me know what you prefer.

**Comment by tombarron** [comment]
Thanks for this PR.  I just set up a machine for the installer with libvirt provider for the first time and the role was quite helpful.

**Comment by DanyC97** [comment]
something to keep in mind for openshift-ansible code base @vrutkovs @sdodson ? my 0.02 $ ...

**Comment by sdodson** [comment]
> something to keep in mind for openshift-ansible code base @vrutkovs @sdodson ? my 0.02 $ ...

Yeah, makes sense to converge on whichever of the two implementations (this link, or #636) in both installer and openshift-ansible.

**Comment by dhellmann** [comment]
I'd be happy to move my repo into this org and let the team manage it, if that makes the decision any easier. Functionally I'm not sure there was a huge amount of difference between the 2 implementations, so if you want to stick with the previous implementation that's fine, too. FWIW, I found having it defined as a role made it easier to integrate it with my existing host setup playbook.

**Comment by cgwalters** [comment]
From my perspective though this is encouraging doing things the "legacy" way of installing a bunch of stuff on your host.  I develop on OpenShift using Fedora Silverblue as a workstation and I don't have `libvirt-devel` on my host - it lives in my dev container.  I live in containers on my desktop the same way we expect our customers to be doing on their servers :smile:

**Comment by abhinavdahiya** [comment]
1. Also mentioned in https://github.com/openshift/installer/pull/636, libvirt has proven to be different enough for every dev, that generic guidelines on how to setup make most sense for now.
2. links to external docs esp non-openshift and private is a no-go.

/close

**Pull request closed without merging**
