### PR TITLE
[vsphere] refactor platform spec

### PR DESCRIPTION
**Pull request by rvanderp3**
The intention of this PR is to correspond with https://github.com/openshift/api/pull/1278 .

### CODE REVIEW

**Comment by rvanderp3** [comment]
cc: @jcpowermac @bostrt

**Comment by jcpowermac** [comment]
e2e-vsphere-zones will fail since this PR modifies the platform spec and #6064 merged

Tested the commits with #6329 no immediate problems

/lgtm

**Comment by rvanderp3** [comment]
closing as this PR is being combined with https://github.com/openshift/installer/pull/6329 .

**Pull request closed without merging**
