### PR TITLE
OCPBUGS-17190: [release-4.13] terraform: aws: bump version to 5.4.0

### PR DESCRIPTION
**Pull request by r4f4**
It contains bug fixes we need for tagging in ISO partitions.

Manual cherry-pick of https://github.com/openshift/installer/pull/7274

### CODE REVIEW

**Comment by patrickdillon** [comment]
/hold
https://issues.redhat.com/browse/OCPBUGS-18830 is a blocking bug for 4.14 and I would like to rule out the provider bump as the cause of the bug before backporting.

**Comment by sadasu** [comment]
@patrickdillon, @r4f4  is this PR ready for the /hold to be removed?

**Comment by r4f4** [comment]
> @patrickdillon, @r4f4 is this PR ready for the /hold to be removed?

@sadasu Not yet. I need to incorporate https://github.com/openshift/installer/pull/7491 into it. I won't get to it until next week the earliest.

**Comment by sadasu** [comment]
@r4f4 do we still need this?

**Pull request closed without merging**
