### PR TITLE
Bug 1940275: Revert "baremetal: send full ignition to masters"

### PR DESCRIPTION
**Pull request by kirankt**
This bug is a manual cherry-pick of #4722 for 4.7 release.

From #4722:
---
This doesn't work for IPI baremetal deployments driven via hive,
because there are firewall rules that prevent access to the
bootstrap MCS from the pod running the installer.

This was implemented in:
#4427

But we ran into problems making the same approach work for
worker machines ref:
#4456

We're now looking at other approaches to resolve the
network-config requirements driving that work, so
switching back to the pointer config for masters seems
reasonable, particularly given this issue discovered for
hive deployments.

Conflicts:
pkg/tfvars/baremetal/baremetal.go

This reverts commit 98dc381.

### CODE REVIEW

**Comment by hardys** [comment]
Thanks for proposing this @kirankt - we need to take care of the merge conflict in pkg/tfvars/baremetal/baremetal.go

**Comment by kirankt** [comment]
> Thanks for proposing this @kirankt - we need to take care of the merge conflict in pkg/tfvars/baremetal/baremetal.go

Thanks, @hardys . That was weird. I don't see the merge conflict in my local copy. :-(. In any case, I took care of it using the manual merge feature in the GUI.

**Comment by staebler** [comment]
The following tests should not be required.
/override ci/prow/e2e-kubevirt
/override ci/prow/e2e-metal-assisted
/override ci/prow/e2e-openstack-ipi

**Comment by cdoan1** [comment]
@staebler seem all the tests passed, any outlook on when this can land?

**Comment by stbenjam** [comment]
/approve
/lgtm

However, see above message from the bot, https://bugzilla.redhat.com/show_bug.cgi?id=1936443 needs to get QE'd first. Once that's done, this will get selected for an OpenShift z-stream sometime after that by the patch manager on duty.

**Comment by blkingrh** [comment]
@kirankt We are hoping to support OCP 4.7 on bare metal with our upcoming ACM 2.1.7 and 2.2.3 releases. Can you provide a target estimate of when you think this change will be on 4.7? Thanks!

**Comment by staebler** [comment]
> @kirankt We are hoping to support OCP 4.7 on bare metal with our upcoming ACM 2.1.7 and 2.2.3 releases. Can you provide a target estimate of when you think this change will be on 4.7? Thanks!

QE needs to verify the change in 4.8 before this PR can merge into 4.7.

**Comment by kirankt** [comment]
> @kirankt We are hoping to support OCP 4.7 on bare metal with our upcoming ACM 2.1.7 and 2.2.3 releases. Can you provide a target estimate of when you think this change will be on 4.7? Thanks!

Hi @blkingrh . Honestly I'm not sure when it will land. Hopefully soon. The 4.8 version of this port is still needs to be verified by QA, which is dragging along the process. I have pinged the QA contact to get things rolling...

**Pull request merged**
