### PR TITLE
OSASINFRA-3153: move `loadBalancer` API to GA for OpenStack

### PR DESCRIPTION
**Pull request by EmilienM**
This API has not moved and there is no plan to make any change that
would be backward incompatible in the future.

The feature was well tested (and automated) by our QE on this platform,
as well documented on OCP 4.13.

We think this API is ready to be GA'ed.

### CODE REVIEW

**Comment by mdbooth** [comment]
> @mdbooth: No Bugzilla bug is referenced in the title of this pull request. To reference a bug, add 'Bug XXX:' to the title of this pull request and request another bug refresh with `/bugzilla refresh`.

Is this part of the temporary hold on 4.14?

**Comment by EmilienM** [comment]
well, while we're at it:

/test e2e-openstack-externallb-techpreview

**Review by mandre — COMMENTED** [review]
/lgtm

**Comment by EmilienM** [comment]
`e2e-openstack-externallb-techpreview` is green :-)
/hold cancel

@patrickdillon do you know why this can't merge without a BZ? Is it some sort of freeze at the moment? Sorry if I missed that info.

**Pull request merged**
