### PR TITLE
OCPBUGS-33454: go.mod: bump aws-sdk-go for ca-west-1 support

### PR DESCRIPTION
**Pull request by r4f4**
ca-west-1 is now supported as of https://issues.redhat.com/browse/OCPSTRAT-1177

### CODE REVIEW

**Comment by sdodson** [comment]
Testing of 4.16 will be tracked in OCPSTRAT-1177, setting `jira/valid-bug` label

**Review by barbacbd — COMMENTED** [review]
It looks like this is missing from the limits file as a `SupportedRegion`. This is also used by quotas. We need to add this region so that it can be used for validation.

**Comment by r4f4** [comment]
> > It looks like this is missing from the limits file as a `SupportedRegion`. This is also used by quotas. We need to add this region so that it can be used for validation.
> 
> That's also missing in 4.16, so I'm going to do it as a separate bug.

Fix is at https://github.com/openshift/installer/pull/8406

**Comment by r4f4** [comment]
/assign @patrickdillon 
for the backport label

**Review by barbacbd — COMMENTED** [review]
/lgtm

**Comment by sadasu** [comment]
This PR needs to be updated with https://github.com/openshift/installer/pull/8406 which adds quota support for the same region.

**Comment by r4f4** [comment]
> This PR needs to be updated with #8406 which adds quota support for the same region.

@sadasu the quota support is being handled via https://github.com/openshift/installer/pull/8412. I'd prefer to do them separately so I can take advantage of the automated backport process.

**Pull request merged**
