### PR TITLE
destroy: vsphere: move API calls to client abstraction and add unit tests

### PR DESCRIPTION
**Pull request by r4f4**
By moving govmomi API calls to a client abstraction, not only it hides away details of some them thus simplifying the cluster destroy code, it also allows us to add unit tests by mocking the API calls.

### CODE REVIEW

**Review by SHAKY404 — APPROVED** [review]

**Comment by patrickdillon** [comment]
/approve

I would like to see feedback from @jcpowermac or particularly @bostrt as I know he has done some work on bringing in the vsphere emulator for testingf

**Comment by r4f4** [comment]
Rebased commits and fixed merge conflicts. Also included one more commit to fix linting issues by removing `context` from the struct.

**Comment by r4f4** [comment]
Coverage looks good: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_installer/6604/pull-ci-openshift-installer-master-unit/1621531308628905984/artifacts/test/artifacts/cover.html#file196

**Comment by jcpowermac** [comment]
/skip

vsphere issues caused by repo service failure, running job should complete

**Comment by r4f4** [comment]
Just a few e2e failures on `e2e-aws-ovn`. Since it's not affected by the changes in this PR, I'll override it if it's not successful after the current run.

**Pull request merged**
