### PR TITLE
Skip cluster config

### PR DESCRIPTION
**Pull request by deads2k**
Should merged with 

1. https://github.com/openshift/api/pull/1666
2. https://github.com/openshift/cluster-config-operator/pull/379
3. https://github.com/openshift/cluster-config-operator/pull/349

ideally these all land in a single unit.  If they don't, merges to openshift/api will get wedged on machine-configs not matching until they do.

### CODE REVIEW

**Comment by deads2k** [comment]
CI payload now has the image

/retest

**Comment by deads2k** [comment]
out of sync openshift/api and cluster-config-operator.  update to cluster-config-operator just merged, so let's try again


/retest

**Comment by patrickdillon** [comment]
/approve
LGTM, but it seems like we may be waiting for some dependencies so I'll hold off on the label

**Comment by deads2k** [comment]
https://github.com/openshift/installer/pull/7666 switching the installer rendering to use openshift/api has tested green and is ready to make the switch

https://github.com/openshift/api/pull/1666 and https://github.com/openshift/cluster-config-operator/pull/379 have clusterbot tested together fine. They hand off the CVO management of CRDs (and others) from cluster-config-operator to api image.

https://github.com/openshift/cluster-config-operator/pull/349 switches the featuregate setting from using the vendored copy from to using openshift/api.  It tested green until it openshift/api updated without a (yet) merged openshift/cluster-config-operator update, so the machine-config-operator mismatched until they rematch. But in combination with the rendering change linked above they will match ok.

Manually merging to get a batch.

**Pull request merged**
