### PR TITLE
WIP: Test a custom MCO build

### PR DESCRIPTION
**Pull request by dprince**

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
you don't need to open a PR on the installer to do that.

```
oc adm release new --from-release-image=<> --to-image=<> machine-config-operator=<custom image>
```

**Comment by abhinavdahiya** [comment]
> you don't need to open a PR on the installer to do that.
> 
> ```
> oc adm release new --from-release-image=<> --to-image=<> machine-config-operator=<custom image>
> ```

/close

**Comment by dprince** [comment]
The gist of this commit was to see if I could test a custom MCO build in CI fwiw. The openstack tests are not yet enabled for that component although there has been some work to enable it:

https://github.com/trown/release/commit/ab34077ebee6fab687f73ea4ec870dda1e637480

**Comment by sallyom** [comment]
@dprince, I did just this yesterday
I use these notes: https://docs.google.com/document/d/1GCu0vbdp9A32x_j9G-1f-18IEYtgtyoHy8HRQv4KYOY/edit?usp=sharing
You can ping me in slack if you have questions : )

**Pull request closed without merging**
