### PR TITLE
OCPBUGS-3110: azure: Fix client certs authentication

### PR DESCRIPTION
**Pull request by rna-afk**
Fixing a typo in the CredentialsMode check.

### CODE REVIEW

**Comment by r4f4** [comment]
We should create a bug for this so it can be backported to 4.12.

**Comment by r4f4** [comment]
/retitle OCPBUGS-3110: azure: Fix client certs authentication

**Comment by rna-afk** [comment]
vsphere failing has nothing to do with this PR
/override e2e-vsphere-ovn

**Comment by patrickdillon** [comment]
/override ci/prow/e2e-azure-ovn ci/prow/e2e-aws-ovn 

azure is completing install and failing in e2e, not affected by this pr

**Pull request merged**
