### PR TITLE
CORS-3466: CAPG set instance group name

### PR DESCRIPTION
**Pull request by patrickdillon**
Sets the instance group name in capg to user "master" to be compatible with MAPI conventions, rather than "apiserver" as used by CAPI.

### CODE REVIEW

**Comment by bfournie** [comment]
Just need one more change to use "master" here instead of "apiserver" https://github.com/openshift/installer/blob/master/pkg/infrastructure/gcp/clusterapi/network.go#L133

The instancegroups are now properly named, e.g.:
```
$ gcloud compute instance-groups list --uri 
https://www.googleapis.com/compute/v1/projects/openshift-dev-installer/zones/us-east1-b/instanceGroups/bfournie-capg-test-vlc9t-master-us-east1-b
https://www.googleapis.com/compute/v1/projects/openshift-dev-installer/zones/us-east1-c/instanceGroups/bfournie-capg-test-vlc9t-master-us-east1-c
https://www.googleapis.com/compute/v1/projects/openshift-dev-installer/zones/us-east1-d/instanceGroups/bfournie-capg-test-vlc9t-master-us-east1-d
```

**Comment by patrickdillon** [comment]
> Just need one more change to use "master" here instead of "apiserver" https://github.com/openshift/installer/blob/master/pkg/infrastructure/gcp/clusterapi/network.go#L133
> 
> The instancegroups are now properly named, e.g.:
> 
> ```
> $ gcloud compute instance-groups list --uri 
> https://www.googleapis.com/compute/v1/projects/openshift-dev-installer/zones/us-east1-b/instanceGroups/bfournie-capg-test-vlc9t-master-us-east1-b
> https://www.googleapis.com/compute/v1/projects/openshift-dev-installer/zones/us-east1-c/instanceGroups/bfournie-capg-test-vlc9t-master-us-east1-c
> https://www.googleapis.com/compute/v1/projects/openshift-dev-installer/zones/us-east1-d/instanceGroups/bfournie-capg-test-vlc9t-master-us-east1-d
> ```

Thanks. Pushed!

That's the same error as ci turned up. Let's see if this fixes it!

/test altinfra-e2e-gcp-capi-ovn

**Comment by patrickdillon** [comment]
nice, after a failure in the last run install has completed!

```
[36mINFO[0m[2024-04-25T21:26:34Z] Step e2e-gcp-capi-ovn-ipi-install-install succeeded after 53m47s. 
```

**Comment by patrickdillon** [comment]
capi e2es failed with:

```
: [Jira:"Networking / router"] monitor test service-type-load-balancer-availability setup expand_more 	11m20s
: [sig-arch] events should not repeat pathologically for ns/openshift-marketplace expand_more 	0s
: [OLM][invariant] alert/KubePodNotReady should not be at or above info in ns/openshift-marketplace expand_more 	0s
: [sig-instrumentation] Prometheus [apigroup:image.openshift.io] when installed on the cluster shouldn't report any alerts in firing state apart from Watchdog and AlertmanagerReceiversNotConfigured [Early][apigroup:config.openshift.io] [Skipped:Disconnected] [Suite:openshift/conformance/parallel] expand_more
: [sig-operator] an end user can use OLM can subscribe to the operator [apigroup:config.openshift.io] [Skipped:Disconnected] [Skipped:NoOptionalCapabilities] [Suite:openshift/conformance/parallel] expand_more
```

Running another e2e test to see which failures stick:
/test altinfra-e2e-gcp-capi-ovn

e2e failures shouldn't be a blocker for this PR, but we will need to determine if any of these failures are caused by the capi install process.

**Review by barbacbd — COMMENTED** [review]
/cc @bfournie 

/lgtm to me bob what do you think?

**Comment by bfournie** [comment]
The change seems fine, we're still getting the altinfra-e2e-gcp-capi-ovn failure how the the install succeeds, see https://github.com/openshift/installer/pull/8314#issuecomment-2082996014, but we can handle that in a follow-up.
/approve

**Comment by patrickdillon** [comment]
e2e failed due to concurrent modifications of iam policy:

> level=error msg=failed to fetch Cluster: failed to generate asset "Cluster": failed to create cluster: failed during pre-provisioning: failed to add master roles: failed to set project IAM policy: googleapi: Error 409: There were concurrent policy changes. Please retry the whole read-modify-write with exponential backoff., aborted

**Comment by bfournie** [comment]
@patrickdillon seeing some e2e failures due to oauth2. As @r4f4 pointed out the last time I updated capg, may need to keep the oauth2 pinned, see https://github.com/openshift/installer/pull/8153#discussion_r1524945069

**Comment by patrickdillon** [comment]
> @patrickdillon seeing some e2e failures due to oauth2. As @r4f4 pointed out the last time I updated capg, may need to keep the oauth2 pinned, see [#8153 (comment)](https://github.com/openshift/installer/pull/8153#discussion_r1524945069)

oh ok I see the replace in the provider. will fix tomorrow. firewall as I have it is not fixing the e2e. so let's tackle that separately.

**Comment by bfournie** [comment]
It looks like the service-type-load-balancer-availability test which was failing before is now passing after the healthcheck fix
`time="2024-05-01T22:50:28Z" level=info msg="response Body:{\"ProwJobName\":\"pull-ci-openshift-installer-master-altinfra-e2e-gcp-capi-ovn\",\"ProwJobRunID\":1785766397066874880,\"Release\":\"Presubmits\",\"CompareRelease\":\"4.16\",\"Tests\":[{\"Name\":\"[Jira:\\\"Networking / router\\\"] monitor test service-type-load-balancer-availability setup\",\"Risk\":{\"Level\":{\"Name\":\"High\",\"Level\":100},\"Reasons\":[\"This test has passed 100.00% of 21 runs on jobs ['periodic-ci-openshift-release-master-ci-4.16-e2e-gcp-ovn'] in the last 14 days.\"]},\"OpenBugs\":[]}],\"OverallRisk\":{\"Level\":{\"Name\":\"High\",\"Level\":100},\"Reasons\":[\"Maximum failed test risk: High\"]},\"OpenBugs\":[]}\n"`

**Comment by bfournie** [comment]
> > It looks like the service-type-load-balancer-availability test which was failing before is now passing after the healthcheck fix `time="2024-05-01T22:50:28Z" level=info msg="response Body:{\"ProwJobName\":\"pull-ci-openshift-installer-master-altinfra-e2e-gcp-capi-ovn\",\"ProwJobRunID\":1785766397066874880,\"Release\":\"Presubmits\",\"CompareRelease\":\"4.16\",\"Tests\":[{\"Name\":\"[Jira:\\\"Networking / router\\\"] monitor test service-type-load-balancer-availability setup\",\"Risk\":{\"Level\":{\"Name\":\"High\",\"Level\":100},\"Reasons\":[\"This test has passed 100.00% of 21 runs on jobs ['periodic-ci-openshift-release-master-ci-4.16-e2e-gcp-ovn'] in the last 14 days.\"]},\"OpenBugs\":[]}],\"OverallRisk\":{\"Level\":{\"Name\":\"High\",\"Level\":100},\"Reasons\":[\"Maximum failed test risk: High\"]},\"OpenBugs\":[]}\n"`
> 
> It looks like that result is coming from periodic-ci-openshift-release-master-ci-4.16-e2e-gcp-ovn. which is still on terraform. the capi presubmit is still failing the e2e: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_installer/8314/pull-ci-openshift-installer-master-altinfra-e2e-gcp-capi-ovn/1785766397066874880

That was from the alinfra test "`ProwJobName\":\"pull-ci-openshift-installer-master-altinfra-e2e-gcp-capi-ovn\"`.  The e2e test is still failing but it will be interesting to see what happens after oath2 is pinned. Anyway, once that is pinned we should be able to merge this and work on any other e2e failures in a separate PR.

**Comment by patrickdillon** [comment]
fixed oauth replace in 02fa61c58e86407126833a3ff869b44c0b0b422c

I removed the commit containing the attempted fix at the ingress e2e test failure. will follow up in a separate pr

**Comment by patrickdillon** [comment]
/test altinfra-e2e-gcp-capi-ovn

The previous runs had a build error which I missed locally because my cached binary was skipping the build. This resolves the build error but oauth2 is still unpinned. I still need to resolve that

**Comment by patrickdillon** [comment]
Install succeeded on the last run, but looks like there were CI scheduling issues that caused a lot of jobs to fail.

**Review by sadasu — COMMENTED** [review]
/lgtm

**Pull request merged**
